### ISSUE TITLE
CD32 Low-Res Quickstart Preset Resolution

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#100]
Firstly i'd like to say thankyou for your continued updates on this emulator. 

I tried the game Pinball Illusions CD32. When the Amiga CD32 logo spins at the beginning the first letter A is off the screen. Then in-game, the right side of the screen where the ball lane is is cut off (about 2cm ?) and a small amount from the top of the screen. When putting the table in hi-res mode with F10 there are weird artifacts on the balls etc. I know the CD32 had several resolutions up to something like 1280x1024.

I don't think that wireless joypads work yet as you know the custom controls can't be set but the keyboard works on this game.

(I'm new to these Github pages, how do I add the Bug/Enhancement symbols ?)

Thanks.

**Comment by midwan** [comment]
@blinkydoos 
Thanks for the feedback and welcome to Github! :)

The CD32 didn't have any "special" resolutions AFAIK, it was the same as the A1200 in that respect. It did have an extra chip named "Akiko", which was responsible for chunky-to-planar conversions, but no new resolutions.

This is most likely a bug regarding drawing of sprites, perhaps related to #64 

(regarding the labels, only authors of the project can set those)

**Comment by blinkydoos** [comment]
I checked the Android version of UAE4Arm and the CD32 preset is set at 384x256. It fits the Amiga CD32 logo nicely on the screen but the resolution seems like a custom lores. Maybe TomB used it for speed reasons ?

**Comment by blinkydoos** [comment]
It seems that the resolution needs to be increased for CD32 games (and possibly in general).

AMIBERRY SDL2
![cd32 amiberry sdl2](https://cloud.githubusercontent.com/assets/27903587/26446706/23bd38b6-413d-11e7-99fa-72d5bdb6f871.png)

UAE4ARM / AMIBERRY SDL1 (704x262)
![cd32 uae4arm 704x262](https://cloud.githubusercontent.com/assets/27903587/26446717/2fed61ce-413d-11e7-8fd6-7b0a93e4811d.png)

AMIBERRY SDL2
![illusions amiberry sdl2](https://cloud.githubusercontent.com/assets/27903587/26446745/4ffdd07a-413d-11e7-9a66-ff992fdccefa.png)

UAE4ARM / AMIBERRY SDL1 (704x262)
![illusions uae4arm 704x262](https://cloud.githubusercontent.com/assets/27903587/26446774/63ad0cb2-413d-11e7-95e4-5617155b6e85.png)

NOTE : The screenshots were captured on Android UAE4Arm. I don't have a camera (that works properly) so I simulated what I see in Amiberry using Android UAE4Arm.

**Comment by blinkydoos** [comment]
When using the CD32 FMV rom and load Cannon Fodder CD32 (ISO) the intro is squashed (Amiberry resolution used 640x256). It looks correct if the resolution is set to 320x216. Must be a scaling issue. I noticed that the CD32 quickstart preset is set to 384x256 ?!? which looks bad for CD32 games. Probably intentional by TomB to keep the speed up on the Pandora.
