### ISSUE TITLE
Allow custom mapping for more than one controller

### ISSUE THREAD

**Issue by rsn8887** [midwan/amiberry#102]
Currently, there is no way to custom map additional controllers for three or four player gameplay. It would be nice to allow any controller input to be custom-mapped to any amiga side keyboard keys or joystick input.

A proposed solution would be to add one drop down selector to the custom controls menu that allows selection of which controller to custom map.

After selection of which controller to custom map, then all the other custom mapping dropdowns would change to display the mappings for that controller,

The mapping options should contain all Amiga-side keyboard keys, as well as 
Amiga Joystick 1 up/down/left/right/button1/button2
Amiga Joystick 2 up/down/left/right/button1/button2, so that mapping to either Amiga joystick 1 or 2 can be done quickly.

This way we could map for example two controllers to joysticks 1 and 2 and a third controller to "cursor keys + space" and a fourth controller to "numkeypad plus enter." That would allow us to play multiplayer games like Masterblaster, Spacetaxi 3 etc. with four controllers!

**Comment by midwan** [comment]
This is coming in the future, as we've added support for Parallel Port joysticks (so you can have up to 4). Not ready yet, but soon...

**Comment by HoraceAndTheSpider** [comment]
This is all covered by the custom panel on the dev branch now.

Inputs 3-4 use parallel ports by default but can be remapped for keys... see: Indy Heat etc
