### ISSUE TITLE
Flink [CD32] Version - Glitchy

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#105]
Hi,

I cannot create a decent config for this game. Can anyone help please? 

- The game has background graphic glitching with fast copper "on". 
- When fast copper is removed game runs way too slow. 
- Circle button on the PS3 Controller moves the screen up and down and gfx glitch again.

Long story short, I dare say this game has issues with this emulator? Can anyone else check it please?

**Comment by CypherXG** [comment]
I've testet the Controllerbuttons with a PS3 Controller.
In the Src Code there must be a Bug, because when i test the Controller with Linux all the Buttons are correct with the Source Code.
But Yellow, Green, Select etc. are not reconized.
Only Red, Blue, Digital Left, Right, Up, Down, the analog Directions and Play are working.

**Comment by ransom1122** [comment]
with this in the config **joyport1mode=cd32joy** Everything works expect blue (Circle button on PS3 controller)

with this in the config **joyport1mode=djoy** only 3 colored buttons work.

**Comment by CypherXG** [comment]
There is somthing wrong in the Src Code.
I try to found the Error... because with some modification i can use Select etc. but not all Buttons...

**Comment by midwan** [comment]
Fast Copper is basically a speedup hack, so it's expected that sometimes you may have glitches when using it.

With the latest update, the speed is improved quite a lot. However, I can still not start playing the game with the default settings, as no button input seems to be recognized from my controller (even if I select keyboard mapping as CD32 controller, is still doesn't work).

I'm not sure if it has to do with the specific version of the game I've been testing though.

**Comment by ransom1122** [comment]
Great news about the speed increase in the latest version...

Regarding controls.. You cannot get any input with any controller ?? I could get input with controller on current version of Amiberry.

**Comment by ransom1122** [comment]
To update. This game is still buggy on v2.14

**Comment by midwan** [comment]
This is now fixed in `dev`.
The `dev` branch will be merged into `master` as soon as beta testing is complete, so we can close this issue for now.
