### ISSUE TITLE
CarlLewisChallenge WHDload is missing from Emulation Station?

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#109]
Hi,

I am comparing my games folder with the games listed in EmulationStation and have noticed that **CarlLewisChallenge** is missing from the list. No idea why?

The game is located on the pie's sdcard here
/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad/CarlLewisChallenge

Config file is located here;
/home/pi/RetroPie/roms/amiga/Carl Lewis Challenge.uae

I renamed the uae file to CarlLewisChallenge, Then the game is shown in EmulationStation and works.

I also tried using spaces like this **Carl Lewis Challenge** as the whdload game folder and uae file also editing the uae file inside looking like this;

filesystem2=rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad/**Carl Lewis Challenge**/,0
uaehf0=dir,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad/**Carl Lewis Challenge**/,0

;filesystem2=rw,DH2:HDFGame:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad/**Carl Lewis Challenge**,32,1,2,512,50,,uae
;hardfile2=dir,rw,DH2:HDFGame:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad/**Carl Lewis Challenge**,32,1,2,512,50,,uae

But that won't show in EmulationStation.

Keeping it all without spaces like this **CarlLewisChallenge** works but it doesn't look like all other entries where there are spaecs between each word. Is there any way to make this happen?

**Comment by blinkydoos** [comment]
This isn't related to Amiberry.

**Comment by ransom1122** [comment]
@blinkydoos, Where do we post these topics then?

**Comment by blinkydoos** [comment]
I'm not sure. It looks like you're using some custom loader judging by the paths.

**Comment by ransom1122** [comment]
I used Horaces youtube tutorial downloaded all games from his site. All scanned except for this game. So i added it in manually. But no game description?

**Comment by midwan** [comment]
This is not really related to the emulator itself, so I'm closing it.
