### ISSUE TITLE
Floppy drive sounds (optional)

### ISSUE THREAD

**Issue by ariath** [midwan/amiberry#11]
Hi all!

Well, my suggestion is pretty simple: Would be possible to add support for floppy drive sounds like WinUAE ones?

I would love hearing my Pi like my old A500 when the floppy was loading :3.

See ya!

**Comment by midwan** [comment]
We can certainly take a look at this one, but I'd prefer put more priority on fixing the bugs first. :)

**Comment by tklicki** [comment]
+1

**Comment by kenjara** [comment]
I would like to see this too. 

I miss those sounds while waiting for my games to load. :)

Thanks!

**Comment by CypherXG** [comment]
Is it possible to add? Most code is a
Brings Amiberry more Amiga feeling.... :-)

**Comment by midwan** [comment]
Yes, it's possible. I just didn't spend much time on this one yet. :)

**Comment by kauffy** [comment]
I'm new to Amiberry, but this is a HUGE missing for me-- I thought it was broken, as UAE has these sounds.

The floppy sounds and scanlines are both things that I think are pretty crucial for an "authentic" Amiga experience. :)

**Comment by MrNoHolster** [comment]
Really hope this feature can be added! Love the Amiberry experience and this would make it complete. :)

**Comment by midwan** [comment]
This is now fully implemented in `dev` - it will be merged into `master` when it's tested to be stable enough, since it's part of more changes in the Sound handling. :)
