### ISSUE TITLE
gamelist.xml - is mine corrupt / How to edit manually?

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#110]
When I quit Emulation Station I get this error;

![1](https://cloud.githubusercontent.com/assets/28079950/26443394/85455e40-417b-11e7-9bdf-0e5199e4731e.jpg)

My gamelist is located here;

**/opt/retropie/configs/all/emulationstation/gamelists/amiga/gamelist.xml** - File Size (37,480kb)

Also if you view gamelist.xml in a text editor should I be seeing all game entries shown in Emulation Station?

I would love to see a manual guide on how to add a games entry including game description, player, features, etc etc with the gamelist.xml. I tried to manually copy & paste an existing entry and edit it to a new game, but it won't show in Emulation Station. I can only get the covers without info to show, like this;

![2](https://cloud.githubusercontent.com/assets/28079950/26443468/d9046dbe-417b-11e7-94ed-684c19320402.jpg)

**Comment by blinkydoos** [comment]
This isn't related to Amiberry.

**Comment by ransom1122** [comment]
@blinkydoos Where do we post these issues then?

**Comment by CypherXG** [comment]
This is Retropie....

**Comment by midwan** [comment]
Not related to the emulator, so closing this one...
