### ISSUE TITLE
International Karate + / Graphic Issues

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#111]
Hi,

This game has constant Graphic problems on the players shadows and lower part of the screen when players fall. Can anyone see if they can figure out a working config for this that may fix this issue please?

It was hard to take a photo as the glitch flickers very fast. but here is it;

![3](https://cloud.githubusercontent.com/assets/28079950/26443839/587349e8-417d-11e7-9b0e-79cdaf9433f1.jpg)

**Comment by blinkydoos** [comment]
The latest WHDLoad version of IK+ (v1.7) seems to work fine set at 25MHz, no graphic glitch but no sound on the bonus stage. If you change the MHz then the sound keeps cutting out.

**Comment by ransom1122** [comment]
That did not work for me, but i tried 7MHz, and that works perfect. No graphic glitches, and also has sound in the bomb bonus stage.

**Comment by blinkydoos** [comment]
Out of interest, what version does it say your IK+ is ? That graphic glitch that you showed happens on the old version. It doesn't do that on mine.

**Comment by ransom1122** [comment]
Cant check at the moment.  But these are the whdload games downloaded from Horaces whdload set games on his site.

**Comment by blinkydoos** [comment]
No worries, let me know when you have the time. Just curious, because as I said before, that graphic glitch happened on an older version which probably means there are a lot more outdated versions in his "pack". I use the collection from Retroplay's folder which is fully up to date and he corrected a lot of errors.

**Comment by ransom1122** [comment]
Can retroplays games just overwrite horaces without causing complications? Ill let you know if I had the old version tomorrow thx.

**Comment by ransom1122** [comment]
@blinkydoos The version I had was IK+ v1.5.

Now I am debating wether I should update the game to the latest v1.7 because 1.5 is working perfect at 7MHz. And what you say v1.7 has sound issues on the bonus stages.

Did you manage to get a stable config on IK+ v1.7?

**Comment by blinkydoos** [comment]
I thought I recognised the glitch. v1.5 came out in 2001 and wasn't updated to v1.6 until June 2016 so I imagine you have a lot of outdated games.

If v1.5 works great for you then I would keep it, I've only quickly tried v1.7 and 7MHz seemed to work also for the bonus stage but when I started a new game the sound kept cutting out. There is an option to completely skip the bonus stages though.

**Comment by ransom1122** [comment]
Ok, interesting...

All the whdload games were from horaces download collection. So I guess it would be wise to replace all the games with Retroplays newer versions at some stage anyway. Thx for testing :)

**Comment by blinkydoos** [comment]
I have been playing some more and it seems that at 25MHz the sound starts cutting out as well after a while. The latest version definitely needs cycle accuracy.

**Comment by blinkydoos** [comment]
The ADF version on A500 works perfect. And if you notice the WHDLoad version intro the multi-coloured guys fighting around the IK+ logo etc. are going warp speed, it works correctly with the ADF, and also the stars around the sensei.

**Comment by HoraceAndTheSpider** [comment]
The download collection I provided is the RetroPlay packs btw. They just are 18 months old or something now, so some games need updating.

**Comment by ransom1122** [comment]
Thanks for the info

**Comment by CypherXG** [comment]
Runs bei me with full speed.
With Jit off runs without GFX Errors.
With Jit on i have the same Errors.

**Comment by blinkydoos** [comment]
@HoraceAndTheSpider Retroplay remade them all a couple of months ago and apparently corrected a lot of tooltype errors etc. Before I think they were made by KillaGorrila ? and from the WHDowload site (don't quote me on that though :) )

@CypherXG There are no graphic errors on v1.7 only some sound issues (depending on the speed you set). It probably needs cycle exact as most people use these on a real Amiga so wasn't corrected. I think JIT is only worth using on 3d games and only works when the CPU is set to Fastest.

**Comment by midwan** [comment]
Cycle accuracy is in the TODO list for future versions of the emulator, but it requires a big update on the CPU emulation routines (=it takes time).

I'll be closing this one then, as I believe it has been addressed. Let me know if you feel it hasn't...
