### ISSUE TITLE
Xenon 2 2Disk WHDLoad

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#112]
I cannot seem to get past the screen after you press fire on the title screen, it says Loading game.. and freezes/stops on a blak screen. You can quit to gui, but thats a bout it..

 Can anyone check this please to see if the game is working on Amiberry?

**Comment by blinkydoos** [comment]
Correct, this version doesn't work. The WHDLoad 1Disk version works fine and still contains the music intro.

**Comment by ransom1122** [comment]
Thanks I will replace the 2disk with the 1disk. Thanks

**Comment by ransom1122** [comment]
I used **Xenon2_v1.9_1Disk_2234** WHDLoad and it freezes at the same stage of the 2disk version, after the title screen where it says loading games. Messing with various configs, It will either stay frozen there, or go black screen after the loading game prompt at the title screen.

What is your config for this game?

**Comment by blinkydoos** [comment]
Works fine on mine. Did you copy the 1disk version over the top of the 2disk version ? If so, you will have 2 slave files and probably causing conflict. Try deleting the 'Xenon22Disk.Slave' and the 'Disk.2' file.

**Comment by ransom1122** [comment]
My bad, i forgot to change the config from Xenon22Disk to Xenon21Disk. 

All good working perfectly now. Thank you
