### ISSUE TITLE
War Zone (Core Design) - Graphic Problems

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#113]
This game has major graphic problems. The barrels at the start have black backgrounds, when you shoot, the bullets create a path of black graphic box images across the screen.

I have tried several version of both WHDLoad and ADF's 

WarZone_v2.0_CoreDesign_0598.lha
WarZone_v1.0_Core_0598.lha

War Zone (1991)(Core Design)[cr FLT].adf
War Zone (1991)(Core Design)[cr FLT][f AGA Galahad].adf

And they all seem to have the graphic issue, wether its AGA or OCS, which makes me believe this may be an Amiberry issue.

![20170528_115039_resized](https://cloud.githubusercontent.com/assets/28079950/26525512/9193c42a-439c-11e7-86a9-518b75a56d04.jpg)

Can anyone investigate this please.

**Comment by ransom1122** [comment]
Anyone tried this game yet?

**Comment by Voljega** [comment]
Tried it but crashes on entering first level, must be the 32 bits thing again

**Comment by ransom1122** [comment]
Such a shame warzone is a good game.

**Comment by midwan** [comment]
I'll be adding this one in the range of test titles for the emulator, to see if we can fix it.

**Comment by Voljega** [comment]
Reproduced it too after adding 24-bit adressing in my configuration
Tried to modify the sprites parameters to see if it would change anything, it didn't

**Comment by midwan** [comment]
Interesting development:
- In the latest dev snapshot, the graphical glitches are gone (yay!), but the game does not respond when starting the level (nay!). 

Although the intro is shown normally, joystick input works to start the game, when it actually does start the level, everything seems "frozen".

**Comment by Voljega** [comment]
But as the glitches appears in the level, how can you see that they are gone if you can't start the level ?

Also on my side the 24 bit thing must be checked for the game to start if I remember well

**Comment by midwan** [comment]
@Voljega The level does start, I just can't move the sprite. :)

Evenything seems to be drawn correctly, but I don't know if moving through the level has any issues later on of course.. :) I'll try some more tests.

**Comment by Voljega** [comment]
Ok I ser... Well then good luck I guess ;)

**Comment by ransom1122** [comment]
The bug occurs only when you move.

**Comment by midwan** [comment]
@ransom1122 Interesting, then we have something to look into...

**Comment by nemo93** [comment]
Issue added to #122.

**Comment by ransom1122** [comment]
Game is now working on both v2.12 & v2.14
