### ISSUE TITLE
Multiple ADF Inside ZIP - Is it working?

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#115]
Hi,

I have multiple ADF game Shadow of the Beast II inside a ZIP file, Emulation Station picks it up and allows me to launch it. But it will only play the first #1 ADF. 

After the intro it asks to switch ADF #2 into DF0, The only way this is possible is if the 2 ADF's are extracted out of the ZIP, then PRESS F12, and manually select Disk #2 into DF0:  This works but it defeats the purpose of having ADF's inside ZIPS?

Is there a way to switch only the ADF disks inside a launched ZIP? Because when I press F12, I see no ADF entries in either DF0 or DF1 after launching a multiple adf games inside a ZIP file.

If not then we will have multiple Entries of the same game in Emulation Station.

I am aware There are WHDLoad versions of these games and YES I will use these instead of the ADF versions, but I am intrigued to figure out how the Launching of ADF's inside ZIPS actually work?

If I have the multiple disk game Cruise For a Corpse this works inside ZIP, and Amiberry swaps Disks automatically when required. :) 

Cruise for a Corpse (1991)(U.S. Gold)[cr SKR](Disk 1 of 5).adf
Cruise for a Corpse (1991)(U.S. Gold)[cr SKR](Disk 2 of 5).adf... and so on

Cruise for a Corpse [ADF].zip = Working fine :)

If there is no way of achieving this, is the only solution to have games th

**Comment by blinkydoos** [comment]
I haven't really used this emulator for a while now and i'm not even sure it's still being worked on (I recently bought a mini PC that's smaller than the original XBOX for dirt cheap (£90) and it runs WinUAE with full Cycle Accuracy perfectly, Core i3) . Your problem is again with Retropie and not Amiberry. Shadow of the Beast II only accesses DF0: The multiple disks in zips is only useful on games that access multiple drives. I think the only option would be to unzip them or zip them separately with GZip.

**Comment by ransom1122** [comment]
I was dreading that. 
What exact model is your mini pc?
Can you hide disk 2 or disk 3 entries in emulation station if you had multiple entries of the same game?

**Comment by blinkydoos** [comment]
It's only a refurbished Dell ex-business. Core i3-3225 (3.3GHz), 8 GB Ram, Intel HD4000 Graphics. It's very small and runs great on the highest accuracy settings.

I don't know much about Retropie's ADF detection script, I know it's only basic though. I know it looks inside zip files for multiple ADF's but like you say, if the game asks you to insert the next disk into DF0: then you can't. You could compress the ADF's to single ADZ files with GZip and stop emulationstation from detecting the filetype then only add disk 1 etc. to your gamelist.xml.

**Comment by ransom1122** [comment]
Regardless looks like mullti disk amiga games that require **only** 1 Disk to work, therefore disc swapping is required for the game to work for example;

Shadow of the Beast II (1990)(Psygnosis)(Disk 1 of 2)[cr Angels].adf
Shadow of the Beast II (1990)(Psygnosis)(Disk 2 of 2)[cr Angels].adf

Disk 2 must be swapped into DF0: after the intro. 

Disk 2 will always be shown in Emulation Station, unless there is an easy way to **hide** Disk 2 from Emulation Station?

**Comment by Voljega** [comment]
There is in recalbox, not sure in retropie

**Comment by midwan** [comment]
Emulation Station is not part of Amiberry, this is part of RetroPie... Not sure if we can help from our side on this, maybe it's better if this issue is brought to the RetroPie crew?
