### ISSUE TITLE
Amiberry & CDTV Images

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#116]
Hi,

Finally got some time to check out CDTV game images and Amiberry, and for the life of me I cannot get them to boot? When I launch it from ES, It remains on the Kickstart v1.3 Kick screen. Seems to be a kickstart problem?

Game in question is Wrath of the demon which is located in this folder

**/home/pi/RetroPie/roms/amiga-data/Games_CDTV/Wrath of the Demon (CDTV)**

Wrath of the Demon (USA).bin
Wrath of the Demon (USA).cue

And my UAE file which is located in 

**/home/pi/RetroPie/roms/amiga**

Wrath of the Demon (CDTV).uae (Attached UAE file as TXT for you to view)

[Wrath of the Demon (CDTV).txt](https://github.com/midwan/amiberry/files/1050125/Wrath.of.the.Demon.CDTV.txt)

in BOLD below are what I believe which kickstart is required to boot CD32

kickstart_rom_file=/home/pi/RetroPie/BIOS/Amiga/**kick13.rom**
kickstart_rom_file_id=1E62D4A5,CD32 KS ROM v3.1
kickstart_ext_rom_file=/home/pi/RetroPie/BIOS/Amiga/**cddtvext.rom**
kickstart_ext_rom_file_id=87746BE2,CD32 extended ROM
flash_file=/opt/retropie/emulators/amiberry/cd32.nvr
floppy0=
floppy0type=-1
floppy1=
floppy1type=-1
floppy2=
floppy3=
cdimage0=/home/pi/RetroPie/roms/amiga-data/Games_CDTV/Wrath of the Demon (CDTV)/Wrath of the Demon (USA).cue,image

When I boot WINUAE on my PC in CDTV Quickstart mode you can see **Kick1.3** and the extended rom 
**cddtvext** as default which I replicated on Amiberry  above.

![1](https://cloud.githubusercontent.com/assets/28079950/26759036/d03a6754-4934-11e7-8eb3-c1ac5490decc.jpg)

There is no CDTV "Built in" bootup with Amiberry so I am not quite sure if or how CDTV Game images boot?

Obviously WHDLOAD_CDTV games work, though these run with Kick31 as they are HD installable WHDified versions.

Please help :)

PS Looks like there is no support for **cdtv.nvr**
I added this line in the uae file

flash_file=/home/pi/RetroPie/BIOS/Amiga/cd32.nvr

added the file **cdtv.nvr** in path **/home/pi/RetroPie/BIOS/Amiga**

And still get Kick 1.3 white screen and CDTV game won't boot?

If I use a CD32 built in quickstart with Amiberry using CD32 Kick, and CD32 Ext Kick, I get a Yellow Screen, then Black screen when I launch CDTV Image games.

On the Amiberry website I do not see CDTV to be a supported platform?

**Amiberry is an optimized Amiga emulator for the Raspberry Pi model 1, Zero, 2 and 3, that brings you the highest performance Amiga emulation. Be it a classic A500, A1200, CD32 or up to a high-end model equipped with a 68040 and a graphics card, we’ve got you covered.**

**Comment by CypherXG** [comment]
CDTV Extend Rom is not supported
Only CD32 CDROM booting is working.

**Comment by ransom1122** [comment]
OK.

Thanks for letting me know. 

Any idea if it will be implemented on future updates of Amiberry?

**Comment by midwan** [comment]
@ransom1122 
CDTV support is not there yet, this will come in a future version while merging with newer versions of WinUAE hopefully.

**Comment by 2play** [comment]
@midwan  HI Demitris
What is the latest on CDTV Amiberry support?

**Comment by midwan** [comment]
@2play 
The CDTV-specific bits are not implemented yet, but lots of progress was made recently in shared WinUAE core emulation updates, which makes things easier for the future. We're getting there slowly... :)

**Comment by 2play** [comment]
@midwan Thank you for quick reply and update!
Ive been playing around today. the lha cdtv andromeda i tested was booting with glitches but not the cue etc
But good news! Thank you again!
