### ISSUE TITLE
Write Protect enable

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#117]
Does Write Protect for df0 enable work? I cant tick the box  or can i find the command in a config to enable it?

I have a ADF Game that requires write protect enabled but i cant get it to work on Amiberry as it forced write disabled.

**Comment by midwan** [comment]
@ransom1122 Have you tried with a Zipped ADF or an uncompressed one?

There is a difference in behavior between those two, only uncompressed ADFs can be written to - zipped ones remain write protected, at least at the moment.

**Comment by blinkydoos** [comment]
If the ADF is zipped and you tick 'write enable' then a differences file is saved to the savestates folder.

**Comment by midwan** [comment]
@blinkydoos that's right, thanks

**Comment by ransom1122** [comment]
All good seems to be working..
