### ISSUE TITLE
Mappings, when keyboard and mouse are not available

### ISSUE THREAD

**Issue by woozer** [midwan/amiberry#118]
I have a gameboy dmg: http://www.sudomod.com/forum/viewtopic.php?f=25&t=2508
I am trying to map buttons and dpad, but have been unsuccessful. Is the emulator using a dpad and buttons feasible?

**Comment by midwan** [comment]
It should be in the new version being prepared. The older (SDL1) version has several things hardcoded, but I was working towards a more flexible solution with the new version.

However, the new version is not ready for release yet. You may have to wait a bit for that, unless you're ok compiling and running experimental versions (in which case, feel free to grab it from the sdl2 branch).

**Comment by midwan** [comment]
@woozer Me and @HoraceAndTheSpider (mostly) are working on a complete overhaul of the controller mapping features, so this will probably be addressed with that.

**Comment by midwan** [comment]
This is also fixed after the recent merge from @HoraceAndTheSpider "controller" branch
