### ISSUE TITLE
A2065 Network Card support

### ISSUE THREAD

**Issue by jamesy0ung** [midwan/amiberry#1185]
I'd like to see A2065 network card support in Amiberry as this will allow networking under Amiga Unix (Amix)

**Comment by midwan** [comment]
@jamesy0ung 
We can add that, but from what I know Amix also requires an MMU to function, which is not implemented in the `master` branch. There is a WIP `preview` branch which includes the latest WinUAE code, including MMU support, but JIT does not work yet there.

So it makes more sense to implement this in the `preview` branch only for now, to have any chance of working with Amix.

**Comment by midwan** [comment]
Implemented in the `preview` branch. For now, there's no SLIRP support, though that may come later.
It shows up correctly under ShowConfig, but I can't say if this will work with Amix or not...
