### ISSUE TITLE
Project on hold ?

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#120]
Hello there seems to not have been any commits for more than the past three months.

Is the project on hold, or worse, dead ?

**Comment by midwan** [comment]
@Voljega 
It's not dead... :)

It was put on hold due to a series of family tragedies that occurred. I'm slowly getting back to it and should resume normally by next month or so...

**Comment by Voljega** [comment]
Ok thank you for your answer and sorry for your family tragedies.

See you soon :)
