### ISSUE TITLE
Mapping Mouse to Analog Stick

### ISSUE THREAD

**Issue by darkuni** [midwan/amiberry#124]
I'm sure this has been brought up somewhere at some point - but I'd love to have the option for the controller to be usable as a mouse; that is mapping controller buttons to mouse clicks and the right analog stick to be mapped to mouse movement.

Thanks - great work!

**Comment by midwan** [comment]
@darkuni Thanks for the suggestion.
I believe it has been mentioned before indeed, this will be implemented once we fix/improve the custom mapping of controls in general.

**Comment by ransom1122** [comment]
Can we map left and right mousebutton clicks with left and right trigger with the current version of Amiberry?

**Comment by blinkydoos** [comment]
https://github.com/midwan/amiberry/issues/119

**Comment by HoraceAndTheSpider** [comment]
It is funny, this function already works in Amiberry , so this could be closed.

If you set your joystick to the input and also change the input mode to "mouse" in the Config, the man analogue sticks will be mapped to the mouse control.

There is also a test version available which allows this to be done in an improved way with the new "mousemap" feature.

The next full release will have complete functionality for this.

**Comment by midwan** [comment]
This is fixed with the merge from @HoraceAndTheSpider "controller" fork.
