### ISSUE TITLE
Cd rom drive mount?

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#125]
Hi.

Is the cd mount for Amiberry only available for cd32 only? I have a hdf + cd image. After creating a 1200 quickstart. Workbench starts the hdf is obviously detected but i dont see anything mounted in cd drive even although i mount the amiga cd image.
The cd drive tab in gui shows nothing even after i re mount the cd image and reset Amiberry?

Game is T-zer0 AMIGACD + HDF found here.
http://eab.abime.net/showthread.php?t=86983

Winuae plays it. Amiberry only plays the HDF therefore lacking the cd audio from the cd image.

**Comment by blinkydoos** [comment]
Currently, it's only for CD32. It's also been asked here (Issue https://github.com/midwan/amiberry/issues/37)

**Comment by ransom1122** [comment]
Is it on the todo list at all?

**Comment by blinkydoos** [comment]
No idea, sorry. If you ask TomB on the Pandora forums i'm sure he'll add it.

**Comment by HoraceAndTheSpider** [comment]
It's probably not that hard to add, I think there is a check prior to mounting that the system is in CD32 "mode"

I can have a look at removing that check and see if that works

**Comment by ransom1122** [comment]
That would be good.  A small little unlock like that can open a big door with Amiberry. Thanks

**Comment by midwan** [comment]
Closing this since it's a dupe of #37
