### ISSUE TITLE
Raspberry Pi3 Install BT 

### ISSUE THREAD

**Issue by JJ-ami** [midwan/amiberry#126]
Rassberry pi 3  add packet to
install bluetouch for any joystick control bluetouch ps3, ps4 or wiimotion
tank´s

good work

**Comment by HoraceAndTheSpider** [comment]
Is "bluetouch" a typo for Bluetooth?

Bluetooth PS3 pads are supported by the Pi with RetroPie installed. This does not form part of Amiberry.

Some PS4 pads will work natively on retropie and newer ones require a PS4 USB dongle.

Amiberry future release will add support for all joystick-input  controllers detected by the system and they will be mapped according to the RetroPie cfg files.

**Comment by JJ-ami** [comment]
ok... i don´t like retro.pie
is a big image, only need Amiberry is a lite image, just need to emu amiga
tank´s

**Comment by HoraceAndTheSpider** [comment]
Hi,  we can take this into consideration and provide some kind of similar config file for universal controller support on the amiberry image i am sure :)

**Comment by midwan** [comment]
@JJ-ami 
@Fourdee 
I think you might prefer an alternative distro than RetroPie then, perhaps something like DietPi?
If you'd like Bluetooth support, it should be enabled in the distro you're using, as it's not really part of the emulator itself. If the underlying system can see your game controller, the emulator can use it.

Also, please keep in mind we're working on a complete overhaul of the controller mapping features in the emulator, so good things are coming! :)
