### ISSUE TITLE
New SDL1 build new features quick test

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#128]
I just did a very quick test on the new SDL1 build. For those who are just copying over the new binary also need the 'data/quickstart.ico' otherwise it won't run.

I tested Cannon Fodder CD32 and it now plays the FMV intro (a few slight audio hiccups).
(You need the 'CD32 Full Motion Video Cartridge ROM v3.1 r40.030 (256k).rom' or similar)

I tested the Action Replay (Mk III) and I got the Action Replay Splash Screen when resetting but i'm not sure what the 'Activate' button is (my mini keyboard may not have the correct key).
(You need 'Freezer - Action Replay Mk III v3.17 (256k).rom' or similar)

The Intro to Super Stardust now plays (superhires mode).

One note, if you select the CD32 Quickstart preset, it sets the screen resolution as low-res 384x256.

Joypad not detected !

As I said, just a very quick test, I might test some more later.

**Comment by CypherXG** [comment]
Can u pls send me the src to my email: cypherxg@gmx.de ?
I want to test your beta.... ^^
Regards
Markus

**Comment by blinkydoos** [comment]
It's not mine, Midwan posted the binary here -

https://github.com/midwan/amiberry/releases/tag/2.5b

**Comment by midwan** [comment]
@blinkydoos Thanks for testing and the feedback! :)
@CypherXG Please keep in mind this is work-in-progress at the moment, more changes are coming before the final version will be released.

**Comment by blinkydoos** [comment]
Is there a reason why my gamepad isn't detected in the latest beta ? It just says 'none' in the Input/Port1 tab. It worked fine in the previous version. I am using a Gamesir G3s in X-Input mode using a wireless dongle (I find Bluetooth in general to be unreliable and laggy). It gets detected as an X-BOX controller. Did you disable gamepads in the Beta until the Custom Controls have been fixed ?

**Comment by midwan** [comment]
@blinkydoos It's a known bug, will be fixed soon... :)

Does it work even though it doesn't show correctly in the GUI?

**Comment by blinkydoos** [comment]
No. If I leave it on 'none' then when going back to the GUI it's changed to 'dpad as joystick' but still doesn't work. I also tried 'dpad as CD32' and no joy. If I set it to 'dpad as mouse' it goes back to 'joystick' or 'CD32'.

**Comment by midwan** [comment]
@blinkydoos Ah ok.
@HoraceAndTheSpider is working on a complete re-implementation of the controller code, but we'll need some time before it's ready.

**Comment by blinkydoos** [comment]
Thanks for confirmation.

**Comment by HoraceAndTheSpider** [comment]
Try building my controller branch. "Dpad as..." options have all been removed now as they relate to the Pandora version.

There are still a few issues/snags to resolve with respect to single controller inputs as far as I know however

**Comment by HoraceAndTheSpider** [comment]
FYI I am not surprised if there are issues with this part on the sdl branch , due to the Pandora code that have been ported. Most of this I think I have fixed or cleaned now, except the custom mapping which I am still working on.

**Comment by blinkydoos** [comment]
@HoraceAndTheSpider I just built your version and gave it a quick test (it's 4mb bigger than Midwan's ?) For my controller that gets detected as X-BOX I have no 'Button 1'. 

'B' is joy button 2
'Y' is Up

Also, 'Port 0' says 'none' but mouse still works though.

**Comment by HoraceAndTheSpider** [comment]
Can you post your retroarch cfg file please. This setup aligns to that so those sound correct. 

I am not sure if you are saying button 1 doesn't work or...? 

No work has been done on the mouse side of stuff yet.

**Comment by HoraceAndTheSpider** [comment]
Keep in mind that the alignment of fire to the "x" position (PlayStation equivalent) is correct as this is where the red button is on a cd32 pad

**Comment by HoraceAndTheSpider** [comment]
if "Y" is the left-hand button, that is also correct hat it is mapped to "jump" in joystick mode, for use with platformers etc

**Comment by blinkydoos** [comment]
This is my button layout

...Y
X...B
...A

jstest reports these numbers as my buttons -

Gamesir G3s (X-Input Mode)

A = 0
B = 1
X = 2
Y = 3
L1 = 4
R1 = 5
L2 = 6
R2 = 7
Select = 8
Start = 9
Home = 10
L3 = 11
R3 = 12

**Comment by HoraceAndTheSpider** [comment]
Thanks for this ... I will check but I think the above doesn't match with RetroArch's labelling. (a/b swapped for example)

However , this doesn't matter you can already fix this :)

In the paths panel, you will see where the joystick cfg is read from. 
Set this to a an Amiberry specific sub-folder, copy your retroarch cfg in there and swap the button numbering then it will fix any swapped numbers.

I will post some Pictures to show how the default works. :)

**Comment by HoraceAndTheSpider** [comment]
An no, it is universal retroarch mapping, not just PlayStation pads, I have tested it with others also , which is why seeing your retroarch cfg would help greatly

**Comment by HoraceAndTheSpider** [comment]
looking at this, your A/B and X/Y buttons are inverted from the standard RetroArch layout:
![retroarch-snes](https://user-images.githubusercontent.com/567602/31307958-b55244e6-ab65-11e7-9e58-96c27ad7cf05.png)

Are you using RetroPie, or some other setup?   This is very easily fixed using a .cfg file

**Comment by blinkydoos** [comment]
Yes, I am using RetroPie. My controller has the same button layout as X-BOX. In X-Input mode it is detected as 'Microsoft X-Box 360 pad' in the ports panel.

![gamesir g3s](https://user-images.githubusercontent.com/27903587/31308041-47bb6e6a-ab67-11e7-8a0a-cace3c801e88.jpg)

**Comment by HoraceAndTheSpider** [comment]
Yes, as i said, this labelling differs from what is stated in RetroArch (see SNES pad picture, which is the labelling they use) ... without posting the full .cfg file from /opt/retropie/configs/all/retroarch-joypads  it will be impossible for me to advise/diagnose any further

**Comment by blinkydoos** [comment]
I have 2 configs because my joypad can do D-Input and X-Input.

[Gamepad Configs.zip](https://github.com/midwan/amiberry/files/1364637/Gamepad.Configs.zip)

**Comment by HoraceAndTheSpider** [comment]
Amiberry will use the one that matches what it shows in the input panel ; so i assume Microsoft X-Box 360 pad.cfg from what you've said above?

**Comment by blinkydoos** [comment]
Yes. I use the X-Box one because you can also map the Home button. The other config doesn't allow it.

**Comment by HoraceAndTheSpider** [comment]
Thanks.  Have you checked that you have set the controller path option in the Paths panel to:  /opt/retropie/configs/all/retroarch-joypads  ?   (or is it still set to the default amiberry/controllers/ ? You may need to change this)

**Comment by blinkydoos** [comment]
It's at the default 'amiberry/controllers/'. So if I change the path to '.../retoarch-joypads' or put the configs in the 'amiberry/controllers/' directory it should work ?

**Comment by HoraceAndTheSpider** [comment]
it will, but looking at your .cfg file you are using the layout/naming designated by yur joypad, and not the one designated by RetroPie.

As i said earlier, you may prefer to copy your .cfg to /amiberry/controllers/ and make an amiberry specific edit: (the following lines should fix your layout issues:

```
input_a_btn = "1"
input_b_btn = "0"
input_y_btn = "2"
input_x_btn = "3"
```

**Comment by HoraceAndTheSpider** [comment]
in theory you should have been using the 'default' layour, so i will look into why the Fire button wasnt working for you.

**Comment by blinkydoos** [comment]
OK. So I put the X-BOX config in 'amiberry/controllers' and swapped the buttons in the config and now it works as described, Thanks. Will I always have to do this in future versions or will you add 'X-BOX pad' compatibility to Amiberry ?

**Comment by HoraceAndTheSpider** [comment]
Glad it works now!

There is no "specific pad" support in amiberry anymore (i removed the only one - the hard-coded PS3 controller)  , there is only this host-mapping function (using RetroArch cfgs) so this is the way you would have to do it.

I still think you should go back and remap the master cfg file the 'retroarch' way, but this is why the alternative location for the file is permitted :)   This way it will not affect your other systems!

**Comment by blinkydoos** [comment]
When I mapped the controller in Emulation Station these were the configs it made. These are the ones that get used in RetroArch as well. I never selected 'A/B Swap' either.

**Comment by HoraceAndTheSpider** [comment]
Oh, i appreciate these are hwo they are made - when you have been asked to click 'b' button, you have clicked what is labelled as 'B' on your pad.

However the SNES pad layout (which i got from the RetroArch page) shows that your A/B X/Y selections are 'swapped' from what is expected by RetroArch, which is why you have the problems with the default behaviour.

This picture shows how the Amiberry default behaviour maps against the RetroArch config:

<img width="964" alt="amiberry_layout" src="https://user-images.githubusercontent.com/567602/31308278-1bb756da-ab6c-11e7-82b6-5fccd3296e60.png">

**Comment by HoraceAndTheSpider** [comment]
it is the same with other input devices, as shown here: https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration

![7f50121a-42c0-11e6-8ef5-50c4b5672216](https://user-images.githubusercontent.com/567602/31308305-a6955766-ab6c-11e7-8500-2a05cb3d09c1.png)

**Comment by CypherXG** [comment]
Can not compile.
Get an "cannot find Mpeg2.h" error.
Try to use an alternate Mpeg2.h, but doesn't work.
Where can i get the correct one?

**Comment by blinkydoos** [comment]
Oh, I see. So it was RetroArch's fault all along ! It requires a specific layout. That X-360 layout picture is wrong. A and B, X and Y should be swapped like my Gamepad. I'll leave it as is for now.

One last thing, have you not added your CD32 controls yet, because only Button 2 works but it presses all the buttons at once ?

**Comment by HoraceAndTheSpider** [comment]
@CypherXG 

try doing these first:

```
  sudo apt-get install libmpg123-dev
  sudo apt-get install libmpeg2-4-dev
```

**Comment by midwan** [comment]
Just wondering, should we keep this issue open or can we close it?
