### ISSUE TITLE
LEDs to GPIO?

### ISSUE THREAD

**Issue by Eriond** [midwan/amiberry#129]
I've read through a lot of posts related to issues with using the keyboard leds for Power/HDD/FDD LED emulation. I too, have such an issue.
So, since we're on a fantastic DIY platform (the Raspberry), could I ask of you that the above mentioned status signals be present on a couple of GPIO pins? I'd be happy to draw a simple schematic, do a PCB/Stripboard layout and/or do the additional documentation.

**Comment by HoraceAndTheSpider** [comment]
When i've finished with the input section, i will probably be looking into this, using WiringPI : 

http://wiringpi.com/the-gpio-utility/

I have a Pi inside an A1200 case myself, with the LEDs wired up to GPIOs for network and drive activity, but I would really like it if when running Amiberry, the HDD/FDD activity took over instead :)

**Comment by Eriond** [comment]
Cool, I'm looking forward to this enhancement.
In case you're at liberty to choose GPIO pins freely, please try not to use those pins that double as UART or SPI bus. I beleive they will have future use as a "real" Amiga serial port, and/or a generic SPI port extender to get real parallel or other ports (game, mouse or floppy).

**Comment by midwan** [comment]
Note: We can add this in the Misc Panel, together with the NumLock/Scroll Lock LED options.

**Comment by BleuLlama** [comment]
Is there any further progress on this feature?  I'd love to see it!

**Comment by thinghacker** [comment]
This is something I am quite interested in as well

**Comment by midwan** [comment]
@BleuLlama @thinghacker 
I didn't have a chance to work on this yet, but now that v2.25 is out we can take another peek.

**Comment by BleuLlama** [comment]
Sidenote, it might be neat to trigger an external/system signal, script, plugin or somesuch... I'll probably look into this myself once the above feature is in place. :D

**Comment by XR4x4** [comment]
Was this ever implemented somewhere I cant find, or still on the back burner ??

Would be a great additiion!!

**Comment by midwan** [comment]
@XR4x4 
Still in the ToDo list I'm afraid...

**Comment by craggus2000** [comment]
Hi, has any more progress been made on this? Really looking forward to it for that final added piece of authenticity!
Many thanks

**Comment by craggus2000** [comment]
> When i've finished with the input section, i will probably be looking into this, using WiringPI :
> 
> http://wiringpi.com/the-gpio-utility/
> 
> I have a Pi inside an A1200 case myself, with the LEDs wired up to GPIOs for network and drive activity, but I would really like it if when running Amiberry, the HDD/FDD activity took over instead :)

What circuit did you create to connect the leds to the pi?

**Comment by midwan** [comment]
wiringPi seems to be deprecated, so I'm open to suggestions on another similar library that could work... :)

**Comment by midwan** [comment]
Update: looks like the recommended multi-platform approach is using `libgpiod`, which allows for this functionality.

I have a demo tool already working with this, so it looks promising. There will be an extra requirement for the system in order to use it (install `libgpiod`) and for now, there are also extra permissions required to access the GPIO pins. I'm looking into how that can be avoided, and eventually all this information will become part of a new wiki page.

**Comment by midwan** [comment]
Initial test from within Amiberry looks promising as well:
![20211220_211726-25%](https://user-images.githubusercontent.com/3877365/146827951-9dba65ae-981b-4d1d-87f2-dec64e226c30.jpg)

I played around with 3 LEDs, for Floppy, HDD and Power respectively.
Now need to add GUI updates to support these in a better way, save the options to the config, etc.

**Comment by Eriond** [comment]
Wow, it's finally becoming reality. I'm so happy you found the time for this. It's yet another step closer to provide an even more true-to-life emulation.
Thank you!

**Comment by midwan** [comment]
First version of the wiki page is here: https://github.com/midwan/amiberry/wiki/Using-GPIO-pins-for-LEDs

Let me know if anything seems unclear or should be improved.

**Comment by midwan** [comment]
You can grab the latest from `master` and test it out yourself. There are some limitations as documented on the wiki page, but this can be improved with future updates. Consider it as a first attempt :)

**Comment by Eriond** [comment]
Oh! How cool. Yes, I will try this right away. I have a Pi400 laying around waiting for something like this :)
Re. the wiki; there is one thing I noticed right away, and that is the always-alluding discrepancy between GPIO numbers and physical pin numbers as in the Raspberry GPIO header pinout. It would help if it was made absolutely clear which of those numbers are referred to.

**Comment by midwan** [comment]
Good point, I'll try to make that clearer.

**Comment by midwan** [comment]
Closing this for now, but I'll continue to improve things in this area with future updates.
