### ISSUE TITLE
SDL2 | Quick floppy insert/eject keys

### ISSUE THREAD

**Issue by ariath** [midwan/amiberry#13]
Hi all!

Would be possible add support for inserting/ejecting floppies with a key combination like WinUAE?
Like End+F1-4 for inserting a floppy in DF0-3 and Supr+F1-4 for ejecting the floppies.

See ya!

**Comment by midwan** [comment]
Not a bad idea.
I'll take a look at this a bit later on. I'd like to get any bugs fixed first, move the codebase to SDL2 and then start implementing enhancements such as this.

Thanks for bringing it up!

**Comment by midwan** [comment]
Note to self:
Add a region in the GUI to map such custom controls

**Comment by midwan** [comment]
The framework for this has now been added.
The next step is to have the relevant options at the GUI, save those in the config file and test the whole thing out thoroughly.

**Comment by midwan** [comment]
@ariath 
This is now fully implemented, in the current `dev` branch.
It will be merged into the next release. :)
