### ISSUE TITLE
IPF support. Is it possible?

### ISSUE THREAD

**Issue by Uukrull** [midwan/amiberry#130]
Some interesting links with info:

https://github.com/libretro/fuse-libretro/issues/30

[SPS decoder library source code](https://kryoflux.com/?page=download)

**Comment by Uukrull** [comment]
Well, it is indeed :) with https://github.com/FrodeSolheim/capsimg

**Comment by Uukrull** [comment]
https://github.com/Uukrull/amiberry/commit/dfe23ba0ae85d470e3883b9bdcd6b5a4faf328d4

These are the (hackish) changes needed for the sdl2-dev branch. I use this branch because is the only one that works on my Mecool M8S Pro+ (a box with an S905x chip and LibreELEC installed) since I don't have a raspberry for testing.

You also need to compile the capsimg.so from https://github.com/FrodeSolheim/capsimg

The code I used is from the latest FS-UAE.

**Comment by midwan** [comment]
Thanks for this, I'll take a look at it...

**Comment by midwan** [comment]
@Uukrull I'll be taking a look at this over the next few days, if all goes well it will be merged in.

**Comment by ZappaUtopia** [comment]
This will be a great addition !

**Comment by midwan** [comment]
I will look into adding this before the v2.13 release, due for this weekend. :)

**Comment by CypherXG** [comment]
I'll tested the IPF support, but it is not working.
When i add different IPF Files in DF0/DF1, the IPF Files are not regonized
like an ADF or Zip etc. by the Emulator.

**Comment by midwan** [comment]
@CypherXG Did you follow the steps indicated in the Wiki article about this?
https://github.com/midwan/amiberry/wiki/Enabling-IPF-support

**Comment by CypherXG** [comment]
Ups.....^^

**Comment by ZappaUtopia** [comment]
Just out of interest, why do we have to do this optionally ? Will it be included in the next binary release ?

**Comment by midwan** [comment]
@ZappaUtopia 
Because it requires an external library to be in the same location as the Amiberry binary (which complicates the delivery), and I suspect that many people may not require it.

Those that want it, can follow the extra steps (once) and just place the lib in the same directory.
Those that do not care about IPF support, can just continue upgrading as previously with no changes in the workflow.

**Comment by ZappaUtopia** [comment]
OK thanks.

**Comment by kblood** [comment]
I noticed Amiberry still uses the library for IPF support, but there are ways around having to use it now. Would it not be an option to use this?
https://github.com/Tom1975/CPCCore/blob/master/CPCCoreEmu/CAPSFile.cpp

It is open source and decodes IPF without using the CAPS library.

**Comment by midwan** [comment]
@kblood 
Thanks, that's interesting and I wasn't aware of it.
I've been trying to keep Amiberry in-sync with WinUAE as much as possible, to make it easier to merge updates. I'll have to check if can be changed without too much of a hassle, unless of course someone is willing to send a pull request with the required changes!

**Comment by midwan** [comment]
If it works just as well, I'm happy to update it. Needs some testing first.
Would be best if this was in a separate issue, not a closed one. ;)
