### ISSUE TITLE
New 2.5 beta in RetroPie, takes me back to EmulationStation

### ISSUE THREAD

**Issue by PanosPl** [midwan/amiberry#132]
Hi,
I have overwriten my amiberry executable in my RetroPie with the new one from the git (2.5 beta)
I use the .uae files trick in order to select the games from inside EmulationStation directly.
Well, with the new executable once I select a game it takes me back to EmulationStation.

Thanx

**Comment by HoraceAndTheSpider** [comment]
https://github.com/midwan/amiberry/issues/128#issue-263418477

**Comment by HoraceAndTheSpider** [comment]
"For those who are just copying over the new binary also need the 'data/quickstart.ico' otherwise it won't run."
