### ISSUE TITLE
Controller fork (Horace) joypad errors ?

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#133]
Hi, I'm not sure if this is a known problem at this stage but i'll report it anyway. I just built your (@HoraceAndTheSpider) latest commits and tested my joypad with the tool below (as it is by far the best).

[SysTest (17-Sep-17).zip](https://github.com/midwan/amiberry/files/1390640/SysTest.17-Sep-17.zip)

I am testing it with a wired iBuffalo SNES pad. I set the controls to 'RetroArch's' standard.

Button 1 works fine (Button B bottom).
Button 2 works (Button A right) but also seems to press Up,Down,Left and Right all at the same time.
Y (left button) works fine as Up.
X (top button) works fine as Button 3.
D-Pad Left presses Left and Up at the same time.
D-Pad Right presses Down and Right at the same time.
D-Pad Up and Down don't register.

[USB,2-axis 8-button gamepad  .zip](https://github.com/midwan/amiberry/files/1390663/USB.2-axis.8-button.gamepad.zip)

**Comment by HoraceAndTheSpider** [comment]
So you are saying you have set the "controllers" path on the paths panel to where your retroarch controller cfg a are found, and there is an ibuffallo cfg there? Can you provide a copy of that file please

**Comment by blinkydoos** [comment]
Yes I set it to RetroArch's 'autoconfigs' directory. I already posted the file above.

**Comment by HoraceAndTheSpider** [comment]
sorry, using phone so could not see the file, 

It looks like your pad doesnt have a HAT, but uses axis 0/1 for the dpad. 

There is also a lot of 'spaces' in the file name, and i wonder if that is causing any issues, or if there is a problem with how it picks up the axis number from the retroarch cfg.

I suspect the latter, and will check later.


From your coments the joypad mode  appears to be set to 'joystick'  - the "multiple buttons" issue on button 2 is common, as this is to do with the different ways that the second button/blue button are detected on UAE. (basically all cd32 buttons will often display as being pressed when the "right mouse button" is pressed on port 1)

Please put the input mode to 'cd32' and test Button A to see if the program you are using returns the correct result for 'blue'

**Comment by blinkydoos** [comment]
The pad is digital only, no analogue. Setting the port to CD32 mode and pressing blue (A button right) presses Blue and up, down, left and right all at the same time.

**Comment by HoraceAndTheSpider** [comment]
digital or analogue shouldn't matter - axis are treated differently by SDL to HATs.

The d-pad wont be changed but this - just needed to know re: blue button, thanks - i have an idea what the issue could be, but cannot update anything for a while i'm afraid.

**Comment by blinkydoos** [comment]
That's OK. I just thought i'd post it to let you know. I'm at work anyway !

**Comment by HoraceAndTheSpider** [comment]
same here ;)  

Think i have worked out the issue(s) just by reading the code... so should be able to solve this.

**Comment by HoraceAndTheSpider** [comment]
@blinkydoos i have committed a (possible) fix, i would be greatful if you could check. Thanks.

**Comment by HoraceAndTheSpider** [comment]
Well it's progress at least, lol 

I can guess again at where the problem might be - glad the button issue is solved :)

**Comment by HoraceAndTheSpider** [comment]
latest commit should fix the swapped axis bug ... as i suspected, i had the X/Y inverted for the single axis detection.

**Comment by blinkydoos** [comment]
All works fine now, thanks.

**Comment by HoraceAndTheSpider** [comment]
This is great - thanks @blinkydoos , this is really good for improving compatibilty.
