### ISSUE TITLE
Respect environment variables

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#135]
This will make the Makefile respect if the user has set CC (which is not used in this case) and/or CXX in the environment.

`diff --git a/Makefile b/Makefile
index 633fecb..345ad4b 100644
--- a/Makefile
+++ b/Makefile
@@ -28,9 +28,9 @@ endif

 NAME   = amiberry
 RM     = rm -f
-CC     = gcc
-CXX    = g++
-STRIP  = strip
+CC     ?= gcc
+CXX    ?= g++
+STRIP  ?= strip

 PROG   = $(NAME`

**Comment by midwan** [comment]
@solskogen Thanks, merged in for both dev branches now
