### ISSUE TITLE
Action Replay activate button ?

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#136]
I set the 'Action Replay Mk III v3.17' ROM in the Cartridge rom section. If I reset the Amiga it shows the Action Replay splash screen but what is the Activate button, does it work ? It's 'Page Up' on WinUAE but couldn't get anything to happen on Amiberry.

**Comment by midwan** [comment]
It's not properly mapped to a button yet, it was hardcoded in the Pandora version but that will change for the Pi version.

@HoraceAndTheSpider is working on the custom controls and mapping section, so this will be added there eventually and merged in the dev branches.

**Comment by HoraceAndTheSpider** [comment]
http://youtu.be/ypVnq3bjwQw

It does work in the latest version on controller branch :)
Best to use the default a500 setup then add the cartridge I found.

**Comment by blinkydoos** [comment]
@HoraceAndTheSpider Nice, I never even thought to look at the Custom Controls section as I thought it wasn't useable yet. Would it also be possible for WinUAE's Warp mode or is that not implemeted in the code ?

**Comment by HoraceAndTheSpider** [comment]
The custom section doesn't load/save yet but does technically work. (Mostly) 

I think the warp mode function was maybe removed from the UAE input events list but almost certainly I didn't include it there (although I did put most functions in) ... several events didn't seem to work after the port (including save state load/save which I need to look into)

**Comment by blinkydoos** [comment]
OK thanks, i'll close this now.
