### ISSUE TITLE
Shadow Fighter

### ISSUE THREAD

**Issue by vultureg7** [midwan/amiberry#138]
Shadow Fighter AGA (maybe ecs too, haven't tested yet) suffers from in-game slow downs and speed ups rendering it unplayable.

**Comment by nemo93** [comment]
Could you please confirm you've tested with a WHD package? If so what version have been used? Any specific way to reproduce this "bug" and could you please share your uae file as well (rename to txt before attaching it here)? If this is confirmed then I'll add it to the "main" games bugs thread here #122.

**Comment by vultureg7** [comment]
Yes, it's the WHDLoad version, latest slave used (1.0) and latest whdload used as well (18.3). Attached the config, thx!
[Shadow Fighter [AGA].txt](https://github.com/midwan/amiberry/files/1405019/Shadow.Fighter.AGA.txt)

**Comment by nemo93** [comment]
Thanks @vultureg7. I can't seem to reproduce this behavior here. As far as I'm able to see game is running fine here on my setup (pi3, retropie 4.3, xbox360 controller) same WHD package as yours (Version 1.0 (24.03.2007)). 
I could see slight differences between your uae and mine. Hence could you please try mine? You could get it [there](https://pastebin.com/uPAEz5cJ). It is from another game but simply change paths according to your setup and see how it goes.

**Comment by ransom1122** [comment]
I also tried nemo93'a config for my Shadow Fighter (AGA) [ADF] version & it is way too slow. All WHDLoad versions vulture has tried also run too slow.

The only success I got was using the ECS ADF version. It plays at normal speed.

Please compare each other and you will see a difference.

**Comment by nemo93** [comment]
Thanks to both for the precious feebacks. I've added the game to the main list in ticket #122. May I kindly ask for this ticket to be closed then to avoid duplicate? Thanks!

**Comment by nemo93** [comment]
Hi @vultureg7 please close this one off. Thanks!

**Comment by vultureg7** [comment]
done!
