### ISSUE TITLE
Can't untick "Write-Protected" in floppy drives

### ISSUE THREAD

**Issue by ariath** [midwan/amiberry#14]
Hi all!

I was testing something in Workbench (i'm using an ADF of Workbench 1.3), and when i was going to save the changes, AmigaDOS told me that the floppy was write protected.

I thought: "No problem, i have to open the emulator GUI and un-tick the write-protection checkbox and i will be able to save my changes".

The problem came when i noticed that the checkbox... was... greyed out :S.
I tried enabling DF1 and DF2 as well, but... can't untick their write-protection checkbox neither :( .

Maybe a bug?

See ya!

P.D: Yes, i'm using Workbench and Kickstart 1.3, the ones of my beloved A500 :3 <3.

P.D 2: Also i wanted to ask if UAE4ARM is compatible with RDB for making hardfiles recognized by HDToolBox :) .

**Comment by midwan** [comment]
Thanks for reporting this, I'll look into it.

**Comment by ariath** [comment]
I have done some research and... maybe i have found the problem:

src/od-pandora/gui/PanelFloppy.cpp

```
chkDFxWriteProtect[i] = new gcn::UaeCheckBox("Write-protected");
        chkDFxWriteProtect[i]->addActionListener(dfxCheckActionListener);
**chkDFxWriteProtect[i]->setEnabled(false);**
```

```
class DFxCheckActionListener : public gcn::ActionListener
{
public:
    void action(const gcn::ActionEvent& actionEvent)
    {
        if(actionEvent.getSource() == chkLoadConfig)
            bLoadConfigForDisk = chkLoadConfig->isSelected();
        else
        {
            for(int i=0; i<4; ++i)
            {
                if (actionEvent.getSource() == chkDFx[i])
                {
                    //---------------------------------------
                    // Drive enabled/disabled
                    //---------------------------------------
                    if(chkDFx[i]->isSelected())
                        changed_prefs.floppyslots[i].dfxtype = DRV_35_DD;
                    else
                        changed_prefs.floppyslots[i].dfxtype = DRV_NONE;
                }
                else if(actionEvent.getSource() == chkDFxWriteProtect[i])
                {
                    **//---------------------------------------
                    // Write-protect changed
                    //---------------------------------------
                    // ToDo: set write protect for floppy**
                }
            }
        }
        RefreshPanelFloppy();
    }
};
static DFxCheckActionListener* dfxCheckActionListener;
```

As long as i understand... 
1) The write-protect checkboxes are disabled by default.
2) It seems that the management of write-protection is a ToDo task.
3) I haven't found any "chkDFxWriteProtect[i]->setEnabled(true)" in the entire file.

I'm right? :3

See ya!

**Comment by midwan** [comment]
@ariath 
Yes, you are probably right in this finding. :)
I didn't have time to test this yet, but from what I see above the Write Protection checkbox is always disabled and there's no code behind that event to change the status.

Thanks for your investigation, we can save some time looking for this now. :)

**Comment by lovrenco** [comment]
I confirm this in UAE4Arm for android. It is a problem because you cannot save games.

**Comment by midwan** [comment]
@lovrenco thanks for confirming. Both emulators use the same codebase, so it's not surpising that they share the same bugs also. :)

**Comment by windale** [comment]
Will this write the changes only to a seperate file like WinUAE or will it modify the original ADF ?

**Comment by midwan** [comment]
@windale 
Like WinUAE, it will write the changes in the ADF itself. ;-)

**Comment by windale** [comment]
WinUAE creates a separate file with '_save.adf' added to the filename so you don't damage the originals. For example, writing to Workbench disks.

**Comment by midwan** [comment]
@windale 
Is that an option somewhere in WinUAE? It did not create such a file in my tests, with the latest WinUAE 3.4.0...

**Comment by windale** [comment]
No, I am using default v3.4.0. it writes the file to the same directory as the Winuae.exe. After writing it shows a button in the Floppy drives section where you can 'Delete save image'.

**Comment by ariath** [comment]
Mmm... i think FS-UAE is the one that saves changes to a different ADF, like a "diff" file.

**Comment by midwan** [comment]
@windale 
I tried it a few minutes ago, created an Empty.adf new image, booted workbench 3.1 and created a new Directory in the empty disk.

No files were generated by WinUAE, either in the ADF's folder or WinUAE's folder..

**Comment by windale** [comment]
Maybe Tony has changed something, my version is 3.4.0 (2016.12.21).

**Comment by midwan** [comment]
@windale 
Also, I don't see an option to "Delete save image" in WinUAE:
![image](https://cloud.githubusercontent.com/assets/3877365/23303674/c00a2ec0-fa95-11e6-9997-1a83996d6ef2.png)

I'm also using the same WinUAE verison, 3.4.0 (2016.12.21) 64-bit

**Comment by windale** [comment]
Mine looks like this after making changes to a floppy -

![write protect](https://cloud.githubusercontent.com/assets/12862298/23303737/b2302b54-fa8d-11e6-8b1d-2cee0bc32582.png)

**Comment by midwan** [comment]
@windale 
Strange, I don't see that button here... :( I'll check WinUAE's source code to see if it only shows it under certain conditions.

**Comment by windale** [comment]
Writing the saved changes to a separate file makes sense though otherwise you could destroy the original image.

**Comment by windale** [comment]
I think it didn't work on yours because you already created a new Empty.adf.

**Comment by midwan** [comment]
@windale 
It behaves the same if I do it on the Workbench disk... and anyway, I created the Empty disk, then restarted WinUAE to be sure, then tested it. The button does not show up, no extra files are generated...

**Comment by windale** [comment]
That's strange, I haven't altered any options regarding Floppy drives. Would it be anything to do with the 64-bit version ? (I'll try it).

Some ADF's won't even load unless you untick Write Protect (like Kult/Chamber of the Sci-Mutant Priestess). This way it will add the changes to a separate file and keep the zipped original un-altered.

**Comment by midwan** [comment]
@windale 
Zipped you said... :)

I found it! If the images are compressed with ZIP, then the button shows up and it works like you described. If they are ADF though, this does not happen.

**Comment by windale** [comment]
Aha ! Could you make AmiBerry save changes to a separate file (maybe in a different directory) to preserve the originals whether they are zipped or not ?

**Comment by midwan** [comment]
@windale 
This is a feature of newer versions of WinUAE, so I'll have to look at how he implemented it there... but yes, it's possible.

**Comment by midwan** [comment]
@windale 
Actually, I think it may already be there... :) At least as an older implementation of the same idea.

In disk.cpp, line 789:
```
fetch_saveimagepath (path, sizeof path / sizeof (TCHAR), 1);
	_stprintf (name1, _T("%s%s_save.adf"), path, name2 + i);
  return name1;
```

I'll have to run some tests to verify it works as expected, but the logic seems to be there.

**Comment by midwan** [comment]
@windale 
Confirmed, if the disk is an archive (e.g. ZIP) then changes are saved to savestates/<diskname>_save.adf automatically. This does not happen with ADFs, where the changes are saved in the image itself.

I think for now we'll leave it to this, in order to merge WinUAE code easier. Once we're up to the 3.4.x standard, then we can make such changes.

**Comment by windale** [comment]
To the save states directory ? But the files will be different from an actual save state though, will you be able to tell the difference between this and the actual save state files ? I say this because if you wanted to revert the changes you would know which file to delete.

**Comment by midwan** [comment]
The disk images are always named <diskname>_save.adf, while savestates are named differently, so there shouldn't be a problem distinguishing one from the other...

**Comment by windale** [comment]
That sounds fine then, I think most people like me would be using zipped files anyway (as it saves a ton of space) and if they need to make changes permanent then mount the file unzipped.
