### ISSUE TITLE
Bombuzal [ADF] Game crashes when you start playing

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#140]
Hi,

I tried the adf version of Bombuzal and it seems to crash just before you start playing level 1. I have tried many different configs with no success..

The ADF used is this one
Bombuzal (1988)(Image Works)[cr QTX][t +3 Vector].adf

On a side note the WHDLoad version works..

**Comment by ransom1122** [comment]
Can you please add this bug to post #146. Thanks

**Comment by blinkydoos** [comment]
The game does work but it stays on the Get Ready screen for about 40 seconds before the game starts.

You created post 146, you can edit that post and then close this one !

**Comment by nemo93** [comment]
@ransom1122 please close this one off. It has been added to #152. Thanks!

**Comment by midwan** [comment]
@ransom1122 
The version you mention has several glitches (gfx corruption in the menu screen, and I can't even start the game), but I tried with "Bombuzal (1988)(ImageWorks).zip" and it worked normally right away.
