### ISSUE TITLE
Compilation error on sdl1-branch

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#141]
g++ `sdl-config --cflags` -march=armv8-a -mfpu=neon-fp-armv8 -mfloat-abi=hard `xml2-config --cflags` -DCPU_arm -DARMV6_ASSEMBLY -DWITH_INGAME_WARNING  -DUSE_SDL -DARMV6T2 -DUSE_ARMNEON -DRASPBERRY -DCAPSLOCK_DEBIAN_WORKAROUND -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -Wno-unused -Wno-format -DGCCCONSTFUNC="__attribute__((const))" -mstructure-size-boundary=32 -falign-functions=32 -std=gnu++14 -g -rdynamic -funwind-tables -mapcs-frame -DDEBUG -Wl,--export-dynamic  -c src/osdep/gui/Navigation.cpp -o src/osdep/gui/Navigation.o
src/osdep/gui/Navigation.cpp:263:2: error: #else after #else
 #else
  ^~~~
src/osdep/gui/Navigation.cpp:255:0: error: the conditional began here
 #ifdef ANDROID
 
src/osdep/gui/Navigation.cpp:252:0: error: unterminated #ifndef
 #ifndef RASPBERRY
 
src/osdep/gui/Navigation.cpp:249:89: error: expected primary-expression at end of input
   { "cboRight",       "cboLeft",        "Input",          "cboDown",        "cboPort0" },
                                                                                         ^
src/osdep/gui/Navigation.cpp:249:89: error: expected '}' at end of input
src/osdep/gui/Navigation.cpp:249:89: error: expected ',' or ';' at end of input
make: *** [Makefile:300: src/osdep/gui/Navigation.o] Error 1

**Comment by HoraceAndTheSpider** [comment]
Compile errors on anything but the master branch are quite likely as we are trying out a lot of changes atm. This issue appeared on Wednesday I think!

This is fixed in the controller branch but has not yet be pulled into the SDL branch. @midwan and I will fix this in the next few days.
