### ISSUE TITLE
ADF Issues

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#146]
Starting a Thread only for ADF's I cannot get working on Amiberry.. I will keep adding to this thread when I find ADF's that have issues with Amiberry.

**Dan Dare III - The Escape** 
ADF Used. Dan Dare III - The Escape (1990)(Virgin Mastertronic)[cr Tristar][t +11 Tristar].adf 
Black screen after Title Screen. (WHDLoad version works)

**Hostages**
ADF Used. Hostages (1988)(Infogrames)[cr QTX].adf
You get shot and killed everytime you start playing. Seems to be a known old Cycle exact isssue. (WHDLoad Version works)

**XR35 Fighter Mission**
ADF Used. XR35 Fighter Mission (1988)(Anco)[cr Tristar][t Tristar].adf & XR 35 Fighter Mission.adf (Gamebase20)
After it loads it can either Freeze and Hang the Raspberry Pie 3 on the 1st screen with a picture of black background with white stars. OR Quickstart a500 Mode quits back to ES.

**Moon Child**
ADF Used. Moon Child (demo-playable) (199x)(Team Hoi)(AGA)(Disk 1 of 3)[unreleased].adf
MAjot Graphic problems when game starts.. unpayable...

**Comment by ransom1122** [comment]
Revelation!
Revelation! (1991)(Krisalis)[cr EP][t +3 EP].adf
Guru Crash after Krisalis Title Screen

**Comment by ransom1122** [comment]
**Revelation!**
Revelation! (1991)(Krisalis)[cr EP][t +3 EP].adf
Guru Crash after Krisalis Title Screen

**Comment by blinkydoos** [comment]
The one from Gamebase Amiga works fine.

`Revelation! (1991)(Krisalis)[cr EP]` (no trainer).

**Comment by ransom1122** [comment]
Your correct Gamebase 2.0 version of Revelation works perfect.  Nice Job :)

**Comment by ransom1122** [comment]
**Striker (Rage)**
ADF Used Striker (1992)(Rage)[cr CSL][a].adf & Striker.adf from Gamebase 2.0
Character Sprites flicker during the game. Problem occurs on Both WHDLoad & ADF Versions of the game

**Comment by nemo93** [comment]
Hi @ransom1122! Do you want me to create a similar ticket as of #122 but for ADF this time? I'll use the same format. I intend to do the same for CD32 as well. If you agree then I'll require people to close some tickets to avoid duplicates and avoid confusion. 

What you think?

Meanwhile I'll add Striker to #122 as there's only a single package version no confusion possible here ;)

Thanks for that

**Comment by ransom1122** [comment]
@nemo93! Personally I think seperating ADF & WHDLoad might be a better idea. As some whdload games work over their ADF counterpart. People may get confusing to say an adf game is not working, when  the WHDLoad versionn does. Hence why I created an ADF Issues/Bugs only thread..

**Comment by nemo93** [comment]
Hello @ransom1122!! My bad my comment above was not clear enough. I definitely agree with you 100%! I definitely prefer to have separate ADF, WHDLoad and CD32 games. If you don't mind I'll go ahead and create a new ticket for ADF asap.

**Comment by blinkydoos** [comment]
@nemo93 Out of interest, what's wrong with this thread that @ransom1122 has already started, why did you create another one ?

**Comment by nemo93** [comment]
Hi! In fact you're right @blinkydoos no need to have a new ticket as it's already there. Let's keep on posting on that one then. Sorry for the confusion :(

**Comment by midwan** [comment]
@ransom1122 
**Dan Dare III - The Escape** - works correctly in the latest sdl1-dev version

**Comment by ransom1122** [comment]
Nice work 😀

**Comment by ransom1122** [comment]
Here's the link to Moon Child. From here on, I will post an issue to each game seperately
https://www.dropbox.com/s/h41xsy5odyoivw4/Moon%20Child.rar?dl=0

**Comment by ransom1122** [comment]
**Dan Dare III - The Escape** - sdl1? Which Amiberry version is that, the older one before the current one? I can;t go back to an older version, will it be fixed in updadted versions of Amiberry?
**XR-35** - Can you please send me a link for "XR-35 (1988)(Anco).zip" The tosec set and gamebase ADF's are all cracked version.
**Striker** - Blitter mode to "Immediate" FIXED the problem
**Bombuzal** - Works with **Bombuzal (1988)(ImageWorks).zip**

2 games remain not working

Hostages
Moon Child

**Comment by midwan** [comment]
@ransom1122 
sdl1-dev is the latest development version. There are 2 dev versions, one is for SDL1 and one for SDL2. These latest changes went in SDL1 first, and SDL2 will be synced soon.

Thanks for the link, I'll test Moon Child and see what happens.

**Comment by ransom1122** [comment]
Your version of xr35 adf is the same as gamebase version. Can you please provide link for the adf or even better show the config you used for it to work?

**Comment by midwan** [comment]
@ransom1122 
Will do, as soon as I get back home. The config was the standard Quickstart A500 configuration, nothing special after that.

**Comment by ransom1122** [comment]
Very strange. I load the XR 35 Fighter Mission.adf from the gamebase 2.0 database as quickstart a500 with kick13.rom and it passes the cracktro screen then you see the scrolling pixels/stars and it immediately quits back to amiberry.

**Comment by blinkydoos** [comment]
@ransom1122 I just tried 'XR 35 Fighter Mission' from Gamebase Amiga and it works fine. I used `Quickstart Amiga 500`, `1.3 ROM, ECS Agnus, 1MB Chip RAM`'.

**Comment by ransom1122** [comment]
@Blinkdoos

That config for xr35 now freezes the pie completely where it usually quits back to amiberry. Need to power off the pie

**Comment by blinkydoos** [comment]
@ransom1122 That sounds very strange, that Quickstart option runs the game fine on mine. It doesn't freeze or quit.

**Comment by ransom1122** [comment]
Are we on the same Amiberry version? Im on tge last stable version.

**Comment by blinkydoos** [comment]
I compiled fairly recently after they merged the controller updates. But I also tested XR35 with that Quickstart option on the Android version of UAE4Arm and it also works fine.

**Comment by ransom1122** [comment]
**Titanic Blinky**
ADF Used. Titanic Blinky (1991)(Zeppelin)[cr Flashtro][t +9 Flashtro].adf.adf & Titanic Blinky.adf (Gamebase20)
After it loads it Titanic Blinky says "Go for it" then walks left it then Freezes.

**Comment by ransom1122** [comment]
**Double Dragon II** 

ADF Used. Double Dragon II (1990)(Virgin Mastertronic)[cr OCL][t +2 OCL].adf (tosec)
ADF Used. Double Dragon II - The Revenge.adf (Gamebase 2.0)

After pressing ENTER on the trainer, You end up with a black screen..

**Comment by ransom1122** [comment]
**Dragon's Lair**

ADF Used. Dragon's Lair (1987)(ReadySoft)[cr ACU][t +2 ACU](Disk 1 of 8).adf

White screen after Cracktro

**Comment by ransom1122** [comment]
**G-LOC - R360 Air Battle**

ADF Used. G-LOC - R360 Air Battle (1992)(U.S. Gold)[cr CSL][t +4 Supplex].adf
ADF Used. G-LOC R360.adf (Gamebase 2.0)

Get a piracy error after Title screen before the game starts.. Same ADF's work properly on WINUAE

**Comment by cinemano** [comment]
Has the Hostages issue been resolved? I also have that problem with getting shot as soon as the game starts. Annoying as its one of my favourite games.. I tried both adf and the whd files.. same issue.. I tried changing the hostages.uae file I created with changing to: immediate_blits=False
;waiting_blits=False  but that didn't work.. any solution at all (appart from getting a used Amiga LOL)

**Comment by ransom1122** [comment]
Havent tried it on 2.19 I'll give it a go tonight.

**Comment by cinemano** [comment]
Thanks so much.. I even tried to get the ST version but of course that wont
run lol it crashes before the game starts. but sound was awful anyway..
Using amiberry on Retropie..

**Comment by ransom1122** [comment]
Until I try it.. in the meantime have you tried it on 2.19 with most compatible enabled.

The game require cycle exact with winuae for it to work otherwise your always shot at in the beginning of the game.

I always though v2.19 had cycle exact implemented?

**Comment by cinemano** [comment]
I'm using Amiberry on a Retropie.. there is a uae file for each game.. I
tried to retype mine to disable the wait for blits .. can I email it to you
to have a look?

**Comment by ransom1122** [comment]
I'm using Amiberry on RPI3 as well. No point sharing configs paths will be all different. I'll try with all my different configs tonight.

In the meantime try a quickstart on a500 & a1200 and see if it works. If not enable compatibility mode in Amiberry GUI I think in CPU tab.

**Comment by cinemano** [comment]
Ok will try. How do you do a quickstart.. from the amiberry app window?

(where the settings are like cpu, ram etc.. ) ? Sorry I'm new on this..

**Comment by cinemano** [comment]
well or how you turn off the waiting for blits.. ?

**Comment by ransom1122** [comment]
Launch +Amiberry from Emulation Station.
Select Quickstart TAB under PATHS tab
Select A500 or A1200 and click start.

All blitter and compatible settings are in the CPU tab

**Comment by cinemano** [comment]
only blitter setting i see is normal, fast or wait for blitter.. no disable
option..
Tried 1200 still gets shot moment he comes out .. using quickstart.. can i
quickstart with WDHload instead?

**Comment by cinemano** [comment]
Holy!! It Worked!! I chose

A1200 on Quickstart
Chipset:  OCS instead of AGA (where it is normally defaults).
Blitter: NORMAL
and opened ADF on quickstart.

Thanks so much!! How can I save these settings on the uae file so I can
open it directly from the Amiga games menu??
Would love to keep those settings for this game.. possibly even all amiga
games?

George

**Comment by cinemano** [comment]
how do i savestate once the game is loaded?

so itll keep all the setting...

**Comment by cinemano** [comment]
Can I make the ADF force the A1200, OCS, Normal blitter settings when
loading?
would be nice not to have a windows settings way of loading it

**Comment by ransom1122** [comment]
Great.  

Just save the game config in configuration tab.

Then you can load configs directly from emulation station.

**Comment by cinemano** [comment]
I tried that i loads the adf without them get shot as soons as it starts..
i tried both configuration tab in quickstart and also configuration tab in
configurations under the name of the game in the list...
Anywhere i missed?
No way to type the info into the hostages.uae file?

**Comment by ransom1122** [comment]
Booting users from emulation station is no on topic here. This thread is mainly for what is not working with Amiberry.

You may want to ask In retropie forums about booti ng amiga uae config files.

I am able to save configs from both Amiberry or manually make them with notepad on PC. 

Make sure your config file path is set to where you store your config use files In paths tab of amiberry.

**Comment by cinemano** [comment]
Ok thanks. Didnt know there was a config path in amiberry settings window.
I created the "hostages.uae" literally by copying it off another game and
changing wherever i saw the names of the previous game to the new one. Mine
are in pi/roms/amiga folder like the others (they point to whdload folder
amiga_data). But to me this is still about making the game work in the same
as the others on amiberry. Appreciate your feedbacks :) after all now this
is the only adf i have in the roms folder just to make it work. All the
others are odd .slave files

**Comment by ransom1122** [comment]
If your using a uae for an adf remove everything from your hard drive paths tab from the uae and re save the config. 

The config files you must be using is for loading whdload games.

Like I said.  Do a Quickstart... when you have a comfortable config save it. Make sure the config is in the /amiga folder of your pi then restart emulation station and boot your config.

**Comment by cinemano** [comment]
You see my adf file is in the same folder as my uae files.. so i figured it
would load that directly being that it appears on the games menu. I thought
it was either: adf  or whdload+.uae..

**Comment by ransom1122** [comment]
I have my games in separate folders.

/Games_ADF
/Games_WHDLoad

Etc etc

Just make sure the uae files path for the adf games point to the exact folder path it is located in.

**Comment by cinemano** [comment]
Ok that the part i didnt know how to do. I dont have an example uae for adf
to compare with. The whd one has tons of paths that confused me. Good to
know uae serve for all. Easier route:
If i delete the .uae file completely, put it in the bin.. and do all paths
and settings inside amiberry setting window, will the 'save configuration'
button create a new one?

**Comment by cinemano** [comment]
Anyway in .uae "normal_blist=True" doesnt exist..... just seems to have:

 "fast_blitter=true"; "Wait_blist=automatic" ..

**Comment by ransom1122** [comment]
Correct.  Make 2 fresh ones as your master ADF UAE.

1. Amiga 500 quickstart and save it.
2. Amiga 1200 quickstart and save it.

Then you can edit and add what you want on a PC with notepad.

**Comment by ransom1122** [comment]
Hostages seems to work too fast with that config. A1200 OCS Blitter Normal. Works but game is way too fast. If you change CPU speed to 7hz from 14hz . It causes bug where you get shot and die.

**Comment by ransom1122** [comment]
Incorrect.  When you save a config everything is saved including chipset.

**Comment by cinemano** [comment]
I tried manually on the uae it doesn't find adf,..

is this correct? ( I put adf in Games_ADF folder


; *** Floppy Drives
; /home/pi/RetroPie/roms/amiga-data/Games_ADF/Hostages-Infogrames.adf
floppy1=
floppy1type=-1
floppy2=
floppy3=
nr_floppies=1
floppy_speed=100

**Comment by cinemano** [comment]
I manually changed aga to ocs.. as the saved config defaulted to aga
somehow..

**Comment by ransom1122** [comment]
Sounds like your save path is read only?

Check your paths in amiberry. Maybe change it to an area you know you can read and write to.

**Comment by cinemano** [comment]
It works now :) yeyy managed to create a save config for hostages but I
accidentally deleted my chaseHQ Whload config uae file..
how do I set a Whload path? create directory?

**Comment by ransom1122** [comment]
Too hard to explain over messaging. Just copy a working whdload uae. Edit in notepad and replace the old whdload game folder with the chasehq whdload game folder. Rename the uae file to reflect the chasehq whdload game.

**Comment by cinemano** [comment]
will do thanks :)

**Comment by cinemano** [comment]
found fiendish freddy but unzipped lha is 116kb that cant be right I
remember having 3 floppies

**Comment by ransom1122** [comment]
Looks incorrect.
http://www.whdload.de/games/FiendishFreddy.html
Download the latest lha version.

**Comment by cinemano** [comment]
65kb file.. its the top lha link on the website right? or are there
additional links?

**Comment by ransom1122** [comment]
ftp://ftp:any@grandis.nu/Commodore_Amiga/Retroplay/Commodore_Amiga_-_WHDLoad_-_Games/F/FiendishFreddysBigTopOFun_v1.3_0500.lha

Access to file is obtained from here
http://eab.abime.net/showthread.php?t=61028

**Comment by cinemano** [comment]
dude you are amazing! Thank you so much! A truly generous community spirit!
Thanks so much!
Will always remember all your help when I load my retropie :)
the adf of fiendish freddy was so slow and the music kept slowing and
speeding. this WHDload version will be a lot better!
Take good care!
George

**Comment by ransom1122** [comment]
No problem. All the best

**Comment by Naviara** [comment]
Hostages is still not working right even with this OCS configuration mentioned above. At first you hear some strange music beeping artifacts during the first stage, but at least it is playable. I also finished the first stage with setting all 3 snipers in position, but after it loads the second part (where the 3 guys dropped out of the helicopter) the screen wents dark and WHDLOAD gives a strange exception on reboot : Exception Adress Error ($B00C) at $9EB536 (ExpMem $34536)
Disk Version crashes at the same area .. When you play around with the speed settings from 14 to 7 Mhz before loading the second part, you get this also to work.

I am on Retropie 4.4 stretch with Raspberry Pi 3B+ and Amiberry V2.20

**Comment by cinemano** [comment]
interesting.. didn't know it was possible to return to config setting
between disks or with the game open. How does one do a savestate of the
game by the way?

**Comment by Naviara** [comment]
I finally got Hostages WHDLOAD to work correctly now.. the "Display" Menu option was finally the key to success - I set resolution to 704 x 216, enabled lined double, fullscreen and correct aspect ratio.. I am not sure, but maybe enabling the "fullscreen" option solved it.

**Comment by midwan** [comment]
@Naviara 
Fullscreen only makes a difference if you're running the emulator under X11, where you can have it as Windowed also. It is ignored if you're running it from the console, as it's always full-screen then. ;)

Line Doubling is only needed if you have Interlace modes, otherwise it doesn't really offer anything. It's meant to eliminate the flickering of Interlace modes, by doubling the lines drawn (hence it comes with a performance hit).

**Comment by ransom1122** [comment]
Intro plays at normal speed but...
I still get shot at the start with this setting.

**Comment by ransom1122** [comment]
@Midwan Can you test Hostages.? 

It should play at normal 7hz speed and you should be able to move your character right without getting shot at immediately.

Is it a fault with the emulator?

**Comment by Naviara** [comment]
@ransom1122 

if you are using WHDLOAD Version you can get this to work with WHDLOAD standard settings, 68020, AGA, 14 Mhz and Blitter set to "normal".and no JIT enable - Any change in speed settings (e.g. from 14 to 7 Mhz) on the first stage will trigger that you get shot immediatly. It is running a bit faster, but it is still possible to solve the stage...

**Comment by ransom1122** [comment]
That fast speed is real bad it makes it unplayable and unrealistic

**Comment by ransom1122** [comment]
Anyone get a fix for titanic blinky adf? Game freezes just before you start. Is it emulator related?

**Comment by midwan** [comment]
This issue has turned into a very large thread, which is difficult to go through and see what remains.
Most of the tests I made with the latest `dev` branch seem to work normally for now, so I suggest we close this issue and open separate ones per game instead, for those that might remain.

**Comment by HoraceAndTheSpider** [comment]
I know this is an old thread, and closed, but Hostages has a recent WHDLOAD update - it will interesting to see if that resolves the previous issue.
