### ISSUE TITLE
SDL2 | Invisible box on Desktop

### ISSUE THREAD

**Issue by idatson** [midwan/amiberry#15]
Ref no: ccc1f11b-b7bb-4963-8e0c-eecc80de8920-0

I have just tried Amiberry so I can get 1920 x 1080 working which seems to be fine. However if I try opening a game through igame the pointer seems to get stuck in an invisible box on the desktop after the game has closed down.

It seems to happen after trying to get out of the game and I usually have to reset the session using F12 and soft rest in the settings. The invisible box survives multiple resets until the machine is hard rebooted then it goes away.

**Comment by Fourdee** [comment]
@idatson 

I'd like to check your current system configuration and setup. Please can you send a bug report: http://dietpi.com/phpbb/viewtopic.php?f=8&t=499#p2184. Thanks.

**Comment by idatson** [comment]
I think it may have something to do with the game being unable to cancel. WHDload says press DEL to quit for example and this does not work. So when you hit F12 and reset the machine it holds on to the game screen size setting for the mouse although the whole desktop is shown.

**Comment by midwan** [comment]
This should be fixed with the port to SDL2, since we won't have to use the resolution switching mechanism (which is what's probably causing this bug). We'll have to test it and make sure of course.

**Comment by midwan** [comment]
@idatson @Fourdee 
This might have been addressed as part of #31 also. Would you mind testing on your end as well to verify?
There was a bug when switching resolution from a Picasso96 one to an AGA/ECS/OCS one, where the Hz calculation would not be called. It caused a black border at the bottom of the screen where there should have been normal graphics lines.

**Comment by Fourdee** [comment]
@midwan 

> Would you mind testing on your end as well to verify?

Can do, using compile of master branch?

**Comment by midwan** [comment]
@Fourdee @idatson 
Yes, the current master branch contains this fix. Feel free to report any other issues if you run into any.

Known issue so far: the CPU performance is lower than the previous stable binary (the one contained in DietPi), reaching about 50% of the number of MIPS (in SysSpeed). Optimizations are in order. :)

**Comment by midwan** [comment]
@idatson 
I'd like to test this on the SDL2 branch I'm preparing as well. Could you give me a list of games it happens with, or does it happen with all of them?
