### ISSUE TITLE
Wireless Playstation3 Controller not found

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#151]
Hi
In the first Version of the SDL1 Version my PS3 Controller was found wenn i start amiberry.
The Sixad programm shows the Controller wenn Amiberry start.
In the new Version my Controller was not found and not shown as PS3 Controller in the Input Panel.
Pls. Can u fix this.

**Comment by HoraceAndTheSpider** [comment]
Are you loading from RetroPie etc?

Which version are you now trying? And what shows in the input panel?

There is a separate branch (fork) with a whole load of new controller options.

I can be 100% sure that PS3 pads will work because I have one myself.

**Comment by CypherXG** [comment]
Loading the 2.5beta from here.
Input Panel shows all the other things like DPad as ... etc.
Link to your Fork?

**Comment by CypherXG** [comment]
Ok. PS3 (Shawan) Controller found.
But DPad is not working. Left and right analog stick is working for directions.
Buttons like X, Circle, Square, Triangle are not working for fire etc.
Select is the Fire Button?
Can not configurate the buttons.

When i watch the Button configs in Jtest
DUp is Button 4
DDown is Button 6
DLeft is Button 7
DRight is Button 5
Select is Button 0
Start is Button 3
Cross is Button 14
Circle is Button 13
Triangle is Button 12
Square is Button 15
L1 is Button 10
L2 is Button 8
R1 is Button 11
R2 is Button 9
LAnalog knob is Button 1
RAnalog knob is Button 2

I am using a Shawan PS3 Controller.
I never had issues before with the other Version from Midwan.
the only problem in the other Versions are that the CD32 Button Config was not correct.
The normal Joystick is working perfectly.

**Comment by HoraceAndTheSpider** [comment]
Have you set up a retroarch Config file?

Select being The fire button is “default” behaviour for PS3 pads due to being button zero; this means the PS3 remapping is not applied. 

I did ask in the first reply if you were using RetroPie but you did not answer. 

By this I would guess that you are not but need to create a file for it, or you need to point the controllers path to the correct location.

The previous build has PS3 “fixes” hard coded ... very bad practice which has been removed, but does mean you need to set this up first.

**Comment by CypherXG** [comment]
Setup done wih Retroarch.
Same.
Can u pls upload your config for testing?

**Comment by HoraceAndTheSpider** [comment]
You should only need to go to the 'Paths' panel and set the`controllers` line to the following

`/opt/retropie/configs/all/retroarch-joypads/`

You will need to enter emulation, exit to the gui, exit amiberry and reload.... (for now at least) 

This should allow it to pick up the above details from the file you have.

**Comment by CypherXG** [comment]
Sry. Doesn't work by me.
Path to the config was set.
Controller was found....ok
The Problem was, that the Buttons that i try to assign are wrong or did not work.
So when i try to assign for example DPad Up with Joy2 Up than for example Start Button has the up assign. I test all possibilities but many commands are not recognized.
Left Trigger is greyed out, right Trigger i can assign ?

I think there are some difference between an org. PS3 Controller and my Shawan PS3 Controller.

**Comment by HoraceAndTheSpider** [comment]
The difference between the two controller types does 

You say “path to the Config was set” ... can you show screenshots or photo please. 

You will not need to assign anything manually to use normal joystick controls.

**Comment by HoraceAndTheSpider** [comment]
Reading you above two posts - if the custom controls page shows “HotKey” and is greyed out on your “select” button the. The Config file is probably being read.

You would also see, by clicking “HotKey” <> that menu is not n “circle” (button 13?)

It looks like your retroarch Config file is set up very unusually.

For escarole, retroarch “b” button is normally X on a PS pad... this would be “red” or “fire” on the Amiga

Your setup has retroarch b = button 15 = Square button (going by your jtest) ... this is not the normal way to set this up? Did you create this manually or create in RetroPie?

**Comment by CypherXG** [comment]
Here you see some Pics:
My PS3 Controller:
http://www.directupload.net/file/d/4904/uybhm33l_jpg.htm

http://www.directupload.net/file/d/4904/v6ul7p2c_jpg.htm

My Config for the Controller. I moved this now to the uae4arm directory.
http://www.directupload.net/file/d/4904/umscjr4y_jpg.htm

The Path Config Panel
http://www.directupload.net/file/d/4904/n9nhul2y_jpg.htm

You see the Custom Control Panel with the greyed out Fields
http://www.directupload.net/file/d/4904/bhnh423d_jpg.htm

Here you see that the left triffer works perfectly
http://www.directupload.net/file/d/4904/r2naiheo_jpg.htm
when i press the Dpad nothing happend
http://www.directupload.net/file/d/4904/t83obypn_jpg.htm
Select is the Fire button
http://www.directupload.net/file/d/4904/jtxwemxu_jpg.htm

When i assign a Button the Wrong button was assigned Example Triangle
http://www.directupload.net/file/d/4904/rhnfh98l_jpg.htm
Pressed Triangle doesn't work
http://www.directupload.net/file/d/4904/4adn8flm_jpg.htm
The right Trigger has the command
http://www.directupload.net/file/d/4904/zatm9rs2_jpg.htm

I hope i can help you with this pictures

**Comment by HoraceAndTheSpider** [comment]
Yes these help thank you. 

You need to set this:

 **Path Config Panel**
http://www.directupload.net/file/d/4904/n9nhul2y_jpg.htm

The third box "Controller files" needs to be set to : `/opt/retropie/configs/all/retroarch-joypads/`

Then:
- Enter emulation
- Return to the gui
- Exit amiberry 
- Reload Amiberry.... (for now at least)

On the 'custom panel' you have hopefully helped find somethign else that needs fixing though :)

**Comment by CypherXG** [comment]
When i do this it's the same.

**Comment by HoraceAndTheSpider** [comment]
I have just realised. Your config file is called `SHANWANPS3GamePad.cfg` but your device is registered as `PLAYSTATION(R)3 Controller`

Please try creating a copy of the .cfg file and renaming to `PLAYSTATION(R)3 Controller.cfg`

I assume you are not setting this up in RetroPie, but some other form of RetroArch ? I need to know this in order to establish why your pad is set up this way.

**Comment by CypherXG** [comment]
Oha.....i renamed it and it's working... :-)
All buttons are working. No Errors.....
