### ISSUE TITLE
CD32/CDROM is not booting any Images like iso,ccd etc.

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#154]
Hi 
I use the HoraceAndTheSpider Version.
My Issues is, that the CDRom does not boot anything.
I use ISO Files, CD32 Games, Audio CD, ccd Images etc.
For CD32 Emulation i use the CD32 Kickrom and the CD32 Ext. Rom.
In the previous Versions the CD32 CDRom is working.
Can you fix that?

**Comment by CypherXG** [comment]
Sry, my fault. CD32 must set in Extra Chipset.

**Comment by midwan** [comment]
:)
Then I guess this is a non-issue?

**Comment by CypherXG** [comment]
Yep. You can close this :-)
