### ISSUE TITLE
Make guisan, flac, mpg, etc... stuff optional?

### ISSUE THREAD

**Issue by vanfanel** [midwan/amiberry#158]
Hi there, Midwan

I am very excited about the upcoming version of this UAE iteration, and I was wondering if you could make the GUI stuff optional on building. I would like an executable-only version to which I could pass my config files and thats it, no need to build a bloated emulator with a GUI I will never use or need and dependencies to read CD images I am not going to use.
So, would that be possible, please?

**Comment by midwan** [comment]
There are currently no plans to separate the GUI from the rest, sorry.
Perhaps in the future we could look into this, but we can't make it a priority at the moment. We simply have too many other things to fix/improve and not enough people to do them all :)

You do know that you can run the emulator without a GUI however, right?
You can pass parameters from the command line to load a config file, don't open the GUI and go straight into emulation, if that's what you want.
