### ISSUE TITLE
Problem building because guisan depends on desktop GL

### ISSUE THREAD

**Issue by vanfanel** [midwan/amiberry#160]
Hi there,

It seems guisan needs the desktop GL headers to build, which does no make much sense on the Raspberry Pi:

`src/opengl/openglgraphics.cpp:71:19: fatal error: GL/gl.h: No such file or directory
`

It also happens in src/guisan/include/guisan/opengl/openglimage.hpp.
In both case, you should include /usr/include/SDL2/SDL_opengl.h instead of GL/gl.h, which is of no use on the Raspberry (not currently accelerated by default).
I believe OpenGL is not used by guisan on amiberry anyway, but it won't build anyway due to this.

**Comment by midwan** [comment]
@vanfanel 
Guisan does not specifically require GL, it's SDL2 that can be configured one way or the other.
If SDL2 is configured to use OpenGL, then everything using SDL2 will do so as well (guisan being one of them).

We don't specifically use OpenGL in the emulator either, we just request the handling of the screen from the SDL2 framework, it takes care of using whatever options are available in your system (and of course, depending on how it was configured).

Which version of the distro are you running on? I found that Stretch seems to behave much more stable than Jessie, with the OpenGL drivers installed. Or you can build SDL2 from source and configure it to use only the "rpi" driver, which will use a full-screen display from the console.

**Comment by vanfanel** [comment]
I am using Raspbian (Lite, no X allowed here).
OpenGL drivers are not needed at all with SDL2 since SDL2 uses dispmanx+GLES2 to draw on screen.
My SDL2 sources are built X-less, no dependencies on X allowed either, so it runs fullscreen from the console as all emulators and games should run on the Pi.
Guisan does not use OpenGL, but it TRIES to build with DESKTOP GL support: it has nothing to do with SDL2, it's guisan trying to include GL/gl.h directly: it works for you because you have GL/gl.h installed (desktop GL includes = wrong). But it does not work for me because I don't have any X-related stuff on my system an DESKTOP GL (GL/gl.h is part of the dev packages for it) depends on X11 to work.

The fix I propose is simply removing the GL stuff from guisan (you are not using it anyway), or at least include SDL2/SDL_opengl.h instead if the "wrong" desktop GL headers.

**Comment by midwan** [comment]
@vanfanel Recreated, I'll work on a fix and update this place.

**Comment by substring** [comment]
Despite this is closed, may I report I get the same error with the including both SDL and SDL2 ? On my side, SDL_ttf.h is in the SDL include dir, not the SDL2, which forces to include SDL/SDL_opengl.h leading to the same error (no GL/gl.h)

**Comment by midwan** [comment]
@substring You should NOT include both SDL1 and SDL2 in the same project, or unexpected things will happen (and quite possibly break)...

**Comment by midwan** [comment]
@substring SDL_ttf.h is part of SDL2_ttf (libsdl2-ttf-dev)

**Comment by 2play** [comment]
Just wanted to say this appears to be the case also on the latest clean RetroPie base 2.5.1
All prerequisites ok but copiling fails with
`g++  -Ofast -frename-registers -pipe -Wno-shift-overflow -Wno-narrowing  -std=gnu++14 -I./include -I/usr/include/SDL2 -DUSE_VCHIQ_ARM -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -D_REENTRANT -MD -MT src/sdl/sdl.o -MF src/sdl/sdl.d  -c -o src/sdl/sdl.o src/sdl/sdl.cpp
In file included from ./include/guisan/sdl.hpp:65:0,
                 from src/sdl/sdl.cpp:61:
./include/guisan/sdl/sdltruetypefont.hpp:50:21: fatal error: SDL_ttf.h: No such file or directory
 #include "SDL_ttf.h"
                     ^
compilation terminated.
<builtin>: recipe for target 'src/sdl/sdl.o' failed
make[1]: *** [src/sdl/sdl.o] Error 1
make[1]: Leaving directory '/home/pi/code/amiberry/amiberry-dev/external/libguisan'
Makefile:440: recipe for target 'guisan' failed
make: *** [guisan] Error 2
make: *** Waiting for unfinished jobs....
`

**Comment by midwan** [comment]
As the log indicates,
`SDL_ttf.h: No such file or directory`

You don't seem to have the `sdl2-ttf-dev` package installed in your system.

**Comment by 2play** [comment]
I fixed the above with:
`sudo apt-get install libsdl2-ttf-dev`
Can be found/check via:
`find /usr|grep SDL_ttf`

Then new error:
**fatal error: SDL_image.h**

**Comment by midwan** [comment]
Please check the requirements for compiling the SDL2 version. :)

`sdl2-image-dev` is also one of those requirements.

**Comment by 2play** [comment]
run `sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev`
and did a `sudo make clean`
running compile and reverting

**Comment by 2play** [comment]
Final fixed result:
1. Fix *SDL_ttf.h* with
`sudo apt-get install libsdl2-ttf-dev`

2. Install SDL2 prerequisites:
`sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev`

3. Clean compile 
`sudo make clean`
and compile for rpi3 (dev https://github.com/midwan/amiberry/wiki/Compiling-Development-Branch) with
`sudo make -j2 PLATFORM=rpi3`
