### ISSUE TITLE
AmigaEmu on RecalBox x64

### ISSUE THREAD

**Issue by maddis4free** [midwan/amiberry#162]
hi there,

would u be able to port this fine software for the x64-version of recalbox?

regards

**Comment by midwan** [comment]
@maddis4free thanks for the interest!
If by x64 you mean Intel/AMD architectures, then that will have to wait I'm afraid.

Currently the code is targeting ARM platforms specifically, including inline assembly for those in some places.
Perhaps in the future we can make a x86/x64 port, but for now we can't prioritize that as we have a lot to do still (and time/people involved are limited).
