### ISSUE TITLE
Control Menu using joystick?

### ISSUE THREAD

**Issue by rsn8887** [midwan/amiberry#167]
Currently, controlling the menu requires a mouse. Is it possible to add joystick control to set menu options? 

It could just be as simple as adding joystick-control to the mouse pointer movement, and mapping joystick button to mouse click in the menu. That would be fine.

**Comment by Darknior** [comment]
Yes it is a really good idea, but maybe not so easy to do ...

**Comment by midwan** [comment]
This is already implemented in the "dev" branch ;)
