### ISSUE TITLE
Unneded headers and libraries for SDL2

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#168]
SDL2 for rpi does not need the files in /opt/vc, so you can do something like this

diff --git a/Makefile b/Makefile
index 512923a..558bc7c 100644
--- a/Makefile
+++ b/Makefile
@@ -57,8 +57,7 @@ else ifeq ($(PLATFORM),rpi3-sdl2)
 USE_SDL2 = 1
     CPU_FLAGS += -march=armv8-a -mfpu=neon-fp-armv8 -mfloat-abi=hard
     MORE_CFLAGS += -DARMV6T2 -DUSE_ARMNEON -DCAPSLOCK_DEBIAN_WORKAROUND -DUSE_SDL2
-    MORE_CFLAGS += -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads
-    LDFLAGS += -lbcm_host -lvchiq_arm -lvcos -llzma -lfreetype -logg -lm -L/opt/vc/lib
+    LDFLAGS += -llzma -lfreetype -logg -lm
     PROFILER_PATH = /home/pi/projects/amiberry/amiberry-sdl2-prof
        
 else ifeq ($(PLATFORM),rpi2-sdl2)

**Comment by solskogen** [comment]
Wow. That looked like shit. But like this then:

#
# SDL2 targets
#       
else ifeq ($(PLATFORM),rpi3-sdl2)
USE_SDL2 = 1
    CPU_FLAGS += -march=armv8-a -mfpu=neon-fp-armv8 -mfloat-abi=hard
    MORE_CFLAGS += -DARMV6T2 -DUSE_ARMNEON -DCAPSLOCK_DEBIAN_WORKAROUND -DUSE_SDL2
    LDFLAGS += -llzma -lfreetype -logg -lm
    PROFILER_PATH = /home/pi/projects/amiberry/amiberry-sdl2-prof

**Comment by midwan** [comment]
@solskogen Thanks for the suggestion!
I was under the impression that it needs those in order to use the "rpi" driver, if SDL2 has been compiled with that configured?
I'll test it out and see, if it works fine without them, of course we'll remove them.

**Comment by midwan** [comment]
@solskogen confirmed, it doesn't seem necessary.
I also found that a few more libs are not really used, so we can remove those as well!

Thanks!
