### ISSUE TITLE
ONE Keyboard Mapping for  Player 1 e 2 (GPIO)

### ISSUE THREAD

**Issue by RINNAA** [midwan/amiberry#169]
Hi !
I read several posts but I did not understand if it is possible to remap the keyboard with the Joysticks 1 and 2 (Mame style). I use GPIO as encoders that simulate the keyboard.

Is there a guide on how to configure the keys and in which file to write the configuration?

I also read that you could use the "retroarch.cfg" configuration file, is this correct?

Thanks to everyone and congratulations for the project!

Rinna

**Comment by HoraceAndTheSpider** [comment]
The retroarch.cfg can be selected from the “paths” panel.

The first joystick option is always a keyboard remap, and if your retroarch file is detected and read, then the keyboard mapping will use what it finds there.

You will be able to check this by  looking at how the input “device” is named in the input panel... “Retroarch Keyboard as Joystick”

There is currently no support to pick up player 2 retroarch keyboard controls in this way, although I have it planned for detection of inputs 2-4 if used in the retroarch cfg file.

**Comment by HoraceAndTheSpider** [comment]
If you do not use any form of retroarch, then you can simply create a retroarch cfg (plain text file) in the Amiberry folder and add the necessary syntax that way.

**Comment by fgambarelli** [comment]
Thanks for the answer, so currently there is no way to remap the player 2 on the keyboard?
Should we wait for the next versions?

Rinna

**Comment by HoraceAndTheSpider** [comment]
There will be a release version probably before I look at the player 2 option, so it will likely be in the next version +1 !

**Comment by arcadeforge** [comment]
Interested in this old enhancement as well. Could you give a short overview where to start, when player 2 via keyboard shall be added? Cheers

**Comment by midwan** [comment]
@HoraceAndTheSpider 
This has been around for quite a while now... Where are we with it?

**Comment by HoraceAndTheSpider** [comment]
Nowhere tbh - the keyboard-as-joystick code would need a bit of an overhaul, as the second one of these would start picking up as joy1 which might have adverse side effects on real controllers

**Comment by midwan** [comment]
I've implemented support for multiple keyboard layouts, same as in WinUAE.
There are 5 layouts provided currently:
1. Layout A: NumPad, 0/5 = Fire1, Decimal/Del = Fire2
2. Layout B: Cursor keys, RCtrl/RAlt = Fire1, RShift = Fire2
3. Layout C: WSAD, LAlt = Fire1, LShift = Fire2
4. Keyrah: Cursor keys, Space/RAlt = Fire1, RShift = Fire2
5. iPac: Cursor keys, LAlt/LCtrl = Fire1, Space = Fire2

You can assign them in any port you want, and you can of course assign 2 or more of them at the same time.
For the moment, these are not remappable. Perhaps that will change...

If you want to test out this functionality, you'll need to checkout the `kbdlayout` branch and compile from there.

**Comment by midwan** [comment]
Note: this has now been merged into `dev` - the `kbdlayout` branch is deleted.
Support for remapping the keys is not there yet, but I'll look into it later.

**Comment by midwan** [comment]
Update: `dev` now has support for up to 4 remappable keyboard inputs, using RetroArch mapping.
Additionally, you can use the standard XInput mapping to map any number of keyboard inputs as game controllers, by editing the `gamecontrollerdb.txt` file included. Those will show up as Joysticks/Gamepads in the Input panel, when recognized.
