### ISSUE TITLE
Keypad emulation?

### ISSUE THREAD

**Issue by vanfanel** [midwan/amiberry#171]
Hi,

Sorry for opening so many issues today! I got the Amiga fever with this fantastic emulator! :dancer: 
Thing is, the game "Ishar: Legend of the fortress" by Silmarills needs a numeric keypad key to be pressed to pass the language selection screen. However, no matter what, keypad does not seem to work.
So, are the numeric keypad keys implemented/supported?

**Comment by midwan** [comment]
There is a known bug with the SDL2 version currently, some keys are not recognized.
These include the function keys (except those mapped to Open GUI and Quit), arrows, keypad and Ctrl, Alt.

They work as mapped to joystick events (they will trigger up/down/left/right and fire) but not as normal keyboard input for some reason.

I'll look into this and fix it soon. :)

**Comment by Voljega** [comment]
They is indeed something fishy regarding keypad numbers, I noticed some games asks for '1', '2', '3' etc for selecting an option before launching game not only accept only numerical key pad press, but the keyboard also have to be configured as qwerty in the system, the keypad numbers aren't recognised when configured in azerty.

If possible, with the small bluetooth keyboards everybody uses today lacking a keypad, it would be great to have a double mapping of regular number keys and number keypads on the keyboard main number keys

**Comment by rsn8887** [comment]
Maybe as an on/off option so it can be enabled or disabled, e.g.
“Remap keypad numbers to regular numbers - on/off”

**Comment by midwan** [comment]
This has been fixed now
