### ISSUE TITLE
[WHDLoad issue] Barbarian The Ultimate Warrior (Palace)

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#173]
**Barbarian The Ultimate Warrior / Palace [version 1.1 (12/03/2017)]** - ECS/OCS
=> game does launch. However impossible to play as it's running at very high speed whatever parameter I set in the uae. Thanks to @maxbeanz from [Retropie's forum](https://retropie.org.uk/forum/topic/12656/amiga-amiberry-whdload-holy-grail-amiberry-s-official-thread/19) for reporting that one.
[uae for Barbarian](https://github.com/midwan/amiberry/files/1293649/BarbarianPalace.txt)

**Comment by nemo93** [comment]
Seems @blinkydoos got a workaround for this one (https://github.com/HoraceAndTheSpider/UAEConfigMaker/issues/25). Could you please share your uae here?

**Comment by HoraceAndTheSpider** [comment]
To config, i have this working on the latest branch of Config Maker settings - i was playing it last night.

I am just working on some improvements to fix the speed issue.

**Comment by blinkydoos** [comment]
@nemo93 
Use 68000, 7mhz and a A600 Kickstart Rom.

You can do this for nearly all games that play too fast.

**Comment by HoraceAndTheSpider** [comment]
F1 to start Barbarian iirc.

**Comment by nemo93** [comment]
Argh! silly me :) I simply forgot about that. Amazing to rediscover this game. Thanks!
