### ISSUE TITLE
[WHDLoad issue] Battle Isle

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#174]
**Battle Isle [version 1.9 (07.10.17)]** - ECS/OCS
=> game does NOT launch. I got the following message within the whdscript_debug file: `The data/disk-files are damaged or it is an unsupported version.` I've followed all directions given [there](http://www.whdload.de/games/BattleIsle.html) but still no luck. 
**Note:** the version which includes all data disks is not working either and output the exact same error message.
[uae for Battle Isle](https://github.com/midwan/amiberry/files/1356033/Battle.Isle.txt)

**Comment by Dalai-** [comment]
Battle Isle works if you add the WHDLoad tooltype "CUSTOM1=3" (.e.g. to the Battle Isle WHDBoot file in save-data/Autoboots). See: http://eab.abime.net/showthread.php?t=68704&page=5

**Comment by nemo93** [comment]
I do confirm Dalai's tip got the game to launch. As this is nothing related to Amiberry in fact but tied to WHDload package of the game I'm closing this case off. Thanks all!
