### ISSUE TITLE
[WHDLoad issue] Cannon Fodder

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#176]
**Cannon Fodder [v1.0 (25.01.2001)]** - ECS/OCS
=> game runs fine. However at the very first intro mission screen where you can see a chopper/helicopter hovering over jungle, you could see that the tail/rotor is not there. This bug can be seen only on this first intro screen, on the following missions tail is there no problem.
[uae for Cannon Fodder](https://github.com/midwan/amiberry/files/1290625/Cannon.Fodder.txt)

**Comment by HoraceAndTheSpider** [comment]
Switch off JIT to resolve this issue.

**Comment by HoraceAndTheSpider** [comment]
see issue #176
