### ISSUE TITLE
[WHDLoad issue] New York Warriors

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#178]
**New York Warriors [version 1.4 (07.10.17)]** - ECS/OCS
=> game does run absolutely fine however there's no sound effect. To be accurate you can hear sound effects but only once in a while (once every minute or so without any clear patterns of when sounds would be heard).
[uae for New York Warriors](https://github.com/midwan/amiberry/files/1282803/New.York.Warriors.txt)

**Comment by blinkydoos** [comment]
@nemo93 
Use 68000, 7mhz and A600 Kickstart Rom.

**Comment by nemo93** [comment]
Thanks @ghost. Indeed works flawless with latest Amiberry 2.14+. For the record below the uae that I use.
[New York Warriors.uae](https://github.com/midwan/amiberry/files/1755928/New.York.Warriors.txt)
