### ISSUE TITLE
[WHDLoad issue] Panza Kick Boxing

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#179]
**Panza Kick Boxing [version 1.6 (01.07.06)]** - ECS/OCS
=> runs ok yet glitches appear on the boxers characters during an animation/move. Just launch a fight against any opponent, do some moves and the glitches would appear pretty quickly.
[uae for Panza Kick Boxing](https://github.com/midwan/amiberry/files/1282798/Panza.Kick.Boxing.txt)

**Comment by blinkydoos** [comment]
@nemo93 
I don't have Panza Kick boxing but I tried Best of the Best (which is an updated version of Panza) but didn't notice any glitches though.

**Comment by nemo93** [comment]
@ghost I didn't know that! I learn something. I do confirm that Panza keeps having glitches which have been fixed in Best of Best. Same game (except you don't have Panza intro but most of us should live with that :)). 

Works flawless with latest Amiberry 2.14+. For the record below the uae that I use.
[Best Of The Best - Championship Karate.uae](https://github.com/midwan/amiberry/files/1755936/Best.Of.The.Best.-.Championship.Karate.txt)
