### ISSUE TITLE
[WHDLoad issue] Second Samurai AGA

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#180]
**Second Samurai [version 1.1 (01-Feb-2001)]** - AGA
=> graphical mess. Logo and loading screens are fine but as soon as you enter the main menu screen it's messy. It's a bit hard to describe but clearly the colors are not where they are supposed to be! **Please do note that the ECS/OCS version of this game is working like a charm.**
[uae for Second Samurai AGA](https://github.com/midwan/amiberry/files/1282813/Second.Samurai.txt)

**Comment by midwan** [comment]
Fixed with 29fe7770ec61a26224fef6ad74dfe679b248ed53 in `dev`

**Comment by midwan** [comment]
the `dev` branch will be merged into `master` as soon as beta testing is complete, so we can close this issue for now.
