### ISSUE TITLE
[WHDLoad issue] Shadow Fighter AGA

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#181]
**Shadow Fighter [(Version 1.0 (24.03.2007))]** - AGA
=> runs ok yet too slow (compare with the ECS version to see what the real speed should be). **Please do note that the ECS/OCS version of this game is working like a charm.** Thanks to @vultureg7 and to @ransom1122 for reporting and confirming that one (original ticket #138).
[uae for Shadow Fighter](https://github.com/midwan/amiberry/files/1293641/Body.Blows.txt)

**Comment by midwan** [comment]
This seems to be working normally in `dev` - tested on an RPI4.
