### ISSUE TITLE
[WHDLoad issue] Striker 

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#182]
**Striker [(version 1.0 (01.11.2001))]** - ECS/OCS
=> runs ok yet character sprites flicker during the game. Problem occurs on both WHDLoad & ADF versions of the game. Thanks to @ransom1122 for reporting and confirming that one (original ticket #146).
[uae for Striker](https://github.com/midwan/amiberry/files/1356029/Unreal.txt)

**Comment by nemo93** [comment]
@Blinkydoos you seem to have a workaround for that one too. May I kindly ask for your uae file please? Thanks!

**Comment by blinkydoos** [comment]
@nemo93 
Change Blitter to 'Immediate'. You will also need to change it to 68000, 7mz and A600 Kickstart Rom, as noted in the Barbarian issue.

**Comment by nemo93** [comment]
Works flawless with latest Amiberry 2.14+ with the changes shared by @ghost. @HoraceAndTheSpider if you read this please modify UAEconfmaker to use kick205 and Immediate blitter. The automatic config I got from your tool was not reflecting the above changes and made the sprites to flicker. Thanks! 

For the record below the uae that I use.
[Striker.uae](https://github.com/midwan/amiberry/files/1755949/Striker.txt)
