### ISSUE TITLE
[WHDLoad issue] XP8 AGA

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#185]
**XP8 [version 1.2 (02.01.03)]** - AGA
=> Text menu on the intro screen is garbled. **Please do note that the ECS/OCS version of this game is working like a charm.**
[uae for XP8 AGA](https://github.com/midwan/amiberry/files/1356086/XP8.txt)

**Comment by midwan** [comment]
Actually, this is still an issue. Re-opening.

**Comment by midwan** [comment]
"Immediate blits" solves this issue.
@HoraceAndTheSpider could we add that in the XML db please?
