### ISSUE TITLE
[WHDLoad issue] Zool AGA

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#186]
**Zool [version 2.0 (13-jan-08)]** - AGA
=> graphical mess. Same as Second Samurai. Logo/main screens are fine yet intro and game itself have messed up graphics. Still hard to describe but it's like colors are not properly rendered.
[uae for Zool AGA](https://github.com/midwan/amiberry/files/1282827/Zool.txt)

**Comment by midwan** [comment]
Fixed with 29fe7770ec61a26224fef6ad74dfe679b248ed53 in `dev`

**Comment by midwan** [comment]
the `dev` branch will be merged into `master` as soon as beta testing is complete, so we can close this issue for now.
