### ISSUE TITLE
[WHDLoad issue] Zool 2 AGA

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#187]
**Zool 2 [Version 1.0 (28.05.2002)]** - AGA
=> graphical mess. Same as Second Samurai and Zool. Logo/main screens are fine yet game itself have messed up graphics. Still hard to describe but it's like colors are not properly rendered.
[uae for Zool 2 AGA](https://github.com/midwan/amiberry/files/1282838/Zool.2.txt)

**Comment by mattsoft** [comment]
What is interesting about this is if I switch to NTSC in Amiberry, then back to PAL, the graphics are FIXED! ???

**Comment by ZappaUtopia** [comment]
Yes, I think this is a very concerning "bug". I can confirm this. On the WHDLoad games (may happen on ADF as well) Zool AGA, Zool 2 AGA, Second Samurai AGA and maybe more. 

Load the game, start the game and the graphics are completely screwed. Goto the GUI and change it to NTSC and resume game. The graphics are fixed ! You can then turn off NTSC and the graphics are still fixed !

**Comment by ZappaUtopia** [comment]
@midwan Have you had any time to confirm this ? Would it be something you could fix or would TomB be needed for this ?

**Comment by midwan** [comment]
@ZappaUtopia 
No, not yet... I'll test it tonight and see

**Comment by midwan** [comment]
Confirmed

**Comment by aersoy** [comment]
I can see this bug with TrapsNTreasures as well. Happens at the Starbyte logo intro, but not during the game (game is perfectly playable). Seeing the problem early on might make this game a good candidate for testing.

I'm using Retropie 4.4.1. If I install amiberry from binary there are no problems with graphics but my controller config is not read from `hostprefs.conf`. When installed from source, `hostprefs.conf` works, but the graphics problems occur. So the bug seeped sometime after the binary release.

**Comment by midwan** [comment]
@aersoy 
Traps 'n Tresures is now fixed, with 65eb34943347a7d72046c5e080f332e6c8c185fd (only in the `dev` branch). The intro logo used a HAM screenmode, and there was a bug with the colors there.

However, I noticed it doesn't display correctly in the title screen afterwards, although the rest seem to be fine.

**Comment by midwan** [comment]
This is fixed with 29fe7770ec61a26224fef6ad74dfe679b248ed53 (currently in the `dev` branch until further tests are made)

**Comment by ransom1122** [comment]
Was there an Amiberry fix for Zool AGA games and Donk the Samurai Duck AGA where selecting NTSC then deselecting NTSC fixes manor gfx problem in game?

**Comment by midwan** [comment]
the `dev` branch will be merged into `master` as soon as beta testing is complete, so we can close this issue for now.
