### ISSUE TITLE
SDL2 | Menu display on small screens 

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#19]
I have recently installed Retropie onto a PiGrrl machine, which has an Adafruit 2.8" PiTFT display 320x240.

Obviously this causes chaos when I press f12, so I'd like to support the case for even a minimal size menu display when either an host option is set (I.e. Not with the game config!) or better still, when a small display is auto detected.

It could probably suffice for this to be like the fs-UAE option screen (although not as pretty!!) and only have options for control changes and disk swapping.

I would be happy to help design something, even if I can't code it, it it would help! 

Thanks

**Comment by midwan** [comment]
Interesting idea, but we'll have to think about it a bit.

The GUI has a minimum resolution of 600x200 currently, to fit everything there. To support a smaller resolution than that, things will have to get really crammed in half the space.

Ideally it should be adaptive, depending on the resolution you're running it on. Higher resolutions should also be taken advantage when it makes sense (nobody likes scrolling much).

We'll look into this after #8 is completed.

**Comment by ariath** [comment]
Due to the small size of these screens, maybe the solution is making an alternative GUI system, more simple, without widgets.

Maybe something similar to MIST's FPGA menu?
http://somuch.guru/wp-content/uploads/2015/09/minimig_iGame.jpg

Because you aren't using a graphical GUI, maybe it is even easier to implement.

See ya!

**Comment by HoraceAndTheSpider** [comment]
Yes , that's the sort of thing.

Even just a basic text on the default OS screen (like raspi-config screen or whatever)

Keeping in mind that it doesn't need to have 100% of the available options.

**Comment by midwan** [comment]
Or we could just check the resolution and adapt the GUI to that automatically. Using scroll bars where needed for example.

But what should be the minimum resolution supported then? We should test this in such a scenario and see which approach works best.

**Comment by Fourdee** [comment]
As per @HoraceAndTheSpider 

> 320x240

I'd recommend the same. Its the lowest resolution panel for SBC's i've found (http://www.waveshare.com/3.2inch-rpi-lcd-b.htm). Beyond that, your looking at 16x2 matrix (http://www.raspberrypi-spy.co.uk/2012/07/16x2-lcd-module-control-using-python/).

**Comment by midwan** [comment]
OK, thanks for the input from all of you. I'll look into this and keep you posted.

**Comment by midwan** [comment]
Note to self: Test this approach in the SDL2 branch

**Comment by midwan** [comment]
SDL2 will automatically scale the display to the resolution given, and this works for upscaling as well as downscaling.

The results will be ugly of course, if we downscale a 800x480 image to 320x240, but it should still be viewable.

**Comment by midwan** [comment]
Does anyone have a display with a resolution of 320x240 to test with?

The current SDL2 version already does auto-scale to fit the native resolution, so I was wondering how it looks like that. If it's not too awful, maybe we don't need to redesign the whole GUI and we can close this issue.

**Comment by HoraceAndTheSpider** [comment]
I do, but I need to fix up my PiGrrl again.... will look into that for you!

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Any luck with this? :)

**Comment by HoraceAndTheSpider** [comment]
No, the PiGrrl has been a pain but I have a new Freeplay CM3 arriving soon.... should be the same size of display :)

**Comment by midwan** [comment]
Tested with SDL2, works on any display size you have. You can even have the window as resizable if running on the desktop (coming in a new version) and scale it up/down any way you want.

**Comment by HoraceAndTheSpider** [comment]
My new CM3 unit is currently sitting in customs.... :(
