### ISSUE TITLE
Save state location ?

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#192]
Hello I tried to use save state with an ADF game.
Due to my special setup (amiberry is copied and launched from ram) I couldn't find the save state file.
It's also not possible to reload it wherever it is.

### Expected behavior
Saving state should generate a save state file somewhere and it should be possible to reload it

### Actual behavior
No save state file, and it's impossible to reload saved state even in same 'session'

### Steps to reproduce the behavior
Not sure if it is my setup problem, so just try it.

**Comment by blinkydoos** [comment]
I just tried this as I just built the latest SDL1 DEV version 2 hours ago. It seems to work fine.

Savestates are saved in -
`amiberry/savestates`

and the screenshot in -
`amiberry/screenshots`

**Comment by Voljega** [comment]
Ok I don't have any savestates sub directory so maybe it's the issue I will try creating one

**Comment by midwan** [comment]
@Voljega Yes, you'll need those directories under the executable in order to generate the files.
Perhaps we can add those as configurable under the "Paths" panel, because now they're hardcoded to be expected under the binary's starting location...

**Comment by HoraceAndTheSpider** [comment]
@midwan yes, when I am working on state improvements i am planning on adding the path values :)

**Comment by Voljega** [comment]
cool, anyway if needed we may patch it on our side, recalbox including standard common paths for saves and screenshots for all emulators

on a side note, not far from the subject (paths), I noticed a minor bug when the bios path in adfdir.conf doesn't include the last `/` (`/recalbox/share/bios` instead of `/recalbox/share/bios/` for instance), the 'ROM' menu is not populated with the bios files even when they were well written in adfdir.conf

The emulator still works fine though and manages to find the bios, it's only a GUI minor issue

**Comment by midwan** [comment]
@Voljega Thanks for that, I'll look into it...
Can we close this issue in the meantime?

**Comment by midwan** [comment]
@Voljega err, wait.. "bios path" ?  I don't think we have such an entry there...

**Comment by Voljega** [comment]
Hmmm in GUI it's in Paths and it's named 'System Roms'
But it's `named `rom_path` in `adfdir.conf` :

```
path=/tmp/amiga/amiberry/adf/
config_path=/tmp/amiga/amiberry/conf/
rom_path=/recalbox/share/bios/
ROMs=6
ROMName=CD32 extended ROM rev 40.60 (512k)
ROMPath=/recalbox/share/bios/CD32ext.rom
ROMType=4
ROMName=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
ROMPath=/recalbox/share/bios/kick13.rom
ROMType=1
ROMName=KS ROM v2.04 (A500+) rev 37.175 (512k) [390979-01]
ROMPath=/recalbox/share/bios/kick20.rom
ROMType=1
ROMName=KS ROM v3.1 (A1200) rev 40.68 (512k) [391773-01/391774-01]
ROMPath=/recalbox/share/bios/kick31.rom
ROMType=1
ROMName=CD32 KS ROM v3.1 rev 40.60 (512k)
ROMPath=/recalbox/share/bios/kick31CD32.rom
ROMType=2
ROMName= AROS KS ROM (built-in) (1024k)
ROMPath=:AROS
ROMType=1
```

**Comment by midwan** [comment]
@Voljega Thanks for confirming.
Regarding the paths issue, the default is <binarydir>/kickstarts/ - I assume you changed the value and saved the config? Is that when the problem occurred?
Or did you follow another route?

**Comment by Voljega** [comment]
No I generate programmatically my adfdir.conf (as pasted) in binarydir/conf alongside my *.uae file and then launch the emulator with just ./amiberry and everything loads quite nicely

**Comment by midwan** [comment]
@Voljega commit 1bf216e should have fixed that ;)
