### ISSUE TITLE
[Latest SDL1 Dev] Configuration 'Load' button doesn't work

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#194]
You can double click a configuration and it loads but if you use the 'Load' button none of the settings seem to change.

**Comment by midwan** [comment]
I can't seem to recreate this...

Tested:

1. Start emulator up (sdl1 version)
2. It starts with the Quickstart option set to A500, and I have 2 example configs (one for A500, one for A1200).
3. I select and Load the A1200 config.
4. Checked the CPU and FPU options, they have changed accordingly.
5. I select and Load the A500 config.
6. Checked the CPU and FPU options, they have changed accordingly.

**Comment by blinkydoos** [comment]
It doesn't seem to work for me unfortunately I have 3 custom configs (for RetroPie) that I can see in the `Configurations` section, CD32, rp-a1200 (A1200) and rp-a500 (A500). If I click on one and then click the `Load` button then it doesn't seem to load it. I checked if the CPU & Chipset changed etc.but no.  It works fine if I double click the name of my configuration.

**Comment by midwan** [comment]
@blinkydoos 
Do you select the configuration with the mouse, keyboard or joystick?
Does it show in the "Name:" and "Description:" fields when you do so?
It might be that it's not selected when you click on Load.

I just tested it again on RetroPie, with the two bundled configs it comes with (a500 and a1200), both load fine here...

**Comment by blinkydoos** [comment]
OK, I did the following so we can be on the same page.

Load and Boot a Quickstart A1200 config, go back to the GUI then click your A500 config (in configurations) and click 'Load'. Now see if your CPU and Chipset options are still at A1200.

**Comment by blinkydoos** [comment]
There is a big problem now i'm afraid, i'm not sure what commit it was (maybe https://github.com/midwan/amiberry/commit/409df536feb654e3563b90d668a28d62fddb0be6) but now if you are in-game and go to the GUI it resets the options or something, so you can't go back to the game.

**Comment by blinkydoos** [comment]
Unfortunately, there is a big problem now. I don't know if it was this commit https://github.com/midwan/amiberry/commit/409df536feb654e3563b90d668a28d62fddb0be6 but if you are in-game then go to the GUI it resets the settings or something, and you can't resume the game because it resets.

**Comment by blinkydoos** [comment]
Another thing that i've been trying to report but Github stopped working ! When selecting, I think it's working fine now when selecting with the mouse but when using the keyboard/joystick it doesn't.

**Comment by midwan** [comment]
@blinkydoos I don't see the problem you mention with Quickstart, using the keyboard it does change the settings correctly here.
What did you check and didn't get updated? 
The only scenario I found was that the ROM would not be updated for A1200, if there wasn't one for that model in the list (I had a kick3.1 for A2000). After placing a proper ROM in there, and Rescanning, it worked.

**Comment by blinkydoos** [comment]
I'll have to get back to you tomorrow about this because I'm out at the moment. The problem I noticed was when loading the Retropie configs with the joystick. For instance, I pressed fire on the rp-a500 config then pressed fire on the Load button. If I then selected a different config and pressed Load the Processor and Chipset etc were still set at the previous config. It worked fine when selecting with a mouse.

Did you catch the problem with it resetting the game when going to the GUI for the first time ? I booted straight into a game using a UAE config (bypassing the GUI) but then when entering the GUI it reset the settings so the game couldn't be resumed.

**Comment by midwan** [comment]
@blinkydoos Yes, the bug with applying the Quickstart settings every time you opened the GUI is now fixed :)

In the tests I made I can't recreate the issue you mentioned above, so please let me know if you still have it when you test it again with the latest updates?

**Comment by blinkydoos** [comment]
I built the latest, the problem still occurred after messing with some options but I can't reproduce it ! Let's forget about this one as it's giving me a headache :)

Regarding the new 'Set Configuration' button, when selecting a quickstart from the list it still changes to the settings. I thought the settings would only change when you pressed the 'Set Configuration' button ?

**Comment by midwan** [comment]
@blinkydoos 
The Set Configuration re-applies the selected config, but the dropdown will also apply what you selected (same as WinUAE does in this respect). This is by-design. :)

**Comment by blinkydoos** [comment]
But the version of WinUAE that I have (v3.6.0 beta) it doesn't apply the chosen quickstart until you press the 'Set Configuration' button. There doesn't seem to be any point for the 'Set Configuration' button if it applies the settings anyway (probably WinUAE 3.5.0 and below).
