### ISSUE TITLE
[Latest SDL1 Dev] Changing Quickstart model also changes some Misc options

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#197]
When selecting a different Quickstart model it also changes some of the Misc options, It turns off the Status line etc. WinUAE doesn't change these options when changing Quickstart model.

**Comment by midwan** [comment]
Note: when a Quickstart option is changed, the emulator loads the built-in default prefs and then the target default prefs. That's the same as WinUAE.
We had been changing the leds_on_screen incorrectly though, so I excluded that.

**Comment by blinkydoos** [comment]
Could you also prevent it from affecting the 'Hide idle led' option as well please as it's part of the status line ?
