### ISSUE TITLE
Quickstart and Immediate blitter

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#204]
Currently all Quickstart configs have Immediate Blitter turned on but in WinUAE it's only turned on with faster CPU's 68020 and above.

**Comment by midwan** [comment]
Actually, that's not correct... 
All Quickstart options have "Wait for blitter" enabled by default, not Immediate.

**Comment by midwan** [comment]
Also, in WinUAE all Quickstart options above A1200 have "Wait for Blitter" enabled by default.
The A500/A600 configuration does not, if you have set it to "Best compatibility" (Cycle-exact). We don't have that mode, so it goes to "Wait for Blitter" as well (same as WinUAE does if you set it to Best Performance).

**Comment by blinkydoos** [comment]
Sorry, I got Immediate & Wait mixed up. Thanks for the explanation.
