### ISSUE TITLE
SDL2 | Keyboard Mapping

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#21]
Sorry, more controls stuff. Unfortunately in it's current state, i find it difficult to use uae4arm because of these issues!!

This time  it's the "other way around" ... It is not there in the GUI, but maybe it already existing in .uae file config settings ?

The joystick/joypad controller for my PiGrrl machine 'fakes' keyboard presses, by using the GPIO , so not a conventional 'controller' input. 

This is pretty easy to do in winuae/fs-uae etc, but i would like to simple add something like keyboard_key_a = joy1_fire_button   etc    

in the days of E-UAE, i could do something like this:  
input.1.keyboard.0.button.17=JOY1_UP
input.1.keyboard.0.button.11=JOY1_DOWN
input.1.keyboard.0.button.3=JOY1_LEFT
input.1.keyboard.0.button.4=JOY1_RIGHT

If this can already be done via the config file, please let me know, otherwise this goes down as a another new request!

thanks

**Comment by midwan** [comment]
@osvaldolove is working on this and had some good ideas.
Note: we should implement this in a libretro-friendly way, if possible.

**Comment by midwan** [comment]
@HoraceAndTheSpider 
I've added some code in the recent updates that allows custom mapping of any key to any function.
The plan is to use that to allow mapping for any control in the emulator to any key (and eventually controller button, but that's not fully done yet).

It's already active in the Misc menu, to map the functions "Quit" and "Enter GUI" to any key you want. It seems to work well and saves to the config file properly.

Once this is tested a bit more and the controller buttons work also, I'll add it in the Custom Controls section also, replacing the hardcoded dropdown lists.
