### ISSUE TITLE
[SDL2] Building fails on Orange Pi PC (Allwinner H3 CPU / Mali400 GPU)

### ISSUE THREAD

**Issue by alerinoreis** [midwan/amiberry#210]
Hello midwan,
apologies if i'm posting in the wrong place, i couldnt find a forum where i could discuss this before stating it's an issue, because maybe it's not supported at all. Trying to compile the SDL2 flavor in an Orange Pi PC (CPU Allwinner H3/ GPU Mali400), it seems to build OK until the end, when i get this: https://pastebin.com/raw/ucTPEVgp . I used the rpi2 target, which is very similar to H3/Mali, default cflags: -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard 
I'm a beginner at compiling so if there is any other info i can provide, let me know. Thanks!

**Comment by midwan** [comment]
@alerinoreis 
Hello, and thanks for the feedback!
The errors seem to indicate problems while compiling the processor-related parts (JIT).
Did you pick the right branch? From the log it would seem you're trying to build the version from the "sdl2" branch, which is quite old and deprecated now. If so, please try the "dev" branch instead.

The old branches are kept for a bit more, just in case we need anything from them. They will be removed eventually to clear things up and avoid such confusion (sorry about that!).

**Comment by midwan** [comment]
@alerinoreis That being said, I don't have an OrangePi here to test with... but let's see how it goes

**Comment by alerinoreis** [comment]
thanks for the quick response! I'll let you know soon.

**Comment by alerinoreis** [comment]
Good progress! Thanks for the heads up!
Now it builds fine:
pi@RetrOrangePi:~/amiberry-dev$ make all PLATFORM=rpi2-sdl2
make -C src/guisan
make[1]: Entering directory '/home/pi/amiberry-dev/src/guisan'
make[1]: 'lib/libguisan.a' is up to date.
make[1]: Leaving directory '/home/pi/amiberry-dev/src/guisan'

 but then, running the binary from the source folder... 

pi@RetrOrangePi:~/amiberry-dev$ ./amiberry-rpi2-sdl2-dev
Could not create color cursor: Cursors are not currently supported
Unable to load image file: data/controller.png

Forcing framebuffer-only SDL2 makes no difference:

pi@RetrOrangePi:~/amiberry-dev$ LD_LIBRARY_PATH=/usr/local/lib ./amiberry-rpi2-sdl2-dev
Could not create color cursor: Cursors are not currently supported
Unable to load image file: data/controller.png

Anyway, i'm very glad that it even built, i thought i would have RPI dependencies in the way...

**Comment by Voljega** [comment]
do you have the controller.png file ? and the data directory under the exec file ?

**Comment by midwan** [comment]
@alerinoreis 
The custom cursor thing is easily fixed, we had the same issue on the XU4 so I'll work on a solution that makes things work regardless of you have support for that or not.

Regarding the missing png file, that is included in the repo under the "dev" branch, so please make sure you got all the files from there?

**Comment by alerinoreis** [comment]
A bit of info: i'm running this on a RetroPie fork for Allwinner H3 devices, so i had to make some minor tweaks to the install script (enable mali, change branch to dev, change require name to amiberry-rpi2-sdl2-dev instead of amiberry) and it built just fine. 

Running the result binary from retropie installation returned the same error, but the good news now is that running the retropie script (amiberry.sh) + auto + %ROM% actually works  :) 

Here is the log (all files from data folder were in the right place btw) 
i did this: https://pastebin.com/7jrcDumB
and got this, despite the "Unsupported archive", it works:
http://www.retrorangepi.org/amiberry.png

not so good news, it seems a little slower than SDL1 with libglshim, but i think it's tweakable since it was a straight RPI2 compile with no changes (maybe deactivating NEON it would improve)

**Comment by midwan** [comment]
@alerinoreis 
Thanks for the update!
The cursor problem will only show in the GUI, because it's only used there. If you skip the GUI and load some config directly, it will launch without it.

The current implementation of SDL2 can be further optimized also, it's slower on the Pi as well compared to the SDL2/DispmanX approach (that's why we still have Dispmanx targets, for both SDL1 and SDL2). If we manage to make it faster, it will be so for all targets SDL2 supports, which would be great news!

Did you enable Mali on the system, SDL2 itself, or did you have to do something with the Makefile also?

**Comment by alerinoreis** [comment]
In fact i still cannot open the GUI. Running amiberry.sh without parameters results in the same error as before. Ingame, pressing F12 quits to EmulationStation. 

The distribution (RetrOrangePi) has Mali r4p0 enabled for the framebuffer and the X11 as well. The SDL2 is the RetroPie version compiled with enable-video-mali and disable-video-x11. 

In the first build attempt i added  '-L/usr/include/SDL2' to the Makefile because it wasnt finding some SDL headers (OK, the system is kinda crazy, includes in /usr/include, fbdev SDL2 libs in /usr/local etc). Second attempt, no changes to Make file, i added the full path to the .cpp files directly, no big deal. 


I'm away from home now, with limited access (only SSH).

**Comment by midwan** [comment]
@alerinoreis I made some changes regarding the custom cursor handling in the GUI, perhaps this fixes the problem you're facing also. Could you please give it another try (remember to fetch the latest!).

**Comment by alerinoreis** [comment]
Running the binary directly with no parameters or omitting -G from binary/amiberry.sh leads to the same error described in the previous posts:
INFO: Could not create color cursor: Cursors are not currently supported                                     
Unable to load image file: data/controller.png
                                                      
with -G , success :) 
http://www.retrorangepi.org/amiberry.png (actual 720p screenshot)

**Comment by HoraceAndTheSpider** [comment]
Controller.png and now also the logo files possibly?

**Comment by alerinoreis** [comment]
all files seem to be there :/ 
pi@RetrOrangePi:/opt/retropie/emulators/amiberry$ ls -l data/                                                
total 296                                                                                                    
-rwxr-xr-x 1 root root   1406 Jan 19 20:06 35floppy.ico
-rw-r--r-- 1 root root 143648 Jan 19 20:06 amiberry-logo.png
-rw-r--r-- 1 root root   1406 Jan 19 20:06 amigainfo.ico                                                     
-rw-r--r-- 1 root root  31724 Jan 19 20:06 AmigaTopaz.ttf                                                    
-rwxr-xr-x 1 root root    318 Jan 19 20:06 chip.ico
-rw-r--r-- 1 root root    665 Jan 19 20:06 controller.png
-rwxr-xr-x 1 root root    318 Jan 19 20:06 cpu.ico
-rw-r--r-- 1 root root   2006 Jan 19 20:06 cursor.bmp
-rw-r--r-- 1 root root   7882 Jan 19 20:06 cursor-x2.bmp
-rw-r--r-- 1 root root    597 Jan 19 20:06 delete.png
-rwxr-xr-x 1 root root   1406 Jan 19 20:06 drive.ico
-rwxr-xr-x 1 root root   1406 Jan 19 20:06 expansion.ico
-rwxr-xr-x 1 root root    318 Jan 19 20:06 file.ico
-rw-r--r-- 1 root root   1406 Jan 19 20:06 joystick.ico                                                      
-rw-r--r-- 1 root root   1406 Jan 19 20:06 misc.ico                                                          
-rwxr-xr-x 1 root root    318 Jan 19 20:06 paths.ico
-rw-r--r-- 1 root root   1406 Jan 19 20:06 quickstart.ico                                                    
-rw-r--r-- 1 root root    528 Jan 19 20:06 savestate.png
-rwxr-xr-x 1 root root   1406 Jan 19 20:06 screen.ico
-rwxr-xr-x 1 root root   1406 Jan 19 20:06 sound.ico
-rw-r--r-- 1 root root  42264 Jan 19 20:06 Topaznew.ttf                                                      
pi@RetrOrangePi:/opt/retropie/emulators/amiberry$

**Comment by midwan** [comment]
@alerinoreis 
Where did you start the emulator from? How did you start it (using a script, or directly calling the binary?)
It's going to expect a data/ folder right where it's started from, perhaps it doesn't find it?

**Comment by alerinoreis** [comment]
Always running from /opt/retropie/emulators/amiberry where binary is and data/controller.png exists. Would file/folder ownership affect this?

**Comment by midwan** [comment]
@alerinoreis 
It should be readable, and I see above that it is.
Strange, I don't see the same error in Retropie if I launch the emulator manually from there...
Let's fix the cursor issue and we'll see about this one after then.

**Comment by midwan** [comment]
Could you please post "amiberry.sh" here, so I can take a look?

The INFO message about the cursor is not blocking or crashing the emulator, it's only FYI because the cursor could not be created in your system. The failure to load data/controller.png however, is fatal and will exit out. I'd like to find out why it happened there...

**Comment by alerinoreis** [comment]
the amiberry.sh is the same used in standard retropie, there is only an additional line to run qjoypad in X11 so its possible to map keyboard/mouse to gamepad buttons
https://github.com/retr0rangepi/RetroPie-Setup/blob/master/scriptmodules/emulators/uae4arm/uae4arm.sh

running the binary directly has the same effect

**Comment by HoraceAndTheSpider** [comment]
how were the extra files copied on? Could there be a problem with the user permissions on the image files?

All those listed seem to say 'root' but you are possibly rnning as user 'pi' ?

**Comment by alerinoreis** [comment]
chowning the folder amiberry to user pi did not change

**Comment by HoraceAndTheSpider** [comment]
I assume that was `sudo chown -hR pi:pi amiberry/ ` to include recursive scanning?  Shame :/

**Comment by alerinoreis** [comment]
yes yes, exactly. I'm still confident we'll find a solution :) thanks guys for all the help.

**Comment by midwan** [comment]
@alerinoreis 
There's a chance that your SDL2 framework is not built with PNG image support, and that's why it fails to load the file.
To test this theory out, I've made a small modification to the `main_window.cpp` file (replaced the controller.png with joystick.ico), which I'm attaching below. Please put this one in place, replacing the original, and recompile.

However, I've left the "savestate.png" in place as the Savestates icon as well. ;-)

If you now get an error that it can't open image: "savestate.png", we'll know the problem is related to PNG images in general in your system.

[main_window.zip](https://github.com/midwan/amiberry/files/1659103/main_window.zip)

**Comment by retr0rangepi** [comment]
I reached this conclusion a couple of days ago, when i edited the code (commented one of the .png lines), and boom, the error skipped to the next png. 

My guess, however, is not SDL2, maybe it's the PNG framework itself. A package in my system, which i dont recall now, requires libpng 1.7, because of that, had to keep both versions in the OS (maybe not a wise decision :/ ). Default debian libpng12 in /usr/lib/arm-linux-gnueabihf, includes in /usr/include/libpng12 AND libpng17 in /usr/local/lib, includes in /usr/local/include/libpng17. I tried to add some flags, change -lpng to -L/usr/local/lib -lpng17 to the MAKEFILE but didnt change the result. Besides, to add more ingredients to the mess, both Mali and SDL have two versions, the framebuffer and the x11 flavors. 

I also get compiling errors not finding SDL_ttf.h, manual editing is sometimes necessary (adding SDL2 include folder to the makefile helps), but i think this confuses the compiler even more, as there are portions of the code pointing to the SDL1 version of TTF <SDL/SDL_ttf.h>. 

I'll try to start from scratch, with a clean Armbian image, which is the RetrOrangePi base OS. If you have any other suggestion, let me know. 

Thanks so much for your patience.

**Comment by retr0rangepi** [comment]
this is our official github account :)

**Comment by midwan** [comment]
@retr0rangepi 
Thanks for the info! At least we know where the problem comes from now.
All instances of `<SDL/SDL_ttf.h>` in the code are behind an `#ifdef USE_SDL1` so it shouldn't be a problem. Did you find something that wasn't or did you not include `-DUSE_SDL2` in your target?

**Comment by retr0rangepi** [comment]
i'm running 'make PLATFORM=rpi2-sdl2' so i assume everything is fine, as -DUSE_SDL2 is used and i get a working binary at the end. Only problem is the GUI not being correctly built. I will report back as soon as i try it in latest Armbian.

**Comment by retr0rangepi** [comment]
So , had some spare time to test it and... success! 

What i did:

1. tried a previous version of RetrOrangePi, but i think it will work just fine on the latest one as well.
2. compiled SDL2 v2.0.7 with Mali backend (from retropie)
3. compiled both SDL2 ttf and image from sources to the same prefix
4. added the cppflag "-I/usr/local/include/SDL2" to the Makefile
5. small tweaks to amiberry scriptmodule on retropie-setup and... 
6. running from command line... voilá! Now i have the menu => http://www.retrorangepi.org/amiberry_menu.png

bugs found:
1. i know mouse works, but cursor is still absent
"INFO: Could not create color cursor: Cursors are not currently supported" error
2. cannot go back to menu, F12 crashes the framebuffer:
*** Error in `./amiberry-rpi2-sdl2-dev': double free or corruption (!prev): 0x02324768 ***

Performance wise, it seems to be very good, better than the other day i tried. Also tested WHDLoad, worked fine! Added Amiberry to our boot menu :D => https://www.youtube.com/watch?v=u-wo_YL0iDQ

Let me know if i can test anything else. Thanks for hanging in there...

**Comment by midwan** [comment]
@retr0rangepi 
That's great news!
Regarding the cursor, I just pushed a workaround for Mali GPUs - you'll need to define "MALI_GPU" for your target in the Makefile, but hopefully it will work for you.
While you're at it, try defining USE_RENDER_THREAD and see if it works for you. It works on the Tinker board (Mali GPU as well) but not on the Pi, unless it's running under x11. You'll see a nice performance boost if it does... ;-)

Strange about the F12 crash? I haven't heard about such an issue from anyone else so far...

**Comment by midwan** [comment]
@retr0rangepi 
Sorry to dig this old issue up, but I just got an OrangePi PC here and I can finally test the emulator in it.
I've downloaded the RetrOrangePi distro (v4.2) and I'll be testing it over the next few days.

If there are any known issues still, could you please report them as well so we can handle them?

**Comment by midwan** [comment]
@retr0rangepi 
How did you compile SDL2 with the Mali backend from RetroPie, exactly?
It looks like the current installation comes with SDL2, but no video device was found when trying to launch it from the console (perhaps it only works under X11).

**Comment by retr0rangepi** [comment]
Great news. Tweaked the Tinker target (includes/libs poiting to usr/local) and got it to compile fine. Menu works fine as well, i'll keep you posted

**Comment by midwan** [comment]
@retr0rangepi 
I've added a dedicated target for OrangePi-PC, so you don't have to tweak the Tinker Board one ;)
Just get the latest from source to see it in the Makefile.
