### ISSUE TITLE
Switching to A1200 emulation freezes on Arch

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#213]
### Expected behavior
Be able to start a A500, go back to the config panel GUI and switch to A1200, and start that.
### Actual behavior
Black screen, not able to go back to the config panel.

### Steps to reproduce the behavior
On Arch Linux (does not seem to happen on Raspbian)
Start amiberry, without any config at all, but with kickstart roms in kickstarts/ (sdl1 or sdl2, does not matter) start A500 from the quickstart - to back to gui, switch to A1200, start emulation.

**Comment by midwan** [comment]
Note to self: check if uae_restart can be avoided in this scenario

**Comment by solskogen** [comment]
Yes, that fixed it!
