### ISSUE TITLE
Question about jstest

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#215]
Hello I just wanted to know if the new controller mapping uses `jstest` behind the scene as the wiki seems to suggest it ?

(reason why I ask is this may lead to some trouble for me/us on Recalbox)

**Comment by HoraceAndTheSpider** [comment]
No, Amiberry doesn’t use it directly, but you can use it for verification as to what is available on the system!

Maybe I need to re-word it slightly then... what do you use to check input devices on recallbox?

**Comment by Voljega** [comment]
I'm not sure exactly bu I do know we used to use `jstest` and that know we use `sld2-jstest` because 'it is more close to what Emulation Station is detecting' so this seems to mean that those two commands don't exactly output the same results...

One thing I know for sure for instance is that the controller string ouput by the Emulation Station of Recalbox (which isn't the same as Retroprie and is heavily modified too) is `-p1index 0 -p1guid 060000004c0500006802000000010000 -p1name PLAYSTATION(R)3 Controller -p1devicepath /dev/input/event0` whereas the amiberry wiki seems to detect a SONY PS3 controller as `PLAYSTATION(R)3 Controller` so that's already one point that may lead to trouble.

Actually this is the point that worries me, the naming of the controller and the related naming of the retroarch file sed by Amiberry

**Comment by HoraceAndTheSpider** [comment]
There is no need to worry :)

The file name simply has to match what is stated in Amiberry’s drop down, which you has already mentioned how to find after -p1name , so I can clarify that.

**Comment by Voljega** [comment]
Ah ok good to know ! Thank you :)

**Comment by HoraceAndTheSpider** [comment]
Some controller's (even Sony PS3 pads) do differ slightly depending on the model, and the ones in the Wiki are only as an example. :)

I have added clarification, so please let me know if it makes more sense now.
