### ISSUE TITLE
WHDload Batman the movie - file not being identified

### ISSUE THREAD

**Issue by JaseDaMase** [midwan/amiberry#216]
### Expected behavior
Game to boot
### Actual behavior
WHDload files not being identified for this game
### Steps to reproduce the behavior
Renamed the uae file to match the name of the whdload folder and slave/info file but still doesn't recognise it

**Comment by HoraceAndTheSpider** [comment]
Please post a copy of your .uae Config file, and the folder structure where you have the game stored. 

Thanks

**Comment by midwan** [comment]
@JaseDaMase 
Could you please post the requested information also, so we can look into this further?

**Comment by ransom1122** [comment]
There is a recent new slave for Batman the Movie. Are you using the latest version?

**Comment by midwan** [comment]
Closing this until we receive more details...
