### ISSUE TITLE
Find out why we need the fix from #142

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#219]
### Expected behavior
The fix that was proposed (and commited) in #142 is really a workaround.
Find out the real fix.

### Actual behavior
Crash, if not the workaround exists. But's the workaround is a bit dirty.

### Steps to reproduce the behavior
Remove the workaround, and amiberry will either crash or produce a black screen (saving config will also crash amiberry)

**Comment by midwan** [comment]
This has now been reported upstream to Toni:
https://github.com/tonioni/WinUAE/issues/138

**Comment by midwan** [comment]
This has now been fixed upstream, closing the issue...
