### ISSUE TITLE
Full screen output (no borders)

### ISSUE THREAD

**Issue by vretro** [midwan/amiberry#221]
Will it be possible in Amiberry in future to adjust the screen output to remove the black borders for a full height 4:3 display, or a full width 16:9 image, as seen in this handy WinUAE tutorial video by Lemon Amiga?:
https://m.youtube.com/watch?v=IiOzfYHvkWY

Thank you for the fantastic work on this project

**Comment by midwan** [comment]
@vretro 
We already have full screen mode, if you don't care about aspect ratio (i.e. it will be stretched). Otherwise the screen is resized to fill your entire resolution, but keeping the correct aspect ratio.
This is controller by an option in the GUI (Correct Aspect Ratio).

This feature is only available in "dev" currently, but this branch is expected to be merged back into master soon...

**Comment by midwan** [comment]
@vretro 
What we don't have currently is support for filters though, if you mean that.
The custom zoom to fill the screen can be achieved with the latest versions of SDL2 that are still in development, but we haven't tested that yet.

**Comment by vretro** [comment]
@midwan appreciate the responses, thank you. From the YouTube video yes, it’s specifically the filter: ‘Automatic scaling’ in conjunction with ‘Point/Bilinear = 1’ that i’d request, so that the output image is automatically filling the viewport. Attempting to adjust the output manually takes lots of tweaking with the multitude of resolutions that different games/programs output. Sounds like the SDL2 version is similar to the YouTube video in some ways and more in line with what’s possible.  Congratulations on the big release.

**Comment by midwan** [comment]
@vretro 
The latest version from `master` includes this now, and the SDL2 versions can use the Scaling options available also. Additionally, if you run Amiberry under X11, you have the option to keep it Windowed or Full screen (options in the Display panel). The options are all saved in the config files normally.
