### ISSUE TITLE
DietPi v6.0 + AmiBerry image update

### ISSUE THREAD

**Issue by Fourdee** [midwan/amiberry#222]
@midwan 

As mentioned earlier: https://github.com/Fourdee/DietPi/issues/1410#issuecomment-360883774

We've updated the AmiBerry existing image to DietPi v6.0. Please update https://blitterstudio.com/amiberry/ with the following changes (items changed highlighted in **bold**)

1. Download the image: **http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Jessie_AmiBerry.7z**
3. Plug in the Ethernet cable OR optionally set the Wifi connection details in the /boot/dietpi.txt file on the sdcard:
- Set **AUTO_SETUP_NET_WIFI_ENABLED**=1
- Set **AUTO_SETUP_NET_WIFI_SSID**=MyWirelessSSID
- Set **AUTO_SETUP_NET_WIFI_KEY**=MyAccessKey
- Set **CONFIG_WIFI_COUNTRY_CODE**= This will enable channels and higher power ratings allowed for your country. Example country codes are: GB US DE JP. Full list: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
Save changes

4. Optionally, to enable OpenSSH, so you can connect and transfer files using that:
edit the file /boot/dietpi.txt and locate the following line:
- **AUTO_SETUP_SSH_SERVER_INDEX**
and change it to: **AUTO_SETUP_SSH_SERVER_INDEX**=-2

**Comment by midwan** [comment]
Thanks for the update!
Links and instructions are now updated!
