### ISSUE TITLE
Updating Amiberry on Rpi3

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#225]
Hi midwan.

Congratulations on the release of Amiberry v2 for the pi3.

When updating an existing image with Amiberry.. do i simply delete the adfdir.conf file then update via emulation station?

Is this the method for updating safely?

Kind Regards
ransom

**Comment by ransom1122** [comment]
Also do you have changelog for v2?

**Comment by midwan** [comment]
@ransom1122 
For RetroPie, the distro will provide an upgrade path itself soon.
You can do it manually if you want also, by:
- Placing the new binary in the same location (rename it accordingly): /opt/retropie/emulators/amiberry/
- Placing the contents of the data/ folder in the same location as the old
- Deleting the adfdir.conf file and allow it to be recreated (by clicking on Rescan Paths for example).

Regarding the version history, check https://github.com/midwan/amiberry/wiki/Version-history

**Comment by ransom1122** [comment]
When you mean Rescan Paths for example). You mean inside of amiverry gui yeah?

**Comment by midwan** [comment]
@ransom1122 
Yes, inside the GUI, in the Paths Panel. That button will trigger a scan for ROMs etc. which will in turn (re)generate the adfdir.conf file, to contain a cached version of what it found. ;-)

**Comment by ransom1122** [comment]
I am getting a write permission error when tensferring files the old data folder.
How do i enable writing persmissions. Sorry for the questions but I am not knowledgeable with linux/commands etc.

**Comment by midwan** [comment]
Try `sudo <whatever command you tried>` and that should give you access ;-)

**Comment by ransom1122** [comment]
I did not try any commands. Nor do i know what the command is? I got the write permission error when transferring files from Amiberry2.zip into the old data folder of my pi3 using a ftp client.

**Comment by midwan** [comment]
OK, you probably can't do a `sudo` over an FTP client... 

The best would be to copy them to a place you have access first (like /home/pi), then use an SSH session and from within that do something like:

`cd ~` (that will get you to /home/pi/)
`sudo cp data/* /opt/retropie/emulators/amiberry/data/` (to copy all files under data/ to the destination directory mentioned)

That is assuming that the `data/` folder was extracted inside `/home/pi/` of course. If it's in another directory, just adjust that accordingly or `cd` there first.

**Comment by ransom1122** [comment]
OK I got it updated thanks for your helpfull guide im sure it will help a lot of people down the track.

Where do we submit bugs etc for Amiberry2 Do you have a spot for bugs/issues.

I tried to play T-Zer0 which mounts HDF as primary and cd image as secondary and it is not picking up the cd image cue file. Did this issue get fixed in Amiberry 2?

**Comment by midwan** [comment]
The Issues page is the usual spot for reporting any problems ;-)
