### ISSUE TITLE
Amiverry v2 custom controls explained

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#228]
Hi.

After updating to amiberry v2 it seems the fire buttons are not working like they did in v1 input PLAYSTATION(R) 3 Controller?

Can you please explain custom controls

1. What is North/South/East/West What should they assign to?
2. Why is Select/L&R Shoulder unselectable?
3. Which configuration do I ammend for primary joystick fire button?

**Comment by ransom1122** [comment]
Can you please provide a default working config all Amiga models.. it seems all my configs are messed up. Fire button is SELECT on the ps3 pad. And i cant reconfigure buttons.

CD32 Controls I cant get working at all.

I think with a working uae config for each model ie 500 1200 cd32 i should be abke to adjust all my 2000 game configs to be compatible with amiberry v2

**Comment by HoraceAndTheSpider** [comment]
To confirm : “select as fire” is expected behaviour for a PS3 pad which has not had a controller map set up, since “select” is button 0.

You would need to create a controller map for this , or set the controller path to that of an existing file (produced by RetroPie / RetroArch)


Details on the wiki page:

https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers


These even includes a diagram explaining the n/s/e/w designation, as used in other emulators (such as fs-uae)

**Comment by ransom1122** [comment]
Understood... to make it clear.. *all* configs will work on one custom controller mapping?

Do you need a 2nd for player 2?

**Comment by HoraceAndTheSpider** [comment]
No, Custom mapping is saved on a game-by game basis.

The general controller mapping (which re uses the retroarch map) is universal. So once you have your PS3 pad mapped, Cd32 controls (for example) will work the same on every game. 


Regarding other players, you effectively do custom mapping on any of the 4 input ports. 

This means you can use port  3 (which by default is the parallel port) to be remapped to say Cursor Keys. 

This allows games like Indy Heat or Super Off Road to be played with 3 pads.

Hope that helps

**Comment by ransom1122** [comment]
Understood. I will give it a go later today.

**Comment by ransom1122** [comment]
Thought came to mind. It appears wether a PS3 Controller is connected via bluetooth or wired the connection name is different although its the same controller.

Does this mean you need 2 configs for both wired and wireless for it to always work on both wired and bluetooth wireless play?

**Comment by ransom1122** [comment]
I test custom mapping and it seems to work. Thank you

**Comment by ransom1122** [comment]
When I try and save a config after adjusting all the cd32 controls in custom controls gui.
I click configuration tab.
Type a name of a new config.
Click save.
And it quits back to emulation station.

Amiberry v2 is not allowing me to save any new configs? Why?

**Comment by HoraceAndTheSpider** [comment]
Two Separate issues here I think.... firstly, need to check - why are are setting cd32 controls in the custom panel?

There is a drop down in the input panel for standard mouse/joystick/cd32 modes. This should make it much easier for you!



Regarding the crash - do you have rights permissions to save to the selected Configurations path? 
I.e can you save to that location (or create a blank text file) from command line without using “sudo”? 


In answer to previous question, if wired and wireless are different names in the system? then yes they need separated config files.

**Comment by ransom1122** [comment]
I tried copying a file via ftp to /home/pi/RetroPie/roms/amiga and it does work. So I am guessing I have permission. This folder path was used in my previous amiberry v1 image before I updated.

In regards to saving a config i just used that as an example.

Input port 1 PLAYSTATION (R) Controller CD32 is selected.

I cant start a cd32 game
 It seems the path to my bios is correct. But it defaults to full file name to cd32 & extended cd32 bios.

When i manually change cd32 bios to cd32kick31.rom it applies the change.

But when i change extended rom file manually to cd32ext.rom it does not apply it still shows the default rom as CD32 extended ROM rev 40.60 (512k)

Do i have to rename my kicks to the full kickstart filename? Maybe this is why cd32 is not starting?

**Comment by ransom1122** [comment]
Could you please attach a standard quickstart cd32 uae config? 

I want to see if I can launch from one thats come from you.. as i cannot save a new cd32 quickstart config in my image

**Comment by midwan** [comment]
@ransom1122 
Did you try deleting the `adfdir.conf` file?
What path settings do you have in the Paths Panel?

Also, the new version is not "v2" exactly, it's v2.12. The older one was v2.1, so it's been in v2.x for quite a while already.

**Comment by ransom1122** [comment]
Yes I did and when I rescanned paths it created another adfdir.conf file
[Img]https://i.imgur.com/nTZMPwW.jpg[/img]

Some seems weird. I can never match the cd image after enabling quickstart cd32?

In the quickstart tab section cd drive. I click select image. (Choose a cd32 game cue file)

Then in harddrive/cd tab. I cannot select the same cue as above. It always remembers the previous used cue file.

**Comment by midwan** [comment]
@ransom1122 
The path to your Config files is set to "/", and that's probably why it can't save them.

That's the root folder in your disk, only "root" has access there.

**Comment by ransom1122** [comment]
Changed it to the roms/amiga folder. Now I can save but it takes about 7 seconds everytime you press F12 because I have 7,800 UAE configs there. It never used to do this in Amiberry 1. Yes I am on Amiberry v2.12

**Comment by midwan** [comment]
@ransom1122 
This is a separate problem then, I think.
Let's move it to another issue to avoid losing track of it, this issue is marked as resolved. ;-)

Also, there wasn't an "Amiberry 1", the previous version was Amiberry v2.1. It might be confusing for people visiting, so let's try to keep it accurate please? :) Thanks!
