### ISSUE TITLE
Amiberry SDL-2 libpng16.so.16

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#230]
Hi. 

When want to execute Amiberry SDL-2 I still have error: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory. How to resolve it ? thanks

**Comment by midwan** [comment]
`libpng16` is included with Stretch, but Jessie has an older version - `libpng12` which is not supported by SDL2.

You'll need to use Stretch (or newer) for this to work.
