### ISSUE TITLE
Request: Warp mode

### ISSUE THREAD

**Issue by ZappaUtopia** [midwan/amiberry#231]
Now this emulator is progressing, my most wanted feature apart from IPF support is 'Warp mode'. I'm not a big fan of WHDLoad and prefer to use the original and best disk method (not to mention most compatible). Some games can take a while to load or if you just want to hurry through an unskippable intro, warp mode is extremely useful (a single configurable button). You can then also leave the floppy load speed at 100% compatible. I wouldn't think this would be too taxing for you to add @midwan , someone of your skill. :+1:

**Comment by midwan** [comment]
IPF support is coming, and probably very soon also.. (see relevant issue #130).

Warp mode will be added in the list of Todo, but we'll have to see how feasible it is for our target platforms.
I would consider it low priority for now however...

**Comment by ZappaUtopia** [comment]
Nice one. I think it will be a great addition for all types of users. Would it even speed up rendering ? I saw your FPU tests on your Facebook page :)

**Comment by ZappaUtopia** [comment]
Hi, i've yet to try the new version as my Pi is in storage. I've seen screenshots of a Turbo mode option, does this work like the Warp mode I requested and if so could it be mapped to a button ?

**Comment by midwan** [comment]
@ZappaUtopia 
The CPU Turbo mode changes the time we devote to CPU vs Chipset during emulation, giving the maximum time to CPU and minimizing the Chipset timing. It's good for certain kinds of usages (e.g. desktop stuff that depend on the CPU mostly, like Lightwave rendering), but not good for games/demos etc.

**Comment by ZappaUtopia** [comment]
Oh, not what I was thinking then ! I never noticed this option in WinUAE. Wouldn't Warp mode do the same thing and be more beneficial ?

**Comment by midwan** [comment]
@ZappaUtopia 
This doesn't exist in WinUAE, it's a unique feature we added. ;)

**Comment by solskogen** [comment]
I do not agree. Warp-mode is for speeding things up temporary, it's not for having a "fast" amiga. (warp-mode on winuae also means frame skip)

**Comment by midwan** [comment]
@solskogen 
OK, but then isn't it just enabling all those things anyway (Fastest/Turbo, JIT, Frameskip)?
Or am I missing something?

**Comment by solskogen** [comment]
Yes-ish, it's a lot easier if can be switched on-off with a keyboard shortcut (WinUAE does this with altgr+pause IIRC)

**Comment by CypherXG** [comment]
Oh you mean this....
Its not really a warp mode...
Only the CPU tickrate was changed. You see it as warp mode. It hast nothing to do with Chipset Timing or emulations speed. The CIA/Chipset Timing is wrong etc. 
Yes its possible to do this i Amiberry. I tried it months ago but it makes no sense...
Why do you want it...Skip an Intro....run the emulator uncontrolled faster?

**Comment by CypherXG** [comment]
You must know....is it really good if timings are not correct to write Data on a hdf or in a directory...
It is a high risk to get CRC errors or crash the hdf file....
