### ISSUE TITLE
Found some Bugs and needed enhancements

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#234]
Version: 2.12
Compiled for RPi3 SDL1

**BUG**: When u start in Picasso Mode the Screen Hz are 60 Hz. This is correct. When you enter the GUI and you go back to the Emulation the Hz switches to 50. Than the Audio is lagging again. Thats again a poblem like [Issue #190 ](https://github.com/midwan/amiberry/issues/190)

**Bug**: When u activate the CPU Turbo option the Hz. are in NTSC 59Hz and in Pal 49Hz. Then u have sync problems in Demos, Games, Module Tracker etc. 

**Bug**: When u activate JIT FPU u will get many GFX Errors in Demos, Games. Test it with TBL Starstruck Demo. This Demo use the FPU if present.

**Bug**: Sometimes, when i use the Workbench i taken an icon with holding the left mouse button. from time to time the left mouse button just lets go while I move an icon. My mouse is ok.

**suggestion**: Can you bring back the "FullscreenRatio"? This is very useful when u use the composide output. It is better to ajust the screen if the TV is smaller like an FULLHD LCD. It was a wonderful feature before it was removed.

**suggestion**: Is it possible to add an horizontal offset menu like the vertikal one in the display options?

**Comment by midwan** [comment]
@CypherXG 
OK, it's better we split these in separate issues so we can handle them properly.

The JIT FPU bug(s) is known, and will be fixed in upcoming versions.

**Comment by CypherXG** [comment]
:-)

**Comment by midwan** [comment]
@CypherXG 
Regarding the things you mentioned above:

1) I haven't seen this problem yet, I'll try to recreate it some more just in case. Any special details that I should be aware of? What resolution / Hz are you running your monitor in? What configuration do you use in Amiberry?

2) The Turbo mode setting is not meant for games/demos, but for desktop usage where you might need the maximum amount of CPU power VS chipset (e.g. if you're rendering in 3D software, compiling, etc). To hit that kind of performance, the time given to the custom chipset is minimized. That being said, it does stick to 50/60 Hz in my tests on an RPI3.

3) The JIT FPU bugs have now been fixed.

4) I haven't managed to recreate the mouse button issue you mention above, not sure if anyone else has seen it either...

5) I'm not sure what your usage scenario is about the "FullscreenRatio"? You have an option to either keep the correct Aspect Ratio, or if you disable that, stretch the image to the full screen. Is that not enough?

6) About the horizontal offset, maybe we can add it in a future version, we'll see.

Please, keep those issues separate in the future so we can close and handle them separately. It would  help to avoid the confusion for other people reading through them as well. ;-)

**Comment by CypherXG** [comment]
To Question 1:
Pi Resolution 1080p 60Hz.
Amiga Resolution 1024x768 32Bit
Config:
CPU 68040/FPU Intern JIT/CPU Speed fastest or turbo does no matter
Chipset AGA/Extra Chipset CD32/Blitter Normal/Copper Fast Copper/Collision Sprite vs Sprite
Kickrom CD32/Ext. Rom CD32
RAM: 8MB Chip, Slow OFF, 24Bit Fast OFF, 32Bit Fast 128MB/RTG 16/A4000 OFF/A4000 CPU OFF

Here you can see the 50/60Hz Bug:
https://www.youtube.com/watch?v=WjtnC2eBYbw
Here you can see the 49/59 Hz Bug. Config is the same and has nothing to do with the Picasso Mode.
https://youtu.be/XOOm2Txk4Gw
The FullscreenRatio is a really cool gadget to zoom for a real CRT TV or an Commodore 1084 Amiga Monitor.

**Comment by midwan** [comment]
@CypherXG 
Thanks for the videos :)
I'll take a closer look a this with a setup like yours and see if I can recreate it. I'll update you once I have more news on it.

**Comment by midwan** [comment]
Regarding the Turbo mode issue:
Like I said, Turbo mode was added for CPU intensive applications which don't require much chipset time. It's designed to work well with Frameskip (since we assume you don't want 50/60 FPS but instead max CPU power), and it's certainly not meant for games or demos, which require more from the chipset.

I'm thinking of exposing the timing settings to the users somehow (maybe on the GUI or a config file), so you can change these on-demand and save them without the need to re-compile. But until then, I think it's best to leave this as-is for now.
