### ISSUE TITLE
Won't remember button assignment in "Cabal"

### ISSUE THREAD

**Issue by Fable-Son** [midwan/amiberry#235]
In Cabal you have to press F1 or F2 for 1 or 2 player. So in "Input" I set the shoulder buttons to F1 and F2, and then continue. And they Work great. But if I exit, and start up the game Again. The new button mapping is gone :/

**Comment by ransom1122** [comment]
Have you saved the config?

Save it.. quit and try it again.

**Comment by Fable-Son** [comment]
I could not find a save button. Only a folder where I could save in the game. So I just thought that it saved the changes automatic?
Sounds like I missed a button 😁

**Comment by ransom1122** [comment]
No you must save the config if any changes are made... Has it worked now?

**Comment by Fable-Son** [comment]
Sounds like I need glasses 😁 Next time, I will try and find the save button. But as I remember, there is only "Quit" "Restart" "Continue" and something else, in the bottom of the GUI screen. Where is the save button? It's embarrasing if the button is right in front of me. So I hope it's hidden? 😊

**Comment by ransom1122** [comment]
https://i.imgur.com/Js6uspF.jpg

Dont forget to turn Autofire Rate OFF. By default Amiberry has it on Medium.

It's found in Input Tab im Amiberry GUI.

**Comment by midwan** [comment]
@Fable-Son 
Settings such as this are saved in Configs, which can be specific to the game you want to play (or more generic, such as a config for all your AGA games for example, it's up to you).

Don't forget to load the config the next time you want to use the same kind of mapping! :)
