### ISSUE TITLE
Request: Disable autofire by default

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#238]
Hi.

It seems all quickstart settings have autofire rate = medium. In my opinion I believe this should be off. It causes major problems to games that require the button to be pressed down. 

Cabal - Character cant stay still and shoot.
Lotus - acceleration goes up and down

Any many more...

If autofire is required for shootemup games then it shouldbe optional for the user to ammend it in input tab themselves.

**Comment by midwan** [comment]
I agree, autofire should be off by default I think.
I'll make the change in the `dev` branch and eventually merge it back into master with everything else that is being fixed there...

**Comment by Voljega** [comment]
Rick Dangerous is also a good test case, the actions (like UP + fire to shoot pistol) are close to impossible to do with autofire activated

**Comment by ransom1122** [comment]
There is a lot of games that are affected. Turrican's laser cannon
Any game that requires acceleration Supwr Hang On. Etc etc
