### ISSUE TITLE
Controller config files do not work with controller names containing a /

### ISSUE THREAD

**Issue by AndrewReidNZ** [midwan/amiberry#244]
### Expected behavior
Retroarch seems to strip "/"'s from the controller name when naming its controller config files

### Actual behavior
1. It is not possible to create a config file of the same name as a controller if the controller name contains a "/".
2. Amiberry does not find the retroarch controller config file because it has the "/" removed from the file name.

### Steps to reproduce the behavior
My controller name is "Shanwan PS3/PC Gamepad".
It is not possible to create a file name with this name due to the "/".
The retroarch config file for this controller is "Shanwan PS3PC Gamepad" - i.e. the / has been removed.

**Comment by CypherXG** [comment]
Rename the file it to PLAYSTATION(R)3 Controller.cfg
I had the same Problems with my Shawan Wireless PS3 Contoller in #151

**Comment by HoraceAndTheSpider** [comment]
Does it show a `/` inside Amiberry , on the input panel?

**Comment by AndrewReidNZ** [comment]
Yes in Amiberry it is listed as "Shanwan PS3/PC Gamepad".
The retroarch .cfg file is Shanwan PSCPC Gamepad - hence amiberry cant match it up.
I cant create a custom .cfg file with a / in the name...

@CypherXG  - i dont think renaming the cfg file it as you suggested will help - Amiberry wont't match it up.

The best solution would seem to be to duplicate what retroarch does and strip any "/" characters from the names it uses (and presumably any other reserved characters).

**Comment by midwan** [comment]
@AndrewReidNZ 
I've found the place in the code that tries to fetch the filename, and it is indeed looking for something with the controller name + ".cfg".

I'll add a filter that strips out any invalid filename characters there. If we have a link to what retroarch is doing exactly, it would be nice, so we can follow the same pattern. But either way, it's not too complicated to add.

**Comment by midwan** [comment]
@AndrewReidNZ 
Just pushed a fix for this, but it would be best to test it on an environment with the problem.
Please let me know if something doesn't work as expected after this, and we'll re-open this issue.

**Comment by midwan** [comment]
@AndrewReidNZ 
Did this work for you? I didn't hear back about it, and now that I look at something similar I have my doubts as I think there's a bug there :)

**Comment by AndrewReidNZ** [comment]
Sorry, I've been meaning to reply.  No it didn't seem to work - it's not picking up the retroarch controller config file.
