### ISSUE TITLE
SDL_Error: No available video device on RPi3 with the SDL2 Dispmanx build

### ISSUE THREAD

**Issue by rabejens** [midwan/amiberry#245]
### Expected behavior
Amiberry should start up as normal

### Actual behavior
Error message:
```
INFO: SDL could not initialize! SDL_Error: No available video device
Internal error; file src/osdep/amiberry_gfx.cpp, line 325
Aborted
```

### Steps to reproduce the behavior

- Start with Raspbian Stretch Lite
- Install SDL2 as per the [instructions in the Wiki](https://github.com/midwan/amiberry/wiki/Compile-SDL2-from-source)
- Install the [Prerequisites](https://github.com/midwan/amiberry/wiki/First-Installation)
- Build amiberry with `make -j2 PLATFORM=rpi3-sdl2-dispmanx`
- Run amiberry

### Followup

I get the same error with the binary.

**Comment by solskogen** [comment]
Post all lines in /boot/config.txt that is not commented out, please.

**Comment by rabejens** [comment]
I only have these in there:

```
disable_overscan=1
dtparam=audio=on
```

**Comment by midwan** [comment]
@rabejens 
You'll need to enable the `fkms` driver using `raspi-config`, in order for SDL2 to be able to open a screen using `KMSDRM`.

**Comment by rabejens** [comment]
I'll try this later, currently not near my RPi.

**Comment by rabejens** [comment]
With the "Fake KMS" setting, it works. With the "Full KMS" setting, the config GUI works but as soon as starting the emulation, the screen goes black.

**Comment by midwan** [comment]
@rabejens 
That is expected behavior, since the "Full KMS" disables Dispmanx. If you use "Full KMS", you cannot use the Dispmanx versions, only pure SDL2 targets (which for the RPI, are slower at the moment).
