### ISSUE TITLE
GUI working incorrectly when setting up multiple drives for a multi-disc game

### ISSUE THREAD

**Issue by AndrewReidNZ** [midwan/amiberry#246]
### Expected behavior
Should be able to set up a multi-drive config for a game that uses multiple disks.

### Actual behavior
When multiple drivers are selected and assigned a adf file, the GUI sets the adf file name on all of the drives to the last adf file that was chosen.

### Steps to reproduce the behavior
Choose a multi disc game.
Assign DF0 to game disk 1
Assign DF1 to game disk 2
   notice DF0 has also been changed to this disk
Assign DF2 to game disk 3
   notice DF0 and DF1 have also been changed to this disk
etc

**Comment by midwan** [comment]
Thanks for reporting this, we'll get it fixed.

**Comment by midwan** [comment]
Fixed in the dev branch, will get merged into master on the next update!
