### ISSUE TITLE
Open GUI menu in game

### ISSUE THREAD

**Issue by Fable-Son** [midwan/amiberry#247]
### Expected behavior
Pressing F12 normally opens the menu. 
### Actual behavior
After the v2.13 update, it's stopped working. I tried accessing the menu by selecting it in the games menu in ES, to change the key to a nother. 
But chat just made the menu freeze up. And then it crash
### Steps to reproduce the behavior
-Press F12 in a game.... 
-Change the key to something else in the menu

**Comment by midwan** [comment]
@Fable-Son 
Thanks for reporting this. Which version are you testing with (SDL1 or SDL2?), and on which distro please?

**Comment by Fable-Son** [comment]
Damn. I don't know 😟
But it's a Pi3. And I updated it through Retropie menu, and installed from source 😊
Is it good enauh, or is there somewhere that it can se what you can use as info? Is it written in the menu, if it's SDL1 or 2?

**Comment by midwan** [comment]
@Fable-Son If it's RetroPie, then it's SDL1.
I have confirmed that the emulator works as expected regarding this, so it must be something with your configuration file(s).

Some users reported that UAE Config Maker caused such problems because of incorrect values in the config, so I'm discussing this with @HoraceAndTheSpider to find a solution.

**Comment by HoraceAndTheSpider** [comment]
UAE Config Maker has been updated to fix the default values, but you should check your hostconfig file value for these as it may need updating to say “F12” etc as this file is not automatically updated

**Comment by Fable-Son** [comment]
Thanks. I will try that.
Just to make shure. Where are the files located, that you want me to look at?
I tried earlier to look in some of the files. But I was unsure of wich ones to look in 😊
