### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#248]
As of friday, Amiberry is now integrated officially in Recalbox, an important thing for me and for our users as it is a two years work (started on UAE4ARM) and my first contribution to an open source project.

https://www.recalbox.com/blog/en/post/blog-2018-02-09-amiga/

Thank you for all your help, for now we are using a dev build from mid-december, but I soon as possible I will work on updating to a newer version with the new controller scheme.

**Comment by midwan** [comment]
@Voljega 
Awesome! Thanks for the feedback! :)
If you need any help integrating the latest version, let me know...
