### ISSUE TITLE
Request - acces save states with controller

### ISSUE THREAD

**Issue by MarcoVer77** [midwan/amiberry#249]

**Comment by MarcoVer77** [comment]
Emulators on retropie have the option to save states by pressing select+left trigger. Is it possible for Amiberry to have that also?

**Comment by HoraceAndTheSpider** [comment]
I will be adding this after I overhaul the controller mapping again (only internally) but it won’t be soon 


For now you can access the gui and load save states using the controller already ( I do this daily!!)

**Comment by MarcoVer77** [comment]
What button combination do you use to access the gui? Is that configured manually?

**Comment by MarcoVer77** [comment]
Oh wait i can change that in the hostconfig.uaetemp right?

**Comment by HoraceAndTheSpider** [comment]
HotKey + menu button depends on your retroarch controller Config 


No longer needed in the hostconfig file since the latest version.

**Comment by midwan** [comment]
Closing this for now then, since it's already planned.
