### ISSUE TITLE
[WHDLoad issue] Dungeon Master

### ISSUE THREAD

**Issue by Naviara** [midwan/amiberry#250]
In Dungeon Master, you can save your actually game. You can press "save game" and then it just saves it,
but actually when you want to save a game in Dungeon Master, the screen becomes black and nothing more happens. When you afterwards want to reload the game, the WHDBooter comes up finding an error, deleting your WHDLoad slave file and creating a new one, of course saving don't work there either.

**Comment by HoraceAndTheSpider** [comment]
Sounds more like a Whdload / uae Config Maker (and booter) problem than Amiberry’s

What is the Whdload error that comes up on reloading? Clearly the saving has caused a problem which is then displayed on the next load and it would be useful to know what that error said. 

Thanks

**Comment by HoraceAndTheSpider** [comment]
A simple work around is to use Amiberry’s save states for your game saving until a permanent solution is found.

 Also could you please say what Whdload slave version you are using?

**Comment by Voljega** [comment]
I thought save state in amiberry weren't compatible with WHDLoad ? I tried it but it didn't work

**Comment by HoraceAndTheSpider** [comment]
Save states work fine with Whdload as long as you have a specific .uae file for that game.

The issues that can occur are only with games that constant write saves to the drive as you play (auto saving) and if your state is out of sync with those changes

**Comment by Voljega** [comment]
What do you mean by specific uae ?

**Comment by midwan** [comment]
@Voljega 
I believe he means a specific config file for the game...

**Comment by Naviara** [comment]
Horace / midwan you're right, it seems like a WHDLoad issue, nothing wrong with Amiberry - tried the same with WinUAE on my PC now and got the same result.

Error:

DOS-Error #202
(object is in use)
on preloading file "whdscript_debug"
File "Disk.2" is compressed using XPK but not cached.

adding this XPK libraries to WHDLoad_Booter libs dir doesn't change.

sorry for opening this issue .. you can close .. I am using the Disk Version now - It works with Savedisk in DF1, so it also can be used in Chaos strikes back... 

thanks for investigating and greetings
Anthony

**Comment by midwan** [comment]
@Naviara 
Thanks for confirming! :)

**Comment by Voljega** [comment]
For the uae file, I just wanted to know what exactly 'specific' file means.

In my case the uae for any whdload game is entirely generated in the ./conf/ directory of amiberry, with a plain dumb never changed name, not related to the name of the game.
amiberry is launched with plain './amiberry"

So in that case save state doesn't seem to work for WHDL, what am I missing ? 
Naming the uae file like the game ? Will it still launch by being detected automatically in "./conf" then without having to pass it as en explicit paramater ?

**Comment by Naviara** [comment]
@HoraceAndTheSpider 

yes I can do this, where do you want me to send it to?

**Comment by Voljega** [comment]
@HoraceAndTheSpider Ok so it may simply work if the generated uae has the same name than the game, I will try it

**Comment by HoraceAndTheSpider** [comment]
@Naviara my username here @ hotmail dot com

Thanks :)

**Comment by Naviara** [comment]
Done.. I also attached a disk combo, wich works perfect in Amiberry with shared Savegame Disk for DM & CSB (import DM Save, DM savegame and CSB savegame all working on the same Savegame Disk in DF1:)

greetings,
Anthony
