### ISSUE TITLE
Chaos Engine CD32 ISO: no video

### ISSUE THREAD

**Issue by deVolff** [midwan/amiberry#253]
Hi, first of all let me thank you for all your great work on this project. Amiberry is an awesome emulator, and I continue to be impressed by it. I've dabbled in Amiga emulation on PC for years, but only recently discovered the Pi+Amiberry, and since day 1 I thoroughly enjoy it on an almost daily basis. Thanks a million, and please keep up the good work!

### Expected behavior
Chaos Engine CD32 (ISO) loads, starts up, displays video and plays sound.
### Actual behavior
Chaos Engine CD32 (ISO) actually loads and starts up; after a while you can hear the game's intro speech & music, but the screen remains blank - no video is visible. You can switch to Amiberry GUI using F12 or through controller buttons; the GUI is visible as normal. After switching back to the game the screen is black, but with sound/music still audible.
### Steps to reproduce the behavior
This is reproduced on a RPi 3 running Amiberry 2.12. The Chaos Engine CD32 ISO which I'm using is CDD3445 on Emuparadise.

The same Chaos Engine CD32 ISO starts up & works fine (video + audio) on a PC using WinUAE 3.5.0.

Also, it's not a general CD32 problem on Amiberry (I think), as for example Speedball 2 CD32 (ISO) runs perfectly fine for me (video + audio).

**Comment by midwan** [comment]
@deVolff 
Thanks for the kind words and for reporting this.
I'll try to recreate it and see where we are.

**Comment by midwan** [comment]
@deVolff 
This actually works for me.

Here's what I did:
- Extracted the ZIP file you mentioned in a new directory
- Launched Amiberry, used Quickstart to select CD32
- Selected the .cue file in the directory I extracted the ZIP file above
- Clicked on Start.

The intro showed normally, no black screen here.

**Comment by deVolff** [comment]
Hi @midwan , thank you for looking into this. I just tried that, and hey - yes, it does indeed work fine through Quickstart! Cheers.

What does NOT (and hasn't) worked properly for me was the direct startup through an .UAE file. The UAE file was originally generated using Horace's UAE Config Maker (an excellent tool by the way). When starting through the UAE I'm getting no video, as reported originally.

I'm attaching the UAE file here (zipped). 
[Chaos Engine, The (v1) [CD32] [ISO].zip](https://github.com/midwan/amiberry/files/1734795/Chaos.Engine.The.v1.CD32.ISO.zip)

You may notice that the CUE file name in the UAE is different than in the original Chaos Engine ZIP - that's because I renamed the Chaos Engine files after unzipping them, as I was worried about their long file names and '!' characters present in the long file names. So I just changed the files' naming convention to something very simple, i.e. to this: 
`pi@retropie:~/RetroPie/roms/amiga-data/Games_CD32/ChaosEngineCD32 $ ls -la
total 543020
drwxr-xr-x 2 pi pi     4096 Feb  8 22:41 .
drwxr-xr-x 4 pi pi     4096 Feb  8 21:32 ..
-rw-r--r-- 1 pi pi  4483072 Feb  8 14:24 ChaosEngineCD3201of14.iso
-rw-r--r-- 1 pi pi 11948204 Feb  8 14:24 ChaosEngineCD3202of14.wav
-rw-r--r-- 1 pi pi 47698604 Feb  8 14:24 ChaosEngineCD3203of14.wav
-rw-r--r-- 1 pi pi 44688044 Feb  8 14:24 ChaosEngineCD3204of14.wav
-rw-r--r-- 1 pi pi 32495276 Feb  8 14:24 ChaosEngineCD3205of14.wav
-rw-r--r-- 1 pi pi 45741740 Feb  8 14:24 ChaosEngineCD3206of14.wav
-rw-r--r-- 1 pi pi 31968428 Feb  8 14:24 ChaosEngineCD3207of14.wav
-rw-r--r-- 1 pi pi 49805996 Feb  8 14:24 ChaosEngineCD3208of14.wav
-rw-r--r-- 1 pi pi 57708716 Feb  8 14:23 ChaosEngineCD3209of14.wav
-rw-r--r-- 1 pi pi 50107052 Feb  8 14:23 ChaosEngineCD3210of14.wav
-rw-r--r-- 1 pi pi 54171308 Feb  8 14:24 ChaosEngineCD3211of14.wav
-rw-r--r-- 1 pi pi 44311724 Feb  8 14:24 ChaosEngineCD3212of14.wav
-rw-r--r-- 1 pi pi 44462252 Feb  8 14:24 ChaosEngineCD3213of14.wav
-rw-r--r-- 1 pi pi 36409004 Feb  8 14:24 ChaosEngineCD3214of14.wav
-rw-r--r-- 1 pi pi     1171 Feb  8 22:37 ChaosEngineCD32.cue
`

This directory (CUE, ISO etc.) works fine through QuickStart - but there is no video when starting via the UAE file.

**Comment by midwan** [comment]
@deVolff 
Thanks for confirming...

Then this is obviously a problem with the config file, at least one of the settings in there is causing the problem ;)

@HoraceAndTheSpider I'm not sure if this config file is already updated somewhere or it's just incorrect?

**Comment by HoraceAndTheSpider** [comment]
I’ll have to investigate which bit of the Config causes this

**Comment by midwan** [comment]
@HoraceAndTheSpider 
It's an older config, if you notice the `enter_gui` key is still assigned to `293` instead of `F12` for example

**Comment by HoraceAndTheSpider** [comment]
Most of it is correct though? It does includes Amiberry.x Instead of pandora.x
