### ISSUE TITLE
BUG - Diskdrives on GUI showing same image path/names

### ISSUE THREAD

**Issue by Naviara** [midwan/amiberry#255]
**### Expected behavior**
V2.13 - I insert one Disk in DF0: and a different one in DF1: / the GUI reflects that showing me the path with image name on both drives.

**### Actual behavior**
When you go to Disk drives and insert an ADF image into DF0: and a different image in DF1: then the image of DF0: also changes to the same image insert in DF1:  It looks like in both drives you have put in the same ADF image. It's just a cosmetic "GUI" issue, in the background the two images are still different, but it can be confusing.

**### Steps to reproduce the behavior**
Just put two different images (best with different paths) in DF0: and DF1:

**Comment by midwan** [comment]
@Naviara 
Thanks for reporting this, it has already been fixed in #246 and will be merged back into master with the next update. :)

**Comment by Naviara** [comment]
Midwan, sorry for double report, I will check all closed ones the next time before I post!

**Comment by midwan** [comment]
@Naviara 
No problem at all :)
