### ISSUE TITLE
Amiberry with Xin Mo dual arcade / vertical axis of operation reversed 

### ISSUE THREAD

**Issue by jbodders** [midwan/amiberry#257]
Firstly just to say great update to the platform - some fantastic features! I'm a bit of a noob when it comes to the .cfg files and behaviour so just trying to work out if this is a known issue with dual arcade controls.

I'm running the latest Amiberry, Retropie 4.3, on a Pi3 as part of an arcade setup with Xin-Mo dual arcade controls.

### Expected behavior

1) Xin-Mo Controls are configured via the GUI.
2) Amiberry detects the Xin-Mo controls from the retroarch configuration.
3) [R] is seen next to the custom controls field
4) In game the joysticks work as per configured in retroarch.

### Actual behavior

Everything works as above,  with the exception of 4) in game the Up/Down axis are reversed, i.e. pulling down on the joystick makes the in game sprite move up and vice-versa, the horizontal axis works as expected and configured.

### Steps to reproduce the behavior

Using setup as per above (Rpi3, retropie 4.3, Xin-Mo dual arcade)
Configure custom controls via GUI
Launch Amiberry
Go to Input and select Xin-Mo controls for port 0 and port 1
Check for [R] in custom control menu
Launch any game

I have tried editing the Xin-Mo cfg file (with swapped vertical axis) in the autoconfig folder and setting this as the path to solve, but this did not work. see attached images.
![img_7980](https://user-images.githubusercontent.com/36568819/36342605-b9817068-13f8-11e8-9f1e-aa3f9191b9aa.JPG)
![img_7981](https://user-images.githubusercontent.com/36568819/36342606-b99b1fea-13f8-11e8-9be3-215d27a23317.JPG)

**Comment by va-lemon** [comment]
@jbodders 
I use the Xin-Mo Dual Arcade controller as well (though with just one set of controls) and this is how I have Amiberry configured. I've also attached my Xin-Mo cfg file so you can compare against yours. On my setup, the joystick responds as expected i.e. up makes sprite go up and down makes the sprite go down.
One thing I noticed in your config is that your RetroArch configuration path is not pointed to the correct location. Try to update it to /opt/retropie/configs/all/retroarch.cfg. On your Custom Controls tab is there [R] displayed next to the Input Device drop-down as in my screenshot?
![paths tab](https://user-images.githubusercontent.com/31974401/36704526-ba7eb9f2-1b2e-11e8-8ffc-594d10f9e398.JPG)
![input tab](https://user-images.githubusercontent.com/31974401/36704547-ccddaaa4-1b2e-11e8-82e2-ccdc469910c9.JPG)
![custom controls tab](https://user-images.githubusercontent.com/31974401/36704553-d2a98aac-1b2e-11e8-82bd-57d826a1b18d.JPG)
![misc tab](https://user-images.githubusercontent.com/31974401/36704558-d7c0886a-1b2e-11e8-8bbb-6250b30ffca5.JPG)

[Xin-Mo Xin-Mo Dual Arcade.cfg.txt](https://github.com/midwan/amiberry/files/1760837/Xin-Mo.Xin-Mo.Dual.Arcade.cfg.txt)

**Comment by jbodders** [comment]
Hi 

Thanks for the response - interestingly my Xin-Mo .cfg file is different to yours (see attached). I will copy your configuration file and see if that changes things!

Also will update the pathway as you suggested and let you know how I get on!
This is what I currently have as .cfg file.
input_device = "Xin-Mo Xin-Mo Dual Arcade"
input_driver = "udev"
input_l_btn = "4"
input_start_btn = "9"
input_up_axis = "+0"
input_a_btn = "1"
input_b_btn = "0"
input_down_axis = "-0"
input_r_btn = "5"
input_right_axis = "+1"
input_x_btn = "2"
input_select_btn = "8"
input_y_btn = "3"
input_left_axis = "-1"
input_vendor_id = "5824"
input_product_id = "1505"

**Comment by jbodders** [comment]
Ok - so I tried setting the paths per your note and replacing my Xin-Mo.cfg file with the one you attached.

The behaviour of the controllers reverted to pre-latest Amiberry release behaviour i.e. controls are all 90 degrees out i.e. North / up = right, Right = down and so on…..

Going back and using Emulation station UI, or retroarch to configure/bind the controls reverts the behaviour to the original situation i.e. North/up = down, South / down = up

Note: in the other emulators the controllers work and are mapped as per Emulation station user input configuration.

It is really odd!

I've tried going into the Xin Mo.cfg file and just reversing the vertical axis but that doesn't seem to work either….I don't understand the retroarch to config file enough to try other options.

**Comment by va-lemon** [comment]
Actually, the 90 degree difference in controls is to be expected as the joystick can be mounted in different orientations. Can you post a screenshot of your Amiberry Custom Controls tab? I don't use any custom controls within Amiberry as all the joystick and button assignments are being read from the cfg file.

**Comment by HoraceAndTheSpider** [comment]
I will look into this properly but just to reiterate that the custom controls tab is only needed her to verify that retroarch mapping is working (see [R] symbol)

Standard joystick modes, including directions, do not require that panel.

**Comment by jbodders** [comment]
Thanks for the response and looking into this….it is so close to working as expected (the [R] symbol appears etc and the horizontal axis are fine) but somewhere the vertical axis are being reversed!

**Comment by HoraceAndTheSpider** [comment]
OK, so it looks like in this mode the  V-axis is 'abnormally' inverted for your controller... at the moment, Amiberry only looks for the 'positive' axis number (0 for the vertical axis here) and doesnt worry about the +/- value. This causes an issue here because 'down' (which it is looking for) is negative on your controller

Unfortunately, this can only be fixed with some hard-coding so unless you can put the device into the same mode as @va-lemon you may have to wait for a fix....

**Comment by jbodders** [comment]
Thanks for getting back to me so promptly, will see whether I can replicate what @va-lemon suggested.

Otherwise I’m into hard-coding territory....any advice on where to start with this:

I.e. which files do I need to change and where do I need to put them to ‘hard code’ the controls for Amiberry? Is there somewhere I can use a reference to set this up.

**Comment by HoraceAndTheSpider** [comment]
in the file `amiberrry_input.cpp` , in the routine `static void read_joystick(void)` you could try inverting the values for the Vertical/Y-Axis. 

so try swapping this out:
```                            // handle the Y axis   
                            val = SDL_JoystickGetAxis(Joysticktable[hostjoyid], current_controller_map.lstick_axis_y);
                            setjoystickstate(hostjoyid + 1, 1, val, 32767);```

with

```                            // handle the Y axis   
                            val = SDL_JoystickGetAxis(Joysticktable[hostjoyid], current_controller_map.lstick_axis_y);
                            setjoystickstate(hostjoyid + 1, 1, val, -32768);```

There is also some similar code below for the remapping of the Axes to the DPAD remapping, but i would check the above works first.

**Comment by jbodders** [comment]
Thanks again - will give it a go!
Where is the .cpp file - i.e. which directory?

**Comment by midwan** [comment]
@jbodders 
The file is located in `src/osdep/amiberry_input.cpp`

@HoraceAndTheSpider 
Seems to me this could be solved if we added an "Invert" option for the two Axis options?

**Comment by HoraceAndTheSpider** [comment]
I dont think we should need to add an invert, but instead adapt the RetroArch reading code to pick up the 'sign' of the AXIS value, and apply an internal invert depending on that. 

It's definately something i intend to pick up when improving the controller code though.

**Comment by jbodders** [comment]
Thanks again both - real beginners question but when I drop into the shell (outside of the retropie GUI) I can't locate the src/osdep pathway. Do you have the full reference ie from pi/etc…./
thanks

**Comment by HoraceAndTheSpider** [comment]
That will depend on where you install the source code! You could put it anywhere

**Comment by jbodders** [comment]
Good point :-)
I followed the - manage packages -> Amiberry -> “install from source”,  in the Retropie GUI, trying to understand where that defaults the files to....

**Comment by HoraceAndTheSpider** [comment]
I am not sure that installing from source within RetroPie will not delete the source code after it has compiled anyway... 

probably it is better to follow the Readme/Wiki guide on this page.

**Comment by HoraceAndTheSpider** [comment]
@jbodders 

Changes in the dev branch should now pick up which sign is used for an axis, and will swap the direction accordingly.

This is picked up from the retroarch compatible cfg file. I tested with a few different controllers and was able to deliberately invert the specific axis simply by using a “minus” sign on the relevant axis settings. Hopefully this will resolve your problems.

**Comment by midwan** [comment]
@jbodders 
Version 2.21 is now merged into master, so you can easily get it from RetroPie's "compile from source" option.

Closing this issue unless we find out there's still a problem.

**Comment by jbodders** [comment]
Realised I hadn't closed the loop on this. To confirm this now works (as expected) and I can reverse axis - thanks for your support on this one.
