### ISSUE TITLE
Picasso96 not working on ClassicWB 3.9 (X-Server, 100% CPU/crash)

### ISSUE THREAD

**Issue by Xnyle** [midwan/amiberry#258]
I installed OS3.9 on the current DietPi/Amiberry (suggested download, RPI3)
Then used that to init ClassicWB 3.9, Installed Picasso96. So far so good.

UAE Config from here http://classicwb.abime.net/classicweb/instructionsos39.htm

Whenever I select a uaegfx mode, uae4arm crashes (black screen, nothing more).

I guess that's a bug or at least some non straightforward config needed?

It's working with the SDL2 version but then everything gets horribly slow, even in/on low resolutions.
On SDL2 Version CPU load is only at about 50-60%

Not sure if this is also a bug or if RPI simply isn't fast enough for uaegfx?

**Comment by midwan** [comment]
Which version of Amiberry do you have installed?
The bundled DietPi distro is due for an update, as DietPi got upgraded to v1.6+ and that image is still based on the older one. @Fourdee is working hard on that, so it should be available soon.

Also, the SDL2-Dispmanx version is the best one to use on a RPI, since it will be much faster than the pure SDL2 one.

For now, I'd recommend you try with a normal Raspbian Stretch environment, install the latest version of Amiberry (check the [Wiki](https://github.com/midwan/amiberry/wiki) page for instructions if needed) and test again.

**Comment by Xnyle** [comment]
I was using the old bundled version.

I'm trying to compile it on https://github.com/bamarni/pi64 which will probably fail ;-)

Arm64 is a target I would very much like you to consider as well.

Probably way more performance to get from a clean, mainline kernel based, up to date stretch that is actually using the RPI3s hardware, not that dreaded "we want to have backwards compatibility" raspbian.

Who is using RPI1/2 anyway anymore ;-)

**Comment by midwan** [comment]
@Xnyle 
Thanks, I wasn't aware of pi64.  I'll give it a try...

I believe most of the problems you mentioned above are fixed already in the latest version, so I'd recommend upgrading to that first.
If you see any issues with the latest version, feel free to mention them and we'll take a look!

**Comment by Xnyle** [comment]
Obviously I failed, 

g++: error: unrecognized command line option '-mfpu=neon-fp-armv8'... Which is not known on aarch64, If I remove the switch, the defines in src/include/sysdeps.h are not able to figure out the cpu type.

Funny you have a pine64 target that only uses -march=armv7-a?

I guess I'll just wait, as I don't really want to use raspbian.

And this issue is slightly getting of topic  :-)

**Comment by midwan** [comment]
@Xnyle 
Yeah, the pine64 target is experimental and doesn't yet work (I added it in order to eventually make it work). :)

**Comment by Xnyle** [comment]
As written, I would appreciate it if you get it to compile on Arm64. Besides Rpi3 and Pine64 there is also the Orange Pi Win / Orange Pi Prime, both are cheap, have lots of power and would benefit as well. And the Rock64 boards, and...
