### ISSUE TITLE
SDL2 crash when using HighGFX Video modes

### ISSUE THREAD

**Issue by Xnyle** [midwan/amiberry#259]
When using screenmodes from http://aminet.net/package/driver/moni/HighGFX40_6 the SDL2 + Dispmanx version crashes instantly.

Why I'm not using Picasso you ask? Because my real Amiga doesn't hava a graphics card, only a Scandoubler. But I would like to copy System: between installations.

HD720 on SDL -> crash
P96 on Amiga -> crash

HD720 works fine on WinUAE, so I hope this is no blocker ;-)

**Comment by CypherXG** [comment]
Why are you using a Monitor Driver with the Pi?
Make no Sense.
Use P96 and the correct rtg.library. You need Version 40.3994 or bigger.
http://aminet.net/package/driver/video/RTG403994p.lha
In the standard Picasso download ( http://aminet.net/package/driver/video/Picasso96 ) is no 3994 Version , only 40.3945 and this doesn't work with the Amiberry. Try to install the newer Version

**Comment by Xnyle** [comment]
> Make no Sense.

You did not read, what I wrote, right?

It makes sense, because 

> I would like to copy System: between installations.

Not once, but so often, that It gets quite cumbersome to install/uninstall P96 and change screen modes every time.

If you won't implement support for HIGHGFX that's ok, but please don't justify it with "Makes no sense"

**Comment by midwan** [comment]
@Xnyle 
You don't need to uninstall the whole P96 package, just move the monitor driver from Devs:Monitors to Storage:Monitors, and that would be enough to disable it.

Regardless, thanks for bringing this up, I'd like to run some tests and find out where exactly this crashes and why. Although I probably can't give it high priority right now (unless it's an easy fix), it shouldn't crash the emulator at least...

**Comment by Xnyle** [comment]
Thanks!

One Question: Do you know where / how the currently selected Screenmode is stored on the filesystem?
I'm thinking about automatically changing that setting in early SS (if possible) depending on what isuaertg returns.

**Comment by midwan** [comment]
@Xnyle 
The selected mode is stored in ENVARC: in a generic filename, but I can't remember the filename at the moment. :)

**Comment by Xnyle** [comment]
Just in case someone finds this later, this is my "change screenmode on boot" quick and dirty solution:
After install P96 you need isuaertg from this [http://www.a1k.org/forum/attachment.php?attachmentid=123585&d=1460195710](url). Then move P96 monitor driver to Storage: and copy screenmode.prefs for both systems once (in my case screenmode.hd720 and screenmode.p96)

`
;Check if we have UAE RTG
FAILAT 11
C:isuaertg >NIL:
IF WARN
  COPY >NIL: SYS:Prefs/Env-Archive/Sys/screenmode.p96 SYS:Prefs/Env-Archive/Sys/screenmode.prefs
  IF NOT EXISTS SYS:Devs/Monitors/uaegfx
    COPY >NIL: SYS:Storage/Monitors/uaegfx SYS:Devs/Monitors/uaegfx
    COPY >NIL: SYS:Storage/Monitors/uaegfx.info SYS:Devs/Monitors/uaegfx.info
  ENDIF
ELSE
  COPY >NIL: SYS:Prefs/Env-Archive/Sys/screenmode.hd720 SYS:Prefs/Env-Archive/Sys/screenmode.prefs
  IF EXISTS SYS:Devs/Monitors/uaegfx
    DELETE SYS:Devs/Monitors/uaegfx QUIET FORCE
    DELETE SYS:Devs/Monitors/uaegfx.info QUIET FORCE
  ENDIF
ENDIF 
`

**Comment by midwan** [comment]
@Xnyle 
The crash happens because the emulator is trying to open a GUI window to notify you that this specific feature is not supported. :-)

The message would be "Variable beam counter comparator enabled. Not supported in Amiberry." specifically.

Of course, it shouldn't crash when trying to tell that to you, so I'll get that fixed. Then we can see how hard it is to support this feature also...

**Comment by midwan** [comment]
@Xnyle 
Fixed the crash, so now you'll get a warning message first, then it will continue with the resolution you requested (though it will not show correctly for now, it's still kind of usable).

I'll look into adding support for this feature in another update.
