### ISSUE TITLE
Build issue "exit is not a member of std"

### ISSUE THREAD

**Issue by escalade** [midwan/amiberry#26]
I'm trying to cross compile this using the LibreELEC toolchain, but running into a build error:

http://pastebin.com/gCRPEL9w

Any ideas? Using GCC 5.4.

**Comment by midwan** [comment]
1) You're using CPU options twice in the same line, "-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard" ... "-mcpu=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4". Only one of those should be used.
2) Try adding -std=gnu++14 in the CFLAGS and see if that helps.

**Comment by escalade** [comment]
I added -std=gnu++11 and that got me further. First there was a missing include guichan.hpp (I thought this used guisan instead?), adding includes from both of guichan/guisan into src/include/ solved that but now I'm getting a different error:

http://pastebin.com/ib20RFk4

I'm trying to compile the SDL2 branch btw.

**Comment by midwan** [comment]
Thanks, that should not be part of the Makefile indeed (as guisan includes its own version).
I'll fix it in the Makefile.

So far the GUI part works on SDL2, with the exception of a glitch in the Configurations list (only one is visible, even though you can select the others using the keyboard). But the emulation screen needs some work, as it doesn't work as it should...

**Comment by escalade** [comment]
There's guichan includes in src/osdep/pandora_gui.cpp and src/osdep/gui/EditFilesysHardfile.cpp as well.

**Comment by midwan** [comment]
Thanks, those were missed earlier and I just fixed them.

There should be no further references to guichan now.

**Comment by escalade** [comment]
guichan is included in src/osdep/pandora_gui.cpp again :)

**Comment by midwan** [comment]
It was until yesterday, but not anymore (fixed a few other issues with compiling in on the Pi also).
Could you please get the latest and check again?

**Comment by escalade** [comment]
Yep, fixed :)
