### ISSUE TITLE
Updating from v2.12 to v2.14

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#260]
Hi midwan..

I am trying to manually update from v2.12 to v2.14 with difficulties again.....  Because I do not have permission I followed your manual method form above..

1. I deleted adfdir from my pi
2. I transferred all data from **amiberry-rpi3-sdl1-dispmanx-Jessie-v2.14.zip** to **/home/pi** 
(Renaming amiberry-rpi3-sdl1 to Amiberry)

Then did the same steps as previously..
**cd ~
sudo cp data/* /opt/retropie/emulators/amiberry/data/** It seemed to work ok...

Now after a sudo reboot. Amiberry still shows up as v2.12? Am I doing something wrong?

I cannot copy Amiberry file manually to /opt/retropie/emulators/amiberry/ because of file permissions, I thought the above script would do it manually?

**Comment by midwan** [comment]
@ransom1122 
In RetroPie installlations, the emulator binary should be placed in `/opt/retropie/emulators/amiberry/` and named `amiberry` I believe. 

You'll need to `sudo cp` it in there, like you did with the `data` directory. ;-)

**Comment by ransom1122** [comment]
**FIXED** Now on V2.14
After the 1st Step above I did this... 

**sudo cp amiberry /opt/retropie/emulators/amiberry/
sudo cp capsimg.so /opt/retropie/emulators/amiberry/**

Funny that I don't recall doing that when I updated to v2.12

Thank you for your fast reply...

**Comment by ZappaUtopia** [comment]
@ransom1122 
@midwan has updated the master branch to v2.14 so you can 'update from source' in Retropie, you don't have to do it manually (only for the dev version). You will still have to manually copy the 'capsimg' though using the commands from the wiki.

**Comment by ransom1122** [comment]
Great news. Ill keep it in mind for future releases

**Comment by ZappaUtopia** [comment]
Its also recommended to 'update from source' because Retropie updated the .zip extraction script for IPF support. (If the zip file contains more than one .ipf or .adf etc. it will extract them to a temp directory and insert them into the drives).

**Comment by ransom1122** [comment]
Thanks
