### ISSUE TITLE
Amiberry 2.14/DietPi 6.2 does not quiet boot

### ISSUE THREAD

**Issue by mattsoft** [midwan/amiberry#264]
Older versions of Amiberry (e.g., 2.12) with DietPi 6.0 would quiet boot on the RPi3. There would be no output to console when you turned on the Pi.

With 2.14 and "Fast boot" selected, DietPi gives you all the output up until Amiberry launches. Is this deliberate?

Write the Amiberry 2.14 image (http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch_AmiBerry.7z) to SD card and install to a RPi3. After setup is done, reboot and watching the boot process stream to the console.

**Comment by midwan** [comment]
We'll have to take a look with @Fourdee on this...

**Comment by midwan** [comment]
@mattsoft 
Could you please post the contents of these files:
- /boot/config.txt
- /boot/cmdline.txt

**Comment by midwan** [comment]
@mattsoft 
Any update on this? Do you need help to see the contents of the files? Or is this a non-issue and has been resolved?

**Comment by mattsoft** [comment]
I reverted to 2.12. Will re-install 2.14 tonight and post those files.

**Comment by mattsoft** [comment]
Re-installed 2.14 and same problem. Probably needs a quiet in the codlin.txt or something.
[config.txt](https://github.com/midwan/amiberry/files/1814014/config.txt)
[cmdline.txt](https://github.com/midwan/amiberry/files/1814015/cmdline.txt)

**Comment by midwan** [comment]
@mattsoft 
Thanks for the info.
The contents of the files look correct, normally what hides the console output is the `console=tty3` option in `cmdline.txt`, which is in place...

I'll do a clean test from my side to double check this, as it used to work in earlier versions at least. Perhaps something changed.

**Comment by jakobwesthoff** [comment]
Are there any updates on this. The problem does still seem to exist with current versions of diet-pi. The redirection to `console=tty3` does not seem to suppress/redirect the initial messages from the diet-pi boot process.

**Comment by midwan** [comment]
@jakobwesthoff 
Thanks for the reminder.
I'll set up an installation this afternoon to see what's going on, maybe we'll have to involve @Fourdee in this...

**Comment by midwan** [comment]
@jakobwesthoff 
Sorry, I didn't have a chance to test this yet. I'll update this issue once I get to it.

**Comment by Fourdee** [comment]
@midwan 

Apologies, leave this with me, only just seen the ticket.

> With 2.14 and "Fast boot" selected, DietPi gives you all the output up until Amiberry launches. Is this deliberate?

Should be silent. Did you use the AmiBerry specific DietPi image, or install manually through DietPi?
