### ISSUE TITLE
Possible to add an Paula/Master Volumeslider?

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#266]
Hi.
I'm using Amiberry sometimes with HDMI Sound output and sometimes i use the Headphone jack for Audio Output.
The Problem is that the Volume can not changed from Amiberry itself because there is no Volumeslider.
I think the best possibility is to regulate the Paula Volume because there are so many different devices like Tinker, Pi and many more.
The original WinUAE has these Slider for Master Volume, Paula Volume, AHI etc.
It would be a nice feature when this where added. :-)

**Comment by CypherXG** [comment]
Any solutions...?

**Comment by midwan** [comment]
@CypherXG 
Not yet, working on some other items currently and there isn't enough free time...

**Comment by CypherXG** [comment]
I'm working on it. It's not hard to implementbecause all the Information like Paula Volume is already in the Audio.cpp.
My problem is right now, when the Slider is at 1% the Volume ist 100% and vice versa.

**Comment by midwan** [comment]
Pull requests are welcome in that case :)

**Comment by midwan** [comment]
This is coming with the next update, as it seems that Tomb has already added something similar in his repo. :)
