### ISSUE TITLE
[Help] Getting a new uae template

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#267]
### Expected behavior
To ensure uae gets inline with latest Amiberry release. Please point to me to any docs or even better if you could share one such template in the Wiki.

### Actual behavior
There are many parameters used in uae that might not be necessary any longer (like the many "pandora.xxxx" sort of params). I'd like to strip every useless/deprecated params out of my former uaes that I made for Amiberry < 2.1x.

### Steps to reproduce the behavior
I've attached one of those "previous uae" I've created for former Amiberry release.
ie. 
[uae for Zool 2 AGA](https://github.com/midwan/amiberry/files/1282838/Zool.2.txt)
[uae for Unreal](https://github.com/midwan/amiberry/files/1356029/Unreal.txt)

Many thanks!

**Comment by HoraceAndTheSpider** [comment]
Hi 

You could just update the uae Config Maker? It has had its template update.

Either that or use the QuickStart option and save a new file :)

**Comment by nemo93** [comment]
Thanks @HoraceAndTheSpider I'm afraid I can't find Config Maker. Bear with me! Do you have a link to that tool please? Also how should I go with the Quickstart option, I'm using Retropie (up to date) and launch uae from ES. I guess i have to go to Amiberry's GUI and look for this quickstart. Am I right?

**Comment by HoraceAndTheSpider** [comment]
Yes the QuickStart is a panel in the gui

The UAE Config Maker is here on GitHub https://github.com/HoraceAndTheSpider/UAEConfigMaker

, but would suggest you remove any older installs of it first with:

`sudo rm -R \home\pi\.uaeconfigmaker`


I see from your configs you are using WHDLoad games anyway, so you might want to keep in mind I am working on a WHDLoad solution that means you won’t need the Config maker or templates anyway.

I have a working prototype and would like to get it into the dev branch within a few weeks

**Comment by Xnyle** [comment]
Regarding Quickstart or autoload: how do I make a custom config autoload at start via the SDL2 GUI?
If not possible via GUI, is it possible by editing the conf manually?

**Comment by nemo93** [comment]
thanks @HoraceAndTheSpider I'll test that out. Also interested by your proto hence let me know if I could help with testing.

**Comment by ZappaUtopia** [comment]
> 
keep in mind I am working on a WHDLoad solution that means you won’t need the Config maker or templates anyway.

I have a working prototype and would like to get it into the dev branch within a few weeks

Could you give us a brief description on how this is going to work ? Will we still be able to launch from emulationstation (with screenshots) or is it only from the Amiberry GUI ? I have read on EAB that they are finding more and more games that need to be extracted on Amiga only. For instance, Retroplay states "Ultima5 extracts fine in Windows but in-game graphics are messed up unless properly extracted Amiga side". They've found about 16 more games, interesting discussion from the following post onwards -

http://eab.abime.net/showpost.php?p=1218613&postcount=307

**Comment by HoraceAndTheSpider** [comment]
I have already tested it with Batman so no issues with Amiga unpack games :)

The intention is to work from command line and I am already doing my testing though a self modified RetroPie :)

Will reveal more in time ;)
