### ISSUE TITLE
[Feature-Request] Debian Buster ARM64, not Raspbian as main target for future builds.

### ISSUE THREAD

**Issue by Xnyle** [midwan/amiberry#270]
As already discussed in previous Issues:

I'd like to see Amiberry being targeted at a modern, future-oriented distribution, that uses the full potiential of the RPI3 as well as all the other current and upcoming A53 based boards. (Orange Pi Prime/Win /Rock64/Pine64,...)

Debian is already nearly there for the RPI3 with a usable image and mainline kernel in the official repos (although only unstable branch atm)

https://wiki.debian.org/RaspberryPi3 uses Buster (testing) as base with kernel from unstable. It's a slim, clean image without any Raspbian bloatware in it.

You could also clone https://github.com/Debian/raspi3-image-spec and extend the build scripts (vmdb2, ansible based) for Amiberry.

First Amiberry has to compile on ARM64 though.

Of course this would mean dropping support for older RPi2/1.

Those boards are becoming more and more obsolete though and as written, better build it for the future, not for the past :)

**Comment by midwan** [comment]
@Xnyle 
I think the main target should be the one that is most commonly used for the platform. Until that changes for the RPI platform, we'll stick to Raspbian as that's what most distros use as a basis (and by extension, most users).

Making Amiberry compile for ARM64 is another valid request however. That is something we can look into separately.

**Comment by midwan** [comment]
Opened #322 for the AArch64 support, closing this one.
