### ISSUE TITLE
Jim Power

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#272]
### Expected behavior
To run at normal speed.

### Actual behavior
Runs slow on intro. Music slows down during level 1.

### Steps to reproduce the behavior
Launching whdload version.
Tried overclocking pi
Tried different settings in gui
Tries res settings in raspiconfig

Nothing fixes it.. may be a emulator issue

Using version 2.14

**Comment by midwan** [comment]
This is a dupe of #58
