### ISSUE TITLE
[Request] Auto Vertical Centering

### ISSUE THREAD

**Issue by ghost** [midwan/amiberry#273]
In some games the image is slightly off the top (or bottom) of the screen so you have to manually use the Offset option to correct it, and the huge amount of games that are in NTSC ratio have the massive black bar at the bottom, it would be good if you could centre it to give equal amount of black space above and below the image (like WinUAE does). :)

Also, what's the 'Fullscreen' option for ?

**Comment by midwan** [comment]
@ZappaUtopia 
There's no bulletproof way of doing this, I'm afraid, but we can look into similar attempts from other systems to replicate that behavior.

The Fullscreen option only makes sense if you run the emulator under X11, where you could have it in either Windowed or Fullscreen mode. Like WinUAE on Windows ;-)

**Comment by midwan** [comment]
No need to close this, it's still a feature that will be implemented.

**Comment by rhester72** [comment]
Perhaps this belongs as a different (incompatible?) request, but honestly, I'd rather see vertical (and horizontal) scaling done properly (for NTSC, at least).  Today, both PAL and NTSC are scaled for 1:1 pixel ratios - which is more-or-less (accidentally) correct for PAL (640x480, which is 1:1, is very close to 640x512), but is WAY off for NTSC.

Ideally, scaling would go like this:

- Scale vertically to take up entire 1080p/720p/fill-in-the-blank physical screen (taking overscan into account)
- Scale horizontally to achieve 4:3 ratio _irrespective of video mode_

Right now, NTSC is much too "stretched" horizontally, even when scaled properly vertically (in aspect ratio correct mode).

It took years to get the SAR vs. PAR right for WinUAE - if you need specific help/guidance/thoughts, more than happy to do so, but I at least share the OP's annoyance with this.  =)

**Comment by midwan** [comment]
I've implemented WinUAE's approach to "smart" horizontal and vertical centering, so there should be no more need for the Vertical Offset setting (which is removed).
The scaling is done based on the emulated resolution, so if you go for an overscan one (e.g. 720 horizontal) that will be taken into account to keep the correct aspect ratio always.
