### ISSUE TITLE
Keyboard as joystick - glitches in Sensible World of Soccer

### ISSUE THREAD

**Issue by mzuidweg** [midwan/amiberry#276]
I'm running Sensible World of Soccer (95/96 I believe, may 96/97) from ADF's, with a rather standard A500, 1.3, 1MB configuration. I have an issue when controlling it using the keyboard as joystick (default layout).

Background: in SWOS, when the game is at a dead moment (free kick to be taken etc.), you can call the coach's bench to select substitutes by moving the joystick quickly three times in the same direction. 

When at such a moment, I press arrow up or arrow down (also when in combination with arrow left/right), the coach's bench appears. It seems to me that arrow up/down triggers faulty joystick signals. 

Normal gameplay is good, controlling the players in all directions works just fine. 

I could imagine that this behaviour occurs if the joystick up/down signal is sent intermittantly instead of constantly when pressing the key. There might be small glitches interrupting the joystick signal..?

Note:
- moving the joystick three times left or right also calls up the coach's bench. This works just fine. The problem is specific to arrow up/down.
- I haven't noticed problems in other games, but then again, I just installed Amiberry yesterday on my brand new Pi. I only played Bubble Bobble so far.
- I'm running Amiberry 2.14 with the premade DietPi image.
- this happens with my homemade "arduino DB9 to usb hid keyboard" adapter (to connect 9 pin joysticks via usb), but also with a regular keyboard.

**Comment by midwan** [comment]
@mzuidweg 
I think this is by-design from the game itself.
I tested it on WinUAE and it does exactly the same thing, actually. :)

There are no joystick events triggered from the arrow keys, unless of course you're using the "Keyboard as Joystick" mapping in which case they act as a joystick. If you have a real joystick connected, the arrow up/down seem to trigger the coach bench anyway, but that's something the game does, not Amiberry. ;)

**Comment by mzuidweg** [comment]
Ah, I see, I'm indeed using the keyboard as joystick, and then basically SWOS receives both the joystick input and the direct keyboard input, and the latter is triggering the behaviour. 

In the meantime I've reprogrammed my homemade Arduino dual 9-pin joystick to USB adapter to emulate two HID gamecontrollers instead of sending keyboard events, and that seems to work. However,  I cannot find a way to be able to control the mouse in workbench, then play SWOS with two joysticks. Any hints?

**Comment by midwan** [comment]
I believe @HoraceAndTheSpider might be the best person to answer that :)
