### ISSUE TITLE
Sprite blinks bottom left, Dynablaster

### ISSUE THREAD

**Issue by OZ2CPU-thomas** [midwan/amiberry#281]
Amiberry v2.14
Dynaplaster : 5 players battle, bottom left player is BLUE
when located at bottom left corner (where he starts)
halve of the player is gone, and the other halve of him is blinking,
the behaviour changes a bit with change of, Chipset, Blitter 
try the 3 settings to see slight change, but no cure it is still a problem.

**Comment by midwan** [comment]
I can't recreate the problem with the current `dev` branch at least.
The sprite appears normal and moving it around does not cause any problems.

I used the default (Quickstart) A1200 settings, with this version of the game:
`Dyna Blaster (1991)(Hudson Soft)[cr VF][t +11 ZNT]` (ADF)

Maybe try with another version?

**Comment by OZ2CPU-thomas** [comment]
how do you adjust the height of the screen ? dynablaster got some sort of height offset,
if you do nothing you cant not see the scoreboart at top.
the startup screen (not a standard dynablaster release) will let you adjust this, 
then you see the problem.
But if you use: display v. offset -16 the problem is gone for me, 
so that conclude my problem and you can close this case as there is this work arround.

**Comment by midwan** [comment]
@OZ2CPU-thomas 
You can tweak the Vertical Offset in the Display Panel for such scenarios, but I didn't have to do that in my case...

I saw no flickering or cut-off sprite with the default settings, using the Quickstart A1200 as a starting point, then loading the ADF, changing the Input Panel for the Parallel Port joystick mapping and clicking on Start.

In any case, I think this can be closed.
