### ISSUE TITLE
Black screen for many minutes, then start ok

### ISSUE THREAD

**Issue by OZ2CPU-thomas** [midwan/amiberry#282]
Amiberry v2.14
select to boot from a HD0 partition file,
this file contain a boot menu, i tried in A1200 and A4000 modes, same issue
BLACK screen, no responce from F12, takes many minutes then bingo it startup and works
i have no idea what it is performing while all black,
is it related to the other bug ? Harddrives, click Restart, all HD settings erased !
then configurations, load a config with HD settings, then in harddrive page, now Start and it most times go fast

**Comment by midwan** [comment]
The Restart button will reset all config options to the defaults for the selected "Quickstart" option. So losing the HDD settings is by design and expected behavior.

I'm not sure about the black screen thing, that seems related to something running inside the emulation session (i.e. something on your HD0 drive). You could check your startup-sequence there perhaps?

**Comment by OZ2CPU-thomas** [comment]
this HD0 and HD1 folders with all the games have been running perfectly stable with the other emulator, and it actually works with this one, most of the times, just sometimes i get this odd black screen while starting up, i cant exactly figure out what triggers it, since next time i try the same, it works perfectly

**Comment by midwan** [comment]
@OZ2CPU-thomas 
Without knowing what exactly triggers it, there's not much we can do...

Could you provide the startup-sequence from there? Maybe we can find which line causes it.
Alternatively, you can try this:
- Boot with no startup-sequence
- Start each line of the startup-sequence manually, until you see the problem
- Report which command/tool it was that caused it

**Comment by OZ2CPU-thomas** [comment]
i have a bit more, i was in the setup screen, simply hit reset, and bingo, 
the same black screen, so it is not only a start thing
i assume i could copy the startup-squence from the DH0 partition, but to do so, i must be inside amiga CLI or workbench, to get access to this file, right

**Comment by midwan** [comment]
@OZ2CPU-thomas 
If you have it in a hardfile, yes. You could also copy it to a machine that runs WinUAE and test it there (or extract the startup-sequence).

Or you could try the steps I mentioned above.

**Comment by HoraceAndTheSpider** [comment]
Is DH0 mounted as an HDF file or a Directory? 

If it is a single HDF file you could share that

**Comment by OZ2CPU-thomas** [comment]
my DH0 is a single file, bootable, my DH1 is a folder,

**Comment by OZ2CPU-thomas** [comment]
i think i got a bit more about the black screen issue,
when goto quickstart A1200, then harddrives, configure my two partitions, then start,
the chance of black screen is smaller.
But when it happens, i also hear sound, like small bites of the audio, very slowly,
so the system must be overloaded, no picture ever. 
also when it works, i do see a black screen for 2-4 sec, so i always gets scared, why this delay ?
with the chips emulator i used before i had no delays at all, and newer seen any black screens.

**Comment by midwan** [comment]
@OZ2CPU-thomas 
As this is something we cannot recreate anywhere else, I'm afraid there's not much we can do until we get more specifics.

E.g. what exactly is it from your startup-sequence that causes this?

**Comment by OZ2CPU-thomas** [comment]
forget about the startup sequence, it is not the problem..
i go to quickstart, select A1200, goto harddrives and check nothing is selected, 
hit start.. 
black screen with no info about what is going on for 2 mins and 35 sec 
then i see the animated disk screen..

**Comment by midwan** [comment]
@OZ2CPU-thomas 
That's strange, I don't believe anyone has reported such a behavior...
Have you tried with different ROMs?
Is your drive busy (LED constantly on) while this is happening?

Something in your environment is causing this, but we have to find out what.

**Comment by CypherXG** [comment]
How big is your boot Directory?
Can you Zip it and upload to an freehoster?
I use HD too without no problems. I can start from an directory or an HDF. Does no matter.
Works fine...
You  write ...black screen with no info about what is going...
Mhhhh this happens on an real Amiga when the Harddisk is not correct for boot the System.
But it takes only 20-30 seconds and then you see the Kickstart Anim.
When you hold both Mousebuttons can you see the HD's in the early Startup Menu?
If not there is somthing wrong with the directory you select.

**Comment by OZ2CPU-thomas** [comment]
the HD image worked for a year with out any black screen, on the chips emulator :-)
so there is nothing wrong with the file, it must be a configure or combination issue,
i did give the file to Gunnar and Dimitris, so far i did not hear any news from them.
also please read all i explain, i get black screens 2.5mins with no harddisks selected at all,
also when it works, i feel it is remarkebly slower, longer black wait, before anything slow, compared to chips, but i really need this version to work, due to the parallel port support, chips dont have that..
also i tested with a few demoes normally run smooth on the chips emulator, this one stutter on gfx and sound, like far from enough cpu power available

**Comment by midwan** [comment]
@OZ2CPU-thomas 
I'm sorry, but I haven't received any image to test with, yet... 
Could you make it available as a download link here, please?

**Comment by OZ2CPU-thomas** [comment]
link provided privatly, the file is not mine to give away in a puplic place,
it is of course ok to share it among delevopment team, but not puplic please.

**Comment by midwan** [comment]
@OZ2CPU-thomas 
It looks like you need to click on "Rescan ROMs", in the Paths panel, once.
That seems to fix the issue for me.

Also, you'll need to install the latest P96 drivers in the system as the current one doesn't seem to work.
