### ISSUE TITLE
Fire Force CD32

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#285]
### Expected behavior
Game to boot ok

### Actual behavior
Black screen then corrupt graphics. Won't go further

### Steps to reproduce the behavior
Quickstart CD32
Load ForeForce.cue file

Game works fine on WINUAE but not on Amiberry v2.14

Can anyone check this please.

**Comment by midwan** [comment]
Can not recreate the problem, game works fine here:

![snapshot](https://user-images.githubusercontent.com/3877365/37391304-12942562-276b-11e8-9ad1-dbe873324910.png)

Tested using the current "dev" branch version, Quickstart CD32, Amiga CD32 - Fire Force.cue.

**Comment by ransom1122** [comment]
I've tried it starting a fresh start on Amiberry 2.14 and now it works. I think my problem occured when you eject old cd32 images and mount new cd32 images and restart.
Thanks problem solved

**Comment by ZappaUtopia** [comment]
@midwan Yes, what @ransom1122 said, if you eject a CD32 image in the GUI and insert a new one and press Restart, sometimes it doesn't boot, it just displays the CD32 logo. You have to go back to the GUI and press Restart again.

**Comment by ransom1122** [comment]
Yeah I think this issue stemmed from that booting problem.. thanks

**Comment by midwan** [comment]
@ZappaUtopia 
That is something I noticed yesterday also, while testing some CD32 titles.
I'll open a separate issue to look into it.

**Comment by ZappaUtopia** [comment]
Also, have you tried any CD32 games with external audio tracks WAV/MP3 ? I haven't updated Amiberry for a few weeks but noticed that it takes a few seconds for the WAV files to start playing and MP3 take even longer. Not sure if this is supposed to be like this ?

**Comment by midwan** [comment]
@ZappaUtopia 
Please give me some specific examples, I've tried several titles but I haven't noticed something like that yet...

**Comment by ZappaUtopia** [comment]
I'll have to double check later but one I remember is Xenon 2 CDTV.

**Comment by midwan** [comment]
@ZappaUtopia 
I happened to test that the last few days, after fixing the audio lag issues in the dev branch,
It worked perfectly fine here. :)

**Comment by ZappaUtopia** [comment]
OK it may be fixed then as I haven't updated since the last 'master branch' update. Did you use WAV or MP3 ?

**Comment by midwan** [comment]
@ZappaUtopia 
My version consists of a .cue and .img file, not separate files. :)

**Comment by midwan** [comment]
@ZappaUtopia 
The Chaos Engine CD32 seems to have external WAV files however, and that also played normally in my test.

**Comment by midwan** [comment]
@ZappaUtopia 
So does Fire and Ice, also worked normally. In some games you had to enable Fast Copper to avoid a bit of a slowdown, but otherwise I found no issues.

**Comment by ZappaUtopia** [comment]
I'll update and test my MP3 versions in a few hours and let you know. I'll also see if it makes the horrible sound still when sometimes resetting in the GUI (when changing CD32 games with external audio).

**Comment by ransom1122** [comment]
WAV & MP3 joined with a CUE work fine on v2.14 I have test quite a few games. All working fine... 

If anyone has issues with any cd32 games please post results so we can verify where the problem is.

**Comment by ZappaUtopia** [comment]
OK, I updated to the latest dev and the CD32 seperate audio tracks delay is a lot better. When using WAV files it's perfect now but MP3 takes 2-3 seconds to start the track (using 44.1 & 128Kbps). I tested this on Xenon 2 CDTV. If you go to the audio selection page that lets you choose the music for each stage. Starting each track takes 2-3 seconds but if you then go back to a track you have already played it starts instantly !? Is it buffering it to memory ?

@midwan Another bug I found. If you load Xenon 2 CDTV (with WAV audio) and wait until the music starts, it asks you to press a button. Go to the GUI and press Reset. It gives out a really horrible sound and you can't do anything for 10-20 seconds.

**Comment by ransom1122** [comment]
Is CDTV supported or are you using Whdload CDTV? I never thought CDTV was supported yet. There is no CDTV quickstart...

**Comment by ZappaUtopia** [comment]
CD32 can load CDTV games.

**Comment by midwan** [comment]
@ZappaUtopia 
Please report bugs in separate issues, to avoid getting them buried in closed ones.. Thanks!
