### ISSUE TITLE
[Heads up] Raspberry Pi 3B+ just released

### ISSUE THREAD

**Issue by ZappaUtopia** [midwan/amiberry#286]
Just a heads up that the Raspberry Pi 3B+ has just been released.

https://www.raspberrypi.org/blog/raspberry-pi-3-model-bplus-sale-now-35/

It's a 200MHz faster CPU, would this make much difference do you think ? Will we be able to leave 'Fast Copper' OFF and it will cope ?

**Comment by midwan** [comment]
we'll have to see when we get one. :)
I've already placed an order.
