### ISSUE TITLE
CD32 - Eject CD, Insert new and Reset doesn't boot the new CD

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#287]
### Expected behavior
When inserting a new CD and clicking on Reset, the new title should boot

### Actual behavior
If having a previous title loaded, then ejecting it, inserting another CD, then clicking Reset, we are presented with the boot screen instead of booting the new CD.

### Steps to reproduce the behavior
- Insert a CD and boot it
- Enter the GUI
- Eject the current CD
- Insert another CD
- Click Reset

**Comment by ZappaUtopia** [comment]
I just checked this and found that it also happens on WinUAE !

**Comment by midwan** [comment]
@ZappaUtopia 
Thanks, that is very interesting (I didn't test it there), as we share the same code for these functions...

**Comment by midwan** [comment]
Reported to Toni (WinUAE):
https://github.com/tonioni/WinUAE/issues/132

It's best if he fixes it upstream, to avoid re-introducing this on a future merge.

**Comment by midwan** [comment]
This is now fixed upstream, so the changes will be merged in Amiberry...
