### ISSUE TITLE
CD32 External Audio Tracks Bugs

### ISSUE THREAD

**Issue by ghost** [midwan/amiberry#288]
- OK, I updated to the latest dev (2.17 beta) and the CD32 seperate audio tracks delay is a lot better. When using WAV files it's perfect now but MP3 takes 2-3 seconds to start the track (using 44.1 & 128Kbps). I tested this on Xenon 2 CDTV. If you go to the audio selection page that lets you choose the music for each stage. Starting each track takes 2-3 seconds but if you then go back to a track you have already played it starts instantly !? Is it buffering it to memory ?

- @midwan Another bug I found. If you load Xenon 2 CDTV (with WAV audio) and wait until the music starts and it asks you to press a button. Go to the GUI and press Reset. It gives out a really horrible sound and you can't do anything for 10-20 seconds. (This is not specific to Xenon 2, I think it happens with all games with separate audio tracks).

**Comment by ransom1122** [comment]
My xenon2 CCTV with bin files for audio seems to work perfect on v2.14
Music player and ingame. I did not notice any lag in audio.

**Comment by ZappaUtopia** [comment]
I checked the MP3 versions on WinUAE and there is no delay. Does it mean that the RPi is not fast enough to play the compressed MP3 audio ? But like I said above, if you go back to a track that's already played there is no delay in starting it playing.

Point 2 above still applies though.

**Comment by CypherXG** [comment]
I don't use Wav and Mp3 Files.
I create a complete .ccd File and i have no problems.
