### ISSUE TITLE
Can't select previous File in CD Dropdown Menu

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#289]
Hi
I think i found a Bug in the CD Dropdown Menu.
When i try to select a previous File in the CD Dropdown Menu Amiberry doesn't select this previous File.
It closes only the Dropdown Menu.
Only the Mousewheel is working to switch images.

To reproduce this Error select only two ore more CD Images, then try to select it with the Dropdown Menu.
Using an RPI3 with the SDL1 Version.

**Comment by CypherXG** [comment]
Dimitri, you can close this.
I found the Bug. It was my fault. :-)

**Comment by midwan** [comment]
@CypherXG 
Thanks for letting me know :)
