### ISSUE TITLE
Wiki page for config changes since v2.1

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#292]
Hi,

Can you please explain in detail what you mean by this changelog when you update to v2.18.1

_Config files have **new options** and some options have been **renamed for clarity**. Older config files may or **may not work correctly**, **depending on their content**. If possible, we recommend you recreate them if you run into problems._

1. What new options?
2. What type of renaming has been made?
3. Older configs may or may not work? (What type of content in old configs can cause problems?)

**Comment by Voljega** [comment]
It sure would be good to have an up-to-date  list of all existing options with a quick description of what they do in wiki

**Comment by ransom1122** [comment]
My configs from v2.14 and earlier seem to work fine in 2.18.1
But yes looking for some type of description in the meantime.

**Comment by Voljega** [comment]
Would also be nice to have a full list of available config parameters and what they do
