### ISSUE TITLE
Flag in hostpfefs.conf for Line-doubling

### ISSUE THREAD

**Issue by AnalogHero** [midwan/amiberry#293]
### Expected behavior
Have a flag for linedoubling in the config file to make ot permanent. Maybe i have not found it, could be my fault.

**Comment by midwan** [comment]
This already exists : gfx_vresolution

Is the same as in WinUAE.

**Comment by HoraceAndTheSpider** [comment]
Probably needs adding to the host prefs for Whdload auto booting though

**Comment by AnalogHero** [comment]
Sure, its in the .uae config, but as HoraceAndTheSpider said, its not in Whdload prefs.

**Comment by midwan** [comment]
Ah sorry, I misunderstood then...
@HoraceAndTheSpider re-opening this then...

**Comment by HoraceAndTheSpider** [comment]
Fixed in commit 2438bd1
