### ISSUE TITLE
Joypad GUI control: constant pressure on the direction cross

### ISSUE THREAD

**Issue by waal** [midwan/amiberry#294]
HI,

As discussed on FB, here's a suggestion of an enhancement for the GUI.

Concerning the GUI controlled by the pad: would you please add a constant pressure on the direction cross ? I find a bit tiring to always press down in the select list when I map the joypad, for instance.

**Comment by HoraceAndTheSpider** [comment]
An old version had it using shoulder buttons to move up/down ten items at a time- this seems to have been lost in an update somewhere. I’ll see about restoring it.

**Comment by Darknior** [comment]
Yes it can do the tric too. It's almost to move on the drop-down menu ... it's very long without moose :p

**Comment by midwan** [comment]
The LShoulder / RShoulder buttons should work as expected now, for navigating in the GUI (10 items at a time).
There was an issue when the gamepad was detected as a controller (vs a joystick), where some input buttons were not detected as expected.
