### ISSUE TITLE
Keyboard Error

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#295]
Testet with Amiberry SDL1 (Jessie)

When i press W it types an W and Enter
Same with Q , it make an Space behind

**Comment by midwan** [comment]
@CypherXG 
I cannot recreate this with any standard combination I tried (e.g. setting the Keyboard as a controller)

Could you please attach your config file, and any retroarch config as well if you have it?

**Comment by CypherXG** [comment]
Ahhh i found it. It was the Retroarch Config.
Amiberry select "Retroarch Keyboard as Jostick" as default when no Joystick was found.
Would it not better the Joyport would be deactivated as default. Only when i select it, or save it with the config it selected?

**Comment by midwan** [comment]
@CypherXG 
Thanks for confirming!

The default behavior is to use Keyboard as Joystick to allow you to have something there, and that setting alone won't create the problem you described (I tested that yesterday as I mentioned above).
If you also have a retroarch config for that however, then there is a chance that it will cause this behavior as you could have mapped certain keys to trigger specific other keys (as it appears from your config, you had W triggering Enter for example).

You can of course disable that and have nothing on that port, and the config will be saved as such. But the default behavior is good enough for most users I think.
