### ISSUE TITLE
autofire not working on any setting

### ISSUE THREAD

**Issue by caffeinated-pixels** [midwan/amiberry#299]
Hi. The autofire setting is not working for me on any setting (slow, medium, or fast) in any game. I'm using Amiberry 2.18.2 through RetroPie. It's also the same for me through Amibian. I'm using standard PC Xbox controllers.

**Comment by HoraceAndTheSpider** [comment]
I can confirm this.

I am I’ll look at it on th next round of controller updates.

**Comment by ransom1122** [comment]
I've tried everything as well on v2.18.2 and autofire will not enable. I could swear it worked on a previous version by using a default autostart config it was enabled and working.

**Comment by midwan** [comment]
@ransom1122 
Yes, it used to work but we must have broken it with an update. As I don't use it personally I missed this in testing, but we'll get it fixed. :)

**Comment by CypherXG** [comment]
I'm using a PS3 Controller and Autofire works fine

**Comment by CypherXG** [comment]
Mhhh...Now i have a Autofire on my Mouseport if is activated...Bad to move Windows in Workbench :-)

**Comment by midwan** [comment]
@CypherXG 
Yikes, you're right... I messed up the check there, it should be only active for non-Mice devices obviously.
I'll get it fixed, thanks for bringing it up!
