### ISSUE TITLE
Keyboard LEDs assigned to drives don't work in DietPi (work in Raspbian)

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#3]
The keyboard LEDs (Scroll Lock, Num Lock) do not work as expected when they are assigned functions like drive activity, from within the emulator.

This works if the emulator is running under Raspbian, but not in DietPi. However, the following scenario applies:
- Setting the Caps Lock when the key is pressed seems to work when running under `xinit`, but not when running in the console framebuffer. However, the functions assigned to the LEDs do not work when running under `xinit`.
- On the contrary, the functions assigned to them (e.g. HD/DF\* activity) seem to work only when running from the console framebuffer and not under `xinit`.

Note: The code uses calls to `ioctl()` (#include <sys/ioctl.h>) to get and set the keyboard LED status.

**Comment by midwan** [comment]
This ideally should be part of one fix which includes the Caps Lock detection when running from the console, so that we eliminate the need to start it with `xinit` (or from within X11).
The emulator should detect key events the same way, regardless of where it's started from.

**Comment by Fourdee** [comment]
@midwan 
If we can remove the need for ```xinit```, it would also reduce the installation size and package count (xserver packages):+1: 

Note to self: 
current launch script. If no ```xinit```, this can be removed and revert back to service only.
https://github.com/Fourdee/DietPi/blob/a29279f443c5d4562358ba390d2f3004a1ac4071/dietpi/dietpi-software#L5667-L5680

**Comment by midwan** [comment]
Yes, I believe that should be the target eventually. I've already started working in this direction, we'll see how it goes in the following days.

**Comment by midwan** [comment]
There is a known issue with the Caps Lock LED/flag in Raspbian, as shown here:
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=70385&p=985457

A temporary workaround is to run
`echo keycode 58 = Caps_Lock |sudo loadkeys -`

which restores the "normal" behavior for the key (both LED and flag are turned on/off when pressing the key after that).
I also tested it under UAE, and it works correctly when started from the console. The LED does not turn on in DietPi, but the flag does change.

Will test the same in Raspbian also to compare.

**Comment by midwan** [comment]
Confirmed working in Raspbian, including turning the Caps Lock LED on under emulation (when started from the console).

This brings us to the difference between DietPi vs Raspbian:
the command ioctl() does not seem to run the keyboard LED on (as expected) in DietPi, but it works in Raspbian. Perhaps some package is missing?

The below is a simple program I used to test this. The result should be that all keyboard LEDs should start flashing in a loop, until you hit Ctrl-C to cancel. It runs from the console:

```
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <sys/stat.h>
#include <linux/kd.h>
#include <sys/types.h>
#include <sys/ioctl.h>

using namespace std;
#define ERROR -1

int fd; /* File descriptor for console (/dev/tty/) */

void sighandler(int signum);

int main(int argc, char *argv[])
{
	int i;

    /* To be used as the fd in ioctl(). */
	if ((fd = open("/dev/console", O_NOCTTY)) == ERROR) {
		perror("open");
		return ERROR;
	}

	signal(SIGINT, sighandler);
	signal(SIGTERM, sighandler);
	signal(SIGQUIT, sighandler);
	signal(SIGTSTP, sighandler);

	printf("w00w00!\n\n");
	printf("To exit hit Control-C.\n");

	while (1) {
		for (i = 0x01; i <= 0x04; i++) {
		    /* We do this because there is no LED for 0x03. */
			if (i == 0x03) continue; 

			usleep(50000);

			if ((ioctl(fd, KDSETLED, i)) == ERROR) {
				perror("ioctl");
				close(fd);
				return ERROR;
			}
		}
	}
	close(fd);
	return 0;
}

void sighandler(int signum)
{
  /* Turn off all leds. No LED == 0x0. */
	if ((ioctl(fd, KDSETLED, 0x0)) == ERROR) { 
		perror("ioctl");
		close(fd);

	}

	printf("\nw00w00!\n");
	close(fd);

}
```

Binary also attached below.
@Fourdee can you take a look at this please? Do you have any idea what might be needed to get the LEDs to work in DietPi in the same way as Raspbian?

**Comment by midwan** [comment]
@Fourdee this means that we can get rid of xinit during startup, once I test that everything works correctly. I'll change the UAE code a bit, since it's now hardcoded to use 0 (zero) as the console, instead it should fetch /dev/tty1 from the system.

Once I test that everything works, I'll post new binaries in Dropbox.

I still didn't get it to turn on the "POWER" led, but we can fix that later.

**Comment by midwan** [comment]
Hmm, nope. It works in Raspbian, but still doesn't work in DietPi for some reason. :-/

**Comment by Fourdee** [comment]
@midwan 

> Perhaps some package is missing?

Yep, very likely, leave it with me i'll take a look today.

> this means that we can get rid of xinit during startup, once I test that everything works correctly. 

:+1:

**Comment by Fourdee** [comment]
Strange, as far as I can tell, all the includes use libc6-dev: https://packages.debian.org/search?suite=jessie&section=all&arch=any&searchon=contents&keywords=sys%2Ftypes.h

```
root@DietPi:~# apt-cache search libc6
...
libc6 - GNU C Library: Shared libraries
```

Binaries are already installed:
```
root@DietPi:~# apt-get install libc6 libc-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc-bin is already the newest version.
libc6 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I was going to compile and test, but the only keyboard I have with Num/scroll/caps LED is a ps/2, and no converter lol.

**Comment by Fourdee** [comment]
## Notes

Borrowing my misses keyboard, has a num lock LED !!!

#### Checking kernel versions

Raspbian:
```
root@raspberrypi:~# uname -a
Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux
```

DietPi:
```
root@DietPi:~# uname -a
Linux DietPi 4.4.19-v7+ #907 SMP Tue Sep 6 14:03:56 BST 2016 armv7l GNU/Linux
```
Revert back to 4.4.11
```
rpi-update 48cfa89779408ecd69db4eb793b846fb7fe40c4b
reboot
```
:u5408: No effect

===

#### Checking logs:

```
/var/log/kern.log
/var/log/syslog
dmesg
```
:u5408: No errors found

=== 

#### Trying Raspbian ```config.txt``` on DietPi:
:u5408: No effect

===

#### Compare packages:
```
dpkg --get-selections | awk '{print $1}' > dpkg_XX
```
https://www.diffchecker.com/o8zdyBFN
DietPi AmiBerry = Left
Raspbian = Right

**Comment by Fourdee** [comment]
Most likely an undocumented configuration on the Raspbian image.

I'll recreate the DietPi image from latest Raspbian, then test LED.

**Comment by midwan** [comment]
Thanks for your efforts!
I can also resume testing later today.

**Comment by midwan** [comment]
To clarify, if you change the source code line above:
if ((fd = open("/dev/console", O_NOCTTY)) == ERROR) {

to this:
if ((fd = open("/dev/tty", O_NOCTTY)) == ERROR) {

and compile, the tool works correctly in both Raspbian and DietPi from the console. Binary version is attached below.

[setled.zip](https://github.com/midwan/uae4arm-rpi/files/470193/setled.zip)

It's within UAE that things break down. It works in Raspbian but not in DietPi, even when using the same code... :-/

**Comment by Fourdee** [comment]
> It's within UAE that things break down. It works in Raspbian but not in DietPi, even when using the same code... :-/

Bizzare. Are you running the setled binary over SSH? I get:
```
root@raspberrypi:~# ./setled
Got /dev/tty as 3

To exit hit Control-C.
ioctl: Inappropriate ioctl for device
```

**Comment by midwan** [comment]
I run it on the actual device (not over SSH).
I got the same message, /dev/tty as 3.

Did you see the LEDs blinking while it's running? that's what it's supposed to do.

**Comment by Fourdee** [comment]
> Did you see the LEDs blinking while it's running? that's what it's supposed to do.

Only when I press Numlock, then capslock comes on, press capslock, numlock goes off lol. Keyboard lacks scroll lock.

**Comment by midwan** [comment]
Hm, it should flash all the LEDs constantly and repeatedly, until you cancel it with Ctrl-C. At least that's how it behaves here in both my environments.
I just flashed over a fresh AmiBerry image to try #3 again, so I'll test it there as well to see.

**Comment by Fourdee** [comment]
> Hm, it should flash all the LEDs constantly and repeatedly, until you cancel it with Ctrl-C. At least that's how it behaves here in both my environments.

Its a cheap china-town USB wifi keyboard, probably to blame :)

**Comment by midwan** [comment]
Try with this version, it skips over the Scroll Lock key:

[setled-noscr.zip](https://github.com/midwan/uae4arm-rpi/files/470227/setled-noscr.zip)

**Comment by midwan** [comment]
Haven't managed to find a solution yet, but some more details that might help us:
- I tried different approaches (all of them failed), including the ugly one of calling `system("setleds +num")` when I wanted the Num lock LED to turn on. It didn't. The `setleds +num` command works from the console as expected.
- The leds appear to respond as expected up until the GUI screen (or emulation screen if you've disabled the GUI) opens up. In other words, if I put some code to flash the leds (using the same method) before the GUI appears, they work. Once the GUI appears, they stay blank even during emulation when there are calls to turn them on/off.
- I tried different tty approaches: a) opening /dev/tty and using that file descriptor in ioctl(), b) not opening any tty and using 0 (zero). Both of them do not work in DietPi. But they do work in Raspbian (both of them).
- I tried upgrading the firmware to the latest version, in both DietPi and Raspbian. Raspbian still worked, DietPi still did not. :-(

I'll keep looking...

**Comment by midwan** [comment]
@Fourdee I've updated the emulator binaries, to fix a bug that caused it not to load the assigned LED functions from the config file correctly (the first entry was always ignored). I was waiting to fix the LED issue here before I push this, but since I see it will take some time, maybe it's better to have it out.

**Comment by midwan** [comment]
I may have discovered something.

Out of curiosity, I flashed a fresh Raspbian Lite to a new card and tried from scratch. I followed these steps:
- installed Raspbian Jessie Lite
- upgraded system
- installed sdl (libsdl1.2debian libsdl-image1.2 libsdl-gfx1.2-5 libsdl-ttf2.0-0)
- installed libmpg (libmpg123-0)
- installed libguichan (libguichan-sdl-0.8.1-1)

then tried UAE. The LEDs did not work - same as in DietPi.

That means that there is a difference between my developer environment/full Raspbian image and this one. At least we know it's not as isolated to other distros as we thought.

**Comment by midwan** [comment]
I tried a fresh full Raspbian image yesterday also, and in a real WTF moment I discovered that it didn't work there as well. I did a quick check for differences in the installed packages, and even installed some of the dev packages that I had as extra on my "dev Raspbian" (where the LEDs work), but it didn't make a difference.

I'm beginning to suspect that it's not a package but rather some configuration, but I'll need more time/tests to narrow this down. I don't remember doing much customization in the Raspbian installation that I use as a development environment.

Next steps:
- Re-test the current binary in my "Raspbian dev" environment, to ensure that it still works (and that I haven't lost my sanity).
- Assuming the above is true, start comparing the two environments for differences, testing after each change. Yeap, I'm taking the brute force approach on this one... :)

**Comment by midwan** [comment]
Confirmed that it still works with the latest binary in my dev-Raspbian image, but not in a stock Raspbian.

Will now try to incrementally bring this image up to the same level as my Dev, to find out what the difference that makes it work is.

**Comment by midwan** [comment]
Update: It seems that the thing that doesn't work in the default Raspbian, is the Scroll Lock LED. The Num Lock one does work, when assigned a function through UAE.

I tested this in both Raspbian Lite and Raspbian, with the same results.
I did try applying the udev fix we used for the Scroll Lock key, but for some reason it didn't seem to work. The Scroll Lock LED remained off.

With this new information, I believe we can move the investigation to the next level:
- Compare a Raspbian Lite installation to the DietPi/Amiberry one for differences that might be causing this.

**Comment by midwan** [comment]
Trying to make some sense before we lose it completely... :)

I followed these steps, and these steps only:
- Fresh installation of Raspbian Lite: Scroll Lock LED does not turn on, not even manually (using the `setleds +scroll`) or with my "`setled`" test application. The Caps and Num lock LEDs work.
- Applying the 50-leds.rules file, then `udevadm control --reload-rules`, then reboot: The scroll Lock led works as normal. My "setled" test app now flashes it, as well as the rest of them.

- Installed UAE dependencies.
Testing current binary of UAE from console, with my existing config (same one I've been testing all platforms). It's configured to use NUM lock for DF* activity, Scroll Lock for HD activity:
- LEDs flash as expected on the assigned activity.

So we know that a stock Raspbian (Lite) has the LEDs working, with the exception of the Scroll Lock one which needs the extra fix (which we have in DietPi already).

This gives us a relatively minimal system to compare against a normal DietPi installation for differences. 
I'll try to find out any differences in configuration, since we saw that package-wise we are (almost?) identical.

**Comment by Fourdee** [comment]
@midwan 

>  with the exception of the Scroll Lock one which needs the extra fix (which we have in DietPi already).

Ah yes, forgot about this one. :+1:  Correct, applied by default to all DietPi RPi systems as per your suggestion.

> package-wise we are (almost?) identical.

Nearly, on a base system, DietPi has less installed packages. Not sure of the exact figure currently, but a while back we had 140~ less installed packages: https://docs.google.com/spreadsheets/d/1mDHGZC-H6tU6_O8kuLTG8d4A8Nt7lV1Q7MXTR_6qw30/edit#gid=0

#### Heres the package difference when AmiBerry is installed on DietPi:

https://www.diffchecker.com/o8zdyBFN
- DietPi AmiBerry = Left
- Raspbian = Right

===

If we can isolate a single test I can run to get a definite result, I'll be able to re-do all my tests and hopefully provide some assistance.
What does this binary do exactly, flash Num and caps locks?: https://github.com/midwan/uae4arm-rpi/files/470227/setled-noscr.zip

Ideally, if we can have a single binary that turns of Num lock, then exits? Would this test cover the current issue?
Should make testing and debugging this easier. I did try and compile this myself, but, couldn't get a stable result. I will take another look hopefully tomorrow.

**Comment by midwan** [comment]
@Fourdee the binary will go in an infinite loop, flashing the LEDs continuously until you hit Ctrl-C to exit.

I'm working on exactly what you mentioned: a method to reliably test the results on a system as untouched as possible. I've just flashed a stock DietPi image, verified that the Scroll Lock LED is working out of the box (the fix is there, I checked) and am now copying over the emulation environment I use for testing.

After this step, which I expect to fail (in the sense that the LEDs won't work inside UAE), the plan is to start comparing the two default distros: Raspbian Lite vs DietPi stock.

Eventually I should run into something that changes the behavior in the emulator. :)

**Comment by midwan** [comment]
- Installed DietPi stock (v130)
- Tested Scroll LED (worked)
- Tested "setled", all LEDs flashed normally
- Copied UAE environment.
- Installed UAE dependencies (libsdl1.2debian libsdl-image1.2 libsdl-gfx1.2-5 libsdl-ttf2.0-0 libmpg123-0 libguichan-sdl-0.8.1-1 libxml2 pulseaudio)
- Enabled sound card and changed Memory split to 128MB using dietpi-config
- Rebooted
- Tested UAE: LEDs do not work

**Comment by midwan** [comment]
I installed a bunch of extra packages that were in Raspbian Lite and not in DietPi, but no change in the behavior. The issue seems to occur only when a screen with DispmanX + SDL is opened, so I created a small tool to replicate the problem.

@Fourdee could you please help with this? 

The tool runs from the command line (i.e. no xinit required) and it will open a blank (black) full screen using DispmanX and SDL. It will start a loop of flashing the keyboard LEDs, much like the "setled" previous program did. It will continue doing so, until it you press "ESC" or "q" on the keyboard, at which point it will quit to the desktop again.

Essentially I'm recreating the same method that UAE opens the screen, and trying to flash the LEDs after that.

This program works normally in Raspbian, but not in DietPi. I thought it might help you find out what is causing this, if you have the possibility to prepare a DietPi installation step by step, based on a Raspbian / Raspbian Lite one? Or if you have a better method, do that of course!

In case you need the "no scroll lock" version of this, I'm attaching that as well.
[testleds.zip](https://github.com/midwan/uae4arm-rpi/files/475554/testleds.zip)
[testleds-noscroll.zip](https://github.com/midwan/uae4arm-rpi/files/475555/testleds-noscroll.zip)

Dependencies: SDL1.2debian, same as UAE.

Let me know if this helps, or if we should use something else?

**Comment by Fourdee** [comment]
@midwan 

> The tool runs from the command line (i.e. no xinit required) and it will open a blank (black) full screen using DispmanX and SDL. It will start a loop of flashing the keyboard LEDs, much like the "setled" previous program did. It will continue doing so, until you press "ESC" or "q" on the keyboard, at which point it will quit to the desktop again.

Excellent :+1: I'll run some tests with those binaries today and see if we can find the cause.

**Comment by Fourdee** [comment]
@midwan 

#### Using Rasbian Lite:
- pre-reqs: ```apt-get install xcompmgr xterm xinit xauth xserver-xorg dbus-x11 xfonts-base x11-xserver-utils x11-common x11-utils alsa-base alsa-oss joystick libsdl-image1.2 libsdl-ttf2.0-0 libsdl-gfx1.2-5 libguichan-0.8.1-1 libguichan-allegro-0.8.1-1 libguichan-sdl-0.8.1-1 libguichan-opengl-0.8.1-1 libjpgalleg4.4 libxml2 libmpg123-0```
- Main screen ```./testleds-noscroll```
 - Black screen appears with mouse cursor in top left corner
 - No LED's are flashing.
 - Tested Num lock at prompt, working fine.
- Main screen ```./testleds```
 - Same results as above

Did you test these on Raspbian (not lite)?

**Comment by midwan** [comment]
@Fourdee sorry for the late reply, I've been a little busy. :)

It works for me with both "testleds" and "testleds-noscroll", in both Raspbian and Raspbian Lite - but not in DietPi.
I have tried it with two different keyboards, one Microsoft Comfort Curve 2000, one HP Desktop. Both worked normally, flashing their LEDs when told to do so... :)

Strange that it didn't work for you... One thing to notice though, I did not install all those pre-reqs you listed above, as the X-environment is not needed for this test. Though the full Raspbian already has X pre-installed of course.

Could you try with a fresh Raspbian Lite, installing only the absolute minimum extras (it only needs libsdl actually) to see if any of those packages is causing this? That might actually help us find out what is going on.

**Comment by Fourdee** [comment]
@midwan 

> Could you try with a fresh Raspbian Lite, installing only the absolute minimum extras (it only needs libsdl actually) to see if any of those packages is causing this? 

#### Raspbian Lite:
- ```apt-get update```
- ```apt-get install libsdl1.2debian libsdl-image1.2 libsdl-ttf2.0-0 libsdl-gfx1.2-5```
- ```./testleds-noscroll``` and ```./testleds```
 - No mouse cursor this time :)
 - No change in Numlock LED on keyboard.

I believe my (misses) keyboard isn't giving expected results: https://www.amazon.co.uk/gp/product/B00JAE915C/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

Unfortunately, dont have another keyboard to try.

> Note: you mentioned a mouse cursor visible? That's not possible from the console, unless you run this test in a Window manager environment?

Could of been on the full Raspbian, cant remember.

#### We could try debugging on your Raspbian Lite installation?
Simply by going through the process of stripping the packages and setting up image for DietPi.

- Run these commands: https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L75-L108
- reinstall libsdl ```apt-get install libsdl1.2debian libsdl-image1.2 libsdl-ttf2.0-0 libsdl-gfx1.2-5```
- try ```./testleds-noscroll```
If it still works at this stage, let me know, will look for next step.

**Comment by midwan** [comment]
@Fourdee sure, we can try it this way. I'll let you know as soon as I test it.

**Comment by Fourdee** [comment]
@midwan 

I've created a new DietPi image based on the current Raspbian Lite. Please can you check if your LED binary works on this image?
http://dietpi.com/downloads/testing/DietPi_RPi-armv6-(Jessie).7z

If it doesn't, please remove the scrolllock fix, reboot then try 1 last time:
```
rm /etc/udev/rules.d/50-leds.rules
```

**Comment by midwan** [comment]
@Fourdee 
I run a fresh test using the image you provided above:
- Flashed the image and booted.
- Installed OpenSSH server
- Installed libsdl1.2debian, libsdl-image1.2, libsdl-ttf2.0-0
- Enabled the default sound card
- Run the "testleds" and "testleds-noscroll" binaries to test

Results: Black image, mouse pointer showing, LEDs **NOT working**.

- Tested the older "setled" binary from the console
Results: **Worked**, LEDs flash normally.

This means that there's something going on when opening a DispmanX display and using SDL surfaces on it (that's what the testleds is doing, that's what UAE is also doing).

To ensure there is a difference from Raspbian Lite, I followed these steps right after:

- Flashed a fresh Raspbian Lite
- Run an upgrade for all packages (apt-get update && apt-get upgrade) to ensure they are in sync with those of the DietPi installation
- Installed the same packages as above (libsdl1.2debian, libsdl-image1.2, libsdl-ttf2.0-0)
- OpenSSH is already installed by default, so I didn't have to install it
- The sound card is enabled by default, so I didn't change it
- Tested "testleds"

Results: **Worked** normally (except Scroll Lock LED because I didn't install the fix for that)

- Run a firmware update (rpi-update) just in case
- Rebooted
- Tested "testleds"

Results: **Worked**

**Comment by midwan** [comment]
I tried starting with Raspbian Lite and following the steps you provided above also:
- Run the commands indicated
- Rebooted
- Tried to install the SDL packages, but apt-get could no longer resolve the jessie mirrors:

Err http://mirrordirector.raspbian.org jessie Release.gpg
 Could not resolve 'mirrordirector.raspbian.org'
Err http://archive.raspberry.org jessie Release.gpg
 Could not resolve 'archive.raspberry.org'

So I couldn't test it further...

**Comment by midwan** [comment]
Interestingly, if I try to run a new binary using SDL2 that I made, I get an error right away:
`XDG_RUNTIME_DIR not set in the environment`

This binary also uses DispmanX and SDL2 on top, and works fine on a normal Raspbian (Lite) distro,

**Comment by midwan** [comment]
@Fourdee 
I managed to test it also after running the steps in Raspbian Lite, by not rebooting in between.
I installed the SDL packages right after they were removed, in order to keep testing between each step.

Notes:
- The step `echo -e "CONF_SWAPSIZE=0" > /etc/dphys-swapfile` failed with "Permission denied". I did run it as sudo.
- when installing the `console-data` package, there is a prompt to Configure the keymap. I left that at the default option of "Don't touch keymap".
In all the steps in-between, as well as after all of them, the `testleds `application kept working normally.

- I rebooted, and run `testleds `again. It work normally.

**Comment by Fourdee** [comment]
@midwan 

Excellent testing and details 👍 

Going to focus on getting v131 released today, however, I've ordered a USB keyboard with LEDs on it: https://www.amazon.co.uk/Microsoft-Wired-Keyboard-200-Layout/dp/B0041SKBGK/ref=sr_1_1?s=computers&rps=1&ie=UTF8&qid=1474380457&sr=1-1&keywords=usb+keyboard
Will be here tomorrow.

Once I've got it, i'll go through your results and see if I can replicate. Hopefully, this keyboard will give me a viable way to testing the LED's are working, then the debugging can begin :)

**Comment by midwan** [comment]
Great, let's hope we'll find out what's going on. :)
So far, I've got the impression that DispmanX does not quite work in DietPi, and it opens an X display instead under SDL1.2. That does not happen with SDL2, hence the complete failure to start up.

That theory explains the mouse pointer shown, and the LEDs not working - since if you go in an X environment the ioctl() calls to the keyboard no longer change the LED status.

I'm not sure why it doesn't work though. Are you removing anything from `/opt/vc` where the files normally reside in? Maybe DispManX cannot initialize because it's missing something for example...

Either that, or it's a configuration issue in the system somewhere.

**Comment by midwan** [comment]
One more thing to test:
We can restore the traditional Caps Lock functionality so that the LED turns on when pressed from the console, using the command documented here:
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=70385&p=985457

`echo keycode 58 = Caps_Lock |sudo loadkeys -`

Of course, this is temporary (it will go away on the next reboot), so if we implement it it should be part of the startup. Unless you know a way to make it more "permanent" that is.

If using the above allows the Caps Lock to work normally within UAE (i.e. press it and the LED turns on, letters are capitals), from a console startup, then we can get rid of `xinit`.

**Comment by midwan** [comment]
I tested it in a fresh installation of DietPi v131, unfortunately it's still the same regarding the LEDs.

I did notice a different behavior compared to my earlier tests, regarding the SDL2 stuff. My test program worked this time, after following these steps:
- Flashed v131 and booted.
- Changed settings to 1080p display, 128MB GPU memory
- Updated firmware
- Reboot
- Installed required packages for SDL2
- Test!

Although the display worked, and testing the "testleds" program does not show a mouse pointer anymore, the LEDs unfortunately remained turned off during the test.

At least this proves that whatever is causing the LED problem is probably unrelated to the earlier display issues I had noticed.

**Comment by Fourdee** [comment]
@midwan 

Using: https://www.amazon.co.uk/gp/product/B00JAE915C/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

Fresh Raspbian lite installation:
- ```apt-get update```
- ```apt-get ugprade```
- ```apt-get install libsdl1.2debian libsdl-image1.2 libsdl-ttf2.0-0 libsdl-gfx1.2-5```
- ```reboot```
- ```./testleds-noscroll``` and ```./testleds```
 - No mouse cursor
 - No change in any LED's on keyboard.
- kill ```testled``` , manually test keys:
 - Numlock = 1
 - Scrolllock = 0 
 - Capslock = 0
- ```reboot```
- ```echo keycode 58 = Caps_Lock |sudo loadkeys -```
 - Capslock = 1
 -  ```./testleds-noscroll``` = no effect

I still cant find a way to make this binary work on 2 keyboards, gah lol. Any chance you can upload the binary test again?

> so I believe we can get rid of xinitfrom the startup alltogether. We still have to fix the LED problem, but there's no need to keep the whole X-stuff around for UAE.

Removal of Xserver package deps would be awesome 👍 Looking forward to seeing this in SDL2. Just wish I could get these LED tests to actually work lol.

**Comment by Fourdee** [comment]
@midwan 

Ok, so LED's work as standard users, but not under ```sudo``` or with ```root``` user. Weird lol

**Comment by midwan** [comment]
Interesting, that explains the behavior at least. I wonder why...

**Comment by Fourdee** [comment]
@midwan 

Not sure. 
From a permissions standpoint, ```root``` has access to everything and running ```sudo``` grants the same permissions. So in theory, it should work under ```root``` and ```sudo```.

I suppose we could test if this is a SDL specific issue, by creating another binary that tests the LEDS without SDL library (bare bones main.cpp with LED flashing). Any chance you can make one of those binaries and i'll continue testing?

**Comment by midwan** [comment]
@Fourdee 
Sure, that was the first binary I had made actually. I don't think it's SDL related, as the call to change the LED status on/off is a system call (ioctl()) and not part of SDL.

The "setled" binary will start from main, go in a loop and flash the LEDs until you cancel it with Ctrl-C.
The "testleds" binary will open up an SDL screen first, but otherwise do the same loop with the same calls to flash the LEDs.

Both of these worked in Raspbian Lite (and full), but of course I only tested them under the "pi" default account.

**Comment by Fourdee** [comment]
@midwan 

Still puzzles me this one. Doesn't make sense why LEDs fail with root, if anything, should be the other way round.

I suppose, as a possible fix, we could create a user specifically for AmiBerry. This would resolve the LED issues.
Permissions shouldn't be an issue, we can apply ownership to ```/mnt/dietpi_userdata/uae4arm-rpi``` directory aswell during patch and install. 

But either way, I'll try the new user fix and run some tests.

**Comment by Fourdee** [comment]
@midwan 
Misc menu, keyboard LED assignments for DF0: work fine on Raspbian?

**Comment by midwan** [comment]
Not able to test right now, but the DF* setting definitely works. It will
turn the led on fire any floppy drive access (e.g. DF0, DF1, DF2, etc).

Only the power led setting does not quite work yet.

**Comment by Fourdee** [comment]
@midwan 

> Not able to test right now, but the DF* setting definitely works. It will
turn the led on fire any floppy drive access (e.g. DF0, DF1, DF2, etc).

Thanks. Will give me something to test against 👍 


Notes:
```
		#-------------------------------------------------------------------------------
		#AmiBerry LED test, run as standard user:

		# useradd amiberry
		# usermod -a -G input amiberry
		# usermod -a -G video amiberry
		# usermod -a -G audio amiberry
		# usermod -a -G root amiberry

		# sed -i '/allowed_users=/c\allowed_users=anybody' /etc/X11/Xwrapper.config

		# cd /etc/uae4arm-rpi && sudo -u amiberry xinit /etc/uae4arm-rpi/uae4arm-rpi -f /etc/uae4arm-rpi/conf/autostart.uae  &> /dev/tty1
		# cd /etc/uae4arm-rpi && xinit /etc/uae4arm-rpi/uae4arm-rpi -f /etc/uae4arm-rpi/conf/autostart.uae  &> /dev/tty1

		# chown -R amiberry:amiberry /mnt/dietpi_userdata/uae4arm-rpi
```

**Comment by Fourdee** [comment]
@midwan 

Ok, Findings:
- 🈯 ```setleds +num``` works as root and non-root. The sourcecode for this also uses ioctl (https://fossies.org/dox/kbd-2.0.3/setleds_8c_source.html)
- 🈹 Running ````testleds``` only works when logged in as non-root user (eg: amiberry).

Maybe this is a SDL issue? 
As far as I can tell, ```setleds +num``` does the same thing, yet works every time, regardless of user who launched it.

**Comment by midwan** [comment]
@Fourdee 
thanks for the detailed testing feedback! :)

Ok, to clarify if this is in any way related to either a) DispManX or b) SDL1.2, I've prepared the following tiny tool that will test the LEDs from the console. No DispmanX and SDL is initialized or used, just pure ioctl().

It works on Raspbian with both a normal user (pi) and when run with sudo. I'm also attaching the source, in case you want to poke around.

[setleds-console-src.zip](https://github.com/midwan/uae4arm-rpi/files/498791/setleds-console-src.zip)
[setleds-console.zip](https://github.com/midwan/uae4arm-rpi/files/498786/setleds-console.zip)

**Comment by midwan** [comment]
Update: I just tested a binary using SDL2, it works normally in DietPi.

I think we can finally close this then. It seems that it's related to DispmanX when used as a back-end for SDL1 screens. SDL2 does not need/use it, and it does not suffer from this problem.

Therefore, we can safely say that when the SDL2 port is complete, this issue should be resolved "for free" with it. :)

**Comment by midwan** [comment]
To test the binary, you can use the following package:
[guisan.zip](https://github.com/midwan/uae4arm-rpi/files/498846/guisan.zip)

It has one requirement: SDL2 library

However, it may not work correctly with the default libsdl2 package delivered through apt-get, as I believe that requires X11 in order to open a screen. Instead, you can use the binary package from libsdl.org (attached below), to avoid compiling your own.

It's compressed with ZIP on top, to allow it to be attached here. It contains the whole dir structure with the files, though you only need the ones contained in "lib" for the binary. Careful to keep the symlinks contained there intact. ;)

[sdl-raspberrypi-1403.tar.xz.zip](https://github.com/midwan/uae4arm-rpi/files/498852/sdl-raspberrypi-1403.tar.xz.zip)

**Comment by Fourdee** [comment]
@midwan 

> Update: I just tested a binary using SDL2, it works normally in DietPi.

🏆 Awesome, great stuff👍 

> sdl-raspberrypi-1403.tar.xz.zip

Excellent, i'll give this a spin 👍

**Comment by midwan** [comment]
I've managed to fix this (probably, at least in my tests) for the SDL1.2 branch also.
The requirements are:
- the emulator needs to be started as a normal user, i.e. not root (not sure why)
- the emulator needs to have been started from the console (i.e. use fbcon)
- the scroll lock fix needs to be applied in the system, otherwise the Scroll Lock LED will not light up (but the rest still work)

**Comment by midwan** [comment]
Closing issue as it has been resolved in both SDL1.x and SDL2 branches, as long as the requirements are ment:
- Launch emulator as a normal (non-root) user
- Launch the emulator from the console (not X11)
- The Scroll Lock fix needs to be applied to the system otherwise the Scroll Lock LED will not work
