### ISSUE TITLE
custom_controls in whdload xml not working

### ISSUE THREAD

**Issue by andreavitali** [midwan/amiberry#301]
Hi, i tried install Amiberry with the latest Retropie setup script and everything works great, games are loaded,  the hardware settings in the <hardware> tag in whdload_db.xml are used, but the controls defined in <custom_controls> tag are not loaded (although they work using .uae files).
This is a snippet from one of my game configuration in whdload_db.xml

```
<custom_controls>
joyport1_amiberry_custom_none_north=P
joyport1_amiberry_custom_none_east=Space
joyport1_amiberry_custom_none_west=M
joyport1_amiberry_custom_none_start=Esc
</custom_controls>
```
Is this correct? Did someone else tried this feature?

**Comment by HoraceAndTheSpider** [comment]
Yes the feature was tested working prior to release. It does require the joyport that is custom mapped to be already set as “used” with an existing input device though and will not work if you are needing to manually change the device. 

However the XML File in not intended for user editing but will be updated when the online database is complete.

You should consider using the traditional .uae file saving method for any customisations , as the WHDLoad booter will use this as priority over the xml if present.

**Comment by midwan** [comment]
Closing this, unless we discover there's an issue with it still...

**Comment by andreavitali** [comment]
I finally tested the version with the fix, and it's working! Thank you again for the great work.
