### ISSUE TITLE
Updating from v2.18.1 to 2.19

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#303]
Hi,

**I am updating from **amiberry-rpi3-sdl1-dispmanx-Jessie-v2.18.1****

I have downloaded **amiberry-rpi-Stretch-v2.19_2.zip** & **amiberry-rpi3-sdl1** I assume I use amiberry-rpi-Stretch-v2.19_2.zip and rename amiberry-rpi3-sdl1 to amiberry?

And also copy all the data over to my pi, is this the manual way to update?

Can we update to 2.19 within RetroPie yet?

**Comment by midwan** [comment]
@ransom1122 
The Jessie binaries will come online today! :)

You should be able to update from source in RetroPie, in the meantime

**Comment by ransom1122** [comment]
Ah that explains why none of my game booted after a manual update with amiberry-rpi3-sdl1.

I've never updated from retropie.. what are the steps to make this happen?

**Comment by ransom1122** [comment]
Ok great.  I updated to 4.4 then did a manual update of amiberry which failed to boot any games. I'll retry it tomorrow.  Thx

**Comment by midwan** [comment]
I'll test RetroPie v4.4 tonight as well, haven't had a chance to try it yet.

**Comment by midwan** [comment]
@ransom1122 
The Jessie binaries are online as well now

**Comment by ransom1122** [comment]
![20180416_201942_resized](https://user-images.githubusercontent.com/28079950/38804114-9dc06a48-41b4-11e8-8222-6fda9174b214.jpg)

Manual updated via FTP Completed and working. Now its time to update RetroPie to 4.4.

@Midwan Did you get your REtroPie to 4.4 with Amiberry 2.19 yet?

**Comment by HoraceAndTheSpider** [comment]
I am currently testing Amiberry's dev branch with RetroPie 4.4 anyway... just ironing out a few discrepencies

**Comment by ransom1122** [comment]
Does this mean it's not safe to go to RP4.4 yet with Amiberry v2.19?

**Comment by HoraceAndTheSpider** [comment]
it wont cause a crash or anything, so it's "safe" if you are compiling from source, but i suspect it will be changed tonight after some tests/changes/fixes , so you might want to wait till then.

**Comment by ransom1122** [comment]
OK I've made a backup already began the RP4.4 update. I'll see how I go and what comes new from you guys in the meantime. Thx

**Comment by HoraceAndTheSpider** [comment]
Pleased to report the fixes are working on both Jessie and Stretch versions of RetroPie.

**Comment by ransom1122** [comment]
I can confirm V2.19 works fine on RPI 4.4. 
1st Step Updated RetroPie to 4.4
2nd Step Manual FTP update of Amiberry to v.2.19

I Quickly Test Quick 'N Silva HDF Autofire works perfectly without having to select Keyboard then Joystick.

A lot of other games seem to work like normal on 2.19

So far all I can say (again) is GREAT JOB!! :) 👍

**Comment by QUIZASERAQ** [comment]
Am trying to update from 2.18.x to 2.19 on Pi 3b+ via Retropie (scripts are updated to 4.4)
- Binary update keeps 2.18.x
- Source update starts, runs, halts after 10 mins and does not move for hours. Then quits without updating..
- tried several images.. always crashes at same position .. any ideas? Thanks

![2018-04-19 09 37 19](https://user-images.githubusercontent.com/3315077/38996162-ecd24236-43ea-11e8-9f74-af12059d1bd3.jpg)

**Comment by QUIZASERAQ** [comment]
Hmm.. will try again l8r.. 

btw.. do you still plan to release that "Ultimate Amiga for Raspberry Pie 3 v2.0" image..  with all the updates preinstalled and latest AMIberry?  That would make my day.. ;-) 

Cheers from Germany

**Comment by midwan** [comment]
@QUIZASERAQ 
The update from the binary is probably something that RetroPie needs to look into, as they use scripts to fetch and decompress the archives. I'm guessing those need an update.
Updating from source however should (and does in all my tests) work.

The RetroPie scripts only use 1 CPU core while compiling, so it will take some time to finish. The parts about compiling the cpu emulation files (e.g. `compemu_XX`) will take the longest. Could it be that you think it's stuck, because it's slow? How long have you left it going?

@ransom1122 Stretch is the distro version "nickname" that Raspbian gave on release. "Jessie" was the previous version for example, "Whizzy" the one before that, etc.
