### ISSUE TITLE
Running Games through WHDload autoboot - goes black 

### ISSUE THREAD

**Issue by jimi007** [midwan/amiberry#305]
Hi

I am running retropie 4.4 stretch with Amiberry 2.19 (Great emulator by the way).
I have no problems running games through the old UAE configs.
I am now trying to run the games through .LHA files and autobooting.

I can see the game on the retropie menu and start it ok. It loads the amiberry screen then disappears and goes black.
I have the correct roms linked in the Kickstarts folder.
There is an autoboot string created and all looks correct.
It finds the slave file.
Is there anything I could be missing. Do I need to rename the roms a certain name eg kick31.rom to something else?

I hope I'm in the right area. Any help appreciated,

Regards

Jimi

**Comment by midwan** [comment]
@jimi007 
You don't need to rename the ROMs or do something special in order for it to work.
We've seen some cases where this happens, but haven't been able to pinpoint it exactly so far.

What controller are you using? There's a chance it might be related to that, but we're not sure yet...

**Comment by jimi007** [comment]
Hi

I am using the 8bitdo sfc30 pro controller.
 
I might try and give retropie a complete reload from scratch

**Comment by HoraceAndTheSpider** [comment]
Does the game load if you just hit reset at the black screen point?

**Comment by jimi007** [comment]
I will pass on a bit more information

I have created a new retopie image 4.4 with stretch and am using amiberry 2.19 and an 8bitdo sf30 pro controller. I have moved two .lha files into the Amiga Roms folder and I also have the kickstart roms in the correct folder.
When I start the lha files the screen goes black with no Amiberry image. No autoboot file is created.
I have manually put in an autoboot file and the game still does not start.
I try and press a button to reset at the black screen point but still does not start the game or create an autoboot file.

I also have a previous retopie image 4.3 on Jessie with Amiberry 2.18.1 working fine on UAE files and games in the whdload folders with the 8bitdo sf30 pro controller.
I upgraded retropie to 4.4 and amiberry to 2.19 (from source).
I moved some .LHA files to the amiga roms folder and started thm through the menu.
This does create the autoboot file and detects the kickstart roms (creates a syslink in the folder).
The issue here is I can see the amiberry logo come up and then the screen goes black and the game doesn't start.
I have tried resetting with the button as well.
I can also see it identifying the .slave file after pressing the reset button but cannot get the game to start.

I can try and take some screenshots if needed.

Fantastic work by the way on the emulator.

**Comment by HoraceAndTheSpider** [comment]
Try replaceing the boot-data.zip in the Configs/amiga/amiberry/whdboot folder with this one:

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/downloads/03-2018/boot-data.zip

THis should at least allow us to see DOS for debugging.

This problem has only appeared since the Retropie integration, so i do wonder if something has gone wrong with thtat install process.

@jimi007 your problems on Stretch suggest a problem with the RetroPie load script, but i would check if i wer you that everything is installed correctly int he configs fodler first.

**Comment by jimi007** [comment]
Hi 

I have now redone the retropie image 4.4 on a new sd card and setup a controller (8bitdo sf30 pro) first and installed amiberry 2.19 from source.
I have kickstart roms and just wanted to confirm which folder I need to place the roms in and do I need to name them a particular name.
eg from the wiki should I put the roms in save-data/Kickstarts and call them kick31.rom or just keep the original names.

I will then test again once this is complete.

Thanks for your help so far

Jimi

**Comment by midwan** [comment]
@jimi007 
The kickstart roms go in ~/RetroPie/BIOS/ and you can create a subdirectory there if you want (I create one called "amiga"). Just make sure you assign the same path in the emulator as well, under the Paths panel, and click on Rescan ROMs once.

The naming of the ROMs does not matter, as they are recognized by their checksum anyway. You can call them whatever you want. ;)

If you are using the Amiga Forever ROMs, remember to also include the "rom.key" file in the same directory, as those are encrypted and the key is required to read them.

**Comment by jimi007** [comment]
Hi
I have done some more testing. 
I have now placed the roms in the correct folder and rescanned the path.
I can see that the syslinks are created to the roms.
I used the new Amiga DOS boot-data.zip
I find when I try and start a new game eg wizball it finds a slave file in the LHA file and then says
Setpatch... Not Found

AmigaDOS says
Scanpath is whdloadgame : only
Execute the Auto-Startup boot script.

WHDLOAD failed return code 10
1>

I have also tried hitting the fire button at the amiberry logo and amiga dos says force creation of new auto startup file and still returns the same error code.

Also the debug whdscript file says "wrong number of arguments"

Hope this helps

**Comment by jimi007** [comment]
Ok I just worked out my issue. Just realised you need the game file in the LHA file or it will not work.
Speedball 2 was the only one with the game file.

I now have a DH0 is write protected issue when running another game but will look into that further.

You can close this off if you need to.

Thanks for your help

**Comment by midwan** [comment]
@jimi007 
Happy to see that you found a solution! :)

**Comment by lukasynthetic** [comment]
I've been scratching my head over this for quite few days as I did everything as described in manuals.
I was using lha's from whdload.dd
None of them worked.
Then I tried other ones, from English Amiga board.
And they work great!
I assume the difference is in structure as I was getting wrong line arguments and other errors in debug.
Any chance to look into this and maybe modify the script?

(Not sure anyone will read this, as it's been closed but finding this question somehow helped me find the right solution)

**Comment by midwan** [comment]
The WHDLoad packages you used originally are out-of-date, hence the problems.
The ones from EAB are newer, so they work as expected.

I don't think there's something that needs to change from the emulator's side of things for this, but @HoraceAndTheSpider  might know more...

**Comment by HoraceAndTheSpider** [comment]
Do you mean WHDLoad.de ?

If so, those don’t have game data, they are the installers only. You need (pre)installed versions , which is why the RetroPlay ones work.

**Comment by lukasynthetic** [comment]
Now it makes sense as the sizes were very small. Thank you for clarification.

**Comment by Marcoqwerty78** [comment]
Sorry to jump on this topic...but i have the same issue.

I tried to play a game: AnotherWorld, i uncompress the .lha (dl from EAB Retroplay), generated a .uae ( with script with UAEConfigMaker) and i get a Black screen.

so... i make another test

Download FlightOfTheAmazonQueen (always from the same place) and replaced the original FlightOfTheAmazonQueen (working) from the original installation ( RetroPieAmigaSetup from Horace ).

The .lha (uncompressed) are identical...identical folder/name and size, but, the whdloader start and "crash" istantly and i get this black screen again.

I make a lot of check, but i do not find anything of wrong.

I'm missing some other steps?

Thank you!

**Comment by HoraceAndTheSpider** [comment]
The .uae Config Maker and uncompressed LHA method is no longer supported. It can still be used but you would need to work out your own requirements.


You are better to use a compressed LHA and the in-build WHDLoad booter solution. 

The two are not the same thing. Please refer to the wiki guide instructions for this.

**Comment by Marcoqwerty78** [comment]
Sorry can you point me on a right direction? or provide me a link? 

I only discover to add -autowhdload=<file> to the cmd line before launch the .lha, but it doesnt work.

Thank you!!!!!!
