### ISSUE TITLE
Help with launching WHDLoad games with autobooter

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#307]
Hello guys,
First of all well done on the latest version of amiberry, this emulator absolutely rocks!
I have read the documentation a few times on the wiki about the WHDLoad autobooter, but I still can't work out how to use it.
The part I am stuck on is where it mentions ''The file should be specified from command line with the option -autowhdload=<file>
Could you give me an example of how do I do that? Do I need to create a text file with a command for each game? If yes, could you post an example of this text file?

I also tried just putting a zipped WHDLoad game in the roms/amiga folder but that just causes the screen to go black and the raspberry pi to freeze when I select it.

I am using a RPI3 running retropie and emulation station. I have installed the amiberry update from binaries.

Thanks in advance for the help!

**Comment by midwan** [comment]
@RetroD 
Thanks for the kind words! :)

If you're running RetroPie, the most of the work is already done for you (meaning the commandline option). What you have to do is:
1) Place your Kickstart ROMs in the right directory (e.g. `~/RetroPie/BIOS/amiga/`)
2) Make sure the same path is references in Amiberry's Paths panel, for Kickstart Roms!
3) Click Rescan ROMs in Amiberry's Paths Panel once, to detect all ROMs and cache them
4) Place your WHDLoad `".lha"` files in the proper location (e.g. `~/RetroPie/roms/amiga/`)
5) Restart Emulation Station to pick up the new files

After that, you should be able to see the list of games you added, and selecting one of them will launch the emulator with the appropriate commandline option to trigger the WHDLoad booter.

If you still have issues, please post specifics so we can investigate. :)

**Comment by RetroD** [comment]
Thanks midwan :)
Ok, so I have done from point 1 to 3 (I can launch WHDLoad games using UAE files no problems). Only difference I see is you mention 'lha' as a file format. I am using 'zip' - could this be the problem?

I can see the game in the list. 

Ok as I was typing this I tested a different game (IK+) and it seems I got a little further. However I get to a CLI window and it stays there (says something about AROS and the last line of text reads '1> 1>'

Is this a sign at least that the game is being attempred to be launched? (note I do not see an amiberry screen at all - just grey, then it took me to the CLI screen)

**Comment by RetroD** [comment]
also, I can see nothing was created under the autoboots or kickstarts folders

**Comment by RetroD** [comment]
I have done one more test with a different game and I get a grey screen that says 'no bootable media'
So in short I tried launching these zipped games:

Moonstone: black screen and pi cannot be used anymore ( I need to pull the power out)
IK+: goes to a cli window
Shadow Of The Beast: grey screen that says 'no bootable media'

**Comment by HoraceAndTheSpider** [comment]
RetroPie does not support the .zip format, only LHA, because it ikely interprets them as Zipped ADF files.

**Comment by RetroD** [comment]
@HoraceAndTheSpider
Ah I see thank you, I will look for a windows tool to batch convert all my zips and will give it another try later on today.  (If you know of one you can recommend please let me know)

Any chance to support zip files as well in the future? Would be great to have the flexibility.

Thanks again

**Comment by HoraceAndTheSpider** [comment]
Amiberry supports ZIP files for this feature, it's a RetroPie scripting issue i'm afraid, so nothing we can do here.

Dont bother with a batch converter, the LHA versions of the same files are very easy to find online, and it is now the common way for distribution since they are more compatibile with ZIPs across multiple systems.

**Comment by RetroD** [comment]
Ah ok, I thought it would have been possible because that's how other emulators work on retropie, but then I don't know the ins and outs of it.
Cool I'll have a look for the lha versions of the files

**Comment by midwan** [comment]
@RetroD 
The launch script that RetroPie uses for Amiberry, specifically checks for `zip` files first and launches them like ADFs, and `lha` files afterwards and launches them as WHDLoad slaves. The emulator itself can handle them, but because of the way RetroPie runs it, it will only work with `lha` format.

**Comment by Marcoqwerty78** [comment]
Hi. I have some issue to running this command line trought Attcact Mode.
I' working hard all the day to find a solution but nothing happens.

Also i have tested trought command line (outside attract mode) to launch a .lha file, but i get an error

Basically these are my step:

(all the step to 1 to 5 are checked)

**- Attract come lauch RUNCOMMAND**


```
# Generated by Attract-Mode v2.3.0
#
executable           /opt/retropie/supplementary/runcommand/runcommand.sh
args                 0 _SYS_ amiga "[romfilename]"
rompath              /home/pi/RetroPie/roms/amiga
romext               .adf;.adz;.dms;.ipf;.lha;.sh;.uae;.zip;.ADF;.ADZ;.DMS;.IPF;.LHA;.SH;.UAE;.ZIP
artwork    flyer           $HOME/1a/boxart
artwork    marquee         
artwork    snap            $HOME/1a/videos;$HOME/1a/snap
artwork    wheel   
```


**Runcommand launch AMIBERRY**

`
amiberry = "/opt/retropie/emulators/amiberry/amiberry.sh -autowhdload=%ROM%"
default = "amiberry"
`

I see the amiga Kickstart and stop

**Log or retropie** 

`
Parameters: 
Executing: /opt/retropie/emulators/amiberry/amiberry.sh -autowhdload="/home/pi/RetroPie/roms/amiga/Capone_v1.1.lha"
` 

Im totally lost, if i can check a way to test if AMIBERRY works correctly outside ATTRACT MODE i can investigate more about "how"to launch it trought attract mode!

Thank you to your amazing work!
