### ISSUE TITLE
Manually load LHA possible ?

### ISSUE THREAD

**Issue by ZappaUtopia** [midwan/amiberry#308]
Is it only possible to use LHA files from EmulationStation ? I would like to load some demos in LHA format. There's no option in Amiberry to load an Archive (like WinUAE). I tried adding a Hardrive but when looking in the filelist none of the LHA's show up.

Also, how would we change the settings for LHA Games like the Vertical Resolution and Offset, I see a lot of them are incorrect. This is a lot more trickier than using the UAE Config Maker. With that you can manually change the settings for each game. Do we have to wait for this Online Database ?

**Comment by midwan** [comment]
Correction: You can also load archives that represent a directory, and they will be treated as virtual hard drives, like in WinUAE.

**Comment by ZappaUtopia** [comment]
So its not possible to load LHA files from within Amiberry ? I thought Horace said you could. 

So to load demos in LHA files I have to put them in the same directory as the LHA games and run them from Emulation Station ? How would you change the settings for the demos ?

**Comment by midwan** [comment]
@ZappaUtopia 
If the LHA files contain WHDLoad installations, regardless if they are games or demos, then YES, they will work. :)

For RetroPie (which I will assume you're using), you can either just place them in the same folder, or even create subfolders (which is what I did) to better organize stuff.
For example, my dir structure looks like this:

~/RetroPie/roms/amiga/
                                      |_Games
                                                  |_A
                                                  |_B
                                                  |_C
                                      |_Demos
                                                  |_A
                                                  |_B
                                                  |_C

and I have titles under each respective folder (A, B, C, etc).

RetroPie scans them and will show them in this structure as well, which makes things easier to navigate also.

The settings for WHDLoad titles come from the database, but you can always override them locally. You can either modify the host_prefs file for some settings you'd like to have persistent, or override them on-the-fly for a title by just hitting F12 (or whatever key you have assigned to open the GUI) and changing them in the emulator's GUI. In the later case, they won't be saved to disk, of course.

When we go live with the online database approach, things will get easier as we can them modify settings there and everyone will get the benefits immediately.

Hope that helps!

**Comment by ZappaUtopia** [comment]
Sorry for all the questions, so where would the settings come from when I load a LHA Demo ? Is it that XML file ? I had a quick look through it but didnt see anything about demos, and it looks like it detects the games by filename. I see some of them are older versions so this means if I use the latest LHA the special settings will not be applied because its looking for an obsolete version ? 

I think I'll have to stick with the UAE config maker as its easier to manually change the settings like resolution and offset :) (a lot need changing) .

**Comment by midwan** [comment]
@ZappaUtopia 
The settings would come from that XML file, so if there are none found for the title, you won't have any special settings.

There's nothing stopping you from using the UAE config approach as well, of course. This was just a new feature for convenience. ;)

**Comment by ZappaUtopia** [comment]
So we will have to wait for a database update (Github ?) before we can use the latest versions ? Also, some games change names. For instance, recently Captain Dynamo has now been renamed to Dynamo.

When you say the the UAE Config Maker has been ceased, it will still be supported/work with Amiberry ?
It's easy to change the settings that have the wrong offset etc. I don't know if people will be able to change the xml file, we can only report and wait for you to change it ?

When I first heard about this feature I thought that you could also set a config in the Amiberry GUI and then mount an LHA file as a Hardrive and then Amiberry would do the rest. This would be good for the Demos side of things as nearly all will run with the same config.
