### ISSUE TITLE
WHDLoad AutoBooter and 68000 CPU kickstart

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#309]
Hello guys,
I finally managed to get WHDLoad Autobooter working great on my Retropie (RPi3), thanks again for this update.
I have encountered one issue which I believe to be related to an incorrect Kickstart.
I am trying to run Barbarian_v1.1_Palace_1784 and when I launch it, it goes back to the games selection list. I noticed the CPU in the XML is set to 68000 and it says on the wiki that if it is the case it will try to use the A600HD Kickstart 2.05 rom.

Now, I did try to cheat and added an override config with a 68020 - the game works, but probably a little too fast :)

So my question is, is there a list of expected names for the kickstart roms? I have the following but maybe Amiberry expects them to be named in a specific way?
A600HD Kickstart ROM v2.05 rev 37.300 (512k)
A600HD Kickstart ROM v2.05 rev 37.350 (512k)

For more information, I have the following in my Kickstarts folder the amiberry points to:
cd32ext.rom
cd32kick31.rom
kick12.rom
kick13.rom
kick20.rom
kick30.rom
kick31.rom
kick204.rom
kick205.rom

And these are the files that were generated so far in whdboot\save-data\Kickstarts:
kick34005.A500
kick37175.A500
kick40068.A1200

Any help would be greatly appreciated, even if there is a list of correct names or revisions for the required roms.
Thanks!

**Comment by HoraceAndTheSpider** [comment]
it is deliberate that 68000 is selected, for the speed issues you mention ;)

Amiberry doesnt use naming for its file detection, but WHDload does require some quite specific versions, and only those have symlinks created .  

There is a list.... it's here:  
http://ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/guide.html#step-2

**Comment by RetroD** [comment]
Thank you, yes that makes sense. I think I have all the correct roms from that list but I still can't get it to work. Do you know the one needed for the 68000? (or are there multiple ones that may be used). Do they need to be the 512 dump or 256 (I remember issues related to these in the past).
I suppose the cloanto ones are no good?

**Comment by midwan** [comment]
@RetroD 
Cloanto ones also work, just remember to keep the "rom.key" file in the same directory as the ROMs, as they are encrypted.

**Comment by RetroD** [comment]
@midwan 
Thanks I have tried  all the kickstarts I have (and I have MANY :) ), but still no luck with that game.
Interestingly enough I though to delete all my kickstarts and just copy the cloanto ones I bought a few months ago (so I assume they should contain everything). I noticed all the kickstarts in whdboot\save-data\Kickstarts are also gone - not sure if it was me doing something but they are not there anymore.

I thought that now I could start clean and it would recreate symlinks. I launched a few games and no symlinks were created, although the games worked (besides Barbarian Palace of course)

Does Barbarian (palace version) work for you guys? Just checking before I lose my mind tonight :-D

**Comment by RetroD** [comment]
The games seem to work without the symlinks, but yeah, if you use the Cloanto ones no symlink is created.
If you guys got the game to work and know what the specific version and dump of the rom is it would be great. I noticed it's the only game with CPU set to 68000 in the configuration.

**Comment by RetroD** [comment]
Maybe it's not kickstart related... I seem to have the correct one according to this:
http://www.whdload.de/games/BarbarianPalace.html

Anything that could cause amiberry to go back to the list when CPU is set to 68000?

**Comment by RetroD** [comment]
Thanks @HoraceAndTheSpider, was writing this as you posted:

Ok, hopefully last post and I'll leave you alone. I got it to work, but it makes no sense to me:
I just created a new override file for the game, but I have put the same parameters from the XML!

My custom config:
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
CPU=68000
JIT=FALSE
SCREEN_HEIGHT=200
SCREEN_Y_OFFSET=3

Is this possibly a bug? I find it strange that it would work by replicating the same thing from the xml.
The speed of the game is the same as when I set it to 68020 though. My memory is a bit hazy on what this should be like on a real amiga so I am unsure if the speed is correct or not.

So I am now wondering if the CPU parameter I have set to 68000 is actually been used?
I'll wait for you to run some tests though. Hopefully you have enough info to establish if it's a problem with my setup or a bug.

Thanks again!

**Comment by HoraceAndTheSpider** [comment]
The two sections use the same parsing code so they should behave the same, but that doesn’t mean they do!!

Useful information for me to track down any bug with though, thank you :)

**Comment by henrikstengaard** [comment]
WHDLoad v17.0 or better supports Cloanto encrypted Kickstart rom files, just remember to include rom.key file next to Kickstart rom files in SYS:Devs/Kickstarts.

As a side note, WHDLoad v18.2 or better doesn't require a registration file.

**Comment by HoraceAndTheSpider** [comment]
I’ll arrange for rom.key to be symlinked if available.

**Comment by RetroD** [comment]
Hello @HoraceAndTheSpider,
I was wondering if you had a chance to test Barbarian_v1.1_Palace_1784 to see if it works correctly for you with the 68000 option? No pressure, just curious if you got round to trying it out.

**Comment by HoraceAndTheSpider** [comment]
@RetroD i've resolved a problem with `Barbarian_v1.1_Palace_1784` today, so see if that works for you. I still need to do the `rom.key` symlink though

**Comment by RetroD** [comment]
Awesome! Do I just need to update from source to get the fix?

**Comment by HoraceAndTheSpider** [comment]
You would need to compile the 'dev' branch, but atm, dont bother, i have experienced some other issues with this i need to look into (GURUs on the game load, but not the booter)

**Comment by RetroD** [comment]
I fear I would get lost trying to compile myself, I am quite new to the raspberry pi. I know how to pull from source when updating software on retropie (or getting binaries directly of course), but that's about it :).
I will wait for when these changes are released no probs.

**Comment by midwan** [comment]
Version v2.21 is now pushed to master, so you can use RetroPie's "compile from source" option to easily get it.

Closing this issue for now then, unless we hear it's still a problem. In that case, we can re-open it.
