### ISSUE TITLE
Render into 32-bit texture instead of 16-bit

### ISSUE THREAD

**Issue by AdvancedFollower** [midwan/amiberry#311]
I'm noticing significant banding when viewing truecolor images on Amiberry even when Workbench is set to 32-bit color.

fbset at the Linux console reports:
geometry 1920 1080 1920 1080 32
accel true
rgba 8/16,8/8,8/0,0/0

So the actual mode of both Workbench and the underlying Linux seems to be 32-bit. Is it possible Amiberry is rendering to a 16bpp (RGB 565) texture on a 32-bit screen?
I searched around for Raspberry Pi banding and found this:
https://discourse.libsdl.org/t/raspberry-pi-and-open-gl-es-2-color-depth/21686/3

**Comment by midwan** [comment]
@AdvancedFollower 
Yes, it's actually using a 16-bit texture for speed considerations.
The reason this wasn't changed already was that we had optimized assembly code to speed up writes to 16-bit surfaces, so if we move to 32-bit ones we need to adapt or change those routines as well.

As most modes were not affected (you won't notice at all on games and normal Amiga modes, only if you open up a 24-bit image in RTG mode) we kept it like that until now.

I'll revisit this however and see how much of an impact there is.

**Comment by AdvancedFollower** [comment]
That makes sense, and for most classic games and programs that would run on a 4 - 256 color screen on a real Amiga, there wouldn't be any visual difference. However it would be interesting to see how much of a performance hit there is on a Pi 3B/3B+. Maybe you could even make it so that 32-bit rendering is only engaged when you're using an RTG mode that requires it (if that's possible).

**Comment by midwan** [comment]
@AdvancedFollower 
Yes, it's certainly possible to only use 32-bit surfaces/textures on RTG modes. In fact, I'm working on this these days and I've already have the non-RTG modes working correctly with 32-bit modes, while the RTG ones still need some work.

Once I have it working correctly everywhere, it will be time for some benchmarks, to see how much of a performance hit there is exactly. Ideally I'd prefer to only use the bit depth required, e.g. if you open a 16-bit RTG mode then the surface should also be that.

**Comment by midwan** [comment]
Testing with Picasso96 32-bit mode:

![amiberry 32-bit test](https://user-images.githubusercontent.com/3877365/39752300-471d2952-52bb-11e8-973e-e7b926d39ba9.png)

**Comment by midwan** [comment]
This is now in `dev` with 6696602e8bfe7b56da0f6f0a0a5b775b14bd5345

**Comment by midwan** [comment]
To clarify:
- Picasso96 modes will now use a 16-bit or 32-bit surface/texture, depending on what mode was requested. This has the added benefit of not having to convert 32-bit surfaces to 16-bit and can now be used "as-is". P96 8-bit modes will still use a 16-bit surface and texture.
- Non Picasso96 modes will use 16-bit surface and texture as before, for speed considerations. I don't think we need higher than that anyway, as even HAM-8 cannot show more colors.

**Comment by midwan** [comment]
Closing this since it's already implemented, it will be merged into `master` with the next update.
