### ISSUE TITLE
Setting up a new ADF game

### ISSUE THREAD

**Issue by Shawson** [midwan/amiberry#312]
Are there any guides kicking about for setting up a new game from an ADF file?  Where do I put the ADF file?  How do I go about creating a UAE file and where should that live once it's been made?  

I've put the ADF file in the roms file, and it appears in emuilation station- when i click it AmiBerry tries to launch it but i just get a blank AROS dos screen- If i then pop the menu and change the rom/ ram etc and restart the game loads, but I've no idea how I go about saving this to a UAE file that appears in my "Amiga" menu?

**Comment by midwan** [comment]
@Shawson 
Technically you can put the ADF file anywhere you want, as long as you point the emulator to it.
If you're using RetroPie (which I'm assuming, from your reference to EmulationStation), it expects ADFs to be in ~/RetroPie/roms/amiga by default.

You can save new configs which include all your settings, including your HDDs, or ADFs, in the Config Panel of the emulator. Just give it a name, optionally a description, and click on Save.
