### ISSUE TITLE
Md5sum crashes or exits with JIT enabled

### ISSUE THREAD

**Issue by henrikstengaard** [midwan/amiberry#314]
### Expected behavior
No crash or exit when running md5sum with JIT enabled.
It works fine without crashing or exiting, if JIT is disabled.

### Actual behavior
Crash or exit when running md5sum a few times.

### Steps to reproduce the behavior

1. Extract attached file amiberry_crash_md5sum_jit.zip and launch Amiberry with added directory containing the files. Config file is included. Make sure JIT is enabled.
2. Type "md5sum -b md5sum".
3. Repeat step 2 a few times and Amiberry crashes or exits.

[amiberry_crash_md5sum_jit.zip](https://github.com/midwan/amiberry/files/1957480/amiberry_crash_md5sum_jit.zip)

**Comment by midwan** [comment]
Confirmed

**Comment by midwan** [comment]
@henrikstengaard 
thanks for confirming that, I'll keep the issue open until we fix this.
