### ISSUE TITLE
Pressing x automatically also presses enter

### ISSUE THREAD

**Issue by henrikstengaard** [midwan/amiberry#316]
### Expected behavior
Pressing x only presses "x" key and pressing 2 only presses "2" key.

### Actual behavior
Pressing x automatically also presses "enter" key  and pressing 2 automatically also presses "p" key.

### Steps to reproduce the behavior

1. Download and compile latest Amiberry from master branch.
2. Start Amiberry with Workbench floppy disk in DF0 and open CLI/Shell.
3. Press x and it will automatically also press "enter" key.
4. Press 2 and it will automatically also press "p" key.

**Comment by midwan** [comment]
@henrikstengaard 
This is happening if you set Port 1 to Keyboard as Joystick, because those keys are used by games and they are included in the default mapping. If you set it to None or a real controller, this behavior will not occur.

**Comment by henrikstengaard** [comment]
Thanks, that solves it.
