### ISSUE TITLE
Add Odroid C1 in Makefile targets

### ISSUE THREAD

**Issue by MJB-G** [midwan/amiberry#317]
### Expected behavior
Building Amiberry on Odroid C1 with Ubuntu 16.04

### Actual behaviour
No C1 option in Makefile. Default building fails ; "fatal error: bcm_host.h" no found.

### Steps to reproduce the behaviour
Take an Odroid C1, install Ubuntu on it, try to compil Amiberry.

### Adding Odroid C1 ###
I success to build Amiberry by modifying XU4 options. Amiberry works fine on C1. Adding C1 in Makefile could make it easier to install with Retropie.

Thank for your help.

**Comment by midwan** [comment]
@MJB-G 
The default target is the RPI, as mentioned in the readme and the Makefile itself - so it's normal that won't work on the Odroid. :)

The XU4 is the closest target and should be used for this scenario. I can modify the Makefile to cover this scenario as well.

**Comment by MJB-G** [comment]
It would be great, thank.

**Comment by midwan** [comment]
@MJB-G 
Could you please check the latest Makefile from `dev` and confirm if it works for you?
I don't have a C1 to test locally I'm afraid...

**Comment by MJB-G** [comment]
I think this is : 

CPU_FLAGS += -march=armv7ve -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon-vfpv4

with this flags it works fine.

**Comment by midwan** [comment]
@MJB-G 
those are the flags I added in the `c1` target in the Makefile, so we should be good to go then.

Thanks for confirming!

**Comment by MJB-G** [comment]
In fact, you add armv7ve and cortex-a7, but I think C1 is armv7-a and cortex-a5.

**Comment by midwan** [comment]
@MJB-G 
Oops, you're right. I'll fix that.

**Comment by MJB-G** [comment]
Thank, I confirm there is no problem to build Amiberry on C1 and that Amiga 500 games work just fine (with gfx_framerate=1).
