### ISSUE TITLE
Question - Volume DH0 is write protected error with LHA file

### ISSUE THREAD

**Issue by jimi007** [midwan/amiberry#318]
### Expected behavior

To Start a game using an LHA file through Retropie 4.4 and Amiberry 2.19.

### Actual behavior

Game starts from the retropie menu and I can see the Amiberry logo.
Message comes up and says Volume DH0 is write protected Retry or Cancel

### Details

Hi

I am starting a game with an LHA file from the Retropie Menu and am receiving the above error message stating the hard drive is write protected.

It may just be that I don't understand how the LHA file works and runs the game files and need to investigate further.

Is there a way to turn off the write protection or is it something to do with the game file?

A game Speedball 2 runs fine but other files have the write protection issue.

The folder appears to be read write on the Raspberry Pi.

Regards

Jimi

**Comment by midwan** [comment]
This is related to the actual rights you have on the (.lha) files on the Linux filesystem.
I'm guessing you have read-only access...

Change the files/folders permissions with something like `chmod a+rw <file>` and this will go away...

**Comment by jimi007** [comment]
Hi 

I just realised I had tried converting a couple of zip files to LHA,
This explains my issue exactly. Amiberry still thinks the file is a zip file so that would explain the message.
The working game was a direct LHA file.

Thankyou for your help. So much easier now with the autoboot loading.

**Comment by HoraceAndTheSpider** [comment]
Zip files should work but you have to follow the exact convention for them, so that internally they have the same structure as the LHA.

**Comment by davidgrohl** [comment]
Hi all, please could you explain how to obtain LHA files from zip files? I have a lot of amiga games in zip format (the zips contain a folder named as the game and a .info file. Inside the folder there are some files: a .slave, a .info etc..): is there a way to convert them in lha?
Thanks for help.

**Comment by midwan** [comment]
@davidgrohl 
I am not aware of a tool that will do a batch conversion like you describe, however there are command line tools available (`unzip` and `lhasa` on linux) that could do the job, with a little script...

**Comment by davidgrohl** [comment]
@midwan I found a a tool called Izarc that can compress in lha. Do you think I can unzip and then compress in lha? Can it work?

**Comment by midwan** [comment]
Yes, that should work

**Comment by davidgrohl** [comment]
@midwan Thanks mate. I'll give it a try.
