### ISSUE TITLE
UAE Config Files v2.8.1 dont work in 3.6.0

### ISSUE THREAD

**Issue by bebess** [midwan/amiberry#319]
Hi,
I have a complet setup of games that have old config files v 2.8.1

I start to upgrade with the odroid version and the config file is v 3.6.0

My games dont load
What config did you change ?
I already change the directory of the home/pi with home/pigaming (for odroid)
i already change the pandora.rom etc with amiberry.rom etc

all the new path have been changed but the games dont star

here is the config file : 

> `config_description=

config_hardware=true
config_host=true
config_version=2.8.1
kickstart_ext_rom_file_id=87746BE2,CD32 extended ROM
kickstart_rom_file_id=1E62D4A5,CD32 KS ROM v3.1
amiberry.rom_path=/opt/retropie/emulators/amiberry/kickstarts/
amiberry.floppy_path=/opt/retropie/emulators/amiberry/disks/
amiberry.hardfile_path=/opt/retropie/emulators/amiberry/
amiberry.cd_path=/opt/retropie/emulators/amiberry/cd32/
; host-specific
pandora.cpu_speed=0
pandora.hide_idle_led=0
pandora.tap_delay=10
pandora.custom_controls=1
pandora.custom_up=-5
pandora.custom_down=-6
pandora.custom_left=-7
pandora.custom_right=-8
pandora.custom_a=-9
pandora.custom_b=-10
pandora.custom_x=-11
pandora.custom_y=0
pandora.custom_l=-13
pandora.custom_r=-12
pandora.move_x=0
pandora.move_y=0
; common
use_gui=no
kickstart_rom_file=/home/pigaming/RetroPie/BIOS/Amiga/cd32kick31.rom
kickstart_rom_file_id=1E62D4A5,CD32 KS ROM v3.1
kickstart_ext_rom_file=/home/pigaming/RetroPie/BIOS/Amiga/cd32ext.rom
kickstart_ext_rom_file_id=87746BE2,CD32 extended ROM
flash_file=/opt/retropie/emulators/amiberry/cd32.nvr
floppy0=
floppy0type=-1
floppy1=
floppy1type=-1
floppy2=
floppy3=
cdimage0=/home/pigaming/RetroPie/roms/amigacd32/Games_CD32/ATR - All Terrain Racing (CD32)/ATR - All Terrain Racing (1995)(Team 17)[!].cue,image
nr_floppies=0
floppy_speed=100
sound_output=exact
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_frequency=44100
sound_interpol=none
sound_filter=off
sound_filter_type=standard
sound_volume_cd=20
cachesize=0
joyport0=mouse
joyport0autofire=none
joyportfriendlyname0=Nubs as mouse
joyportname0=MOUSE0
joyport1=joy1
joyport1autofire=none
joyport1mode=cd32joy
joyportfriendlyname1=PLAYSTATION(R)3 Controller
joyportname1=JOY1
bsdsocket_emu=false
synchronize_clock=true
key_for_menu=293
key_for_quit=0
gfx_framerate=0
gfx_width=384
gfx_height=256
gfx_width_windowed=320
gfx_height_windowed=240
gfx_width_fullscreen=640
gfx_height_fullscreen=480
gfx_lores=true
gfx_resolution=lores
gfx_correct_aspect=0
gfx_fullscreen_ratio=100
kbd_led_num=-1
kbd_led_scr=-1
kbd_led_cap=-1
immediate_blits=false
waiting_blits=automatic
fast_copper=false
ntsc=false
chipset=aga
chipset_refreshrate=0.000000
collision_level=playfields
cd32cd=true
cd32c2p=true
cd32nvram=true
fastmem_size=8
z3mem_size=0
z3mem_start=0x10000000
bogomem_size=0
gfxcard_size=0
gfxcard_type=ZorroIII
chipmem_size=4
finegrain_cpu_speed=1024
cpu_type=68ec020
cpu_model=68020
cpu_compatible=false
cpu_24bit_addressing=true
rtg_modes=0x502
input.config=0
input.joymouse_speed_analog=2
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=15
input.analog_joystick_offset=-1
input.mouse_speed=100
input.autofire_speed=2496
input.1.joystick.0.friendlyname=dPad as joystick
input.1.joystick.0.name=JOY0
input.1.joystick.0.empty=true
input.1.joystick.0.disabled=false
input.1.joystick.1.friendlyname=PLAYSTATION(R)3 Controller
input.1.joystick.1.name=JOY1
input.1.joystick.1.empty=true
input.1.joystick.1.disabled=false
input.1.joystick.2.friendlyname=Sony PLAYSTATION(R)3 Controller
input.1.joystick.2.name=JOY2
input.1.joystick.3.empty=true
input.1.joystick.3.disabled=false
input.1.joystick.4.empty=true
input.1.joystick.4.disabled=false
input.1.joystick.5.empty=true
input.1.joystick.5.disabled=false
input.1.joystick.6.empty=true
input.1.joystick.6.disabled=false
input.1.joystick.7.empty=true
input.1.joystick.7.disabled=false
input.1.mouse.0.friendlyname=Nubs as mouse
input.1.mouse.0.name=MOUSE0
input.1.mouse.0.empty=true
input.1.mouse.0.disabled=false
input.1.mouse.1.friendlyname=dPad as mouse
input.1.mouse.1.name=MOUSE1
input.1.mouse.1.empty=true
input.1.mouse.1.disabled=false
input.1.mouse.2.empty=true
input.1.mouse.2.disabled=false
input.1.mouse.3.empty=true
input.1.mouse.3.disabled=false
input.1.mouse.4.empty=true
input.1.mouse.4.disabled=false
input.1.mouse.5.empty=true
input.1.mouse.5.disabled=false
input.1.mouse.6.empty=true
input.1.mouse.6.disabled=false
input.1.mouse.7.empty=true
input.1.mouse.7.disabled=false
input.1.keyboard.0.friendlyname=Default Keyboard
input.1.keyboard.0.name=KEYBOARD0
input.1.keyboard.0.empty=false
input.1.keyboard.0.disabled=false
input.1.keyboard.1.empty=true
input.1.keyboard.1.disabled=false
input.1.keyboard.2.empty=true
input.1.keyboard.2.disabled=false
input.1.keyboard.3.empty=true
input.1.keyboard.3.disabled=false
input.1.keyboard.4.empty=true
input.1.keyboard.4.disabled=false
input.1.keyboard.5.empty=true
input.1.keyboard.5.disabled=false
input.1.keyboard.6.empty=true
input.1.keyboard.6.disabled=false
input.1.keyboard.7.empty=true
input.1.keyboard.7.disabled=false
input.2.joystick.0.friendlyname=dPad as joystick
input.2.joystick.0.name=JOY0
input.2.joystick.0.empty=true
input.2.joystick.0.disabled=false
input.2.joystick.1.friendlyname=PLAYSTATION(R)3 Controller
input.2.joystick.1.name=JOY1
input.2.joystick.1.empty=true
input.2.joystick.1.disabled=false
input.2.joystick.2.empty=true
input.2.joystick.2.disabled=false
input.2.joystick.3.empty=true
input.2.joystick.3.disabled=false
input.2.joystick.4.empty=true
input.2.joystick.4.disabled=false
input.2.joystick.5.empty=true
input.2.joystick.5.disabled=false
input.2.joystick.6.empty=true
input.2.joystick.6.disabled=false
input.2.joystick.7.empty=true
input.2.joystick.7.disabled=false
input.2.mouse.0.friendlyname=Nubs as mouse
input.2.mouse.0.name=MOUSE0
input.2.mouse.0.empty=true
input.2.mouse.0.disabled=false
input.2.mouse.1.friendlyname=dPad as mouse
input.2.mouse.1.name=MOUSE1
input.2.mouse.1.empty=true
input.2.mouse.1.disabled=false
input.2.mouse.2.empty=true
input.2.mouse.2.disabled=false
input.2.mouse.3.empty=true
input.2.mouse.3.disabled=false
input.2.mouse.4.empty=true
input.2.mouse.4.disabled=false
input.2.mouse.5.empty=true
input.2.mouse.5.disabled=false
input.2.mouse.6.empty=true
input.2.mouse.6.disabled=false
input.2.mouse.7.empty=true
input.2.mouse.7.disabled=false
input.2.keyboard.0.friendlyname=Default Keyboard
input.2.keyboard.0.name=KEYBOARD0
input.2.keyboard.0.empty=false
input.2.keyboard.0.disabled=false
input.2.keyboard.1.empty=true
input.2.keyboard.1.disabled=false
input.2.keyboard.2.empty=true
input.2.keyboard.2.disabled=false
input.2.keyboard.3.empty=true
input.2.keyboard.3.disabled=false
input.2.keyboard.4.empty=true
input.2.keyboard.4.disabled=false
input.2.keyboard.5.empty=true
input.2.keyboard.5.disabled=false
input.2.keyboard.6.empty=true
input.2.keyboard.6.disabled=false
input.2.keyboard.7.empty=true
input.2.keyboard.7.disabled=false
input.3.joystick.0.friendlyname=dPad as joystick
input.3.joystick.0.name=JOY0
input.3.joystick.0.empty=true
input.3.joystick.0.disabled=false
input.3.joystick.1.friendlyname=PLAYSTATION(R)3 Controller
input.3.joystick.1.name=JOY1
input.3.joystick.1.empty=true
input.3.joystick.1.disabled=false
input.3.joystick.2.empty=true
input.3.joystick.2.disabled=false
input.3.joystick.3.empty=true
input.3.joystick.3.disabled=false
input.3.joystick.4.empty=true
input.3.joystick.4.disabled=false
input.3.joystick.5.empty=true
input.3.joystick.5.disabled=false
input.3.joystick.6.empty=true
input.3.joystick.6.disabled=false
input.3.joystick.7.empty=true
input.3.joystick.7.disabled=false
input.3.mouse.0.friendlyname=Nubs as mouse
input.3.mouse.0.name=MOUSE0
input.3.mouse.0.empty=true
input.3.mouse.0.disabled=false
input.3.mouse.1.friendlyname=dPad as mouse
input.3.mouse.1.name=MOUSE1
input.3.mouse.1.empty=true
input.3.mouse.1.disabled=false
input.3.mouse.2.empty=true
input.3.mouse.2.disabled=false
input.3.mouse.3.empty=true
input.3.mouse.3.disabled=false
input.3.mouse.4.empty=true
input.3.mouse.4.disabled=false
input.3.mouse.5.empty=true
input.3.mouse.5.disabled=false
input.3.mouse.6.empty=true
input.3.mouse.6.disabled=false
input.3.mouse.7.empty=true
input.3.mouse.7.disabled=false
input.3.keyboard.0.friendlyname=Default Keyboard
input.3.keyboard.0.name=KEYBOARD0
input.3.keyboard.0.empty=false
input.3.keyboard.0.disabled=false
input.3.keyboard.1.empty=true
input.3.keyboard.1.disabled=false
input.3.keyboard.2.empty=true
input.3.keyboard.2.disabled=false
input.3.keyboard.3.empty=true
input.3.keyboard.3.disabled=false
input.3.keyboard.4.empty=true
input.3.keyboard.4.disabled=false
input.3.keyboard.5.empty=true
input.3.keyboard.5.disabled=false
input.3.keyboard.6.empty=true
input.3.keyboard.6.disabled=false
input.3.keyboard.7.empty=true
input.3.keyboard.7.disabled=false
input.4.joystick.1.friendlyname=PLAYSTATION(R)3 Controller
input.4.joystick.1.name=JOY1
input.4.joystick.1.custom=true
input.4.mouse.0.friendlyname=Nubs as mouse
input.4.mouse.0.name=MOUSE0
input.4.mouse.0.custom=true
input.4.keyboard.0.friendlyname=Default Keyboard
input.4.keyboard.0.name=KEYBOARD0
input.4.keyboard.0.custom=true

**Comment by midwan** [comment]
@bebess 
There are several changes, some options are obsolete, some are renamed and some are completely removed (especially duplicates).
The best way to proceed would be to create a new config based on the Quickstart option closer to the system you want to emulate, then save it and compare it with the old one you had.

This was necessary to bring it up to date with the latest versions of WinUAE and remove several inconsistencies (e.g. duplicate options, pandora-specific options that didn't make sense to keep, etc).

**Comment by bebess** [comment]
i try a quickstart uae config file
i don't see so much difference , some are removed
but i don't know why the old config file dont work at all
it just boot on the amigacd32 logo , and nothing

i have a quickstart config file that work but i have 175 cd32 games so i don"t want to edit each files 1 by 1 to change the cue/iso files ^^

i ll try to check the difference...

**Comment by midwan** [comment]
Another thing that might help:
Try deleting the old `adfdir.conf` file (under the conf/ directory) and then restart the emulator, and click on Rescan ROMs in the Paths panel.

The file will be regenerated when you quit the emulator again.

**Comment by bebess** [comment]
no difference after deleting the old file

**Comment by bebess** [comment]
I FIND IT ! ^^

ok there was a config line that seems important and is not in the old config uae files
``chipset_compatible=CD32`

@ransom1122 , i use your config files :) ^^
I change 2 lines that need to be changed to be ok for the last update (3.6.0)

"gfx_width=384" need to be changed for "gfx_width=768"
"chipset_compatible=CD32" need to be added
(you can easily change a line that is useless like input.config=0 )

i only test cd32 games , no whd/adf games
