### ISSUE TITLE
CHD support for CD images

### ISSUE THREAD

**Issue by bebess** [midwan/amiberry#320]
hello :)

I see in the `blkdev_cdimage.cpp` file

> - iso (2048/2352 block size)
> - cue/bin, cue/bin/wav, cue/bin/mp3, cue/bin/flac
> - ccd/img and ccd/img/sub
> - chd cd

I try a CHD file but it"s not recognized ^^

I will be a great feature..
It save 30% to 40% of space and only 1file/game

Any idea if it will be implemented on future updates ?

**Comment by midwan** [comment]
@bebess 
I haven't tested CHDs so far, so I wasn't aware there was an issue.
You can still have 1 file / game with other formats as well (ZIP, LHA, 7z), but I don't even have CHDs to try with. How did you create it?

**Comment by bebess** [comment]
chd has a better compression than bin/cue

i test with chdman.exe version 0.189
with command line `chdman createcd -i name.cue -o name.chd"`

**Comment by Enverex** [comment]
@midwan Just to clarify, bebess is likely referring to CD32 games or virtual CD images to access in Workbench. It's not an ADF or LHA WHDLoad format replacement.

CHD's becoming relatively common in emulators now for a few reasons. Firstly is that it's tidy; each disk is only a single file. Second is that it's pretty much the best compression format for discs you can get (it uses LZMA for data and FLAC for audio) but doesn't need to be decompressed before use, it's "seekable" as-is.

Pretty much a godsend for space and tidiness.

**Comment by bebess** [comment]
@midwan , any update ?

**Comment by midwan** [comment]
@bebess 
Do you have a CHD image that works with WinUAE 4.1.0?
If so, could you send me such an image so I can test it here?

We had a file filter on the requester to only show *.cue, *.ccd and *.iso files, so *.chd would be hidden. I could easily add those in the list, but I'd like to test that they work first.

**Comment by gt46l** [comment]
Midwan, 

Since there is no PM system on Github, have you thought about starting an Amiberry discord channel, or otherwise joining an existing Amiga channel?  I'm sure people would be happy to contribute there, were you to need examples.

**Comment by midwan** [comment]
@gt46l 
We have a few Amiberry channels on Discord already:
- Ultimate Amiga: https://discord.gg/XaRNfB
- TheRA Official: https://discord.gg/u9f5SV (for the Odroid and Pine versions)

**Comment by nighthurdles** [comment]
@midwan Just trying to get into the Ultimae Amiga Discord channel but apparently the invite link on this thread has expired, could you please post a new one if it's still active? Thank you!

**Comment by midwan** [comment]
@nighthurdles 
Here's a new one: https://discord.gg/HeJgfmw

**Comment by nighthurdles** [comment]
Thanks :)

**Comment by foxp4v** [comment]
Hello, any chance to see chd support in Amiberry? Thanks for the great work so far!

**Comment by rtissera** [comment]
@midwan check out my https://github.com/rtissera/libchdr for easy CHD support ;)

**Comment by rtissera** [comment]
@midwan should/could I start a fork with CHD support for CD images based on my own libchdr ?
There's still "old" WITH_CHD #defines in blkdev_cdimage so it should be not too hard to hook in.

**Comment by midwan** [comment]
@rtissera 
I haven't had a chance to look into this yet, unfortunately. If you could assist with a pull request, it would be great!

**Comment by rtissera** [comment]
@midwan will do !

**Comment by TheRobotFactory** [comment]
Just checking in on the progress of this.

**Comment by midwan** [comment]
@rtissera 
Did you make any progress with this?
I was thinking of looking into it, now that I'll have some spare time during vacations. :)

**Comment by rtissera** [comment]
@midwan nope, feel free to have a look on how to integrate it through upstream MAME / WinUAE code or libchdr.

**Comment by midwan** [comment]
If anyone's interested to test it, I have a first version ready on a separate branch: `feature/chd`
Please provide feedback so we can be sure it works as expected, and nothing else is broken :)

So far I've tested both CD images and HDFs compressed to CHD, using `chdman` 0.238 (latest available on Manjaro), and they seem to work fine.

**Comment by rtissera** [comment]
Brilliant work @midwan !

**Comment by midwan** [comment]
This has been merged into `dev` now, including a full upgrade of all the 7-zip/LZMA archiver files (from v9.22 beta to v16.04), and the option to select .7z as a valid Hardfile format.
