### ISSUE TITLE
Compile under AArch64

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#322]
### Expected behavior
Amiberry should compile under AArch64 as well, for the platforms that run it (e.g. Pine64, Odroid N1, etc)

### Actual behavior
The project fails to build under AArch64.
There are errors reported regarding the loss of precision for pointers (`-fpermissive` can turn those into warnings for now) and some assembly code will not work.

### Steps to reproduce the behavior
Compile Amiberry under AArch64

**Comment by rockford** [comment]
Any progress? Would really like to use amiberry on AArch64 (Rock64 with debian stretch in my case).

**Comment by midwan** [comment]
There is some progress, but it's not complete yet due to lack of time...

**Comment by midwan** [comment]
The `dev` branch now includes support for 64-bit targets.
