### ISSUE TITLE
Visual artifacts with Birdie in 16-bit modes

### ISSUE THREAD

**Issue by AdvancedFollower** [midwan/amiberry#323]
### Expected behavior
Here's what it looks like on WinUAE running at 1920x1080x16bpp full-screen:
https://roughlyit.hopto.org/lychee/uploads/big/6097b34df1d19e2c21fb23eb451375c4.jpg

### Actual behavior
Here's the same HDF, loaded in Amiberry 2.19, DietPi 6.8 on a Pi 3B+, also 1920x1080x16bpp:
https://roughlyit.hopto.org/lychee/uploads/big/0bf139d3b292fbf54e5908d3938e9f6e.jpg

### Steps to reproduce the behavior
I'm running ClassicWB on top of AmigaOS 3.9, Picasso96 driver from here: http://lilliput.amiga-projects.net/Picasso96.htm

Using the Birdie theme from here: http://aminet.net/package/pix/theme/os4theme (only the Birdie part is needed to cause these pink lines to appear)

Turning off Birdie removes these visual artifacts. Switching to a 32-bit mode in Workbench also makes everything look normal (except for banding on the 24bpp wallpaper due to the emulator running in 16-bit mode).

**Comment by midwan** [comment]
@AdvancedFollower 
Thanks for reporting this.
I take it you haven't tested it with the latest `dev` branch version then, which includes native 32-bit support?

**Comment by AdvancedFollower** [comment]
I tried updating Amiberry from source in RetroPi, but Amiberry 2.21 just gives me a black screen when trying to boot from the HDF (can't even press F12 to access the menu). Will have to look into that.

**Comment by midwan** [comment]
@AdvancedFollower 
RetroPie will only allow you to install or compile the `master` branch version.
The `dev` version is newer and considered experimental, so it's not available in RetroPie. It can be downloaded, compiled and installed manually however. We wrote a Wiki article about the process [here](https://github.com/midwan/amiberry/wiki/Compiling-Development-Branch).

**Comment by midwan** [comment]
This is still happening in v2.24b8 currently.

Since I'm not sure what causes it exactly (Birdie is after all a hack, so it might be doing something funny - without the sources we don't know), I think I'll leave this out of the next stable release for now.

Maybe in a future update we can fix it by improving compatibility further, but I don't see it as a big issue for now.

**Comment by midwan** [comment]
This seems to be fixed in the current `dev`
