### ISSUE TITLE
Generic USB arcade joystick controller does not exit game

### ISSUE THREAD

**Issue by jabulonboaz** [midwan/amiberry#324]
### Expected behavior
Press a button or combination of buttons say select and start on a generic USB arcade joystick controller and exit game back to game list 

### connect a generic USB game controler such as RisDragon to the Pi,3 that used Amiberry and Retropie and press the retroarch hot key combination for exiting a game -read bellow

I am running retropie and i have updated Amiberry from source running version v2.20

Generic USB arcade joystick controller does not exit game  
I like to be able to just quit and exit a game via the press on a joypad button or combination of buttons say "select" and "start" just like it worked for my mame arcades in the same retropie build, i have read the wiki relevant sections.
In the Amiberry menu i see DragonRis USB controller and [N] it is just a generic USB game controller board with a Sanwa Joystick and 8 arcade style buttons. I went to the Amiberry GUI and changed the input to Retroarch controller for one game but on the "customised controls" menu then i get "not a valid input controller joystick" when i do that and [.] is empty and the joystick won't respond at all. When i revert back to the "DragonRis" controller the joystick and fire button work but i have the same issue of not being able to quit the game back to the emulator.
My retroarch setup is ok as the hotkey combination works for arcade mame in the same build same pi.

**Comment by midwan** [comment]
Hi @jabulonboaz 
The fact that you don't see an [R] for your controller means that Amiberry didn't find/pickup the retroarch.cfg file for it...

**Comment by midwan** [comment]
@HoraceAndTheSpider is there an easy way to find out what the filename that ES generates is?

**Comment by jabulonboaz** [comment]
@midwan thank u for looking at this and please let me know if i can do something to help trubleshoot. Btw is there a workaround perhaps a change i can do in the .cfg file u refered to above?

**Comment by HoraceAndTheSpider** [comment]
Dragonrise controller needs the latest dev beta , so I think this is fixed already.

@midwan Maybe we should push fixes to the release version.

**Comment by jabulonboaz** [comment]
Thank you both any chance to get the beta version myself?

**Comment by midwan** [comment]
@jabulonboaz 
There's a glitch I need to fix first, and then we can push this version to the master branch.
It should be done in the next few days I hope.

**Comment by midwan** [comment]
Version 2.21 is now merged into master, please use RetroPie's "compile from source" to get it right away.

**Comment by jabulonboaz** [comment]
@midway thank you for this! "Compile from source" Is this a manu option on Retropie's GUI ? Can you please point me to a wiki or somerhing with somw instructions ?

**Comment by jabulonboaz** [comment]
@midwan do you pehaps mean "update from source"?

**Comment by midwan** [comment]
@jabulonboaz 
Yes, that's the one! Great to see that it worked for you! :)
