### ISSUE TITLE
Keyboard as joystick - Left + Up + Fire doesn't work

### ISSUE THREAD

**Issue by chucky666** [midwan/amiberry#325]
Hello,
thanks for wonderful piece software. Apart from some compatibility issues I have discovered problem controlling chaos engine through keyboard mapped as joystick. When I hold left+top arrow keys and want to shoot (alt), it won't shoot. All other arrow combination works with shooting but this one particular doesn't.

### Expected behavior
combination left+up arrow and alt will reproduce correct behavior

### Actual behavior
holding left+up arrow cause alt key press to be ignored

### Steps to reproduce the behavior
just load some game and test it.

**Comment by midwan** [comment]
@chucky666 
Thanks for reporting this, and sorry for the delay.
I'll try to recreate it and see what happens.

**Comment by midwan** [comment]
This seems to be fixed in the current beta, or at least I can no longer recreate it here.

Closing it unless we discover something wrong. :)
