### ISSUE TITLE
Joystick not recognised

### ISSUE THREAD

**Issue by quantum8** [midwan/amiberry#328]
Using version v2.18.2 on retropie 4.4 and my joystick is not fully recognised by amiberry. 

Once I select the joystick in the input tab I get the dreaded "N" for custom settings. 

 The controller is found in the controllers folder in /opt/retropie/emulators/amiberry/controllers as ShanWan PCPS3Android.cfg

I suspect it's due to the name of the device: 
"Shanwan PC/PS3/Android"

**Comment by midwan** [comment]
@quantum8 
Please try with the latest version just pushed to the repo (v2.21), it contains a few relevant bug fixes.

You'll need to compile from source, using RetroPie's scripts to get it.
