### ISSUE TITLE
Amiga Official CDTV gamws that dont work

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#329]
### Expected behavior
Game to boot

### Actual behavior
Game will not boot

### Steps to reproduce the behavior
Amiberry 2.19
Quickstart as CD32
Load either CUE or ISO

I played with quite a few Offical CDTV games most of them work these seem to have problems

Curse of RA, The (1992)(Rainbow Arts)[!].zip - **Black Screen**
Log!cal (1992)(Rainbow Arts)[!].zip - **Black Screen after Title Screen**
Power Pinball (1990)(KarmaSoft).zip - **Black Screen**
Ultimate Basketball! (1991)(Context Systems)[!].zip - **Game works but Character Graphics are missing and corrupt**

The game images are from (TOSEC 2012-04-23) ISO Commodore Sets 05 Amiga CDTV and all work with WINUAE in a windows environment.

**Comment by CypherXG** [comment]
You know that Amiberry has no CDTV Emulation?

**Comment by ransom1122** [comment]
Midwan said he implemented CDTV emulation? All other official cdtv game images work.

**Comment by CypherXG** [comment]
When he wrote this? When the Games are running then you have luck.
In Sysconfig CDTV is not active. Also you cannot activate the CDTV Ext. Rom File.

![unbenannt](https://user-images.githubusercontent.com/7895130/40573054-5f232566-60bb-11e8-898a-21429a8fe2fc.JPG)

**Comment by midwan** [comment]
CDTV support is not officially there, meaning that we've made no effort to make sure it fully works at this point.

Some titles will work anyway, but there's no guarantee. Perhaps once we have more time we can look into this, but I can't imagine it's a high priority thing...
