### ISSUE TITLE
Statusbar fixed problem

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#330]
Hi. After your Statusbar fix i get these error in the SDL1 Version.
When i start is all ok
![dsc_0003 1](https://user-images.githubusercontent.com/7895130/40583532-048cab1e-6191-11e8-9c0b-75b088feaf21.JPG)
After Picasso Screen shows up it look like this:
![dsc_0001 1](https://user-images.githubusercontent.com/7895130/40583536-14d239b2-6191-11e8-8444-91cb956321d3.JPG)
And when i open a Screen like Hires...(Sysinfo or something else it looks like this:
![dsc_0002 1](https://user-images.githubusercontent.com/7895130/40583539-2f121554-6191-11e8-880a-c456db8a773b.JPG)
When i make a reset the last Picture Bug stays there. it goes away only when i close Amiberry.

**Comment by midwan** [comment]
This is now fixed in the latest `dev`.
It will be merged into master on the next update, but you're free to test it by compiling the `dev` version in the meantime.

**Comment by CypherXG** [comment]
Is this really working?
When i overwrite my Files with these
The Statusbar shows up really big, not in the right corner. When Amiberry switches to Picasso Mode the screen goes black and that's it. Also i can not enter the Config Menü. Black Screen.

**Comment by midwan** [comment]
@CypherXG 
Damn, it looks like there's a problem with the DispmanX targets.
It works fine under SDL2 otherwise.

**Comment by midwan** [comment]
This commit fixes the segfault when opening a P96 screen while having an AGA/ECS screen opened before, and the OnScreen LEDs activated (on Dispmanx targets).
There's still the bug of showing a black screen when exiting from the GUI, if the OnScreen LEDs were active.

**Comment by CypherXG** [comment]
Only Problems.....App crash when Picasso Screen shows up.
When i enter the Config Menu and i will go back to the emulation with pressing ESC App hangs.
Also with back Button.
Are the LEDs really so big?

**Comment by midwan** [comment]
@CypherXG 
Regarding the size, what resolution are you running Linux on?
They don't look big in my environment, and I've tested both 1080p and 800x480.

**Comment by midwan** [comment]
@CypherXG 
Hopefully this last commit fixed the bug once and for all, but please test on your side as well.
I've tested SDL1 + Dispmanx and SDL2 + Dispmanx, both seem to work fine now (opening P96 screen, entering GUI and back multiple times).

**Comment by CypherXG** [comment]
Hello.
i found another bug with the Status bar.
I have a Screenblanker running with the Matrix Effekt.
[MTX Screenblanker.zip](https://github.com/midwan/amiberry/files/2109016/MTX.Screenblanker.zip)
I load this in the WBStartup folder. In the Info Information you cn change the activation Time.

So here are the Problems:
When i startup the LED Statusbar look like this:
![dsc_0025](https://user-images.githubusercontent.com/7895130/41508365-e6169122-7243-11e8-8f04-16fd652efd9c.JPG)
Entering the Picasso Mode it looks like this:
![dsc_0026](https://user-images.githubusercontent.com/7895130/41508368-f7d89d88-7243-11e8-926f-0e82bdb1b7ab.JPG)
All OK. 
My Screensize is:
![dsc_0030](https://user-images.githubusercontent.com/7895130/41508371-06d167f2-7244-11e8-8870-a0c80d047d80.JPG)
My config is 68040, JIT, Turbo, Z3 Fastmem 128MB, RTG 128MB, Chipmem 8MB.
The Rest is also ok....HD etc, 
Now when the Screensaver activates the Statusbar look like this:
![dsc_0027](https://user-images.githubusercontent.com/7895130/41508391-4d662eaa-7244-11e8-9f63-16dfcfe1f551.JPG)
I don't know what Screenmode the Saver use but you see the Statusbar looks bad.
When i move the Mouse or press a Key to deactivate the Saver the Screen goaes back in RTG Mode, but the Statusbar looks like the beginning of the Statusbar Errors before you fix that:
![dsc_0028](https://user-images.githubusercontent.com/7895130/41508400-97760e20-7244-11e8-9447-4cdf77cd13f8.JPG)
![dsc_0029](https://user-images.githubusercontent.com/7895130/41508401-99ab9002-7244-11e8-8798-55124f4d54ef.JPG)
It moves in the middle of the Screen.

I hope i can help you with this Pictures...

Regards
Markus
