### ISSUE TITLE
Games that run to fast

### ISSUE THREAD

**Issue by Fantomas13** [midwan/amiberry#333]
### Expected behavior
The Games should run slower

### Actual behavior
The Games run to fast. 
In Firepower the Tanks drive much to fast und in Ninja Mission the Ninja acts too fast.
In my mind it was slower in the past.

### Steps to reproduce the behavior
Start these Games with amiberry

Thank you
Fantomas13

**Comment by Fantomas13** [comment]
For Details:

Retropie v4.4
Amiberry v2.21


Games
NinjaMission_v1.0
Barabarian2_V1.2_PALACE_2264
Firepower_v1.0_0061

**Comment by bspinner** [comment]
Related: https://github.com/midwan/amiberry/issues/150 https://github.com/midwan/amiberry/issues/310

**Comment by Fantomas13** [comment]
Everythings OK. thank you. I compared it with youtube videos. In my mind the ran slower. But now I'm convinced they're running at right speed. 

Sorry for that.

**Comment by midwan** [comment]
@Fantomas13 
No problem, glad this is a non-issue :)
