### ISSUE TITLE
Question:  How to save V. offset settings and Resolution in a game

### ISSUE THREAD

**Issue by Fantomas13** [midwan/amiberry#334]
How to...
1. save new V. offset and save for one specific game
2. Change With and Height for specific games and save these settings

Yours
Fantomas13

**Comment by midwan** [comment]
@Fantomas13 
This is a simple matter of saving a config for the game(s) as per your preferences, then loading it when you want to run that game again.

The same way you'd do for other Amiga emulators also (e.g. WinUAE, FS-UAE).

Or did you have a problem doing that?

**Comment by midwan** [comment]
@Fantomas13 
You didn't specify which environment (distro) you're using, which type of game (adf, whdload, other?) and how you launch the game/emulator.

**Comment by Fantomas13** [comment]
I have a retropie full updated with the newest amiberry and launching it with LHA-Files

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Do we have those options available in the hostprefs.conf?

**Comment by Fantomas13** [comment]
I'm wondering. I edited my post.

It is retropie 4.4

Amiberry 2.21

LHA File (for example): 
Bubble   Bobble_V1.1_2518

**Comment by midwan** [comment]
@Fantomas13 
As mentioned in the Wiki page here: https://github.com/midwan/amiberry/wiki/WHDLoad-Auto-booting
these settings are part of the `whdload_db.xml` file, but they can also be overridden by adding a game-specific file named `*.whd`.

It's generally not recommended to change the `whdload_db.xml` file, as that will be overwritten in future updates.

**Comment by Fantomas13** [comment]
Thank you. It works
