### ISSUE TITLE
Line Doubling behaves differently per resolution

### ISSUE THREAD

**Issue by Dalai-** [midwan/amiberry#335]
When I compile the dev branch (with just default 'make' on a Pi 3, so it's using SDL1), I get a scanline effect over the screen. It doesn't happen with the master branch. Here are some pics illustrating the issue:

https://imgur.com/a/LjxqYnM

Note: this isn't a result of the Roadkill blitter fixes, it was happening before then. Those pics are from 19 days ago.

**Comment by SaucySarah** [comment]
@midwan Is this the scanlines feature that you said was coming soon ? :) It's been leaked !

**Comment by midwan** [comment]
@Dalai- 
Interestingly, I didn't notice this on a default A500 configuration, running on RPI3 and SDL1 + Dispmanx.
What configuration did you try? Did you change any of the default settings?

**Comment by midwan** [comment]
@Dalai- 
I still can't recreate this, and I tried several Quickstart Modes, as well as my saved Configs I'm always testing with.

Could you provide more details (e.g. a config file, exact steps to recreate) on how you get this?

**Comment by Dalai-** [comment]
Sure, I'll try to describe it all.

The system is a Raspberry Pi 3 Model B running Retropie updated to the latest version a couple of months ago. I have both the Amiberry dev and master branches downloaded to the Pi and I build them by typing 'make' at the shell.

I had my Amiga games setup and working using the master branch, then all I did was swap the binary for the dev one and the scanlines appeared. If I swap the binaries back, they go back to solid pixels. The emulator runs with this command line:

`./amiberry -autowhdload=/home/pi/RetroPie/roms/amiga/Alien Breed Special Edition.lha -G`

The .lha file was originally called AlienBreedSpecialEdition_v1.0_0615.lha but I renamed it so it looked good in the Attract Mode list.

I have an Alien Breed Special Edition.whd file with this in:

```
PRIMARY_CONTROL=JOYSTICK
PORT0=CD32
PORT1=CD32
```

And the AlienBreedSpecialEdition.auto-startup file generated by whdboot contains this:
```

CD "whdloadgame:AlienBreedSpecialEdition/"
WHDLOAD SLAVE="whdloadgame:AlienBreedSpecialEdition/AlienBreedSpecialEdition.Slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEDIR=AlienBreedSpecialEdition DATA="whdloadgame:AlienBreedSpecialEdition/data/"  NOREQ >"WHDLoadSave:Debugs/AlienBreedSpecialEdition.whdscript_debug"

uae-configuration SPC_QUIT 1
```

This is the resolution reported when running Amiberry:

```
root@retropie:/home/pi# tvservice -s
state 0x12000a [HDMI CEA (31) RGB lim 16:9], 1920x1080 @ 50.00Hz, progressive
```

**Comment by midwan** [comment]
@Dalai- 
Thanks, I'll see if I can recreate it using the game and config reported.
So far I haven't seen it otherwise, and I've been testing it on RetroPie and standard Raspbian Stretch.

**Comment by Dalai-** [comment]
Are you building with SDL1 or 2?

**Comment by midwan** [comment]
@Dalai- 
I've tested both, got the same (non-scanline) result...

**Comment by Dalai-** [comment]
One of the config files I forgot, hostprefs.conf:

```
CONTROLLER_1=joy1
CONTROLLER_2=joy2
;CONTROLLER_3=joy2
;CONTROLLER_4=
;CONTROLLER_MOUSE_1=joy1
;CONTROLLER_MOUSE_2=joy2
RETROARCH_QUIT=TRUE
RETROARCH_MENU=FALSE
RETROARCH_RESET=TRUE
;KEY_FOR_QUIT=page down
;KEY_FOR_MENU=PAGEUP
;DEADZONE=
STEREO_SPLIT=1
;SOUND_ON=FALSE
;ASPECT_RATIO_FIX=TRUE
;FRAMESKIP=TRUE
LINE_DOUBLING=TRUE
```

**Comment by MrGimper** [comment]
I noticed this a couple of dev releases ago but I didn't mention it as I thought that was just how it was now! Certainly only shows when line doubling is enabled from my experience.

**Comment by CypherXG** [comment]
Lol....i use the actually dev Version. SDL1
I start a simple A500 config.
Nothing special. 
Amiga Screen is 640x270
Nothing else.
The Screen look normally when i start it first time
![screenshot](https://user-images.githubusercontent.com/7895130/42183349-c1fffcec-7e41-11e8-9f7a-ec3241c8eca2.png)
After i turn on Line Doubling the screen look like
![screenshot](https://user-images.githubusercontent.com/7895130/42183379-e44cedd2-7e41-11e8-9c06-fcdc21a39cdf.png)
Here is my config:
[Amiga500-Kick13.zip](https://github.com/midwan/amiberry/files/2156611/Amiga500-Kick13.zip)

**Comment by JejeMiga** [comment]
I find the picture is better with scanlines for lower screenmodes. Would be very nice to have an option to keep that :)

**Comment by midwan** [comment]
@JejeMiga 
That's the plan.
The option is "Line Mode" and it can take a few parameters (though we'll probably only use 2: Scanlines and Line Doubling).

**Comment by JejeMiga** [comment]
That is really great news Midwan, thank you very much !

**Comment by midwan** [comment]
I was finally able to recreate this:
- Line Mode set to Double, behaves differently depending on the screen resolution.
- If the screen is a PAL HighRes (640x256), then we get Scanlines
- If the screen is a PAL HighRes Laced (640x512) then we get Double Lines

Now that the "mystery" is solved, I can fix it :)
