### ISSUE TITLE
WHDBOOTER Load default config file (.uae or other)

### ISSUE THREAD

**Issue by Marcoqwerty78** [midwan/amiberry#336]
- Amiberry 2.21
- WHDBooter with .lha
- Retropie (last update)
- Attract Mode
- USB Keyboard and Mouse

### Expected behavior

- Load game with WHDBooter with a default .uae configuration (or another way to pick a default config)

### Actual behavior

- Loading game (from Attract mode Front-end)
- Open Amiberry GUI
- Change config how i wish (Mouse, Keyboard as encoder and some remapping key for exit emulator)
- Save the new config
- Restore the game (now its ok i can control the Joy and have new Keys)

- Also if i save the gamename.uae this is not loaded next time i pick the same game.

### Steps to reproduce the behavior

- Load any game from Attract Mode

**Comment by Marcoqwerty78** [comment]
Tons of times trust me...i tried all.
PS:
- the first link point me at another "to be write" post.
- in the second link its mentioned different files (hostprefs.conf and whdload_db.xml) but not where they are located (i found different of these files in my setting)
for example (whdload_db.xml) one here /opt/retropie/configs/amiga/amiberry/whdboot/game-data and the others /opt/retropie/emulators/amiberry/whdboot-dist/game-data

**Comment by midwan** [comment]
@Marcoqwerty78 
Strange about the first link, the URL seems correct but it lands in a "new" wiki page. Must be related to the naming I guess.

anyway, if what you're looking for is controller settings, the file you should be looking for (and changing accordingly) is `whdboot/hostprefs.conf`, as mentioned in https://github.com/midwan/amiberry/wiki/WHDLoad-Auto-booting (last paragraph).

Not all emulator settings are available there, but they should be enough for what you're describing.
Don't change `whdload_db.xml`, as this contains the game-specific settings and can/will be overwritten with future updates. We're planning to make use of an online database to fetch the latest/best settings per game, which will allow for users to submit changes as well, but until that happens, this is the file that contains it.

**Comment by Marcoqwerty78** [comment]
**FIXED**
There was a my mistake, i leave a space between words inside `hostprefs.conf` because i copy this setup from a post around the web, when i paste the same of the wiki (without spaces) all goes fine.

Sorry for all the trouble!

**Comment by Enverex** [comment]
To expand on this, considering the original request itself still technically isn't fulfilled, is there any way to actually specify the default system settings for Amiberry to use as a default?

"hostprefs.conf" doesn't allow many options to be set, e.g. chipset, processor, etc. e.g. a Default.whd or Default.uae file that can be used to specify these settings, or alternatively allow them to be specified in hostprefs.conf instead?
