### ISSUE TITLE
Why does ingame-saving not work

### ISSUE THREAD

**Issue by Fantomas13** [midwan/amiberry#337]
### Expected behavior
I can save stats in game. like in PortsOfCall_v1.1_2489.lha, StreetRod, Kaiser,

### Actual behavior
Kaiser. Saving doesn't work. Saving command freezes the game.
Utopia Freezes

Ports of call: You can save, evertything is fine

StreetRod: When you save, you cannot click nothing and have to restart the game to load the saved game.
Example: https://drive.google.com/open?id=1-kp6RbcFz5V3P2-gyeSwRKnzC66RQ1Ie

### Steps to reproduce the behavior
Start these games in normally with retropie 4.4 and amiberry 2.21 and try

Greetz 
Fantomas13

**Comment by midwan** [comment]
It this when using the WHDLoad versions of those games, I assume?

**Comment by HoraceAndTheSpider** [comment]
Saving is diverted to the RetroPie Config folder .... have you checked that space for the presence of the saved files?


You have given the version of PortsOfCall but I would need the exact names/versions to check the others

**Comment by midwan** [comment]
Closing this due to no further activity - it doesn't seem to be related to the emulator anyway.
