### ISSUE TITLE
Statusbar PowerLED Filter & HD LED Bug

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#338]
Hi 
Whe you use normal Amiga Modes like Hires etc. the PowerLED Filter LED and the HD LED works perfectly.
When you enter Picasso Mode the Red Powerled goeas to the HD LED and this is a confict.
The Version i use is SDL1 Dispmanx.
Best use a demo which shows Filter on/off or use some Tools to turn Filter on/off like Protracker etc.

**Comment by midwan** [comment]
@CypherXG 
Is this still an issue after the latest merge from `dev`?
The LEDs were updated from the latest WinUAE code, so I suspect this might not be happening anymore.

**Comment by CypherXG** [comment]
Jepp. When i compile the RPI3 SDl1 Dev Version i'll get the bug.
In the normal Amiga Screenmodes the LEDs are perfect.
If the Screen uses the Picasso Mode the PowerLED (Red one) switch the color to the HD LED.
Here you see the Screen with Picasso Mode.
The Powerled is dark blue and not red. HD looks normal.
![screenshot-picasso](https://user-images.githubusercontent.com/7895130/47815293-459f7380-dd50-11e8-80ae-db9f1af11c2b.png)
Next is Picasso Mode. HD is working and it is red. That's wrong. It must be blue and the Powerled must be red
![screenshot-hd is red](https://user-images.githubusercontent.com/7895130/47815332-64056f00-dd50-11e8-937d-5a6b148b185c.png)
This is a Screenshot with the normal Amiga Screenmodes without Picasso.
All colors and Led's are correct.
![screenshot-amiga screenmode](https://user-images.githubusercontent.com/7895130/47815386-89927880-dd50-11e8-8182-d93f29b578c7.png)

**Comment by midwan** [comment]
Note: the incorrect color on P96 modes only occurs with 32-bit screenmodes. 
16-bit ones have the correct colors.
