### ISSUE TITLE
North and South

### ISSUE THREAD

**Issue by Fantomas13** [midwan/amiberry#339]
### Expected behavior
Should start with amiberry

### Actual behavior
Black screen oder missing Disk
No Matter which version
NorthAndSouth.lha
NorthAndSouth_v1.7_Files_0194.lha
NorthAndSouth_v1.7_Files_NTSC_1780.lha
NorthAndSouth_v1.7_Image_0194.lha

no matter which config of kickstarts. with and without renaming the Files oder adding the 
kick34005.A500.RTB

### Steps to reproduce the behavior
Start normally with amiberry

**Comment by dudleydes** [comment]
I raised this issue in the Amiberry thread at the RetroPie forum. The issue has been reported upstream  but is yet to be resolved. A fix was provided in this [post](https://retropie.org.uk/forum/topic/12656/amiga-amiberry-whdload-holy-grail-amiberry-s-official-thread/223) which I can confirm will get North and South working.

**Comment by Fantomas13** [comment]
Thanks dude,

it worked fine.

**Comment by midwan** [comment]
For future reference:
I have estabilished that the problem with North & South is the same as Jaguar XJ 220 , and is a bug in the WHDLoad slave, which is not 'friendly' to the booter.

I have reported this here:

http://mantis.whdload.de/view.php?id=3880

You can probably manully fix this by changing `DATA="whdloadgame:NorthAndSouthImage/` to `DATA="whdloadgame:NorthAndSouthImage/data` on the WHDLoad execution line in the north and south autoboot file. (NorthAndSouthImage.auto-startup)

**Comment by HoraceAndTheSpider** [comment]
Fixed in latest version;

http://www.whdload.de/games/NorthAndSouth.html
