### ISSUE TITLE
Parse .uae config files from command line without the -config parameter

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#34]
Add support for parsing config (.uae) files from the command line, without specifying "-config <filename>" (or "-f <filename>").

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Do we still need this, in light of the recent improvements?

**Comment by HoraceAndTheSpider** [comment]
hmm... maybe - we could consider how we might parse various filetypes without specifying the option, but there are a lot of potential variables sadly!

**Comment by midwan** [comment]
I think we can close this, with the WHDLoad Booter function implemented?

**Comment by HoraceAndTheSpider** [comment]
Yes, but I would like to consider the default behaviour of .uae .lha and maybe even .cue files with an option specified :)

**Comment by midwan** [comment]
Closing this as it's been stale for far too long. We can revisit it if we wish.
