### ISSUE TITLE
Savestate Black Screen

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#342]
I get an black Screen in Amiberry when i try to make an savestate and i must reboot the Raspberry Pi to
start again.
Only the mousepointer is visible.

Version i use: Last dev version, SDL1 Dispmanx
recreate:

Just start an Amiga 500 with Quickstart or something else and make a savestate.

**Comment by Fantomas13** [comment]
Do you make the savestate in the game or by pressing F12 and savestate

Amiberry Version?

**Comment by midwan** [comment]
This doesn't seem to be an issue with the current `dev`, could you please test again and confirm?
