### ISSUE TITLE
Beam-racing in Amiberry?

### ISSUE THREAD

**Issue by h5n1xp** [midwan/amiberry#343]
Is it possible to add the new Beam Racing feature found in WinUAE 4.0.0 to Amiberry?

**Comment by midwan** [comment]
@h5n1xp 
Although it should be possible to do, I'm afraid it might not be worth it from a performance perspective. This method takes a toll on the CPU/GPU, which is not very noticeable on modern PCs with high-end GPUs, but we'll definitely feel it on low-powered devices like the RPI.

**Comment by h5n1xp** [comment]
Cheers for the response!

I've been reading the theory behind it, perhaps something to think about for the future (as RPi models become more powerful :) )

**Comment by midwan** [comment]
@h5n1xp 
Certainly something to look into and experiment with ;)
