### ISSUE TITLE
Amiberry PS4 Port

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#344]
With the PS4 scene blown wide open is it at all possible we can see a PS4 port of Amiberry at all?

**Comment by HoraceAndTheSpider** [comment]
I’d like to see a Ps-Vita port first ;)

**Comment by midwan** [comment]
I have neither of these devices in my disposal, so I don't think that will come from me :)

**Comment by HoraceAndTheSpider** [comment]
I have now installed fw 3.60 on my Vita, so that may become an option ;)

**Comment by ransom1122** [comment]
Nice.. if you need testers on the ps4 side I can help.

**Comment by midwan** [comment]
Closing this until it becomes relevant :)
