### ISSUE TITLE
No Games load after initial 1st successful run

### ISSUE THREAD

**Issue by Hasslehogg** [midwan/amiberry#347]
Hi guys

I Install Amiberry and setup from source, run a game (Sensi 97/98 in correct LHA format)

Next time I run it or ANY LHA game I just get a black screen. So basically I can play any game once after install then no other games even after a restart.

I have even removed the autoboot config file and debug file and it still doesnt work

zip's work fine still

seen something about different controllers, tried 2 different controllers and its the same

running retropie 4.4 on odroid xu4

thanks in advance

**Comment by CypherXG** [comment]
Kickstart Roms installed?

**Comment by Hasslehogg** [comment]
Yes, after install it plays the the 1st WHDLoad game without issues, and it also plays all disk/zip games ALL of the time.

I have copied the games and the kickstart roms from my pi, that works no problems, so I know the kickstart roms are fine.

its really weird

**Comment by CypherXG** [comment]
Did you make a Romsscan?

**Comment by Hasslehogg** [comment]
Hi CypherXG, I dont know what one of those is or how to do it. Do you mean just scan a directory for roms? if so emulation station obviously does this each time its started? The roms all show up but only zip/disk games work and no WHDLoad games after the very 1st WHDLoad game.

By th st WHDLoad game working for the very 1st time then nothing since it proves everything is in the right place, also I used successfully in my raspberry pi for months, I just want a more powerful system in the Odroid

thanks

**Comment by CypherXG** [comment]
I didn't mean the Game Roms. I mean the Kickstart Roms. 
If Amiberry don't know which Kickroms are available, the Emulator can not 
use the correct Kickrom for your games

**Comment by Hasslehogg** [comment]
Hi, amiberry must know where they are as i played the very 1st whdload game i tried and any zip disk game anytime without issues.

The problem seems to be the whdbooter which autoboots, as it works once then never again. Whereas amiberry works without issues with any disk games

**Comment by Hasslehogg** [comment]
very weird

fixed the issue kind of, i updated over the top by binary rather than source and it works, even after a restart

BUT

as i had finally gotten it to work, i took an image of it incase it ever stopped working with win32 disk imager, i then wrote it back to sd card and it doesnt work!!!!!

weird stuff

**Comment by HoraceAndTheSpider** [comment]
sounds like you might have some memory card corruption in that case?

**Comment by SaucySarah** [comment]
I have encountered something similar. I forgot what button it was to reset the boot sequence so I held down 'Space' and all I got from then on was a black screen.

**Comment by midwan** [comment]
@Hasslehogg 
Have you tested another SD Card? Like @HoraceAndTheSpider mentioned, this sounds suspicious, perhaps the SDcard is faulty or misbehaving from time to time?

**Comment by Hasslehogg** [comment]
Guys, resolved. Somehow after writing the image i took to another sd card, the symlinks to the roms had turned red even though they were untouched. Deleted the red links, restarted and now back but green, all working. Weird but thanks for the help

**Comment by midwan** [comment]
@Hasslehogg Awesome, great to see that it worked in the end! ;-)

Closing this then.
