### ISSUE TITLE
[Request] Add '4:3' option (as well as 'Correct Aspect Ratio')

### ISSUE THREAD

**Issue by SaucySarah** [midwan/amiberry#349]
I would like to use the original Amiga resolution in WHDLoad (or as close as Amiberry allows, 640x256). So currently we are forced to use the resolutions that Horace has set in the "database". If I turn on 'Correct Aspect Ratio' then most of the games lower the Amiga resolution to something like 640x216 to fill up the screen but sometimes parts can't be seen because they are off screen (bad offset settings) and end up just looking like the low res Atari ST !. If I turn off 'Correct Aspect Ratio' then it stretches everything to Widescreen which looks stupid and it also stretches them vertically to fill the screen which ends up with the wrong looking aspect ratio. 

@midwan Could you add a '4:3' option as well as the 'Correct Aspect Ratio' option please ?. If we have both options turned on and the horizontal Amiga resolution is 640 (PAL) then it will default to 640x256. Horace can then add the option to his 'hostprefs' file.

Thanks.

**Comment by midwan** [comment]
@SaucySarah 
The "Correct Aspect Ratio" option will keep 4:3 (assuming that's the resolution you use), and disabling that will fill the screen, stretching and distorting the image (hey, some people prefer that).

Besides this option, you have control over the horizontal and vertical sizes, so if you want 256 pixels in height, you can control that with the relevant slider. 

Correct Aspect Ratio does NOT change resolution, only fills the screen differently (either by keeping the aspect ratio or not).

**Comment by SaucySarah** [comment]
I meant to say for the WHDLoad side of things. Horace is setting custom resolutions like 640x216 in lots of games to fill the screen (lowering the original resolution). I would like it 4:3 but not stretched (640x256 keeping the black bars). If you turn off 'Correct Aspect' in a game he has set as 640x216 then it stretches it widscreen and it also stretches it vertically obscuring the aspect. If I turn on 'Correct Aspect' then it also fills the Widescreen but at the correct aspect.

**Comment by midwan** [comment]
@SaucySarah 
I don't see how this requires for a new emulator option, as it's still a configuration option that is already available (vertical size).

For now, the settings for each WHDLoad title come from presets, but you can still modify them according to what you prefer. We tried to take into account what most people would like, but of course that can't cover everyone's wishes.

The plan for the future is to have an online WHDLoad database for those settings, which can be easily updated and managed.

**Comment by SaucySarah** [comment]
That's my point. You would have to set them all manually. Because he has lowered most of the resolutions to 640x216 and 640x240 to fill the screen and look like an Atari ST, you can't have 4:3 aspect (with black bars).

Or if he could add a user custom resolution in the hostprefs file that would overide the 'forced' presets would also be a good option.

**Comment by HoraceAndTheSpider** [comment]
I will add a “fixed” height override value into hostprefs.

The actual aspect ratio option is already included in hostprefs.

FYI the current sizes are from user feedback/preference and not set by myself, but most users seem to prefer the screen filled and use the aspect ratio option depending on whether they deem black bars (on the sides) acceptable.

You always have the option to specify an alternative and save a .uae Config for the game which takes precedence.

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Do you need this issue open until you implement your improvements, or do you have it already in a separate list?

**Comment by GeorgeSpiggott** [comment]
I've been experimenting with full screen. How do I get NTSC sized (320x200) games to fill the whole screen (16:9 modern TV). I'm not really bothered if that distorts the aspect ratio or not. 

Thanks

**Comment by HoraceAndTheSpider** [comment]
This is covered by a new feature in `hostprefs.conf` called `FIXED_HEIGHT=`

**Comment by GeorgeSpiggott** [comment]
Thanks. What are the parameters for FIXED_HEIGHT=? Is it implemented on the current version?

**Comment by HoraceAndTheSpider** [comment]
`FIXED_HEIGHT=270` or any valid height value.

It’s on the “Horace” branch here of can can pull and compile that.

**Comment by 2play** [comment]
Hi @HoraceAndTheSpider Hi @midwan 
I have the pi3b dispmanx compiled and works great with lha cue etc as Ive posted on other issue.

I was reading on the above hostprefs.conf and the FIXED_HEIGHT=
I can find these entries in the official release or horace branch or in dev hats

Would an entry FIXED_WIDTH=320 will work?
I d like to force test 320x256

If i change the res in Amiberry settings and save as new configuration game starts in the  middle squeezed.

Any pointers will be very much appreciated.
