### ISSUE TITLE
Pinball dreams & Fantasies 

### ISSUE THREAD

**Issue by KerbiePlays** [midwan/amiberry#352]
### Expected behavior
should behave without black background and missing objects

### Actual behavior
Missing Background and graphics

### Steps to reproduce the behavior
Just loading with default settings in amiberry

**Comment by Luikuri** [comment]
Similar(?) blacked out graphics in both Street Rod games. Just load with default settings and check the garage. There have been other games with this issue as well, just don't remember them all now.

**Comment by KerbiePlays** [comment]
After looking into it a bit further think its an Amiberry issue as the games do it no matter what settings you use supercars II has the same issue and on .ADF versions too

**Comment by midwan** [comment]
@Luikuri 
I assume you're referring to the `dev` branch version?

**Comment by Luikuri** [comment]
Updated via Retropie source. Sorry, should have mentioned.

**Comment by KerbiePlays** [comment]
No change on mine still doing the same after updating the source

**Comment by Luikuri** [comment]
Aaaargh! My bad! Sorry everyone. Somehow I screwed up the installation and it had in fact reverted back to 2.18.... So no, the graphics are still black in 2.21, which is the latest Retropie-updating version. Sorry again.

**Comment by KerbiePlays** [comment]
No worries thanks for the update

**Comment by midwan** [comment]
I believe this is now fixed with 7a130954dfad5b5647a262f371027ca0a2f6b188
You'll need to compile the latest version from source (master branch) to get the fix, until a new binary is released.
