### ISSUE TITLE
[Bug] Games playing at low speed

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#356]
### Expected behavior
Games to run at full speed.

### Actual behavior
Slow downs or slower speed than usual encountered for the following games. Many different settings tested (FastCopper on/off, Blitter, CPU etc) but no luck.

### Steps to reproduce the behavior
[JimPower_v1.1_0068] => launch game then wait for the title screen. You'll be able to hear the music plays at slower pace and screen animation also suffer slow downs.
[Nicky2_v1.1] => same as above. Music/gameplay lower speed than expected.
[Nitro Boost Challenge #348] => not tested by myself just refering to that similar issue.

**Comment by midwan** [comment]
@nemo93 
The Jim Power issue is known, and it's related to some funky sprite handling it does on the title screen.
This is handled separately already here: #58
