### ISSUE TITLE
[Fix] Barbarian Palace - once again!

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#357]
### Expected behavior
To be able to launch the game.

### Actual behavior
Without changing anything to the Amiberry settings if you try launching Barbarian you'll end up straight into the Menu. Making the game unplayable obviously!

### Steps to reproduce the behavior
Just launch Barbarian_v1.1_Palace_1784. 

### Fix
I found out that by amending the whdload_db.xml file this way everything went back to normal:

```
<game filename="Barbarian_v1.1_Palace_1784"  sha1="94b1935ab9ad803fe1def5b56c7d0adf3ffe25cd">		
<name>Barbarian Palace</name>
		<slave_count>1</slave_count>
		<slave_default>BarbarianPalace.Slave</slave_default>
		<hardware>
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
CPU=68020
CPU_COMPATIBLE=FALSE
JIT=FALSE
SCREEN_HEIGHT=200
		</hardware>
		<custom_controls>
		</custom_controls>
</game>
```

**Comment by OddyOh** [comment]
@nemo93 Thanks for this, got it working. It feels like it is running too fast, but I don't remember. Anyway thanks for sharing your fix!

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Maybe we can update the XML database with the settings above?

**Comment by HoraceAndTheSpider** [comment]
the XML above is out of date - it *should* go to the 68000 to get the speed right, but this will only work with the new booter. I'm testing this at the moment.

**Comment by HoraceAndTheSpider** [comment]
Fixed with booter update - see #424

**Comment by HoraceAndTheSpider** [comment]
https://youtu.be/fVjSod3j1hk

**Comment by nemo93** [comment]
Thank you! Another one that get fixed :)
