### ISSUE TITLE
[Bug] Dungeon Master

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#358]
### Expected behavior
For game to launch

### Actual behavior
Black screen. From the **DungeonMaster.whdscript_debug** 

```
Error XpkUnpack on file "disk.2"
'Can't find required XPK library'
You need to install 'xpkSQSH.library' into LIBS:compressors!
File "Disk.2" is compressed using XPK but not cached.
Detected in function 'resload_DiskLoad'.
```

### Steps to reproduce the behavior
DungeonMaster_v1.2_0833 => this games played fine in previous Amiberry releases.

**Comment by nemo93** [comment]
Can someone confirm it's WHDload-related issue? Like it seems to be the case based on #250. If so I'm really curious since when as this game works definitely on previous Amiberry!

**Comment by HoraceAndTheSpider** [comment]
the most annoying thing about this bug is that it means i have to include at *least* xpkmaster.library in the new booter package, although i hope i have a solution for this.

**Comment by Naviara** [comment]
@nemo93 - Use the disk versions, it's just one disk and it supports savegame disk in DF1: - load times are similar to WHDLoad with fastest disk speed settings.

**Comment by HoraceAndTheSpider** [comment]
This will have a manual fix in the next update, as it requires the boot-data to be assigned for LIBS only.

I will later on add an automated fix to be applied for this, and any other games that need it.

@Naviara the use of the ADF version is not a 'fix' to the problem here ;) but a work-around only.

**Comment by HoraceAndTheSpider** [comment]
https://youtu.be/4bG0SAGDJkk

**Comment by nemo93** [comment]
Simply awesome. I was far to imagine that such bug would give you so much work! I don't know nothing unfortunately about the booter and how to properly manipulate the "startup" files as you demonstrate in your video. I thank you for all this, really. Let me know if I should go ahead and close that one off? Or test something else. You tell me.

**Comment by HoraceAndTheSpider** [comment]
I've actually automated the fix shown in the video in the latest HATS changes :)

**Comment by HoraceAndTheSpider** [comment]
This is the only game (currently) marked in the XML as needing extra libraries, but if any other come up, they are now easy to fix.

**Comment by HoraceAndTheSpider** [comment]
@midwan in encountering this issue again - can we check on the implementation of LIBS: again with the Whd booter please.

i have checked and the xpk library is in the zip so I assume the libs: ADD assign may be missing in the current startup sequence generation

**Comment by HoraceAndTheSpider** [comment]
Update- there is no LIBS folder in the tmp/Amiberry - I can’t recall if we move the files when required or just `assign Add Libs: dh3:Libs/ `

**Comment by midwan** [comment]
@HoraceAndTheSpider 
There is this related section, when generating the startup-sequence:
```
if (whdload_prefs.slave_libraries)
{
	whd_bootscript << "DH3:C/Assign LIBS: DH3:LIBS/ ADD\n";
}
```

Does the game you selected have `slave_libraries` set?
