### ISSUE TITLE
[Bug] Benefactor

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#359]
### Expected behavior
For game to launch

### Actual behavior
Black screen. There was something in the whdscript.debug file but I deleted it :( 

### Steps to reproduce the behavior
Benefactor_v1.1_0636 => this games played fine in previous Amiberry. The CD32 version plays fine with 2.21 however.

**Comment by CypherXG** [comment]
Is it not better to fix other problems from the emulator than game fixes?
There are a lot of issues...
If theese are done the Games can be fixed....

**Comment by midwan** [comment]
@nemo93 
Which version of Amiberry did you test this on?
Is it still happening with the latest from `master` ?

**Comment by nemo93** [comment]
@midwan 
Benefactor_v1.1_0636 is now working flawlessly with the latest master (2.24 as of writing). Awesome!
