### ISSUE TITLE
Controllers in hostpref.conf

### ISSUE THREAD

**Issue by poing77** [midwan/amiberry#360]
Hi,
I'm trying to setup Amiberry (v2.18.2) whdload with a x360 wired controller, on a Retropie 4.4.2 platform (Raspberry PI 3 B+).
The controller works fine in ES and other emus, as well as if i manually set it in the Amiberry GUI after Amiberry started. But if I try to set it in the **hostprefs.conf**, Amiberry seems to ignore it, and boots with no controllers at all ("none" everywhere in the input tab).
Here is my hostpref.conf:

_CONTROLLER_1=joy1
CONTROLLER_2=joy2
;CONTROLLER_3=
;CONTROLLER_4=
CONTROLLER_MOUSE_1=joy1
CONTROLLER_MOUSE_2=joy2
;RETROARCH_QUIT=TRUE
;RETROARCH_MENU=TRUE
;RETROARCH_RESET=TRUE
KEY_FOR_QUIT=F12
KEY_FOR_MENU=F11
;DEADZONE=
STEREO_SPLIT=1
;SOUND_ON=FALSE
ASPECT_RATIO_FIX=FALSE
;FRAMESKIP=TRUE_

I tried several times to change the **CONTROLLER** lines using different combinations, but nothing changed. Neither the **joy0** (which should set keyboard as a joystick, if I'm not wrong) seems to work.

Another issue I noticed is that the lines 

_KEY_FOR_QUIT=F12 
KEY_FOR_MENU=F11_

do not actually set **F12** and **F11** as the quit and menu keys, but if I change them with simple characters (ie **Q** and **M**), it works.

The line

_ASPECT_RATIO_FIX=FALSE_

instead seems to work correctly.

In the end, it seems that the **hostprefs.conf** file is only partially working for me. Maybe some other configuration file/method is overriding non-working lines?

Thanks in advance for your help!

**Comment by CypherXG** [comment]
There is no problem with amiberry and a x360 controller, PS3 Controller etc
works fine. Also the quit and menu keys.
Did amiberry find the retroarch.cfg? If not you got problems with your controller.
Amiberry read this config.

**Comment by poing77** [comment]
Ok.. Solved by removing/purging all Amiberry files and reinstalling it from source. Maybe something was broken. Sorry, and thanks again.
