### ISSUE TITLE
Mouse pointer does not activate correct area

### ISSUE THREAD

**Issue by mikeybyte** [midwan/amiberry#361]
### Expected behavior
Clicking on an area should activate it (amiberry control panel / setup)
### Actual behavior
Need to click above and to the left of intended area to click on required box (actually its different for each screen I've tested on - either way the mouse pointer does not click the area expected).
### Steps to reproduce the behavior
Install amiberry on pi3 using blitterstudio installer

**Comment by midwan** [comment]
@mikeybyte 
Which version did you use? There are a few provided for the Pi3:
- SDL1 + Dispmanx
- SDL2 + Dispmanx
- SDL2

Did you run it from the console directly, or under X11?

And also, what OpenGL driver option do you have enabled on the Pi? It can be one of these:
- Legacy
- Fake KMS
- Full KMS

I cannot recreate the problem in my environment, using the following (recommended) configuration:
- Pi3 with the latest updates including latest firmware
- Fake KMS driver
- Amiberry SDL2 + Dispmanx version

**Comment by mikeybyte** [comment]
Thats just it, I didnt set/change any options. I used the installer from here https://blitterstudio.com/amiberry/  "Installing the pre-configured distro (based on DietPi):", wrote the image to a card and it did the rest. Should be very easy to replicate ?

**Comment by midwan** [comment]
@mikeybyte 
Aha, OK. Then I know how to look for this problem, thanks.

It's just that the emulator can be run under various different environments, different platforms and different configurations of those platforms, which can make things tricky when trying to recreate something.

**Comment by midwan** [comment]
@mikeybyte 
This should be fixed with 752971ff4f2c5a0c4de2a47318b3553fe5ba5b44 now.
You'll need to either update from the latest sources or wait until a new binary release is out, to test this! :)
