### ISSUE TITLE
[Bug+Fix] Future Wars / Voyageurs du temps

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#362]
### Expected behavior
For the game to be playable after the 1st launch.

### Actual behavior
First launch of the game go smooth no problem. However on 2nd launch and onwards you just got a white cursor on screen.

### Steps to reproduce the behavior
Simply launch FutureWars_v4.3-B_1570.lha/VoyageursDuTemps_v4.3-B_Fr_2384.lha several times.

### Fix 
Thanks to @dudleydes on the Retropie forum ([click](https://retropie.org.uk/forum/topic/12656/amiga-amiberry-whdload-holy-grail-amiberry-s-official-thread/315#)). You could add an entry in the whdload_db.xml file as follows: 
```
<game filename="VoyageursDuTemps_v4.0_Fr_2384"  sha1="d11fd15f89751eab04a54e54d53aa7c7a7d7e073">
```

**NOTE**: According to @Apekop123 who [quote ](https://retropie.org.uk/forum/topic/12656/amiga-amiberry-whdload-holy-grail-amiberry-s-official-thread/317#) the Amiga forum this issue might not be related to the Whdload package. So this ticket.

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Have you added this already in the latest XML changes?

**Comment by HoraceAndTheSpider** [comment]
what is the actual fix here?  (the snippet only shows the first line of the XML)

The one linked appears to relate to changing the main control to the mouse

**Comment by nemo93** [comment]
Apologies for making that one unclear. In short, the newest archive for the game "4.3" comes with the aforementioned bug. To remediate you have to use an older version of this game the "4.0". I've shared the sha1 of this older archive for the FR version of the game as an example.

**Comment by HoraceAndTheSpider** [comment]
If you can send me the 4.0 archive i can add it to the XML scanner for inclusion automatically in the future.

Still curious as to why v4.3 doesnt work though?

**Comment by nemo93** [comment]
Files should be deleted within 24h:
- FR
https://file.town/download/cp6wadyia69t9k7urkv1rncck
- DE
https://file.town/download/7ql7dchezb6hq6cc100l1koax
- EN
https://file.town/download/0ib1r6qai49rx34cnjfq379cv

No idea how come this 4.3 doesn't work or to be precise does work but only at first launch! I can only point to whdload bugtracker: http://mantis.whdload.de/view.php?id=3306

Hope this helps.

**Comment by HoraceAndTheSpider** [comment]
The older versions are now included in the scanned archive. Please allow 1-2 days for these to reach the XML.  (I think the next full scan is tonight though)

Going by the BugTracker, it looks like its an issue with the data used on the 4.3 install.  Possibly one to contact RetroPlay regarding via EAB.

**Comment by HoraceAndTheSpider** [comment]
The updates XML generated this morning has these additional files.
