### ISSUE TITLE
[Bug+Fix] Worms Director's cut 12MB

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#363]
### Expected behavior
For the game to be playable.

### Actual behavior
Black screen. From the **WormsDCAGA12MB.whdscript_debug**

```
Can't allocate ExpMem.
Can't allocate ExpMem.
Can't allocate ExpMem.
Can't allocate ExpMem.
Can't allocate ExpMem.
Can't allocate ExpMem.
Can't allocate ExpMem.
Can't allocate ExpMem.
....
```

### Steps to reproduce the behavior
Simply launch WormsDirectorsCut_v1.3_AGA_12MB_0605.lha. Definitely related to the RAM set in the whdload_db.xml file as there are only 2MB Chip/4MB Z2 and I'm not familiar enough to change the correct amount.
**NOTE**: the WormsDirectorsCut_v1.3_AGA_0605 version is working fine. Just add to the whdload_db.xml file:

```
<game filename="WormsDirectorsCut_v1.3_AGA_0605"  sha1="5440fa5310dd2f99e68711532b673995569602c4">
		<name>Worms Directors Cut [AGA]</name>
		<slave_count>1</slave_count>
		<slave_default>WormsDCAGA.Slave</slave_default>
		<hardware>
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
CHIPSET=AGA
		</hardware>
		<custom_controls>

		</custom_controls>
	</game>
```

**Comment by midwan** [comment]
@HoraceAndTheSpider 
We might need to update the `whdload_db.xml` file for this one?

**Comment by nemo93** [comment]
Thanks both!
