### ISSUE TITLE
Disabling usage of controller in menus

### ISSUE THREAD

**Issue by dnlopez** [midwan/amiberry#366]
Hi - I notice that, as it says in the wiki, "The 'first' detected controller on the host system will also be able to navigate the Amiberry menus".

Is it possible to disable this behaviour? (I have my own joy-to-mouse style solution that runs in the background and is better for my purposes).

**Comment by midwan** [comment]
New option added in `amiberry.conf` for this purpose:
`gui_joystick_control=yes` (change to `no` to disable this default behavior)
