### ISSUE TITLE
Incorrect color rendering after v2.19

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#372]
**Describe the bug**
In some games, some colors are not rendered correctly. The image appears to have less colors on-screen. This started happening on versions after 2.19, which seems to be the last one that didn't have the bug.

**To Reproduce**
1. Start Super Cars 2
2. After the title music plays, press fire to proceed
3. The title screen showing the car and people, shows with less colors than it should:
![2 21](https://user-images.githubusercontent.com/3877365/47530362-a808f780-d8aa-11e8-91ca-64ce9895d4d1.jpg)

**Expected behavior**
The screen should have looked like this instead, as it appears in v2.19:
![2 19](https://user-images.githubusercontent.com/3877365/47530384-b6571380-d8aa-11e8-8bf8-a76b138fbff7.jpg)

**Comment by midwan** [comment]
v2.20 also works, so this happened between that version and v2.21

**Comment by midwan** [comment]
Looks like it was caused by something in 68a4119cf775c9ddd29e3037289870f6d52f0746

**Comment by midwan** [comment]
Update: the changes in `custom.cpp` didn't cause it, so it's probably something within the updates of `drawing.cpp`.

Now we'll have to isolate which exact lines did it, within that file.

**Comment by kevster88** [comment]
I've noticed the same bug when playing pinball dreams too
