### ISSUE TITLE
Amiberry crashing to configuration screen

### ISSUE THREAD

**Issue by KerbiePlays** [midwan/amiberry#375]
### Expected behaviour
Should be able to load WHDload games 

### Actual behaviour
Since updating to 2.24 my kickstarts don't work anymore and amiberry just crashes to configuration menu with no warning, this is not on a single game its every single .LHA file and I cannot change any settings as they do not save and Amiberry will not let me change to the default bios folder which have a copy of the amiga kickstart files.

### Steps to reproduce the behaviour
I cannot find any way to reproduce this as only seems to be happening on 2.24 now

**Comment by midwan** [comment]
@KerbiePlays 
Did you do a Rescan ROMs? That will refresh the list of ROMs found in your system, and store them in the `conf/adfdir.conf` file.

After that, does a Quickstart option work, as a test? E.g. the A500 and A1200 options from Quickstart, should pick a default appropriate ROM and be able to start-up normally.

**Comment by KerbiePlays** [comment]
I will give it a shot and report back shortly.

**Comment by midwan** [comment]
I found a problem when the game is using an A1200 config, as the WHDLoad auto-booter selects an incorrect Quickstart model (now that I've added more models in the list). I'll get that fixed right away and test some more...

**Comment by KerbiePlays** [comment]
That would make sense actually as its booting the 1.3 kickstart instead of the a1200 3.1 thanks for the help 

Tim

**Comment by midwan** [comment]
Alright, that should be fixed now. Let me know if you find anything else, I've only had time for some quick tests. :)

**Comment by KerbiePlays** [comment]
I will let you know if there is futher issues 

Tim
