### ISSUE TITLE
Black Screen Dreamweb & Pushover 2.24

### ISSUE THREAD

**Issue by KerbiePlays** [midwan/amiberry#377]
### Expected behavior
Dreamweb & Pushover should load

### Actual behavior
Dreamweb & Pushover are able to get past initially whdload boot install and then lock up and do nothing, deleted all syslinks from save data folder and re scanned bios folder and this has not worked

### Steps to reproduce the behavior
attempt to load on 2.24

**Comment by midwan** [comment]
@KerbiePlays 
Thanks for the report.
Does this happen only when using the WHDLoad version (and/or the whdbooter) or with all versions of the games?

**Comment by KerbiePlays** [comment]
Seems to be just whdloader version

**Comment by midwan** [comment]
Alright then, I'll try to recreate it and see.
Have you tried updating the WHDLoad slave? 
The latest version is here: http://www.whdload.de/games/DreamWeb.html

**Comment by KerbiePlays** [comment]
Checked Up to date 1.1 1660

**Comment by KerbiePlays** [comment]
Dreamweb now loading perfectly on 2.24 B11

**Comment by midwan** [comment]
@KerbiePlays Thanks for confirming! :)
