### ISSUE TITLE
Start .cue files from within Emulation Station

### ISSUE THREAD

**Issue by MarcoVer77** [midwan/amiberry#379]
I was looking for a way to start CD32 and CDTV bin/cue files from within Emulation Station but i couldn't get it to work. I made a default for CD32 as emulator but de .cue file doesn't start.

Only way to get CD32 now working is by going into the emlulator and select quickstart and select the .cue file or make a config file.

Is it possible to get this working in future builds so that you don't have to make .uae files for every cd image? Or is there another way to do this?

**Comment by CypherXG** [comment]
Amiberry does "not" support CDTV !!

**Comment by midwan** [comment]
@MarcoVer77 
Thanks, I'll take a look at this with future updates. It should be possible if you specify a command-line option, but then RetroPie would need to update how they call Amiberry from their end as well.

@CypherXG 
That is true now, but updates are coming and CDTV support is not very hard to implement. ;)
