### ISSUE TITLE
Distorted Audio When Using USB Audio Instead of 3.5mm Jack on RPI 3

### ISSUE THREAD

**Issue by Gemba** [midwan/amiberry#381]
**Expected behavior**:  Same (or better) audio experience with USB audio device instead of 3.5mm audio jack.

**Actual behavior**: Audio is noticable distorted when playing back audio with Amiberry.

**Steps to reproduce the behavior**

1. Play any audio from a rom with Amiberry via the 3.5mm jack (works flawless).
2. Attach and configure in ALSA an USB audio device, disable audio jack (`dtparam=audio=off` in `/boot/config.txt`)  (followed setup at: https://github.com/retropie/RetroPie-Setup/wiki/Sound-Issues#usb-audio).
2. Playback some files in console or in other emulators, works fine.
3. Now, play back the same audio (from 1.) in amiberry but now via USB Audio
4. Easily notice the distortion in audio in contrast to 3.5mm jack playback: The output is overlayed with periodic pops every few ms at constant rate.

**Configuration**

 * Amiberry 2.24b5 compiled from source (no crosscompile), SDL1
 * Rpi3B with full updated retropie 4.4 distribution
 * Quality switched-mode power supply, 5.05V, 4A max.
 * Some USB Audio device (see Audio Devices below)

**Additional information**

- Other emulators show no differences in audio if playing via USB audio device instead of 3.5 audio jack
- Moderate overclocking (to 1300 MHz CPU clock) of the rpi did not fix/reduce the distortion

**Workaround**

Reduce audio sampling from 44100 to 32000 in amiberry. Does not impact the audio quality at all but the distortion is gone.

1. Edit `sound_frequency` parameter in each `*.uae` config file.
2. And/Or to enforce sound frequency of 32000 Hz automagically with WHDLoad edit the `amiberry.sh` file. Do change the line 12 (currently), add `-s sound_frequency=32000`, save and exit. Make it read like:
```
 "$emulator" -autowhdload="$rom" -s sound_frequency=32000 -G
```

**Tested USB Audio Devices**:

- ID 0d8c:000c C-Media Electronics, Inc. Audio Adapter
- ID 040d:340a VIA Technologies, Inc.
- ID 1b3f:2008 Generalplus Technology Inc.

**Comment by CypherXG** [comment]
Mhhhh
I use the SDL1 Version too. I can switch with my Version of Amiberry direct between HDMI or audio jack.
I tried it also with an USB Audio Card/Headset ( Logitech G430/Speedlink Medusa (C-Link USB) ) and i have no issues. All sounds are very good. Also when i change the sound frequency. No issues. 
I noticed it in some forums that not all USB Audio Cards are perfect for the raspberry....
Try to search with google if there are some problems....

**Comment by midwan** [comment]
@Gemba 
Thanks for reporting this.

I have a USB audio card that I can test with, and see if I can recreate it.

**Comment by Gemba** [comment]
@midwan Thanks for paying attention very soon. I got some news.

I took a different angle on this issue the other day. It turns out that a [GPIO kernel module](https://github.com/recalbox/mk_arcade_joystick_rpi/issues/67) imposes some latency. Without the kernel module Amiberry works fine with USB Audio at `sound_frequency` set to 44100.

**Comment by midwan** [comment]
@Gemba 
Thanks for the feedback, I'll add this in the FAQ for anyone else that might come across it.
