### ISSUE TITLE
WHDLoad "DefenderOfTheCrown2" language choice not possible in WHDBooter

### ISSUE THREAD

**Issue by micv2** [midwan/amiberry#383]
Hello everyone,
I'm new here. I own Raspi 3 B + with Retropie and Amiberry v2.21. I'm very satisfied with that.
Only one problem I have .. In the WHDload game "Defender Of The Crown 2" I can no choose the German language. The game always starts in English. I have with the WHDBooter no possibility to set the options Custom1 = 0 and Custom2 = 0. I have already tried to manually edit "auto-startup", unfortunately without success. Why is there no possibility in WHDBooter to set the required values?
Please for help, the game is very important to me.
http://whdload.de/games/DefenderOfTheCrown2.html
Best regards, MiC

**Comment by HoraceAndTheSpider** [comment]
I can only think you are editing the incorrect auto-startup file, as this would be the correct way to apply this setting.

**Comment by HoraceAndTheSpider** [comment]
in the boot-data/ folder you should find a `DefenderOfTheCrown2.auto-startup` file to edit

**Comment by micv2** [comment]
Also there I tried .. no success.

CD "whdloadgame:"
WHDLOAD SLAVE="whdloadgame:DefenderOfTheCrown2CD32.slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 Config=C1:B:Custom1;C2:B:Custom2 CUSTOM1=0 CUSTOM2=0 DATA="whdloadgame:data/"  NOREQ >"whdloadgame:whdscript_debug"

uae-configuration SPC_QUIT 1

**Comment by HoraceAndTheSpider** [comment]
Your syntax is wrong.

Remove `Config=C1:B:Custom1;C2:B:Custom2 CUSTOM1=0 CUSTOM2=0 `

And insert

`CUSTOM2=X` but swap X for a number 1 to ...5? ... whatever number is correct for your language

**Comment by micv2** [comment]
no chance, it always comes in English. So whether the WHDBooter would ignore this input. On real A1200 I just have to tick CUSTOM1=0 and  CUSTOM2=0 and finish. Other entries lead immediately to the English version. It must be possible, why is the entry ignored?

**Comment by HoraceAndTheSpider** [comment]
what language are you after please

**Comment by micv2** [comment]
Hello, Germany.

**Comment by micv2** [comment]
I got this message the first time I launch Defender of the Crown 2. The picture is just an example. It says that the slave file can not be read?
![img_2395](https://user-images.githubusercontent.com/45406373/49182163-c8205080-f359-11e8-84b9-809261b12557.JPG)

**Comment by HoraceAndTheSpider** [comment]
I had to look at the WHDLoad slave source to work this out...

```
_check_language_dir:
	lea	.language_dir(pc),a1
	move.l	_custom2(pc),d1
	beq.b	.notforced
	lea	_language(pc),a0
	move.l	d1,(a0)
.notforced
	move.l	_custom1(pc),d1
	bne.b	.forced_to_english	; CUSTOM1!=0: force english
	move.l	_language(pc),D1
.forced
	cmp.b	#3,D1
	beq.b	.german
	cmp.b	#4,D1
	beq.b	.french
	cmp.b	#5,D1
	beq.b	.spanish
	cmp.b	#6,D1
	beq.b	.italian
```

basically the WHDload readme is terrible.

You need to set CUSTOM2=3 for german.  

However.... I still get an error from WHDload `DOS-Error #205 (object not found) on reading "GE".`

`DefenderOfTheCrown2_v1.1_CD32.lha` does not appear to contain the files for other languages, so you may need to contact Retroplay to ask for an install to be created with the German language files included.

**Comment by HoraceAndTheSpider** [comment]
ah, OK, i have just seen your new post. So i need the `VerteidigerDerKrone2_v1.1_CD32_De`

You can ignore the error message you are seeing (just click past it)

With that `CUSTOM2=3`  should work

**Comment by micv2** [comment]
I have tried it by hand, there is always the English version. I attach my version here. If it is not allowed, please delete.
[DefenderOfTheCrown2_v11_CD32.zip](https://github.com/midwan/amiberry/files/2626604/DefenderOfTheCrown2_v11_CD32.zip)

**Comment by HoraceAndTheSpider** [comment]
ZIP files are not supported by the native WHDLoad booter. 

Please use the file `VerteidigerDerKrone2_v1.1_CD32_De.lha` which is availale.   You will still need to edit the file `configs/amiga/amiberry/whdboot/save-data/Autoboots/VerteidigerKrone2CD32De.auto-startup` and add the necessary `CUSTOM2=3` and it should work.

**Comment by HoraceAndTheSpider** [comment]
I followed the above myself and all worked.

the final `VerteidigerKrone2CD32De.auto-startup` file reads as follows;

```
CD "whdloadgame:VerteidigerKrone2CD32De/"
WHDLOAD SLAVE="whdloadgame:VerteidigerKrone2CD32De/VerteidigerKrone2CD32De.slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEDIR=VerteidigerKrone2CD32De DATA="whdloadgame:VerteidigerKrone2CD32De/data/"  **CUSTOM2=3** NOREQ >"WHDLoadSave:Debugs/VerteidigerKrone2CD32De.whdscript_debug"

uae-configuration SPC_QUIT 1
```

**Comment by HoraceAndTheSpider** [comment]
![53cc0df4-d76b-4398-a588-d9d5837841c1](https://user-images.githubusercontent.com/567602/49184026-35ca7d80-f356-11e8-9729-993239d14772.jpeg)

**Comment by micv2** [comment]
The zip I created for here .. In RetroPie it is unpacked.
Unfortunately it does not work. CUSTOM2=3 does not change anything.
I have the "Damaso Ultimate Image" with 32GB. There have since added some games. All games work, Defender Of The Crown 2 remains in English.
The directories are a bit different for me, but I found everything.

\\RETROPIE\roms\amiga-data\_BootWHD\WHDbooter\Autoboots
\\RETROPIE\roms\amiga-data\Games_WHDLoad_CD32\DefenderOfTheCrown2CD32

It works for you, I want too .. ;-)
Remember, I'm not a professional programmer ..

**Comment by HoraceAndTheSpider** [comment]
Sorry, but you are using an unsupported method of loading the game files. If `CUSTOM2=3` is not working it is being set in the wrong location.

The UAE Config Maker is some years old now , and as the author of the original software, i have never endorsed  "Damaso Ultimate Image" to use my software on their image.... one of the reasons i have never supported images is because they become out-of-date, and lack some of the functionality as a result.  As a result, i am unable to reproduce your problem at this end. 

Please consider using the supported method for WHDLoad auto-loading, which is part of this project, and for which our online Wiki can help:

https://github.com/midwan/amiberry/wiki/Using-Amiberry-WHDBooter-with-RetroPie

This works with the publically available RetroPie image.

**Comment by HoraceAndTheSpider** [comment]
Sorry to hear that - if you do decide to reinstall from the Retropie original image (and there are hundreds of great tutorials and videos out there for this) , please feel free to let us know if you have any problems with the advice from the Wiki page.

The function you want is certainly possible, i am just not sure how we can achieve this with the Damaso setup.
