### ISSUE TITLE
SDL2: Quickstart A4000/A4000T emulation crashes when JIT is on

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#387]
**Describe the bug**
A4000/A4000T crashes if either "A4000 Motherb. slot" or "A4000 Proc. board" is set to anything but 0.

**To Reproduce**
1.Select path to roms
2. Select A4000/A4000T in quick start
3. Press Start

If you instead on the RAM screen set A4000 memory settings to zero, it works.

**Expected behavior**
It should work instead :-)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux ARM on The Rpi3 and Armbian on Tinkerboard
 - Checkout from master branch on 07.12.2018

**Comment by CypherXG** [comment]
Mhh i cannot reproduce this crash.
I select the rom, select a4000 in quickstart
Start and...sho up Kick 3.1 Boot Screen....
Testet with/without Extra A4000Ram, testet with an other Kickstart.
The only thing i can see that the Chipset is not correct. It is generic and must be A4000.
Same with A3000 Quickstart. Chipset is then A4000. That's wrong.
But with all other options i have no issues with the Quickstart.

**Comment by solskogen** [comment]
Strange. I can reproduce it on both Tinker(running armbian) and RPi3 (Arch
Linux). Did you try with the latest and greatest checkout from git?

**Comment by solskogen** [comment]
Ok, I found something. 
If I do not strip the binary, it works.

**Comment by solskogen** [comment]
I also have the same issue with Raspbian Stretch (latest image from november)

**Comment by midwan** [comment]
I managed to recreate it, but only when running Amiberry from the console using KMSDRM.
If I launch it from within X11, the problem does not occur.

**Comment by midwan** [comment]
This only seems to happen if JIT is enabled also. If we use the Quickstart option, but disable JIT before starting the emulation, it seems to work fine.

**Comment by midwan** [comment]
@solskogen 
This is getting tricky, since the same code seems to cause the problem only when running under specific conditions (SDL2 with KMSDRM and JIT). Since all the non-RPI platforms depend on SDL2, it's quite important to get this fixed - so I'm thinking if we should disable the "A4000 RAM" option altogether and instead maybe increase the maximum Z3 RAM to 256MB?

I can't think of a scenario where this would be a problem during emulation, can you?

**Comment by solskogen** [comment]
Not that I know of.

**Comment by midwan** [comment]
@solskogen 
Interestingly, I cannot recreate the problem in a fresh test I made.

I used the current sources from `master`, with both a stripped and a non-stripped binary. It was compiled on the latest Raspbian environment I had.

I run them on the latest DietPi, after setting it up for Amiberry (it installs the pre-requisites including SDL2 with KMSDRM support) and replacing the binary.

**Comment by solskogen** [comment]
Not able to reproduce on tinker either. I'm pretty sure problem is solved.
