### ISSUE TITLE
Support 2 mice simultaneously (e.g. Lemmings 2-player mode)

### ISSUE THREAD

**Issue by Babbonz** [midwan/amiberry#388]
Not an issue but a request. Is there anyway amiberry could support 2 player mouse games (lemmings, settlers) using 2 mice?
I've plugged two into my pi but can't get the second mouse to register as a second mouse? I've not currently got a pc so have no idea if this is even possible on winuae but was hoping it might be for amiberry?

**Comment by midwan** [comment]
@Babbonz 
That's not a bad idea actually, thanks for bringing it up.
I'll look into it as soon as the next stable release is ready and published, so that it can make it into an upcoming version.

**Comment by midwan** [comment]
@Babbonz 
We'll have to wait until SDL2 implements support for multiple mice for this to work: https://wiki.libsdl.org/Roadmap

**Comment by midwan** [comment]
Closing this for now, until SDL2 adds support for more than 1 mouse
