### ISSUE TITLE
CPU Speed Auto Switch

### ISSUE THREAD

**Issue by DesertBlizzard** [midwan/amiberry#389]
An option to set a specific CPU speed when running a program from within RTG mode that switches to the native chipset. 

Taking this a step further, options to not only select speed parameters, but also timing specific parameters.

**Comment by midwan** [comment]
@DesertBlizzard 
Could you please explain in more detail what you mean by specific CPU speed?

I was planning to allow for managing the balance between time spent in CPU cycles vs Chipset cycles, which is now sort of hard-coded and only has two settings (the "normal" one designed for RPI boards, and a "faster" one for more powerful ones like the Tinker board).

**Comment by DesertBlizzard** [comment]
I have my environment set up as follows:
68020/68881 "More compatible"
8MB Chip 
128MB Fast
8MB RTG
CPU Speed Turbo

When set to Turbo, the RTG environment works great (Using AmiKit X).  Super smooth movement of windows, fast loading of icons, etc.  However, when loading anything that switches to the native chipset, often those programs slow down and the audio becomes choppy.  I would assume that is why you are considering working to better balance the scheduling between CPU and Chipset.  That may work.  However, when I open a demo, Starstruck is a good example, (included with AmiKit X), the performance is dramatically improved when I F12 to the UAE GUI and switch from Turbo to Fastest CPU speed setting.  So I thought it would be a great idea to give the user the option to have UAE switch this setting to Fastest (or whatever speed) when it detects that the environment switched to Native from RTG.  If your solution works, that would create an overall better user experience, however even if it does, providing the user the ability to instruct UAE to change to a pre-determined CPU speed when switching between RTG and Native might be an interesting feature.  I agree however with your notion that perhaps there is room to improve the balance.

FWIW, I have both an RPi3+ and Tinkerboard.  I'm only testing right now on the Tinkerboard.  I need to build out the environment for RPi, but when I get the time to do this I will be able to test both worlds for you.

**Comment by midwan** [comment]
@DesertBlizzard 
I think automatically changing that CPU setting would be a bad idea. Here's a simple example:
Let's say you want to render something in Lightwave. It's not a P96 application, it runs on it's own custom screen. And you need the maximum CPU cycles you can get for that operation, while you don't care if the chipset doesn't get many cycles for accurate emulation.

That's the reason "Turbo" mode was added in the first place: prioritize CPU cycles over Chipset cycles, even at the cost of the later.

Fastest Possible on the other hand, means that the CPU should get as many cycles as it can AFTER the chipset got all it needed.

And the specific speed settings would try and approximate the real CPU speed the emulated machine had, by allocating only enough CPU cycles for that and leaving the rest.

**Comment by DesertBlizzard** [comment]
Good point!  I don’t suppose there is a way for UAE to identify running processes within the emulated environment, say Lightwave, to use your example?  And even if it could, is there a way to determine which process is the “foreground” process?  

I imagine that if this was possible it would have been already thought up by someone much smarter than I and implemented in WinUAE by now.

**Comment by midwan** [comment]
@DesertBlizzard 
No way to do that as far as I know. What is usually done is to set up "hooks" or events that the emulator will listen on, and have applications call them - that's how you can control the emulator from within the AmigaOS using special tools.

What we could do, is add a way to configure the Timing settings for CPU vs Chipset time, from within the GUI or config file. That way, at least it won't be hard-coded to a set of two possible values as it is right now (the normal setting for RPI and a "Faster" setting for faster boards).
