### ISSUE TITLE
Amiberry could not init SDL on DietPi 6.19 auto-start

### ISSUE THREAD

**Issue by symbios24** [midwan/amiberry#391]
Hello
I installed amiberry on the latest DietPi 6.19 in a Raspberry Pi3B installation ask me to set it to auto-start so i did.but after installation has finished amiberry is not starting
by doing a systemctl i see that the Amiberry service failed to start
I set in the dietpi-config in the auto-start section the normal boot for amiberry and i reboot
now i see in the Processes that dietpi diplays after has finished booting:

INFO: SDL could not initialize SDL_ Error: No available video device
Internal error; file src/osdep/amiberry_gfx.cpp, line 324
/mnt/dietpi_userdata/amiberry/run.sh: line 3: 1183 aborted ./amibbery-rpi3-sdl2-dispmanx -f conf/autostart.uae

FAILED: DietPi Process_Tool Amiberry: Affinity 0-3
FAILED: DietPi Process_Tool: An Issue Has Occurred

Any Suggestions?

**Comment by midwan** [comment]
@Fourdee 
You might want to know about this? I'll look into it as soon as I can also, just need to flash the latest DietPi version to a new card.

**Comment by symbios24** [comment]
ok thanks i`l wait

**Comment by midwan** [comment]
@symbios24 
As mentioned here also https://github.com/Fourdee/DietPi/issues/2352, both @Fourdee and I cannot recreate this so far.

**Comment by midwan** [comment]
@symbios24 
Please let me know if this happens again, if you set it up from scratch only selecting Amiberry in DietPi.
I'll close it for now, since we cannot seem to recreate it on any environment we tried, but we can reopen it if we find out more.
