### ISSUE TITLE
DOS-Error #205 (object not found) on reading "devs:kickstarts/kick34005.a500"

### ISSUE THREAD

**Issue by KerbiePlays** [midwan/amiberry#395]
**Describe the bug**

DOS-Error 205 (object not found) on reading "devs:kickstarts/kick34005.a500".

This may have been covered previously and a fix released however I am finding it a little confusing to understand and locating the process to do it. 

I have so far relinked all the kick start roms and replaced the ones I had originally to the ones in the amiga forever collection, changed the name of the kick start roms in the bios folder to their symlink name and that seemed to fix alot of issues and majority of games now load but the above happens on a lot of games still aswell.

**To Reproduce**
Steps to reproduce the behaviour: Load a game like abandoned places 2

**Result**  
Black screen after whdboot loader

**Comment by CypherXG** [comment]
Oh come on.....This is no Bug....You need the correct Kickstart in your DEVS/Kickstarts Directory....
You have the wrong Kickstart.....that's it...
P.S. If you are using Cloantos original Roms you must put also the rom.key in the directory..

That's all....
I wish you Merry Christmas

**Comment by KerbiePlays** [comment]
I never said it was a bug, I was looking for help on this not some one turning around and being like "Oh come on" that's a bit unfair but I have fixed it now.
