### ISSUE TITLE
Automatically boot

### ISSUE THREAD

**Issue by symbios24** [midwan/amiberry#399]
Hello, Happy new year
I installed workbench 3.1 to amiberry but on every boot i have to select and load the configuration and then press start to load the workbench
How can i automatically start/boot the workbench without doing this every time ??
Thanks

**Comment by midwan** [comment]
@symbios24 
The "GUI" option is located in the Misc panel of Amiberry. It's saved in the config file you create, but it can also be specified as a command-line parameter if you want (`-G`).
