### ISSUE TITLE
Textbug?

### ISSUE THREAD

**Issue by chq1976** [midwan/amiberry#401]
Is [there](https://github.com/midwan/amiberry/wiki/WHDLoad-Auto-booting) a textbug?

Wrong:
When loading a game, if an equivalent .uae config file for the game is found in the Configurations Path, this (and only this) will be used for the game's individual preferences.

Right:
When loading a game, if an equivalent .whd config file for the game is found in the Configurations Path, this (and only this) will be used for the game's individual preferences.

**Comment by HoraceAndTheSpider** [comment]
No. It is correct.

An equivalent .uae takes precedence over any whd file, which are not used anymore anyway due to the xml
