### ISSUE TITLE
Banshee_v3.3_CD32/AGA [Black Screen]

### ISSUE THREAD

**Issue by bizzar721** [midwan/amiberry#404]
**Describe the bug**
Banshee_v3.3_CD32 will go to a black screen after Amiberry logo.  
Debug log shows "This installed program requires the AGA Chip Set."  Same goes for the AGA version.

When the Amiberry logo appears, if I enter the menu and change Chipset from Full ECS to AGA, the game will load properly, albeit without controller configured.

**Comment by midwan** [comment]
@bizzar721 
All CD32 games require AGA, so the behaviour is normal in that sense.
Was this a WHDLoad installation? In that case, I assume the game was not recognised in the provided XML and didn't set the correct settings in the emulator (e.g. Full ECS instead of AGA).

@HoraceAndTheSpider are you aware of this case?

**Comment by dudleydes** [comment]
The `whdload.xml` file needs updating for v3.3 - currently it supports v3.2.

**Comment by bizzar721** [comment]
Thank you. Yes it is WHDload. I created a "game specific setting" set to AGA and it is working.  If there anything I would be able to do to help update  `whdload.xml`  just let me know!

**Comment by HoraceAndTheSpider** [comment]
AGA is automatically picked up in the file name to set the chipset (from the XML scanner) so i will check why CD32 isnt doing the same.

**Comment by HoraceAndTheSpider** [comment]
edit: detection is looking for `_CD32_` and yet this is labelled `_CD32` so i will widen the parameters for pickup

**Comment by bizzar721** [comment]
@HoraceAndTheSpider   All the other games I tried with Autoupdated WHDloader database are working great so far!   It just so has it that Banshee has been the odd man out.  
'Banshee_v3.2_CD32.lha'  loaded fine, controls mapped & all
`Banshee_v3.3_CD32.lha` now loads, but the controls are not mapped

I went to the Amiberry menu and took a picture of the `input` and `custom controls` for Banshee v3.2
In Banshee v3.3 `custom controls` matched, and `input` the only thing I had to change was Port 1 far right drop down had to change from CD32 to `Joystick`

That did not correct it. It appears to me all other settings are the same. I've been reviewing the docs but couldn't find where else a game specific setting would be.   

I am perfectly fine using v3.2 since it wasn't such a major change, but if there is something I can do to get v3.3 working for everyone else I'll spend some more time on it.

**Comment by stuffu** [comment]
Probably the stupid question of the day, but I have run into the problems. I guess they are CD32 but could be AGA as well. Anyway, WHDload games turns black screen with the "This installed program requires the AGA Chip Set." message.

I'm running 2.25, but how/where do I get an updated xml...?

**Comment by midwan** [comment]
@stuffu 
You can always download the latest XML file by going in the Paths panel, and clicking on the Download XML button.

As long as you have Amiberry v2.25 of course. :)

**Comment by stuffu** [comment]
> @stuffu
> You can always download the latest XML file by going in the Paths panel, and clicking on the Download XML button.
> 
> As long as you have Amiberry v2.25 of course. :)

Thanks for pointing it out, but that didn't work either, even removed all traces of Amiberry and reinstalled. Same thing, AGA is black screen but other work. Probably something really easy but it has bugged me for months now. Arrgh!

**Comment by ransom1122** [comment]
Has the controller issue for this game been fixed? I updated Amiberry via source and although the game works I cannot get the controls to work?

AGA version works fine but

Banshee_v3.3_CD32.lha fails with controls

**Comment by midwan** [comment]
I tested the CD32 archive, and the controls are a bit messed up (Red button behaves as a directional Right, Blue button as a directional Down).

**Comment by midwan** [comment]
However, the black screen problem is no longer there in `dev` at least, so this issue is resolved. The controller problem might be related to something external, we're not sure yet. We should handle it separately to keep it clear from this one's main subject (black screen).
