### ISSUE TITLE
change the Amiberry WHDLOAD logo 

### ISSUE THREAD

**Issue by Mangaclub** [midwan/amiberry#406]
I am trying to change the Amiberry Logo that flickers in different colors when loading whdload games but i think i am not having my right glasses on to be able to find that file. 
Can you point me there to the right path ?

**Comment by midwan** [comment]
The splash logo is an Amiga IFF file, which is contained within the `boot-data.zip` file that the WHDLoad booter uses.

Specifically, in this path: `WHDBooter/Splash/intro_000A.iff`

**Comment by HoraceAndTheSpider** [comment]
FYI you can unpack the `boot-data.zip` and then easily access all the files change as well should you want to

**Comment by Mangaclub** [comment]
thankyou, i changed it now but the logo wont change at all O.o. is it maybe hardcoded in the splashscreen exe?
