### ISSUE TITLE
Screen Bug after upate

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#407]
I use the SDL1 Version of amiberry.
After you updated the drawing routines from latest WinUAE 4.1.x sources amiberry does not show
a normal amiga screen after Picasso drivers are loaded. 
So i can not see any demo, game or any program that change the screen to highres, 
The Screen flashes 1 sec. the mouse is hidden and that's it. 
The programs are running because from some programms i know whre the quit button is and it's possible to quit the program and come bach to the picasso workbench screen.
This happens only when the Picasso driver was loaded.
You can test this simple with the screenmode programm in the prefs dir.

**Comment by CypherXG** [comment]
Another Bug found with the Screenmode.
8Bit and 16Bit mode are wrong. If selected you can it only restore if you open Amiberry Menu.
See Attached Video:
https://youtu.be/uO6MkUv7GRM

**Comment by midwan** [comment]
@CypherXG 
I cannot recreate what you showed in the video, it seems to work normally for me...

**Comment by CypherXG** [comment]
Jessie

**Comment by midwan** [comment]
that explains it then, you have older versions of the C libraries. I'll have to check if there's an easy way to make it work for those as well, but all the supported distros have moved on to Stretch anyway...

**Comment by CypherXG** [comment]
MMhh. i'll try to update my Distro

**Comment by CypherXG** [comment]
Ok. i updated my Distro without any errors
The i cleared my folder, put your master inside an compile the sdl1 version.
No errors with the compiling, but the purple screen is there. I don't know whats wrong. 
The GL Driver is legacy.

**Comment by midwan** [comment]
@CypherXG 
Have you tried with another workbench installation? You seem to be using some eye-candy stuff in your video, perhaps that is related?

Try with a standard 3.1/3.9 and see if you can recreate it there.

**Comment by CypherXG** [comment]
Ok. Done....It was not the workbench....It was the tool Screenmode. 
I didn't press use or save directly in the Screenmode Tool. I only press Test the Screenmode.
So the tool is buggy....

**Comment by CypherXG** [comment]
Mmmhhh i think it's not an Amiberry problem.
The new Version of Winuae have also the bug. Testet with the Screensaver.
![zwischenablagebild](https://user-images.githubusercontent.com/7895130/51189909-56886b80-18e1-11e9-9033-52442ef09784.jpg)
[Screensaver.zip](https://github.com/midwan/amiberry/files/2760231/Screensaver.zip)
The bug must be in the drawing.cpp. 
We had that bug in an earlier Version where the Statusline color was also purple and centered....

**Comment by midwan** [comment]
@CypherXG 
Moved to separate issue.
If you can recreate this in WinUAE, perhaps it would be best to report it upstream to Toni?
