### ISSUE TITLE
Documentation for WHDLoad_db.xml file

### ISSUE THREAD

**Issue by Shawson** [midwan/amiberry#408]
Hi- Not really a bug or feature request.  We spoke a while ago on facebook about me using the AmiBerry WHDLoad boot stuff with WinUAE and I've finally got around to writing a bit of PowerShell which managed this.  You pass it the lha file, and it extracts it to game-data, downloads and extracts the bootdata.zip if it's missing and launches the game with a stock .uae config file in WinUAE, and all works great.  

I'm now looking to get the powershell to check with WHDLoad_db.xml file to tweak the settings for each game, passing the correct settings to WinUAE.  Is there any documentation or anything really which sheds a little light on what the various sections of the xml refer to?

I'll create a GitHub repo and upload what I have so far incase it's of any use to anyone else?

**Comment by Shawson** [comment]
Currently I'm picking through /src/osdep/amiberry_whdbooter.cpp and transcribing this as best I can to powershell, mapping to the winuae equivalent setting names- most of which do seem to marry up!

**Comment by 2xtime** [comment]
I think someone beat you to it !

http://eab.abime.net/showthread.php?p=1297513
https://github.com/solarmon/WHDLoad-Game-Launcher
https://github.com/solarmon/UCG

This looks like a better version of the one that's included with Amiberry (not sure about lha support though). It works with joystick and also has a built in game selector if no slaves are found. He also has a UAE config maker. I wonder if @midwan would be interested in this guy's work to replace the slow AMOS one in Amiberry ?

**Comment by midwan** [comment]
@HoraceAndTheSpider this might interest you?

**Comment by Shawson** [comment]
I've put up what I have so far here; https://github.com/Shawson/PSWHDLoader
It's working on my arcade at the moment in as much as it will boot up a game- but missing quite a bit at the moment with regards to other settings supported by AmiBerry when using whdload

**Comment by HoraceAndTheSpider** [comment]
How can you select a game if no slave is found? Any way the existing launcher already works with joystick control including a slave selector.


Regardless of this, I will meet the OP requirement by detailing the xml format in the wiki.

Alternative launchers are of no interest since I am in the middle of a complete rewrite to move the functions onto the host machine. This is why there is now more detail in the xml and weekly scanning of RetroPlay packs

**Comment by HoraceAndTheSpider** [comment]
Please see documentation now produced to fulfil the OP request.

https://github.com/midwan/amiberry/wiki/Structure-of-the-whdload_db.xml-file
