### ISSUE TITLE
[SDL2] When changing resolutions back and forth, the screen goes black after 4 changes

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#41]
Applies only to SDL2:
When switching resolutions, e.g. from Picasso96 to PAL and back, after the 3rd change the screen goes black (i.e. on the 4th time)

**Comment by pawelomega** [comment]
Hello #Midwan. I'm back from my hard work and first what i do was a fresh compilation  of amibary. Now all works are  very good but i see small delays when i trying to compse some music with my favourite tracker i feel some delays when pressed keys.  At this time black border was fixed and i want to say You thank you. Next saturday i will back to my job so next 3 weeks i cannot write comments.

**Comment by midwan** [comment]
@pawelomega 
I'm happy to see that the problem was fixed for you, but I believe you're referring to issue #31 instead. :)
This one is related to the upcoming SDL2 port.

We can take a look at the new problem you mention, but we should really handle it as a separate issue.
