### ISSUE TITLE
RetroPie - Cannot compile capsimg.so

### ISSUE THREAD

**Issue by ChaosFrosted** [midwan/amiberry#410]
Hello! I am trying to compile the `capsimg.so` file to enable IPF support as seen here:

[https://github.com/midwan/amiberry/wiki/Enabling-IPF-support](url)

However, the instructions say to use the command `git submodule update --init` and when I try that from the `/opt/retropie/emulators/amiberry/` file, I get this response: `fatal: Not a git repository  (or any of the parent directories): .git`

I am stuck and there's no forum for me to post this issue on. Your assistance is appreciated. Thank you.

**Comment by midwan** [comment]
@ChaosFrosted 
RetroPie keeps the Amiberry binaries only in `/opt/retropie/emulators/amiberry/`, so it's not a clone of the git repository there.

You could either:
1) Clone the repository in another directory (e.g. your home directory) using `git clone https://github.com/midwan/amiberry` and then follow the instructions as normal from there. Copy the compiled file in `/opt/retropie/emulators/amiberry/` in the end.
2) Grab a pre-compiled copy from the previous release, as it hasn't changed anyway. I'll put up binaries for this release soon also.
