### ISSUE TITLE
Swap Alt and Windows keys

### ISSUE THREAD

**Issue by walkero-gr** [midwan/amiberry#412]
**Is your feature request related to a problem? Please describe.**
Some keyboard doesn't have a menu key, or these are in weird place. So it is difficult to use the Right Amiga key, especially for the shortcuts.

**Describe the solution you'd like**
It would be great if we could swap Alt keys with Win/Menu keys, so that if the user press the Right Alt key, this will behave as Right Amiga key. If he press the Left Alt key, this should behave as Left Amiga key.

**Describe alternatives you've considered**
I checked at Aminet if there is a utility that might work like the above, but couldn't find something.

**Comment by midwan** [comment]
Implemented in dev, as a global option in `amiberry.conf`.
The new option name is: `swap_win_alt_keys` and accepts a value of `yes` or `no`.
The default value is `no`.

If set to `yes` then the Reset combination can be triggered with Ctrl-LAlt-RAlt (or RMenu).

Make sure to update your `amiberry.conf` file once by Rescanning the ROMs in the Paths panel, to see the new option appear with the default value (or add it manually of course).
