### ISSUE TITLE
Kickstarts and symlink questions

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#413]
Hello guys, just got the 2.24 update and it's awesome, thanks for all the effort you have been putting into this!

I had some questions about the kickstarts :
(please note I use retropie on a rpi3) 

1) can the kickstarts be organised in a subfolder under BIOS? Eg under BIOS/amiga. I thought it was working at some point (and it is working on another sd card where I have 2.19 installed) , but after a few hours of messing with moving kickstarts around whdloader only launches the games when the ks are in BIOS. If I just launch the amiberry fronted I can see the ks in the roms drop down as long as I have set the correct path. 
It seems that the symlinks are created only if the files are in the root of BIOS. 

2) this may be related to the above (perhaps there is a problem with symlink creation).
While I was testing various Kickstarts I have, i tried using the original ones from cloanto (with the key). Pretty sure these worked at first , however whdload booter does not seem to like these anymore (no symlinks are created for these) 

Is it possible something could be going wrong with the creation of symlinks? It seems that they are 'stuck' with whatever it created at some point and only likes a few specific files i have. 
Is there a file I can delete to reset all this and start from scratch? Not very familiar with Linux, so it could well be something I am unaware of.

**Comment by midwan** [comment]
@RetroD 
1. Yes, you can certainly place the kickstart roms in any path you want. You'll need to update the path configured in the Paths panel of course, and rescan using the relevant button. 
2. I only use Amiga Forever roms here for testing, and they work normally.

Regarding your issues with the symlinks, it might be that you already have them created and they point to your rearlier path (under `BIOS`). Try deleting the symlinks manually, then let the booter recreate them for you from the correct path and it should work.

**Comment by RetroD** [comment]
Please disregard all the above, I was been a noob!
Did more research about symlinks and found how to unlink them. Once I unlinked all of them I have put my cloanto roms in a BIOS/amiga subfolder and all needed symlinks were created :)

I was thinking if the unlinking could be done when you press the 'rescan paths' button in amiberry, or maybe add a button to 'refresh' the symlinks?

PS: @midwan was typing this as you replied :)

**Comment by midwan** [comment]
Great, glad to see this one resolved! :)
