### ISSUE TITLE
Pause emulation hot key not working 

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#414]
Hello, I have assigned the pause emulation function to one of the game pad buttons in the custom controls section, but that doesn't seem to be doing anything when I am playing a game. I have tried binding other functions and they seem to work fine though. Are some of these functions not supported in amiberry?
I am running 2.24 on retropie on a rpi3

**Comment by midwan** [comment]
The pause emulation button seems to work for me, and I didn't even have to assign any special button for that. 

The default one ("Start") from RetroPie's controller mapping worked right away.
Did you try using that?

**Comment by RetroD** [comment]
Strange, yeah start doesn't do anything for me, and assigning it doesn't work either. Is that meant to work on any whdload game this way? Just tried it with IK+ and battle chess

**Comment by midwan** [comment]
I've tested it with multiple WHDLoad games, and it seems to work for me for all of them.
I'll test it again on a different machine with a different controller also, just to be sure.

**Comment by RetroD** [comment]
@midwan thanks for checking,
I have tried both with a XBOX 360 and XBOX One controller. Mapped the pause emulation function to other buttons too, just to see if it was a problem with the start button. Even tried disconnecting my keyboard, which makes no sense I know, but I have experienced more  bizarre things with computers in the past :)

I have also tried one of the quick start configs (A1200 stock) rather than going via the whdload route

**Comment by midwan** [comment]
@RetroD 
It should work now, please test and let me know if you run into anything weird :)

**Comment by RetroD** [comment]
Awesome! Do I just need to go and install from source to get it?

**Comment by midwan** [comment]
Yep!

**Comment by CypherXG** [comment]
I can not compile the SDL1 Version. Getting this Error.
![img_0444](https://user-images.githubusercontent.com/7895130/52519469-f7a5e000-2c5b-11e9-872a-78dd19d3dbcc.JPG)

**Comment by RetroD** [comment]
Hey guys, I am also having trouble installing from source via retropie setup. Says it could not successfully build amiberry because amiberry-rpi3-sdl1 was not found

**Comment by midwan** [comment]
Seems like I missed something, let me get that fixed...

**Comment by midwan** [comment]
@RetroD 
That should have fixed it, it seems to build fine here. Please test and let me know when you get a chance.

**Comment by RetroD** [comment]
Yep, tested and all working fine now!  Fix verified :)
Thanks for the quick turnaround!
