### ISSUE TITLE
Screen height and offset not being used from database file?

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#415]
Hello,
I noticed the screen height is not being set on the games from the whdload database xml (this is in version 2.24 in retropie - installed from source)
I tried uninstalling amiberry and re-installing in case I set something up wrong, but that made no difference.
I tested another installation of amiberry on my older sd card and this is working as expected.
This is v2.24b12, installed from binary (which I assume is not the latest version that is available when installing from source?)

**Comment by midwan** [comment]
The latest version currently is 2.24 (all betas were earlier builds).
I don't believe we changed anything in that area however, especially between b12 and the final 2.24.

**Comment by RetroD** [comment]
Ok, I think I found the issue!
I compared the whdload_db.xml files that I have from the 2.24b12 and 2.24 installation.
The 2.24 one (which has the problem) has a space after the last entry in the hardware sections. for example I have this:

<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		SCREEN_HEIGHT=200
		SCREEN_Y_OFFSET=8
		
</hardware>>

the xml that works is like this:

<hardware>
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
SCREEN_HEIGHT=200
SCREEN_Y_OFFSET=8
</hardware>

I substituted the 2.24 xml with the 2.24b12 and now it's working as expected :)

Could be a line ending issue when the latest xml was generated?

**Comment by HoraceAndTheSpider** [comment]
Yes Amiberry needs to be told to trim out the tab characters that are used on the new Xml.

I will take a look it @midwan doesn’t beat me to it

**Comment by RetroD** [comment]
@HoraceAndTheSpider 
Thank you. Just noticed my xml didn't paste correctly, but I think you understood what happened by your answer :)

**Comment by RetroD** [comment]
@HoraceAndTheSpider
awesome, thank you :)

**Comment by HoraceAndTheSpider** [comment]
Tested and fixed in the latest booter update today.
