### ISSUE TITLE
Refresh kickstart symlinks

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#416]
Would it be possible to add a feature in amiberry that refreshes the symlinks for the kickstart roms?
Essentially it would unlink all kickstart symlinks so that new ones could be recreated (maybe it could be something that is triggered when you hit 'rescan paths'?

Reason why I am asking is that I was doing various tests with different kickstart roms I have, and noticed symlinks were not being created anymore. Turned out that the symlinks were hidden because the files they linked to were deleted. Things got pretty messy very quickly, and after some research I learned a bit more about symlinks and how to unlink them so that I could start from scratch.

I think this could make life easier for linux noobs like me :)

**Comment by HoraceAndTheSpider** [comment]
On the latest change son my branch, the rescan paths option re-does the symlinks.

It also removes the previous ones, dead or otherwise.

This while routine also runs as part of the WHDLoad boot process, so hopefully that fixes any broken links.

**Comment by RetroD** [comment]
@HoraceAndTheSpider that's great, nice work :)
