### ISSUE TITLE
WHDLoader crashes when booting a 68000 CPU

### ISSUE THREAD

**Issue by bkg2k** [midwan/amiberry#417]
**Describe the bug**
Starting an ECS/OCS WHD using commandline option -autowdhload with the CPU set to 68000 in the game.whd make the virtual amiga crash in a lovely Guru Meditation 80000003 :)

**To Reproduce**
1. Take any ECS/OCS WHD game (say 'Adrenalynn' for exemple)
2. Delete any amiberry.conf and uaeconfig.uae to start from a 'cold' install
3. Edit an Adrenalynn.whd in whdboot/game-data with the following lines:
```;PRIMARY_CONTROL=MOUSE/JOYSTICK
;PORT0=MOUSE/JOY/CD32
;PORT1=MOUSE/JOY/CD32
;FAST_COPPER=TRUE
CPU=68000
;BLITTER=NORMAL/WAIT/IMMEDIATE
;CHIPSET=OCS/ECS/AGA
;JIT=TRUE
;CPU_COMPATIBLE=TRUE
;SCREEN_HEIGHT=216
;SCREEN_Y_OFFSET=10
;LINE_DOUBLING=TRUE
;NTSC=TRUE
;SPRITES=NONE/PLAYFIELD/SPRITES/FULL
;FAST_RAM=1/2/4/8
;Z3_RAM=16/32/64/128
;CLOCK=7/14/28/MAX
```
4. Run the emulator: amiberry -autowhdload=/path/Adrenalynn.lha
Tested on many games. It ends up in guru meditation everytime.
Changing any other settings in the .whd file has no effect. Only the CPU crashes the machine.

**Expected behavior**
The game should run!

**Additional context**
Compiled in rpi3-sdl2 for Recalbox OS.
Everything is working fine when the selected CPU >= 68020.

**Comment by HoraceAndTheSpider** [comment]
I don’t advise the use of .whd files anymore. I think now they are an undocumented “feature” that should be removed in favour of saving an equivalent .uae file.

The incompatibility with 68000 and the booter is known- Lilkeky due to a bug in the replacement Os commands, which hopefully won’t be needed with the future booter.

**Comment by bkg2k** [comment]
Being a Recalbox developer, I'm currently working on Amiberry 2.24 integration.
Actually I don't use .whd files, but it was a convenient way to explain the issue.
Obviously, setting the CPU in the .uae config produce the same bug :)

Thanks for your explanations. Until the future booter is available, I'll set an A1200 for all WHD, AGA or not.

**Comment by HoraceAndTheSpider** [comment]
This is tested as resolved wit3h any game using the 68000 option in the XML. 

Games which are not in the XML, but require the original booter (as a fallback) will still crash due to the AROS issue unfortunately.
