### ISSUE TITLE
Random controls in CD32 games

### ISSUE THREAD

**Issue by bkg2k** [midwan/amiberry#418]
**Describe the bug**
Trying to play several CD32 games. Control behavior vary from game to game and a few games are really playable.
For example, in "Super Startdust", using an XBox 360 standard pad, the A button seems to be mapped to all CD32 pad buttons. B/X/Y does nothing.
In base jumper, Y button behaves like Start.
Etc...
Each individual game seems to get it's own random mapping. However it's always the same for a given game.
Tried to add a .cfg file to remap buttons. No luck. The buttons move but it's still buggy.
Tried to add joyport0_mode=cd32joy in the uaeconfig.uae file, but still no luck.
I'm using auto-generated configuration files close to the default files generated by amiberry for a CD32 console.
Maybe am I missing something?

**To Reproduce**
1. Copy all the attached config files into amiberry's config folder.
2. Run amiberry
3. Play Super Stardust, or Street Fighter or Base Jumpers

**Expected behavior**
A/B/X/Y should behave like coloured buttons of CD32 pads.

**Additional context**
Using amiberry compiled for rpi3+sdl2 on Recalbox OS, with an autogenerated amiberry.conf, uaeconfig.conf and optionnaly an XBox 360 .cfg file. Appropriate CD32 bios and extended bios were used.
See attached configuration files.

[configs.zip](https://github.com/midwan/amiberry/files/2804764/configs.zip)

**Comment by HoraceAndTheSpider** [comment]
joyport0_mode  would be setting the mouse port.

Most games (although i think Liberation is an exception?) will need you to set `joyport1_mode=cd32joy` 

Looking at your config, you havent set the joystick port (port 1) to the CD32 mode, or your pad... so you are basically sending CD32 controls where the mouse is expected!

**Comment by bkg2k** [comment]
Thanks, it's working now.

I first tried with the A1200 config (mouse on port 0) but nothing changed. I had to add joyport1_mode=cd32joy for the pad to be fully responsive. Seems logical :)

However, that issue seems more related to the key (joymodeX_mode).
On a CD32, there is no mouse (at least out of the box, AFAIK), and on every amiga, port0 & 1 may accept joystick or mouse (Battle Squardon is playable with 2 mouses ;) ), so is mandatory mouse on port0 a limitation of the emulator itself?

**Comment by HoraceAndTheSpider** [comment]
No, nothing to do with the emulator. there are very few games that play player 1 with the joystick in port 0.

Player 2, Yes, If  the game has it, but it’s down to what hardware registers are being read by the game. 

Mice and joysticks are read in different ways, and Battle squadron would be the exception to the rule to read both in both ports. Most game code does not bother to check what device is plugged in.

And yes, as a cd32 owner myself I can tell you many of it’s games still supported the mouse, and still in port 0.... eg Diggers where the mouse was the original control from the a1200 version.

**Comment by bkg2k** [comment]
I never had the chance to get a CD32 myself, so... thanks again :)

Last question: For multi-player games with 2 CD32 pads, where was the second pad plugged?
