### ISSUE TITLE
Lionheart graphical glitches fix

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#422]
Hello guys,

Noticed Lionheart has graphical glitches when using the configuration from whdload_db.xml.
You can see that if you play the first level and look at the clouds - there is some graphical corruption.

I did some googling and seem to have found a way to fix it.
These are the settings I changed from  the defaults (if you want me to send my .uae config let me know):

CPU: 68000 - instead of 68020
ROM: 3.1(A500,A600,A2000) rev 40.63 - instead of 3.0 (A1200) rev 106
RAM Z2 Fast: 8 MB

Maybe these could be added to the next xml file?
Also, is this the best place to make these suggestions? (I may have a few more while I go through my list of games)

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Has this been added already? It's been here for a while, not sure if we should keep it open if there's nothing else to do?

**Comment by sittingduck77** [comment]
I have the same issue even with an updated XML.

**Comment by sittingduck77** [comment]
Is the XML still being updated or is that work off for now? Lionheart still hasn't been updated.

**Comment by midwan** [comment]
@sittingduck77 The XML is getting updates every few days, so it's certainly updated.
Regarding this specific change, maybe @HoraceAndTheSpider can help?

**Comment by svk77** [comment]
Enough to fix:
CPU: 68000
ROM: 2.05 (A600) rev 37.299

**Comment by AlGrenadine** [comment]
I had to set CPU =68000, chipset=ecs and speed=max to get it playable

**Comment by midwan** [comment]
Please open such tickets on the related repo: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder
