### ISSUE TITLE
Amiberry should recognize joystick reconnection

### ISSUE THREAD

**Issue by tednilsen** [midwan/amiberry#423]
Would be nice to have the joystick back "online" when the bt connection is lost and then reconnected.
In other words: if the bluetooth joystick loses connection (after idle) and I reconnect it, Amiberry are still out of reach and I have to restart Amiberry to recognize the joystick.

**Comment by midwan** [comment]
This is a dupe of #193 - closing this issue, let's keep the discussion on that one instead :)
