### ISSUE TITLE
Trolls Graphical Glitch

### ISSUE THREAD

**Issue by tukicat** [midwan/amiberry#426]
when running the AGA WHDload version of Trolls on my pi B+ graphical issue occur when starting the game, the background is all messed up but the main sprite is fine.

If you turn on NTSC and exit out of the Amiberry GUI It resolves the issue. However, if you go back into the menu and turn NTSC back off it still runs fine.

Another user reported the same issue on the Retropie forum, so it is possible there is an underlying issue

**Comment by midwan** [comment]
@tukicat 
This should now be fixed with 29fe7770ec61a26224fef6ad74dfe679b248ed53 (currently in the `dev` branch, until further tests are made)

**Comment by midwan** [comment]
The `dev` branch will be merged into `master` as soon as beta testing is complete, so we can close this issue.
