### ISSUE TITLE
Chipset Cycle Exact It Came From the Desert

### ISSUE THREAD

**Issue by Dwarfboysim** [midwan/amiberry#427]
Any update on implementing this?  HDF plays too fast, try wait for blotter it slows the game down but screen then flickers like crazy.  Could NTSC mode be an option?

**Comment by midwan** [comment]
@Dwarfboysim 
Did you try the WHDLoad version of it?

**Comment by Dwarfboysim** [comment]
Yes I did

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by midwan** [comment]
@Dwarfboysim 
Could you try with the `dev` version also? I've updated the custom chipset code there, and although it's not ready to merge into `master` yet (it's running slower, I'd like to see if I can optimise it further), it might solve your problem.

**Comment by Dwarfboysim** [comment]
Hi,
How do I try it with the dev version if you can give me instructions and what settings to set I will get it a shot?

Dwarfboysim

**Comment by midwan** [comment]
@Dwarfboysim 
Try the related wiki entry: https://github.com/midwan/amiberry/wiki/Compiling-Development-Branch

**Comment by Dwarfboysim** [comment]
Hi,

Looks complicated.  Will give it a shot when I have time got a bit on at the moment.

 

Thanks,

Dwarfboysim

 

 

Greg Eames

e-Mail: gregseames@gmail.com <mailto:gregseames@gmail.com> 

-----------------------------------------------------------

"I sit looking at this damn computer screen all day long, day in and day out, week after week, and think: Man, if I could just find the 'on' switch..."

- Zachary Good
