### ISSUE TITLE
Compile time error:  ‘ceil’ is not a member of ‘std’

### ISSUE THREAD

**Issue by johannes87** [midwan/amiberry#428]
**Describe the bug**
I get the following error when compiling: 

```
src/osdep/amiberry_gfx.cpp: In function ‘void* display_thread(void*)’:
src/osdep/amiberry_gfx.cpp:240:23: error: ‘ceil’ is not a member of ‘std’
      viewport.h = int(std::ceil(height * scale));

```

I fixed it by putting `#include <cmath>` at the beginning of amiberry_gfx.cpp

**To Reproduce**
1. Set HEAD to version 56cc2fc354c2f664084f9ef7a0c58fc6c3daaa71 from git (branch: master)
2. Compile on an Raspberry Pi 3 B+ with `make -j2 PLATFORM=rpi3`

**Expected behavior**
It compiles without error

**Comment by midwan** [comment]
@johannes87 
Are you testing this on Jessie by any chance? It compiles fine under Stretch.
