### ISSUE TITLE
default config save

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#429]
Hi. When I setting my own option in display panel in Line mode as "Double" and untick "Correct Aspect Ratio" then i doing save and when quiting and restarting again then Amiberry showing still two option as default line mode as Single and tick Correct Aspect Ratio. Other option is saved correctly but problem persist with display panel. When I load manually config from Configuration panel then display parameter is loading properlly but not when starting Amibbery from retropie.

**Comment by midwan** [comment]
@pawelomega 
What resolution are you running on Linux, before starting the emulator?
If you don't have enough vertical lines (>540) for line doubling/scanlines, that option is disabled automatically.

I'll look into the Correct Aspect Ratio one.

**Comment by pawelomega** [comment]
1280x800 in retropie. Amiberry works ok and i sad when i load default conifguration manually then all option work fine.

**Comment by midwan** [comment]
@pawelomega 
Which configuration do you save this option in?
RetroPie uses 2 "default" configs, one for A500 emulation and one for A1200. Try saving this option in those, if you're running ADF games (which then RetroPie launches using those configs), instead of WHDLoad games (in which case, Amiberry chooses the "best" settings per game using the XML database).

If you're running WHDLoad games instead, then you can use the `hostprefs.conf` file instead, to make global modifications for all games, that would override what's in the XML database we provide.

**Comment by Regaladfr** [comment]
@midwan have you find out for the "Correct aspect ratio" issue ?
i have same issue running Amiberry on retropie (PI zero).
Whatever i change and save settings on UI or configs files.

uaeconfig.uae
`config_description=UAE default configuration
config_hardware=true
config_host=true
config_version=4.1.0
amiberry.rom_path=/opt/retropie/emulators/amiberry/kickstarts/
amiberry.floppy_path=/opt/retropie/emulators/amiberry/disks/
amiberry.hardfile_path=/opt/retropie/emulators/amiberry/
amiberry.cd_path=/opt/retropie/emulators/amiberry/cd32/
; 
; *** Controller/Input Configuration
; 
joyport0=mouse
joyport0_autofire=none
joyport0_friendlyname=Mouse
joyport0_name=MOUSE0
; 
joyport1=joy1
joyport1_autofire=none
joyport1_mode=djoy
joyport1_friendlyname=Microsoft X-Box 360 pad
joyport1_name=JOY1
; 
; 
; 
input.joymouse_speed_analog=2
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=15
input.analog_joystick_offset=-1
input.mouse_speed=100
input.autofire_speed=0
kbd_lang=us
; 
; *** Host-Specific
; 
amiberry.vertical_offset=0
amiberry.hide_idle_led=0
amiberry.gfx_correct_aspect=0
amiberry.kbd_led_num=-1
amiberry.kbd_led_scr=-1
amiberry.scaling_method=-1
amiberry.use_analogue_remap=false
amiberry.use_retroarch_quit=true
amiberry.use_retroarch_menu=true
amiberry.use_retroarch_reset=false
; 
; *** Common / Paths
; 
use_gui=yes
kickstart_rom_file=$(FILE_PATH)/Kickstart v1.3 r34.5 (1987)(Commodore)(A500-A1000-A2000-CDTV)[!].rom
kickstart_ext_rom_file=
flash_file=
cart_file=
; 
; *** Floppy Drives
; 
floppy0=
floppy1=
floppy2=
floppy3=
nr_floppies=2
floppy_speed=100
; 
; *** Hard Drives
; 
; 
; *** CD / CD32
; 
cd_speed=100
; 
; *** Display / Screen Setup
; 
gfx_framerate=1
gfx_width=640
gfx_height=240
gfx_refreshrate=50
gfx_lores=true
gfx_resolution=lores
gfx_lores_mode=normal
gfx_linemode=none
gfx_fullscreen_amiga=true
gfx_fullscreen_picasso=true
ntsc=false
; 
; *** CPU options
; 
cpu_speed=real
cpu_type=68000
cpu_model=68000
cpu_compatible=true
cpu_24bit_addressing=true
fpu_no_unimplemented=true
fpu_strict=false
compfpu=false
cachesize=0
; 
; *** Memory
; 
chipmem_size=1
z3mapping=uae
fastmem_size=0
a3000mem_size=0
mbresmem_size=0
z3mem_size=0
z3mem_start=0x0
bogomem_size=2
gfxcard_hardware_vblank=false
gfxcard_hardware_sprite=false
gfxcard_multithread=false
rtg_modes=0x112
; 
; *** Chipset
; 
chipset=ocs
chipset_refreshrate=50.000000
collision_level=playfields
chipset_compatible=A500
rtc=MSM6242B
cia_todbug=true
immediate_blits=false
waiting_blits=automatic
fast_copper=false
; 
; *** Sound Options
; 
sound_output=exact
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_frequency=44100
sound_interpol=none
sound_filter=off
sound_filter_type=standard
sound_volume_cd=0
; 
; *** Misc. Options
; 
bsdsocket_emu=false
`

hostprefs.conf
`CONTROLLER_1=joy1
CONTROLLER_2=joy2
CONTROLLER_3=joy0
;CONTROLLER_4=
CONTROLLER_MOUSE_1=joy1
CONTROLLER_MOUSE_2=joy2
;RETROARCH_QUIT=TRUE
;RETROARCH_MENU=TRUE
;RETROARCH_RESET=TRUE
;KEY_FOR_QUIT=F12
;KEY_FOR_MENU=F11
;DEADZONE=
STEREO_SPLIT=1
;SOUND_ON=FALSE
;ASPECT_RATIO_FIX=FALSE
;FRAMESKIP=TRUE`

**Comment by Regaladfr** [comment]
Look to have find a way.
It still check on default on UI but uncheck on game :)
