### ISSUE TITLE
[Bug] Roadkill CD32 - flashing black screens

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#433]
**Description**
I'm using the Roadkill_v2.1b_CD32 version of the game with FMV intro. During that intro as well as select screens every few seconds flashing black screens do appear. Nothing critical just a bit annoying. Apart from that game emulation is perfect during normal gameplay.

**To Reproduce**
launch the game and watch for the intro and following select screens.

I'm using Amiberry latest master (latest commit from Feb 11th) on Retropie 4.4.8/Pi3b+. I should try with the AGA version of that game if I have time.

**Comment by HoraceAndTheSpider** [comment]
Being a cd intro this needs quite a lot to cache (the flashing is caused by direct access to uncached data) - setting Z3 ram to 32meg sorts this.

I will get this added to the XML

**Comment by HoraceAndTheSpider** [comment]
the z3 memory is now set to 64meg , so i assume this is resolved.
