### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Selig22** [midwan/amiberry#436]
Installed RetroPie 4.4 on RBP 3+ 
Installed Amiberry
Installed almost all Kick Bios
Got different roms from various sources but nothing is working.

Got files from EAB - trying to include via DH0 (prev. installed)
got .lha data - starting from emulator
everything is not working error codes - 101, 103, 10

No idea what I can try next,
what can I do?

**Comment by HoraceAndTheSpider** [comment]
What do you mean by error codes 101 etc?
Can you screenshot please.

RetroPie currently does not install some needed files we have asked for this to be fixed. 

Have you scanned your roms folder front he roms panel?

**Comment by midwan** [comment]
@Selig22 
Please provide detailed steps to recreate your problem, we cannot help without more information I'm afraid.

**Comment by AnalogHero** [comment]
Hi. Sorry to hijack but maybe this is related. Today i did a reinstall (to update) of amiberry. First problem: WHDLoad:Unknown command. Solved by copying WHDLoad from whdboot-dist to whdboot folder. 
It seesms hat boot-data.zip isnt loaded/extracted. When i try to extract it by hand creating a new folder called boot-data it also gets ignored.

**Comment by jamrom2** [comment]
Hi.  I had the same problem as this user.... and just solved it with the work-around AnalogHero just posted.  I was getting constant WHDLoad: unknown command for everything with the new build.   Seems to work good now.

**Comment by jamrom2** [comment]
I have to add as well... this new version is a big step forward as far as load time!  The games come right up without any more WHDLoad screens.  Thank you!  

BUT... if there are any Trainers... how do I gain access to them?  Persian Gulf Inferno comes to mind immediately.

**Comment by HoraceAndTheSpider** [comment]
WHDLoad should be installed by RetroPie when you install from source, but currently it is not, or at least it (incorrectly) remains is WHDLoad-dist (which is a RetroPie package, not ours)

To fix this, today we pushed a change that means the “download  xml” button (in paths panel) will check for and if needed download WHDLoad and the RTB files that are used to add compatibility.

For reference the boot-Data.zip should *not* be extracted. It functions perfectly well zipped and is now only needed for unknown LHA files and a few edge cases (Dungeon master) for providing additional library files.

We did update boot-Data.zip so hopefully updates to this file are picked up by the RetroPie install process.

**Comment by HoraceAndTheSpider** [comment]
For the record there are updates to the XML file every few days to pick up new WHDLoad releases and updates. It is recommended to regularly download the latest version.

**Comment by HoraceAndTheSpider** [comment]
Trainers (custom options) should be manually set in the game’s auto-startup file, which is in whdboot/save-data/autoboots and is generated on first load.

We will, eventually, add a WHDLoad booter panel to Amiberry that will allow you to set these from within the GuI, and setup your games, in a similar manner to the QuickStart panel.

**Comment by jamrom2** [comment]
That would be very useful.  I just looked at the file you suggested, and not having any idea how to activate the Trainers, I'm probably better off waiting for the new changes to Amiberry.

Also.. how do I make changes to the default chipset setting?  I'd like everything to run as NTSC because it fill my screen.  Presently, I set it, and I can save it as a specific game config file, but then I'd have to do that over 400 times to set every game I have.  I don't see an option for NTSC in hostprefs.conf.  Can it be set somewhere else?

**Comment by HoraceAndTheSpider** [comment]
Setting NTSC globally might stop a lot of games working, but I could add it to hostprefs. 
The games marked as NTSC should run in that mode automatically but I need to check on that

**Comment by HoraceAndTheSpider** [comment]
The WHDLoad readme for the game you want (on WHDLoad.de) will tell you what II need to set for a specific game trainer.

It’s usually something like custom1=1

**Comment by Selig22** [comment]
After 4 nights trying to get Amiberry to work I decided to start from scratch. I installed RetroPie again. So right now I cannot screenshot until I´m at the same stage back. But right now I´m working at the car so I cannot play around with RSP.

I installed RetroPie 4.4 on RBP 3+
Installed Amiberry
Installed a lot of Kick Bios
I compiled all SDL2 stuff manually (as described on your site), but I still don't know if I have to, since I do not know which video driver I use or need. I have no idea where to find out about that - but since you are in favor of SDL2 I thought it might be a good idea. 

I installed the missing common required packages, but many times the system told me that nothing was updated since the files were already existing.
I installed a different boot-data.zip in order to see the return codes - then - starting a game - I got failure return codes, 101, 103 and 10 (not at the same time).

I read that the game-files might be the problem and ones from EAB should work - but same thing - no success.

My problem: 
I (newbie) find it hard to cope with your detailed guide - since it is displayed on different pages (some pages are repeating topics partly) it is not really clear what is mandatory to install and what is not.
I would be great to have a list on one page that one can follow from the top to the end.
... and I have no idea if I need SDL1 or 2 and what is the difference and how I can find out what I need. I would like to understand this.
Another thing is what file is needed at the end. My computer unzipps some files automatically after download and then I end up with folders that I should integrate on HD0, or use the zip file - or an .lha file that needs to be pre a installed version? When I do try and error there are too many possibilities it will take forever. 

Hope you can give me a hint - but seeing your many replies I´m positive it will work.

**Comment by midwan** [comment]
@Selig22 
If you're using RetroPie, you don't have to do anything manually at all.

Just use RetroPie's menu (RetroPie-Setup) to install Amiberry from the "optional" packages, and it will take care of everything for you.

Tinkering around manually without the necessary experience, might lead you to trouble. Better leave that for later, when you've gained more experience :)

**Comment by Selig22** [comment]
Ok, fine - I started from scratch yesterday so it is almost new - but a edited boot-data.zip that shows no black screen while booting - so Amiberry is installed and I can start it from RetroPie to get to the emulator menu.

**Comment by midwan** [comment]
ok then. For Hard drives, you can either use HDF files, or normal directories - Amiberry can use both, just choose either "Hardfile" or "Directory" in the HDD panel.

For games/demo floppy images, you can use: ADF, DMS, ZIP (which contains either ADF or DMS inside) and optionally also IPF (you need to install an extra library for that).

you can also use pre-installed WHDLoad packs, which come in LHA format. RetroPie will recognize those also, and pass them to the emulator, which will then utilize a special "auto-booter" to start them up with the best settings per game.

**Comment by HoraceAndTheSpider** [comment]
FYI Boot-Data.zip Is no longer used by the majority of WHDLoad games being loaded. 

For a newbie, install RetroPie, install Amiberry from source in the RP menu, add kickstarts to the bios folder and LHA files of pre-installed games to roms/Amiga.

In theory you should be good to go from there, although the “download xml” option in the Amiberry menu is recommended

**Comment by midwan** [comment]
Aaand, don't forget to click Rescan once, after you add those Kickstart ROMs in place. ;)

**Comment by Selig22** [comment]
Done all that in the past. Do I need to install common required packages as stated on your guide?
Do I have to go via Amiberry menu or can I start directly via RetroPie if the File is shown in the Amiga menu on RetroPie?

**Comment by midwan** [comment]
The instructions in the installation guide are for people not using RetroPie, in your case everything is already handled by RetroPie and you don't have to install anything extra to get Amiberry running. You do need Kickstart ROMs (they go in the BIOS directory) and some games or demos of course (they go in the roms/amiga directory).

Once you add games/demos in the right directory in RetroPie, they will show up in EmulationStation (after a restart of that I believe) and they can be launched directly from there. 

It will launch Amiberry for you, with the selected game/demo automatically.

**Comment by Selig22** [comment]
Might it be the BIOS then? I installed about 40 Kick files. ... and always get blue screens showing Amiga screen. I disabled all floppy drives above df0. Or do I have to wait longer - but after 5min it should be loaded.

**Comment by Selig22** [comment]
What about returning rights of transferred files - is this relevant?

**Comment by HoraceAndTheSpider** [comment]
If you copy games onto a card from the pc directly , yes , you probably need to fix the rights/permissions yes.
It is better to use the samba share or SFTP transfer methods - RetroPie pages cover these - to avoid those sorts of issues.


If you are using LHA files from RetroPie, you can forget anything about DH0 etc - loading is only a few seconds

**Comment by Selig22** [comment]
Ok, I use SFTP so no issue with rights.

**Comment by Selig22** [comment]
I start a game and the AmiBerry Logo turns up, next screen gives info on three kicks found. Afterwards Info on the game is given and a file is being created. Then the screen turns black and nothing else happens anymore. Another game ends up with the blue Amiga screen and the possibility to enter commands via keyboard. Game is not being loaded further.

**Comment by HoraceAndTheSpider** [comment]
What is the name of the game file you are loading?

Compatible files will no longer show the Amiberry logo on boot. You are on the latest Amiberry , downloaded from source, yes?

**Comment by Selig22** [comment]
Yes, I downloaded all emulators from source - took all night. The file is Defender of the Crown. Some games end at a grey AROS screen.

**Comment by HoraceAndTheSpider** [comment]
Exact file name please.

If you are seeing the AROS screen then you haven’t copied/scanned the kickstarts properly

**Comment by Selig22** [comment]
DefenderOfTheCrown_v3.0b_0317.zip
After a rescan do I have to save the config somehow?

**Comment by HoraceAndTheSpider** [comment]
Zip files are not supported by the WHDLoad booter. You will need to use .lha files, which all of the RetroPlay packs are provided as. 

After “rescan roms” it should save the path on quitting Amiberry I believe

**Comment by Selig22** [comment]
DefenderOfTheCrown.lha ends up at the AROS screen

**Comment by Selig22** [comment]
Got a new file - this one works!

**Comment by HoraceAndTheSpider** [comment]
glad it works, but still you should *never* see the AROS screen if your Kickstarts are correct. 

I would suggest reading this:
https://github.com/midwan/amiberry/wiki/Kickstart-ROMs-(BIOS)

and also : 

https://github.com/midwan/amiberry/wiki/WHDLoad-Auto-booting

**Comment by HoraceAndTheSpider** [comment]
Since this is resolved, and i have tested the new system with a fresh Retropie installation successful, this issue will be closed.

I have also updated the WIKI page to note recent changes:
https://github.com/midwan/amiberry/wiki/Using-Amiberry-with-RetroPie---Installation-and-Setup

**Comment by Selig22** [comment]
Thank you for your support - this was awesome.

**Comment by zzzMarrezzz** [comment]
Thanks guys!
In addition to verifying the above (everything looked good in my installation) I had to manually select the "Main ROM File:" from the ROM tab (press F12 for access) and select the "amiga-os-310-a1200" file from /opt/retropie/emulators/amiberry/kickstarts.
Make sure to have the key.rom file in your main BIOS folder.
