### ISSUE TITLE
[WHDLoad issue] Seek and Destroy AGA - Game Controls Require Keyboard

### ISSUE THREAD

**Issue by GeorgeSpiggott** [midwan/amiberry#438]
Hi I'm not sure if this is really the place to ask this, please do delete if it is not.

Seek and Destroy AGA requires the use of a keyboard to land the helicopter (down arrow) and complete a level. Some other keys are used to swap weapons and such.

The CD32 version of this game did not require a keyboard. All the game controls were accessible through the CD32 joypad. Is there a way to map all the necessary keys to the Joypad so that the game can be played sans keyboard?

Thanks

**Comment by HoraceAndTheSpider** [comment]
You can set keyboard controls to the joypad using the Custom controls tab and save to a .uae Config file.

If you produce a set of custom options which are suitable for a retroarch like setup, please post them here and I will include them as the default in the games XML

**Comment by GeorgeSpiggott** [comment]
Will do. I took a quick look at the manuals for both games (AGA and CD32) and they have the following controls.

Weapon select - AGA: F1- F6 CD32: L + R Shoulder Buttons. (Not sure how I'm going to copy this, some fudging may be required).

Map - AGA: Space CD32: Green Button

Zoom - AGA: F9 CD32: Yellow Button

Land - AGA: Down Arrow Key CD32: Blue Button

Pause - AGA: P Key CD32: Start Button (Already implemented)

Fire - AGA: Joystick Fire CD32: Red Button  (Already implemented)

Joystick / Mouse Toggle - AGA: M Key / J Key CD32: Same? (Not sure this needs mapping to the Joypad).

Now I think about it I find it odd that they did an AGA version and a separate CD32 version. This issue may be a  Joypad configuration problem. I will investigate.

**Comment by GeorgeSpiggott** [comment]
I tried setting the joypad buttons to match the CD32 buttons and they do not respond. So I'll go the route of assigning keys to joypad buttons. I should be able to get most of the vital buttons assigned to the joypad. Alternatively I'll look around for a CD32 version of this game as a WHDLoad file.

**Comment by GeorgeSpiggott** [comment]
After a slight hitch where several of my Amiga games were not working I'm back on with this now they all boot.

Rather than fix the buttons I think the best option is to simply play the CD32 version. That may also clarify what is different about it and maybe I can come back to the WHDLoad version.

The CD32 game file is a .zip file containing a .cue file 7 .wav files and a disk image file. The file shows up in retropie and attempts to boot but comes up with a 'no bootable media found...' error is it in the wrong format? if so which format should it be in?

Thanks

**Comment by midwan** [comment]
@GeorgeSpiggott 
RetroPie will assume .zip files are ADFs and pass them as such to Amiberry, from the command line. So it will recognize the title, but it won't work if it's not a disk image.

To use the autoloader feature of Amiberry, you will need to use `.cue` or `.iso` files directly, not zipped ones.

**Comment by GeorgeSpiggott** [comment]
I shall convert it and report back.

**Comment by GeorgeSpiggott** [comment]
I unpacked the .zip file and after renaming the BIOS from kick31 to kick40060.cd32.rom in the rp-A1200 config file I've got Amiberry to boot as a CD32. However it still doesn't boot the game, or any .cue/.iso based game I try. It won't go past the Amiga insert disk screen.

**Comment by HoraceAndTheSpider** [comment]
Do you have the extended CD32 rom as well?  (The cd32 needs the 'normal' kickstart and it's own special rom)  i.e. can you set the CD32 mode 'manually' from the Kickstart menu and get to the spinning CD screen ?

Just so you know, you dont need to rename any of the BIOS/Kickstart files, the scan picks them up by CRC hashing.

**Comment by GeorgeSpiggott** [comment]
SUCCESS! Thanks Horace. I was missing the second 3D32 ROM. I've now successfully played the game with all the CD32 buttons fully mapped, including landing and swapping weapons.

The process Is less than automated. I have to load up Amiberry, switch to CD32, find the ROM and map the keys then I load the game up. My plan to automate this is to have Amiberry boot as a CD32 since WHDLoad will AFAIK automatically reset the setting when a WHDLoad game is loaded.

**Comment by HoraceAndTheSpider** [comment]
>>The process Is less than automated. I have to load up Amiberry, switch to CD32, find the ROM and map the keys then I load the game up. My plan to automate this is to have Amiberry boot as a CD32 since WHDLoad will AFAIK automatically reset the setting when a WHDLoad game is loaded.

are you using RetroPie?  Using Retropie to load the .cue file, or from command line using `autoload=gamename.cue` would automatically set CD32 pad controls and mount the CUE/BIN and set the config to a CD32 mode.

**Comment by GeorgeSpiggott** [comment]
Yes I'm using RetroPie on a Pi3B+

I just get "no bootable media" if I go in through Retropie (as I would for any WHDLoad game), even with the correct ROMs. I tried putting _CD32  on the end of the filenames but this just takes me to the 'cats eyes' bios where it tells me there is no bootable media.

Regarding differences between this and the disk version. The CD version is modified, there is a different loading screen (rotating CD instead of floppy disk) and there is no option for mouse control. This would explain why the CD32 buttons don't map to the WHDLoad floppy version.

**Comment by HoraceAndTheSpider** [comment]
the "cats eyes" mean it cant see the kickstart roms, so make sure you check the paths panel has saved the folder with all your kickstarts in it.

**Comment by GeorgeSpiggott** [comment]
I just did a full reinstall of Amiberry, no joy.

This is my amiberry file if it helps. There is an edit on the controllers line to allow me to hot button quit with an Xbox pad. 

Quickstart=1
read_config_descriptions=yes
write_logfile=no
scanlines_by_default=no
speedup_cycles_jit_pal=10000
speedup_cycles_jit_ntsc=6667
speedup_cycles_nonjit=256
speedup_timelimit_jit=-5000
speedup_timelimit_nonjit=-5000
speedup_timelimit_jit_turbo=0
speedup_timelimit_nonjit_turbo=0
path=/opt/retropie/emulators/amiberry
config_path=/opt/retropie/emulators/amiberry/conf/
controllers_path=/opt/retropie/emulators/amiberry/conf/
retroarch_config=/opt/retropie/emulators/amiberry/conf/retroarch.cfg
rom_path=/opt/retropie/emulators/amiberry/kickstarts/
ROMs=6
ROMName=KS ROM v1.3 (A500,A1000,A2000) rev 34.5 (256k) [315093-02]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick34005.A500.rom
ROMType=256
ROMName=CD32 extended ROM rev 40.60 (512k)
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick40060.CD32 Extended.rom
ROMType=1024
ROMName=CD32 KS ROM v3.1 rev 40.60 (512k)
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick40060.CD32.rom
ROMType=512
ROMName=KS ROM v3.1 (A1200) rev 40.68 (512k) [391773-01/391774-01]
ROMPath=/opt/retropie/emulators/amiberry/kickstarts/kick40068.A1200.rom
ROMType=256
ROMName=Freezer: HRTMon v2.37 (built-in)
ROMPath=:HRTMon
ROMType=524291
ROMName= AROS KS ROM (built-in) (1024k)
ROMPath=:AROS
ROMType=256
MRUDiskList=0
MRUCDList=0
