### ISSUE TITLE
[GUI] Reorganize buttons

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#439]
Reported from Facebook:

The buttons on the bottom seem to be grouped wrong. Currently:
Reset/Quit/Shutdown/Help
Restart
Start

But Start will start the emulation, and Reset will do a hard reset in the emulation

While "restart" will restart the entire emulator software... the raspberry pi software...

I would expect controls for the emulator/raspi to be grouped, and the controls for the emulation to be grouped; in order of severity; that is to say perhaps:

[ Shutdown (pi)] [Quit (pi)] [Restart (uae)]
[ Help (uae) ]
[ Reset (amiga) ] [ Start (amiga) ]

I think it would be a little more intuitive...

**Comment by BleuLlama** [comment]
(I submitted this,  just replying so i'm sure to get updates. :D)

**Comment by midwan** [comment]
I believe this looks better then:

![image](https://user-images.githubusercontent.com/3877365/64074664-92c0de80-ccae-11e9-8552-cef2f6911784.png)

**Comment by midwan** [comment]
This is now fixed in `dev`, as soon as beta testing is completed we'll be merging it to `master`.
