### ISSUE TITLE
Technological Death - problem with demo

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#44]
Please to check Technological Death demo. In scene at the Devil I see dissynchronizing scene (timer and animation)  and scene still staying. For ex. FS-UAE nad WINUAE demo playing normal.

**Comment by midwan** [comment]
@pawelomega 
I'll test this with both branches and see. In in the process of upgrading the core to the WinUAE 2.8.1 standard as a first step, with the aim of bringing it up to 3.4.0 afterwards. That should fix all compatibility problems like this.

**Comment by bspinner** [comment]
@midwan Will cycle excat emulation with that core upgrades? The lack of that is a real bummer. :(

**Comment by midwan** [comment]
@pawelomega 
Is this still an issue with the latest updates? We've improved compatibility in several places, so perhaps it's fixed (didn't have time to test it myself yet).

@bspinner 
We have made some internal tests with Cycle-Exact mode, but the Pi3 wasn't fast enough to handle it and keep at 50 FPS currently. We'll see if we can optimize it any further and make it possible...

**Comment by bspinner** [comment]
@midwan I could try and see whether it runs fluently on odroid xu4 (as soon emulation starts on xu4 again :D)

**Comment by midwan** [comment]
This seems to be fixed in the current version, or at least I didn't notice something like the original description...
