### ISSUE TITLE
Whdload games no longer launching on v2.25

### ISSUE THREAD

**Issue by RetroD** [midwan/amiberry#441]
Hello guys,

I have just updated amiberry to 2.25 (installed from bin on my rpi3).
When launching my WHDLoad games I am now getting the amigados screen with the following error messages:

WHDLoad: Unknown command
WHDLoad failed returncode 10

Is there anything I need to change to my previous setup to get the games to run again? I assume this is related to the big changes to the autobooter?

**Comment by midwan** [comment]
@RetroD 
This is a known "bug" in RetroPie's upgrade process, because it doesn't copy the new files contained in the updated `whdboot` folder (specifically, the WHDLoad binary for example).
There are two workarounds until RetroPie fixes this:

1) Use the Download XML button in the Paths Panel. This will also download any additional files missing from the `whdboot` folder for you. You need to have the device connected to the internet for this, obviously.
2) Copy the required file in there manually. You need the latest WHDLoad Amiga binary copied into the `whdboot` folder, use any means you want to do that (SSH, FTP, Samba). Just ensure that your user has permissions to read it afterwards! :)

**Comment by RetroD** [comment]
I have tried the first method, but it made no difference. I can see it's getting the latest xml in the whdboot folder, but that's about it. Actually the xml was updated when I first updated amiberry. I could tell because I stripped all the tabs in my version to get games to work for 2.24 and the new xml does have the tabs again.

If I try to update the xml again it's now saying that I already have the latest

**Comment by midwan** [comment]
@RetroD did you get Amiberry after v2.25 was announced and published in the Releases?
We added the feature of downloading the extra files then, but if you got a slightly earlier version before that, it would only get the XML. Try getting the latest from source again to make sure?

**Comment by RetroD** [comment]
@midwan 
I updated from binary, so maybe that's a slightly earlier version? I will try from source now and post the results :)

**Comment by RetroD** [comment]
ok, games are now running, but they don't seem to work correctly. I only tried 2 games so far: Agony, IK+.
Agony quits to amiga dos 1 sec once the first level starts, and IK+ runs too fast and then quits to amiga dos after a few seconds. Anything else you could suggest might be going wrong?

**Comment by midwan** [comment]
@RetroD 
Please provide the exact filenames, so we can try to recreate this?

**Comment by RetroD** [comment]
@midwan 
Sure, here they are:
IK+_v1.8_2063.lha
Agony_v2.0_0960.lha

I'll try more games in the mean time

**Comment by RetroD** [comment]
@midwan 
Tried a few more, almost all with the same issue:

GreatCourts2_v1.5_0333.lha - quits to amigados as you start playing a game)
Gods_v2.3.1_0666.lha - quits to amigados as you start playing a game
AlienBreedTowerAssault11_v1.2_2331.lha - quits to amigados as you start playing a game
Barbarian_v1.1_Palace_1784.lha - seems to randomly end the current game after playing for a few seconds - and go to the 'demonstration' mode

This ones worked fine: (played it for 1-2 mins)
Moonstone_v1.6_0360.lha
PrinceOfPersia_v3.1_1823.lha

The thing they have in common is that in order to quit to amigados (or end your current game, as in barbarian) is that it requires you to actually play a level, not just launch the game. The games UI works fine - I find it quite bizarre.

Hopefully you can reproduce the issues and find the cause

**Comment by GeorgeSpiggott** [comment]
I have this exact same problem. I have discovered that renaming files helps. e.g. try renaming AlienBreedTowerAssault11_v1.2_2331.lha to AlienBreedTowerAssault and see if that works. It does for me.

I have a thread on the Retropie forums about this.
https://retropie.org.uk/forum/topic/21541/amiberry-change-of-filename-stops-game-working/3

**Comment by HoraceAndTheSpider** [comment]
Someone who had his fault found that a reinstall from source fixed this.

What you are getting is the trigger of a WHDLoad “quit” which is usually allocated to a keyboard button. 

I will test Tower Assault but Barbarian is one of my big test games so I am not sure how I don’t have this.

I do have a fresh RetroPie install though.

**Comment by RetroD** [comment]
I just tried updating again from source like you suggested and now all these games I mentioned are working fine :)
I am still confused to why it has happened, but I guess even with computers sometimes you need to suspend your disbelief! :P 
In any case, I am happy this is all working, and thank you guys for keeping up the great work on this! Looking forward to what's coming next!

**Comment by RetroD** [comment]
@HoraceAndTheSpider 
Just a thought... do you think the issue I was having was related to the new button that downloads the xml and the whdload executable? I was wondering if perhaps the download button copied something wrong and then installing from source has fixed the issue.

Its just a very wild guess, but maybe there is  a connection there.

**Comment by sickill** [comment]
I tried to install from source but it fails with segmentation fault error, so I had to stick to 2.25 binary.

Found a way to make it work by doing this:

```
ssh pi@<retropie-ip> 
cp /opt/retropie/emulators/amiberry/whdboot-dist/WHDLoad /opt/retropie/emulators/amiberry/whdboot/
```

**Comment by midwan** [comment]
@sickill 
Thanks for the input.
This indicates that the `whdboot` directory was not updated in RetroPie, during the installation/upgrade process. And I'm not even sure why they have that `whdboot-dist` directory there at all...

This might need to be taken up with the RetroPie team directly, @HoraceAndTheSpider what do you think?

**Comment by HoraceAndTheSpider** [comment]
i'm hoping my latest fixed resolve this, but yes, RetroPie need to be aware if there are distro issues.

**Comment by midwan** [comment]
It's been a while since we had any activity in this issue - I'm not sure we can do anything else from our side, so I'm closing it for now.
We can revisit it if necessary of course.
