### ISSUE TITLE
DOS-Error #205 (object not found) on reading "OSEMU.400"

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#442]
Hi guys hope you are all well.

Game ACSYSDemo_v1.11_AGA.lha Not starting.

I recently updated to 2.25 and noticed there was a game that did not boot and give the error in subject line. The game is ACSYSDemo_v1.11_AGA.lha Is there a way to fix this.

Possible Solutions I have tried which have not worked.

1. Attach the OSEmu.400 from the ACSYSDemo_v1.11_AGA.lha into the boot-data.zip /C Folder.
2. Copy & Paste the OSEmu.400 file from the ACSYSDemo_v1.11_AGA.lha Data folder to the root folder as well.
3. Tried numerous amount of OSEmu.400 in the ACSYSDemo_v1.11_AGA.lha into the boot-data.zip /C Folder.
4. Tried replacing whdload file to latest v18.4 and an older version 16.8.
5. Attempted to edit the ACSYSDemo_v1.11_AGA.auto-startup file in folder /opt/retropie/configs/amiga/amiberry/whdboot/save-data/Autoboots Folder with this added DATA=data for the preload of the game which is required and was not present.

CD "Games:ACSYSDemoAGA"
WHDLOAD SLAVE="whdloadgame:ACSYSDemoAGA/ACSYSDemoAGA.slave" PRELOAD DATA=data NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEDIR=ACSYSDemoAGA DATA="whdloadgame:ACSYSDemoAGA/" NOREQ >"WHDLoadSaveebugs/ACSYSDemoAGA.whdscript_debug"

CD "Games:ACSYSDemoAGA"
WHDLOAD SLAVE="whdloadgame:ACSYSDemoAGA/ACSYSDemoAGA.slave" DATA="whdloadgame:ACSYSDemoAGA/data" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEDIR=ACSYSDemoAGA NOREQ >"WHDLoadSaveebugs/ACSYSDemoAGA.whdscript_debug" 

Both times this startup bypasses the error but then has an error of a DOS error again with a CD unknown command.

 Obviously you can see I have tried heaps of ways to activate this game as a lha which has failed. On the other hand, I have made a HDF of the same game and it works perfectly with a UAE config file.

Hopefully Horace has a logical answer.

**Comment by HoraceAndTheSpider** [comment]
`boot-data.zip` isnt really used from the 2.25  update onwards. 

Your startup-script appear sto be one for the older method of booting (Pre 2.25) .  it should read:

```
CD "Games:ACSYSDemoAGA"
WHDLoad SLAVE="games:ACSYSDemoAGA/ACSYSDemoAGA.slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEPATH=Saves:Savegames/ SAVEDIR="ACSYSDemoAGA"
```

(Note the use of `games:` and not `whdgame:`)

AFAIK, the OSemu.400 is usually included with the game data... 

... having checked the file, it's in the `data` folder. So like Jaguar XJ220 this slave doesnt set the data path correctly from it's slave header. You will need to add `DATA=DATA` to the WHDLoad commands, and i've just tested that this works.

**Comment by HoraceAndTheSpider** [comment]
corrected startup:

```
CD "Games:ACSYSDemoAGA"
WHDLoad SLAVE="games:ACSYSDemoAGA/ACSYSDemoAGA.slave" PRELOAD DATA=DATA NOWRITECACHE NOREQ SPLASHDELAY=0 SAVEPATH=Saves:Savegames/ SAVEDIR="ACSYSDemoAGA"
```

**Comment by ransom1122** [comment]
When I use this as my script I get

: Unknown command
 Failed returncode 10

In AmigaDOS screen?

**Comment by HoraceAndTheSpider** [comment]
There must be something before that “unknown command” ?

**Comment by HoraceAndTheSpider** [comment]
What program/editor are you editing the startup script with?

**Comment by ransom1122** [comment]
I've used Notepad & Notepad ++ same result 
The game.lha is in RetroPie/roms/aniga1200

![20190312_184848](https://user-images.githubusercontent.com/28079950/54183267-e1f43680-44f7-11e9-95d1-209063993406.jpg)
![20190312_184833](https://user-images.githubusercontent.com/28079950/54183268-e1f43680-44f7-11e9-9f67-24eba6efb559.jpg)

**Comment by HoraceAndTheSpider** [comment]
Your startup sequence is broken and I think the use of notepad on any save (even if you try to correct it) will do that

**Comment by ransom1122** [comment]
Ok I'll try. Can editing the boot-data.zip by adding latest v18.5 whdload affect Anything?

**Comment by ransom1122** [comment]
Well what do you know it works. Problem was editing the auto-startup file for the game with with notepad. Did it from host machine and immediately saw more text inside the startup sequence then when views in notepad.

DATA=data / Confirmed working now.

You do realize there are quite a few games that require DATA=data. Can this be automated somehow so when Amiberry detects data folder to add this in startup sequence?

Thanks Horace

**Comment by HoraceAndTheSpider** [comment]
If a slave requires data= to be manually set in the icon but does not have this in the slave header then the slave has been incorrectly compiled. There is a variable set in the slave header which specifies the default data path, but the installer package has used an “unknown” sub folder.

The scanner (xml builder) already makes the scan to get this needed information from the header, so this works in 99% of cases to set the data= path.

Any missing this, should be reported via mantis bugtraker for correction. North and south recently had this corrected and Jaguar XJ220 I have confirmed and registered this. 

The fault is easy to spot in the slave source and just as easy to fix.

**Comment by ransom1122** [comment]
Fair enough. Thanks for your time.

**Comment by HoraceAndTheSpider** [comment]
No problem - glad it’s working now - hopefully those missing it in the header are a minimum (originally 3, now down to 2)

**Comment by ransom1122** [comment]
Yes it is. Is there a secure way to edit these files on pc? Or is nano on the host the only way?

**Comment by midwan** [comment]
@ransom1122 
It should be possible with Notepad++, if you change the Edit->EOL Conversion setting to "Unix".

**Comment by ransom1122** [comment]
Excellent I'll keep that in mind. Great work Gents
