### ISSUE TITLE
Failing whdload Games with 2.25 update

### ISSUE THREAD

**Issue by Mangaclub** [midwan/amiberry#444]
First of all, congratulations to this outstanding update! all the whdload games are booting enormousley fast! This is really good now for the arcade machine use!
Although there are a few failing titles on whdload that simply refuse to start.
AlienBreedSpecialEdition_v1.0_0615 (object not found, CD failed returncode 20)
AlienBreedTowerAssault_v1.2_AGA_0279 (object not found, CD failed returncode 20)
JaguarXJ220_v1.5_Image_1200 (DOS ERROR #205 (object not found) on reading "Disk.1")
JurassicPark_v1.5_AGA_0836 (stuck and scrambled graphics by starting a new game)

with jaguar i could make it to boot in earlier version by adding a line:
DATA="whdloadgame:JaguarXJ220Image/data/"
and with the new version i thought adding DATA="games:JaguarXJ220Image/data/"  would work but sadly it doesnt :(

Im on a Raspi 3+ here with attract mode.

**Comment by nemo93** [comment]
Hello @Mangaclub!! 
Good point, I believe there's a slight change in the directory commands used by new loader (someone please keep me honest :)). In short you have to use the "games:" parameter now instead of "whdloadgame" to declare the DATA path. Please find below the full content of my **JaguarXJ220_v1.5_Files_1200.auto-startup** to examplify this. The file is bein stored in the **retropie/configs/amiga/amiberry/whdboot/save-data/Autoboots** folder.

```
CD "Games:JaguarXJ220Files"
WHDLoad SLAVE="games:JaguarXJ220Files/JaguarXJ220Files.slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 CUSTOM2=0001 CUSTOM3=0001 DATA="games:JaguarXJ220Files/data/" SAVEPATH=Saves:Savegames/ SAVEDIR="JaguarXJ220Files"

```
The other games listed do work ok here with exception of JurassicPark as I don't have it installed. To me this is linked to the package itself not to Amiberry.

**Comment by Mangaclub** [comment]
i hopes that line worked too but ti still fails into not found :(

**Comment by Mangaclub** [comment]
Ok i found out whats going on. there are 2 versions of jaguar. one with loose files and one with disk images. 
Amiberry just knows the loose files one resulting in a fals Directory structure.
the upper line must now look like this:
`CD "Games:JaguarXJ220image"
WHDLoad SLAVE="games:JaguarXJ220Image/JaguarXJ220Image.slave" PRELOAD NOWRITECACHE NOREQ SPLASHDELAY=0 CUSTOM2=0001 CUSTOM3=0001 DATA="games:JaguarXJ220Image/data/" SAVEPATH=Saves:Savegames/ SAVEDIR="JaguarXJ220Image"`

I think the same problem appears to be also with the others

**Comment by Mangaclub** [comment]
as a addition, the archives of alien breed where corrupted for whatever reason so those are working now too :)

**Comment by HoraceAndTheSpider** [comment]
The problem with Jaguar is a problem with the slave. I have reported it here: 

http://mantis.whdload.de/view.php?id=3831

**Comment by HoraceAndTheSpider** [comment]
As a follow up, i've actually fixed the above bug in Jaguar and submitted it to WHDLoad as a possible new version. 

For the Alien Breed games, i would suggest deleteing everything in the autoboots/ folder, updating Amiberry and the XML and trying again.

**Comment by midwan** [comment]
@Mangaclub 
Any updates on this issue, or can we close it?
