### ISSUE TITLE
New screenshots for install guide

### ISSUE THREAD

**Issue by sigboe** [midwan/amiberry#445]
**Is your feature request related to a problem? Please describe.**
The picture guide for installing on RetroPie is horrific!

**Describe the solution you'd like**
I want you to use something like, or please feel free to use this image.

![render1552291682261](https://user-images.githubusercontent.com/2087930/54109015-c3018180-43dd-11e9-9166-359676b2b352.gif)

**Describe alternatives you've considered**
At least update the pictures without the putty frame, and [set putty to support utf-8.](https://askubuntu.com/questions/16912/ncurses-prompts-look-broken-in-putty-from-windows)

**Additional context**
I can send you the source code of the gif, or make changes per your request and it and render it again. (including I can have more (if I record again) or less of the part where it starts installing)
If you want I can do a pull request to your repo with the source code of the gif, if you tell me what folder to put it (its a yaml file)

**Comment by midwan** [comment]
@sigboe 
Thanks for the suggestion for further improving this. I assume you're referring to this wiki page? https://github.com/midwan/amiberry/wiki/Using-Amiberry-WHDBooter-with-RetroPie-(Step-1)

I don't see a problem in using an animated GIF there, but I would prefer it to be a little "slower" in the selections so that users could see what is being selected easier.

@HoraceAndTheSpider what do you think?

**Comment by sigboe** [comment]
![render1552294296605](https://user-images.githubusercontent.com/2087930/54111148-75881300-43e3-11e9-8c18-2ab3c7baf55b.gif)

I slowed down the frames before hitting enter on the menu choices to about 1.7 seconds (arbitrary number). Any more changes you want?

**Comment by midwan** [comment]
Thanks, I think it looks good now.
Just waiting to get confirmation from @HoraceAndTheSpider since he wrote the original guide, if he's OK with it, we can make the change right away. :)

**Comment by HoraceAndTheSpider** [comment]
I am not precious about it. I took a few screenshots with raspi2png - please feel free to change with whatever is available.

**Comment by sigboe** [comment]
@HoraceAndTheSpider Is there anything else you want to change about the gif?

@midwan I can supply the source of the gif, but I don't see a logical place to put it, for example in my repo I put them like so in the resource folder in the doc folder https://github.com/sigboe/pie-galaxy/tree/master/docs

**Comment by HoraceAndTheSpider** [comment]
I’m fine with the gif as it is thank you.

At the moment the images are hosted externally but I’ll let @midwan confirm if they will be added elsewhere in the repo instead

**Comment by midwan** [comment]
I think it's best if we host it in the repo, to avoid disruptions in the future.

@sigboe is there a difference between the source of the gif you mentioned, and the one you posted here? Can't I just save this one I mean?

**Comment by sigboe** [comment]
@midwan sure you can just save the image, go ahead. The source file is a yaml file that can be used to generate the gif again, or alter the gif and generate it with the changes. The yaml file can also be used to convert it from source to other kinds of files than gif, like in website animation, or even in terminal.

I just like having the source of the media files :) just like having the source of the main program.

**Comment by sigboe** [comment]
Example the frame can be altered using a snippet of css in the yaml file

**Comment by midwan** [comment]
@sigboe 
That sounds interesting, could you please send me the source also then? It might come in handy in the future. :)

Thanks again for your help in this!

**Comment by sigboe** [comment]
@midwan its impossible to attach text or yaml files to comments in github, I can open a pull request to your repo, its just a single yaml file, but I don't see any folders in your repo for gif's or extra files resource files.

**Comment by midwan** [comment]
@sigboe 
Feel free to create a new directory with it, as part of the PR. No problem from my side.
