### ISSUE TITLE
[RetroPie] gamepad as joystick in .uae file?

### ISSUE THREAD

**Issue by sigboe** [midwan/amiberry#447]
Hi, I am using a `.uae` file that looks like this

```
use_gui=no
kickstart_rom_file=/home/pi/RetroPie/BIOS/Amiga/kick12.rom
kickstart_rom_file_id=A6CE1636,KS ROM v1.2 (A500,A1000,A2000)
floppy0=/home/pi/RetroPie/roms/amiga/gog/RocketRanger-1.adf
floppy1=/home/pi/RetroPie/roms/amiga/gog/RocketRanger-2.adf
nr_floppies=2
floppy_speed=800
```
But AFAIK rocket ranger requires input from the joystick port, no interaction happens via the keyboard or mouse as far as I can tell (same `.uae` file works for Wings and Defender of the Crown). Is there a directive for the `.uae` file to connect the gamepad in retroarch into the amiga joystick port?

**Comment by HoraceAndTheSpider** [comment]
If you are running ADFs , just set the joystick port (1) to your device in the input panel and re save your Config

**Comment by sigboe** [comment]
@HoraceAndTheSpider thank you!

Is it possible to do that via `.uae` file?

**Comment by HoraceAndTheSpider** [comment]
Yes but if you do it in GUI would would be able to see what the changes are - I don’t recall them from my head and they are host machine specific. (Selecting your controller)

**Comment by sigboe** [comment]
@HoraceAndTheSpider 

Thanks, I will try it the gui way

also googling i found this `joyport0=joy0` do you think it will work in RetroPie for the Player1 controller automatically? Or will it not work, and I need to set the name of the controller which can be different from time to time, or for a different user?

**Comment by HoraceAndTheSpider** [comment]
Joyport0 (left side) is the Amiga mouse port, so you would need to change that to joyport1

Joy0 is *probably* your first connected (host) controller but I can’t guarentee that.

**Comment by HoraceAndTheSpider** [comment]
Actually joy0 might be “keyboard as joystick” so it could be joy1 again

**Comment by sigboe** [comment]
Thans!!, I will try all this out

**Comment by sigboe** [comment]
I've tried many things for the joystick, including `js0`and `/dev/input/js0` in port 1 and 2, 

I have no interaction in Rocket Ranger, any tips?

**Comment by HoraceAndTheSpider** [comment]
@ sigboe  Is this reoslved?

Did you manage to set the desired settings through the GUI and see what the result was?

**Comment by sigboe** [comment]
@HoraceAndTheSpider No I have not managed to get any input to Rocket Ranger. Do you have any suggestions of what I can try?

If you own Rocket Ranger on GOG and you have a Pi you can easily replicate my setup by running my script https://github.com/sigboe/pie-galaxy

**Comment by HoraceAndTheSpider** [comment]
I dont have Rocket Ranger on GOG. However, i am confused as to why not try a another ADF or the WHDload version?

If you cannot set your controllers from the GUI, then there is little hope of setting it by the .uae config i'm afraid.

**Comment by sigboe** [comment]
I don't have a legal copy of rocket ranger that is whloader. And I don't legally own a kickrom or other files required to convert to whloader. But does it work as a whloader version in amiberry?

**Comment by midwan** [comment]
@sigboe 
Rocket Ranger works normally from the WHDLoad installed version at least.

@HoraceAndTheSpider 
The `WHDLoad_db.xml` setting for this title configured my "keyboard as joystick" to the Parallel port 1 port, instead of joy port. Perhaps you can update that?
