### ISSUE TITLE
Upgrade in previous Amibian versions

### ISSUE THREAD

**Issue by Trigger58** [midwan/amiberry#451]
Hello,
is there anywhere a step-by-step manual how to upgrade an existing Amiberry?

All updates i tried went wrong and destroyed my whole image so i had to restore it with a backup :(

**Comment by midwan** [comment]
@Trigger58 
On which distro? Which board?
Amiberry runs on multiple, you'll need to be more specific. :)

Generally it's a matter of following the instructions in the README (https://github.com/midwan/amiberry), which means:
1) clone this repo (`git clone https://github.com/midwan/amiberry`) somewhere
2) enter the newly created directory (`cd amiberry`)
3) compile for your platform (e.g. `make -j2 PLATFORM=rpi3-sdl2-dispmanx` for the RPI3 SDL2 Dispmanx version)

**Comment by Trigger58** [comment]
I use Amibian on a Raspberry Pi 3b+

I tried the commands you wrote. It runs an update and compiles it but it dont start.
If i use rpi3-sdl2-dispmanx then i cant get it started in any way.
if i use normal rpi3 (sdl1-dispmanx) then i get the error message "permission denied" if amibian try to start it.

**Comment by Trigger58** [comment]
It would be great if it could work with Amibian. :)

I tried different Images like DietPie, Retropie, but all are horrible. DietPie cant start my HD0-folder and the mouse was laggy like hell. RetroPie starts fine but cant handle HD0-folder too. Only HDF-Files but with many errors if i try to save something on there. Mouse was creepy too and it needs damn time till this starts.

Amibian is the only distro which runs like hell, less errors, great mouse moving ,...

**Comment by midwan** [comment]
@Trigger58 
All distros run the same emulator, so it will work the same way in all of them. I suspect your problems with other distros were related to something else, perhaps permissions on the filesystem?

In the current Amibian, SDL2 is not installed so you can only use the SDL1-Dispmanx version. I know Gunnas is working on a new version however, which will include SDL2 by default and come with a newer version of Amiberry also.

I can't help with the specifics of Amibian at the moment, but I worked with Gunnar to ensure that the new version will work without problems. If you can't figure out where the permission denied error is coming from, perhaps it would be best to wait for an update from Gunnar?

**Comment by Trigger58** [comment]
But if this is true, why do i have this massive problems with other distros? i made a clean install of retropie, set a root pw, installed amiberry, copied the needed files on this card and get only problems. Not really userfriendly. The same thing with DietPie. Same steps, same problems.

Only Amibian is the only distro which works from the start.

Nice to hear that Amibian is still living and the works go on :)))

The problem i saw is, that if i use these steps:

cd ~
  git clone https://github.com/midwan/amiberry
  cd amiberry

A folder "amiberry" on root is created. But in Amibian the "amiberry" folder is there:

root -> amibian -> amiberry -> amiberry

So the command i use, install this to the wrong place. if i try to install this in the folder above, then i get an error that the folder already exist. Do i need to delete this folder before i clone the new one?

This is all so confusing and in the whole internet there is nowhere an installation guide how to update a current program manual step-by-step for noobs.

Sorry, i'm frustrated.

**Comment by Trigger58** [comment]
I GOT IT !!!!!!!!!!!!!!!!!!!!!!! :)

Here are the steps i did:

1.) I wrote a clean image of Amibian on a SD-Card
2.) used the commands:

cd ~
git clone https://github.com/midwan/amiberry
cd amiberry

3.) the used this command:

make -j2 PLATFORM=rpi3

4.) deleted all old amiberry-rpi files from the folder root->amibian->amiberry
5.) copied the new amiberry-sdl-rpi3 file from root->amiberry TO root->amibian->amiberry
6.) downloaded the amiberry-rpi-v2.25.zip from https://github.com/midwan/amiberry/releases and unpack these
7.) used FTP-Client to copy all the files from the Zip to root->amibian->amiberry and overwrote the old ones
8.) i deleted the adfdir.conf file from the folder's root->amibian->amiberry->conf  & root->amibian->amiberry->amiberry->conf

Now if i take a look in running Amiberry's "About" there stands v.2.25

:)

**Comment by midwan** [comment]
@Trigger58 
I'm happy to see that you got it working.

BTW, if you download the zip package, you don't need to compile it also. The ZIP package contains everything pre-compiled for Raspbian based systems, so you can just use that directly if it works for you.

**Comment by Trigger58** [comment]
Thanks.

You are not right with the package. Amibian needs a file called amiberry-rpi3-sdl1.
This file dont't exist. I tried to rename one of the contained file but then i get the "Permission Denied"-Error.
That's why i need to compile it ;)

**Comment by Trigger58** [comment]
This Zip contains only 2 rpi3 files:

amiberry-rpi3-sdl2
amiberry-rpi3-sdl3-dispmanx

both don't work

**Comment by midwan** [comment]
@Trigger58 
Oops, sorry, you're right. In v2.25, it looks like I forgot to include SDL1 pre-compiled versions.
I'll get that sorted later today, and update the zip package accordingly.

**Comment by Trigger58** [comment]
:+1:

**Comment by midwan** [comment]
I've also added this guide for the future:
https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version

**Comment by midwan** [comment]
And now we have a zip archive with binaries for Amibian specifically: https://github.com/midwan/amiberry/releases/tag/v2.25
