### ISSUE TITLE
Marble Madness - 2 Player Controls

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#452]
Can we use 2 mice to play Marble Madness in 2 Player mode? Every time I try it my two wired mice always move player 1 whilst player 2 is inactive.

I don't believe you can add two mice in Port 0 & Port 1. 

I was able to get 2 player mode with Joystick but not mice... The game has the option on the main menu to select two mice or two joysticks.

**Comment by midwan** [comment]
This is a dupe of #388
