### ISSUE TITLE
On-screen LEDs

### ISSUE THREAD

**Issue by ghost** [midwan/amiberry#457]
When enabling the on-screen LEDs it now shows them all like WinUAE (11 LEDs !). Is there any way you could go back to the way it was before ? The Power LED and then the others would only show up if you had the drive/device enabled. Then maybe you could have an extra option tick if you wanted to display the FPS light and the other one with the % on it (Hide idle led option doesn't do anything also).

**Comment by 2xtime** [comment]
This would be great if you could limit the on-screen LED's like it was originally. 11 is a bit much :-)

**Comment by midwan** [comment]
We can look into hiding some LEDs depending on some scenarios/options, but we won't be going back to the old code for that.

**Comment by midwan** [comment]
In the interest of keeping the code as similar to WinUAE as possible, we won't be modifying this behavior for now.
