### ISSUE TITLE
Can't start any ADF game

### ISSUE THREAD

**Issue by IlBuonAdamu** [midwan/amiberry#459]
Hello,

I installed Amibian 1.4 in my Raspberry Pi 3, including over 4500 adf files and the various necessary kickstarts through the Midnight Commander.

Despite having followed all the steps provided, I can't get any of the downloaded games started. When starting the emulator, only the kickstart start image remains visible and I am not allowed to go ahead.

I have tried various configurations changing the kickstart, the number of floppies available, the RAM configuration and the CPU speed, but in none of these cases do the adf start.

I have followed several online tutorials, but everyone is shown the same thing as me: they load the kickstart, choose the floppy from the directory and start what they want to start.

What am I doing wrong? What advice can you give me?

Thanks a lot.

**Comment by midwan** [comment]
Could you please give me a step by step example, including exact filenames of the ADFs you're testing with?

If you get to the kickstart screen, then the ROMs have been detected/loaded correctly and there's normally no reason not to load an ADF from there. Perhaps it's a permissions issue on your filesystem?

**Comment by IlBuonAdamu** [comment]
Hi everyone.

Shortly after writing I wanted to do another test: create the emulator on Windows PC using WinUAE trying the same games. I found that those adf didn't work even on windows machines. Most likely the pack that contained them is not reliable and made me lose a lot of time.

Sorry for opening the thread, although I can share having learned that it may be useful to test configurations first under an environment known as Windows and then play them back on Amibian.

Thank you all and have fun!

**Comment by midwan** [comment]
Thanks for confirming. :)
