### ISSUE TITLE
Missing Mouse Scroll wheel during Emulation

### ISSUE THREAD

**Issue by Trigger58** [midwan/amiberry#460]
Hello Midwan,
the mouse scroll wheel is working with the emulator but not during emulation. I emulate an A1200 with a HDF-File. Installed is the Workbench OS3.9 with BoingBag 1 & 2. FreeWheel is installed too.
FreeWheel is a tool for Workbench which allows you to use the wheel on an amiga like on a pc.

I use the same configuration and same HDF-File on both systems:

1.) WinUAE 3.0.0 on a PC (Windows 7 Ultimate 64bit) 
2.) Amibian 1.4.1001 with Amiberry v2.25 on a Raspberry Pi 3b+

During emulation at pc the mouse wheel works fine with the tool FreeWheel. 
At raspberry the mouse wheel works only with in amiberry but not during emulation.

I tried 3 different mice:
- normal USB-PC-Mouse (NoName)
- Logitech G900 with USB and with Bluetooth
- only Bluetooth mouse (NoName)

I looked into the config-files of amiberry and of winuae and i saw that amiberry's config-file is missing many informations about the mouse.

This is all i could found about the mouse in an amiberry config-file (i took **config4.uae** for this example):

---------------------------------------------------------------------------------------------------------

**joyport0_autofire=none
joyport0_friendlyname=Mouse
joyport0_name=MOUSE0
; 
joyport1=joy1
joyport1_autofire=none
joyport1_friendlyname=OnyxSoft Dual JoyDivision
joyport1_name=JOY1
; 
; 
; 
input.joymouse_speed_analog=2
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=15
input.analog_joystick_offset=-1
input.mouse_speed=100
input.autofire_speed=0
kbd_lang=us
;**

---------------------------------------------------------------------------------------------------------

And this below is the script about the mouse from my WinUAE config-file:

---------------------------------------------------------------------------------------------------------

**joyport0=mouse
joyport0autofire=none
joyportfriendlyname0=Windows mouse
joyportname0=WINMOUSE1

input.config=0
input.joymouse_speed_analog=20
input.joymouse_speed_digital=10
input.joymouse_deadzone=33

input.mouse_speed=100

input.1.mouse.0.friendlyname=Windows mouse
input.1.mouse.0.name=WINMOUSE1
input.1.mouse.0.empty=false
input.1.mouse.0.disabled=true
input.1.mouse.0.axis.0=MOUSE1_HORIZ.0
input.1.mouse.0.axis.1=MOUSE1_VERT.0
input.1.mouse.0.axis.2=MOUSE1_WHEEL.0
input.1.mouse.0.button.0=JOY1_FIRE_BUTTON.0
input.1.mouse.0.button.1=JOY1_2ND_BUTTON.0
input.1.mouse.0.button.2=JOY1_3RD_BUTTON.0
input.1.mouse.1.friendlyname=Maus *
input.1.mouse.1.name=6F1D2B60-D5A0-11CF-BFC7444553540000 6F1D2B60-D5A0-11CF-BFC7444553540000
input.1.mouse.1.empty=false
input.1.mouse.1.disabled=false
input.1.mouse.1.axis.0=MOUSE1_HORIZ.0
input.1.mouse.1.axis.1=MOUSE1_VERT.0
input.1.mouse.1.axis.2=MOUSE1_WHEEL.0
input.1.mouse.1.button.0=JOY1_FIRE_BUTTON.0
input.1.mouse.1.button.1=JOY1_2ND_BUTTON.0
input.1.mouse.1.button.2=JOY1_3RD_BUTTON.0
input.1.mouse.1.button.3=KEY_ALT_LEFT.0,KEY_CURSOR_LEFT.0
input.1.mouse.1.button.4=KEY_ALT_LEFT.0,KEY_CURSOR_RIGHT.0
input.1.mouse.2.friendlyname=PS/2 Mouse
input.1.mouse.2.name=\\?\ACPI#PNP0F03#4&cb4dc81&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
input.1.mouse.2.empty=false
input.1.mouse.2.disabled=true
input.1.mouse.2.axis.0=MOUSE1_HORIZ.0
input.1.mouse.2.axis.1=MOUSE1_VERT.0
input.1.mouse.2.axis.2=MOUSE1_WHEEL.0
input.1.mouse.2.button.0=JOY1_FIRE_BUTTON.0
input.1.mouse.2.button.1=JOY1_2ND_BUTTON.0
input.1.mouse.2.button.2=JOY1_3RD_BUTTON.0
input.1.mouse.2.button.3=KEY_ALT_LEFT.0,KEY_CURSOR_LEFT.0
input.1.mouse.2.button.4=KEY_ALT_LEFT.0,KEY_CURSOR_RIGHT.0
input.1.mouse.3.empty=true
input.1.mouse.3.disabled=0
input.1.mouse.4.empty=true
input.1.mouse.4.disabled=0
input.1.mouse.5.empty=true
input.1.mouse.5.disabled=0
input.1.mouse.6.empty=true
input.1.mouse.6.disabled=0
input.1.mouse.7.empty=true
input.1.mouse.7.disabled=0

input.2.mouse.0.friendlyname=Windows mouse
input.2.mouse.0.name=WINMOUSE1
input.2.mouse.0.empty=false
input.2.mouse.0.disabled=true
input.2.mouse.0.axis.0=MOUSE1_HORIZ.0
input.2.mouse.0.axis.1=MOUSE1_VERT.0
input.2.mouse.0.axis.2=MOUSE1_WHEEL.0
input.2.mouse.0.button.0=JOY1_FIRE_BUTTON.0
input.2.mouse.0.button.1=JOY1_2ND_BUTTON.0
input.2.mouse.0.button.2=JOY1_3RD_BUTTON.0
input.2.mouse.1.friendlyname=Maus *
input.2.mouse.1.name=6F1D2B60-D5A0-11CF-BFC7444553540000 6F1D2B60-D5A0-11CF-BFC7444553540000
input.2.mouse.1.empty=false
input.2.mouse.1.disabled=false
input.2.mouse.1.axis.0=MOUSE1_HORIZ.0
input.2.mouse.1.axis.1=MOUSE1_VERT.0
input.2.mouse.1.axis.2=MOUSE1_WHEEL.0
input.2.mouse.1.button.0=JOY1_FIRE_BUTTON.0
input.2.mouse.1.button.1=JOY1_2ND_BUTTON.0
input.2.mouse.1.button.2=JOY1_3RD_BUTTON.0
input.2.mouse.1.button.3=KEY_ALT_LEFT.0,KEY_CURSOR_LEFT.0
input.2.mouse.1.button.4=KEY_ALT_LEFT.0,KEY_CURSOR_RIGHT.0
input.2.mouse.2.friendlyname=PS/2 Mouse
input.2.mouse.2.name=\\?\ACPI#PNP0F03#4&cb4dc81&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
input.2.mouse.2.empty=false
input.2.mouse.2.disabled=true
input.2.mouse.2.axis.0=MOUSE1_HORIZ.0
input.2.mouse.2.axis.1=MOUSE1_VERT.0
input.2.mouse.2.axis.2=MOUSE1_WHEEL.0
input.2.mouse.2.button.0=JOY1_FIRE_BUTTON.0
input.2.mouse.2.button.1=JOY1_2ND_BUTTON.0
input.2.mouse.2.button.2=JOY1_3RD_BUTTON.0
input.2.mouse.2.button.3=KEY_ALT_LEFT.0,KEY_CURSOR_LEFT.0
input.2.mouse.2.button.4=KEY_ALT_LEFT.0,KEY_CURSOR_RIGHT.0
input.2.mouse.3.empty=true
input.2.mouse.3.disabled=0
input.2.mouse.4.empty=true
input.2.mouse.4.disabled=0
input.2.mouse.5.empty=true
input.2.mouse.5.disabled=0
input.2.mouse.6.empty=true
input.2.mouse.6.disabled=0
input.2.mouse.7.empty=true

input.3.mouse.0.friendlyname=Windows mouse
input.3.mouse.0.name=WINMOUSE1
input.3.mouse.0.empty=false
input.3.mouse.0.disabled=true
input.3.mouse.0.axis.0=MOUSE1_HORIZ.0
input.3.mouse.0.axis.1=MOUSE1_VERT.0
input.3.mouse.0.axis.2=MOUSE1_WHEEL.0
input.3.mouse.0.button.0=JOY1_FIRE_BUTTON.0
input.3.mouse.0.button.1=JOY1_2ND_BUTTON.0
input.3.mouse.0.button.2=JOY1_3RD_BUTTON.0
input.3.mouse.1.friendlyname=Maus *
input.3.mouse.1.name=6F1D2B60-D5A0-11CF-BFC7444553540000 6F1D2B60-D5A0-11CF-BFC7444553540000
input.3.mouse.1.empty=false
input.3.mouse.1.disabled=false
input.3.mouse.1.axis.0=MOUSE1_HORIZ.0
input.3.mouse.1.axis.1=MOUSE1_VERT.0
input.3.mouse.1.axis.2=MOUSE1_WHEEL.0
input.3.mouse.1.button.0=JOY1_FIRE_BUTTON.0
input.3.mouse.1.button.1=JOY1_2ND_BUTTON.0
input.3.mouse.1.button.2=JOY1_3RD_BUTTON.0
input.3.mouse.1.button.3=KEY_ALT_LEFT.0,KEY_CURSOR_LEFT.0
input.3.mouse.1.button.4=KEY_ALT_LEFT.0,KEY_CURSOR_RIGHT.0
input.3.mouse.2.friendlyname=PS/2 Mouse
input.3.mouse.2.name=\\?\ACPI#PNP0F03#4&cb4dc81&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}
input.3.mouse.2.empty=false
input.3.mouse.2.disabled=true
input.3.mouse.2.axis.0=MOUSE1_HORIZ.0
input.3.mouse.2.axis.1=MOUSE1_VERT.0
input.3.mouse.2.axis.2=MOUSE1_WHEEL.0
input.3.mouse.2.button.0=JOY1_FIRE_BUTTON.0
input.3.mouse.2.button.1=JOY1_2ND_BUTTON.0
input.3.mouse.2.button.2=JOY1_3RD_BUTTON.0
input.3.mouse.2.button.3=KEY_ALT_LEFT.0,KEY_CURSOR_LEFT.0
input.3.mouse.2.button.4=KEY_ALT_LEFT.0,KEY_CURSOR_RIGHT.0
input.3.mouse.3.empty=true
input.3.mouse.3.disabled=0
input.3.mouse.4.empty=true
input.3.mouse.4.disabled=0
input.3.mouse.5.empty=true
input.3.mouse.5.disabled=0
input.3.mouse.6.empty=true
input.3.mouse.6.disabled=0
input.3.mouse.7.empty=true
input.3.mouse.7.disabled=0
**

-----------------------------------------------------------------------------------------------------

Here you can see that the mouse got much more information into WinUAE and the there is a description for the mouse wheel too. 

I think one of the most important thing is the mouse name like above (as example 6F1D2B60-D5A0-11CF-BFC7444553540000 6F1D2B60-D5A0-11CF-BFC7444553540000).

I read about near the same problem with mouse wheel on **Rasbian** at Pi. Only a clear declaration of the mouse-ID or mouse-hardware-ID solved the problem. I dont't know if this could be the problem with amiberry but i think this info could help.

**Comment by midwan** [comment]
@Trigger58 
The mouse wheel events are not supported in SDL1, only in SDL2.
Amibian 1.4 still uses SDL1 I'm afraid, so you won't be able to get that working there. The new version of Amibian which is still in preview, runs the SDL2 version of Amiberry - so it should work there.

RetroPie also still runs the SDL1 version, and that's the last distro that I know of that still uses it. All other distros run the SDL2 version of Amiberry.

**Comment by midwan** [comment]
That being said, I noticed that it doesn't work as expected under SDL2 also, even though it does trigger the event. I'll look into that and try to fix it, but it will still only work under SDL2 versions of Amiberry.

**Comment by Trigger58** [comment]
Ok. Thanks for the Info. 


I hope Amibian 1.5 will get a release soon. I want test the new SDL2-Version :)
