### ISSUE TITLE
Amiberry SDL2 in Emulationstation

### ISSUE THREAD

**Issue by Tarvoskemwer** [midwan/amiberry#463]
Is it at all possible possible to use Amiberry with SDL2-dispmanx in Emulationstation? if not, is there a chance it will be in a future release?
The DosBox-SDL2 fork works in Emulationstation, perhaps use some of their code?

My story so far:
I'm on a Raspberry Pi 3 b, with Stretch and running RetroPie

Did a "sudo apt-get update && sudo apt-get upgrade" and followed the guide to compile SDL2 from source with the full list of requirements

then did a "make -j2 PLATFORM=rpi3-sdl2-dispmanx", which compiled succesfully
(didn't do an rpi-update beforehand as it didn't appear to be a requirement)

Copied over the binary to the Amiberry-dir and updated the symlink to point the new binary, tried a test run only to learn that it instantly exits to Emulationstation.

then I changed the driver to FKMS (not full), only to learn that Emulationstation wont boot with that, so switched back to legacy.

then I decided to play around and learn some more, so tried "amiberry-rpi3-sdl2" target, which failed and then "rpi3" target, which also failed.
Both failed to compile, I have the outputs from cmd if its of any interest?

Eventually I reverted back to compiling Amiberry with Retropie-Setup

Otherwise, hope you have time to answer my questions and thanks for a great emulator :-)

**Comment by midwan** [comment]
The SDL2-Dispmanx version won't work with the current RetroPie at least, because of a few reasons:

The default SDL2 package from the Raspbian repo, uses the `rpi` back-end which also utilizes Dispmanx. This creates a conflict since we can't open the Dispmanx context simultaneously from two sides (SDL2 and Amiberry). The workaround was to use the `KMSDRM` backend for SDL2, but that requires that you configure and compile SDL2 yourself, to enable it. And the `kmsdrm` backend also requires the `FKMS` or `KMS` driver (but since we also want to use Dispmanx from Amiberry, that leaves us only with `FKMS`).

However, you can run the regular (non-dispmanx) SDL2 version of Amiberry on RetroPie, which will use whatever SDL2 installation you have. I've done some tests like that and it seems to work fine, but I need to measure the performance difference before we can say it's a good alternative or not.
The reason we made a special dispmanx version in the first place, was to maximize the performance further from what SDL2 provided with the `rpi` back-end.

If you want to try that out, just make sure you have the SDL2 requirements in place (`libsdl2-dev`, `libsdl2-image-dev` and `libsdl2-ttf-dev`) from the normal Raspbian repo, and compile the `amiberry-rpi3-sdl2` version instead.

**Comment by Tarvoskemwer** [comment]
installed the SDL2 requirements, but compiling fails:

pi@retropie:~ $ cd amiberry/
pi@retropie:~/amiberry $ make -j2 PLATFORM=rpi3-sdl2
make -C guisan-dev
make[1]: Entering directory '/home/pi/amiberry/guisan-dev'
make[1]: 'lib/libguisan.a' is up to date.
make[1]: Leaving directory '/home/pi/amiberry/guisan-dev'
g++ -o amiberry-rpi3-sdl2 src/akiko.o src/ar.o src/aros.rom.o src/audio.o src/autoconf.o src/blitfunc.o src/blittable.o src/blitter.o src/blkdev.o src/blkdev_cdimage.o src/bsdsocket.o src/calc.o src/cd32_fmv.o src/cd32_fmv_genlock.o src/cdrom.o src/cfgfile.o src/cia.o src/crc32.o src/custom.o src/def_icons.o src/devices.o src/disk.o src/diskutil.o src/dlopen.o src/drawing.o src/events.o src/expansion.o src/fdi2raw.o src/filesys.o src/flashrom.o src/fpp.o src/fsdb.o src/fsdb_unix.o src/fsusage.o src/gayle.o src/gfxboard.o src/gfxutil.o src/hardfile.o src/hrtmon.rom.o src/ide.o src/inputdevice.o src/keybuf.o src/main.o src/memory.o src/native2amiga.o src/rommgr.o src/rtc.o src/savestate.o src/scsi.o src/statusline.o src/traps.o src/uaelib.o src/uaeresource.o src/zfile.o src/zfile_archive.o src/archivers/7z/7zAlloc.o src/archivers/7z/7zBuf.o src/archivers/7z/7zCrc.o src/archivers/7z/7zCrcOpt.o src/archivers/7z/7zDec.o src/archivers/7z/7zIn.o src/archivers/7z/7zStream.o src/archivers/7z/Bcj2.o src/archivers/7z/Bra.o src/archivers/7z/Bra86.o src/archivers/7z/LzmaDec.o src/archivers/7z/Lzma2Dec.o src/archivers/7z/Xz.o src/archivers/dms/crc_csum.o src/archivers/dms/getbits.o src/archivers/dms/maketbl.o src/archivers/dms/pfile.o src/archivers/dms/tables.o src/archivers/dms/u_deep.o src/archivers/dms/u_heavy.o src/archivers/dms/u_init.o src/archivers/dms/u_medium.o src/archivers/dms/u_quick.o src/archivers/dms/u_rle.o src/archivers/lha/crcio.o src/archivers/lha/dhuf.o src/archivers/lha/header.o src/archivers/lha/huf.o src/archivers/lha/larc.o src/archivers/lha/lhamaketbl.o src/archivers/lha/lharc.o src/archivers/lha/shuf.o src/archivers/lha/slide.o src/archivers/lha/uae_lha.o src/archivers/lha/util.o src/archivers/lzx/unlzx.o src/archivers/mp2/kjmp2.o src/archivers/wrp/warp.o src/archivers/zip/unzip.o src/caps/caps_win32.o src/machdep/support.o src/osdep/bsdsocket_host.o src/osdep/cda_play.o src/osdep/charset.o src/osdep/fsdb_host.o src/osdep/amiberry_hardfile.o src/osdep/keyboard.o src/osdep/mp3decoder.o src/osdep/picasso96.o src/osdep/writelog.o src/osdep/amiberry.o src/osdep/amiberry_filesys.o src/osdep/amiberry_input.o src/osdep/amiberry_gfx.o src/osdep/amiberry_gui.o src/osdep/amiberry_rp9.o src/osdep/amiberry_mem.o src/osdep/amiberry_whdbooter.o src/osdep/sigsegv_handler.o src/sounddep/sound.o src/osdep/gui/UaeRadioButton.o src/osdep/gui/UaeDropDown.o src/osdep/gui/UaeCheckBox.o src/osdep/gui/UaeListBox.o src/osdep/gui/InGameMessage.o src/osdep/gui/SelectorEntry.o src/osdep/gui/ShowHelp.o src/osdep/gui/ShowMessage.o src/osdep/gui/SelectFolder.o src/osdep/gui/SelectFile.o src/osdep/gui/CreateFilesysHardfile.o src/osdep/gui/EditFilesysVirtual.o src/osdep/gui/EditFilesysHardfile.o src/osdep/gui/PanelAbout.o src/osdep/gui/PanelPaths.o src/osdep/gui/PanelQuickstart.o src/osdep/gui/PanelConfig.o src/osdep/gui/PanelCPU.o src/osdep/gui/PanelChipset.o src/osdep/gui/PanelCustom.o src/osdep/gui/PanelROM.o src/osdep/gui/PanelRAM.o src/osdep/gui/PanelFloppy.o src/osdep/gui/PanelHD.o src/osdep/gui/PanelInput.o src/osdep/gui/PanelDisplay.o src/osdep/gui/PanelSound.o src/osdep/gui/PanelMisc.o src/osdep/gui/PanelSavestate.o src/osdep/gui/main_window.o src/osdep/gui/Navigation.o src/osdep/neon_helper.o src/newcpu.o src/newcpu_common.o src/readcpu.o src/cpudefs.o src/cpustbl.o src/cpuemu_0.o src/cpuemu_4.o src/cpuemu_11.o src/cpuemu_40.o src/cpuemu_44.o src/jit/compemu.o src/jit/compstbl.o src/jit/compemu_fpp.o src/jit/compemu_support.o src/archivers/7z/BraIA64.o src/archivers/7z/Delta.o src/archivers/7z/Sha256.o src/archivers/7z/XzCrc64.o src/archivers/7z/XzDec.o -L/usr/local/lib -Wl,-rpath,/usr/local/lib -Wl,--enable-new-dtags -lSDL2 -lSDL2_image -lSDL2_ttf -lguisan -Lguisan-dev/lib -flto -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lpthread -lz -lpng -lrt -lxml2 -lFLAC -lmpg123 -ldl -lmpeg2convert -lmpeg2
src/osdep/amiberry_gfx.o: In function `display_thread(void*)':
amiberry_gfx.cpp:(.text+0x108): undefined reference to `vc_dispmanx_vsync_callback'
amiberry_gfx.cpp:(.text+0x110): undefined reference to `vc_dispmanx_display_close'
amiberry_gfx.cpp:(.text+0x114): undefined reference to `bcm_host_deinit'
amiberry_gfx.cpp:(.text+0x154): undefined reference to `vc_dispmanx_resource_write_data'
amiberry_gfx.cpp:(.text+0x15c): undefined reference to `vc_dispmanx_update_start'
amiberry_gfx.cpp:(.text+0x16c): undefined reference to `vc_dispmanx_element_change_source'
amiberry_gfx.cpp:(.text+0x17c): undefined reference to `vc_dispmanx_update_submit'
amiberry_gfx.cpp:(.text+0x220): undefined reference to `bcm_host_init'
amiberry_gfx.cpp:(.text+0x228): undefined reference to `vc_dispmanx_display_open'
amiberry_gfx.cpp:(.text+0x23c): undefined reference to `vc_dispmanx_vsync_callback'
amiberry_gfx.cpp:(.text+0x280): undefined reference to `vc_dispmanx_display_get_info'
amiberry_gfx.cpp:(.text+0x294): undefined reference to `vc_dispmanx_resource_create'
amiberry_gfx.cpp:(.text+0x2ac): undefined reference to `vc_dispmanx_resource_create'
amiberry_gfx.cpp:(.text+0x2c4): undefined reference to `vc_dispmanx_resource_create'
amiberry_gfx.cpp:(.text+0x2e0): undefined reference to `vc_dispmanx_rect_set'
amiberry_gfx.cpp:(.text+0x2fc): undefined reference to `vc_dispmanx_resource_write_data'
amiberry_gfx.cpp:(.text+0x318): undefined reference to `vc_dispmanx_resource_write_data'
amiberry_gfx.cpp:(.text+0x334): undefined reference to `vc_dispmanx_rect_set'
amiberry_gfx.cpp:(.text+0x350): undefined reference to `vc_dispmanx_rect_set'
amiberry_gfx.cpp:(.text+0x3fc): undefined reference to `vc_dispmanx_rect_set'
amiberry_gfx.cpp:(.text+0x41c): undefined reference to `vc_dispmanx_update_start'
amiberry_gfx.cpp:(.text+0x44c): undefined reference to `vc_dispmanx_element_add'
amiberry_gfx.cpp:(.text+0x484): undefined reference to `vc_dispmanx_element_add'
amiberry_gfx.cpp:(.text+0x498): undefined reference to `vc_dispmanx_update_submit'
amiberry_gfx.cpp:(.text+0x504): undefined reference to `vc_dispmanx_rect_set'
amiberry_gfx.cpp:(.text+0x510): undefined reference to `vc_dispmanx_resource_delete'
amiberry_gfx.cpp:(.text+0x520): undefined reference to `vc_dispmanx_resource_delete'
amiberry_gfx.cpp:(.text+0x52c): undefined reference to `vc_dispmanx_resource_delete'
amiberry_gfx.cpp:(.text+0x558): undefined reference to `vc_dispmanx_resource_write_data'
amiberry_gfx.cpp:(.text+0x560): undefined reference to `vc_dispmanx_update_start'
amiberry_gfx.cpp:(.text+0x570): undefined reference to `vc_dispmanx_element_change_source'
amiberry_gfx.cpp:(.text+0x584): undefined reference to `vc_dispmanx_update_start'
amiberry_gfx.cpp:(.text+0x590): undefined reference to `vc_dispmanx_element_remove'
amiberry_gfx.cpp:(.text+0x59c): undefined reference to `vc_dispmanx_element_remove'
amiberry_gfx.cpp:(.text+0x5a4): undefined reference to `vc_dispmanx_update_submit_sync'
collect2: error: ld returned 1 exit status
Makefile:445: recipe for target 'amiberry-rpi3-sdl2' failed
make: *** [amiberry-rpi3-sdl2] Error 1
pi@retropie:~/amiberry $

**Comment by Tarvoskemwer** [comment]
fixed it, seems to be compiling now - didn't know I had to delete and clone the git again

**Comment by Tarvoskemwer** [comment]
I get an error when I try to launch a game, log:

Parameters: 
Executing: /opt/retropie/emulators/amiberry/amiberry.sh auto "/home/pi/RetroPie/roms/amiga/somegame.lha"
INFO: SDL could not initialize! SDL_Error: No available video device
Internal error; file src/osdep/amiberry_gfx.cpp, line 347
/opt/retropie/emulators/amiberry/amiberry.sh: line 63:  1109 Aborted                 "$emulator" -autoload="$rom" -G
~

**Comment by midwan** [comment]
@Tarvoskemwer 
You don't need to delete and clone again, you could just do a `make clean` and it would also work. :)

The error about `No available video device` however is strange. Did you compile/install SDL2 yourself from the wiki? In that case, the `rpi` back-end is NOT enabled, only `kmsdrm` is - and if you're using the Legacy driver then `kmsdrm` will not work.

If you're using the standard SDL2 libs from the Raspbian repo, it should work (that's how I've tested it also).

**Comment by Tarvoskemwer** [comment]
Yes, first followed the guide SDL2-guide https://github.com/midwan/amiberry/wiki/Compile-SDL2-from-source , turned on fake kms as you mentioned in https://github.com/midwan/amiberry/issues/268, then reverted to legacy when emulationstation wouldnt launch.
Then followed your instructions regarding SDL2 requirements (libsdl2-dev, libsdl2-image-dev and libsdl2-ttf-dev) from the normal Raspbian repo, and compiled the amiberry-rpi3-sdl2 version.

**Comment by midwan** [comment]
@Tarvoskemwer 
Yeap, that's probably the source of your problem.
You can either re-compile SDL2 yourself, but this time use the `rpi` backend instead of `kmsdrm` (`--enable-video-rpi`) or uninstall that, and install the one provided by the Raspbian repo (using `sudo apt install libsdl2-dev` for example).

The one provided by the repo is an older version, which may contain known bugs, but it's faster to get since you don't need to compile it.

**Comment by Tarvoskemwer** [comment]
So this?
cd SDL2-2.0.9
make clean 
./configure --enable-video-rpi --disable-video-opengl --disable-video-x11 && make -j$(nproc) && sudo make install

**Comment by midwan** [comment]
Yeap, that should do it. And actually, even if you don't specify `--enable-video-rpi` I think it will be enabled by default.

**Comment by Tarvoskemwer** [comment]
that did the trick, thanks for all your help :)

**Comment by midwan** [comment]
@Tarvoskemwer 
Thanks for confirming.
If you manage to run some tests on it and compare the performance to the dispmanx version, it would be great if you would share your results.

I haven't had time to properly compare them, but if the performance is similar it would make sense to switch to SDL2 exclusively in the future.
