### ISSUE TITLE
Amiga CD32 Screen is cut off left and right

### ISSUE THREAD

**Issue by mrfomt** [midwan/amiberry#464]
When I start a cue file to autoload a CD32 game, the game starts and everything works, but the display is cut off on both sides, left and right, so cant see the whole game. If I go in to the settings and change the display to set it correct, then when I save the config file (autoload for game) I loose my controller in the game, cant exit amiberry or enter config anymore. The other games still works with controller, but if I just save then the game they looses the controller.
Amiberry on Odroid XU4 (Odroid Arena, Latest Thera image)
IMAGE:
https://i.ibb.co/4KGrKkR/20190411-141937.jpg

**Comment by CypherXG** [comment]
The screen from the CD32 Emulation was not correct until the beginning of Amiberry. The Screen is not centered..

**Comment by mrfomt** [comment]
You mean that it never have been correct?

**Comment by CypherXG** [comment]
Yep. But i think its only a small correction nad than it's fixed.

**Comment by midwan** [comment]
@mrfomt 
Does this only happen when you load WHDLoad games that are CD32 titles?
What if you just use the Quickstart and select CD32 as a platform there, does the image look OK?

**Comment by CypherXG** [comment]
This issue happens everytime.
It does no matter if you start an CD32, LHA or with the quickstart option.
Simple start Amiberry with the CD32 Roms. That's it.
The Screen is cut off on the left side. It's not centered like with the other roms.
I think the bug is in the akira file.

**Comment by mrfomt** [comment]
@midwan
It happens only for me while loading cd32 cue files

**Comment by midwan** [comment]
This seems to be fixed in `dev` from what I can see.
It will be merged into `master` as soon as beta testing is complete.
