### ISSUE TITLE
Improve analog controller sticks as mouse (mousemap)

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#467]
Analog sticks working only digitaly. (only one speed, only 8 directions).
Add please fully support of real analogy sticks.)

Thanx.)

**Comment by midwan** [comment]
We'll look into this with a future update, it requires merging in code from WinUAE.

**Comment by HoraceAndTheSpider** [comment]
I would like to add a drop down customisation for the analogue sticks. I will have a look to see if this is one that can be put in. 

Is there  specific game to test with? Grand Prix perhaps?

**Comment by Tomato1981** [comment]
It will be great! I think best games for testing are mouse games: POW, Die Hard, Take Em Out, Operation Wolf, Super Hang On, Battle Squadron,...

**Comment by HoraceAndTheSpider** [comment]
Ok, I’m confused - I thought the request for analogue support was for Amiga analogue joysticks? 


What you are after is host-side analogue  control of the Amiga mouse

**Comment by Tomato1981** [comment]
This is just a misunderstanding. My fault. I thought Analog Sticks on joypad PS4, XBox. If you set it to a mouse, now works only digitally - only 1 speed, 8 directions. I'm talking about smooth, free movement.

**Comment by midwan** [comment]
This is implemented in the current version, you can set mousemap with the Left Analog stick from the dropdown (you'll need to have a controller mode other than default to enable mousemap options).
You can also control the sensitivity with the Analog joy-mouse speed slider. The default is 100, but you can set it lower or higher as needed.

After that, the left stick acts like a mouse, with analog movements - move it slightly, and it will move slightly. Move it all the way and it will move much faster.
