### ISSUE TITLE
Sensible World Of Soccer Bug career mode

### ISSUE THREAD

**Issue by danko79** [midwan/amiberry#468]
Hi,i have a raspeberry pi 3b with latest version RETROPIE plus AMIBERRY put rom .LHA all versions Sensible World Of Soccer 95/96 96/97 97/98 when play in career mode and select (example Serie A team Milan) black screen appears you hear game music, when try a friendly game works without any problem...

**Comment by HoraceAndTheSpider** [comment]
Check that immediate blits is enabled. Seem to recall this being a requirement for SWOS

**Comment by danko79** [comment]
> 
> 
> Check that immediate blits is enabled. Seem to recall this being a requirement for SWOS

how do i enable it?

**Comment by danko79** [comment]
Does anyone have this stupid bug?

**Comment by gazchap** [comment]
I have a similar problem - when playing a match (I've only tried Career mode so far), the screen fades to black and then a split second later fades back to normal again, and then keeps doing that every few seconds.

Behaviour starts as soon as the match screen starts, i.e. as the players are running out on to the pitch.

Immediate blit is turned on, using the LHA version of SWOS 96/97. Tried 97/98 but can't even get into a match with that one, screen just hangs when I select a team.

**Comment by aurunmilla** [comment]
set bliter as immediate

**Comment by aurunmilla** [comment]
Set Blitter as immediate

**Comment by gazchap** [comment]
Immediate blits are already turned on. If I try the same settings on SensibleWorldOfSoccer1617_v1.7 it's all fine though.

**Comment by midwan** [comment]
Tested with `SensibleWorldOfSoccer9798_v1.7.lha` - I can recreate the issue.
However, if I start the game with Immediate Blitter enabled, I don't have the problem and it works fine.
