### ISSUE TITLE
Sensible Soccer  Repeat Key issue

### ISSUE THREAD

**Issue by JTilla** [midwan/amiberry#469]
When pushing a direction on key  in Sensible Soccer during a dead ball situation the substitute bench keeps appearing. The normal way to make this happen is to push in the same direction twice.  Is there anyway to stop the keys repeating? 
This doesn't happen when holding down or up on a gamepad.
I use keyboard as joystick so I can use my picade arcade control connected to the gpio. 
It makes using the keyboard near impossible for some games.
Otherwise what a fantastic emulator.

**Comment by midwan** [comment]
@JTilla 
Thanks for reporting this. It's fixed in the current `dev` branch, and will be merged into `master` as soon as beta testing is complete.

Closing this issue as there's nothing more to do about it for now.
