### ISSUE TITLE
WHDLoad AGA games fail to launch

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#473]
**Describe the bug**
Using amiberry 2.25 with current xml but have issues launching whdload games (lha) thats AGA or CD32. Past the script, screen turn black on most games, and other displays a page with something like this game is intended for the Amiga 1200, which I guess is because the incorrect rom is used when launching a game. Debug log also indicates the it uses wrong chipset.

All rom have correct checksum and symlinks, also tried recreating symlinks as well as removing all instances of amiberry and installing again. RetroPie is latest version as well. I have had this issue for a long time with earlier versions as well.

Normal Amiga 500 games launches without issues.

**To Reproduce**

Launch .lha whdload AGA game in amiberry on RetroPie.

**Expected behavior**
Game should continue loading after script is created. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RetroPie
 - Version 4.4

**Additional context**
I’m pretty sure it’s about amiberry not identifying the game as AGA/CD32 and using wrong wrong rom to launch.

**Comment by HoraceAndTheSpider** [comment]
Have you renamed the files, and are the definitely the ore installed RetroPlay packs?

**Comment by stuffu** [comment]
Well, I have renamed them (to make it easier scraping). Still, the Amiga 500 games works without issues, they have also been renamed.

Anyway, an example of a file name would be "1869.lha" and original name "1869_v1.0_AGA.lha". They are Retroplay WHD games.

I'm not at home so I can't test renaming to see if it works, but I don't think I've read the renaming could cause problems...?

Thanks for replying and for awesome work on Amiberry!

**Comment by stuffu** [comment]
Rolled back to originals and everything is working again. Thought necessary info for amiberry was in the .slave file...
