### ISSUE TITLE
Amiga cd32 height 270

### ISSUE THREAD

**Issue by mrfomt** [midwan/amiberry#475]
**Describe the bug**
Amiga CD32, cant see whole screen

**To Reproduce**
Start a cue file.

**Desktop (please complete the following information):**
 - OS: RetroArena
Odroid Xu4

**Additional context**
If the screen height is set to 270 then it appears to be the whole screen.
Can you fix it in next whdload_db.xml file?

**Comment by HoraceAndTheSpider** [comment]
I will adapt the hostprefs height function to have a default for cd32 games using the AutoBooter

**Comment by mrfomt** [comment]
Sounds great!

**Comment by mrfomt** [comment]
It could also be fixed by change the widht in cd32 games, with height 270 the screen is smaller, but the whole game fits, adding both fixed height and fixed width for cd32 games would be great, then users could experiment with the resolution they want, scanlines doesnt look good in certain resolution, that could be fixed if you can change the resolution that works for your display. Another option ofcorse is create .uae files for every game but easier to set it fixed in hostprefs.

**Comment by HoraceAndTheSpider** [comment]
I am going to add `fixed_cd32_width` and `fixed_cd32_height` options to hostprefs shortly.

**Comment by midwan** [comment]
This is now merged into `dev` and should be working as expected.
It will go into `master` as soon as beta testing is completed.

I'm closing the issue as there's nothing more to do here, unless we discover a bug of course! :)
