### ISSUE TITLE
SDL2 Compiling Guide to 2.0.9

### ISSUE THREAD

**Issue by 2play** [midwan/amiberry#477]
Hello Jim,

I was trying to upgrade to the sdl2 2.0.9 as per your guide here
https://github.com/midwan/amiberry/wiki/Compile-SDL2-from-source
so i can use the sdl2 binary with dispmanx
but only the SDL2_ttf seems to be upgraded.
The rest still show as 
libsdl2-2.0-0: 2.0.8+1rpi 
libsdl2-image- 2.0.1+dfsg-2

Any tip on what to do to force the update as per your so I can have DispmanX back-end with SDL2 (configured for KMSDRM).

Kind regards

PS I was testing the sdl2 binary with dispmanx and my current sdl2 setup, by pressing F12 and then resume back to amiberry was just giving a black screen even though a rom booted ok and displayed on screen.

**Comment by midwan** [comment]
Did you already have SDL2 installed in your system, from the official repos?
If so, you'd need to uninstall that one first, because it takes priority in the path.

**Comment by 2play** [comment]
ok I ll do
sudo apt-get remove -y --force-yes libsdl2-dev
sudo apt-get autoremove -y

I ll try to rerun installs or even try this
hg clone http://hg.libsdl.org/SDL
cd SDL

I was thinking to build basis below. But I d like to have your feedback.
I had built in the past the 2.0.8 basis this steps to use with mame on rasperry
https://choccyhobnob.com/sdl2-2-0-8-on-raspberry-pi/
./configure --enable-video-kmsdrm --disable-video-opengl --disable-video-x11 --disable-video-rpi --disable-pulseaudio --disable-esd --disable-video-mir --disable-video-wayland --host=arm-raspberry-linux-gnueabihf

Looking forward to your reply (Efcharisto polu)

**Comment by midwan** [comment]
That should work, and probably even without having to specify so many options in the configure. I usually go for: `./configure --enable-video-kmsdrm --disable-video-opengl --disable-video-x11 --disable-video-rpi` if I want to use KMSDRM.

**Comment by 2play** [comment]
thank you for the swift reply. Ill post my result and close it as needed in due time
