### ISSUE TITLE
whdload_db.xml (Editing Games Width does not stick)

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#478]
Pi3B+
Amiberry v2.25 (2019-02-20) Updated from Source 9th of May

**Describe the bug**
When editing this xml with Notepad++, I am finding that  SCREEN_WIDTH=768 does not stick? Anything else I add or edit sicks to the XML, here is an example below. I am able to make this config stickif using UAE file, but not default in the xml without the uae file.

**To Reproduce**
1. Edit whdload_db.xml from path /opt/retropie/configs/amiga/amiberry/whdboot/game-data using notepad++
2. Edit changes to a game and "save"
3. Game's width defaults back to 640 when you launch the edited game.

**Expected behavior**
 Game's width to have the width from the xml ingame.

**Screenshots**

**Comment by midwan** [comment]
@ransom1122 
Thanks for reporting this, I suspect that #464 is also related to this (CD32 needs overscan to show some titles correctly).

@HoraceAndTheSpider got time to look into it? Or should I pick this up instead?

**Comment by ransom1122** [comment]
@Midwan Its not only cd32. It's any game.

**Comment by ransom1122** [comment]
Also I have noticed minor game issues with the xml like Addams Family requires SCREEN_HEIGHT=256, default is set incorrectly.

Is there a way to help build the XML correctly? The last thing I want to do is make many manual changes then I will be unable to use the online updater as it will remove all my custom changes..

**Comment by HoraceAndTheSpider** [comment]
SCREEN_WIDTH is not specifiable in the XML (which you shouldnt be editing anyway), only SCREEN_HEIGHT. The value of one can force a change in the other if they are not correct, so i avoided the inclusion of both as WIDTH alone can produce the desired effect.

If there are specific game changes you want, let me know and i will filter them into the weekly updates. What is the file name for Addams Family please?

i will try and find time to take a look at the CD32 one - i have a bug of my own i'd like to fix.

**Comment by ransom1122** [comment]
I've been manually fixing a few on my own. Like double dragon 3 etc.

Sometimes games require maximum height and width. Hence the question Can we manually enter screen width in xml?

**Comment by HoraceAndTheSpider** [comment]
I'm afriad the answer to the question is that you cannot manually enter the screen width into the XML (well... you can, but it wont do anything!)

**Comment by HoraceAndTheSpider** [comment]
Manulaly fixing is a bad idea. The XML is updated every other day with the latest WHDLoad slave files. You will either lose your changes, or you would need to manually add support for each new WHDLoad release.

**Comment by thatman84** [comment]
So the best way to make xml changes stick is to submit them here on github?

**Comment by ransom1122** [comment]
Game configs I've fixed in xml which don't require screen width are

Superfrog games
Ugh!
Double dragon 3

Question after making manual edits in xml. Updating xml from gui will this remove any edits I've made or just add-on new ones without removing my custom edits.

**Comment by ransom1122** [comment]
I was dreading this losing my changes if I ever update xml from gui.

I see the new slave desert strike also requires some adjusting in xml which ive done. Interesting setting though...

Default will cut a lot off the top of the in game screen but main menu centered. After adjusting xml setting I got it to show perfect in game screen but main menu is slightly lowered.

You will see what I mean when you tinker with it.

1. Can you please add screen width option in xml?

2. Is there a safe place to submit adjusted and working configs?

Everyone knows I'm a Die Hard type of guy when it comes with configuring Amiga Games :)

**Comment by HoraceAndTheSpider** [comment]
I would just post any proposed changes on this board, and mark the subject 'XML FIX' or something.

I will need to look at screen width behaviour before i decide whether it should be added. I feel the screen width is already catered for automatically by being relative to the height (and dependent on the use of correct-aspect-ratio) - we should keep in mind that long term i want to remove the WIDTH option as well, and replace with an automatic screen sizer (like FS-UAE and PSPUAE)

For Desert Strike i think i played this and agree needs a change. I would go with best-fit for the gameplay, providng no options are lost in the menus.

**Comment by ransom1122** [comment]
Correct that's what I've managed to do with desert strike no loss in menus and in-game perfect screen fit.

Of there is no interest to have width implemented in XML then what is the point of it in gui?

**Comment by ransom1122** [comment]
@Horace AddamsFamily_v1.3_0419.lha

I will post my XML adjustments tomorrow.

**Comment by mrfomt** [comment]
PinballDreams_v1.3_0377 shoud have SCREEN_Y_OFFSET=-4 instead of -2

**Comment by mrfomt** [comment]
Is there anyway to get better scanlines? It only looks good in height 270 on a 1080p screen, or else its to dark or gets strange horizontal thick bars over the screen every other black and white

**Comment by midwan** [comment]
@mrfomt 
Not without adding shader support I think, as the monitor scaling will affect how these look (which is not the case on CRT monitors).

**Comment by ransom1122** [comment]
Here are my updates for XML Database Entry to these games...

Ugh_v1.1_0396.lha
Superfrog_v1.3_CD32.lha
Superfrog_v1.4_0035.lha
SuperfrogDemo_v1.1_AmigaAction.lha
SuperfrogDemo_v1.1_CUAmiga.lha
SuperfrogDemo_v1.1_TheOne.lha
DoubleDragon3_v1.3_0321.lha
DesertStrike_v3.1_0112.lha
Banshee_v3.3_CD32.lha

Banshee has added input "joyport1_amiberry_custom_none_west=Space" So SQUARE Button is Bomb button. All the other games have corrected Screen Dimensions.

Please add to XML

**Comment by ransom1122** [comment]
Here are my updates for XML Database Entry to these games...

Ugh_v1.1_0396.lha
Superfrog_v1.3_CD32.lha
Superfrog_v1.4_0035.lha
SuperfrogDemo_v1.1_AmigaAction.lha
SuperfrogDemo_v1.1_CUAmiga.lha
SuperfrogDemo_v1.1_TheOne.lha
DoubleDragon3_v1.3_0321.lha
DesertStrike_v3.1_0112.lha
Banshee_v3.3_CD32.lha

Banshee has added input "joyport1_amiberry_custom_none_west=Space" So SQUARE Button is Bomb button. All the other games have corrected Screen Dimensions.

Please add to XML

** I could not attach XML or ZIP so heres the link for the xml
https://www47.zippyshare.com/v/lNIl7oGv/file.html

**Comment by HoraceAndTheSpider** [comment]
> https://www47.zippyshare.com/v/lNIl7oGv/file.html

I cannot reach this file (404)

Can you please just let me know the sepcific changes.

e,g, Superfrog_v1.3_CD32.lha
- Screen Height 320 
- Screen Offset -4

etc. (those are made up examples!)

Banshee addition should make its way into the next update

**Comment by ransom1122** [comment]
Zippy link works. Anyway here's a mirror from mega https://mega.nz/#!lJdnRQbQ!_MlhHyW2yd6Kd61mJyolEpN1bfqyHvYjFfXTVdGf5XQ

Superfrog default has the image too high up missing the players score. It is now centered and all in-game screen is visible

**Comment by ransom1122** [comment]
Zippy link works. Anyway here's a mirror from mega https://mega.nz/#!lJdnRQbQ!_MlhHyW2yd6Kd61mJyolEpN1bfqyHvYjFfXTVdGf5XQ

Superfrog default has the image too high up missing the players score. It is now centered and all in-game screen is visible

**Comment by ransom1122** [comment]
Perfect Example of a game that requires Width greater then default is Roadkill AGA/CD32
	
	<game filename="Roadkill_v2.1b_AGA_1108"  sha1="f6acefa1e618333c927b57f01ae130d56f01ba6a">
		<name>Roadkill [AGA]</name>
		<subpath>RoadkillAGA</subpath>
		<variant_uuid>f0c6d69a-372c-5f39-a371-63a34595c748</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>RoadkillAGA.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
		<filename>RoadkillAGA.Slave</filename>
		<datapath>data</datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		CHIPSET=AGA
		SCREEN_HEIGHT=270
		SCREEN_WIDTH=768
		SCREEN_Y_OFFSET=-5		
		</hardware>
		<custom_controls>
		joyport1_amiberry_custom_none_select=Space
		joyport1_amiberry_custom_none_west=Joy2 2nd Button/Mouse2 Right Button
		joyport1_amiberry_custom_none_start=P
		</custom_controls>
	</game>
	<game filename="Roadkill_v2.1b_CD32"  sha1="178c9c8637d2e496c55972f25e6b846fa3d8d3b3">
		<name>Roadkill [CD32]</name>
		<subpath>RoadkillCD32</subpath>
		<variant_uuid>1e1e1061-6f46-5b52-b236-1abad2782576</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>RoadKillCD32.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
	<filename>RoadKillCD32.Slave</filename>
	<datapath>data</datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		CHIPSET=AGA
		SCREEN_HEIGHT=270
		SCREEN_WIDTH=768
		SCREEN_Y_OFFSET=-5
		Z3_RAM=64		
		</hardware>
		<custom_controls>
		joyport1_amiberry_custom_none_select=Space
		joyport1_amiberry_custom_none_west=Joy2 2nd Button/Mouse2 Right Button
		joyport1_amiberry_custom_none_start=P
		</custom_controls>
	</game>
	
	So Questions remains can you please add Sccreen_Width entry into XML So we dont have to have extra unnessesary uae's in configs folder for these games.

**Comment by ransom1122** [comment]
Excecutioner fails to load... It requires Kickstart 2.0 Are we able to change the kick rom in the XML Database for this game, or is this another game that will require a seperate UAE file in configs to activate the kick2.0 for it to work. Here is my config for the game...

	<game filename="Executioner_v1.1"  sha1="a8c8b77c47097fa98d41e20579cd0094ddbe645b">
		<name>Executioner</name>
		<subpath>Executioner</subpath>
		<variant_uuid>a8850399-dd4d-51a7-890e-13f68864b0da</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>Executioner.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>Executioner.Slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=0
		</hardware>
	</game>

**Comment by ransom1122** [comment]
Damage - The Sadistic Butchering of Humanity - Fixed Screen Dimension
Damage (Preview) - Fixed Screen Dimension
Fire & Ice - The Daring Adventures of Cool Coyote - Fixed Screen Dimension
Fire & Ice [CD32] - Fixed Screen Dimension
Future Tank - Fixed Screen Dimension
It Came From The Desert - Fixed Screen Dimension & Speech
It Came from the Desert II Antheads - Fixed Screen Dimension & Speech
The Executioner - Fixed Screen Dimension
Chaos Engine - Fixed Screen Dimension
Chaos Engine [AGA] - Fixed Screen Dimension
Chaos Engine [CD32] - Fixed Screen Dimension
Chaos Engine 2  - Fixed Screen Dimension
Chaos Engine 2 [AGA] - Fixed Screen Dimension


	<game filename="FutureTank_v1.0"  sha1="345fcb2df29b9cdadbcd3b3b8ba147b5b23715b8">
		<name>Future Tank</name>
		<subpath>FutureTank</subpath>
		<variant_uuid>c169bfe4-f91b-59ef-b322-79e7b327e6e7</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>FutureTank.slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>FutureTank.slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		SCREEN_Y_OFFSET=
		SCREEN_HEIGHT=256
		
		</hardware>
	</game>
	
	
		<game filename="ItCameFromTheDesert2_v2.0"  sha1="8fd4d6797f43231b63daeaf874af595fbebf6edd">
		<name>It Came from the Desert II - Antheads</name>
		<subpath>ItCameFromTheDesert2</subpath>
		<variant_uuid>e7ccd1b2-4648-5628-99aa-b62ea9db5683</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ItCameFromTheDesert2.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ItCameFromTheDesert2.Slave</filename>
			<datapath>data</datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=MOUSE
		PORT0=MOUSE
		PORT1=JOY
		CLOCK=7
		SCREEN_HEIGHT=200
		SCREEN_Y_OFFSET=32
		JIT=TRUE
		BLITTER=WAIT FOR BLIT
		</hardware>
	</game>
	
	
	<game filename="ItCameFromTheDesert_v2.0_0014"  sha1="acb56d26e21e06a89c8b6a775dae7bad120ed3ef">
		<name>It Came From The Desert</name>
		<subpath>ItCameFromTheDesert</subpath>
		<variant_uuid>216ed497-6392-5ded-9341-c60df8c088dc</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ItCameFromTheDesert.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ItCameFromTheDesert.Slave</filename>
			<datapath>data</datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=MOUSE
		PORT0=MOUSE
		PORT1=JOY
		CLOCK=7
		SCREEN_HEIGHT=200
		SCREEN_Y_OFFSET=32
		JIT=TRUE
		BLITTER=WAIT FOR BLIT
		</hardware>
	</game>
		
		
	<game filename="Fire&amp;Ice_v2.2_0502"  sha1="712a3077045118da24c0cea037894710b6785419">
		<name>Fire &amp; Ice - The Daring Adventures of Cool Coyote</name>
		<subpath>Fire&amp;Ice</subpath>
		<variant_uuid>50626de6-3dc9-5c32-9996-708a239705ba</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>Fire&amp;Ice.slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>Fire&amp;Ice.slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=-3
		
		</hardware>
	</game>
	
	<game filename="Fire&amp;Ice_v2.2_CD32"  sha1="e3816eef019be858909056f610fb65053ff0ee9f">
		<name>Fire &amp; Ice [CD32]</name>
		<subpath>Fire&amp;IceCD32</subpath>
		<variant_uuid>7008c1db-9a56-595b-af5b-bc65713bb4d1</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>Fire&amp;IceCD32.slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>Fire&amp;IceCD32.slave</filename>
			<datapath>data</datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=CD32
		PORT1=CD32
		JIT=FALSE
		CHIPSET=AGA
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=-3
		
		</hardware>
	</game>
	
		<game filename="Executioner_v1.1"  sha1="a8c8b77c47097fa98d41e20579cd0094ddbe645b">
		<name>Executioner</name>
		<subpath>Executioner</subpath>
		<variant_uuid>a8850399-dd4d-51a7-890e-13f68864b0da</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>Executioner.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>Executioner.Slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=0
		
		</hardware>
	</game>
	
	
		<game filename="DamagePreview_v1.0"  sha1="9d9236b4c67141f49459bf0ca62cff27d32730ca">
		<name>Damage (Preview)</name>
		<subpath>DamagePreview</subpath>
		<variant_uuid>5c31738c-1fc6-5de9-adb3-a00bf6684f38</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>DamagePreview.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>DamagePreview.Slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		SCREEN_HEIGHT=270
		SCREEN_Y_OFFSET=-5
		
		</hardware>
	</game>
	
	
	<game filename="Damage_v1.2"  sha1="e54e182043a78a6266798dbe57e615c66850346a">
		<name>Damage - The Sadistic Butchering of Humanity</name>
		<subpath>Damage</subpath>
		<variant_uuid>b72ce13f-b2a0-5fd6-9c47-a4d29fcee17f</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>Damage.slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>Damage.slave</filename>
			<datapath>data</datapath>
			<custom>
			C1:B:Unlimited Energy
			</custom>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		SCREEN_HEIGHT=270
		SCREEN_Y_OFFSET=-5

		</hardware>
	</game>
	
	
	<game filename="ChaosEngine2_v2.1_0172"  sha1="927ba0b245837e2d60a19ff63115b87b36b11478">
		<name>Chaos Engine 2</name>
		<subpath>ChaosEngine2</subpath>
		<variant_uuid>c3066dbe-95c9-56b7-8c0e-664a25c3514e</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ChaosEngine2.slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ChaosEngine2.slave</filename>
			<datapath></datapath>
			<custom>
			C1:X:disable mouse/2nd player joystick:0
			
			</custom>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=270
		SCREEN_Y_OFFSET=-5
		
		</hardware>
	</game>
	<game filename="ChaosEngine2_v2.1_AGA_0173"  sha1="95a627f09244e435a5fca0e7012c731efcd6c73e">
		<name>Chaos Engine 2 [AGA]</name>
		<subpath>ChaosEngine2AGA</subpath>
		<variant_uuid>767feb7c-9c65-5f1a-9e51-200936c404ce</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ChaosEngine2AGA.slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ChaosEngine2AGA.slave</filename>
			<datapath></datapath>
			<custom>
			C1:X:disable mouse/2nd player joystick:0
			
			</custom>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		CLOCK=28
		CHIPSET=AGA
		SCREEN_HEIGHT=270
		SCREEN_Y_OFFSET=-5
		
		</hardware>
	</game>

	
	<game filename="ChaosEngine_v1.2_0106"  sha1="4121079eff94ce88391208e88cb77f8bee7e4575">
		<name>Chaos Engine</name>
		<subpath>ChaosEngine</subpath>
		<variant_uuid>9191275d-3ca7-5a8e-9f61-b7af6d368617</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ChaosEngine.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ChaosEngine.Slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=0

		</hardware>
	</game>
	
	
	<game filename="ChaosEngine_v1.2_AGA_1324"  sha1="5e5f668071eeca8b35b61c0d34fd1a29d7aaf63e">
		<name>Chaos Engine [AGA]</name>
		<subpath>ChaosEngineAGA</subpath>
		<variant_uuid>d64ec2c9-daea-51c8-915d-7c1111cb1fb5</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ChaosEngineAGA.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ChaosEngineAGA.Slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		CLOCK=28
		CHIPSET=AGA
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=0
		
		</hardware>
	</game>
	<game filename="ChaosEngine_v1.2_CD32"  sha1="cd444da5a5cf290a4b14fa7566d4409d6d4ddb37">
		<name>Chaos Engine [CD32]</name>
		<subpath>ChaosEngineCD32</subpath>
		<variant_uuid>c807f6c6-6542-5600-b261-682e7981118f</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ChaosEngineCD32.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ChaosEngineCD32.Slave</filename>
			<datapath>data</datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=CD32
		PORT1=CD32
		JIT=FALSE
		CLOCK=28
		CHIPSET=AGA
		SCREEN_HEIGHT=256
		SCREEN_Y_OFFSET=0
		
		</hardware>
	</game>

**Comment by HoraceAndTheSpider** [comment]
Thanks for these - i will be adding shortly.

I've also added screen-width as an option to my branch, and included th necessary changes in the XML generator

**Comment by ransom1122** [comment]
Great work.......

**Comment by HoraceAndTheSpider** [comment]
I still dont know what the changes are for:

Ugh_v1.1_0396.lha
Superfrog_v1.3_CD32.lha
Superfrog_v1.4_0035.lha
SuperfrogDemo_v1.1_AmigaAction.lha
SuperfrogDemo_v1.1_CUAmiga.lha
SuperfrogDemo_v1.1_TheOne.lha
DoubleDragon3_v1.3_0321.lha
DesertStrike_v3.1_0112.lha
Banshee_v3.3_CD32.lha



Changes now added to `Screen Y Offsets.txt`
```
RoadkillAGA -5
RoadkillCD32 -5
RoadkillCD32NoIntro -5
Fire&Ice -3
Fire&IceCD32 -3
Executioner 0
Damage -5
DamagePreview -5
ChaosEngine2 -5
ChaosEngine2AGA -5
```

Changes now added to `Screen_Height_256.txt`

```
ChaosEngine
ChaosEngineAGA
ChaosEngineCD32
Executioner
Fire&Ice
Fire&IceCD32
FutureTank
```

Changes now added to `Screen_Height_270.txt`

```
ChaosEngine2
ChaosEngine2AGA
Damage
DamagePreview
```

added to `Chipset_WaitBlitter.txt` and `CPU_ForceJIT.txt`

```
ItCameFromTheDesert
ItCameFromTheDesert2
```

Hopefully i've picked up all the changes, but with so many games, please can you only give me the details of *only* what needs changing as it makes it very difficult to add otherwise!

Some of the items (like Roadkill CD32 having CD32 controls) should be automatically picked up, so for example should not need a custom control setting

**Comment by mrfomt** [comment]
PinballDreams_v1.3_0377 shoud have SCREEN_Y_OFFSET=-4

**Comment by ransom1122** [comment]
My changes were to games that had parts of the screen chopped off either bottom or top.

**Comment by HoraceAndTheSpider** [comment]
> PinballDreams_v1.3_0377 shoud have SCREEN_Y_OFFSET=-4

This one was already done :)

**Comment by HoraceAndTheSpider** [comment]
> My changes were to games that had parts of the screen chopped off either bottom or top.

These are the changes i made, as above - plus ICFTD. Those which were uploaded i cannot do because 
a) i cant access the files
b) there is too much information there to know what to change.

I will open up the 'issues' section on the XML Bilder GitHub - to save @midwan on this one! But i will have to have some clear rules about how changes are to be posted so that i am not flooded with information!

> I couldn't get standard cd32 controls to work for roadkill you will see what I mean. Try pausing the game or starting the game after the practice 1st lap.

I'll test this out, but afaik, all CD32 games should be using the CD32 controls so there should never be a need to remap.

**Comment by HoraceAndTheSpider** [comment]
New issues section open on the XML GitHub.

Please however follow the posting rules when proposing changes:

https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/wiki/The-Amiberry-XML-Builder
