### ISSUE TITLE
SDL1 | Ctrl + LWin + Rwin keys don't cause a reset

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#48]
I am currently writing on a keyboard interface for an Arduino to steer an Amiga 500 keyboard as HID interface.
Unfortunately, there is a small problem.
I can definitely not control the right Amiga button for a typical Amigareset.
The typical Amiga Reset on a Windows keyboard is done with CRTL + Win + WinMenu
The normal Winuae is thus clear that on a normal keyboard the right Windows key or the right Windows menu key together with CTRL and the left Windows key may be pressed, so the reset works.
The UAE4ARM can not do this because I have programmed my Amiga keyboard to the right Windows key and with the combination CRTL+LeftWin+RightWin the Reset don't work.
Now my little concern:
Can you possibly integrate both right keys (Windows key and the menu key) for a reset as well as the Winuae?
Then the Amiga 500 Keyboard would work perfectly.
Would be super if that would fold.

Greeting Markus

**Comment by midwan** [comment]
This is a known issue with the current (SDL1.2) version, which is fixed already in the SDL2 branch.

I'll see if I can do anything for the current version as well, but since the SDL2 version is nearing completion we might not need to worry about it too much. ;-)

**Comment by midwan** [comment]
Given the improvements in the SDL2 version, I think it's best if we focus our efforts there for now.
Putting this on the back-burner, if anyone wants to assist with a pull request they are more than welcome.
