### ISSUE TITLE
Problem updating Amiberry 2.24b12

### ISSUE THREAD

**Issue by PotNoodleMan** [midwan/amiberry#483]
![IMG_2235](https://user-images.githubusercontent.com/51078397/58462602-9277eb00-8175-11e9-8703-c17d28e0f5dc.PNG)

I’m trying to upgrade Amiberry v2.24b12 to v2.25 and encounter the following error when trying to update ‘from source’ in the retroarch menus.  I am running Stretch on Readpberry Pi 3.

Error: ‘Error running ‘git clone -- recursive -- depth 1........’- returned 128

Screenshot of error is attached.

**Comment by HoraceAndTheSpider** [comment]
This script i maintained by the RetroPie team, so you may need to ask there i'm afraid to say

**Comment by midwan** [comment]
@PotNoodleMan 
Might be worth checking also: Did you update the RetroPie_Setup script first? Just in case you had an older version of it, and they fixed it later.

**Comment by midwan** [comment]
Closing this as I don't believe we can do anything more from our side.
