### ISSUE TITLE
Option --autoload doesn't work with relative paths

### ISSUE THREAD

**Issue by arcadeforge** [midwan/amiberry#484]
Thanks for the awesome work on this emulator

Tried to start whd game with autoload option and provided relative path.

Gave me cd failed returncode 20 error.

Tried again with absolute path and it works like a charm.

My setup

Rpi3b+
Arch linux with regamebox
Latest release amiberry compiled for SDL 1.

**Comment by HoraceAndTheSpider** [comment]
I can only assume non-working  path is not relative to the amiberry binary?

I would expect such things to be handled by the underlying OS rather than the Amiberry code

**Comment by arcadeforge** [comment]
Don't know. I thought perhaps amiberry changes to another folder (ie /tmp) when doing file actions, so the base folder is getting lost when the following relative path is used. Just to be clear that a absolute path must be used if another users stumble on something similar. Cheers

**Comment by HoraceAndTheSpider** [comment]
AFAIK, it shouldnt ever 'lose' the base path - certainly anything using /tmp/ is quite specific.

Could you prove the logfile for when trying to load a relative path?

**Comment by midwan** [comment]
I've run into this as well, actually.

**Comment by arcadeforge** [comment]
[amiberry_log.txt](https://github.com/midwan/amiberry/files/3275640/amiberry_log.txt)

here is the log

line 207
FS: Games (flags=00000004,E=0,ED=0,EF=1,native='games/Barbarian_v1.1_Palace_1784.lha') starting..
