### ISSUE TITLE
Retroarch Keyboard in Port 2

### ISSUE THREAD

**Issue by arcadeforge** [midwan/amiberry#486]
Hey, 

I'm using amiberry as emulator backend with a frontend called lemonlauncher on the distribution regamebox. 

I want to ensure that the retroarch keyboard Joystick is in joyport 1 as default when loading ie lha whdload files.

**Describe the solution you'd like**
Introduce a game specfic uae config feature that is on top of all other configs. Example

conf/Cybernoid2_v1.3_0003.uae

```
joyport1=joy0
joyport1_autofire=none
joyport1_friendlyname=RetroArch Keyboard as Joystick [Input #1]
joyport1_name=JOY0
```

I tried to generate such a config, but I think a config must be complete. This approach would take the config from whd config and put the config part from  Cybernoid2_v1.3_0003.uae on top.

**Describe alternatives you've considered**

Alternative could be a default config feature that overwrites all other configs. Example

conf/default.uae

```
joyport1=joy0
joyport1_autofire=none
joyport1_friendlyname=RetroArch Keyboard as Joystick [Input #1]
joyport1_name=JOY0
```

**Comment by arcadeforge** [comment]
Found a solution for my challenge via hostprefs.conf

```
CONTROLLER_1=joy1
CONTROLLER_2=joy0
;CONTROLLER_3=joy1
;CONTROLLER_4=joy1
```
By commenting out controller 3 and 4 retroarch keyboard show up in controller_2 and joyport 1

Cheers

**Comment by HoraceAndTheSpider** [comment]
What you have described is exactly what hostprefs is for.

If there is a feature/option missing which is not currently in hostprefs and you have justification for it to be added, please let me know
