### ISSUE TITLE
joystick ( number 2 ) to keyboard mapping

### ISSUE THREAD

**Issue by Guitarans** [midwan/amiberry#487]
Im gonna be very specific here:
Joystick 2 to simulates keyboard button press. Is it possible ?
Im playing North and south, and player 2 are forced to use a keyboard ( coded in the game file ), so, is it possible that the joystick 2 can simulate/emulate press on the keyboard ? such as Button A - space..

and so on ?

**Comment by Guitarans** [comment]
Im gonna be very specific here:
Joystick 2 to simulates keyboard button press. Is it possible ?
Im playing North and south, and player 2 are forced to use a keyboard ( coded in the game file ), so, is it possible that the joystick 2 can simulate/emulate press on the keyboard ? such as  Button A - space..

and so on ?

**Comment by HoraceAndTheSpider** [comment]
You just need to use the custom controls panel. The wiki here describes its;

https://github.com/midwan/amiberry/wiki/Customised-Controls


Re: North and South specifically the latest WHDLoad version has an option to move all keyboard controls over to the second joystick anyway so it might be worth looking into that first to save yourself the effort of creating a bespoke layout

**Comment by Guitarans** [comment]
ohh.. mann, you are a savier!! thanks so much.. finally mu frustration is depleted !!
