### ISSUE TITLE
Unable to make configurations changes for WHDLOAD package usage only

### ISSUE THREAD

**Issue by mth75** [midwan/amiberry#488]
**Describe the bug**

I'm trying to change some settings in Amiberry (compiled for SDL2, RPI backend graphics only)(only for WHDLOAD package use) which one would normally do with uae config files.

From my understanding, I can make per whdload package config settings in .whd files or make them in the hostprefs.conf file. 

For example, i'm trying to use the double line mode (in uae terms: gfx_linemode=double) for all WHDLOAD games. 

Question: which options (besides the ones which are documented in the documentation) are possible in hostprefs.conf file.

Another question (but related), in the uae/amiberry gui under configurations one can see 3 profiles:

1. rp-a1200
2. rp-a500
3. uaeconfig (Autoboot Configuration [WHDLOAD])

The first 2 are clearly for starting adf files. The third one would be the answer to my question above, however, the uaeconfig file won't work. Changes for example the double line mode will be saved but won't be loaded.

Further information, I noticed that in the emulators.cfg file (opt/retropie/configs/amiga/emulators.cfg) following entries are visible:

amiberry = "/opt/retropie/emulators/amiberry/amiberry.sh auto %ROM%"
amiberry-a500 = "/opt/retropie/emulators/amiberry/amiberry.sh rp-a500.uae %ROM%"
amiberry-a1200 = "/opt/retropie/emulators/amiberry/amiberry.sh rp-a1200.uae %ROM%"

The emulator option Amiberry is for loading the WHDLoad packages. I've tried:

amiberry = "/opt/retropie/emulators/amiberry/amiberry.sh uaeconfig.uae %ROM%"

with no succes.

**Desktop (please complete the following information):**
 - Raspberry 3b+/RetroPie

**Comment by HoraceAndTheSpider** [comment]
Something that you want in every game should be via the hostprefs.

The .whd files have been removed as the options can be covered by the .uae

The ljnemode option I think is in hostprefs already but I would have to check, and /or there may be a bug with reading that in (other users have had issues with selecting scanlines)

**Comment by knapejor** [comment]
I too would like to know how to add / change an option as default option for each WHDLoad game.

Because of an issue I have, I would like to add the 'sound_frequency' option but I can't get it to work.

The hostprefs seems to be the place to add it, but it does not pick it up / support it it seems.

**Comment by midwan** [comment]
@mth75 
Your approach has a point, you could use a default config for all your games that way - however, you missed specifying the path to the config file in your command line, so it couldn't be found:

`amiberry = "/opt/retropie/emulators/amiberry/amiberry.sh uaeconfig.uae %ROM%"`

Unless the file `uaeconfig.uae` exists in the same location you're launching the emulator from, it won't be found. Try specifying the full path to it, to be sure.

**Comment by HoraceAndTheSpider** [comment]
@midwan if we remove most of hostprefs , does this use case require consideration?

**Comment by midwan** [comment]
The `hostprefs.conf` file is now obsolete, with the latest commits in `master`.
All relevant options have been moved into `amiberry.conf`, which includes several defaults that will be used if nothing overrides them from a config file.
