### ISSUE TITLE
Serialization support for save states (preparing for libretro)

### ISSUE THREAD

**Issue by skaba** [midwan/amiberry#49]
So libretro API expects to serialize state directly into memory and and all UAE forks have file based API (due to compression I suppose). Hence non of the libretro ports out there support savestates. Is it possible to implement this?

**Comment by a7mag3ddon** [comment]
What game formats are you using. I'm pretty sure save states states don't work on WHDLoad games either on uae4arm.

**Comment by HoraceAndTheSpider** [comment]
I can't see the follow up comment here for some reason.

However, when using HD save-states can be used , but are deemed "unsafe" since HD writes (externally) won't be picked up by a fixed memory state.

To allow savestates support when using HDs, an "unsafe save states support" option should be added, to limit or permit this kind of usage. This could be left as "unsafe" in any libretto build

**Comment by skaba** [comment]
@HoraceAndTheSpider I don't know enough about libretro to understand your comment maybe you can point me to right documentation

**Comment by HoraceAndTheSpider** [comment]
i don't know anything about libretro either, but you seemed to be saying libretro ports *should* (if possible) support save-states?

There was a comment on here which i received on email, saying that ". I'm pretty sure save states states don't work on WHDLoad games either on uae4arm."

This is not true on the *latest* amiberry, *but* general convention (WinUAE/FS-UAE etc) is to *not* support save-states on Hard-Drive modes by default. (see comments section here: https://fs-uae.net/whdload-support)

**Comment by midwan** [comment]
@skaba 
I haven't investigated the libretro API very extensively yet, but since we're in charge of the code here we can at least attempt to do whatever is necessary. We'll see if we run into any problems and decide accordingly.

**Comment by midwan** [comment]
This is probably not worth the effort, considering that we'll end up with more problems if we attempt it (due to the nature of hard-drive state vs memory state). There's a reason the other emulators didn't implement it either...
