### ISSUE TITLE
Amiberry WHDLoader and Xin-Mo encoder

### ISSUE THREAD

**Issue by FlorentMartinPilot** [midwan/amiberry#490]
Hi !

I'm using Amiberry with Recalbox 6.0.

Everything is working great when I plug a Xbox 360 controller, but if I'm using my Xin-Mo USB encoder (I have my Rpi in a Bartop) then the WHDloader stays black.

CD32 is working fine, as well as the ADFs games.

Only WHDLoad games WITH the Xin-Mo are crashing the loader :(

So I guess it's a problem with the loader. I have heard that there were some issues with the DragonRise encoder as well...

I can still access the Amiberry interface pressing the hotkey, but the loader won't start anyway.

Thanks for your help, and by the way congrats for this great software !

**Comment by midwan** [comment]
@FlorentMartinPilot 
Are you still having this issue?
If so, could you please try with the current `dev` branch and see if it also occurs there?

**Comment by FlorentMartinPilot** [comment]
Dear Dimitris,

I can’t tell you that, because I’m using Amiberry on Recalbox, not directly.
And I have gotten rid of my Xin-Mo encoder to plug directly my joystick on the GPIO pins…

Congratulations by the way for this great emulator !

Florent

De : Dimitris Panokostas
Envoyé le :samedi 5 octobre 2019 20:05
À : midwan/amiberry
Cc : FlorentMartinPilot; Mention
Objet :Re: [midwan/amiberry] Amiberry WHDLoader and Xin-Mo encoder (#490)

@FlorentMartinPilot
Are you still having this issue?
If so, could you please try with the current dev branch and see if it also occurs there?

**Comment by midwan** [comment]
@FlorentMartinPilot 
Ah ok then. In that case, I think we can close this issue, as I don't see anything else I can do about it from my side.
