### ISSUE TITLE
Joystick settings in conf file ignored

### ISSUE THREAD

**Issue by DBMandrake** [midwan/amiberry#492]
Hi,

I'm helping to get improved Retropie support working on the Vero4k (armv8 platform running Debian based OSMC) and have come across a very perplexing problem that I can't solve.

In short, the Joystick setting saved in a configuration profile will not load automatically on startup with the rest of the profile instead reverting to "None". I am using an Xbox 360 wireless controller with the Microsoft USB receiver, and the xpad driver with the Retropie patch to convert triggers into buttons. (although I am having the same problem with xboxdrv) The controller is working perfectly with emulation station and other emulators.

Here is an example configuration exhibiting the problem:

```
config_description=UAE default configuration
config_hardware=true
config_host=true
config_version=4.1.0
amiberry.rom_path=/opt/retropie/emulators/amiberry/kickstarts/
amiberry.floppy_path=/opt/retropie/emulators/amiberry/disks/
amiberry.hardfile_path=/opt/retropie/emulators/amiberry/
amiberry.cd_path=/opt/retropie/emulators/amiberry/cd32/
; 
; *** Controller/Input Configuration
; 
joyport0=mouse
joyport0_autofire=none
joyport0_mode=mousenowheel
joyport0_friendlyname=Mouse
joyport0_name=MOUSE0
; 
joyport1=joy1
joyport1_autofire=none
joyport1_mode=djoy
joyport1_friendlyname=Xbox 360 Wireless Receiver
joyport1_name=JOY1
joyport1_amiberry_custom_none_dpad_up=Mouse1 Up
joyport1_amiberry_custom_none_dpad_down=Mouse1 Down
joyport1_amiberry_custom_none_dpad_left=Mouse1 Left
joyport1_amiberry_custom_none_dpad_right=Mouse1 Right
joyport1_amiberry_custom_none_select=Enter GUI
joyport1_amiberry_custom_none_left_shoulder=Joy1 Fire/Mouse1 Left Button
joyport1_amiberry_custom_none_start=Pause emulation
joyport1_amiberry_custom_none_right_shoulder=Joy1 2nd Button/Mouse1 Right Button
joyport1_amiberry_custom_hotkey_right_shoulder=Hard reset emulation
; 
; 
; 
absolute_mouse=mousehack
input.joymouse_speed_analog=2
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=15
input.analog_joystick_offset=-1
input.mouse_speed=100
input.autofire_speed=0
kbd_lang=us
; 
; *** Host-Specific
; 
amiberry.vertical_offset=-5
amiberry.hide_idle_led=0
amiberry.gfx_correct_aspect=1
amiberry.kbd_led_num=-1
amiberry.kbd_led_scr=-1
amiberry.scaling_method=-1
amiberry.use_analogue_remap=false
amiberry.use_retroarch_quit=true
amiberry.use_retroarch_menu=true
amiberry.use_retroarch_reset=false
; 
; *** Common / Paths
; 
use_gui=no
kickstart_rom_file=$(FILE_PATH)/Kick13.rom
kickstart_ext_rom_file=
flash_file=
cart_file=
; 
; *** Floppy Drives
; 
floppy0=
floppy1=
floppy2=
floppy3=
nr_floppies=2
floppy_speed=100
; 
; *** Hard Drives
; 
; 
; *** CD / CD32
; 
cd_speed=100
; 
; *** Display / Screen Setup
; 
gfx_framerate=0
gfx_width=704
gfx_height=262
gfx_refreshrate=50
gfx_refreshrate_rtg=50
gfx_lores=false
gfx_resolution=hires
gfx_lores_mode=normal
gfx_linemode=none
gfx_fullscreen_amiga=false
gfx_fullscreen_picasso=false
ntsc=false
; 
; *** CPU options
; 
cpu_speed=real
cpu_type=68000
cpu_model=68000
cpu_compatible=true
cpu_24bit_addressing=true
fpu_no_unimplemented=true
fpu_strict=false
compfpu=false
cachesize=0
; 
; *** Memory
; 
chipmem_size=1
z3mapping=real
fastmem_size=1
a3000mem_size=0
mbresmem_size=0
z3mem_size=0
z3mem_start=0x40000000
bogomem_size=2
gfxcard_hardware_vblank=false
gfxcard_hardware_sprite=false
gfxcard_multithread=false
rtg_modes=0x112
; 
; *** Chipset
; 
chipset=ecs
chipset_refreshrate=50.000000
collision_level=playfields
chipset_compatible=A500
rtc=MSM6242B
cia_todbug=true
immediate_blits=false
waiting_blits=automatic
fast_copper=false
; 
; *** Sound Options
; 
sound_output=exact
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_frequency=44100
sound_interpol=none
sound_filter=off
sound_filter_type=standard
sound_volume_cd=0
; 
; *** Misc. Options
; 
bsdsocket_emu=false

```
To rule out problems with the launcher in emulation station I have tried manually running amiberry:

```
cd /opt/retropie/emulators/amiberry
./amiberry -config=conf/rp-a500.uae
```
The result is that the emulator loads, the correct profile is highlighted in Configurations, all custom settings from the configuration profile load except "Port 1 [Joystick]" in Input, which gets set to None instead of Xbox 360 Wireless Receiver. Port 0 [Mouse] (which I have left and right clicks bound to the controller shoulder buttons) appears as normal. As a consequence all the "custom controls" mappings also say none as Input device says "Not a valid Input Controller for Joystick Emulation".

However if I go to Configurations, choose the profile that is already loaded and hit load, suddenly Input shows the correct Joystick reported for Port 1, and Custom controls are correct and the Joystick works perfectly. So it seems that the joystick profile will not load during initial startup of the emulator, but will when selected and loaded via the GUI.

Even more confusing is that when I use the exact same profile with the same Xbox 360 wireless controller/receiver on a Raspberry Pi 2 running Retropie and the same version of Amiberry both compiled from up to date souce it works properly - eg the Joystick part of the profile is loaded correctly on initial launch.

I've spent a few hours on this now and can't figure out what the difference is. I've tried compiling a different version of Xpad for the Vero4k and also using the alternative xboxdrv userspace driver - but the problem persists. When I compare the joystick device on both systems with jstest it looks the same - the same number of axes and buttons, the same device name and the same button mapping.

I can't really think what the difference could be - about the only thing I can think of is that the Pi 2 version is built with armv7 compiler options while the vero4k version is build with armv8 compiler options...

Is there any debug mode or log that might show why it is refusing to import Joystick settings from the config file on startup ? I'm pretty stumped at the moment. :)

**Comment by DBMandrake** [comment]
After some back and forth testing with @hissingshark we've discovered that this bug occurs when Amiberry is built using SDL2 support instead of SDL1.2. I was able to reproduce the problem exactly on a Raspberry Pi 2 by changing the build script to build against SDL2.

As the Vero4k can only use SDL2 this is a problem for any Vero4k build.

**Comment by midwan** [comment]
@DBMandrake 
Hm, I don't have the same exact controller here, to test with - I have an XBox One controller, but it's detected differently, and it works normally under SDL2 builds.

@HoraceAndTheSpider do you have such a controller to run a test with?

**Comment by DBMandrake** [comment]
Hi @midwan, is your controller an original Xbox One controller or an Xbox One S or X controller ? And if S or X are you using a Bluetooth or USB connection ?

I have an Xbox One S controller that I can test with as well - if I try to use Bluetooth it uses the HID driver and does not go through xpad, however connecting it via USB cable does go through Xpad and works fine with emulation station/amiberry.

So I can try reproducing the problem with my USB connected Xbox One S controller to see if it still happens.

**Comment by midwan** [comment]
@DBMandrake It's an original XBox One controller, and I mostly use it on Windows otherwise (I don't own an actual XBox). I always use it wired over USB.

**Comment by DBMandrake** [comment]
I've just tested my Xbox One S controller using a USB connection and the problem exists there as well.

What are other possible differences than controller between our systems ? SDL library versions ?

What OS are you running Amiberry on when testing ?

**Comment by DBMandrake** [comment]
Some more thoughts. I wonder if there could be an issue with building with SDL2 using the Retropie amibery.sh build script, I assume you would normally test Amiberry on it's own ? Here is the patch I applied to the amiberry.sh build script in RetroPie-Setup to build using SDL2 to reproduce the problem:

```
--- amiberry.sh 2019-06-26 08:25:42.330810027 +0000
+++ /home/pi/amiberry.sh        2019-06-26 05:38:37.295423896 +0000
@@ -18,7 +18,7 @@

 function depends_amiberry() {
     local depends=(libpng-dev libmpeg2-4-dev zlib1g-dev)
-    if ! isPlatform "rpi" || isPlatform "kms" || isPlatform "vero4k"; then
+    if isPlatform "rpi" || isPlatform "kms" || isPlatform "vero4k"; then
         depends+=(libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev)
     fi

@@ -39,8 +39,8 @@
     local amiberry_bin="$__platform-sdl2"
     local amiberry_platform="$__platform-sdl2"
     if isPlatform "rpi" && ! isPlatform "kms"; then
-        amiberry_bin="$__platform-sdl1"
-        amiberry_platform="$__platform"
+        amiberry_bin="$__platform-sdl2"
+        amiberry_platform="$__platform-sdl2"
     elif isPlatform "odroid-xu"; then
         amiberry_bin="xu4"
         amiberry_platform="xu4"
@@ -61,7 +61,7 @@
 function install_amiberry() {
     local amiberry_bin="$__platform-sdl2"
     if isPlatform "rpi" && ! isPlatform "kms"; then
-        amiberry_bin="$__platform-sdl1"
+        amiberry_bin="$__platform-sdl2"
     elif isPlatform "odroid-xu"; then
         amiberry_bin="xu4"
     elif isPlatform "tinker"; then
```

So git cloning RetroPie-Setup then applying this patch to amiberry.sh should give the same build environment.

It's also occurred to me that amiberry is using my retroarch.cfg generated by emulation station, and the contents of that might be a factor, so I've attached the retroarch.cfg that amiberry is pointing to:

[retroarch.txt](https://github.com/midwan/amiberry/files/3329055/retroarch.txt)
