### ISSUE TITLE
PI 4b, 1,2 and 4gb support

### ISSUE THREAD

**Issue by uigiflip** [midwan/amiberry#493]
I Just ordered pi4b with 4gb ram, will there eventually be a new build to support the new power pi 4b?

**Comment by midwan** [comment]
Yes, but probably after the summer.
I'm leaving on vacation in a few days :)

**Comment by solskogen** [comment]
I can confirm that it works on rpi4.

**Comment by midwan** [comment]
Makefile updated for RPI4 with 042e7f1a5f0aa6c40d64fa0c2b6f1ce41d22057b
