### ISSUE TITLE
LattePanda Ubuntu 18.04

### ISSUE THREAD

**Issue by voicenoise** [midwan/amiberry#499]
Hi All

is there any way to install amiberry on a LattePanda with Ubuntu x64 ?

**Comment by 5schatten** [comment]
Just use FS-UAE for x86-64 since Amiberry is optimised for ARM.

**Comment by voicenoise** [comment]
ok thanks, can i use the same files/config from pi amiberry ?

**Comment by 5schatten** [comment]
https://fs-uae.net/configuration-files

I guess you should have a look these documentation files.

**Comment by midwan** [comment]
I believe this is covered, so I'm closing it. We may have x86 versions of Amiberry in the future, but for now the effort is focused on ARM.

**Comment by voicenoise** [comment]
thanks anyway... i'm not really happy with fs-uae :-(  my scripts with amyberry are perfect and fs-uae is so bad with configs etc... hoping for a future x86 version. 
And it still has to be said, for me is amyberry the best amiga emulator ;-) cu
