### ISSUE TITLE
Error using your precompiled binary

### ISSUE THREAD

**Issue by caitsith01** [midwan/amiberry#50]
Hi - using your precompiled binary here: https://github.com/midwan/amiberry/releases

Placing this in a folder, making it executable and running it results in the error "SDLTrueTypeFont::SDLTrueTypeFont. Couldn't open data/FreeSans.ttf".

I assume this is supposed to be packaged with the binary?  I have installed all of the dependencies you mention.

**Comment by caitsith01** [comment]
I should add this is on an RPi3 running retropie using your RPi3 binary.

**Comment by midwan** [comment]
@caitsith01 
The binary is not packaged with the rest of the uae4arm content, e.g. data folders, config, icons and fonts. This was meant as a drop-in replacement, so I didn't package those together assuming they will already be in place.

I can update the release to include those to avoid such issues of course. :)

**Comment by caitsith01** [comment]
Understood.  So if I grab the source zip, dump that in the same folder and change ownership etc, should work, right?

**Comment by caitsith01** [comment]
Might be worth doing a full package so that people like me trying to do a 'clean' install can use it.  I was worried I would end up with old config stuff that clashed with the new version.

**Comment by midwan** [comment]
@caitsith01 
I'm uploading a full package now, give me a few minutes. :)

**Comment by midwan** [comment]
@caitsith01 
Ok, try getting the "full" package from https://github.com/midwan/amiberry/releases/tag/v2.1 now. ;)
