### ISSUE TITLE
Warp Mode

### ISSUE THREAD

**Issue by ransom1122** [midwan/amiberry#501]
Hi midwan,

Hope your having/had a great time with your vacation ;)

I have a query for you wether you can implement Warp Mode for Amiberry? 

Winuae implements it by maximizing the fps anywhere from 4 to 500, Great for any games that may take long to load.

If implemented hopefully we can have a shortcut key that can me mapped to warp mode?

Later
ransom

**Comment by CypherXG** [comment]
Why do you need a warp mode?

**Comment by ransom1122** [comment]
I wouldn't say need. I run more then just whdload, I understand floppy speeds can be sped up but can cause incompatibility issues, hence the a good reason to keep floppy speeds at normal but be able to use a warp mode during loading times.

**Comment by midwan** [comment]
I've added some support for Warp mode in the current `dev` branch, but it hasn't been tested yet.
Also, there's no key you can map for it yet. I'll look into it slowly during the testing phase and see if it makes sense to use that feature at all. :)

**Comment by ransom1122** [comment]
Happy to test when it becomes available

**Comment by midwan** [comment]
This is also related to #504 since the framerate value is changed when Warpmode is enabled.

**Comment by midwan** [comment]
This is now implemented, but only for SDL2 versions (not Dispmanx).
It's toggled with the same hotkey that WinUAE uses: END + Pause
