### ISSUE TITLE
Amiberry CD32 NVRAM Emulaton

### ISSUE THREAD

**Issue by Wulmund** [midwan/amiberry#502]
Apologies as I'm a new user and not posted before, if I've got anything wrong or not enough detail, please be kind...

When emulating the CD32, certain .ISO files are either unable to write to the emulated NVRAM, or unable to reference it when they load through the emulator.
You don't get an error message, the game just loads without high scores or progress that on the original machine would have been saved automatically.

**To Reproduce**
I'm using custom .uae config files, theya re clones of each other, the only difference is that they reference the relevant .ISO file.
If you load a game e.g. Arcade Pool.iso (or whatever filename variant you have) , do something like enter player info, set a pool high score, exit back to the menu and exit. Or Overkill & Lunar-C.iso (or whatever you call your .iso file), play the game and set a high score.

Then restart the emulator/game.

**Expected behavior**
In these games, the player info (Arcade Pool) and the high scores (both) should have been saved to the NVRAM file, It should then be read from that file and be seen in the game when its restarted - however this does not happen due to some kind of bug.

**Screenshots**

I'm using the latest version of RetroPie (Rasbpian).

** Investigating **
Some games can work with the emulated NVRAM e.g. Pinball Fantasies (which auto-saves high scores) and Diggers (where you manually create a save).
I have tried giving each game it's own NVRAM file but this does not lead the game to be able to save or then read from (whichever is the problem?) the NVRAM file.
I have made the NVRAM file readable to everyone in Linux.
I have tried different (other than the default) file locations for the NVRAM file.
I have reinstalled and tested with just one game at a time.

Note that if you specify  different location for Overkill, it can create a new NVRAM file if it doesn't exist. However it then either doesn't write to is, or does not read the values it's written and then make them available in the game when it next starts.

**Comment by Wulmund** [comment]
Have I posted this in the wrong place?

**Comment by midwan** [comment]
@Wulmund 
No, this is the right place. Just didn't have a chance to look into it yet. :)
I'll try to recreate this and see if we can see what's happening.

**Comment by Wulmund** [comment]
@midwan thanks let me know what I can provide to help you recreate the issue

**Comment by CypherXG** [comment]
> I have made the NVRAM file readable to everyone in Linux.

Öhm.....only readable? Not both readable and writable? 
Ist the Directory also eadable and writable?

Sry that i'm asking...

**Comment by Wulmund** [comment]
Read and writable.

I don’t know why I put “readable”. Sorry. 

It didn’t make any difference to the functioning.

**Comment by Wulmund** [comment]
@CypherXG Are you running .iso files? My Pinball Fantasies.iso was one of the 2 I got to work correctly (read/write nvram files).

**Comment by CypherXG** [comment]
Running my own ccd File. All my CD32 Games are in ccd.

**Comment by Wulmund** [comment]
Try a .iso and see if it works?

**Comment by midwan** [comment]
@Wulmund 
I tested Arcade Pool on Amiberry and WinUAE, and it behaves the same way - the changes to the Player Name are not saved in both cases.

Did you compare with WinUAE in your tests, for those that fail to save? This may be an issue with WinUAE itself.

**Comment by Wulmund** [comment]
I don’t have winUAE. I will try to install and run it on my laptop, if it’s capable. Last time I used WinUAE, the controllers had real issues and I gave up with it, years ago.

**Comment by Wulmund** [comment]
@midwan I’m wondering if the .iso images themselves could be the issue? On my real machine, Arcade Pool, Overkill, Sensible Soccer images burnt to disc work fine, but do not save to the machine’s NVRAM. Just need real copies to test this against.

**Comment by midwan** [comment]
@Wulmund 
Could be. I cannot find anything else that might be wrong from the emulator side on this, and since WinUAE also behaves the same way with these titles it can either be a generic problem that is inherited from there, or an issue with these specific titles/ISO images.

Either way, I don't see what I can do about it from here. If it's proven to be an issue with WinUAE, it should be reported upstream so that it gets fixed there, and we'll merge those fixes in Amiberry as well afterwards.
