### ISSUE TITLE
Animation glitches in Supercars

### ISSUE THREAD

**Issue by emuchicken** [midwan/amiberry#503]
Graphics glitches in animation.  In both Intro, results screen and even entering your name (flashes white instead of clear )

**To Reproduce**
1. Load up Supercars (either whdload or adf)
2. See error in intro or upon name entery

**Expected behavior**
Smooth animation with transparency. I assume the emulator is displaying transparent pixels as white.

**Screenshots**
Added gifs
![videotogif_2019 08 19_07 14 15](https://user-images.githubusercontent.com/45140115/63231146-46a78000-c252-11e9-8951-3a9ce9a6fa12.gif)
![videotogif_2019 08 19_07 15 02](https://user-images.githubusercontent.com/45140115/63231147-4a3b0700-c252-11e9-8581-76f11144b1da.gif)

Raspberry pi 3b+ / emulation station via retropie latest updates.

**Comment by midwan** [comment]
@emuchicken 
Thanks for reporting this. It's fixed in the `dev` branch, will be merged to `master` as soon as beta testing is finished.

**Comment by emuchicken** [comment]
Thanks for fixing this!!
Legendary game. :)

**Comment by emuchicken** [comment]
Latest v3.0 release, glitches are still present.

**Comment by midwan** [comment]
@emuchicken 
Hmm, I only noticed some gfx glitches in the loading screen, but nowhere else. Is that what you mean?
Certainly not the same as originally reported?

**Comment by emuchicken** [comment]
Start the game, enter the car shop (on the right) ... Check the receptionist typing, and bits of animation there.  The eyes when blinking, etc.

**Comment by emuchicken** [comment]
On the intro (wait for reporters) 
![image](https://user-images.githubusercontent.com/45140115/69014410-5a878d00-09cd-11ea-8627-7c2bda22079a.png)
Receptionist in car shop
![image](https://user-images.githubusercontent.com/45140115/69014421-6a9f6c80-09cd-11ea-845d-70598d4ef253.png)

**Comment by midwan** [comment]
Hm, I can't recreate this here (testing on an RPI3B+, on standard Raspbian Buster).
The animation in the intro seems correct, not like your screenshot.
Same with the typing in the background...

I used a default A500 config from Quickstart, then loaded the ADF version of the game from there.
Did you do something different? Can you try the above steps?

**Comment by emuchicken** [comment]
I'm running through the whdload lha route.  I will give the adf a shot now.

**Comment by emuchicken** [comment]
Adf with 500 settings works fine. Perhaps the fixes don't transfer to a1200 whdload?  Or is it a bad dump for whdload ? :/

**Comment by midwan** [comment]
@emuchicken 
Or it might be a setting in the XML settings file that is incorrect.
You can try changing some settings after it's loaded to see if they affect the situation (e.g. blitter mode, Fast copper, etc)
