### ISSUE TITLE
gfx_framerate option different from WinUAE

### ISSUE THREAD

**Issue by rsn8887** [midwan/amiberry#504]
**Describe the bug**
gfx_framerate=1 disables frameskip in WinUAE.
gfx_framerate=1 enables frameskip in Amiberry.

Why break .uae file compatibility like this?

Or maybe I am missing something.

**Comment by ransom1122** [comment]
🤔

**Comment by midwan** [comment]
This was a deliberate change to simplify the function, done by TomB in uae4arm originally.
I could change it to match WinUAE, but we'll need GUI changes as well to be able to specify the desired Framerate - WinUAE has a slider there for this purpose.

**Comment by midwan** [comment]
I've added a poll about which approach people would prefer:

- The current Checkbox to enable/disable Frameskip (which would set the framerate to half, like today)
- WinUAE's approach with a slider and a textbox, for setting the desired framerate.

The current approach requires less user interaction (just one click for ON/OFF), while the slider would require more clicks (and possibly keyboard input for setting a value in the textbox).

The poll is on Amiberry's Facebook page here: https://www.facebook.com/amiberry.emulator/posts/2699784733368102
