### ISSUE TITLE
Newest dev does not compile

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#506]
**Describe the bug**
Compiling error

**To Reproduce**
[alarm@alarmpi4 amiberry-dev]$ make PLATFORM=rpi4-sdl2-dispmanx
Makefile:471: extraneous text after 'else' directive
make -C guisan-dev
make[1]: Entering directory '/home/alarm/amiberry-dev/guisan-dev'
make[1]: 'lib/libguisan.a' is up to date.
make[1]: Leaving directory '/home/alarm/amiberry-dev/guisan-dev'
g++ -o amiberry-rpi4-sdl2-dispmanx src/akiko.o src/ar.o src/aros.rom.o src/audio.o src/autoconf.o src/blitfunc.o src/blittable.o src/blitter.o src/blkdev.o src/blkdev_cdimage.o src/bsdsocket.o src/calc.o src/cd32_fmv.o src/cd32_fmv_genlock.o src/cdrom.o src/cfgfile.o src/cia.o src/crc32.o src/custom.o src/devices.o src/disk.o src/diskutil.o src/dlopen.o src/drawing.o src/events.o src/expansion.o src/fdi2raw.o src/filesys.o src/flashrom.o src/fpp.o src/fsdb.o src/fsdb_unix.o src/fsusage.o src/gayle.o src/gfxboard.o src/gfxutil.o src/hardfile.o src/hrtmon.rom.o src/ide.o src/inputdevice.o src/keybuf.o src/main.o src/memory.o src/native2amiga.o src/rommgr.o src/rtc.o src/savestate.o src/scsi.o src/statusline.o src/traps.o src/uaelib.o src/uaeresource.o src/zfile.o src/zfile_archive.o src/archivers/7z/7zAlloc.o src/archivers/7z/7zBuf.o src/archivers/7z/7zCrc.o src/archivers/7z/7zCrcOpt.o src/archivers/7z/7zDec.o src/archivers/7z/7zIn.o src/archivers/7z/7zStream.o src/archivers/7z/Bcj2.o src/archivers/7z/Bra.o src/archivers/7z/Bra86.o src/archivers/7z/LzmaDec.o src/archivers/7z/Lzma2Dec.o src/archivers/7z/Xz.o src/archivers/dms/crc_csum.o src/archivers/dms/getbits.o src/archivers/dms/maketbl.o src/archivers/dms/pfile.o src/archivers/dms/tables.o src/archivers/dms/u_deep.o src/archivers/dms/u_heavy.o src/archivers/dms/u_init.o src/archivers/dms/u_medium.o src/archivers/dms/u_quick.o src/archivers/dms/u_rle.o src/archivers/lha/crcio.o src/archivers/lha/dhuf.o src/archivers/lha/header.o src/archivers/lha/huf.o src/archivers/lha/larc.o src/archivers/lha/lhamaketbl.o src/archivers/lha/lharc.o src/archivers/lha/shuf.o src/archivers/lha/slide.o src/archivers/lha/uae_lha.o src/archivers/lha/util.o src/archivers/lzx/unlzx.o src/archivers/mp2/kjmp2.o src/archivers/wrp/warp.o src/archivers/zip/unzip.o src/caps/caps_amiberry.o src/machdep/support.o src/osdep/bsdsocket_host.o src/osdep/cda_play.o src/osdep/charset.o src/osdep/fsdb_host.o src/osdep/amiberry_hardfile.o src/osdep/keyboard.o src/osdep/mp3decoder.o src/osdep/picasso96.o src/osdep/writelog.o src/osdep/amiberry.o src/osdep/amiberry_filesys.o src/osdep/amiberry_input.o src/osdep/amiberry_gfx.o src/osdep/amiberry_gui.o src/osdep/amiberry_rp9.o src/osdep/amiberry_mem.o src/osdep/amiberry_whdbooter.o src/osdep/sigsegv_handler.o src/sounddep/sound.o src/osdep/gui/UaeRadioButton.o src/osdep/gui/UaeDropDown.o src/osdep/gui/UaeCheckBox.o src/osdep/gui/UaeListBox.o src/osdep/gui/InGameMessage.o src/osdep/gui/SelectorEntry.o src/osdep/gui/ShowHelp.o src/osdep/gui/ShowMessage.o src/osdep/gui/SelectFolder.o src/osdep/gui/SelectFile.o src/osdep/gui/CreateFilesysHardfile.o src/osdep/gui/EditFilesysVirtual.o src/osdep/gui/EditFilesysHardfile.o src/osdep/gui/PanelAbout.o src/osdep/gui/PanelPaths.o src/osdep/gui/PanelQuickstart.o src/osdep/gui/PanelConfig.o src/osdep/gui/PanelCPU.o src/osdep/gui/PanelChipset.o src/osdep/gui/PanelCustom.o src/osdep/gui/PanelROM.o src/osdep/gui/PanelRAM.o src/osdep/gui/PanelFloppy.o src/osdep/gui/PanelHD.o src/osdep/gui/PanelInput.o src/osdep/gui/PanelDisplay.o src/osdep/gui/PanelSound.o src/osdep/gui/PanelMisc.o src/osdep/gui/PanelSavestate.o src/osdep/gui/main_window.o src/osdep/gui/Navigation.o src/osdep/arm_helper.o src/newcpu.o src/newcpu_common.o src/readcpu.o src/cpudefs.o src/cpustbl.o src/cpuemu_0.o src/cpuemu_4.o src/cpuemu_11.o src/cpuemu_40.o src/cpuemu_44.o src/jit/compemu.o src/jit/compstbl.o src/jit/compemu_fpp.o src/jit/compemu_support.o src/archivers/7z/BraIA64.o src/archivers/7z/Delta.o src/archivers/7z/Sha256.o src/archivers/7z/XzCrc64.o src/archivers/7z/XzDec.o -lbcm_host -lvchiq_arm -L/opt/vc/lib -Wl,-rpath=/opt/vc/lib -L/usr/lib -Wl,-rpath,/usr/lib -Wl,--enable-new-dtags -lSDL2 -lSDL2_image -lSDL2_ttf -lguisan -Lguisan-dev/lib -flto -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lpthread -lz -lpng -lrt -lxml2 -lFLAC -lmpg123 -ldl -lmpeg2convert -lmpeg2
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x4): undefined reference to `ARM_doline_n1'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x8): undefined reference to `NEON_doline_n2'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0xc): undefined reference to `NEON_doline_n3'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x10): undefined reference to `NEON_doline_n4'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x14): undefined reference to `NEON_doline_n5'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x18): undefined reference to `NEON_doline_n6'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x1c): undefined reference to `NEON_doline_n7'
/usr/bin/ld: src/drawing.o:(.data.rel.ro+0x20): undefined reference to `NEON_doline_n8'
collect2: error: ld returned 1 exit status
make: *** [Makefile:499: amiberry-rpi4-sdl2-dispmanx] Error 1

There are two problems here. The first is in the Makefile, the other in src/drawing.o

**Comment by solskogen** [comment]
And this is the fix :-)

diff --git a/Makefile b/Makefile
index 42cbc47..fb346ed 100644
--- a/Makefile
+++ b/Makefile
@@ -468,7 +468,9 @@ ifdef AARCH64
 OBJS += src/osdep/aarch64_helper.o
 src/osdep/aarch64_helper.o: src/osdep/aarch64_helper.s
        $(CXX) $(CFLAGS) -Wall -o src/osdep/aarch64_helper.o -c src/osdep/aarch64_helper.s
-else ifeq($(PLATFORM),rpi1)
+endif
+
+ifeq ($(PLATFORM),rpi1)
 OBJS += src/osdep/arm_helper.o
 src/osdep/arm_helper.o: src/osdep/arm_helper.s
        $(CXX) $(CFLAGS) -Wall -o src/osdep/arm_helper.o -c src/osdep/arm_helper.s

**Comment by midwan** [comment]
Oops, sorry about that. Thanks for the quick fix.
