### ISSUE TITLE
Cursor keys to use the mouse?

### ISSUE THREAD

**Issue by Bonedwarf** [midwan/amiberry#507]
Wasn’t sure if it’s a bug or a feature request. I have a Pi in a case, and the built in controls, the dpad sends cursor key input. Now when I switch the controller to be the mouse, I get a mouse button function just fine, but when I hit the cursor keys the mouse pointer moves ever so slightly, though not in the expected direction, like maybe a pixel or two. 

Now I don’t know if that movement is a bug or coincidence. 

So if it’s not a feature, I’d like to request it. (My other requested feature is a virtual keyboard but I think I read that’s coming.)

**Comment by midwan** [comment]
I'm not sure exactly what you mean...
- Do you want to control the mouse inside the emulation (i.e. AmigaOS?) using the keys? You can already do that - AmigaOS provides that shortcut itself, using the LAmiga and cursor keys (and if you also hold down Shift, it will "jump" longer distances).
- Do you want to control the mouse in Amiberry's GUI using the keyboard? There's no real need for that, as we already have keyboard and controller support for all the items in the GUI.

**Comment by Bonedwarf** [comment]
I had totally forgotten you could do that on the Amiga. It has been 25 years since I used a real one though.

I’m trying to control the mouse inside the emulation. The case I’ve got the Pi in only has a handful of buttons that send keypresses to the Pi. Sadly it’s just letters (z, x etc...) and there’s no way to get the thing to produce an Amiga key, so I can’t use the cursor keys to move the pointer and I’m not sure if there’s a way to get around this in the emulator currently or if it’s just impossible without you adding a function like you did for quit, open menu etc... to add your own control to toggle the Amiga key so Amiberry thinks it’s being pressed.

I’d been trying to map the dpad to move the mouse, but the controls seem to be listed as Retroarch Keyboard or similar, and in the menu panel where you can map controls to the dpad, North, south etc... it’s all greyed out.

I hope all this makes sense. Happy to provide more clarification if needed. (I can take pictures if need be.)

**Comment by midwan** [comment]
Are you using a game controller with analog sticks?
We have an option in the Input panel to map those to Mouse movements, for exactly this purpose. You can pick which one (Left, Right or Both) will be mapped.

**Comment by Bonedwarf** [comment]
The pad on this case, the Waveshare Pi43, has simple dpad that just sends cursor key presses. No analog. I’ve tried every option in Amiberry to try and make it move the mouse.

If I could even map a keypress to simulate an Amiga key that’d be enough.

**Comment by midwan** [comment]
@Bonedwarf 
Do you have LAlt/RAlt keys in your solution? If so, you can now emulate the LAmiga/RAmiga keys with that, if you enable the new option in `amiberry.conf` with:
`swap_win_alt_keys=yes`

(this only works in the `dev` version for now)

**Comment by Bonedwarf** [comment]
I might be able to remap one of the buttons to that. Thanks for the heads up!
