### ISSUE TITLE
libsdl2 from archive.raspberrypi.org repo Buster branch

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#512]
Has anyone tested these "new" RPi-special `libsdl2` packages? https://archive.raspberrypi.org/debian/pool/main/libs/libsdl2/

Such did not exist yet in the Stretch branch of this repo. Compared to those from Raspbian repo (which match the ones from Debian repo), those have some RPi-specific patches. Although I could not fine some word about KMSDRM, at least it's worth giving it a try, so one might be able to skip the SDL2 compiling on RPi?

**Comment by solskogen** [comment]
You can skip SDL2 compiling on the RPi if you use X11 rather than KMSDRM. But if you want / need KMSDRM you must compile it your self (probably because the KMSDRM-driver in SDL2 is not enabled by default)

**Comment by midwan** [comment]
@MichaIng 
I believe RetroPie used a custom SDL2 compile even on Stretch.
In any case, like @solskogen mentioned: If you want to use SDL2 from the Desktop, you don't need to compile it yourself for the RPI platforms. The repo-provided versions are good enough, and actually more recent version (2.0.10 vs 2.0.9) than those provided by RetroPie.

**Comment by MichaIng** [comment]
@solskogen @midwan 
Okay, I think so. Just to make it clear, the repo I linked above is not the Raspbian repo. Raspbian ships the Debian-default libsdl2 packages, just compiled for the RPi1/Zero armv6hf architecture. On Raspbian, there is no other libsdl2 package available.

But the RPi comes with the additional archive.raspberrypi.org APT repo, which contains e.g. the kernel/bootloader/firmware packages and some other RPi-specific ones, as well RPi-specific Kodi and FFmpeg packages, Chromium and all such, which require or benefit from hardware specific builds/configs, supporting the RPi audio/video (GPU acceleration) capabilities.
And the new Raspbian Buster image (which provides RPi4 support as well) now ships this repo with a Buster-compatible branch of course, which contains RPi-specific libsdl2 packages.

So I was hoping that this SDL2 is compiled with KMSDRM. Will do a quick test tomorrow.

**Comment by midwan** [comment]
@MichaIng 
Thanks, let me know if you find something interesting and we can revisit this. :)
