### ISSUE TITLE
[JIT-FPU] Lightwave's Modeler.FP crashes Amiberry on startup

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#513]
**Describe the bug**
Launching Lightwave's "Modeler.FP" application crashes Amiberry, if JIT FPU is enabled.

**To Reproduce**
1. Boot an environment that has Newtek's Lightwave installed.
2. Double click on Modeler.FP
3. Amiberry crashes before Modeler opens its window, if JIT FPU is enabled

**Expected behavior**
Modeler should open up without crashing the emulator

**Platform tested**
- RPI4, SDL2-Dispmanx, 32-bit, Raspbian Buster Desktop

**Comment by ziosante** [comment]
Hi,
I've experimented same problem with ClassAction 4.40 when JIT PFU is enabled
[http://aminet.net/util/wb/classaction.lha](url)

Launch the program and emulator crash

dmesg output on linux console:
[  392.831569] Alignment trap: not handling instruction ed8c1b00 at [<5b1c3e28>]
[  392.831581] Unhandled fault: alignment exception (0x801) at 0x606c9eda
[  392.831595] pgd = 27ac04dd
[  392.831601] [606c9eda] *pgd=3307f835, *pte=1a17555f, *ppte=1a175c7e

**Platform tested**

- RPI2, SDL2-Dispmanx, 32-bit, DietPi

**Comment by midwan** [comment]
@ziosante I've reported this to TomB: https://github.com/PandTomB/uae4arm/issues/4

He is the brains behind the current JIT implementation for ARM, so I'm hoping he might find a fix. ;)

**Comment by midwan** [comment]
Fixed with c47b8b5257f763ba1545e1bf653ab1ac1e2b7857
