### ISSUE TITLE
[DietPi] Non responsive keyboard after quit

### ISSUE THREAD

**Issue by JerichoCross** [midwan/amiberry#514]
**Describe the bug**
When using the DietPi-based distribution, selecting Quit drops you back to the command line but the keyboard is unresponsive. The keyboard works fine whilst Amiberry is running. The Pi had not frozen, however, because I was able to interract with it via SSH from another machine.

**To Reproduce**
1. Boot the DietPi-based Amiberry distribution on a Pi 3b
2. Select 'Quit' in Amiberry
3. Try to type something

**Expected behavior**
Normal CLI behaviour - ability to issue commands via the keyboard

**Screenshots**

**Hardware**
Raspberry Pi 3b

**Comment by midwan** [comment]
@JerichoCross 
This is a known bug, but it's not related to Amiberry itself - it's something to do with the DietPi environment.

In any case, there's an update incoming to bring it up to Buster, so we could make sure this is also fixed there.

**Comment by midwan** [comment]
Reported here: https://github.com/MichaIng/DietPi/issues/3104

**Comment by MichaIng** [comment]
@JerichoCross 
Thanks for your report.

Actually it sounds like being this bug, which has been resolved with DietPi v6.23 already: https://github.com/MichaIng/DietPi/pull/2718

Can you verify the following:
- You updated to the latest DietPi version.
- You boot into Amiberry using the `dietpi-autostart` Amiberry fast boot (index 6) option, or flashed the RPi Amiberry image which has this setting applied automatically?
- When exiting Amiberry, no login prompt appears, only a blank screen with a blinking dash at best?
- Is this changing, when you hit `Ctrl+Alt+F1` (actively switch to TTY1, if not yet the case).
- Is this changing when you run `systemctl enable --now getty@tty1` from SSH session?
- Can you verify `systemctl is-active systemd-logind` prints `active`?
