### ISSUE TITLE
Problem with some CD32 games as CUE/BIN files

### ISSUE THREAD

**Issue by GeorgeSpiggott** [midwan/amiberry#516]
After a Summer away from my Pi Iv'e got back to trying to get a working copy of Seek and Destroy CD32. Having achieved that I've been converting the existing CUE/ISO/WAV files to a single CUE/BIN combination. This has worked well for Pinball Illusions and Pinball Fantasies which are much easier to play on a Pi/gamepad with the CD32 versions and also Fire and ICE and Skidmarks 2.

My problem is that in this CUE/BIN format Seek and Destroy CD32 (and Alien Breed 3D CD32 bring up the cats eyes/no bios found screen.  I don't see how this is possible since the game runs fine as a CUE/ISO/WAV and four other games run fine as CUE/BIN files.

The only other modification I am making is to the CUE files by adding " CD32" to the title to get Amiberry to recognise the game as a CD32 game. Also of note when Seek and Destroy does boot as CUE/ISO/WAV files it does not auto create CD32 joypad controls and they must be set manually. This is easily resolved by creating a config file but I thought I'd let you know.

I have had issues with Seek and Destroy before is this thread here: https://github.com/midwan/amiberry/issues/438
I've linked to it to give a little background. I am now using a completely fresh install of Retropie (5.0) with new CD32 ROMS. I'm not sure which solved the problems from that thread but they are resolved now. I'd also like to take this opportunity to thank you for all your help.

**Comment by midwan** [comment]
I've just tested this with the image of Seek and Destroy I had (it's a .cue/.img combination), with the current `dev` - it worked without a problem.

If you're getting the AROS rom instead, make sure you have correct CD32 ROMs in place? It will switch to that only if the correct ROM is not found.

**Comment by GeorgeSpiggott** [comment]
Yes mine works fine as a .cue/.img(/.wav) combination. It is when I convert it to a .cue/.bin that I have the problem. I have some other CD32 games that I have converted that work fine so it can't be the CD32 roms. 

I suppose the short answer is don't use the converted version since the .cue/.img(/.wav) works well enough. I just think that it is odd that it is bringing up missing bios.

Thanks
