### ISSUE TITLE
cd32 cue video problems retropie

### ISSUE THREAD

**Issue by rickude** [midwan/amiberry#517]
When using amiga cd32 cue files for launching games the resolutions are not correct sometimes screen not fitting e.g. Sensible soccer left part of screen not fully displayed.

lost vikings top of screen not correctly displayed.

many cd32 games are like this when using proper bin cue files to play the games.

loading the same game using lha files gives perfect video resolution.

other retropie users also report the same only when launching cd32.

**Comment by CypherXG** [comment]
This has nothing to do with the cue File. Cue has only information from the CD about the Data and Audio Tracks, Format etc.
Many Games from CD32 have a wrong Screen format.
@Midwan: Is it possible to add a vertical screen slider like the horizontal?

**Comment by rickude** [comment]
That's what I meant proper cd32 games.

So this is a known issue, is it being worked on or any workarounds?

**Comment by midwan** [comment]
I believe we fixed this issue with the changes now merged into the `dev` branch, at least the titles I've tried all seem to work and display fine.

I'll test the specific ones you mentioned above also next week, just to be sure. Otherwise this might already be resolved (the `dev` branch will eventually be merged into `master` and become the next stable release).

**Comment by rickude** [comment]
I've updated from source again today, I have most titles on bin, cue format would you be able to fix if I give details of ones need adjusting.

**Comment by midwan** [comment]
Updating from source will always get you the latest from the `master` branch, not beta versions from `dev`.  ;)

What are the exact filename(s) of the images you're testing with please?

**Comment by midwan** [comment]
This is now fixed in `dev`, we'll merge it to `master` as soon as beta testing is finished

**Comment by rickude** [comment]
Thanks for letting me know.

So eventually after testing is done this will be available with amiberry
under retropie if I update from source regually and update xml hopefully
those games will have video settings fixed.

**Comment by rickude** [comment]
Sensible Soccer - European Champions (Europe) (En,Fr,De,It).cue
Lost Vikings, The (Europe).cue

games from redump.org 2019-05-11

thanks i am really looking forward to getting these working.

**Comment by midwan** [comment]
@rickude 
Yeap, as I said this is already fixed now. It's just a matter of finalizing the polishing, bug fixes etc. and releasing the new version. Then you'll get the update in RetroPie as well if you update from source (and I guess from binary eventually, when they provide a new one).

**Comment by rickude** [comment]
Arabian nights also height needs adjusting

If your able to fix in future so I can have all working I would be more
than happy to test every game I have and report if any issues.

**Comment by midwan** [comment]
@rickude 
The change I've implemented in `dev`, changes the CD32 settings to full Overscan display settings, so it will show the full extend of what the emulated device could display. :)

**Comment by rickude** [comment]
Massive thanks for all your work I'm a huge amiga fan and looking forward
so much to having this working.

**Comment by rickude** [comment]
Any chance of letting me know when amiberry under retropie gets updated
with your amiga cd32 fixes.  Or should I just keep eye on retropie updates
and amiberry.

Thanks
Rick

**Comment by midwan** [comment]
@rickude 
As soon as this is merged into `master`, you can build it under RetroPie as well.
Before that, you can only get it manually by checking out the `dev` branch, compiling and then placing the resulting binary in RetroPie's right location `/opt/retropie/emulators/amiberry/`

**Comment by rickude** [comment]
I have no clue how to do that but thanks for letting me know.  I will try
to learn.
