### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#518]
Is there anyway to contribute/donate for this project? Really looking forward to more fixes and features in coming releases!

Tack för allt så här långt! Du/ni gör ett fantastiskt bra jobb!

F

**Comment by midwan** [comment]
@stuffu 
Thanks for the kind words!
I didn't really have a donation thing up until now, but I've added one in the main page just in case someone wants to help: https://paypal.me/pools/c/8apqkBQovm

Tack så mycket!
