### ISSUE TITLE
Long time goal: Werror and Wall

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#519]
**Is your feature request related to a problem? Please describe.**
No, just code cleanness.

**Describe the solution you'd like**
Add -Wall and -Werror to CFLAGS

**Additional context**
Get rid of all warnings from the compiler

**Comment by midwan** [comment]
This is kind of self-evident, do we really need an open issue for it? It will just linger here for a long time, without any reason I believe.

**Comment by solskogen** [comment]
Until they are default CFLAGS I think it should

**Comment by midwan** [comment]
This doesn't look possible, if we want to be able to merge upstream WinUAE sources which have a lot of such issues. If they are fixed upstream, they will of course be merged into Amiberry as well, and things that are specific to Amiberry should give no warnings.
