### ISSUE TITLE
Improve Custom Controls GUI

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#520]
Whenever I start a game, wether in ADF or WHDL with a well configured controller, using retroarch file type and everything :
**retroarchcustom.cfg**
```
#aspect_ratio_index = "21"
aspect_ratio_index = 
cache_directory = /recalbox/share/extractions/
cheat_database_path = /recalbox/share_init/cheats/cht/
cheat_settings_path = /recalbox/share/cheats/saves/
cheevos_enable = false
cheevos_hardcore_mode_enable = false
config_save_on_exit = false
core_options_path = /recalbox/share/system/configs/retroarch/cores/retroarch-core-options.cfg
fastforward_ratio = -1.0
fps_show = false
framecount_show = false
input_autodetect_enable = false
input_enable_hotkey = "escape"
input_enable_hotkey_btn = 10
input_exit_emulator_btn = 9
input_hold_fast_forward_btn = 16
input_joypad_driver = udev
input_libretro_device_p1 = 1
input_libretro_device_p2 = 1
input_load_state_btn = 2
input_menu_toggle_btn = 0
input_player1_a_btn = 1
input_player1_analog_dpad_mode = 1
input_player1_b_btn = 0
input_player1_down_btn = 14
input_player1_joypad_index = 0
input_player1_l2_btn = 6
input_player1_l3_btn = 11
input_player1_l_btn = 4
input_player1_l_x_minus_axis = -0
input_player1_l_x_plus_axis = +0
input_player1_l_y_minus_axis = -1
input_player1_l_y_plus_axis = +1
input_player1_left_btn = 15
input_player1_r2_btn = 7
input_player1_r3_btn = 12
input_player1_r_btn = 5
input_player1_r_x_minus_axis = -3
input_player1_r_x_plus_axis = +3
input_player1_r_y_minus_axis = -4
input_player1_r_y_plus_axis = +4
input_player1_right_btn = 16
input_player1_select_btn = 8
input_player1_start_btn = 9
input_player1_up_btn = 13
input_player1_x_btn = 2
input_player1_y_btn = 3
input_reset_btn = 1
input_rewind_btn = 15
input_save_state_btn = 3
input_screenshot_btn = 4
input_shader_next_btn = 7
input_shader_prev_btn = 6
input_state_slot_decrease_btn = 14
input_state_slot_increase_btn = 13
joypad_autoconfig_dir = /recalbox/share/system/configs/retroarch/inputs/
libretro_log_level = 0
log_verbosity = false
menu_driver = rgui
menu_swap_ok_cancel_buttons = "true"
network_cmd_enable = "true"
rewind_buffer_size = 10
rewind_enable = false
rewind_granularity = 2
rgui_show_start_screen = false
savefile_directory = /recalbox/share/saves/segacd
savestate_auto_load = false
savestate_auto_save = false
savestate_directory = /recalbox/share/saves/segacd
screenshot_directory = /recalbox/share/screenshots/
system_directory = /recalbox/share/bios/
video_aspect_ratio_auto = true
video_font_path = /usr/share/fonts/truetype/ubuntu_condensed.ttf
video_gpu_screenshot = true
video_scale_integer = false
video_shader = /recalbox/share_init/shaders/scanline.glslp
video_shader_dir = /recalbox/share_init/shaders/
video_shader_enable = true
video_smooth = false
video_threaded = true

```

the Custom Controls submenu in GUI appears like that :
![IMG_20190627_222530150](https://user-images.githubusercontent.com/1405681/66778586-682c8d00-eecc-11e9-8c86-4ad244444181.jpg)

In the wiki the Custom Controls submenu is documented like that :
![687474703a2f2f756c74696d617465616d6967612e636f2e756b2f486f7374656450726f6a656374732f526574726f506965416d6967612f67756964652f416d6962657272795f4d656e7531335f437573746f6d50616e656c2e706e67](https://user-images.githubusercontent.com/1405681/66778660-aa55ce80-eecc-11e9-9080-a2daaf4736f4.png)

So as you can see, the [R] indicates that the controller configuration is well and loaded but :
- Hotkey isn't checked even if the controller uses the hotkey schemes
- I would expect each key association to be filled with the correct command (D-PAD Up : Joystick Up, South: Joy Button 1, etc etc like your wiki example show for Select or Start) but they are totally void.

Is it supposed to be like that or what is missing in configuration to make it appear correctly ?

**Comment by midwan** [comment]
@Voljega 
Please update Amiberry (either from `master` or `dev`) and check again.
I recently fixed a bug that caused some controller mapping options not to be read correctly, so you would have incorrect/invalid settings in custom controls there.

**Comment by Voljega** [comment]
@midwan > thank you Dimitri, I will try as soon as possible

**Comment by Voljega** [comment]
Hello, well this is still not working

**Comment by HoraceAndTheSpider** [comment]
On you first picture, that is correct. 

You have not clicked the hotkey “Radio  button” (under “function key”) so you will only see customisations if you (or the xml) sets some for the game. 

Hopefully if you do, you will see that hotkey+start is quit etc.

**Comment by Voljega** [comment]
Yes you're right.

However I still think with None function key, you should show the current standard mappings for the buttons and direction, it would be more clear

**Comment by HoraceAndTheSpider** [comment]
> However I still think with None function key, you should show the current standard mappings for the buttons and direction, it would be more clear

I would like to, but it creates a lot of line-specific code to show defaults, plus it then has to adapt for different control mode: default / joystick / mouse / cd32 .   A lot of specifics for not a lot of gain.

I am going to do a few changes in this area, so i will look at it as a possibility.

**Comment by redm123** [comment]
> Yes you're right.
> 
> However I still think with None function key, you should show the current standard mappings for the buttons and direction, it would be more clear

I like this suggestion! As a newbie who just spent quite some time trying to figure out how all the input controls and mapping works and how it all interacts between Retroarch, Amiberry, ports, joysticks, devices and games, I can only support this. Having default mappings shown in the UI would have made some things a lot clearer. (+ Optimally one would be able to see then whether an entry is the default, or was explicitly re-mapped)

I'm using Amiberry from Recalbox.

Cheers
