### ISSUE TITLE
WHDL Games database

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#521]
In the wiki there is this page about WHDL : https://github.com/midwan/amiberry/wiki/WHDLoad-Booter-(WHDBooter)-F.A.Q.

It gives this adress for accessing the db : http://whdload.rasterbar.xyz/ but it leads nowhere...

Has this been abandoned ?

And where we use the button in GUI to update the whdl db, where is it downloaded from ?

**Comment by midwan** [comment]
Thanks for reporting this, the link was incorrect.
I've updated the wiki page with the actual link:
https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/
