### ISSUE TITLE
Amlogic AMLG12B compilation error

### ISSUE THREAD

**Issue by shantigilbert** [midwan/amiberry#522]
**Describe the bug**
I am not 100% sure this is a real bug that happens to everyone or is it something on my side but just want to make sure.

latest dev branch gives me this error: 

```
Assembler messages:
Error: unknown cpu `cortex-a73.cortex-a53'
Error: unrecognized option -mcpu=cortex-a73.cortex-a53
```
When building with PLATFORM="AMLG12B"

if I change it to `-mcpu=cortex-a73` it compiles fine, I know its a minor thing, but does this happens to anybody else?

This started happening after this commit: https://github.com/midwan/amiberry/commit/5a03c3548e3a1d3b003bc086fb4d3c10512c0a1c

**Comment by midwan** [comment]
Thanks for reporting this, fixed.
