### ISSUE TITLE
8bitdo controller issues WHD load

### ISSUE THREAD

**Issue by scott8bit** [midwan/amiberry#525]
hi everyone, using pi3 and having issues getting 8bitdo Bluetooth controller to work on amiberry v2.25

ive got a few devices, USB PS4 fight stick, 8bitdo controller and Bluetooth keyboard.

my keyboard and usb stick are working perfectly fine in amiberry, however my 8bitdo will not
under any circumstances operate, even thought its showing as a recognised device in the amiberry input section within the gui

i know the controller is fine because it works on all other emulators without any issue, and its recognised with retroarch in conjunction with joystick selection, its just seems like amiberry wont play?

I wondered if anyone else has the 8bitdo and runs into any trouble with it?

**Comment by scott8bit** [comment]
update, while none of the controls are responding, the start button on the controller seems to work as a fire button. which is really strange because the start button is not mapped as a firebutton in any of the configuration files.

I cant remember the last time I updated amiberry, so im going to uninstall it and reinstall with source and see if that helps

**Comment by midwan** [comment]
In scenarios like these, I've seen that the problem was usually related to the retroarch.cfg file (I'm assuming you're using RetroPie and have mapped the controls there).

Have you gone through our wiki article on this subject https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers ?

**Comment by Solo761** [comment]
Does your 8bitdo controller has different modes it can turn on to? Like Android, iOS, Windows...

I have two 8bitdo zero gamepads and just yesterday managed to get them working with Amiberry (+Amibian). 

8bitdo Zero gamepads have few modes they can work as. If I power it by pressing start button it will turn on in Android mode, if I turn them on in this mode only fire button works, dpad doesn't work at all. But if I power it in Windows mode (start + R on zero) everything works as expected.

If yours have same options try starting them in Windows mode and try configuring them again, Maybe it'll help.

I have two zeros and managed to configure both and multiplayer works fine. As to why would someone try to use so small controllers... I have 5'' rPi LCD so I tried to make miniature setup :)

https://imgur.com/a/wyNqBPe

**Comment by scott8bit** [comment]
Sadly i still can’t get it to work. Here’s the thing the controller works perfectly fine navigating emulationstation and works on other emulators. It’s just amiberry...

Like I said it recognises it within amiberry but won’t function. I have tried changing input in amiberry example, east as firebutton j1 or j2 j3 and still won’t work.

Scratching my head!

**Comment by midwan** [comment]
@scott8bit 

Please test again with the latest commits from yesterday (in `dev`) and today (in `master`). There was a bug there that would not load all controller mapping settings correctly, in some cases. That is fixed with this commit.

**Comment by midwan** [comment]
Closing this for now, as I don't see what else I can do from my side.
If we see that this is still occurring even with the latest `dev` then we can re-open it.

**Comment by scott8bit** [comment]
Thank you for your help.

The latest build has certainly helped with the issue. I can control! However;
To get the joypad working, I have to define within amiberry that the east button is set to joy1 fire, and I have to do this with every rom launch...

(Joy1 doesn’t actually work) but it’s like it needs me to do this to ping it awake. Hard to explain.

But many thanks I will keep my eye out for more updates but as it is, it’s working with some messing.

It’s probably my end too, as I edited and messed around with all my configs prior to updating amiberry when I was trying to get it work.
