### ISSUE TITLE
Cyberstorm PPC support

### ISSUE THREAD

**Issue by phalkon13** [midwan/amiberry#527]
**Is your feature request related to a problem? Please describe.**
There is support for OS up to 3.9, but nothing for support past that.  FS-UAE, WinUAE etc.. have added support for Cyberstorm PPC functionality with the Amiga 4000/4000T to allow for install of 4.0/4.1/4.1FE Classic versions to be installed.

**Describe the solution you'd like**
Support added to allow for Cyberstorm PPC compatibility

**Describe alternatives you've considered**
I've tried using FS-UAE as well as using WinUAE, but being able to set up scripts and use Amiberry with Cyberstorm PPC ROM support would be much more desirable.  I know there are a lot of people that use Amiberry either on it's own as well as with builds like Amibian or RetroPie that have wanted something like this to allow for newer AmigaOS builds to be installed on a low-cost Raspberry Pi instead of the AmigaOne boards that are way too pricey.

**Additional context**
If this support has already been added, thank you very much.  If it hasn't, it would be very appreciated.  Amiberry does do some amazing stuff for us "frugal" Amiga fans.

**Comment by midwan** [comment]
@phalkon13 
PPC support is not feasible in the current board range I'm afraid, as it's too demanding on resources and it would make it unusable. The emulation of PPC happens with qemu in the background, which is good enough for the powerful x86 CPUs of modern desktops/laptops, but would kill the performance on the current ARM boards we have around.

Perhaps in the future, when we have faster boards available, this can become a reality.

**Comment by phalkon13** [comment]
Just to verify, are the Raspberry Pi 4 boards still not powerful enough?

**Comment by CypherXG** [comment]
No.
A good PC with Winuae have also problems to run a ppc emulation perfectly.

**Comment by juanpc2018** [comment]
Amibverry is Bare Metal like Emu68k - PiStorm?
Performance Tripple 3x, Not using RaspBerryOS.

also Odroid N2+ is much faster than Pi4B+

**Comment by solskogen** [comment]
No, amiberry is a Linux application.
