### ISSUE TITLE
Some controller DPads are not mapped correctly

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#528]
**Describe the bug**
After 99e13859edd307a4778d7a3a28bb4ff998f3f80c, some controller DPads are no longer mapped correctly. The buttons work, but the DPads do not. The same `retroarch.cfg` used to work correctly before this commit.
Changing the config as per the wiki (https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers) seems to fix the problem.

**Comment by joolswills** [comment]
The configs for my gamepads:

`USB,2-axis 8-button gamepad  .cfg`
```
input_device = "USB,2-axis 8-button gamepad  "
input_driver = "udev"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "7"
input_exit_emulator_btn = "7"
input_down_axis = "+1"
input_r_btn = "5"
input_save_state_btn = "5"
input_right_axis = "+0"
input_state_slot_increase_axis = "+0"
input_select_btn = "6"
input_left_axis = "-0"
input_state_slot_decrease_axis = "-0"
input_up_axis = "-1"
input_a_btn = "0"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "6"
input_x_btn = "2"
input_menu_toggle_btn = "2"
input_y_btn = "3"
```

`USB Gamepad .cfg`
```
input_device = "USB Gamepad "
input_driver = "udev"
input_l_btn = "4"
input_start_btn = "9"
input_down_axis = "+1"
input_r_btn = "5"
input_right_axis = "+0"
input_select_btn = "8"
input_left_axis = "-0"
input_up_axis = "-1"
input_a_btn = "1"
input_b_btn = "2"
input_x_btn = "0"
input_y_btn = "3"
```

**Comment by midwan** [comment]
@joolswills 
Thanks for the samples, they helped in figuring out where the issue was. :)
I believe it's fixed with the commit referenced above, could you please also test from your side and let me know?

**Comment by KevinGaynor** [comment]
I'm having issues with the controller directions with a Competition Pro USB controller. The buttons are all working fine, however, the left and right directions are moving diagonal left and up (when I move left) and diagonal right and down (when I move right). I have verified the positive and negative axes using the joystick test.

This is running Amiberry on the latest version of RetroPie on a Raspberry Pi 4.

Both of these configurations yield the same results:

input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"

And:

input_l_y_minus_axis = "-1"
input_l_y_plus_axis = "+1"
input_l_x_minus_axis = "-0"
input_l_x_plus_axis = "+0"

The controller (Speedlink Competition Pro) works absolutely fine on Commodore 64 (lr-vice and vice) and Arcade (lr-fba) - it is literally only with Amiberry the directions are borked.

Amiberry correctly identifies the controller as SPEEDLINK COMPETITION PRO Game Controller for Android.

**Comment by joolswills** [comment]
@midwan thanks. Will test now.

@KevinGaynor did you try the latest fix?

**Comment by joolswills** [comment]
@KevinGaynor it's likely the same issue, the fix is on the dev branch btw. If unsure how to test you can wait for this to be included in RetroPie later.

**Comment by joolswills** [comment]
@midwan Thanks. Confirmed working. Will you backport this to master (or revert the older commit) or wait for your new release? I may want to fix this in RetroPie before we include the newer release.

I may have another issue for the dev branch btw. Unrelated and may just be expected behaviour. Need to do some testing. (Glitches with fast copper on which didn't happen before with same setting on current version - happens with a simple 1.3 kickstart booting to cli. I will provide full details though after testing/bisecting).

**Comment by joolswills** [comment]
Also I just noticed the mouse speed setting doesn't seem to work (with my gamepad mapped as a mouse). Will open an issue after further testing for that too. Sorry for going off topic.

**Comment by midwan** [comment]
@joolswills 
I've added this fix to `master` as well now (I'll update the version string also a little later), so we should be OK.

Let's look into the mouse speed problem separately.

**Comment by KevinGaynor** [comment]
This is now working perfectly for me - many thanks.

**Comment by midwan** [comment]
@KevinGaynor 
Thanks for confirming!

**Comment by KevinGaynor** [comment]
No problem apologies for the delay had to wait until I got home from work! The following worked flawlessly:

input_l_y_minus_axis = "-1"
input_l_y_plus_axis = "+1"
input_l_x_minus_axis = "-0"
input_l_x_plus_axis = "+0"

This one, the character ran down and right without me doing anything but once I started moving it worked fine:

input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"

I ran three separate games and they all exhibited the same behavior. So the first method of configuration is the way to go with the joysticks :)

**Comment by joolswills** [comment]
The mouse speed issue was just due to a setting when I was looking into the dpad issue. I had use_analogue_remap enabled which broke mouse speed using dpad.

The graphical glitches I mentioned are also resolved with the recent changes.

Thanks!
