### ISSUE TITLE
Makelink to Ram: not working

### ISSUE THREAD

**Issue by lastylegp** [midwan/amiberry#529]
Creating a symbolic link to a file in ram disk with Makelink results in n function not supported.
Usage is like
makelink ram:avail c:avail soft

Works fine in any mounted hdf file though

**Comment by midwan** [comment]
This seems to work fine for me, using AmigaOS 3.1.4 and the current `dev` version.

![snapshot](https://user-images.githubusercontent.com/3877365/68527994-c7c06180-02ed-11ea-93a2-6065dd273e53.png)

Where/how did you test it?
