### ISSUE TITLE
Pinball Illusions table broken in latest dev (bisected to b1edcbba)

### ISSUE THREAD

**Issue by joolswills** [midwan/amiberry#530]
**Describe the bug**
The table in Pinball Illusions do not display correctly when building from dev branch (Looks like copper/bitplane pointers type fault). There are some menu / intro graphical glitches in commits around the one I bisected to, but the game is still playable.

**To Reproduce**
Load Pinball Illusions / skip intro
Press enter then space to select the first table
Top score display shows, but main table graphics are not working.

Built from dev branch on rpi2 with `make PLATFORM=rpi2-sdl2` using quick start a1200 settings.

I have bisected the problem to a specific commit b1edcbbaffd569503ae303d8d2b3d8126bd90476

```
b1edcbbaffd569503ae303d8d2b3d8126bd90476 is the first bad commit
commit b1edcbbaffd569503ae303d8d2b3d8126bd90476
Author: Dimitris Panokostas <midwan@gmail.com>
Date:   Fri Sep 20 22:23:59 2019 +0200

    custom optimizations

:040000 040000 2b49cf7b3fbb6c37c7a00339f75928223e17c265 f3b54ee6f540210811e23844abbb61991c42ff4d M	src
```

**Comment by midwan** [comment]
@joolswills 
Thanks for tracking this down!
Fix incoming in a bit.

**Comment by joolswills** [comment]
Noticed that the score display glitches during play also. I can open a new ticket - can check if it's related to the same commit
