### ISSUE TITLE
Battlechess gfx corrupted with fast copper enabled

### ISSUE THREAD

**Issue by joolswills** [midwan/amiberry#531]
**Describe the bug**
With the 3.0 version the board gfx are corrupted in Battlechess with fast copper on. It worked on the 2.24 version with the same settings.

Rpi2 / raspbian buster on retropie. Built with `make PLATFORM=rpi2`

Didn't finish bisecting this yet. There are issues with some commits not building I need to workaround to locate the commit that broke it. It's a bit confusing as commits seem to have unrelated changes to the commit messages and lots of cosmetic changes mixed in with code changes. Hard to see actual changes mixed in with that.

**Comment by joolswills** [comment]
Settings are default a500 with fast copper switched on. But it's the fast copper setting which seems relevant.

**Comment by midwan** [comment]
@joolswills 
Thanks for finding this.
Keep in mind that Fast Copper is a bit of a "hack", meant to speed things up in situations where a game might have been too slow otherwise. It's disabled by default because it might cause glitches, the idea being that we should enable it if needed.

There was an update in the Fast Copper logic from TomB's code, meant to increase compatibility. I would guess that's what caused this change in behavior since the previous version.

Is the game too slow without Fast Copper?

**Comment by joolswills** [comment]
It's full speed but it's not a game which has an advanced copperlist. I have noticed glitches on a standard kickstart con where it didn't used to have them with fast copper on so I believe compatibility may have actually decreased in the cases I've noticed. The digital illusions score may be related too. Also chess master 2000 (intuition / os game). Graphical glitches on right mouse menus.

**Comment by midwan** [comment]
@joolswills 
Thanks, I'll do some tests after reverting that specific change to see if it affects these scenarios

**Comment by midwan** [comment]
@joolswills 
I believe I found and fixed the offending change. 
It was specific to Fast Copper, and I only reverted the function that caused the problem. I tested it with Battle Chess and it seems to work fine now, but please let me know if you see any problems elsewhere.

**Comment by joolswills** [comment]
With latest 3.0.2 code I am seeing some issues still with fast copper enabled that didn't happen before. Sensible soccer has screen glitches which it didn't with 2.x. I will bisect and open a new ticket but just mentioning it as it's something I play a lot. It works fine without and I understand this is a bit of a hack, but I think for the games I played it was more compatible before. On an arm6 based system this may be more of an issue. Appreciate all your work on this.
