### ISSUE TITLE
[Fury Of The Furries] slowdown

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#533]
FuryOfTheFurries_v1.0_1347

**Describe the bug**
Similar to Jim Power #532. Game does run slower than expected right from the intro screen but also during gameplay. Not sure also about the colors in the stage selection screen.

**To Reproduce**

1. Launch the game
2. Select 60Hz option (right arrow) after the introduction. The 50Hz plays the game fine.
3. Slowdown will occur and for the music too

**Expected behavior**
Game to run full speed. It was in 2.25 as far as I recall.

**Desktop (please complete the following information):**

- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0 the one shipped with Retropie. 

**Additional context**
Given some other games run full speed only when Fast Copper is turned on (Agony, Fire & Ice, Brian the Lion) I gave it a try too without success. Also increasing CPU clock speed does nothing.

**Comment by midwan** [comment]
This runs at 50 FPS for me, after the latest update (Makefile compiler flags).
Please check again?

**Comment by nemo93** [comment]
I've missed an important step in the "steps to reproduce" above. Game plays absolutely fine whenever you pick the 50Hz option (left arrow) after the intro. I've picked the 60Hz and if you do so emulation goes nuts.

**Comment by midwan** [comment]
OK, this is a completely different issue basically: it seems that NTSC modes are restricted to 30 FPS (half the normal rate), even in the kickstart screen.

I believe we can close this issue as it's not specific to this game, and I'll open a separate bug report about this.
