### ISSUE TITLE
[Banshee AGA] left side of screen cropped

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#534]
Banshee_v3.3_AGA_0633

**Describe the bug**
The left side of the screen where you got the energy bar, score etc is being cropped. You can see only a half of it as it seems. 

**To Reproduce**

1. Launch the game
2. Get to the 1st stage and check on the left side

**Expected behavior**
Full screen and proper "hud" to be shown like the below
![image](https://user-images.githubusercontent.com/8100500/69162955-b6493780-0aed-11ea-896a-a05ad9d22215.png)

**Desktop (please complete the following information):**

- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0 the one shipped with Retropie. 

**Additional context**
It worked in previous Amiberry version 2.25.

**Comment by midwan** [comment]
Fixed with v3.0.2
