### ISSUE TITLE
[Ishar AGA WHDLoad] unplayable / screen garbage

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#536]
Ishar_v1.4_AGA

**Describe the bug**
Game is unplayable as you can't see a thing right after the emu starts.

**To Reproduce**

1. Simply launch the game
2. See screen with complete garbage

**Expected behavior**
Normal display.

**Desktop (please complete the following information):**

- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0 the one shipped with Retropie. 

**Additional context**
Worked on 2.25. I've tried several different parameters (fast copper, blitter, etc) without success. The screen keeps on being a mess. Tested on 3.0. I'll give another try on 3.0.2 to be sure.

**Comment by midwan** [comment]
The ADF version of this game works normally, so I suspect there's something happening with the WHDLoad version/options.

**Comment by nemo93** [comment]
After fiddling a bit around with the various parameters I've found a setup allowing the game to launch normally. I'm not 100% sure what exact parameter triggers the fix but it works with the following config file:
[Ishar_v1.4_AGA.uae](https://github.com/midwan/amiberry/files/3972636/Ishar_v1.4_AGA.txt)
