### ISSUE TITLE
Super Stardust AGA SuperHires resolution

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#54]
Hi, I tried this game on Amiberry 2.1 but at the beginning of the intro it completely locks up with no warning. I tried the same game on the Android version of UAE4Arm and it gave a warning saying "Superhires resolution requested. Not supported in UAE4ARM". I clicked OK and it continued, the graphics were corrupted but it didn't lock up. Once in game it's fine. I just wondered why AmiBerry never gave this message and locked up ?

**Comment by midwan** [comment]
@windale 
Yep, this is a known bug for now - I was planning to include support for SuperHighRes so I took away the warning, but the implementation is not finished yet and it crashes if you try to use it. I'll get it fixed... :)
