### ISSUE TITLE
Update WHDLoad Database/XML, No internet connection was found.

### ISSUE THREAD

**Issue by cesarpuig** [midwan/amiberry#540]
**Describe the bug**
I have installed the latest version of amiberry (3.0, 3.0.1 and  3.0.2), and since then when I try to update the file whdload_db.xlm I get an error in which it tells me that there is no internet connection, it did not happen with previous versions (2.25).

**To Reproduce**
1. Uninstall, previous versions and previous configuration files, belonging to Amiberry. I install the latest version of the master branch.

1. Go to Amiberry GUI

2. Click on Update WHDLoad Database/XML

3. See error "No internet connection was found¡ Please connect to the internet then try again."

**Expected behavior**
Click and update WHDLoad Database/XML

**Desktop (please complete the following information):**

Rasberry Pi 3b
Retropie 4.5.3
Linux 4.14.98-v7+ armv7l GNU/Linux

**Additional context**
I use an ethernet connection, but I have tried to disconnect ethernet and connect via Wi-Fi and exactly the same thing happens to me. Can't find connection

**Comment by midwan** [comment]
@cesarpuig 
I don't have a reliable way of recreating this (it works for all the devices I have here), but this feature should definitely be improved.

**Comment by cesarpuig** [comment]
@midwan 

> I don't have a reliable way of recreating this (it works for all the devices I have here), but this feature should definitely be improved.

Try to investigate why it happens to me.

Thanks

**Comment by Dwarfboysim** [comment]
I am also having this problem on all my Pi's.  Are there manual steps to update the file?

**Comment by cesarpuig** [comment]
@Dwarfboysim Yes, if you download it from this link

https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder?files=1

and replace the file  whdload_db.xml with the one in the amiberry configuration folder

**Comment by midwan** [comment]
This was somewhat improved recently, so it only tries to run the command `route` with a few parameters, then piping the results to `grep`.
Normally both commands should exist in your system, but if they don't you will still get this error of coruse. 

Could you test with the latest versions please?

**Comment by cesarpuig** [comment]
@midwan 

Hello, this weekend I try it and I comment the result, thank you very much

**Comment by Dwarfboysim** [comment]
Hi all,

Updated my RetropIe install of AmiBerry to v3.1.0 and the download XML now works.  AWESOME!!

 

Thanks,

Greg

 

 

Greg Eames

e-Mail: gregseames@gmail.com <mailto:gregseames@gmail.com> 

-----------------------------------------------------------

"I sit looking at this damn computer screen all day long, day in and day out, week after week, and think: Man, if I could just find the 'on' switch..."

- Zachary Good

**Comment by midwan** [comment]
@Dwarfboysim Thanks for confirming.

**Comment by cesarpuig** [comment]
@midwan Hello, in my case it has not been solved. I uninstall amiberry, delete all configuration files, and install from source. But he tells me No internet connection was found. Thank you

**Comment by midwan** [comment]
@cesarpuig 
Which distro are you using?
What happens if you go to the linux console and type "route" ?

**Comment by cesarpuig** [comment]
@midwan Hi.

> Which distro are you using?

I run Retropie 4.5.13, in Raspbian stretch 9.11, installed in a Raspberry pi 3B, and the internet connection I use is ethernet.

> What happens if you go to the linux console and type "route" ?

![image](https://user-images.githubusercontent.com/30637939/74365470-7634e080-4dce-11ea-8959-f05d04fee7d8.png)

**Comment by midwan** [comment]
@cesarpuig 
I suspect this has something to do with the permissions RetroPie uses to launch the emulator.
Can you try the following test please:

* Exit EmulationStation
* Login to the console
* Launch Amiberry manually (e.g. `sudo /opt/retropie/emulators/amiberry/amiberry`)
* Test the button again

Let me know what the results of that test are, perhaps we'll figure out something more.

**Comment by cesarpuig** [comment]
@midwan Hi. 
I get the following error if I run it from the console.


pi@retropie:~ $ sudo /opt/retropie/emulators/amiberry/amiberry
libEGL warning: DRI3: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
libEGL warning: DRI2: xcb_connect failed
Internal error; file src/osdep/gui/main_window.cpp, line 1032
Abortado

**Comment by midwan** [comment]
@cesarpuig 
I've updated the approach here to use `ping` instead of `route`, which should work better in all systems (some distros don't even have `route` installed).

Could you please test with the latest commit and let me know if it improved the situation for you?

**Comment by cesarpuig** [comment]
@midwan Hi. I have tried it, with connection through wifi and ethernet, and it still does not work.

**Comment by midwan** [comment]
@cesarpuig 
Hmm, ok. Then I have to assume it's related to how RetroPie runs Amiberry specifically, since it seems to work everywhere else except there.

**Comment by midwan** [comment]
This should be fixed with d6c103e3310bcf75c2d72a15849fbdf5eb7432b5 now.
