### ISSUE TITLE
[Goblins 3] need confirmation - memory error

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#544]
Goblins3_v2.3

**Describe the bug**
Error message being shown quickly after the game started. It's something like "system error -6 RAM:0" in the top right corner.

**To Reproduce**
1. Launch Goblins3_v2.3 (WHD)
2. Wait for the security code and after that screen the error should pop up any minute.
3. Game will just sit there preventing from playing.
Note: the error might take longer to appear sometimes. I've been able to go through the 1st stage. I saw the mouse cursor was messed up and then crash.

**Expected behavior**
To be able to play the game.

**Desktop (please complete the following information):**
- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0.3

**Additional context**
I've tried several different parameters (fast copper, blitter, etc) and with various kicks still without success. Tested on 3.0.3.
[Goblins3_v2.3.uae](https://github.com/midwan/amiberry/files/3897843/Goblins3_v2.3.txt)

I've found the below on [Whdload.de](http://www.whdload.de/games/Goblins3.html) yet I don't understand the instructions :-( Based on my uae above I do have 4MB of chipmem (`chipmem_size=4`).
```
found workaround for issues #0003339 and #0003638: use EXPCHIP when you get system err -6
(you need 2MB chipmem to be able to do that). Spent a lot of time on that bug, seems that the
game has a nasty uninitialized variable error, and depending on the fastmem config it 
happens or not. Locating the program in chipmem doesn't work if contiguous (0-$100000) 
but EXPCHIP works because it probably allocates the expmem very high in chipmem.
```

**Comment by amyren1966** [comment]
Case is probably solved? 
But since I see no one have comfirmed it here yet, I'll leave some feedback.

The game runs well here. Small graphical glitches if the game is launched with JIT enabled. 
JIT needs to be turned off and set to 7mhz for the game to run at normal speed.

System 
Amibian 1.5ee
Raspberry 4B
Amiberry 3.13 (worked also on 3.1.1)
Amiga environment: 
AmigaOS 3.9/Picasso96
68030/A4000 3.1 Rom
2mb chip/64MB Z3/2MB RTG

**Comment by midwan** [comment]
@amyren1966 
Thanks for confirming! :)

**Comment by sheerun** [comment]
In my case I needed to use Amiga 1200, 2 MB chip memory, 8 MB flash memory, and add EXTCHIP argument to WHLoad as so: `Goblins3.slave PRELOAD CUSTOM2=1 EXPCHIP`. 

The game is also playable on just 4MB memory on Amiga 3000, but main Blount moves very quickly (I like it though as it makes playing game faster).
