### ISSUE TITLE
Amiberry v3.0.4 - Screen Position Off

### ISSUE THREAD

**Issue by 2play** [midwan/amiberry#546]
Hi @midwan 
Please see the screen being off on the new binary
The latest beta i tested was ok. Can we have this fixed please?

![20191129_120059 binary](https://user-images.githubusercontent.com/30235736/69874913-7daf1800-12bc-11ea-9c00-b58b9f8a3532.jpg)

I m testing on:

**AGA**:
AlienBreed2_v1.4_AGA_0044.lha
![20191129_104120 AGA](https://user-images.githubusercontent.com/30235736/69874900-7ab42780-12bc-11ea-9625-62f98f30fb42.jpg)

**Non-AGA:** 
NorthAndSouth_v2.1_Image_0194.lha
![20191129_110756 Non AGA](https://user-images.githubusercontent.com/30235736/69874953-9e776d80-12bc-11ea-8a50-f376e52bc30b.jpg)

**CD32:** OK!
Brutal - Paws of Fury (1995)(Gametek)(M3)[!].cue
![20191129_13310 CD322](https://user-images.githubusercontent.com/30235736/69874970-a8996c00-12bc-11ea-8328-8f97d89b7480.jpg)

thanking you in advance

**Comment by midwan** [comment]
Try enabling Horizontal and/or Vertical centering, in the Display panel?
That option was enabled by default, but I changed it (and added an option to enable it in the GUI/config instead), due to some games having trouble with it.

**Comment by 2play** [comment]
Thank you @midwan Dimitri!
Vertical fixed it. 
but I guess i have to do in every game with this problem and save config. or...
I think ill add this to my defult a500 and a1200 and play around.  So to have it permanently.
`gfx_center_horizontal=smart
gfx_center_vertical=smart`
I think it will be easier to add later certain games with their custom config rather apply

**Comment by 2play** [comment]
ok not working on default config files. I guess controlled by the xml.
i think ill revert to my plain v3 or beta binary.
thank you though for the tip!

**Comment by midwan** [comment]
The setting could also go in the XML file, there have been requests for such modifications lately in the relevant repo: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder

Keep in mind v3 had some known bugs that were fixed afterwards (e.g. a performance issue)

**Comment by 2play** [comment]
I know couple said about performance but had no prob on my PlayBox base. This perf glitches were about couple games.
Im manually compiling 3.0.3 - 3.0.1 to see where the screen setting has been applied. I ll use that. 
Thank you for your continuous great work

**Comment by 2play** [comment]
@midwan I fixed it! small workaround but 3.0.4 is great with a tiny tweaking!
I ve applied a vertical display centering as main config rather the disabled one.
All setups are great now!
Amiberry rocks!
