### ISSUE TITLE
Cleanup PLATFORM overlaps

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#547]
I recognised some platform overlaps and was thinking which choice should be preferred in which case. Probably it makes sense, when some SBC-specific flags are applied via SBC-specific platform string, to mention or exclude it (via comments) from the generic SoC platform string. Also some seem to not match:
- https://github.com/midwan/amiberry/blob/master/Makefile#L93-L97
  - **Odroid N1** and **RockPro64** have **RK3399** SoC, which has it's own platform string. Not sure which is the better choice in this two cases, but since all relevant hardware is the same (?), I'm pretty sure the there are no SBC-specific optimisations possible, hence the RK3399 platform should be sufficient to over all of em.
  - **Odroid N2** is **Amlogic S922X** SoC, so a different SoC which does not fit together with the other two. But this SoC seems to have its own definition below as **AMLG12B**, if I get it right: https://github.com/midwan/amiberry/blob/master/Makefile#L120

I just recognised 32bit vs 64bit here, which is probably the reason for the overlap? Probably it makes sense to either allow 32 and 64 bit for 64bit capable SoCs (since in some cases 32bit kernel/OS might be used) or switch them to 64bit all together, since really, I never saw an RK3399 running with 32bit kernel/OS, which would not deserve any support (joke) 😄.

**Comment by midwan** [comment]
@MichaIng 
The only reason is the different bit-ness basically (32-bit/64-bit versions).
There are different distros that use one or the other, so to cover all grounds I'm providing both flavors. Distros like Batocera using buildroot have a preference towards 32-bit versions in general, whereas others might prefer 64-bit.

**Comment by MichaIng** [comment]
@midwan 
> The only reason is the different bit-ness basically (32-bit/64-bit versions).

Jep, I recognised this while writing the issue. Also I see now that the makefile comments contain this info as well in most cases, like "(SDL2 64-bit)", so this makes it quite clear. I personally would use two platform names for x64-capable SoCs with suffix, e.g. like "RK3399_64" and "RK3399_32", with "RK3399" (no suffix) defaults to x64 bit. This would make things easier for new users who might simply take the first matching platform from the makefile. Otherwise changing names again breaks existing scripts 😄.

Finally everything is fine, just something worth a though when new platforms are added or naming is changed for another reason anyway, at least I was confused a bid with current situation 😜.
