### ISSUE TITLE
whdload_db.xml resolution fix to AlienBreedTowerAssault_v1.3_AGA_2331

### ISSUE THREAD

**Issue by 2play** [midwan/amiberry#548]
@HoraceAndTheSpider 
**Describe the bug**
AlienBreedTowerAssault_v1.3_AGA_2331 has wrong resolution set in whdload_db.xml

**fix**
please update resolution from 
`SCREEN_HEIGHT=262`
to 
`SCREEN_HEIGHT=284`

**Comment by 2play** [comment]
I have noticed that this height (which is in the default  gui settings) seems to work in many games. 
ex also AlienBreed2_v1.4_AGA_0044
Later has minor centering issue but easily fixed with new display panel/tab gui option are can be ignored.

**Comment by midwan** [comment]
Please post this to the right repo directly: 
https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder

;-)
