### ISSUE TITLE
[Leander] need confirmation - no collision

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#549]
Leander_v2.5_0496

**Describe the bug**
Whenever you try hitting something with your sword nothing happens. I haven't enabled any cheats or debug mode.

**To Reproduce**
1. Launch Leander_v2.5_0496 (WHD)
2. Go straight to the game first level
3. Try hitting a chest or enemy. Nothing will happen. 
Note: you won't get hit yourself too by traps or enemies.

**Expected behavior**
To be able to play the game with proper collisions.

**Desktop (please complete the following information):**
- OS: Raspbian / Retropie
- Version 4.5.2 (latest)
- Pi3B+
- Amiberry v3.0.3

**Additional context**
I've tried several different parameters (fast copper, blitter, etc) and with various kicks still without success. Tested on 3.0.3.
[Leander_v2.5_0496.uae](https://github.com/midwan/amiberry/files/3908112/Leander_v2.5_0496.txt)

**Comment by Merlin2010** [comment]
Hi,

I've the same issue with collisions, but with different game, Deluxe Galaga. Enemies doesn't shoot me, and also I can't grab any prizes.

Desktop (please complete the following information):
    OS: Raspbian / Retropie
    Version 4.5.3 (latest)
    Pi3B+
    Amiberry v3.0.3

**Comment by midwan** [comment]
Thanks for reporting this.
Fixed in v3.0.6 now
