### ISSUE TITLE
[Cannon Fodder] missing helicopter

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#550]
CannonFodder_v2.0_Fr_2332

**Describe the bug**
If I'm right you should see a chopper right before a mission starts. What you got today is a just a scrolling background. I recall there was an issue in the past where only the rotor was missing. This time it's the entire helicopter.

**To Reproduce**
1. Launch CannonFodder_v2.0_Fr_2332 (WHD)
2. Get to the first mission and check for the scrolling background.
3. No helicopter shown.

**Expected behavior**
To get the heli sprite.

**Desktop (please complete the following information):**
- OS: Raspbian / Retropie
- Version 4.5.3 (latest)
- Pi3B+
- Amiberry v3.0.7

**Additional context**
I've tried several different parameters (fast copper, blitter, etc) and with various kicks still without success. Tested on 3.0.7.
[CannonFodder_v2.0_Fr_2332.uae](https://github.com/midwan/amiberry/files/3935421/CannonFodder_v2.0_Fr_2332.txt)

**Comment by midwan** [comment]
This seems to be related to the slave, as CannonFodder_v2.0_0860 works properly.
Please report to the slave author :)
