### ISSUE TITLE
LePotato Libre Computer build configuration 

### ISSUE THREAD

**Issue by baltobor** [midwan/amiberry#551]
**Is your feature request related to a problem? Please describe.**
Libre Computer (La Potato) released an "RetroPi"-Image. Most emulators work, but an amiga emulator is missing. I would like to contribute in making this emulator work on Le Potato.

**Describe the solution you'd like**
I set up some experimental compiler flags in the make file. It turned out that the compiler now starts working. But it stops in 

```
sigsegv_handler.cpp:799:34: error: ‘struct mcontext_t’ has no member named ‘arm_r0’
unsigned long* regs = &context->arm_r0;
```

Unfortunately I don't know so much about this project. Maybe some one could give me a hint on how to solve this issue.

**Additional context**
Here is some Informations:
Board: https://libre.computer/products/boards/aml-s905x-cc/
Gaming-DS-Card-Image: http://share.loverpi.com/board/libre-computer-project/libre-computer-board-aml-s905x-cc/image/retropie/

I used the following entry in the makefile :

```
else ifeq ($(PLATFORM),lePotato)
	CPUFLAGS = -fpermissive -march=native
	#CPUFLAGS = -mabi=lp64
	CPPFLAGS += -DARMV7_ASSEMBLY -D_FILE_OFFSET_BITS=64 -DARMV6T2 -DUSE_ARMNEON -DARM_HAS_DIV -DSOFTWARE_CURSOR -DFASTERCYCLES
	HAVE_NEON = 1
	CPUFLAGS += -mcpu=cortex-a53 	
	NAME  = amiberry-LaPotato
```

**AML-S905X-CC (Le Potato)**

* 2GHz quad-core A53 S905X.
* Mali-450 MP2 GPU.
* Architecture:        aarch64
* Byte Order:          Little Endian
* CPU(s):              4
* On-line CPU(s) list: 0-3
* Thread(s) per core:  1
* Core(s) per socket:  4
* Socket(s):           1
* NUMA node(s):        1
* Vendor ID:           ARM
* Model:               4
* Model name:          Cortex-A53
* Stepping:            r0p4
* BogoMIPS:            48.00

**Comment by midwan** [comment]
@baltobor 
If the OS is aarch64, then you should try with a 64-bit target as a basis (your example above is from a 32-bit one, which activates inline assembly that only works on 32-bit).

Try replacing your `CPPFLAGS` with only the following:
`-DCPU_AARCH64 -D_FILE_OFFSET_BITS=64`

(remove the rest, and remove `HAVE_NEON = 1` also)

**Comment by baltobor** [comment]
Hi again. I could narrow down that the code compiles well. The program is entering graphics_setup(). There

**Comment by midwan** [comment]
@baltobor You'll probably need to compile SDL2 from source if the one from the repos doesn't work directly. Most of the distros have an SDL2 that only works under X11.

We have a wiki entry regarding that here: https://github.com/midwan/amiberry/wiki/Compile-SDL2-from-source - it might be of help! :)

**Comment by baltobor** [comment]
Hi @midwan I did that already. Exactly your documentation is what I tried before. But something went wrong. Later I will try again.

**Comment by baltobor** [comment]
@midwan Your documentation works. I could successfully start the GUI. There were two issues. I compiled the scum engine before. And I've had double installations of SDL on my system. I deinstalled everything regarding SDL2 and recompiled using your doc.

**Comment by baltobor** [comment]
@midwan Success!
![Giganoid](https://user-images.githubusercontent.com/9945149/70564906-4892a780-1b91-11ea-8432-05bb0ded294c.jpg)

**Comment by baltobor** [comment]
@midwan Success!

Thank you very much for your help. Now officially Amiberry runs on LePotato.

The Configuration is a follows.
Makefile:
```
else ifeq ($(PLATFORM),lePotato)
	
   CPUFLAGS += -mcpu=cortex-a53 -mabi=lp64
   CPPFLAGS += -DCPU_AARCH64 -D_FILE_OFFSET_BITS=64 -DSOFTWARE_CURSOR -DFASTERCYCLES
   AARCH64 = 1
   NAME  = amiberry-LePotato
```

![Giganoid](https://user-images.githubusercontent.com/9945149/70565009-868fcb80-1b91-11ea-93b4-9741cfdf675b.jpg)

**Comment by midwan** [comment]
@baltobor 
Great work!
I'll add the new target in the Makefile, and create a Wiki page regarding this platform.
You are also able to edit wiki pages and update the information, if you get things working better in the future for example...

**Comment by midwan** [comment]
Wiki page is now here: https://github.com/midwan/amiberry/wiki/Compiling-for-LePotato-Libre-Computer
