### ISSUE TITLE
Custom Controls and Joystick Ports

### ISSUE THREAD

**Issue by tukicat** [midwan/amiberry#552]
Hi, 

I've upgraded to 3.0.8 and I am having an issue with custom controls and joysticks.

I have been using Midnight Resistance for testing as it is a two player game. 

In order to play Midnight Resistance player one has to have a joystick plugged into port 0. On the "Input" tab in the GUI port 0 is labelled [mouse]. I am also changing the device type to "Joystick".

If I set my controller (in this case an Ultimarc IPAC) to port 0, it is then recognised in the "Custom Control" tab in the GUI, as when I select port 0: mouse there is a [R] next to the input device name. 

If I play the game the joystick and fire button for player one are recognised fine. However Midnight Resistance also uses the "left shift" key for Player one (secondary weapon), but if I set this up as the custom config the button mapping is not recognised. 

After a while I decided to test setting my (Ultimarc IPAC) to port 1 [Joystick], this is the port that would be used for most single player games, as the mouse usually goes in port 0. When i did this and then went to "Custom Controls" and selected port 1: joystick the custom controls worked fine, although I was now acting as player two rather than player one.  

It appears that the custom joystick controls are not working when setting a joystick to port 0. 

Is this a known issue?

**Comment by midwan** [comment]
@tukicat 
We have some experimental code in `dev` regarding IPAC controllers, which might fix the issue you're facing. I still need to test this a bit better before merging into `master` however.

**Comment by tukicat** [comment]
Hi, 

Thanks, I compiled the dev version. I still can't use custom controls on when the joystick is set to port 0.

Also, I have a controller showing as "RetroArch Keyboard as Joystick [#1]", this is my player two controller. The joystick and fire button works fine, but it is not recognised as retroarch controller (there is no "r" next to the input name. Is there anyway to get it recognised as a retroarch controller?

**Comment by midwan** [comment]
@tukicat 
I've bugfixed and merged the IPAC support changes into `master` now, so you can test there.
The current `dev` has some known bugs so it's considered experimental at this time.

You'll need a retroarch mapping to get 2-player support out of your IPAC controller, but I don't own one so I'm not the best person to give you details on how to do that. I'm sure there are other people in the community that can assist in that however.

**Comment by midwan** [comment]
@tukicat 
Is this issue still happening, or can we close it?

**Comment by tukicat** [comment]
I’ll test tomorrow evening and let you know

**Comment by midwan** [comment]
@tukicat 
You can verify that Amiberry uses the "correct" Shift mapping with a tool like AmigaTestKit (https://github.com/keirf/Amiga-Stuff), which shows the keys pressed on-screen.

**Comment by tukicat** [comment]
@midwan 
I tried out AmigaTestKit and all the mappings were correct. The "left shift" key is the "left shift" key, etc.

So this means that all is working well, it must be that the manual for Midnight Resistance is wrong on which shift keys operates the secondary weapon for each player. 

Looks like you can close this one down.

**Comment by midwan** [comment]
Thanks for confirming!
