### ISSUE TITLE
Can't set Screenmode width lower than 640

### ISSUE THREAD

**Issue by alivesay** [midwan/amiberry#553]
Latest version on rpi4.  Using vga666 running at 320x240.

Display settings are set to 320x240.

With OCS, ECS, and AGA, I cannot set a ScreenMode with a width of 320.  640x200 is listed as the Minimum Size.

I've tried adding 320x240 here but it didn't help: https://github.com/midwan/amiberry/blob/8d0061262e5a6d078577a38e599126476ffb9de6/src/osdep/amiberry_gfx.cpp#L59

Why am I missing Super-Lores Modes?

**Comment by midwan** [comment]
@alivesay 
How are you testing this? Did you try setting a Screenmode in a graphics program, or Workbench for example?

I cannot recreate it:
![snapshot](https://user-images.githubusercontent.com/3877365/70666257-97fad580-1c6e-11ea-9158-c5243ae2e284.png)

**Comment by alivesay** [comment]
@midwan 

Hi,

I'm just running a default WBClassic LITE install.  I can set 320x240 in the Amiberry Display settings, however when I attempt to set the mode in Screenmode Prefs within Workbench I only have NTSC and PAL resolutions, all of which have a "Minimum Size" of 640 width displayed.

I don't see any of the "UAE" ScreenModes listed.  Is there something I need to install within Workbench?

Thank you,

-a

**Comment by alivesay** [comment]
I'm now thinking this may be because I don't have the Picasso96 drivers.  Installing now to find out...

**Comment by midwan** [comment]
@alivesay 
The UAE screenmodes will only show if you have P96 installed and you have some RTG memory assigned in the emulation.

But PAL/NTSC LowRes modes should work even without that, of course.

**Comment by alivesay** [comment]
Sorry, I've now learned Workbench is not capable of running a 320x240 desktop, having a 640 minimum width (autoscroll).

**Comment by alivesay** [comment]
@midwan 

I'm running my Pi at 640x200 now, and Amiberry seems confused by this resolution.

![](https://i.imgur.com/2jD1oRG.jpg)

![](https://i.imgur.com/4tZDQtZ.jpg)

It's not totally apparent in those pictures, but the display is squished horizontally with about 40% of the screen black on both left and right sides.  "Correct Aspect Ratio" does nothing.

Amiberry Display is set to 640x200.  Workbench is set to 640x200.

If I uncheck "Fullscreen", I get this:

![](https://i.imgur.com/fCxfeuP.jpg)

**Comment by midwan** [comment]
I see a few things here:
1) You're running the SDL2 version, not the Dispmanx one. On the RPI boards, the Dispmanx version will give you maximum performance, though of course the SDL2 one will also work fine (just a bit slower).
2) "Correct Aspect Ratio" only works in Dispmanx and will stretch the display it's not selected. I guess it should also work in SDL2, so I'll look into that separately.
3) Try changing the Display Height to another value, then back to 200? If an invalid value is found there, it will default to the first available on the GUI (which is 200), but it doesn't necessarily take effect. Changing to another one and back will update it.

Why are you using your RPI at 640x200? The default PAL Resolution is 640x256, unless you're emulating an NTSC Amiga of course. But the performance benefit of lowering the host resolution is minimal, if any.

**Comment by alivesay** [comment]
Thanks for the help!  I'll recompile with the DispmanX flag.

 I'm trying to natively run a Hires mode on a Sony PVM via a vga666 (VGA out over Pi GPIO), I was hoping the PVM could handle 640x256@50, but there just aren't enough vertical lines (you loose about 8 lines or so, plus the flicker at @50Hz is awful). 

In case you're curious, here are the timings I was able to work out that seem stable:

dpi_timings=640 0 40 64 56 200 1 15 8 39 0 0 0 60 0 12575000 1 #640x200@60
dpi_timings=640 0 8 32 120 256 1 4 26 26 0 0 0 50 0 12480000 1 #640x256(~-8px)@50
