### ISSUE TITLE
CD32 emulation doesn't start after v3.0.7

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#556]
Hello folks,
at first i want to say thank you for your fantastic work on amiberry. :-)

Let me describe my problems with amiberry 3.0.9 and amiberry 3.0.10

amiberry 3.0.9
---------------

	Positive: The heavy flickering in Test Drive II (WHDLoad with WB 3.1.4.1) was gone with this version.
	I described the problem here: [Test Drive II - Heavy flickering with amiberry](http://eab.abime.net/showthread.php?t=99696)

	Negative: I can not start my CD32 files (iso with cue file) anymore. In 3.0.7 it works perfect.

amiberry 3.0.10
---------------

	Negative: The heavy flickering in Test Drive II is back again with this version.

Kind Regards
Retro1968

P.S.: In all amiberry versions my Workbench 3.1.4.1 (with Kickrom 3.1.4) wont load to the end when JIT is ON. It stucks.  If JIT is OFF Workbench 3.1.4.1 is loaded perfectly.

**Comment by Retro1968** [comment]
**Addition:** I use amiberry on a Raspberry Pi 4, with Raspbian Buster and RetroPie 3.5.3.

**Comment by midwan** [comment]
@Retro1968 
OK, you have multiple things mentioned, so let's break those down:
1) There is a known bug in JIT, which shows up as this problem with Workbench 3.1.4.x. We're working on that separately.
2) Version 3.0.10 only had one change from 3.0.9, that was support for SCP disk images. No other code was touched, so I doubt that what you described started happening there, but wasn't happening before. Did you change any options in your config in the meantime perhaps?
3) Regarding the flickering problem, I see that other people mentioned that changing emulation options might help (e.g. CPU speed, but check Chipset options also). I'll need to recreate this to know more.

**Comment by Retro1968** [comment]
Hello,
thank you for your answer.

1. Thank you that you work on the JIT Proiblem.
4. Thank you that you look at the CD32 Problem

2+3. I normally put the CPU Clock Speed to 7 Mhz to turn off the flickering. In Version 3.0.9 the flickering was gone without changing anything... what surprised me a lot. After i installed 3.0.10 the flickering was back again. So far as i know i changed nothing in the config. I send it to you.
[++AmigaOS 3.1.4.zip](https://github.com/midwan/amiberry/files/3964933/%2B%2BAmigaOS.3.1.4.zip)

**Comment by Retro1968** [comment]
I have another addition: Since iam a german i use the german keyboardlayout. In this there i an error which is while using amiberry. On an real Amiga 1200 this problem is not there: If i press the "#" key i get a "\". There is no keycombination in the german keyboardlayout which produces a "#". I need the "#" for the command: protect dh0:#? +wd all

**Comment by Retro1968** [comment]
Yes thank you. The CD32 problem was fixed. :-)

**Comment by midwan** [comment]
I just tested TestDrive2_v1.1_0588 using the `-autoload=` feature of Amiberry. No flickering at all in the game, title screen or options. ;-)

That feature is unique in Amiberry, and uses pre-installed WHDLoad `lha` archives to run games/demos directly from the emulator. It uses an XML database for matching titles and best known settings for the emulator, to make things as simple as possible (especially in RetroPie, it's just click and forget as the LHA files will also show in the list of available Amiga games).

For reference, the settings used for this game specifically were:
- CPU: 68020
- 24-bit addressing
- FPU: None
- CPU Speed: 7 MHz
- Chipset Full ECS
- Extra: A600
- Blitter: Wait for Blitter
- Collision level: Sprites and Sprites vs Playfield
- ROM: KS ROM v3.0 (A1200)
- RAM: Chip 2MB, Z2 Fast: 4MB
- Display: Width: 720, Height: 216

**Comment by Retro1968** [comment]
Yes in the autoload Test Drive II works perfect. The problem exits under Workbench whith high CPU settings.

**Comment by Retro1968** [comment]
Is it possible to get 3.0.9 to try out again?

**Comment by midwan** [comment]
Sure, you can clone the repo, checkout the specific commit (1df2751f138dd57f2c03de261e7d43bbc68bbc38) and compile that, for testing.
But as I said, there was only one change from that version and it only added support for one more image format. 
I don't see how that could change what you are describing.

**Comment by midwan** [comment]
You could also get the pre-compiled binary, but that is compiled for Buster and RetroPie is still on Stretch. You'd have to use that on a Buster-based distro, if you have one around (e.g. standard Raspbian Buster Desktop)

**Comment by Retro1968** [comment]
Ok i downloaded the sourcecode of 3.0.9 and executed "sudo make". I still do not see a executable.... So i ask a newbie question... what command do i have to input next... after "sudo make"?

**Comment by midwan** [comment]
You don't need "sudo" normally.
If you're on an RPI, then you could use "make -j2 PLATFORM=rpi4", and wait
until it's finished.
The binary will be named "amiberry" in the same folder, so you may have to
copy it to where RetroPie expects it to be:
/opt/retropie/emulators/amiberry

**Comment by Retro1968** [comment]
Thank you. 3.0.9 flickers too ;-)
Is it possible that you fix the problem with the german keyboardlayout that i described above?

**Comment by midwan** [comment]
@Retro1968 
Let's look at that in a separate issue please, this one can be closed I believe.
