### ISSUE TITLE
[Might & Magic III] Doesn't start

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#560]
Might&Magic3_v1.2_2346

**Describe the bug**
Game doesn't start and crash to an AmigaDOS screen with an illegal return code.
![Might Magic3_v1 2_2346](https://user-images.githubusercontent.com/8100500/70985951-4c588980-20bd-11ea-88ef-e269c15114b3.png)

**To Reproduce**
1. Launch Might&Magic3_v1.2_2346
2. You'll get straight to the AmigaDOS with the "illegal return code"
3. Game can't be started.

**Expected behavior**
To be able to start the game.

**Desktop (please complete the following information):**
- OS: Raspbian / Retropie
- Version 4.5.3 (latest)
- Pi3B+
- Amiberry v3.0.11

**Additional context**
I've tried several different parameters (fast copper, blitter, etc) and with various kicks still without success.

**Comment by midwan** [comment]
This looks like a slave problem, as it's WHDLoad that crashes - not the emulator.
Does this slave version work anywhere else?
