### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by marcomto** [midwan/amiberry#568]
Hello, 
I'm trying to compile amiberry pi3+ with sdl2 dispman:
make -j2 PLATFORM=rpi3 ()gcc version 4.9.2

I get the following error:

make -C external/libguisan
make[1]: Entering directory '/root/amibian/amiberry/amiberry/external/libguisan'
g++ -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -Ofast -pipe -Wno-shift-overflow -Wno-narrowing  -std=gnu++14 -MD -MT src/inputdevice.o -MF src/inputdevice.d -DARMV6_ASSEMBLY -D_FILE_OFFSET_BITS=64 -DARMV6T2 -DUSE_DISPMANX -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads  -DUSE_ARMNEON -DARM_HAS_DIV -I/usr/local/include/SDL2 -D_REENTRANT -Iexternal/libguisan/include -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -I/usr/include/libxml2 -DAMIBERRY  -c -o src/inputdevice.o src/inputdevice.cpp
make[1]: 'lib/libguisan.a' is up to date.
make[1]: Leaving directory '/root/amibian/amiberry/amiberry/external/libguisan'
g++ -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -Ofast -pipe -Wno-shift-overflow -Wno-narrowing  -std=gnu++14 -MD -MT src/main.o -MF src/main.d -DARMV6_ASSEMBLY -D_FILE_OFFSET_BITS=64 -DARMV6T2 -DUSE_DISPMANX -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads  -DUSE_ARMNEON -DARM_HAS_DIV -I/usr/local/include/SDL2 -D_REENTRANT -Iexternal/libguisan/include -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -I/usr/include/libxml2 -DAMIBERRY  -c -o src/main.o src/main.cpp
src/inputdevice.cpp: In function ‘void inputdevice_store_unplugged_port(uae_prefs*, inputdevconfig*)’:
src/inputdevice.cpp:581:25: error: could not convert ‘{0}’ from ‘<brace-enclosed initializer list>’ to ‘jport’
  struct jport jpt = { 0 };
                         ^
src/inputdevice.cpp: In function ‘void inputdevice_fix_prefs(uae_prefs*, bool)’:
src/inputdevice.cpp:8753:29: error: could not convert ‘{0}’ from ‘<brace-enclosed initializer list>’ to ‘jport’
      struct jport jpt = { 0 };
                             ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-shift-overflow"
<builtin>: recipe for target 'src/inputdevice.o' failed
make: *** [src/inputdevice.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by midwan** [comment]
It looks like you're running an older version of Raspbian?
GCC 4.9.2 is rather old and doesn't support all the modern language syntax changes, which is why you're getting an error.

Why not upgrade to the latest Raspbian Buster?

**Comment by marcomto** [comment]
Yes, you're right. It is an amibian distro I installed last year. Now I'm running Raspbian buster light and I've  successfully compiled the last Amiberry version. Thank you.
