### ISSUE TITLE
Running bustest freezes amiberry

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#569]
**Describe the bug**
Running bustest (http://aminet.net/package/util/moni/bustest) freezes emulation. F12 works to get back to the GUI.

**To Reproduce**
Unpack bustest and run for instance "bustest chip size=1024"

**Expected behavior**
No freeze

**Desktop (please complete the following information):**
Raspberry PI Manjaro ARM 64bit - Emulating A1200 with both 68020 and 68040

Amiga OS 3.1.4

**Comment by solskogen** [comment]
This seems to happen on WinAUE as well, but not on my MiST FPGA.

**Comment by midwan** [comment]
If it happens on WinUAE as well, I think we'll have to wait until it's fixed upstream.

**Comment by midwan** [comment]
Note: This only happens if JIT is enabled, with JIT disabled it seems to work
