### ISSUE TITLE
Kickstart 3.1.4 update

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#570]
Read that support was added recently for the new 3.1.4(.1?) ROM. To have symlinks created etc, what should the file name be? An update on this page would be nice:

https://github.com/midwan/amiberry/wiki/Kickstart-ROMs-(BIOS)

Thanks for great work!

**Comment by solskogen** [comment]
There are no symlinks for needed WHDLoad for 3.1.4 (No game or demo
requires that version yet)

**Comment by stuffu** [comment]
Thanks for quick reply, I'll leave it is then.
