### ISSUE TITLE
boot-data.zip containing Apple OS junk?

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#574]
![Bildschirmfoto zu 2020-01-08 17-58-07](https://user-images.githubusercontent.com/28480705/71999376-94447980-3241-11ea-8e5e-4af4aa6edc84.png)

This `_MACOSX` dir and contained `.DS_Store` files look like Apple OS junk being stored across files systems it accesses once. I guess this could be cleaned a bid? Nothing urgent but looks a bid strange currently :wink:.

**Comment by midwan** [comment]
You're absolutely right, thanks for the heads-up!
