### ISSUE TITLE
Barbarian (Palace) not starting

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#575]
Barbarian isn't launching. So far that's the only game I haven't been able to launch.

What happens is that it loads for a few seconds and ends up with the kickstart screen.

I can't seem to find a log on why it happens. Also, I've read some other posts about setting it as A600 but the result is the same (or maybe I just didn't understand).

Using Amiberry 3.0.11 on a RetroPie system and updated WHDload xml.

**Comment by midwan** [comment]
Are you testing an ADF version, or WHDLoad?
Do you have the exact filename please?

**Comment by stuffu** [comment]
I’m testing WHDLoad; Barbarian_v1.1_Palace_1784.lha

**Comment by nemo93** [comment]
@stuffu can you please check [here](https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/issues/3)? and confirm the proposed solution does work for you?

**Comment by stuffu** [comment]
@nemo93 It works! Thanks for the workaround!
