### ISSUE TITLE
Use nearest neighbour scaling with WHDLoad

### ISSUE THREAD

**Issue by mth75** [midwan/amiberry#576]
Hi all,

I'm still unable to run my WHDload packages with Amiberry (now for the Raspberry Pi4 - SDL2) with nearest neighbour as scaling method. I never succeeded with prior versions, and I would really like to tackle this problem for my RPI4 build.

So question, how to use default nearest neighbour scaling method when running WHDLOAD packages.

Best!

**Comment by midwan** [comment]
Currently this only works if you're using the SDL2 version of Amiberry, not the Dispmanx one.
Since you're on an RPI, you could be using either one. The Dispmanx one is slightly faster (especially on platforms before the RPI4), which is why it exists in the first place.

So the question is, which version are you using? Which environment are you running this on?

**Comment by mth75** [comment]
Hi, I'm running the SDL2 version on the RPI4 weekly build. To clearify, i'm unable to make the default nearest neighbour my default config (in order to start with this setting as default). It works when setting manual per session.

**Comment by midwan** [comment]
@mth75 
Thanks for clarifying that - then the request is basically about having that option as the default, as you mentioned.
I'll see about adding that to the global `amiberry.conf` file.

**Comment by mth75** [comment]
Thx! That really would be awesome. I think that it would also be nice to have the "double" as a default in amiberry.conf

**Comment by midwan** [comment]
@mth75 
Line mode Double has a performance impact, since we have to draw double the amount of lines to do that, which may slow down the framerate (especially on slower systems). That's the reason it's not the default option, in contrast with WinUAE for example.

**Comment by midwan** [comment]
New option added in `amiberry.conf` regarding this:
```
default_scaling_method=-1
```
The default value is -1, which corresponds to the existing default option of Auto.

Possible values are -1, 0 and 1:
-1: Auto (default)
0: Nearest neighbor
1: Linear

Any other values will be ignored and it will default back to -1.

This of course can and will be overriden by any `.uae` config files that may be loaded afterwards.

**Comment by mth75** [comment]
Thank you for the quick implementation!
