### ISSUE TITLE
Add Global default for H/V centering

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#577]
I am not sure it's actually a bug, it could also be a feature, but many games start in a weird resolution and often off center vertically.

I don't know why some games start with something like 720x200, but when setting both horizontal and vertical resolution to max it always resolves the issue. So instead of making individual configs for each game, a "master setting" would be appreciated. 

Same goes with the setting to force horizontal and vertical center. If forcing vertical center, the display ends up in the right spot (except NTSC, but that's another issue). The display is often above center off the screen, but still not cut off. (this seems to be the same issue as #565 )

Using WHDload games, Amiberry 3.0.11, latest xml.

**Comment by Haxel66** [comment]
I have exact same issue devis aware of it.

Vertical ticked works for almost all games so far.  

Then save uae file under configuration. 

But if it was possible to do for all games at once would be great.

**Comment by midwan** [comment]
I'll probably add a setting to have horizontal and vertical centering ON/OFF by default, in `amiberry.conf`

**Comment by midwan** [comment]
However, regarding the resolution - the default is actually the max it can be displayed. But a game can override this with its own config, and that's the desired behavior.

If a game has incorrect settings in the XML file, it's there it should be fixed.

**Comment by Haxel66** [comment]
Would be great as most games need vertical ticked I've checked 300 so far and 244 of them needed vertical ticked so would take along time to get the xml updated.  Default vertical would be best bet and if games needs it off then we can do that and save uae for that game which wont be many.  Ticking vertical to games which don't need it may sometimes mess them up but I'd still rather fix those few after.  But ultimate goal would be to have xml updated for all game resolutions. 

Just to let you know I'm using latest revisions of each game from retroplay whdload set and latest amiberry.

**Comment by stuffu** [comment]
When it comes to default resolution for Amiga Screen I haven't found one example of a WHDLoad that doesn't work with 720x284. Many titles are set default to something like 720x200 or similar and that both ends up in wrong aspect ratio as well as parts of the screen is not visible.

So even if it's wrong input in the xml, it's still something that would make life a lot easier if there was a global setting. The workaround I have currently is starting a title, enter the gui, change default resolution to 720x284 and save a uae for each title.

Maybe this should go in another subject but in earlier versions (3.0.X) opening the gui defaulted to F12, the default gui key (on 3.1) in the amiberry.conf is not set.

**Comment by midwan** [comment]
@stuffu 
I think it will default to 200 if the value found is invalid. I'll check that and see if we can change it to be the maximum instead, to play it safe.

Regarding F12, that sounds like a bug, thanks. I'll check it out separately.

**Comment by midwan** [comment]
@stuffu 
Can you check your `amiberry.conf` file please? Do you have a line for `default_open_gui_key=` and what does it have assigned, if you do?
If you don't have it (since it was added with the new version), then I obviously missed that case and I will add a fallback default for it.

**Comment by stuffu** [comment]
Yes, I have the default_open_gui_key= in amiberry.conf and it didn't have a set value at all. I changed it to F12 and all worked out fine.

**Comment by stuffu** [comment]
And I think it will save a lot of time to have it default to 720x284 instead. If I recall correctly I think I read about a performance issue with having a lot of config files. This will likely remove the need of manual configuration files in many cases (and even more with having a default value for vertical center).

By the way, Amiberry is a fantastic work. I highly appreciate it! Thanks a lot for your effort.

**Comment by Haxel66** [comment]
The issue I find with 720x284 is the screen is so small but I do understand
atleast its correct aspect ratio and the games fit.

Wouldnt it make sense then to just replace all the custom resolutions in
xml to 720x284.

**Comment by Haxel66** [comment]
I edited the xml changing all custom resolutions to the 284 and removed
offset and all games fit.

**Comment by midwan** [comment]
@Haxel66 
Thanks, that's exactly what I was going to look into as well.
The default resolution (which is also applied from Quickstart) already is the max, but if the config file includes another, it overrides it. However, if the other one it includes is invalid, it would fall-back to the minimum from what I saw (200 for vertical), which is why this happened.

So I will look into that and change the behavior so it falls back to the max, instead the minimum - but the XML file should be updated and cleaned up as well (offset no longer applies anyway, for example).

Can you send your changes as a pull request to the relevant repo, please?

**Comment by Haxel66** [comment]
Yes of course I can upload the adjusted xml file if needed.

**Comment by Haxel66** [comment]
whdload_db
Screen_Height=284
For all games which custom screen height. 
And offset=
For all games with custom offset value

Thanks
Haxel

**Comment by midwan** [comment]
New options added for this in `amiberry.conf`:

```
default_horizontal_centering = no
default_vertical_centering = no
```
Setting either one to `yes` will enable the corresponding Centering option by default.
This of course can and will be overriden by any `.uae` config file which may be loaded afterwards.
