### ISSUE TITLE
New DietPi image available

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#578]
I wrapped together a new DietPi RPi Amiberry image based on Debian Buster and DietPi v6.28: https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Buster_Amiberry.7z
As before it is configured to automatically install and configure the newest Amiberry (currently v3.0.11) with all dependencies on first login and then boots into Amiberry on reboot. So basically plug, wait a few minutes, and play.

@midwan 
Could you update the link on: https://blitterstudio.com/amiberry/
Also the way how to setup WiFi has changed a bid: https://dietpi.com/phpbb/viewtopic.php?p=9#p9
- Enable WiFi adapter/interface via dietpi.txt as before: `AUTO_SETUP_NET_WIFI_ENABLED=1`
- Add one or multiple WiFi credentials via `dietpi-wifi.txt`, including EAP, e.g.: `aWIFI_SSID[0]='MySSID'` and `aWIFI_KEY[0]='MyWifiKey'`

I see the `4. Optionally, to enable OpenSSH`, which gives the impression that no SSH is available by default. Note that Dropbear SSH server is pre-installed on all DietPi images, hence OpenSSH in only required in rare cases where users require the additional features.

I read through: https://dietpi.com/phpbb/viewtopic.php?p=64#p64
Since we ship no `autostart.uae` anymore (I think defaults should be fine, else user can or should select settings/paths etc oneself), the mentioned path for floppy disks (`/mnt/dietpi_userdata/amiberry/floppy_images`) is not valid anymore, or what is the default where Amiberry looks for them? From what I see one anyway needs to navigate and select them manually, hence there is no real "default" path and they can be freely placed as desired anyway.

If you have any suggestions about changed/set settings/defaults on this image, please let me know. One thing I just remembered is that the GPU memory split will stay on 16M, which is most likely too low for flawless Amiberry joy, what do you suggest? On interactive install, DietPi would prompt user and apply 128M when chosen.

**Comment by midwan** [comment]
@MichaIng 
Awesome, thanks!

I've updated the link and instructions accordingly. Regarding your questions:

1. The `autostart.uae` file is no longer relevant. With the latest versions of Amiberry, we've harmonized the options with WinUAE, so if you want a config file automatically loaded on startup it has to be named `default.uae` instead. However, for the case of the DietPi based image, I don't think this is required anyway. It's a relic from the older times, when we didn't have the "Quickstart" Panel implemented for easy selection of an Amiga configuration. Let's remove it, please.

2. Amiberry will open up a dialog box by default, when browsing for disks/ROMs or config files. The last path used will be saved in the `conf/amiberry.conf` file, so it's remembered there. But there's no hard requirement on having those files somewhere specific, they can reside anywhere (even on a network path, if it's accessible).

3. Regarding the GPU memory split (is this still valid on RPI4?), I think we could use the default of `64`. Based on the documentation here: https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md

**Comment by MichaIng** [comment]
@midwan 
1. Okay so that is all fine then already.
2. I will adjust our docs then as well to only suggest `/mnt/dietpi_userdata/amiberry/floppy_images` as possible floppy location, which would need to be created then. Since Amiberry runs as root currently (something I actually would like to change, when complete sound + video + GPU access is otherwise guaranteed), there is as well no permissions-related limitation.
3. RPi4 requires mostly less GPU memory, since the new MMU allocates certain parts on system memory instead. Finally some testing would be fine to have GPU memory as few as possible but as much as required on each RPi model, which could then be configured as model-specific minimum on Amiberry install, so applied, if not already or higher done, without user accepting interactively. However I will apply 64M default on the Amiberry image for now, fine tuning is done with next DietPi version.
