### ISSUE TITLE
[ADF] Jim Power slow on title screen

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#58]
The game "Jim Power" has a slowdown on the title screen.
The audio is breaking up while trying to keep in sync with the video.

Frameskip helps resolve this, but we should try and to optimize the areas causing it.

Version tested: 
Jim Power - Mutant Planet (1992)(Loriciel)(Disk 1 of 2)[cr FLT]

**Comment by midwan** [comment]
Running a profiler (gprof) shows these are the functions taking the most CPU % during this test:

%   cumulative   self              self     total          
time   seconds   seconds    calls  Ts/call  Ts/call  name    
 4.87      3.41     3.41                             m68k_run_2()
 4.79      6.77     3.36                             record_sprite_1(int, unsigned short*, unsigned int, int, int, unsigned int, int, unsigned int)
 4.06      9.62     2.85                             toscr_3_ecs(int)
 4.06     12.46     2.85                             update_copper(int)
 2.72     14.37     1.91                             do_cycles_cpu_norm(unsigned long)
 2.70     16.26     1.89                             linetoscr_16_stretch1_aga(int, int, int)
 2.48     18.00     1.74                             disk_doupdate_read(drive*, int)
 2.34     19.64     1.64                             one_fetch_cycle_0(int, int, int, int)
 2.22     21.19     1.56                             update_audio()
 2.20     22.74     1.55                             update_fetch(int, int)
 1.84     24.03     1.29                             m68k_getpc()
 1.80     25.29     1.26                             decide_line(int)
 1.77     26.53     1.24                             draw_sprites_aga_sp(sprite_entry*, int, int, int)
 1.70     27.72     1.20                             do_specialties(int)
 1.70     28.91     1.19                             adjust_cycles(unsigned long)
 1.66     30.07     1.16                             decide_sprites(int)
 1.53     31.14     1.07                             draw_sprites_aga_dp(sprite_entry*, int, int, int)
 1.45     32.16     1.02                             disk_doupdate_predict(int)
 1.41     33.14     0.99                             unformatted(drive*)
 1.40     34.12     0.98                             fetch(int, int)
 1.31     35.04     0.92                             anti_prehandler(unsigned long)
 1.18     35.87     0.83                             is_bitplane_dma(int)
 1.12     36.66     0.79                             do_get_mem_word(unsigned short*)
 0.97     37.34     0.68                             events_schedule()

**Comment by windale** [comment]
I have tried this game before with your Amiberry 2.1 Binary release and turning JIT OFF gave an extra 5-6 fps. I noticed this on a few games/demos where it's better to keep JIT turned off. I now always default it to OFF.

**Comment by midwan** [comment]
@windale 
Yeap, JIT is not very useful with games and software that expects a "normal" A1200/A500 with chipset timings etc. In those cases, you're better off without it for now at least.

On the other hand, it is very useful when working with stuff that you want to go "as fast as possible", such as Workbench applications on Picasso resolutions.

**Comment by midwan** [comment]
Update:
Things look slightly improved with the latest SDL1 version (dev), but it should be improved further, as it's still breaking up.

**Comment by nemo93** [comment]
Hello! It's me again as I'm trying to keep things clean re issues with games. I've created one ticket for each game "format" (ADF #152, WHDLoad #122 and soon CD32). May I kindly ask you about the version of the game being used please? It seems to work fine here at least the WHDload with following revision V1.1 (03.01.2001). 

Let me share the uae I'm using just in case. [Jim Power.txt](https://github.com/midwan/amiberry/files/1470791/Jim.Power.txt)

**Comment by midwan** [comment]
@nemo93 
I've updated the title and description accordingly, thanks for noticing!
The latest updates in the emulator have helped reducing this problem, but it's still there I'm afraid (at least in the ADF version I'm testing).

I don't have a WHDLoad environment to test it yet, once I prepare that I will also try it there.

There is a noticeable difference if you enable Frameskip in the title screen, where the music then plays normally. Otherwise, it's in "slow motion"...

**Comment by ransom1122** [comment]
What's the latest update on this game? Still laggy?

**Comment by midwan** [comment]
Just tested it on the XU4 target, where the title screen runs at full 50 FPS.
This is due to the more powerful CPU of course... :)

**Comment by emuchicken** [comment]
Similar issues, gameplay at 41fps on the regular whdload config.  You can squeeze it to around 47-48fps if you turn fastcopper to ON.

**Comment by midwan** [comment]
The RPI4 can also now play this full-speed.

**Comment by ransom1122** [comment]
So this means on pi3b+ impossible to get full speed?

**Comment by emuchicken** [comment]
It's a shame to hear "upgrade your pi" when I used to rock Amiga emulation on a p200 back in the day.  Perhaps a slight overclock can be beneficial for this title ?  Still not really a "fix" is it ?

**Comment by ransom1122** [comment]
I've tried everything to fix Jim Power on 3B+ There's no reason why it shouldn't work on 3b+

Maybe after some emulator improvements...

I'm not going pi4 route just to play Jim Power, when I can play the game on less powerful machines then pi3b+

**Comment by emuchicken** [comment]
It's possible to get far better FPS on Jimmy by turning on quick copper, but still not optimal. I assume it's due to the amount and complexity that the behemoth of winuae has become... Maybe there's a work around within the code to have it run on a lighter routines?

I'm with you here ransom, but also I didn't develop this. ;)

**Comment by ransom1122** [comment]
Fast Copper.. No thanks...
Emulator advancements Yea Please

**Comment by emuchicken** [comment]
I actually loaded up a demo earlier this week, it was scrolling text, and I could see it visually lagging .  Jimmy's title screen is... All parallax scrolling isn't it ?  There has to be something that's chugging in relation to this.

**Comment by ransom1122** [comment]
Exactly, similar to Lionhearts paralax scrolling. I've said it before and I'll say it again, it's emulator code, not on par with winuae, nothing to do with pi 3b+

**Comment by midwan** [comment]
@ransom1122 
The reason this issue was closed was that there's nothing else I can think of to do regarding it.
The code in Amiberry is derived from WinUAE, and is actually even more optimized in parts to increase the performance. So saying it's not "on par with winuae" is false.

**Comment by emuchicken** [comment]
I thought it was focused more on "accuracy" rather than "performance"?  Hence the increase in required specs as winuae continued development.

**Comment by ransom1122** [comment]
The winuae old code was able to run Jim power many many years ago. So something seems not right.

**Comment by Darknior** [comment]
Yes i'm agree with @ransom1122 . WinUAE with time is so focuced on "accurracy" rather than "performance" ... with an old vertion of thie emulator we can play AMIGA on an XBOX 1, with 700Mhz of Proc and 64 Mo of RAM !!! But at this moment the emulator was focussed on performance for little boards...

**Comment by emuchicken** [comment]
So, as I stated earlier, is it possible to have a different option to run "performance (cough, old) code" only ?
Only for the problematic titles.

**Comment by midwan** [comment]
@emuchicken 
The "Fast Copper" option was exactly one such thing - it's older code that has since been removed from WinUAE, which hacked things together to gain some extra performance in copper related operations. This game makes heavy use of the copper, and thus sees an improvement if that is turned on.

However, since it's a bit of a hack, it may have unexpected glitches if turned on in some cases. 

And as you can see from the profiler results above, the copper use (which can be sped up with Fast Copper) was just one of the heavy use areas. The others are more standard functions from the custom chipset emulation (sprite, ECS display) and the CPU emulation itself.
