### ISSUE TITLE
Amiberry is slow when Coffin RTG is activated

### ISSUE THREAD

**Issue by philip930** [midwan/amiberry#582]
**Describe the bug**
I am using Coffin R54 hdr image copied to SD card as HDD in Amiberry. When Coffin uses ECS/AGA video mode, things are OK, sysinfo gives 260k+ MIPS, etc.

As soon as I activate any RTG mode, things become very slow and Sysinfo shows from 99k to 105k MIPS.

- OS: Raspbian Buster on RPi4.

- Amiberry 3.11 release, launching from console, both SDL and non-SDL versions suffer from the issue.

Config and Amiberry logs attached.
[ConfAndLogs.zip](https://github.com/midwan/amiberry/files/4140087/ConfAndLogs.zip)

**Comment by CypherXG** [comment]
With activated RTG Amiberry slows down. Thats normal.

**Comment by midwan** [comment]
@philip930 
What resolution are you running the RTG mode on?
And what bit depth?

**Comment by philip930** [comment]
I've tried multiple (1024x768 16 bit, 1920x1080 32 bit), it is slightly better if it's lower, but the general effect is the same - as soon as you turn on RTG, Coffin becomes so slow, nearly unusable.

**Comment by CypherXG** [comment]
Did you change the Picasso Driver.
Coffin is optimized for the Vampire Card. You can't compare these two different types of hardware.

**Comment by philip930** [comment]
I was choosing one of UAE: xxx modes in ScreenMode preferences, I guess this automatically means usage of included uaegfx driver.

**Comment by midwan** [comment]
@philip930 
Could you try removing the pre-installed P96 driver, and installing the latest one (either from Aminet or the newer one from IComp should work)?

And make sure that there's only `uaegfx` in the Devs:Monitors then, not the vampire gfx one as well?

**Comment by midwan** [comment]
@philip930 
This is confirmed to be related to the P96 files used in Coffin.
Try replacing the card driver(s) with the current P96 archive and only use `uaegfx` in your Devs:Monitors and things should work normally.
