### ISSUE TITLE
Multiple tries to start Amiberry

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#583]
**Describe the bug**
Installed Amiberry-rpi4-sdl2-v3.1.0 and changed the properties of the Amiberry icon to allow owner and group to execute.  When I click on execute, Amiberry does not always start.  Sometimes it takes 3-5+ times to start.  I made sure to update and upgrade before extracting Amiberry and trying to start it.  A log is not created until Amiberry starts.  This behavior also occurs if I select execute in terminal.

**Expected behavior**
Click on execute and Amiberry starts

**Screenshots**

**Desktop (please complete the following information):**

- OS: Raspbian Linux raspberrypi 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 LNU/Linux  (I am running the 64-bit kernal)

**Comment by midwan** [comment]
@digitalMedic 
That sounds a bit strange.
Did you use the Zipped binaries from the release or did you compile from source?
The binaries I provided are compressed with `upx`, so there's a slight chance your problem might be related to that. Try compiling one from source to see if it behaves differently for you.

I can't recreate this so far.

**Comment by digitalMedic** [comment]
I used the zipped SDL2 binaries.  I will try a fresh compile.

**Comment by digitalMedic** [comment]
I compiled the SDL2+dispmanx for the RPi 4B and I do not have the problem any more.  Might have been something with my Pi.  I also reinstalled Raspbian before I compiled Amiberry.  Thanks for checking though.
