### ISSUE TITLE
68060 support

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#584]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Would like to see full 68060 support.  Is this possible on the RPi?

**Comment by midwan** [comment]
Not at the moment I'm afraid.

The CPU core code is "borrowed" from the Aranym project, which only has up to 040 implemented. Without someone spending the time to implement 060 support, I don't see it happening.

But on the other side, it's not really needed in most cases. And it wouldn't make the emulation any faster either (probably the opposite).

**Comment by joolswills** [comment]
I was wondering what the use case for this may be anyway? Most software for higher end Amigas will work on the 040+fpu.

**Comment by digitalMedic** [comment]
Mostly a just because.  Not sure if the RPi can handle it, but I use it on WinUAE.
