### ISSUE TITLE
Typing and cursor move in GUI text fields

### ISSUE THREAD

**Issue by 2play** [midwan/amiberry#586]
Good day,
@midwan As I've mentioned when I tried to create custom configuration files, at the field where you enter the name I tried to put + (with shift) and no special chats can be entered.  When I press the arrow keys to move the cursor to type something extra it jumps out of the field and to next navigation button or option which is fine when moving around with keyboard but not when I wna to simply type.
So only way is to save the name as best as you can and then navigate to folder and update name manually.

I used this on Amiberry v3.09  pi3B board.

**Comment by midwan** [comment]
@2play 
The shift key to enter special characters doesn't currently work in Guisan, we've only managed to fix entering Capital letters (somewhat related issue here: https://github.com/kallisti5/guisan/issues/4)

But the behavior with the arrows can be controlled in Amiberry so I can fix that.

**Comment by 2play** [comment]
looking forward to it!

**Comment by midwan** [comment]
@2play 
This should be fixed with the latest updates. Please test and let me know ?

**Comment by 2play** [comment]
Kalimera @midwan 
I have compiled and installed 3.1.1
Confirm that cursor moving ok in the txt fields by the use of arrow keys rather jumping to next button etc.

Something of interest maybe...
- if I press END key on the keyboard while I was in the text field (configuration name or description)
it exited gui and booted the default config. I thought it would take me at the end of the text field instead
- as you mentioned SHIFT isnt working with special chars (+_etc)
- if num pad is off when starting the gui, it can not be enabled while in it. is this normal?
if num pad enabled before, i enter gui, light is on but only 2-4-6-8 work as arrow keys. if I press the key to enable (again) light still stays on and numbers work also :-)

Just for your ref.

KInd regards!

**Comment by midwan** [comment]
@2play 
Thanks for confirming.
The rest of the behavior you mention is "normal", in the sense that Guisan (the GUI framework used) will consume all keyboard input, but does not yet implement all the expected features. So far I've been reporting these things to the author(s), but since the project doesn't seem to move forward much I've started implementing solutions directly in our implementation.

If it's needed, we could add those as separate issues to implement further in Guisan.

**Comment by 2play** [comment]
@midwan  Thank you!
