### ISSUE TITLE
Using WHDLOAD - Is it possible to add gfx_center_vertical=smart to each game loaded

### ISSUE THREAD

**Issue by davidonabus** [midwan/amiberry#587]
I've found that the settings pulled from the WHD database work great, but every title I've tried requires me to add "gfx_center_vertical=smart" for it to fit properly on my television.

Is it possible to add this globally to all games loaded? Or will I need to create a UAE for each title I'd like to play?

**Comment by midwan** [comment]
@davidonabus 
This was recently added as a default global option in `amiberry.conf`:
https://github.com/midwan/amiberry/wiki/Amiberry.conf-options

Keep in mind that config files can override this of course, this is just the "default" behavior when you start up.

**Comment by davidonabus** [comment]
This is excellent news! Thank you
