### ISSUE TITLE
Budbrain Psychotic demo - missing part of texture

### ISSUE THREAD

**Issue by shelterx** [midwan/amiberry#588]
Amiberry v3.0.11 dietpi
A1200 mode, JIT, 3.1 kickstart, ClassicWB, whdload

I was reliving my youth and I noticed when "the squeeze" scene is loaded, the guy is missing top of his head.

I tried the exact same thing on FS-UAE, everything seems to wok there, no missing part of the texture.

**Comment by midwan** [comment]
What's the Height value set to, in the Display panel?

Try increasing that if it's too low (e.g. 200) and see if it helps?

**Comment by shelterx** [comment]
Got it set to max,. seems to be some sort of rendering issue with the animation used, if i quit the demo with F10 i see top of the head show up right before the demo quits back to workbench.

**Comment by solskogen** [comment]
Try without JIT

**Comment by shelterx** [comment]
No difference... perhaps some slight flicker that wasn't there before.

**Comment by shelterx** [comment]
I do get the same problem with JIT enabled in FS-UAE tho.

**Comment by solskogen** [comment]
Just for the heck of it.... Could you try a floppy version and set amiberry to emulate a A500?

**Comment by shelterx** [comment]
3.1 KS and a500/68000 mode works fine. 
My real A1200 is currently broken so I can't really compare with real hardware.

**Comment by deepx77** [comment]
'Blitter Immediate' works for me

**Comment by midwan** [comment]
This seems to be fixed in the latest Beta, when using Cycle-Exact mode and A500 configuration (tested with the disk version).
