### ISSUE TITLE
CD32 quits Amiberry

### ISSUE THREAD

**Issue by deepx77** [midwan/amiberry#589]
CD32 gives a black screen and crashes amiberry. It sends me back to the DietPi login screen.
Only when I select A1200 as the Extra in Chipset it will load the kickrom and ext rom with no problem. But then its not a CD32 and can't load disc images.

Steps:
1) Quickstart Amiga CD32
2) CD drive: image game Alfred Chicken (it works on Winuae with same image and kickstart-files)
3) Rom: CD32 KS Rom v3.1 rev 40.60 (512k)
4) Ext Rom: CD32 extended rom rev 40.60 (512k)
5) Port1: Generic X-Box pad (CD32)
6) Reset
7) Dark grey screen for 2 seconds, then Quits Amiberry by itself
8) It sends me back to the DietPi login screen

I use dietpi with Amiberry pre-compiled. 
I also create a config file myself but it also quits Amiberry.
My other config file: 68020/24bit/FPU:None/14mhz, AGA Chipset Extra:CD32/Blitter:Wait/Copper: OFF/Collision:Sprites and Sprites, ROM: CD32 KS 3.1 40.60/CD32 Extended 40.60, Chip:2MB) (Amiberry v3.1.0) (Pi3B+: stock speed)

**Comment by deepx77** [comment]
My logfile starts with my autoboot to my A1200 WHDLOAD config. That boots fine and has no issues.
After that I load the cd32 quickstart and after that crash I load my CD32 config file.

AMIBERRY Logfile

Allocated 16 MB for 24-bit area (0x20000000) and 640 MB for Z3 and RTG at fake address (0x30000000 - 0x58000020)
Controller Detection for Device: Generic X-Box pad 
Controller Detection for Device: SPEEDLINK COMPETITION PRO Game Controller for Android  
KS ver = 34 (0x22)
Stored port 0/0 d=0: added 200 0  
Stored port 0/0 d=0: added 200 0 Mouse MOUSE0
Port0: ID 'mouse' matched
Stored port 1/0 d=0: added 101 0  
Stored port 1/0 d=0: added 101 0 Generic X-Box pad JOY1
Port1: ID 'joy1' matched
Port2: NONE
Port3: NONE
0: 640x400, 8-bit (50,60)
1: 640x400, 16-bit (50,60)
2: 640x400, 32-bit (50,60)
3: 640x480, 8-bit (50,60)
4: 640x480, 16-bit (50,60)
5: 640x480, 32-bit (50,60)
6: 720x400, 8-bit (50,60)
7: 720x400, 16-bit (50,60)
8: 720x400, 32-bit (50,60)
9: 800x480, 8-bit (50,60)
10: 800x480, 16-bit (50,60)
11: 800x480, 32-bit (50,60)
12: 800x600, 8-bit (50,60)
13: 800x600, 16-bit (50,60)
14: 800x600, 32-bit (50,60)
15: 960x540, 8-bit (50,60)
16: 960x540, 16-bit (50,60)
17: 960x540, 32-bit (50,60)
18: 1024x768, 8-bit (50,60)
19: 1024x768, 16-bit (50,60)
20: 1024x768, 32-bit (50,60)
21: 1280x720, 8-bit (50,60)
22: 1280x720, 16-bit (50,60)
23: 1280x720, 32-bit (50,60)
24: 1280x800, 8-bit (50,60)
25: 1280x800, 16-bit (50,60)
26: 1280x800, 32-bit (50,60)
27: 1280x1024, 8-bit (50,60)
28: 1280x1024, 16-bit (50,60)
29: 1280x1024, 32-bit (50,60)
30: 1360x768, 8-bit (50,60)
31: 1360x768, 16-bit (50,60)
32: 1360x768, 32-bit (50,60)
33: 1366x768, 8-bit (50,60)
34: 1366x768, 16-bit (50,60)
35: 1366x768, 32-bit (50,60)
36: 1680x1050, 8-bit (50,60)
37: 1680x1050, 16-bit (50,60)
38: 1680x1050, 32-bit (50,60)
39: 1920x1080, 8-bit (50,60)
40: 1920x1080, 16-bit (50,60)
41: 1920x1080, 32-bit (50,60)
Trying to get Current Video Driver...
Trying to create window...
target_cfgfile_load(): load file /mnt/dietpi_userdata/amiberry/conf/default.uae
Controller Detection for Device: Generic X-Box pad 
Controller Detection for Device: SPEEDLINK COMPETITION PRO Game Controller for Android  
load config '/mnt/dietpi_userdata/amiberry/conf/default.uae':3
unknown config entry: 'config_hardware_path='
unknown config entry: 'config_host_path='
unknown config entry: 'config_all_path='
KS ver = 40 (0x28)
Stored port 0/0 d=0: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 1/0 d=0: added 102 0 SPEEDLINK COMPETITION PRO Game Controller for Android  JOY2
Port1: COMBO 'SPEEDLINK COMPETITION PRO Game Controller for Android' + 'JOY2' matched
Port2: NONE
Port3: NONE
KS ver = 40 (0x28)
Stored port 0/0 d=1: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 1/0 d=1: added 102 0 SPEEDLINK COMPETITION PRO Game Controller for Android  JOY2
Port1: COMBO 'SPEEDLINK COMPETITION PRO Game Controller for Android ' + 'JOY2' matched
Port2: NONE
Port3: NONE
Controller Detection for Device: Generic X-Box pad 
Controller Detection for Device: SPEEDLINK COMPETITION PRO Game Controller for Android  
Autoconfig board list:
Card 01: '<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: '<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.
Card 04: 'UAE FS ROM'
  d1.52.40.00.07.db.00.00.00.03.20.00.00.00.00.00
  MID 2011 (07db) PID 82 (52) SER 00000003
  Z2 0x00e90000 0x00e90000   64K ROM 0
END
KS ver = 40 (0x28)
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 1/1 d=0: added 102 0 SPEEDLINK COMPETITION PRO Game Controller for Android  JOY2
Port1: COMBO 'SPEEDLINK COMPETITION PRO Game Controller for Android ' + 'JOY2' matched
Port2: NONE
Port3: NONE
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 102 0 SPEEDLINK COMPETITION PRO Game Controller for Android  JOY2
RTAREA located at 00F00000
mapped_malloc(): 0x00f00000 - 0x00f10000 (0x20f00000 - 0x20f10000) -> UAE Boot ROM (rtarea)
TRAP_ENTRY = 00f0181a
mapped_malloc(): 0x00f80000 - 0x01000000 (0x20f80000 - 0x21000000) -> Kickstart ROM (kick)
mapped_malloc(): 0x00000000 - 0x00400000 (0x20000000 - 0x20400000) -> Chip memory (chip)
Try to get A3000 memory at correct place (0x08000000). 0 MB and 16 MB.
Succeeded: location at 0x28000000 (Amiga: 0x08000000)
mapped_malloc(): 0x08000000 - 0x09000000 (0x28000000 - 0x29000000) -> RAMSEY memory (high) (ramsey_high)
ROM loader.. (<none>)
Known ROM 'KS ROM v3.1 (A1200)' loaded
ROM loader end
memory init end
No disk in drive 0.
Resetting frame rate hack
1870 CPU functions
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 102 0 SPEEDLINK COMPETITION PRO Game Controller for Android  JOY2
Resetting frame rate hack
JIT popallspace: 0x6c228000-0x6c228200
<JIT compiler> : actual translation cache size : 16384 KB at 0x6c228200-0x6d228200
CPU=68020, FPU=68881 (host), JIT=CPU/FPU=16384. fast
memory init end
hdf_close_target
hfd attempting to open: '/mnt/dietpi_userdata/amiberry/Harddisks/System van RasPi WHDLOAD/System.hdf'
HDF '/mnt/dietpi_userdata/amiberry/Harddisks/System van RasPi WHDLOAD/System.hdf' opened, size=512000 mode=1 empty=0
Reset at 00000000. Chipset mask = 00000007
PAL mode V=50.0000Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
Autoconfig board list:
Card 01: '<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: '<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.
Card 04: 'UAE FS ROM'
  d1.52.40.00.07.db.00.00.00.03.20.00.00.00.00.00
  MID 2011 (07db) PID 82 (52) SER 00000003
  Z2 0x00e90000 0x00e90000   64K ROM 0
END
Card 0: skipping autoconfig (not autoconfig)
Card 2: skipping autoconfig (not autoconfig)
hardreset, memory cleared
mapped_malloc(): 0x00e90000 - 0x00ea0000 (0x20e90000 - 0x20ea0000) -> Filesystem autoconfig (*)
Card 4: Z2 0x00e90000   64K ROM Filesystem autoconfig
filesystem: diagentry 08000098 configdev 00000c00
waiting_blits detected PC=00f8b74a
PAL mode V=50.0000Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
Mounting uaehf.device:0 0 (0):
FS: mounted HDF unit DH0 (0000-1f400000, /mnt/dietpi_userdata/amiberry/Harddisks/System van RasPi WHDLOAD/System.hdf)
RDB: fakefilesys, trying to load '/mnt/dietpi_userdata/amiberry/kickstarts/FastFileSystem', dostype 0x444F5301 (DOS\1)
RDB: filesys not found, mounted without forced filesys
Mounting uaehf.device:0 1 (0):
FS: mounted virtual unit DH1 (/mnt/dietpi_userdata/amiberry/Harddisks/Demos-HD-dh1/)
Mounting uaehf.device:0 2 (0):
FS: mounted virtual unit DH2 (/mnt/dietpi_userdata/amiberry/Harddisks/Data-dh2/)
Mounting uaehf.device:0 3 (0):
FS: mounted virtual unit DH3 (/mnt/dietpi_userdata/amiberry/Harddisks/Games-dh3/)
FS: Demos (flags=00000000,E=0,ED=1,EF=0,native='/mnt/dietpi_userdata/amiberry/Harddisks/Demos-HD-dh1/') starting..
FS: Data (flags=00000000,E=0,ED=1,EF=0,native='/mnt/dietpi_userdata/amiberry/Harddisks/Data-dh2/') starting..
FS: Games (flags=00000000,E=0,ED=1,EF=0,native='/mnt/dietpi_userdata/amiberry/Harddisks/Games-dh3/') starting..
Autoconfig board list:
Card 01: '<no name>' no autoconfig 00da0000 - 00daffff.
Card 02: '<no name>' no autoconfig 00600000 - 00a7ffff.
Card 03: 'UAE Boot ROM' no autoconfig 00f00000 - 00f0ffff.
Card 04: 'UAE FS ROM'
  d1.52.40.00.07.db.00.00.00.03.20.00.00.00.00.00
  MID 2011 (07db) PID 82 (52) SER 00000003
  Z2 0x00e90000 0x00e90000   64K ROM 0
END
target_cfgfile_load(): load file /mnt/dietpi_userdata/amiberry/conf/CD32.uae
hdf_close_target
closing file handle 0x58b6770
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
Controller Detection for Device: Generic X-Box pad 
Controller Detection for Device: SPEEDLINK COMPETITION PRO Game Controller for Android  
load config '/mnt/dietpi_userdata/amiberry/conf/CD32.uae':3
unknown config entry: 'config_hardware_path='
unknown config entry: 'config_host_path='
unknown config entry: 'config_all_path='
KS ver = 40 (0x28)
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 1/1 d=0: added 101 7 Generic X-Box pad JOY1
Port1: COMBO 'Generic X-Box pad' + 'JOY1' matched
Port2: NONE
Port3: NONE
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 101 7 Generic X-Box pad JOY1
Autoconfig board list:
END
KS ver = 40 (0x28)
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Port0: COMBO 'Mouse' + 'MOUSE0' matched
Stored port 1/1 d=0: added 101 7 Generic X-Box pad JOY1
Port1: COMBO 'Generic X-Box pad' + 'JOY1' matched
Port2: NONE
Port3: NONE
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 101 7 Generic X-Box pad JOY1
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 101 7 Generic X-Box pad JOY1
Stored port 0/1 d=0: added 200 0 Mouse MOUSE0
Stored port 1/1 d=0: added 101 7 Generic X-Box pad JOY1
Resetting frame rate hack
JIT popallspace: 0x6c228000-0x6c228200
CPU=68020, FPU=0, JIT=0. fast
JIT popallspace: 0x6c228000-0x6c228200
CPU=68020, FPU=0, JIT=0.
mapped_malloc(): 0x00000000 - 0x00200000 (0x20000000 - 0x20200000) -> Chip memory (chip)
ROM loader.. (/mnt/dietpi_userdata/amiberry/kickstarts/Kickstart v3.1 rev 40.68 (1993)(Commodore)(A1200).rom)
mapped_malloc(): 0x00e00000 - 0x00e80000 (0x20e00000 - 0x20e80000) -> Extended Kickstart ROM (rom_e0)
Known ROM 'CD32 KS ROM v3.1' loaded
ROM loader end
memory init end
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
hdf_close_target
Reset at 00F811F8. Chipset mask = 00000007
PAL mode V=50.0000Hz H=15625.0878Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
Autoconfig board list:
END
hardreset, memory cleared
PAL mode V=50.0000Hz H=15625.0879Hz (227x312+0) IDX=10 (PAL) D=0 RTG=0/0
PAL mode V=50.0000Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0

**Comment by midwan** [comment]
@deepx77 
Does it work for you if you don't load the specific CD image?
You should get to the CD32 boot animation at least.

I'm thinking perhaps your crash is related to the image you're testing with, since I can't recreate a generic problem with CD32 emulation and other images here...

**Comment by deepx77** [comment]
Without an image I get the same crash. Only when I load with Chipset extra: A1200, it will boot to bootanimation. But if I'm the only one with this problem, then don't waste your time man. Maybe my Pi is faulty then, I don't know. It's not that important for me to run CD32 but it would make the package complete for me. Maybe in the future I will get a Pi 4 and the problem is gone.

**Comment by midwan** [comment]
@deepx77 
It's not related to the Pi itself normally, I just tested this on a Pi3 running Raspbian Buster and it worked as expected. 

If the other emulated models work fine, then maybe the CD32 kickstart ROMs might be faulty? Have you got an official set (e.g. Amiga Forever), can you try with others?

**Comment by deepx77** [comment]
I downloaded Amiberry 3.1.2 just a few minutes ago and now it's booting 8 out of 10 times. Don't know if it's just luck....  But I'll continue testing.

**Comment by deepx77** [comment]
I tried a couple of different roms before, all with same result. And all working without problems on Winuae. So, yeah I don't know.

**Comment by midwan** [comment]
@deepx77 
Could it be related to SD card issues? If the same images work sometimes but not always, that would also be an indication that something weird is going on.

Do you have another SD card to test with?

**Comment by midwan** [comment]
@deepx77 
Ping! :)
