### ISSUE TITLE
No FDD-Diskicon shown

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#590]
Hello i use amiberry 3.0.12 on a Raspberry Pi 4. RetroPie 4.5.13 is installed on Raspbian Buster.
I use AmigaOS 3.1.4.1 with Kickrom 3.1.4.

Everytime i incorporte a adf-file (Diskette) in virtual DiskDrive DF0: the Diskicon is not shown on the Workbench. DirectoryOpus shows the diskcontent correctly.

With every other virtual diskdrive the Diskicon is shown.

Kind Regards
Retro1968

**Comment by midwan** [comment]
I can't recreate this, every time I insert a disk in DF0: it shows up correctly in AmigaOS 3.1.4.x

Have you tried with a minimal system installation? Perhaps you have something running in your AmigaOS system that does this?

**Comment by Retro1968** [comment]
Oh... shame on me. I forgot that i hided device DF0: under Prefs/Workbench. I changed that, so that now the discicon of DF0: is shown correctly... Problem solved.

**Comment by midwan** [comment]
Thans for confirming.
