### ISSUE TITLE
BorderBlank do not work

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#591]
Hello i use amiberry 3.0.12 on a Raspberry Pi 4. RetroPie 4.5.13 is installed on Raspbian Buster.

When i start an adf-file the disk is loaded correctly and the program runs fine.
The problem is that i start the program BorderBlank in the startup-sequence before the mainprogram is loaded, but the border wont get black. On an original Amiga 1200 it runs fine. I tried several other border blank programs but all of them do not work with amiberry. I tried it with austerlitz.adf but other all tested adfs do have that issue.

Kind Regards
Retro1968

**Comment by midwan** [comment]
Testing with http://aminet.net/package/util/boot/BorderBlank seems to work fine here, using the latest Amiberry and AmigaOS 3.1.4

**Comment by Retro1968** [comment]
Running BlackBorder with Austerlitz on AmigaOS 3.1.4 works.
![2](https://user-images.githubusercontent.com/58906142/74939083-9167a780-53ef-11ea-8cd6-b748fa7da956.jpg)


BlackBorder do not work running the ADF Austerlitz (Disk uses Kick 1.3) from RetroPiemenu with Amiberry Autoload. All tested ADFs results in no working of BlackBorder when started via Amiberry Autoload.
![1](https://user-images.githubusercontent.com/58906142/74939244-d7247000-53ef-11ea-88a2-470dd636b9b1.jpg)

**Comment by midwan** [comment]
You mentioned this works on a real A1200 - but that's not a 1.3 machine either.
When you run it using the Autoload option, it will try to use the most compatible settings (which could be A500 with Kick 1.3). Perhaps borderblank doesn't work at all with Kick 1.3 in general.

Have you tested this with WinUAE and a similar config (e.g. A500, kick 1.3) ?

**Comment by Retro1968** [comment]
The second picture is form amiberry autoload. That uses Kick 1.3.

On my real Amiga it runs too, but i sended no foto of it. Both above photos are Raspberry Pi. The first with amiberry an amigaos 3.1.4. The second the pure austerlitz.adf with blackborder with amiberry autoload.

**Comment by Retro1968** [comment]
To reproduce it. Get austerlitz or any other disk you want. Put blackborder on it and start it in startup-sequence. Then start it via amiberry autoload on raspberrypi.

**Comment by midwan** [comment]
Borderblank does not work on Kickstart 1.3 - this is not an issue with the emulator, as WinUAE also behaves the same way.

When you launch a game using autoload, it will use the most compatible settings for that game. In some cases, that can be Kickstart 1.3 of course. That's why you see that it works when you run it under a newer Kickstart version, but not when using autoload.

**Comment by Retro1968** [comment]
Ok, i didnt knew that. Tested it and now works when using Kickrom 3.1.

**Comment by midwan** [comment]
No worries! :)
