### ISSUE TITLE
Unable to Transfer/Write to any folder within the Amiberry Folder

### ISSUE THREAD

**Issue by RetroAsh** [midwan/amiberry#593]
I have connected via FTP and can write to all folders except the Amiberry Folder and any folder inside this folder.

What Im I doing wrong ?

**Comment by pawelomega** [comment]
Did you check folder permision ?

**Comment by midwan** [comment]
@RetroAsh 
Which distro are you referring to? This is 99% related to permissions, for example RetroPie places Amiberry in a folder where only `root` has write access.

**Comment by RetroAsh** [comment]
Im using dietpi version of amiberry. I have now been able to sort this by using file explorer built into dietpi and change the permissions on the amiberry folder, be default this folder is locked down and does not mention anything about enabling permissions on the web guide. I was trying to FTP kickstarts and getting permisson errors.

https://dietpi.com/phpbb/viewtopic.php?t=5&start=20

**Comment by midwan** [comment]
@RetroAsh 
Hm, in that case please report this to the DietPi team so they can get it fixed please?

**Comment by MichaIng** [comment]
@RetroAsh 
Indeed on DietPi by default the Amiberry directory `/mnt/dietpi_userdata/amiberry` is owned by root:root, with 755/644 permissions, hence only root is able to write to this directories, while our file servers come with dietpi:dietpi by default.

Just to assure, does or did the following solve the issue?
```
chown -R dietpi:dietpi /mnt/dietpi_userdata/amiberry
```

While I think that the program itself should keep root R/W only, at least the kickstarts sub directory could or should have dietpi user ownership to enable access for the file servers by default. Also I can add the info to our online docs, for things like the floppy directory or others where one might want to upload data to.
