### ISSUE TITLE
Add x86 support

### ISSUE THREAD

**Issue by egrath** [midwan/amiberry#594]
**Idea**
Allow compilation not only for ARM targets, but also x86

**Possible solution**
Add the x86 JIT from WinUAE to AmiBerry, as everything else is pretty generic to all platforms?

**Reason**
More and more x86 compatible SBC are available on the market (LattePanda, Udoo Bolt, ...) which would make a great Amiga Emulation Box.

**Comment by MichaIng** [comment]
I would love that as well, but based on a short discussion it seems to be more work, then just JIT.

**Comment by midwan** [comment]
It's a bit more work than just JIT, as the CPU emulation in general is ARM-specific right now (and also quite simplified from the full-blown emulation model that WinUAE has, for performance reasons).
It's certainly not impossible, but it requires some time and effort.

It would have been great if someone were to pick this up and help, otherwise it will have to wait until its time comes. :)

**Comment by midwan** [comment]
There is now an experimental x86-64 target in the Makefile, in the `dev` branch. JIT is not enabled, as it requires more work to adapt that, but the rest of it seems to work normally so far.

I've tested it on a Manjaro x86-64 installation, as well as on WSL2 on Windows 11, both worked (and quite fast).

**Comment by MichaIng** [comment]
Awesome. I anyway wanted to add some more target builds to DietPi the next days. Will give it a try then.

**Comment by midwan** [comment]
@MichaIng Let me know if you notice anything, this is still fresh and I'd like to test it more, before I merge it back to `master` for the next release. The `dev` branch is almost identical to `master`, except for some custom chipset changes coming from WinUAE, which make it more accurate but a bit slower. Not a problem on a x86 platform of course. :)

**Comment by midwan** [comment]
Closing this as it's implemented, even if without JIT for now. Will look into adding x86 JIT later, as it needs a big rewrite of the CPU handling code (it's currently hardcoded for ARM)
