### ISSUE TITLE
Resolution switching causing crash back to linux on Manjaro Minimal x64

### ISSUE THREAD

**Issue by rockheddie** [midwan/amiberry#595]
I am running my own setup on Manjaro Minimal with Amiberry DISPMANX built from source v3.1.2.
It seems that switching resolutions in applications causes a crash back to linux, no Guru, just straight out.

My setup is RTG using P96 and my Workbench is set to 1920x1080, and this works all fine.

Changing resolutions in programs that use their own screens, public or not, seems to always cause a crash though.

It is reproducible for me when using any application, for example, if I load a new image in PersonalPaint, I get the dialogue asking if I want to switch resolution and bitdepth, after clicking yes I crash.

Same thing for example if I load AWeb on its own public screen and change the settings to use a new screenmode, crash.

These issues using the exact same setup except on 32bit Raspbian Lite do not occur there, only on x64 Manjaro.

[amiberry_log.txt](https://github.com/midwan/amiberry/files/4235665/amiberry_log.txt)

**Comment by midwan** [comment]
This might be related to the experimental 64-bit Dispmanx version.
Do you have similar issues when using the normal SDL2 version?

**Comment by rockheddie** [comment]
I tried today with the SDL2 version without DISPMANX.

When performing the same tests, Instead of crashing to the console the system freezes.  I can't bring up the Amiberry GUI, no input seems possible, after about 10 or 12 seconds of hanging it then crashes out to the console.

**Comment by midwan** [comment]
@rockheddie 
Is this still happening for you?
I've only been testing on Manjaro desktop, but it works fine for me in all scenarios.

**Comment by midwan** [comment]
@rockheddie 
Any progress on this?
It would be worth testing with the latest release (v3.2.1) to see if you still have any issues or not.

**Comment by midwan** [comment]
Closing this since I cannot recreate it, and it seems to be stale.
