### ISSUE TITLE
Hotkey for safe shutdown.

### ISSUE THREAD

**Issue by rockheddie** [midwan/amiberry#596]
Since Amiberry has assignable hotkeys for the GUI and also EXIT.  I was hoping it would be possible to make an assignable hotkey for safe shutdown as well.

This will save a step of having to go into the GUI to do this, or exit to console.  It will also be really handy for people who are putting their Pi's into Amiga cases and other projects and who want to keep the experience as close to real as possible.

**Comment by MrNoHolster** [comment]
Ctrl + A + A would be an awesome function to power off, just like the reset on a real Amiga!

**Comment by midwan** [comment]
@MrNoHolster 
That key combination is already taken, to reset the emulated Amiga. :)
