### ISSUE TITLE
No control in GUI with gamepad after update to 3.1.2

### ISSUE THREAD

**Issue by joolswills** [midwan/amiberry#597]
**Describe the bug**
Gamepad can enter GUI but cannot navigate with the gamepad after update from 3.1.0 to 3.1.2

I just rebuilt binaries for retropie and noticed this. Using retroarch config for the controller.

GUI seems sluggish too

This is on a RPI4 with RetroPie. Gamepad is a basic ibuffalo usb snes style controller.

I will bisect the recent commits and debug to provide more information - sorry this is brief for now.

**Comment by midwan** [comment]
hm, it seems to work fine here with a DS4 controller on Raspbian... Let me know if you know more?

**Comment by joolswills** [comment]
I have bisected the GUI input problem to commit 615e9520e

Are all those changes supposed to be in that commit? It's got loads of input change logic and re-indents. Looks like it's not all supposed to be there tbh.

**Comment by midwan** [comment]
@joolswills 
Yeah, that was intentional actually. Instead of listening to all game controller events, I changed the logic to only listen to specific ones in the GUI. This was to address issues of e.g. DS4 controllers which have a gyro and reported events constantly, which in turn resulted in higher CPU usage that necessary.

If you're not getting any input triggered, then I assume your controller sends different events through SDL2 than the ones we're listening for. I can test with a few different controllers here to see if I can recreate this.

**Comment by midwan** [comment]
More specifically, the controller events it's listening for currently are:
* SDL_JOYHATMOTION
* SDL_JOYBUTTONDOWN
* SDL_CONTROLLER_AXIS_LEFTX
* SDL_CONTROLLER_AXIS_LEFTY

so far, the controllers I've tested with worked normally with this code. I don't have the same model as yours, but perhaps it's reporting something else (e.g. maybe SDL_CONTROLLER_AXIS_RIGHT ? Although that's normally for analog sticks).

Normally the D-Pad is reported as a HAT, and analog sticks as AXIS_LEFT/AXIS_RIGHT, but I know that some weird controllers might be reporting different things than expected.

**Comment by joolswills** [comment]
Code looks maybe incorrect to me

I don't see in the sdl docs that using SDL_PollEvent will return any SDL_CONTROLLER_AXIS_LEFTX / LEFTY event type?

https://wiki.libsdl.org/SDL_EventType

Navigation seems works doing this but I've only just done a quick test as I have no free time right now

```diff
diff --git a/src/osdep/gui/main_window.cpp b/src/osdep/gui/main_window.cpp
index 6ef765c..be8dbd0 100644
--- a/src/osdep/gui/main_window.cpp
+++ b/src/osdep/gui/main_window.cpp
@@ -625,8 +625,7 @@ void checkInput()
 			}
 			break;
 
-		case SDL_CONTROLLER_AXIS_LEFTX:
-		case SDL_CONTROLLER_AXIS_LEFTY:
+		case SDL_JOYAXISMOTION:
 			if (gui_joystick)
 			{
 				gotEvent = 1;

```

Btw it would be a lot easier to debug and I think manage the code if you did less changes in one commit. And did cosmetic changes separately also. Not trying to be overly critical :-)

**Comment by joolswills** [comment]
There may be other changes needed elsewhere too. But the above may help. Cheers.

**Comment by midwan** [comment]
@joolswills 
You're right, I missed that - sorry.
I'll get it updated ASAP. Thanks for the assist!

**Comment by joolswills** [comment]
I don't know the code as well as you. But it would seem it may be possible to have some shared input functions for all the GUI code? Even if there needs to be different behaviour perhaps some of it could be abstracted?

**Comment by joolswills** [comment]
Thanks for the fix also.
