### ISSUE TITLE
Whdload won't load games if Z2 Fast Ram is set to 8Mb

### ISSUE THREAD

**Issue by shelterx** [midwan/amiberry#598]
Amiberry v3.0.11 dietpi
A1200 mode, JIT disabled, 3.1.4 kickstart, 8Mb fast

For some reason the WHDLoad games won't start if I set Amiberry to use 8Mb fast mem.

As a "reference" I tried with FS-UAE using the same settings, it worked fine.

**Comment by solskogen** [comment]
I can confirm this.
Not sure if it's related, but if you only configure Z2 memory (not z3) "C:LoadModule libs:intuition.library" in startup-sequence will result in a never-ending reset. 
A workaround is to not use z2, but rather use z3 instead.

**Comment by shelterx** [comment]
Hmm, yes Z3 Fast Ram works. Z2 does not.
I just felt it to be more logical to pick Z2 for the A1200 emulation... And at first I couldn't change the Z3 slider for some reason.

**Comment by solskogen** [comment]
Turn off 24-bit addressing in CPU and FPU page to be able to add Z3.

**Comment by midwan** [comment]
This doesn't seem to be an issue with the current `dev`, in my tests...
