### ISSUE TITLE
Hotkey for menu not working

### ISSUE THREAD

**Issue by MrNoHolster** [midwan/amiberry#599]
Just updated to the new version and I've noticed the usual hotkey for menu toggle is no longer working. I'm using a real Amiga keyboard, and previously the key to toggle the menu screen was 'Keypad *' but that's not working now. Is there a default key that combination I should know about?

**Comment by midwan** [comment]
The default key has always been F12, but you can change it in the amiberry.conf setting file.

**Comment by midwan** [comment]
For your reference:
https://github.com/midwan/amiberry/wiki/Amiberry.conf-options
You can set the default enter GUI key there.

Besides that, there is an option in the GUI panel itself, that will allow you to set a key and save that to a .uae config file instead. Keep in mind that .uae config files will override any defaults you have set.

**Comment by MrNoHolster** [comment]
Brilliant, thanks again Dimitris! 👍
