### ISSUE TITLE
Native CD-rom (bootable .iso) function

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#602]
**Is your feature request related to a problem? Please describe.**
Unable to use bootable CD .iso images in Amiberry

**Describe the solution you'd like**
Is it possible to have a similar CD rom system that is built into WinUAE?

**Comment by CypherXG** [comment]
It is possible to boot an iso without cd32 funktion.
You have to extract the cd.device from the extended Rom.
Put that cd.device into devs.
Ajust the CD0 Info file and mount cd0.

**Comment by midwan** [comment]
Booting from CD is only supported for CD32 for now.

There are plans to add support for mounting CDs in the system, like WinUAE (covered in #37).
However, booting from CDs was not supported on real Amiga hardware (except for CDTV and CD32 of course), so is your description/request accurate? Or are you referring to mounting them?

**Comment by digitalMedic** [comment]
I thought OS 3.9 could boot from CD, but I could be wrong.  I couldn't get it to boot from CD on my A4000 with OS 3.1.4 roms.  I would like the auto mount feature like WinUAE though for sure.  :D
