### ISSUE TITLE
Crash out of emulator w/FPU JIT enabled

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#603]
**Describe the bug**
If using FPU JIT, the emulator crashes out if opening some programs.  Turn off FPU JIT and crash does not happen.  This just started happening after latest Amibian update and Amiberry recompile (through Amibian).

**To Reproduce**
1.  Select config using FPU JIT
2.  Start emulator and wait for it to load WB
3.  Open one of the following programs: MUI 5.0 prefs or EvenMore.  Others may crash as well, have not tried.

**Expected behavior**
That the programs open with crashing to the desktop.

**Desktop (please complete the following information):**

- OS:  Amibian 1.5ee (latest version as of 2/29/2020 with 64-bit kernel

- Amiberry Version: 3.1.2

- AmigaOS version:  3.1.4

Other context:  This problem does not occur with CPU JIT on and FPU JIT off.

**Comment by midwan** [comment]
I cannot recreate this when using Raspbian Buster (32-bit). I'll test under Manjaro 64-bit also to see if it's only happening there. Have you tested a 32-bit version as well?

**Comment by midwan** [comment]
Nope, can't recreate it under 64-bit Manjaro either, running AmiKit XE (which includes MUI 5.0).

**Comment by digitalMedic** [comment]
I have only tried it under Amibian 1.5ee.  I just updated Amiberry under Amibian and it is still crashing with FPU JIT on.

**Comment by midwan** [comment]
You mentioned you used a 64-bit kernel however, which is experimental. Perhaps that's causing the problem, since I cannot recreate it in either 32-bit Raspbian or pure 64-bit Manjaro.

Otherwise, perhaps it's something within your emulated system that's causing issues?

**Comment by digitalMedic** [comment]
I will try a couple more things and report back.  I have been using the 64-bit kernel for some time without this issue.  I'll revert back to the 32-bit kernel and see if that helps.  I may also reinstall Amibian as there are other issues that are slowly creeping up with that also.

**Comment by digitalMedic** [comment]
I tried the .hdf file that was crashing with FPU JIT under Amibian's Amiberry and it works fine under Raspbian's Amiberry (new install).  No idea what is wrong.  Thanks for checking.

**Comment by digitalMedic** [comment]
I just compiled the latest version of Amiberry under the latest version of Raspibian.  With the 32bit kernel, Amiberry does not crash with the FPU JIT enabled.  If I update and enable the 64bit kernel, Amiberry crashes with FPU JIT enabled when I open some programs (i.e.: MUI prefs, EvenMore, etc.).

**Comment by solskogen** [comment]
That's probably not a amiberry problem, unless it also crashes under *real*
64bit OS like Manjaro.

**Comment by midwan** [comment]
@digitalMedic 
It seems that this might be an issue with the experimental 64-bit kernel on Raspbian then.
I've tested it and so far cannot recreate the problem, on both 32-bit Raspbian and 64-bit Manjaro...

**Comment by digitalMedic** [comment]
Ok, it may be either the 64-bit kernel.  Not sure they have changed anything in the 64-bit kernel recently, but who knows.  I cannot recreate it with any other system (Manjaro, 32bit Raspibian, etc.).
