### ISSUE TITLE
Crash to desktop/cli if no config selected and load hit

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#604]
**Describe the bug**
If hitting 'Load' config button before selecting a config, the emulator crashes to the desktop/cli

**To Reproduce**

1. Run the emulator

2. Click on 'Configurations'

3. Without selecting a configuration, hit the 'Load' button.

4. Emulator crashes out.

**Expected behavior**
Would be nice to have an error trap that gives a message stating a configuration file needs to be selected first, preventing the emulator from crashing.

**Desktop (please complete the following information):**

- OS: Amibian 1.5ee

- Version: 3.1.2 (also occurred on 3.1.1)

**Comment by midwan** [comment]
@digitalMedic 
Thanks for reporting this, I had missed it somehow. :)
