### ISSUE TITLE
Mouse pointer gone in emulator config screen

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#605]
**Describe the bug**
There is no mouse pointer in the emulator's config screen after I updated it.  It was there until I updated Amiberry and Amibian two days ago.

**To Reproduce**
Start the emulator and try to find the mouse pointer  :)

**Expected behavior**
Have a mouse pointer in the config screen

**Desktop (please complete the following information):**

- OS: Amibian 1.5ee

- Amiberry Version: 3.1.2 (2020-02-18)

**Comment by midwan** [comment]
Please make sure that you have Fake KMS enabled in the `/boot/config.txt` file.
You should have the line: ```dtoverlay=vc4-fkms-v3d``` uncommented there.

**Comment by digitalMedic** [comment]
Ok, that fixed it.  Is this a change that will be permanent?  I haven't had to enable the fake KMS before.

**Comment by midwan** [comment]
@digitalMedic 
Actually it's always been like that - if you want to use SDL2 and KMSDRM (to get full screen output from the console), you need that option enabled. :)

**Comment by digitalMedic** [comment]
OK, weird.  Never had to use it before the other day.  All set now though.
