### ISSUE TITLE
Slow RTG with 31kHz mode on

### ISSUE THREAD

**Issue by TuKo1982** [midwan/amiberry#606]
Describe the bug
If using Picasso96 in 31kHz mode (via PVS tool), RTG gets super slow and unusable. Reverting it back to 15kHz fixes it. 31KHz is needed for 44kHz audio.

To Reproduce

- Start a Picasso96 workbench
- Change mode to 31kHz via PVS tool, save or use
- Feel the slowness
- Reopen PVS tool
- Change mode to 15kHz, save or use
- Speed is back to normal

Desktop (please complete the following information):
OS: Amibian 1.5ee
Amiberry Version: 3.1.2
AmigaOS version: 3.9

**Comment by amyren1966** [comment]
Just tested on my Picasso96 / OS3.9 workbench and can confirm this issue. I also did upgrade P96 to the latest iComp 2.4.4 version, but the issue ramains.

**Comment by TuKo1982** [comment]
It means it's not P96 related but more about how the emulator handles multiscan signal. P96 31kHz is a trigger for it.

**Comment by amyren1966** [comment]
Ok. But how can I test this in combination with the audio, because in uae the audiosettings are 44100 by default, and I do get sound without using 31khz?

**Comment by midwan** [comment]
This seems to be fixed in `master` now, or at least I can no longer recreate it.
Could you please test and verify, @TuKo1982 ?
