### ISSUE TITLE
Dependency file names

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#607]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Code page that describes install and compile lists dependencies, but the file names shown will not pull the dependencies.  The new filenames are:

sudo apt-get install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0 libxml2 flac mpg123 libmpeg2-4

**Comment by MichaIng** [comment]
Indeed:
- Debian: https://packages.debian.org/libsdl2, https://packages.debian.org/libmpeg2
- Ubuntu: https://packages.ubuntu.com/libsdl2, https://packages.ubuntu.com/libmpeg2

**Comment by midwan** [comment]
Thanks, I've updated the readme file accordingly.
