### ISSUE TITLE
BUG? Amiga screen settings keeps resetting?

### ISSUE THREAD

**Issue by shelterx** [midwan/amiberry#609]
Amiberry v3.0.11 dietpi, also tried version v3.1.2.

I just got myself a 4:3 monitor. When I set Amiga Screen to 640x256. that gives me a full screen without borders, if I center horizontal and vertical. Just like I want to.

However when I quit any game (or some amiga programs) and start another, it goes back to 640x200 or 640x288 for some reason.
I've fiddled with settings but it always reverts back.

Is there any way to make it KEEP my setting? Otherwise I'd file this as a bug.
For plain desktop use I'm using P96 UAEGFX, that always shows up correct.

**Comment by midwan** [comment]
@shelterx 
How do you "quit a game and start another" exactly?
If you close the emulator and start another instance, it will reset the settings to their defaults.
If you start a game through some front-end, like RetroPie, it might load a config with certain settings first.
And if you're using WHDLoad installations (.lha game packs), they will also attempt to change settings per title, based on a matching entry in the WHDLoad Booter XML. Some settings there are not ideal and that's a known issue.

**Comment by shelterx** [comment]
Hmmm Its whdload games but the same issue happens when I start SysInfo. So I don't think it's related only to whdload. Would be nice to have a force or keep option for the Amiga screen setting.

**Comment by shelterx** [comment]
Btw I start the games from workbench. So I don't start them directly from amiberrys whdload feature.

**Comment by midwan** [comment]
Sorry, but I'm a bit confused.
Are you saying that if you have WB running, then start SysInfo, the emulator configuration in Display changes values?

**Comment by shelterx** [comment]
Yes, to reproduce:
1. Set the Amiga screen setting to 640x256
2. Start SysInfo (I have WB 3.1.4 installed on a HDF image with P96 drivers)
3. Quit SysInfo
4. Check Amiga screen settings in Amiberry, it should have reverted to 640x288 or something.

Same thing happens with WHDLoad games started from Workbench.

**Comment by midwan** [comment]
Interesting, it's only the height that seems to change for some reason.
Let me look into this and find out what causes it...
