### ISSUE TITLE
Retropie updating/ installing from source does not work

### ISSUE THREAD

**Issue by Fantomas13** [midwan/amiberry#610]
**Describe the bug**

When I start Updating from source I get this log:

Log started at: Thu 12 Mar 12:06:17 CET 2020

RetroPie-Setup version: 4.5.1 (922149b0)
System: Raspbian GNU/Linux 9.9 (stretch) - Linux retrobox 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'amiberry' : Amiga emulator with JIT support (forked from uae4arm)
= = = = = = = = = = = = = = = = = = = = =

/home/pi/RetroPie-Setup/tmp/build/amiberry /home/pi

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'amiberry' : Amiga emulator with JIT support (forked from uae4arm)
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --depth 1 --branch master "https://github.com/midwan/amiberry/" "/home/pi/RetroPie-Setup/tmp/build/amiberry"
Cloning into '/home/pi/RetroPie-Setup/tmp/build/amiberry'...
Submodule 'external/capsimg' (https://github.com/FrodeSolheim/capsimg) registered for path 'external/capsimg'
Submodule 'external/libgo2' (https://github.com/OtherCrashOverride/libgo2) registered for path 'external/libgo2'
Submodule 'external/libmpeg2' (https://android.googlesource.com/platform/external/libmpeg2) registered for path 'external/libmpeg2'
Cloning into '/home/pi/RetroPie-Setup/tmp/build/amiberry/external/capsimg'...
Cloning into '/home/pi/RetroPie-Setup/tmp/build/amiberry/external/libgo2'...
Cloning into '/home/pi/RetroPie-Setup/tmp/build/amiberry/external/libmpeg2'...
Submodule path 'external/capsimg': checked out '1713452be0c5adf94fcb22bcb083adc5dac45876'
Submodule path 'external/libgo2': checked out '27879347b053cb1aab59cd2a1b8b16372b8ccb3a'
Submodule path 'external/libmpeg2': checked out '185d891f1c282732584f5dbfed224ddefe864cc6'
HEAD is now in branch 'master' at commit '9b4712cfd73c9c0cbe8155e3e53ba3a534adc0e7'
patching file Makefile
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
/home/pi
amiberry patch /home/pi/RetroPie-Setup/scriptmodules/emulators/amiberry/01_remove_cflags.diff failed to apply

Log ended at: Thu 12 Mar 12:06:29 CET 2020
Total running time: 0 hours, 0 mins, 12 secs

**To Reproduce**
1. Go into Retropie-Setup
2. Got to manage Packages
3. go to optional packages
4. go to amiberry
5. go to "update from source"

Removing an try to install again i become the same problem

**Expected behavior**
Normal Update/ Installation via source

**Desktop (please complete the following information):**

- OS: Retropie 4.5

I tried over LAN and WLAN

**Comment by joolswills** [comment]
This is not an amiberry issue. I guess the RetroPie makefile patch isn't applying and it will need readjusting. I will sort it.

**Comment by joolswills** [comment]
Please report retropie issues first on the RetroPie forum.

**Comment by joolswills** [comment]
actually, RetroPie looks fine - you haven't updated RetroPie-Setup so you're running an old version of the scriptmodule.
