### ISSUE TITLE
src/inputdevice.cpp build error

### ISSUE THREAD

**Issue by philstopford** [midwan/amiberry#611]
Build from current source fails with the below. I couldn't see an existing ticket, so hope this report is useful

```
src/inputdevice.cpp: In function ‘void inputdevice_store_unplugged_port(uae_prefs*, inputdevconfig*)’:
src/inputdevice.cpp:581:25: error: could not convert ‘{0}’ from ‘<brace-enclosed initializer list>’ to ‘jport’
  struct jport jpt = { 0 };

```

**Comment by midwan** [comment]
@philstopford 
It doesn't for any system I've been testing on.
Please provide more details regarding distro and environment (including versions)?

**Comment by philstopford** [comment]
pi@retropie:~/RetroPie-Setup/tmp/build/amiberry $ uname -a
Linux retropie 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

Not sure how to check versions:

```
sudo apt-get install gir1.2-ibus-1.0 libdbus-1-dev libegl1-mesa-dev libibus-1.0-5 libibus-1.0-dev libice-dev libsm-dev libsndio-dev libwayland-bin libwayland-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev x11proto-randr-dev x11proto-scrnsaver-dev x11proto-video-dev x11proto-xinerama-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libroar-dev' instead of 'libsndio-dev'
gir1.2-ibus-1.0 is already the newest version.
gir1.2-ibus-1.0 set to manually installed.
libdbus-1-dev is already the newest version.
libdbus-1-dev set to manually installed.
libibus-1.0-5 is already the newest version.
libibus-1.0-5 set to manually installed.
libibus-1.0-dev is already the newest version.
libice-dev is already the newest version.
libice-dev set to manually installed.
libroar-dev is already the newest version.
libsm-dev is already the newest version.
libxi-dev is already the newest version.
libxinerama-dev is already the newest version.
libxkbcommon-dev is already the newest version.
libxrandr-dev is already the newest version.
libxss-dev is already the newest version.
libxt-dev is already the newest version.
libxv-dev is already the newest version.
x11proto-scrnsaver-dev is already the newest version.
x11proto-scrnsaver-dev set to manually installed.
x11proto-video-dev is already the newest version.
x11proto-video-dev set to manually installed.
x11proto-xinerama-dev is already the newest version.
x11proto-xinerama-dev set to manually installed.
libegl1-mesa-dev is already the newest version.
libwayland-bin is already the newest version.
libwayland-bin set to manually installed.
libwayland-dev is already the newest version.
libwayland-dev set to manually installed.
x11proto-randr-dev is already the newest version.
x11proto-randr-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by midwan** [comment]
Have you upgraded the RetroPie-Setup script first?

**Comment by philstopford** [comment]
Yes. Here's the uncompressed log.

[rps_2020-03-13_162510.log](https://github.com/midwan/amiberry/files/4330828/rps_2020-03-13_162510.log)

**Comment by midwan** [comment]
Hm, it might be best to open this issue in RetroPie's side first then, since I cannot recreate it here. Perhaps it's something specific there?

**Comment by joolswills** [comment]
They are running Raspbian Jessie which is no longer supported. It has an old GCC. RetroPie-Setup opens a dialog saying it's unsupported so not sure why that's been ignored.

**Comment by joolswills** [comment]
There's an issue in the log with installing SDL2 - it shouldn't try and use a binary install (there are no prebuilt binaries for jessie any more), but  we don't check anything on Jessie. It was dropped over a year ago.

**Comment by midwan** [comment]
@joolswills Thanks for the clarification :)

**Comment by philstopford** [comment]
I remember seeing the dialog, but it wasn't obvious why it was coming up and given the large amount of text, it seemed like an informational dialog rather than something important. It didn't seem to block the sequence of events. Some bright red text (error/warning/unsupported) would probably be useful.

I've got the RPi chewing on the upgrade to stretch. We'll see how that goes.

**Comment by philstopford** [comment]
Stretch installed, update now seems to go through without issues. Thanks to all.
