### ISSUE TITLE
[Question] Clarification about SDL2 video backends

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#612]
Short question, as I lack some understanding of graphics rendering and drivers in general 😅. If I compile SDL2 with `--enable-video-kmsdrm`, does it need to be compiled with `--enable-video-opengles2` as well, respectively does it need to show GLESv2 as supported graphics module in build summary?

With `libgles2-mesa-dev` installed, it is done automatically, if not `--disable-video-opengles2` used, but I am wondering if it can use KMS/DRM directly without having GLESv2 graphics module listed explicitly.

**Comment by midwan** [comment]
From what I know, you don't need to use `--enable-video-opengles2` as it's enabled by default.
The KMS/DRM code is not enabled by default, so you need to use the flag if you want it.

**Comment by solskogen** [comment]
This seems like a question for
https://discourse.libsdl.org/c/sdl-development

**Comment by MichaIng** [comment]
@midwan 
Yes it is enabled by default, at least when the related -dev package is installed. The question is if it would be possible to disable it, as long as KMS/DRM is enabled, or if in cases both backends are required/can be used concurrently.

@solskogen 
Thanks for the link. I think I'll simply try it out, once all current builds (with GLESv2 enabled) are done.
