### ISSUE TITLE
Please write how to activate Action Replay III

### ISSUE THREAD

**Issue by Toontje** [midwan/amiberry#616]
I have seen the video at https://www.youtube.com/watch?v=ypVnq3bjwQw on the fact that the AR3 works, but i cannot get it to work myself. I have configured the North key to launch the cartridge, but it doesn't launch. I'd love the AR3 in my games.

**Comment by CypherXG** [comment]
AR3 doesn't work with higher Kickstarts.
1.3 ist maximum. For other Kickstarts try HRMon.

**Comment by Toontje** [comment]
OK, thanks! Any HRMon manual out there?

**Comment by CypherXG** [comment]
Check here:
http://aminet.net/package/dev/debug/HRTmon
There is an Amiga Guide inside with all the commands...

**Comment by Toontje** [comment]
I see it. Nice! Thanks for the tip.
