### ISSUE TITLE
Amiberry - PC Compatibility AMD or Intel CPU

### ISSUE THREAD

**Issue by JonnyAlpha** [midwan/amiberry#617]
I have installed Linux Mint on an old PC. 
Motherboard ASUS M2N-VM/S
CPU is an AMD
4 x 1GB DDR2 SDRAM

I have installed RetroPie and am now trying to add some Amiga Games by installing Amiberry.
Is Amiberry compatible with AMD or Intel CPUs?

**Comment by joolswills** [comment]
Not sure why you are posting here as you are being helped on the RetroPie forum already and I have answered this. There is also a ticket open regarding this

https://github.com/midwan/amiberry/issues/594

**Comment by JonnyAlpha** [comment]
Ok thanks - I have only just started using the RetroPie Forums, however this was to see if there was any support for AMD and Intel CPU's. Please close this issues / request for advice. Tks

**Comment by CypherXG** [comment]
Amiberry is only for ARM Cpu's. For x86 or x64 better use Winuae
