### ISSUE TITLE
Question. How to 'Write-enable' DH0 when using .lha

### ISSUE THREAD

**Issue by JohnP-Ami** [midwan/amiberry#618]
Expected behavior

To Start a game using an LHA file through Retropie 4.4 and Amiberry 2.19.

Actual behavior

Game starts from the retropie menu and I can see the Amiberry logo.
Message comes up and says Volume DH0 is write protected.

Details

Hi

This is similar to a previously reported issue which has since been closed.
I am bootng a game (PGA Tour Golf) with an LHA file from the Retropie Menu. The game boots fine but upon requesting 'Player name' and attempting to save to disk it gives the message 'dh0 is write-protected'.

It may just be that I don't understand how the LHA file works and runs the game files and need to investigate further.

Is there a way to turn the write protection off?

Regards
J

**Comment by midwan** [comment]
@JohnP-Ami 
You are running a much older version of Amiberry I'm afraid.
The Amiberry logo showing during startup indicates that you're using the older WHDLoad booter also, which had some known issues.

Please upgrade to the latest version and see if you still have any issues, in which case we can look into it.
