### ISSUE TITLE
Savestate limit check

### ISSUE THREAD

**Issue by amyren1966** [midwan/amiberry#619]
I did just test creating a savestate on a game, kick1.3, ECS, 68000, 1MB chip, 1MB slow , running from 1 floppy drive.  This works fine.
Next I try with Workbench, kick 3.1,  AGA, 68020, 1MB chip, harddrive. 
That does not work. It also makes everything expect the mouse cursor freeze, so I have to pull the power to reset.

My question is then:
What are the current limits for savestates? Is it for only original A500 like setups?

Feature request:
1. Add the answer the above question to the Wiki.
2. If possible, add a system check to the Savestates save function, so that it will warn or the save button will be disabled in the current settings are outside the savestate limits.

I am using Amiberry 3.1.3 /Amibian 1.5ee/ Rpi4B

**Comment by midwan** [comment]
@amyren1966 
As mentioned in the Help message (from the Savestates Panel), Savestates will not work with HDDs, only with floppy images. ;)

**Comment by amyren1966** [comment]
Oh, I didnt notice the help message.

However, it still would be nice to have some check that avoid it crashing amiberry if save is clicked on accidently.
