### ISSUE TITLE
SDL2 | Very small mouse pointer in GUI at 1080p

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#62]

**Comment by midwan** [comment]
The mouse pointer used in the GUI is coming from the Linux system itself, so the size is also coming from there. However, we should be able to override it in SDL2 and use our own design and size also.

This might be fun and interesting if we used an "Amiga design" pointer actually, but I'll have to see how that is implemented (I haven't done it before). Then depending on the native resolution we could double the size for example, if it's above a certain threshold (let's say that 1080p will get a double-sized pointer, but maybe up to 720p you get the normal size?)

**Comment by windale** [comment]
Yes, the mouse pointer is larger at 720p. I'll probably keep 720p as the default as it might give a slight speed increase ? The Amiga mouse pointer does sound good though for the future.

**Comment by midwan** [comment]
Added custom mouse pointer - fb023d05461b4662ea951e51a300c5d5e6c259c8
