### ISSUE TITLE
Where do i store game specific uae files? (Settlers_v1.6_0143 update for whdload_db.xml)

### ISSUE THREAD

**Issue by Toontje** [midwan/amiberry#623]
I have read the documentation a godzillian times and i have tried many different things, but i cannot figure it out. Can you document where EXACTLY rom-specific uae files need to be stored? I know they need to have the same file name as the lha itself and that it needs to be stored in some whdboot directory. But is that the /opt/retropie/emulators/amiberry/whdboot directory? Because when i place the file there it doesn't have any effect. Or maybe a whdboot directory in the roms directory? Or does the uae file go into the roms directory itself? The game-data directory where the whdload_db.xml files is stored maybe? That sounds like the most logical place to put it.
For now i make the changes in the XML file which, obviously, get overwritten with the next update.
Please document in a clearer way.

BTW, the change i am making is that i am changing the SCREEN_HEIGHT for Settlers_v1.6_0143 to 280 instead of 200.

**Comment by midwan** [comment]
@Toontje 
The config files should be placed in the configured `config` path (check the Paths panel).
Normally going in the Configurations panel and saving it from there, should save it in the right directory.

**Comment by Toontje** [comment]
Ok, thanks!
