### ISSUE TITLE
Mouse becomes very erratic

### ISSUE THREAD

**Issue by quantum8** [midwan/amiberry#624]
I'm using 3.1.3 that's installed with Pimiga 1.2 release and it works great for the most part. 

But if I leave it on overnight, either idle, or copying files across, in the morning the cursor on the amiga side becomes unusable. The slightest touch sends the cursor all over the place.

I've tried the following steps to eliminate some basics:
- disconnecting the USB mouse and reconnecting it. Used the same port, as well as different ones.
- changing the mouse setting to "none", and then back to "mouse"
- resetting the amiga

The mouse works fine in the configuration interface at all times.

None of the items above made the mouse on the amiga side return to normal. I have to quit and restart amiberry completely.

**Comment by solskogen** [comment]
The same happens in WinUAE. I've seen it a couple it times.

**Comment by midwan** [comment]
Strange, that's the first time I've heard about such behavior.
I'll run a test and leave both WinUAE and Amiberry running overnight, to see if I can recreate this problem.

**Comment by midwan** [comment]
I haven't been able to recreate this so far, and I've tried:
- Leaving Amiberry running overnight with a Workbench 3.1.4.1 installation
- Leaving WinUAE running overnight with an AmigaOS3.9 installation
- Leaving WinUAE running overnight with AmiKit copying a huge number of files over the network.

All my emulator tests worked normally when I returned to them.

**Comment by quantum8** [comment]
Interesting. Must be something that the pimiga build uses and amikit does not that causes incompatibilities after a while.

**Comment by midwan** [comment]
I've seen this happen in WinUAE at least once now, so it looks like an upstream bug there.

**Comment by quantum8** [comment]
You're right @midwan , I just had this happen on my vanilla 3.1.4 installation (no RTG) on FS-UAE on my Mac.

**Comment by crale** [comment]
Hi, I ma also having a laggy/sluggish cursor too. One attempt was to try....in /boot/cmdline.txt add usbhid.mousepoll=0
This did not help at all.

I also have on another SD card an installation of Amibian. It, however, does not have this problem. I prefer the Pimiga for obvious reasons, but I though that I would add this information in case it might be of some help.

**Comment by midwan** [comment]
Looks like WinUAE _might_ have patched this, so I've merged those changes in Amiberry as well.
Please test with the latest (both `master` and `dev` branches include this fix now) and report back if you can recreate this?
Otherwise, we'll consider it "fixed" for now...
