### ISSUE TITLE
Files not showing up on an ExFat formatted USB drive

### ISSUE THREAD

**Issue by LaTeigne** [midwan/amiberry#626]
Hello !
It took me hours to understand why amiberry would work properly on my playstation classic using my autobleem USB drive and won't using my Project Eris one.

Actually no file can be displayed (par the linux system files and the directory structure) when the drive (with Project Eris) is formatted using ExFat. With exactly the same setup on the same NTFS USB drive, it would work.

This is worrying since it doesn't seem documented and considering that Project Eris won't work with a Fat32 drive (ExFat being the natural 2nd choice for many of us).

**To Reproduce**
Format a USB drive using ExFat, install Project Eris and add the amiberry mod.
Ad files (kickstarts and adf files) in the proper place, then boot your playstation classic, launch amiberry and browse for files (select files in the Quickstart or Floppy drive menu). All directories would appear empty even if they are not.

This might be a feature and not a bug, but in that case you'd want to make it clearer to user so they won't be disappointed using this great piece of software !

**Comment by midwan** [comment]
@LaTeigne 
I wasn't aware of Project Eris and what it does, until now. I'm not sure who ported Amiberry to that framework, but it wasn't me.

Amiberry uses standard filesystem calls from `dirent.h` to open files and directories. It's designed to work with Linux filesystems, and hasn't been tested on anything else. It sounds that this approach might not work as expected with ExFat?

Who ported Amiberry there? Perhaps you should try to get them onboard with this?

**Comment by midwan** [comment]
Closing this from our side, as I'm not sure what we can do at this point.
