### ISSUE TITLE
Request info about Cabinet controls

### ISSUE THREAD

**Issue by VITOAMOROSO82** [midwan/amiberry#627]
Hi, I open this request because although I have read the Wiki about the configuration of the controls, something is not clear to me yet. First of all I apologize for my English and if I didn't understand something.

I have assembled a cabinet where I use a Raspberry with Amiberry installed, everything works very well. In the cabinet of course I have two controllers ( Dragonrise USB stick), and I also installed two side buttons for Pinball games that I love very much. Since one of the Pinballs that I like most of all is Pinball Dreams, I'm trying to figure out how to make it work with the side keys of the Cabinet. The original game involves the use of the SHIFT key pair or the ALT pair to hit the ball. I read in the Wiki and see in the Amiberry GUI the possibility of customizing the keys, so my question is: is it possible to map the two SHIFT keys, for example on the two keys input_player1_btn8 and input_player1_btn9?

thanks a lot

**Comment by midwan** [comment]
@VITOAMOROSO82 
Amiberry will use the Retroarch mapping, that Retopie and other systems use. You should be able to customize your controls using that, and the relevant wiki page is here: https://github.com/midwan/amiberry/wiki/Setting-up-Keyboard-Controllers

You cannot currently do this from the GUI, that view is read-only to show you what you have mapped. This might change in the future, but for now you need to edit your mapping either manually (by editing the file) or with another front-end (like EmulationStation which RetroPie uses).

**Comment by VITOAMOROSO82** [comment]
> @VITOAMOROSO82
> Amiberry will use the Retroarch mapping, that Retopie and other systems use. You should be able to customize your controls using that, and the relevant wiki page is here: https://github.com/midwan/amiberry/wiki/Setting-up-Keyboard-Controllers
> 
> You cannot currently do this from the GUI, that view is read-only to show you what you have mapped. This might change in the future, but for now you need to edit your mapping either manually (by editing the file) or with another front-end (like EmulationStation which RetroPie uses).

Ok thanks, I would to do It by the file, but really don't understand how... Ok I create the retroarch.cfg, I put the code in this page, but If I add for example:

input_player1_b_btn = "0"

I know that on my controller, the PLAYER1 B Button is mapped like 0 on my Dragonrise USB Sticl device.

So, I don't have any input_player1_rshift_btn = XXX, so I'm lost in the logic on how to do this, I hope to be clear

**Comment by VITOAMOROSO82** [comment]
There's an interesting emulator (DOSBOX) in which you can configure keyboards keys and joystick keys in a simple way:

http://dosonthepi.blogspot.com/2015/01/configure-game-controllers-in-dosbox_29.html

Also you can configure multiple keys for a behavior...

I tried all the morning to setup my buttons for the Cabinet but no way to reach the goal :-(

**Comment by midwan** [comment]
@VITOAMOROSO82 
Thanks - we have an idea of how it should work already, it's a matter of taking the time it needs to implement it. Considering that most people have another front-end that they use to configure their retroarch controls anyway, this didn't seem that important.

**Comment by VITOAMOROSO82** [comment]
> @VITOAMOROSO82
> Thanks - we have an idea of how it should work already, it's a matter of taking the time it needs to implement it. Considering that most people have another front-end that they use to configure their retroarch controls anyway, this didn't seem that important.

Ok, so for the moment could you help me to understand how to fix my issue? I need to assign the SHIFT buttons to input_player1_a_btn and input_player1_b_btn for example...

Thank you very much

**Comment by VITOAMOROSO82** [comment]
Ok, I understand there's no way to let It work. Thank you
