### ISSUE TITLE
SDL2 | Resolution, Screen Scaling & Custom Controls don't save

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#63]
When trying to save these options it doesn't. Not that it matters with the controls yet, because as you already know the custom controls don't work especially CD32, or do they ? I'm using a wireless PS3 pad.

**Comment by HoraceAndTheSpider** [comment]
I pushed a fix for cd32 controls on PS3 pads but not any others.
You need to set joy1mode=cd32joy iirc

**Comment by windale** [comment]
In the GUI when it says 'Arrow keys as CD32' ?

**Comment by HoraceAndTheSpider** [comment]
no, i dont know about the GUI, the joy1mode=cd32joy can be set manually in the .uae file though.

**Comment by windale** [comment]
Oh, hopefully Midwan can implement this into the GUI so everyone will know about it as not all of us use your WHDLoader :)

**Comment by HoraceAndTheSpider** [comment]
hi,

nothing to do with the booter - this is a standard UAE command. However, the 'nubs as cd32' etc is legacy stuff from the Pandora version, so there is no other way to select the CD32 pad mode when a direct controller is chosen.

**Comment by midwan** [comment]
The GUI option mentioned refers to the built-in keyboard mapping for Joystick/CD32 controllers. In other words, that's what you can use if you don't have a real game controller connected (or detected).

If you have a controller connected, then you should select that instead. The "custom mapping" for a real controller is not worked on yet, that's coming soon. ;) For now, I've only worked on and tested the built-in keyboard mapping, and it works correctly with all the CD32 buttons.

As for saving those options, did you check the config file and they were missing, or did you just check the GUI? I suspect that it's a GUI thing but I didn't test it very thoroughly yet.

**Comment by windale** [comment]
@midwan 
I have PS3 pad selected in Port 1, as you said, that's why I can't use CD32 yet because custom mapping is not working yet.

The other options I mentioned are in the config file
gfx_correct_aspect=0
scaling_method=0
But they don't seem to save what I chose.

@HoraceAndTheSpider 
It no longer says 'nubs as cd32' in the SDL2 version, you must be using an old version.

**Comment by midwan** [comment]
@windale 
Thanks for the clarification.
"gfx_correct_aspect" is no longer needed, as we use the correct aspect automatically always. Well, @HoraceAndTheSpider has a request to allow stretching, but again that won't need this option to work.

"scaling_method" on the other hand  IS needed and should be saved in the config. The default value is "-1" if nothing is specified and it's the "Auto" option. Older configs that don't have it, will default to that. Changes however to a loaded config SHOULD be saved, so if that's what you noticed we have to get it fixed.
For the record, the options are:
-1: Auto
0: Nearest neighbor
1: Linear

That leaves room for more in the future (like 2:Stretch for example).

**Comment by windale** [comment]
I noticed that there are now two entries for 'scaling method' in the config. Maybe it is working but the GUI is not showing it because of the two entries in the config ?

**Comment by midwan** [comment]
@windale 
Thanks, I'll have to check and see. A good test suite would be:
1) Try with a brand new config, save it from scratch. Check the results
2) Load an older config which didn't have the option. Save it and check the results.
3) Try with a "newer" config that had the option saved already. Change/save and check the results.

**Comment by HoraceAndTheSpider** [comment]
"It no longer says 'nubs as cd32' in the SDL2 version, you must be using an old version."

**Comment by midwan** [comment]
@HoraceAndTheSpider 
"nubs as cd32" has been renamed to reflect what it is a bit more accurately. :)
It refers to keyboard mapping, and specifically using the layout with the arrow keys, so I named it accordingly. If a better name idea comes up, we can rename it again. :)

**Comment by HoraceAndTheSpider** [comment]
@midwan 
sure, i think the point is being missed though. I was only using that as an example.

The CD32 pad mapping on PS3 pads though, the fix i submitted, is still in the SDL2 version, yes?

**Comment by midwan** [comment]
@HoraceAndTheSpider 
Yes, except the "Blue" button mapping which caused problems with the keyboard mapping - we'll have to check if that works correctly now or not.

**Comment by windale** [comment]
@midwan 
I created a brand new config with default settings, it seems that there are lots of duplicates at the start of the config

amiberry.custom_play=0
amiberry.custom_r=0
amiberry.custom_l=0
amiberry.custom_y=0
amiberry.custom_x=0
amiberry.custom_b=0
amiberry.custom_a=0
amiberry.custom_right=0
amiberry.custom_left=0
amiberry.custom_down=0
amiberry.custom_up=0
amiberry.custom_controls=0
button_for_quit=-1
button_for_menu=-1
key_for_quit=0
key_for_menu=1073741893
scaling_method=0

There may be other duplicates. I then changed the custom controls and scaling method and saved to the same config. Now it has 3 entries for each, 2 are unchanged.

**Comment by midwan** [comment]
@windale 
OK, thanks, if there are duplicates then there's something going on there. I'll take a look and fix it.

**Comment by windale** [comment]
Also, on PS3 pad mapping

      Triangle
Square   Circle
        Cross

The Circle button used to be the main fire button, now it's X/Cross. Is this by design ?

**Comment by HoraceAndTheSpider** [comment]
@windale - that would be correct. It was incorrectly hard-coded previously.Red button is the main fire button, which is positioned in the X position.

**Comment by HoraceAndTheSpider** [comment]
@windale - that would be correct. It was incorrectly hard-coded previously. 

Red button is the main fire button, which is positioned in the X position. 

![pads1](https://cloud.githubusercontent.com/assets/567602/23588457/a975b414-01b5-11e7-9e81-d80fa84d40f2.jpg)

**Comment by windale** [comment]
OK thanks, it just feels a bit strange now because I was used to Circle being the main fire button and all other emulators in Retropie (including the menu) use Circle as button 1. I'll get used to it.

**Comment by windale** [comment]
I know you haven't touched on this yet but I noticed on github that you changed all references of 'Pandora' to 'Amiberry' but when creating a new config file there are still entries for 'pandora' listed.

**Comment by midwan** [comment]
@windale 
All pandora references are cleared now, but if you still have them in your config they will not be deleted. Try creating a new config to test.

There's still something causing duplicate entries for the custom controls settings, I'm working on that.

**Comment by midwan** [comment]
This should now be fixed, let me know if you have any further issues with it
