### ISSUE TITLE
Skidmarks game doesn't work (needs serial port emulation)

### ISSUE THREAD

**Issue by BartP223** [midwan/amiberry#631]
After pressing the "Skidmarks" button the game does not start. The problem concerns the WHDLoad and .adf versions

**Comment by midwan** [comment]
Which version of Amiberry?
Which distro?
How are you launching the game? Using a front-end, from the command-line, or from the GUI?

**Comment by BartP223** [comment]
Amiberry v3.1.3 in RetroPie 4.6
Skidmarks v1.06 (adf) I run the GUI (manually mount the disk to df0)
WDLoad wersion (skidmarks_v1.0_AGA_0204.lha) run from the RetroPie game list.
There is always the same effect. The program runs until you need to press the "Skidmarks" button.
Nothing happens when the button is pressed. I checked on different settings (68000, 60020, 7MHz, 14Mhz, AGA, ECS, KS1.3, KS3.0 etc.)

**Comment by nemo93** [comment]
Perhaps this would help. => http://eab.abime.net/showthread.php?t=16412

I'll try also on my end.

**Comment by BartP223** [comment]
How to enable serial port in amiberry?

**Comment by midwan** [comment]
I'm afraid there's no serial port emulation in Amiberry, yet.
I'll test Skidmarks to see if I can recreate this, does it also happen with other versions of the game (e.g. Super Skidmarks) ?

**Comment by BartP223** [comment]
Super Skidmarks works fine

**Comment by midwan** [comment]
Confirmed, but if it's looking for a serial port, there's nothing we can do about it until we get serial port emulation in Amiberry. :)

**Comment by BartP223** [comment]
Thank you very much for your answer. If this option ever occurs, I will use it. Regards, Lukas.

**Comment by nemo93** [comment]
If that helps I just cracked a ticket on [whdload bugtracker](http://mantis.whdload.de/view.php?id=4619) as well.

**Comment by midwan** [comment]
Closing this and we'll track the serial support implementation with #682
