### ISSUE TITLE
Command line parameters to launch CD32 game

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#632]
More a question than a bug :
Is there any way to launch CD32 game through command line without using an uae conf file ?
I its not mentioned in the wiki

**Comment by nemo93** [comment]
hi @Voljega ! You have to rely on the `-autoload=` parameter of Amiberry for that. Just ensure to rename your `.cue` file to the CD32 name found inside the `whdload_db.xml`.

E.g. let's assume I want to run Chaos Engine CD32. I put all cue/bin files inside my "roms" folder. I then double-check inside the .cue to be sure it points to the corresponding .bin file(s). I take a peek inside the the `whdload_db.xml` to see what name I should chose and this one looks a fine candidate => `ChaosEngine_v2.1_CD32`. I simply rename the `.cue` with that name and run Amiberry with:
```
$ amiberry -autoload=ChaosEngine_v2.1_CD32.cue -G
```

**Comment by nemo93** [comment]
hi @Voljega !! Amiberry does rely (for now) on this DB to set things up whenever there's no uae provided. I think it's really useful and save the users the hassle of configuring things. I understand the process looks to be tedious but it's just a one-off. And you still have the ability to pass a .uae instead.

I'm actually updating the db ([here](https://github.com/nemo93/Amiberry-XML-Builder)). I'm ok to have a look and to add the 2 games you mentioned. Apparently there's already an entry for Kang Fu => KangFuAGA-WHDL (this game is really a mess to put it midly :)). Can you try to rename and this how it goes please?

**Comment by Voljega** [comment]
It's more than I fond it a bit 'dirty' to have to rename a game to make it work correctly ...

Anyway it seems why whdl xml is not uptodate as Kang Fu doesn't appear in mine
It also seems it wouldn't be enough to have some game work correctly, for instance the configuration for flashback in the wml db doesn't use a joy32 controller, so the cd32 version couldn't be used with joy32 that way ?

To explain what I want I would just like to be able to launch a cd32 game through command line, something like :
`/usr/bin/amiberry -G -model=CD32 -cd /userdata/roms/amigacd32/Flashback.iso`
maybe ?

**Comment by midwan** [comment]
@Voljega 
If you're using WHDLoad sets, then the easiest way is to use the WHDBooter function, with the `-autoload=<path to game file>` option.

The alternative, is to use a quickstart option to set the CD32 model as you suggested, with `-model=CD32` and feed it your file. It will use the default settings of the Quickstart for that model, and load your title.

**Comment by Voljega** [comment]
@midwan ok but for the alternative `/usr/bin/amiberry -G -model=CD32 -cd /userdata/roms/amigacd32/Flashback.iso` I used non-existent option `-cd` and I can't find anything in `amiberry -h` to replace it what should I use ?

**Comment by midwan** [comment]
@Voljega I believe the option you're looking for is `-cdimage=` 
Looks like it would be a good idea to add the command-line options in the Wiki :)

**Comment by Voljega** [comment]
yes ;) at least for launching cd32 

also it's missing here :
`Amiberry v3.1.2 (2020-02-18)
Usage:
 -h                         Show this help.
 --help                     Show this help.
 -f <file>                  Load a configuration file.
 -config=<file>             Load a configuration file.
 -model=<Amiga Model>       Amiga model to emulate, from the QuickStart options.
                            Available options are: A500, A500P, A1200, A4000.
 -autoload=<file>           Load a WHDLoad game or .CUE CD32 image.
 -statefile=<file>          Load a save state file.
 -s <config param>=<value>  Set the configuration parameter with value.
                            Edit a configuration file in order to know valid parameters and settings.

Additional options:
 -0 <filename>              Set adf for drive 0.
 -1 <filename>              Set adf for drive 1.
 -2 <filename>              Set adf for drive 2.
 -3 <filename>              Set adf for drive 3.
 -r <filename>              Set kickstart rom file.
 -G                         Start directly into emulation.
 -c <value>                 Size of chip memory (in number of 512 KBytes chunks).
 -F <value>                 Size of fast memory (in number of 1024 KBytes chunks).
`

and it seems Batocera is using amiberry 3.1.3 so maybe version number hasn't been updating in help ?

**Comment by midwan** [comment]
The version string comes from one place, so if it shows 3.1.2 there, it's probably v3.1.2 and not 3.1.3 :)
But I'm pushing a small update now, to include the extra options in the help there, which will bring it up to 3.1.3.1.
