### ISSUE TITLE
SDL2 | No border sprites

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#64]
UAE4Arm used to be able to display border sprites, example is the game Banshee. The left third of the screen should be an information panel with number of lives, score etc. It's completely missing on AmiBerry SDL2.

**Comment by midwan** [comment]
@windale 
Thanks for the continuous feedback, it's very helpful to make the emulator better! :)

I'm working on a fix regarding this, but run into some problems with it. Once I've fixed it, I'll push out an update.

**Comment by windale** [comment]
No problem, if I find anything i'll always let you know as I like your improvements. A lot of these things i'm finding are quite blatant so I must be the only person that's installed the SDL2 version, either that or no-one else can be bothered and just waiting for the end result ! :)

**Comment by midwan** [comment]
Confirmed in SDL2 version, does not occur in SDL1 version.

**Comment by blinkydoos** [comment]
I checked this and it has nothing to do with the resolution. It seems some code was removed that enabled this, not sure why ?

AMIBERRY
![banshee amiberry](https://cloud.githubusercontent.com/assets/27903587/26446879/e20e7eba-413d-11e7-8a3d-5f5403c73625.png)

UAE4ARM
![banshee uae4arm](https://cloud.githubusercontent.com/assets/27903587/26446890/f07ef6b4-413d-11e7-84e2-7673b0c74458.png)

NOTE : The screenshots were captured on Android UAE4Arm. I don't have a camera (that works properly) so I simulated what I see in Amiberry using Android UAE4Arm.

**Comment by ransom1122** [comment]
My whdload version of banshee AGA on amiberry shows the panel. But the blue background moves left to right when moving the plane and you can see corrupt graphics behind the panel where it is supposed to be black
[Img]https://i.imgur.com/O8UXt4T.jpg[/img]

**Comment by blinkydoos** [comment]
Yeah, the panel is only missing on SDL2. The issue with seeing the graphics behind the panel also happens on TomB's original UAE4Arm, so no fault of Amiberry.

**Comment by midwan** [comment]
This is fixed in the current "dev" branch
