### ISSUE TITLE
Implement AHI driver support  

### ISSUE THREAD

**Issue by AmiManga** [midwan/amiberry#643]
I am trying to use UAE driver for AHI in OS 3.9 so I can play AmiAMP in 44KHz - using Amibian 1.5 with PI4 - Latest Amiberry from git. 

Is this supported? Am I using the wrong driver? 
Can I use workbench AmiAMP in 44KHz using Amiberry. 
This works in WinUAE for me.

Any suggestion is highly appreciated.
Cheers

Ranko

**Comment by midwan** [comment]
@AmiManga 
AHI support is not yet implemented in Amiberry, sorry.

**Comment by AmiManga** [comment]
Hi Midwan.

Thank you for your reply.
Amiberry is awesome but AHI support may expand usability of emulated Amigas.
Aside from games, many people use emulated Amigas as MP3 or internet radio players. 
I hope this will feature will end up on the list eventually! 
I will take a look and maybe contribute with AHI support is my time permits. 

Aside from that Amiberry rocks! 
Awesome work. 

Regards

Ranko
EmbeddedSoft

**Comment by midwan** [comment]
@AmiManga 
I agree, it would be great to add it in the feature list.
It's just a matter of time and effort, so if you can help, that would be awesome!

**Comment by midwan** [comment]
A first working version is now implemented in the `dev` branch, meaning at least we get some sound output from it.
It's not perfect yet, and it seemed to have some glitches during playback in my tests. But it's a start :)

**Comment by midwan** [comment]
Closing this as this is implemented, will continue working on improvements anyway.
