### ISSUE TITLE
Atoms.lha does not load

### ISSUE THREAD

**Issue by penx** [midwan/amiberry#644]
**Describe the bug**
Atoms.lha does not load

**To Reproduce**

1. Download Atoms.lha from http://aminet.net/package/game/2play/atoms

2. Click on put in roms/amiga folder on Retro Pie

3. Launch Atoms via Retro Pie

4. Black screen, `dev/shm/runcommand.log` contains

```
Parameters:
Executing: /opt/retropie/emulators/amiberry/amiberry/sh auto "/home/pi/RetroPie/roms/amiga/atoms.lha"
Could not load system ROM, trying system ROM replacement.
~
```

**Expected behavior**
game should load

**Comment by midwan** [comment]
@penx 
The game is not a WHDLoad one, is it? You can run all .lha archives with the WHDLoad booter feature, the game/demo needs to be a valid WHDLoad installed one, including a `.slave` file.

Alternatively, you can run self-bootable games (e.g. ADFs) by using disk images.

In this case, it seems like the game needs a Workbench environment to run it into, so you could set that up using a Virtual HDD, install Workbench and then extract and run the game from there.
