### ISSUE TITLE
Add ability  for Zoom or Fullscreen Scaling option

### ISSUE THREAD

**Issue by bigly2001** [midwan/amiberry#645]
Hi

Would you like please add any option for 
1- Zooming or Full screen scaling like Winuae.
2- Virtual keyboard like Puae or at least ability to define  hotkey for left and right mouse click.

thx

**Comment by midwan** [comment]
Hi @bigly2001 
Regarding your requests:
1 - Amiberry will always scale to full screen when:
a) You're using the DispmanX version (it's full-screen always) or
b) You're using any other SDL2 version, and you select to go Full Screen from the Display panel.

Additionally, with the new Auto-Height option (currently in the 3.2 beta, release coming soon), you can maximize the emulated screen area by eliminating the black borders from the top/bottom. This works best with Vertical Centering enabled, also.

2 - This is already covered in a separate issue: https://github.com/midwan/amiberry/issues/224
