### ISSUE TITLE
Problem with the new "Auto High" function.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#649]
Raspberry Pi 4 with RetroPie 4.6.1 and Amiberry 3.2 beta. I start my WHD-Load Games from AmigaOS 3.1.4.1. 

The new setting "Auto High" in the display tab is a very good idea. At the moment, however, it still means that the image is not shown centered, but is shifted downwards so that part of the lower image is cut off.

Cheers
Sid1968

P.S .: Thank you for your excellent work for the Amiga scene.

**Comment by midwan** [comment]
@Retro1968 
Please report which version you've tested this with.
This feature is still W.I.P. and it might change every day, so the specific date stamp of the beta you're testing with is important here. :)

**Comment by Retro1968** [comment]
The version from yesterday that i compiled today. (26.05.2020)

**Comment by midwan** [comment]
@Retro1968 did you have Vertical Centering enabled in the Display panel?
Without that, the image is not re-centered and it might just show as being cut-off at the bottom.

**Comment by Retro1968** [comment]
No. Activating horizontal and vertical centering and the problem is solved the problem. Thank you, looks great!!!

I tested two games. While Test Drive II runs fine, the game 4D Sports Driving has some flickering in the intro.

**Comment by midwan** [comment]
Flickering that is not there when you disable Auto Height you mean?
It's certainly possible that some games will not work perfectly well with this, since they might be doing tricks (like changing resolution every frame). In these cases the recommended approach would be to not use this setting, and have a fixed value in Height instead.
