### ISSUE TITLE
SDL2 | OCS & ECS Screen Bug

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#65]
@midwan If the chipset is OCS or ECS then the mouse pointer is stretched and you can't move to the left side of the screen, like an invisible wall. Works fine on AGA.

This means that OCS and ECS modes are unusable if you're using the mouse. Also effects graphics. I think this should be a priority.

**Comment by midwan** [comment]
Note to self: Need to test this after the new changes in drawing.cpp, in SDL2

**Comment by midwan** [comment]
Confirmed in current SDL2 version

**Comment by midwan** [comment]
Note to self: does not occur in SDL1 version

**Comment by midwan** [comment]
@windale 
This should be fixed now, please test when you get a chance and let me know if it's still an issue for you?

Thanks for bringing it up.

**Comment by windale** [comment]
Yep, seems to work fine now.
