### ISSUE TITLE
KMSDRM black screen when using Auto Height

### ISSUE THREAD

**Issue by Lex15** [midwan/amiberry#650]
When using the SDL2(no DispmanX) version outside of Rasban desktop. The screen remains black when auto height changes screen size. If F12 is used to open GUI after each screen size change the screen is displayed correctly again.

**Comment by midwan** [comment]
@Lex15 
Which environment are you testing with, when you say "outside of Raspbian Desktop" please?

**Comment by Lex15** [comment]
I'm testing on the lite version of Raspbian(no GUI) from the command line.

**Comment by midwan** [comment]
The I guess you have compiled SDL2 from sources, could you provide more details on that please? Which flags did you use whenc compiling it, which version did you use?

**Comment by Lex15** [comment]
I compiled them as describe on your wiki page. I've tried running on Retropie 4.6 aswell which has pre compiled SDL2. With the same results.

**Comment by midwan** [comment]
RetroPie uses the Dispmanx version however - are you saying that you have problems with that version as well? Or did you compile the non-Dispmanx version in RetroPie and tested with that?

**Comment by Lex15** [comment]
No sorry I compile the non-Dispmanx version on Retropie.

**Comment by midwan** [comment]
This should be fixed now, but please let me know if that's not the case?

**Comment by Lex15** [comment]
Sorry still not fixed.

**Comment by midwan** [comment]
@Lex15 
Do you have a specific scenario to recreate this please?
When testing this with normal Desktop versions, it seems to work fine. Is it some specific titles you're testing that have this problem, or all of them (which means it only happens under KMSDRM from the console, not the desktop)?
