### ISSUE TITLE
Support for Nanopc T3

### ISSUE THREAD

**Issue by BenMtl** [midwan/amiberry#651]
It would be nice to see support for the Nanppc T3 and others by friendlyarm. I think these boards would be great with amiberry running on them.

**Comment by midwan** [comment]
@BenMtl 
I don't have such a board to test with, but from what I read in the specs it's using a cortex-a53 CPU and has Debian and Ubuntu running on it.
So the big question is: does SDL2 have support for the board's GPU?

If that works, then it should be rather easy to modify a similar entry in the Makefile (one that uses the same CPU) and try compiling that.

**Comment by midwan** [comment]
Can't do much more for this from my side...
If you modify the Makefile and it works for you, feel free to send a Pull Request with the changes and I'll happily integrate them.
