### ISSUE TITLE
Additional Save States

### ISSUE THREAD

**Issue by vretro** [midwan/amiberry#652]
Save states are a very welcome feature of Amiberry enabling the ability to “pause” and “resume” content at your convenience, especially over prolonged periods of time, with a handy screenshot serving as a reminder of the save state.

Amiberry is currently limited to 5 save state slots in total per loaded content.

I would like to see the quantity of save state slots available increased.

My reasoning? Saving state makes exploring and revisiting games, programs and demos more enjoyable.

As an example, not only is it useful for saving your progress, but I like to revisit particular stages/levels again in old favourites.

Having a screenshot per save state is a feature which should be retained in any adjustment to the save state functionality. It is very helpful.

Thank you

**Comment by midwan** [comment]
There are currently 4 slots available (not 5) :)
Would increasing them to 10 be enough?

**Comment by vretro** [comment]
Brilliant @midwan 10 will be a world of difference, thank you.

I didn't recall the Savestates were numbered 0-3, at the time of writing the feature request :)

**Comment by midwan** [comment]
@vretro 
This is already implemented with the commit above, so you can get it immediately if you grab the latest sources.
And it will be included in the next stable release as well, of course.
