### ISSUE TITLE
Universal config for all games?

### ISSUE THREAD

**Issue by chrisinodentino** [midwan/amiberry#653]
Hi,

I want to run all ROMs/games full screen but can't figure out how to do it. 

I can load a game and save a config for each game.

This isn't really practical. How do I create 1 config for all games to run full screen?

**Comment by midwan** [comment]
Hi @chrisinodentino 
Take a look at the options in `amiberry.conf`: [related wiki here](https://github.com/midwan/amiberry/wiki/Amiberry.conf-options).

I just added an option to control the default behavior of starting in Fullscreen or not. ;)
