### ISSUE TITLE
Centering Display

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#655]
Auto Centering works great, but sometimes it´s not working properly.
So, put manual settings back, please. (with Auto centering switch of course).

Thanks a lot, I appreciate your work.)

**Comment by midwan** [comment]
@Tomato1981 
I don't think it makes sense to bring back manual centering.
It's better if we investigate which cases had a problem with this and try to fix that, instead.

Please provide more details on which test scenarios you've tested, which platform you're using, which distro, etc.

**Comment by midwan** [comment]
Closing this, as it doen't include any meaningful information to do anything further.
Please come back with specific details (as I mentioned above), so we can look into it.

**Comment by Tomato1981** [comment]
I tested some games. mainly is problem with games/programs with no black background.
(Agony etc.)
In Gold of Aztecs is impossible to reach right settings.
In older versions of Amiberry was horizontal alignment OK without interruption,
in latest version 3.1.3 is wrong centering when it´s switch ON, even OFF.
![Centering01](https://user-images.githubusercontent.com/48894236/84592060-0483a680-ae43-11ea-8de9-889e15cc9689.jpg)
![Centering02](https://user-images.githubusercontent.com/48894236/84592061-05b4d380-ae43-11ea-8e50-dfdd69530f75.jpg)
![Centering03](https://user-images.githubusercontent.com/48894236/84592062-064d6a00-ae43-11ea-9d79-cfa57d42247e.jpg)

(I am using Amiberry 3.1.3 on Raspberry Pi 3b with Emulation station 2.8.3RP)
(I tested 700 games last year, so I can start again:))

**Comment by midwan** [comment]
In most cases we've tested, auto-centering works perfectly well. In some cases, it might need a little tweaking of the width/height values. It also works great in many cases (though not all), combined with the new Auto-Height feature, in the v3.2 beta. The Auto-Height feature is a little experimental, so it will definitely not work perfectly in all cases. But in those that it does, it will set the correct Height value for you dynamically (and change it in real-time, as requested).

For Agony: There's no 100% perfect solution to this. You can either disable the auto centering, and set adequate width/height values, then that specific intro screen shows correctly but in-game, you'll have a somewhat shifted image, or live with Auto-Centering (perhaps in combination with Auto-Height, in the new v3.2 version) and have the intro screen show like that, but have the rest of the game perfectly aligned.

For Gold Of the Aztecs: Just set the Width to 720, and you'll see that Horizontal Centering works perfectly well. The 640 default width set for this game in the XML is obviously not enough, and some pixels get cut-off. Better report this change to @HoraceAndTheSpider so we can adapt the XML accordingly!

**Comment by Tomato1981** [comment]
Thanks a lot for very quick response. I will play with that:)
