### ISSUE TITLE
Amiberry won't start if controller.cfg file has empty lines

### ISSUE THREAD

**Issue by tednilsen** [midwan/amiberry#656]
Using RPi3 on RetroPie / Debian.

**Describe the bug**
trying to start amiberry, both sdl2 and dmx version outputs this to console:
`terminate called after throwing an instance of 'std::out_of_range'`
`  what():  basic_string::substr: __pos (which is 2) > this->size() (which is 0)`
`Aborted`

**To Reproduce**
All apt-get packages updated.
I tried using the RetroPie script and also my own git clone, submodule and make (both sdl2 and dmx)...
The prebuilt amiberry binary on RetropPie works, when I build amiberry from source about 2 weeks ago it worked.

**Amiga RuleZzzZZzz :)**

**Comment by midwan** [comment]
@tednilsen 
Which version of RetroPie are you running, please?

**Comment by tednilsen** [comment]
RetroPie v4.6.1 (latest)

**Comment by midwan** [comment]
@tednilsen 
Sorry, I can't recreate that problem here.
Testing with the current RetroPie and compiling from source on an RPI3, works normally.

**Comment by tednilsen** [comment]
found the bug:
the retroarch controller config file under the "controllers/Generic X-Box pad.cfg" folder had empty lines that made new changes to amiberry crash... this was my file:
***
`input_driver = "udev"`
`input_device = "Generic X-Box pad"`
`input_vendor_id = "121"`
`input_product_id = "6268"`

`input_select_btn = "8"`
`input_start_btn = "7"`

`input_a_btn = "1"`
`input_b_btn = "0"`
***

the lines had to be changed to (I removed the empty lines):
***
`input_driver = "udev"`
`input_device = "Generic X-Box pad"`
`input_vendor_id = "121"`
`input_product_id = "6268"`
`input_select_btn = "8"`
`input_start_btn = "7"`
`input_a_btn = "1"`
`input_b_btn = "0"`
***

...guess the bugger bugged after all, cheers ;)

**Comment by midwan** [comment]
Oh, that's interesting! Then we definitely need to impove the parsing logic there, it shouldn't crash in such cases.

Thanks for bringing this up, and the extra details. I'll get it fixed.
