### ISSUE TITLE
Implement full CDTV support

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#658]
Look into implementing full CDTV support in upcoming versions.

**Comment by GeorgeSpiggott** [comment]
Great news. I assume this is still very much WIP on version 3.2 beta.

I tested a game (.iso version of Xenon II) and I think it is picking up on the _CDTV tag in the filename but it brings up what I think is a ROM error (dark grey boot screen). Will follow this with interest.

If it helps my Kickstart ROMS have the following CRCs.

Kickstart 1.3 v34.5 (A500, CDTV etc.) - c4f0f55f
CDTV Extended 2.7 - ceae68d2

PS. It definitely isn't an issue with the game image as it boots fine with the .cue file renamed to _CD32.

**Comment by midwan** [comment]
@GeorgeSpiggott 
Yes, this is still WIP. There is a problem with the way Amiberry does the memory allocations currently, which for some reason makes the CDTV extended rom not work. If I change the memory allocation routines, then JIT breaks instead. :)
I haven't figured out a solution to this yet, but I'm working on it.
