### ISSUE TITLE
Repeating Sound on Short Samples

### ISSUE THREAD

**Issue by ghost** [midwan/amiberry#66]
Sometimes when short samples are played it sounds like it's played twice in quick succession. Good example is the game 'Jimmy Whites Whirlwind Snooker' when clicking the menu items and in-game when hitting a ball.

**Comment by blinkydoos** [comment]
Hi @midwan . Is there anything that can be done about this ? I've noticed it happen on several games & utilities etc. As stated above, Jimmy Whites Snooker can easily hear the sound hiccup. I think it started happening when you fixed the sound from Chips build.

**Comment by midwan** [comment]
@windale We've already rewritten the sound handler in the current dev branch, and we'll be releasing a version publicly soon (we hope), after merging in some extensive improvements currently being worked upon.
There may be more bugs to fix in the future of course, but progress is being made.

**Comment by blinkydoos** [comment]
> We've already rewritten the sound handler in the current dev branch

I am using Horace's latest controller build which I assume contains the latest sdl1 commits but it still has this audio issue that windale reported. Has the rewritten sound handler been committed yet ?

**Comment by midwan** [comment]
I noticed the problem, it seems to happen if you use the mouse to navigate the menu and click, but not when doing so with the keyboard? As if the mouse click registers as "multiple" clicks...
Could you confirm if this is what you see as well?

**Comment by blinkydoos** [comment]
I've also noticed it on various games when using the joypad fire button (and sometimes when no buttons are pressed). I'm out at the moment, I'll see if I can find a few test cases in a few hours.

**Comment by blinkydoos** [comment]
No time to test at the moment but something else I remember that exhibits the audio hiccup is Michael Gibbs WHDLoad Frontend.

http://aminet.net/package/util/misc/TinyLauncher

It can be used with a joypad and can hear the audio quickly repeat when selecting menus, so it doesn't just happen with the mouse.

It can also be heard on most games and cracktros when the music starts playing.

**Comment by ZappaUtopia** [comment]
Is there anything that can be done about this ? Now that i've noticed it, it's really quite annoying :-) Has nobody else noticed this ?

**Comment by midwan** [comment]
This seems to be fixed in the current beta.
