### ISSUE TITLE
How to install "host-run"

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#660]
RetroPie 4.6.2 on Raspberry Pi4 wit amiberry 3.2 beta (28.06.2020).

Hello Midwan,
with your last release you gave us a link to the program "host-run".  Since i have no idea how to install / run it i ask you for instructions. A 120 minutes dolby surround full HD movie should be enough. ;-)

**Comment by Retro1968** [comment]
Ok, Thank you. But how do i install host-run on Raspbian Buster?

**Comment by midwan** [comment]
You don't install it in Raspbian at all. It's an Amiga program, that you can just copy into your C: (or any other location).
The binary is available at the link I mentioned above ;)

**Comment by Retro1968** [comment]
Oh .. yes, of course ... I knew that immediately. I only asked for those who are too stupid to come up with it themselves ... ;-)
