### ISSUE TITLE
Is there any way that mouse/joystick could switch based on button press? 

### ISSUE THREAD

**Issue by BrianGilbert** [midwan/amiberry#661]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to jump to settings to switch between mouse and kyboard input between 2 player games and workbench

**Describe the solution you'd like**
On my real A1200 I have a hardware device that switches input between mouse and joystick when I press a button on the given device, eg:

-Click left mouse button input switches to mouse
-Click joystick button input switches to Joystick

Would this be possible to implement in amiberry so that we don't need to jump to settings to be able to enable a secondary joystick when in a game, then again to re-enable mouse after I finish playing?

**Comment by BrianGilbert** [comment]
Seems like it's in winuae already http://eab.abime.net/showpost.php?p=1411284&postcount=166

**Comment by midwan** [comment]
@BrianGilbert 
The setting is already in Amiberry, and enabled by default... but it doesn't currently do what it's supposed to, due to the way the mouse handling is implemented.
I'll look into improving this in an upcoming update however.

**Comment by BrianGilbert** [comment]
@midwan do you have any idea when you might get to looking at this? Hoping to allow my young boys to play multi player games :)
