### ISSUE TITLE
Physical devices (HDD/CDROM) support

### ISSUE THREAD

**Issue by DesertBlizzard** [midwan/amiberry#663]
**Is your feature request related to a problem? Please describe.**
Not really.  Would be enjoyable to be able to fit a cdrom into my slot loading optical drive and feed Amiberry a disk with music or CD32 Game disk.
![20200709_212417047_iOS](https://user-images.githubusercontent.com/45675403/87092388-2bd65500-c1f0-11ea-9137-34f8f31a9451.jpg)

**Describe the solution you'd like**
Add support for USB attached optical drives.

**Describe alternatives you've considered**
Folder based HD mapping to a mountpoint in Linux might get me part way there, minus CDDA support.

Love Amiberry? Please consider supporting our collective:
👉  DONE

**Comment by ant-gent** [comment]
I use the following workaround with my IDE to USB adapter:

Create a symlink with a .hdf extension pointing to the real device like so:
`# ln -s /dev/sda sda.hdf
`

Then with sda.hdf selected as a Hardfile in the amiberry UI, the emulator boots off the real hard disk.

**Comment by midwan** [comment]
Floppy drive support has been added in the `dev` branch, and it's currently under testing with the upcoming v4.2 beta.
It's using Rob Smith's Arduino "DrawBridge" solution: https://amiga.robsmithdev.co.uk/

**Comment by midwan** [comment]
Floppy drive support is now part of the 4.1.5 release! :)

**Comment by midwan** [comment]
The workaround @ant-gent mentioned above is no longer needed, as you can now type the path manually and it will work (e.g. /dev/sda). Keep in mind that you still need access to that path under Linux - you may need to change ownership or at least add read/write permissions to it, first.

**Comment by midwan** [comment]
You can now use Amiga HDDs directly, by typing the device name.
But I couldn't make it work for CD-ROMs, at least not yet. Perhaps in the future or if someone else can send a related Pull Request, we can revisit that. But for now, I think this is "good enough" :)
