### ISSUE TITLE
Problems with facts. Amiberry Restart dont work.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#664]
Raspberry Pi 4 with RetroPie 4.6.2 and Amiberry 3.2 beta (07/12/.2020). Workbench 3.1.4.1 with Kickrom 3.1.4.

I autostart the program facts.
http://aminet.net/package/comm/tcp/facts

This program synchronizes the time with a time server (I use: ptbtime1.ptb.de) from the Internet. Since the Amiberry version from 07/12/2020, the program no longer reaches the time server and hangs, although I do get ibrowse on the Internet.

If I now want to restart with the F12 key, Amiberry hangs in the loading screen. The same applies if I want to exit Amiberry with F11.

**Comment by Retro1968** [comment]
Oh ... I was able to fix the error. There is obviously maintenance work on the server ptbtime1.ptb.de, so that it is currently not available. If I use the alternative server ptbtime2.ptb.de everything works again. :-)

**Comment by midwan** [comment]
Thanks!
I had been using Facts myself from years ago, but it's not the most stable app for the purpose. I found `sntp` combined with `setDST` to be much more reliable.
