### ISSUE TITLE
Keyboard led select in miscellaneous does not match

### ISSUE THREAD

**Issue by FlopGithub** [midwan/amiberry#666]
Hi,

I try to use NumLock and ScrollLock to act as Amiga Leds and choice in dropdown menu does not correspond to reality or does not work at all.
I want ScrollLock as df* and NumLock as HD.
df* does not work at all.
With DF3 in Numlock and POWER in ScrollLock, NumLock is acting as HD and ScrollLock as DF0 !

SetLeds utility works perfectly in raspbian command line.

Raspberry PI 2 Model b V1.1
Raspbian Buster
I've tried with amiberry from github source, precompiled version 3.1.3.1 and 3.2-beta1
Keyboard used is original A600 Keyboard with a home made "adaptator" to usb ( like a keyrah ).
Led patch applied in Raspbian rules : ACTION=="add", SUBSYSTEM=="leds", ENV{DEVPATH}=="*/input/*::scrolllock", ATTR{trigger}="kbd-scrolllock"
Amiberry launched as non root user on console.

**Comment by midwan** [comment]
@FlopGithub 
Could you please test with a more recent version, and see if it works better for you?
There was a bug with the index of the items listed in the dropdowns vs the actual selected one, but I believe this was fixed.

**Comment by FlopGithub** [comment]
With version 3.3 ( 17sep ) leds are working with scrolllock as DF0 and NumLock as HD, that's ok.
But why is there no more df* in the items ?

**Comment by midwan** [comment]
I took that away because it didn't exist in WinUAE, and I wanted to sync these areas.
Perhaps I can add it again in a future update, but it would require manually keeping it up to date with newer versions of WinUAE (so it won't get overwritten with a future merge).
