### ISSUE TITLE
Mouse is not working properly in config menu

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#668]
Raspberry Pi 4 with Retropie 4.6.4. Amiberry 3.2 beta (2020-07-13)

Tonight I updated Raspbian Buster and then did a RetroPie update from version 4.6.2 to version 4.6.4. I have had most packages, such as Amiberry, updated as "source".

I have had the following problem since then. Amiberry starts my AmigaOS 3.1.4.1 hdf without any problems. EVERYTHING is going well there. If I now go to the Amiberry menu with F12, I can still move the mouse pointer there, but nothing happens as soon as I want to click something. For example when I click on "Path". Only when I click about 5 cm to the right of "Path" is "Path" actually selected. It's odd, isn't it?

Cheers
Retro1968

**Comment by Retro1968** [comment]
I just uninstalled amiberry and deleted everything in the "opt / retropie / configs / amiga / amiberry" folder except for the "conf" folder. Even after reinstalling amiberry with the "Source" option, the mouse problem remains.

**Comment by Retro1968** [comment]
The mouse problem also exists when I click on "Start Amiberry" under RetroPie, so no config file is loaded.

**Comment by amyren1966** [comment]
I had a similar issue with the Amiberry config menu, using Amibian. 
I was advised to toggle the overscan setting in the raspi-config settings. That fixed it for me.

**Comment by Retro1968** [comment]
Thanks for the hint, but when I activated the overscan, nothing changed. However, a RetroPie update had apparently changed the screen resolution from Amiberry to "52-11" with "1920x1080 @ 25Hz", which caused this error. After I corrected the screen resolution to "52-16" with "1280x1024 @ 75 Hz", the error was fixed. :-)

**Comment by midwan** [comment]
@Retro1968 
I'm glad to see you found a fix for this! 👍
