### ISSUE TITLE
Joypad overrides mouse as input

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#669]
I don’t think it’s related to the other issue just reported. Amiberry GUI works fine with mouse, as well in game. Tested monkey island without issues.

But when trying to move the cursor in Amiga os, like when there is screen with a cracking group in a “window” the cursor doesn’t move. Starting with a mouse connected doesn’t use the actual mouse as input but rather the controller. In my case SN30PRO, when moving the analog sticks the cursor moves slightly but you can’t control it. It seems that the controller overrides the the mouse as input. Maybe not a bug but a setting instead but can’t figure it out. I built today with latest 3.2 beta from source but I’m pretty sure this happened even in earlier versions of Amiberry. I just never reported it.

Running Amiberry on a PI 4 with RetroPie 4.6 , using latest commit of RetroPie-Setup as of today.

**Comment by midwan** [comment]
@stuffu 
Could you please test with the current `dev` branch version, and see if you still have the problem there?
I've rewritten the controller handling/mapping code there, so hopefully this is already resolved.

**Comment by stuffu** [comment]
Sure, but I failed to build with dev branch when trying... In amiberry.sh, what should I change?

**Comment by midwan** [comment]
@stuffu 
Coming back to this...

If this is still an issue for you, could you please post a screenshot of your Input panel when you have the problem?
What you describe sounds like Port 0 having a controller assigned to it, instead of the Mouse.

**Comment by stuffu** [comment]
I would love to help but I don’t know how to choose to update from dev branch. I’m stuck on 3.3...

**Comment by midwan** [comment]
Don't worry about the `dev` branch for now. :)
Please provide a screenshot from the version you currently have, the `dev` one is not required for what you describe.

**Comment by stuffu** [comment]
Ok, so I tested some different games with both mouse and controller attached. First arkanoid revenge of doh, the controller doesn’t do anything really, mouse works but you can see the cursor in game and it’s not centered on “bat” so mouse position is wrong. Also tested a-train, neither mouse or controller moves the cursor. Also tested disconnecting the mouse and use only the controller, couldn’t even get the game to start (button press not recognized). A-train controller only, same as arkanoid, nothing happens. Same with workbench screen, pre game load, I’m unable to move the cursor. 

![ADAB916A-6744-48EE-B27F-4A6B4ED1C4DD](https://user-images.githubusercontent.com/4310040/98449775-fb1f1180-2136-11eb-84db-aeb2c633cd15.jpeg)

**Comment by midwan** [comment]
@stuffu 
I still can't recreate this here.
Are you using ADFs or WHDLoad .lha files to run these games?
If they are WHDLoad, could you attach your amiberry.conf file here please? Maybe it's a problematic setting there.
In that case, the ADF version should work as expected, also - so that's one test worth trying.

**Comment by stuffu** [comment]
Hi

I only have WHDLoad .lha files. Attaching 
[amiberry.conf.zip](https://github.com/midwan/amiberry/files/5866594/amiberry.conf.zip)

Not sure it's related, but the mouse cursor is off target, It appears that the actual clickable area is above the button image. Attaching a screenshot with the cursor clicking "Help" button. Having the cursor on the actual button doesn't do anything.
![IMG_0728](https://user-images.githubusercontent.com/4310040/105708185-5aa9e380-5f14-11eb-9963-8bad2ab53690.jpeg)

Let me know if you want me to try something else and thanks for looking into it.

**Comment by midwan** [comment]
Do you have an ADF version of the game(s) you're testing, so we can check if it's related to the WHDLoad one only?

**Comment by stuffu** [comment]
Not at the moment, but I will see if I can work something out with ADF. 

The mouse cursor issue is not related to a game though, I guess you recognise the image from Amiberry GUI. I can't recall changing anything related to mouse input. Is that a known bug?

**Comment by stuffu** [comment]
I tried several ADF but they all ended up in a black screen, not advancing from that point. Never bothered with adf so might have missed something here, but ran them from ES as the WHD games.

I did some more tests and, maybe this is intended, but pure mouse games the mouse works as expected (cursor at correct position as well), tested A-train, future wars, dungeon master and monkey island. What doesn’t work is having the mouse disconnected and start just with the controller. It’s like the controller is disabled, even controller hot key doesn’t respond. Should the controller behave this way? It would be nice to be able to move the cursor with a controller stick, even if it’s not the same experience as with a mouse. I believe it worked like that previously? I have been away from amiga gaming for a while so it’s a bit blurry...

“Joystick” games works fine with the controller. Just ran Arnie to test it out, hot key also works.

Tested Arkanoid revenge of doh again and the cursor is off from the position it should have been, with mouse. It feels like it’s related to the cursor being off in GUI as well.

all tested are “official” WHDLoad games.

**Comment by midwan** [comment]
Do you have Overscan enabled by any chance? I remember a mouse offset issue when Overscan was used (on the RPI screen settings, not with emulation)

**Comment by stuffu** [comment]
Checked and it says single lines in line mode. Somewhere along the trial and error for this I reset settings so everything should be default. If I recall correctly, someone else reported a similar issue with cursor being off?

**Comment by midwan** [comment]
The overscan setting is set in `/boot/config.txt` and it's an RPI system setting, not related to Amiberry. :)

**Comment by stuffu** [comment]
Ooops :) Anyway, checked but it was commented, no overscan enabled. The only thing I found was this: `overscan_scale=1` but from what I understood it's not really related to overscan and should be uncommented.

**Comment by midwan** [comment]
This should no longer be an issue with the latest version in `master` (4.1.5 RC).
If you still have the problem with the latest updates, let me know and we'll re-open the case.
