### ISSUE TITLE
No picture unless either Screen Mode or Line Mode have been toggled first (every boot)

### ISSUE THREAD

**Issue by tenleftfingers** [midwan/amiberry#671]
**Describe the bug**
I was getting a black/blank screen when booting an A500 config on AmiBerry. But when I switched from Windowed screen mode to Fullscreen, I successfully got a boot screen. Great, except when I reset the machine (screen mode was preserved), I got a blank screen again. Screen mode was still on Fullscreen, so I switched it back to Windowed and reset. It worked. I had a boot screen again. But, when I reset, the image was gone. So, I have to constantly toggle the screen mode to get a picture. Toggling Line Mode has the same effect. Doesn't matter what the value is as long as it's different from last time.

**To Reproduce**
Requirements:
Retropie 4.6 for Raspberry Pi 3B (I have checked the MD5 and I believe this has Amiberry 3.1.3)
Kickstart ROMs
AmiBerry installed

1. Load AmiBerry and choose the A500 from the Quickstart section.
2. Ensure DF0: is empty
3. Click "start"
4. Observe black screen.
5. Press F12 to return to AmiBerry and choose "Reset".
6. Observe black screen.
7. Now press F12 and change the screen mode to anything. Then Reset again.
8. Success! You can see a boot screen.
9. Reset again. The display is gone again.
10. F12 and change the screen mode once more. Reset.
11. Observe that the picture is back, but only for this boot.

**Expected behavior**
No screen mode toggling should be needed. Picture should just display. 

**Screenshots**
Here it is again with pictures
A) Choose the A500 from the Quickstart menu
![IMAGE 2020-07-25 17:44:48](https://user-images.githubusercontent.com/1757768/88461977-29d2ee00-cea0-11ea-9405-c5a0743c01fa.jpg)
B) Press Start and notice there is no picture displayed (I'm using a projector, which is why you only see a wall)
![IMAGE 2020-07-25 17:44:43](https://user-images.githubusercontent.com/1757768/88461990-3bb49100-cea0-11ea-9d32-6930fd5a2f40.jpg)
C) Change the screen mode. It doesn't matter which value, as long as it's different to current.
![IMAGE 2020-07-25 17:44:41](https://user-images.githubusercontent.com/1757768/88462001-55ee6f00-cea0-11ea-8afe-eca2aa6aa71a.jpg)
D) Success! We have a picture.
![IMAGE 2020-07-25 17:44:39](https://user-images.githubusercontent.com/1757768/88462016-61419a80-cea0-11ea-84ec-b5ef54bbc3b5.jpg)
E) Stay with the current screen mode. Do not change it (I was on Fullscreen, so I keep with that)
![IMAGE 2020-07-25 17:44:38](https://user-images.githubusercontent.com/1757768/88462042-761e2e00-cea0-11ea-8b54-7eb2c099d95a.jpg)
F) Reset one more time. We got good results with this setting last time.
![IMAGE 2020-07-25 17:44:38](https://user-images.githubusercontent.com/1757768/88462048-833b1d00-cea0-11ea-9001-cf37798b2fca.jpg)
G) But, there is no picture. It is not the value of Screen Mode that mattered, but the changing of it.
![IMAGE 2020-07-25 17:44:36](https://user-images.githubusercontent.com/1757768/88462053-87673a80-cea0-11ea-8eda-044f90cab22a.jpg)

This change is necessary every time before starting the emulator and before every reset.

**Desktop (please complete the following information):**

Retropie 4.6 for Raspberry Pi 3B (I have checked the MD5 and I believe this has Amiberry 3.1.3)

**Additional context**
This is a standard installation with the ROMs copied to the BIOS directory.
I did try reinstalling Retropi + AmiBerry (binary installation) but I got the same result.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate
Done

**Comment by midwan** [comment]
Thanks for the detailed description.
This seems to be a bug which only happens under that environment, but I managed to recreate it.
Fix incoming soon...

**Comment by midwan** [comment]
Actually, this bug was fixed with a9166eb8b83ec9ba83c6de42f4e7e4b3e83cfe5f from 2020-07-10.
Please upgrade to the latest version from source, if you're running the beta that had this problem.

**Comment by tenleftfingers** [comment]
Thanks for your time. Reinstalling from source was easy from the Retropie config/settings. It's all working now.

**Comment by joolswills** [comment]
Just to note I updated retropie binaries a week ago or so, but updated them again a few hours ago.

Please can people using RetroPie use the retropie forum first for issues, so we can test, and avoid multiple issues being reported here. 

Thanks @midwan

**Comment by joolswills** [comment]
I've ran into this btw after updating to the latest code on master (61fcb9a73b91069665e609558dc3e01f4b07abce)

Rpi4 with fkms and kernel 5.4.51

I'll provide example configs and more information as it could be a config issue my end triggering.

**Comment by joolswills** [comment]
I believe it actually may be an issue with installing from binary Vs source on retropie. It's possible some env stuff in RetroPie is wrong so rather than continue speculating I'll.come back after looking into it thoroughly.

If any retropie users have this issue I recommend they try and install from source. Sorry for spamming a closed ticket.

**Comment by joolswills** [comment]
The issue was due to the prebuilt binaries for the rpi4 being built for sdl2 without dispmanx. So looks like this is an issue with pure sdl2 version on the rpi4.

Rebuilding retropie binaries now.

See https://github.com/RetroPie/RetroPie-Setup/commit/86470aad66cb6189dfadcf96014f9f7a9a517dfa for the related fix on our side.

**Comment by midwan** [comment]
@joolswills 
Thanks!
