### ISSUE TITLE
Gloom Deluxe Slow Music

### ISSUE THREAD

**Issue by GeorgeSpiggott** [midwan/amiberry#673]
Hi, a bug has appeared with Gloom Deluxe that wasn't ptesent in previous versions with the old kernel. The intro and game loading music plays slowly. In game speed seems unaffected. No other games seem affected.

Also the game brings up a black screen when the new Auto screen height feature is enabled. I can negate this by not enabling it. I am assuming this feature is still WIP. 

Amiberry is set to replicate a 25mhz 040 AGA. It is set to fastest speed with JIT in order to have the game settings set as high as possible. 

Raspberry Pi4 Overclocked to 2100Mhz Running the latest 5.4 kernel with legacy audio. Amiberry is 2.3 beta.

**Comment by GeorgeSpiggott** [comment]
Updated Retropie this evening and this problem has resolved itself.

Thanks

**Comment by midwan** [comment]
Thanks for confirming!
