### ISSUE TITLE
NOT A DOS DISK IN DEVICE DH0

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#674]
Raspberry Pi 4, RetroPie 4.6.2, Amiberry 3.2 beta (2020-08-01).
AmigaOS 3.1.4.1 on HDF-File using IDE-Controller

After today's amiberry update, my HDF file is no longer recognized. The error "NOT A DOS DISK IN DEVICE DH0" appears. The error persists even after I have backed up a working backup of the HDF file. The HDF file worked without errors until the update. It is formatted as an IDE hard disk and is integrated with the "A600 / A1200 / A4000 IDE" controller. The "scsi.device emulation" option is also activated.

Cheers
Retro1968

PS: The amiberry option "run at priority" is not saved when I set "High" there. Every time it is set to "normal" I reload the config file.

**Comment by midwan** [comment]
@Retro1968 
Thanks for the report.

I can't recreate a problem with the HDFs I have here, is there a way you can either a) send me the one you're using or failing that b) give me specific steps to recreate one like it?

I fixed the prio options not being parsed when loading the config on a separate commit.

**Comment by Retro1968** [comment]
Simply create a 100 MB HDF File and use as HD-Controller "IDE" (e.g. in WinUAE). After that load your workbench, start HD-Toolbox and configure the new HD-File. After that copy your workbench on that HDF-File and start it with amiberry.

I restored a backup to my SD card earlier and am now using Amiberry 3.2 (2020-07-30) with my old config file. The HDF file is recognized normally again. I suspect that something is no longer saved correctly in the config file, since the priority setting under "Display" is also not saved.

**Comment by Retro1968** [comment]
But the problem exists since then. Something from version 2020-07-30 to 2020-08-01 must have changed that causes the error.

**Comment by Retro1968** [comment]
How an HDF file is recognized in the HDToolbox - creating an HDF file under WinUAE:
-------------------------------------------------- ----------------------------------------

When creating a new HDF file, the file size may not exceed 4000 MB, as with FAT32
Formatted SD cards can only recognize files with a maximum size of 4GB.

So that an HDF file in the AmigaOS is recognized as a SCSI drive in the HDToolbox,
The following settings must be made when creating the HDF file in WinUAE:

Chipset: extra chipset = A1200

Expansions: * Set A600 / A1200 / A4000 IDE (Commodore) to "Enable".

CD & hard files:

     Add hard file:

          HD controller: Commodore A600 / A1200 / A4000 IDE

          Activate "Full drive / RDB Mode".

          Enter 4000 (or the size you want) under "New hard disk image file" and click on "Create". Now the file name
          and specify the storage location in the following menu.

A newly created HDF file is not on the first start as a second hard drive under the Workbench
to see. The following settings must first be made in the HDToolbox:

Change Drive Type: Drive Types = SCSI -> Define New: Read Configuration -> OK -> OK

Partition Drive (confirm all entries with the RETURN key):

Change the partition size to 4000 MB (or the size you want).

Check "Advanced Options".
Partition Device Name: DH0
Buffers: 1000

Click the "Change" button:
Select "Standard File System".
Check "Fast File System" and "Long Names".
MaxTransfer: 0x1FE00

Save Changes to Drive

Exit


The HDF file created in this way is recognized in AmigaOS after a restart and can then be formatted.

**Comment by Retro1968** [comment]
Since Amiberry Version 3.2 (2020-08-02) the hdf error is gone. Everything is OK. :-)
How do you solved that?

**Comment by midwan** [comment]
@Retro1968 
Thanks for confirming.
It was related to some glitches when loading a config, and detecting changed prefs during runtime. :)

**Comment by actraiser30** [comment]
Hi,I have a somehow the same error,using amiberry 3.3 after updating to 4.1.6 i got this error in the photo

![IMG_20220504_124948](https://user-images.githubusercontent.com/38106933/166660287-55060c8e-f123-4db5-967d-874c6735cc6d.jpg)


if i go back to amiberry 3.3 everything works fine again

thank you

**Comment by actraiser30** [comment]
ok kanena provlima efxaristo
