### ISSUE TITLE
PPaint 7.3c loads images in false colors.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#676]
Raspberry Pi 4, RetroPie 4.6.2, Amiberry 3.2 beta (2020-07-30) with AmigaOS 3.1.4.1.

Since this version the Pictures i load in PPaint 7.3c are shown in false colors.
I disabled "Filtered Low Res", "Blacker than black" and "Remove interlace artifacts" but the error remains.

The problem has existed since you introduced the "Display" tab. So there must have been a mistake somewhere.

Cheers
Retro1968

**Comment by midwan** [comment]
@Retro1968 
I have changed the default screen mode to be 32-bit, since I didn't notice any disadvantages in my tests.
If we start discovering things like that however, I can easily switch it back to 16-bit. The only problem with 16-bit modes was that "Filtered low resolution" didn't show the correct colors, but I guess not many people would care/want to use that...

**Comment by midwan** [comment]
It looks like only the 8-bit modes are affected, can you confirm that please?

**Comment by Retro1968** [comment]
A 24-Bit photo was shown with correct colors so i guess you are right.

**Comment by midwan** [comment]
The priority tab is completely unrelated to the HDF problem you mentioned. I'll have to recreate that and see what caused it.

**Comment by Retro1968** [comment]
> 
> 
> The priority tab is completely unrelated to the HDF problem you mentioned. I'll have to recreate that and see what caused it.

But the HDF-problem exists since then. Something from version 2020-07-30 to 2020-08-01 must have changed that causes the HDF error.

**Comment by midwan** [comment]
@Retro1968 
Sure, then it was introduced there, but there were more changes besides just adding a new panel. One of those caused it, not the panel itself or the Priority related functions. They have nothing to do with the HDD handling.
I need to recreate the problem first, then start testing small changes to see which one did it.

**Comment by midwan** [comment]
@Retro1968 
The incorrect colors in 8-bit RTG modes should now be fixed, with 17d8f7b15b92114185577dae9292975ef87a14c0
