### ISSUE TITLE
Use UTF-8 on host filesystem

### ISSUE THREAD

**Issue by chris-y** [midwan/amiberry#677]
**Is your feature request related to a problem? Please describe.**
When using a filesystem directory as a hard drive AmiBerry writes files always in the Amiga's charset.  This causes weird characters on the Linux side when non-ASCII characters are used on the Amiga filesystem.  This makes it difficult to manipulate these files under Linux as they usually can't be typed.

**Describe the solution you'd like**
Amiga filenames should be translated to/from UTF-8 for Linux filesystem access, probably as an option for compatibility.

**Comment by midwan** [comment]
@chris-y 
Do you have any specific examples of this, please?
Amiberry uses UTF-8 internally, like FS-UAE, for the charset.

**Comment by chris-y** [comment]
Here's the same file, created under Linux with accented characters.

In Linux:
![image](https://user-images.githubusercontent.com/1818803/101397480-a5b85a80-38c4-11eb-8e63-04ca5a00baeb.png)

In Amiberry:
![image](https://user-images.githubusercontent.com/1818803/101397728-f9c33f00-38c4-11eb-9cd6-066c330e3c96.png)

**Comment by midwan** [comment]
Thanks for the example, I'll look into this further.

**Comment by midwan** [comment]
In fact, the problem here is the opposite:
Linux can save files in UTF-8 without a problem, but AmigaOS does not support UTF-8. The filenames need to be converted to Latin1 when saving, with "invalid" characters being replaced. I'm working on such a solution, partly using logic from FS-UAE's similar approach.
