### ISSUE TITLE
DOS-Error #205 (object not found) on reading "".

### ISSUE THREAD

**Issue by joelnet** [midwan/amiberry#679]
I have read a few issues regarding the DOS-Error 205 error and none seem to solve my problem.

I'm having problems getting WHDLoad working. I get stuck on a black screen after trying to load and the logs in Debugs aren't giving me any clues.

I'm using the latest build of RetroPie on a raspberrypi4.

Debugs/AnotherWorldHD.whdscript_debug

```
DOS-Error #205
(object not found)
on reading "".
Other posts I have read, there is a kickstart in between the quotes, but my logs just show empty.
```

```
$ ls -alh /opt/retropie/emulators/amiberry/whdboot/save-data/Kickstarts

drwxr-xr-x 2 pi pi 4.0K Aug  8 01:01 .
drwxr-xr-x 6 pi pi 4.0K Aug  6 08:53 ..
-rw-r--r-- 1 pi pi    1 Aug  6 08:53 foo.txt
-rwxr-xr-x 1 pi pi 3.8K Aug  6 08:53 kick33180.A500.RTB
-rwxr-xr-x 1 pi pi 3.8K Aug  6 08:53 kick33192.A500.RTB
lrwxrwxrwx 1 pi pi  112 Aug  8 01:01 kick34005.A500 -> '/opt/retropie/emulators/amiberry/kickstarts/Kickstart v1.3 rev 34.5 (1987)(Commodore)(A500-A1000-A2000-CDTV).rom'
-rwxr-xr-x 1 pi pi 4.0K Aug  8 00:52 kick34005.A500.RTB
-rwxr-xr-x 1 pi pi 4.9K Aug  6 08:53 kick40063.A600.RTB
lrwxrwxrwx 1 pi pi   97 Aug  8 01:01 kick40068.A1200 -> '/opt/retropie/emulators/amiberry/kickstarts/Kickstart v3.1 rev 40.68 (1993)(Commodore)(A1200).rom'
-rwxr-xr-x 1 pi pi 4.9K Aug  8 00:52 kick40068.A1200.RTB
-rwxr-xr-x 1 pi pi 4.9K Aug  6 08:53 kick40068.A4000.RTB

$ crc32 kick34005.A500
c4f0f55f
$ crc32 kick40068.A1200
1483a091
$ crc32 kick34005.A500.RTB
ae7a9ac7
$ crc32 kick40068.A1200.RTB
cf631e0b
$ crc32 ~/RetroPie/roms/amiga/AnotherWorld.lha
7f700435
```

**Comment by CypherXG** [comment]
Did you have all Kickstarts in the devs/kickstarts directory?
WHDLoad does not work without the roms. 
My kickstart dir looks like my picture:
![Anmerkung 2020-08-09 095450](https://user-images.githubusercontent.com/7895130/89727566-72ed7b00-da26-11ea-8d87-8e8f30991e03.jpg)
Your roms doesn't match the size of the needed roms. 
Without them you will get a Dos 205 File not found error and a black screen because there is no kickrom.

I hope i can help you

**Comment by joelnet** [comment]
[quote]Did you have all Kickstarts in the devs/kickstarts directory?[/quote]

*all*? no. I only put Kickstart 1.3 and 3.1 in there. The other files were already there from the amiberry install.

I'll play around with this folder and if anything happens.

**Comment by joelnet** [comment]
I still can't get anything working.

Initially I only had the 3 ROMS listed with checkmarks from this page https://github.com/midwan/amiberry/wiki/Kickstart-ROMs-(BIOS).

I installed all 10 ROMS and have confirmed the CRC32 on each ROM file.

I have also confirmed the symlink for each file is correct too.

**Comment by joelnet** [comment]
I can also run `adf` files just fine. It's the `lha`'s I just can't get to load.

**Comment by CypherXG** [comment]
LHA Version?
Did you try to rename your kickstart files?
Read rights are correct for the directory?

**Comment by midwan** [comment]
@joelnet 
Have you tried using the "Update XML" button, from the Paths panel?
That will download the latest files if they are missing, which might help.
You could also try deleting them manually first, to make sure they get regenerated after using that button.

**Comment by joelnet** [comment]
> @joelnet
> Have you tried using the "Update XML" button, from the Paths panel?
> That will download the latest files if they are missing, which might help.
> You could also try deleting them manually first, to make sure they get regenerated after using that button.

I clicked `Update XML` and then deleted the files in `whdboot/save-data/Autoboots` and `whdboot/save-data/Debug` same issues.

**Comment by joelnet** [comment]
> LHA Version?
> Did you try to rename your kickstart files?
> Read rights are correct for the directory?

AnotherWorld.lha version 2.4 (18.03.06)

The kickstart files are all automatically symlinked to the name required by https://github.com/midwan/amiberry/wiki/Kickstart-ROMs-(BIOS)

the owner is `pi`, which is correct and `rwx` is assigned to all files.

**Comment by joelnet** [comment]
I swapped my boot-data.zip for http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/downloads/03-2018/boot-data.zip to show the DOS.

I don't know if this is helpful

```
WHDLoadGame: will be mapped to DH1:

Scan for auto-startup and debugging messages...
Copied WHDLoadSave:Autoboots/AnotherWorldHD.auto-startups to T:

No Debug file found.DH0:WHDbooter/Debugs/

Scan done

Execute the Auto-Startup boot script.

WHDLOAD failed returncode 101
1>
```

**Comment by joelnet** [comment]
I just noticed the lha I am using is only 58k and could no way contain a game. It wasn't a problem with the Kickstarts, it was the lha. I switched to a good lha and the game is loading!

Thanks everyone for your help!

**Comment by midwan** [comment]
Thanks for confirming the fix :)
Hopefully if anyone else runs into this, they can find this solution.

**Comment by joelnet** [comment]
> Thanks for confirming the fix :)
> Hopefully if anyone else runs into this, they can find this solution.

Ya what threw me off on this one was the error messages. I wish there was a way to get a more verbose error. 

Appreciate the help even though it was user error 👍
