### ISSUE TITLE
Amiberry install amiga OS 

### ISSUE THREAD

**Issue by symbios24** [midwan/amiberry#68]
Hello, i would like to know if its possible to install Amiga OS in amiberry,  if yes are there any instructions on how to install it? 

Thank you

**Comment by midwan** [comment]
@symbios24 
Amiberry is a UAE clone, so it works very much like all UAE clones. You can use an ADF image of Workbench disks for example, to start it up and begin an installation.

You will need to configure either an HDF or a directory as a "Hard Drive" for the Amiga side. I'd recommend a directory as it's easier to manage and has less problems (HDFs can be problematic if they grow in size and you may also run out of space if you fill it up).

Once you boot using your Workbench "Install" disk, you can just follow the normal procedure like you would on a real Amiga. 

Alternatives would be to use pre-installed systems, like ClassicWB (http://classicwb.abime.net/)

**Comment by symbios24** [comment]
Kalispera ellinas eisai?

**Comment by midwan** [comment]
Ναι :)

**Comment by symbios24** [comment]
Kali doulia ekanes mpravo, epidi ligo me zalizei i diadikasia na ta kano ola afta eiparxei kapio image me to amiga os eggatestimeno?

eyxaristo

**Comment by midwan** [comment]
Δες το ClassicWB που ανέφερα παραπάνω, είναι σχετικά εύκολο.

**Comment by symbios24** [comment]
euxaristo oi odigies einai se video eiparxoun odigies se keimeno?

**Comment by symbios24** [comment]
kalimera katafera na to kano, tora thelo na trexei apefthias stin ekinish sto boot mipos ksereis pos tha ginei afto?

**Comment by symbios24** [comment]
Kalispera, mipos ksereis pos mporo na peraso to quake kai to doom sto amiberry?

efxaristo
