### ISSUE TITLE
Fullscreen doesn't work, games are centered with black borders 

### ISSUE THREAD

**Issue by 25minutes** [midwan/amiberry#683]
**Describe the bug**
I'm trying to let the game fill the whole screen. I don't find much info about this topic in Wiki. I see 2 similar closed issues but unfortunately none of them help. 
https://github.com/midwan/amiberry/issues/221
https://github.com/midwan/amiberry/issues/645

I change the following in amiberry.conf (keep all other parameters untouched). However, when I launch WHDLoad .lha files, the game screen is still centered with black borders, not in full screen. 

default_horizontal_centering=yes
default_vertical_centering=yes
default_correct_aspect_ratio=no
default_fullscreen=yes

**To Reproduce**

I have tested with two devices, and see the same result on both of them.
1. Raspberry Pi 3B running RetroPie 4.5.1, connecting to CRT monitor (PAL mode 720x576). I update RetroPie-Setup script and install Amiberry from binary today, so I think it should be DispmanX version. The about page shows Amiberry v3.2 beta (2020-8-5).
2. Amlogic S905 device running EmuELEC v3.5 (https://github.com/EmuELEC/EmuELEC), connecting to LCD (1080p mode 1920x1080). I think it's SDL2 version. The about page shows Amiberry v3.1.2 (2020-2-10).

On both devices, the only thing I change is amiberry.conf on the parameters listed above. I've tried different games and the results are all the same.

**Expected behavior**
In fullscreen mode with correct aspect ratio off, game screen should fill the whole screen.

**Comment by midwan** [comment]
@25minutes 
The `amiberry.conf` settings define the default values (i.e. what should the emulator do when no config is loaded), but individual configs can always override those.
If you're using WHDLoad games with the autoloader (which is the default way of handling them in RetroPie), then the settings for each game will be picked from the WHDLoad XML file. You can double check this, by pressing F12 once you have loaded a game, and checking the settings in the Display panel.

The XML is frequently updated with improved settings for each game, so it would be useful to try getting the latest first (use the button in the Paths panel).
If the settings included there are not perfect, you can try playing around with the Display panel and see if you can tweak them to perfection, the submit your changes to the relevant repo (or make a suggestion there), so they can be updated accordingly: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder

**Comment by midwan** [comment]
Also, it's good to keep in mind that "Fullscreen" and "Fullwindow" modes are different in SDL2 versions (Fullscreen will also change resolution, Full-window will stretch to the current resolution), while Dispmanx only uses Full-window.

This used to be different in older versions of Amiberry, where there was only Fullscreen and it actually meant "Full-window". :)

**Comment by 25minutes** [comment]
@midwan 
Thank you for the info. When I read the Wiki, I thought amiberry.conf setting would always take effect as long as I don't have .uae for the specific game. Apparently I have misunderstood.

On RetroPie, when I open GUI, the Display panel seems ok. 
- Screen mode: Fullscreen
- Correct Aspect Ratio: unchecked
- Centering: Both Horizontal & Vertical are checked
- Fullscreen: It shows 800x600, not sure if it will cause problem, so I change it to 720x576 (as It's CRT PAL mode). Then I select Resume button at the right bottom of the GUI. However, the game is still centered with back borders. 
- In the Screen mode drop down menu, if I change it to "Full-window", and select Resume button, it only shows black screen, so I have to cheange it back to Fullscreen. Any idea? The retropie team pre-build binary isn't Dispmanx?

If I search the .lha file name "ChaosEngine_v1.2_0106" (use this game as an example) in amiberry/whdboot/game-data/whdload_db.xml, I see the following. Do you see any individual configs of this game can block it from running in fullscreen?

	<game filename="ChaosEngine_v1.2_0106"  sha1="4121079eff94ce88391208e88cb77f8bee7e4575">
		<name>Chaos Engine</name>
		<subpath>ChaosEngine</subpath>
		<variant_uuid>9191275d-3ca7-5a8e-9f61-b7af6d368617</variant_uuid>
		<slave_count>1</slave_count>
		<slave_default>ChaosEngine.Slave</slave_default>
		<slave_libraries>False</slave_libraries>
		<slave number="1">
			<filename>ChaosEngine.Slave</filename>
			<datapath></datapath>
		</slave>
		<hardware>
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
		PORT1=JOY
		JIT=FALSE
		SCREEN_HEIGHT=256
		SCREEN_CENTERH=SMART
		SCREEN_CENTERV=SMART
		</hardware>
	</game>

Also, I've searched the whole file system for *.uae. There are only 2 of them: rp-a1200.uae & rp-a500.uae, both under /opt/retropie/configs/amiga/amiberry/conf. I think they come with Amiberry installation. I didn't change these files, but on EmuELEC, I see it contains parameters like amiberry.gfx_correct_aspect, gfx_fullscreen_amiga, gfx_center_vertical, gfx_center_horizontal, etc. Will they affect the actual config? My understanding is, Amiberry only looks for .uae file with same file name (e.g. ChaosEngine_v1.2_0106.uae), so rp-a1200.uae & rp-a500.uae doesn't matter. Am I correct? 

Last question, on EmuELEC, "full screen" option is just a check box, not a drop down menu. I don't see how to choose "Full-window". Is "Full-window" not supported in v3.1.2? 

Sorry for so many questions raised. I've been using Retropie and EmuELEC for years, but I'm new to Amiberry. :)

**Comment by 25minutes** [comment]
Update: 
On RetroPie, In the Screen mode drop down menu, if I change it to "Full-window", and also check "Auto Height" option. Then I can see game screen. However, there's black borders at left/right side.

**Comment by 25minutes** [comment]
Update: 
On RetroPie, If I check "Auto Height" (need change to Full-window to enable this option then change back to Fullscreen) & "Fullscreen" together, the game no longer has black borders at top/bottom side, but still has black borders at left/right side.

**Comment by midwan** [comment]
Try changing the Width as well?
E.g. 640 might be a good bet. ;)

**Comment by 25minutes** [comment]
Awesome! 640 resolves the issue on RetroPie (CRT)! Though I have a few more questions:

1. I edit amiberry.conf with "default_width=640". However, when I re-launch the game, there's black border at left/right side, GUI shows the width is still 720. Where does this 720 come from? 

2. I edit whdload_db.xml, and add "SCREEN_WIDTH=640" for this game. This time, game runs in fullscreen properly. In addition, as GUI says height is 400 with "Auto Height" selected, I further change "SCREEN_HEIGHT=400" for this game. Now game can run in fullscreen perfectly with "Auto Height" unechecked.

3. A quick test on EmuELEC with 1080p monitor shows that the same whdload_db.xml method doesn't work. I may re-test it tomorrow to be sure. 

4. As Amiberry already has "Auto Height" function, is it technically possible to implement "Auto Width" function as well? 

My 1st guess is, Amiberry has to know the correct resolution that the game uses, in order to scale it correctly. In my case, the game is actually already scaled to full screen, but because Amiberry believes the resolution width is 720, that's why it leaves black borders  at left/right side. Am I correct?

My 2nd guess is, there's no standard resolution for Amiberry games? This is part of the reason why we need whdload_db.xml to gather this info?

**Comment by midwan** [comment]
@25minutes 
1. For WHDLoad games that are recognized by a matching entry in the XML, the settings included in that XML are applied when it's loaded. If no relevant setting is found, then the defaults are applied instead. There might be a bug there in the `whdbooter` section, if it doesn't use the defaults specified in `amiberry.conf` and only goes for the standard, built-in defaults. I'll take a look.

2. What you've done is the correct approach, at least until I look into 1. above. ;)
3. If it is using the same method of loading the game, then the same method should apply anywhere. In other words, is it using the parameter `--autoload <path to lha file>` when launching it? Only then will the whdbooter logic be activated. Alternatively, you can load an `.lha` file through the GUI also (check Quickstart)
4. I did try to implement that as well, but it killed the performance because it had to be calculated on each frame. Usually the width doesn't fluctuate so much between games however, so it seemed like a reasonable compromise.

Finally yes, your assumption is correct. Amiberry will scale the window specified to the full screen. If the game uses a slightly lower window, then you'll have black borders.

Amiberry emulates a few different Amiga models, all of which had programmable screen resolutions. Therefore you may have some applications or games that use 640 pixels only, but you can also have others that use more (up to the maximum of 720, which is the default). The height was also variable, and many games made use of different heights to gain more performance (less lines to draw on screen).
