### ISSUE TITLE
Segmentation fault with HDF

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#686]
**Describe the bug**
Segmentation fault happens when you change controller from IDE to UAE.

**To Reproduce**
1. Create a HDF file in amiberry (or with truncate)
2. Add that HDF to a IDE controller
3. Partition and format HDF
4. Change controller to UAE in GUI and reset. You will now get a segfault.

Even if you change the controller back to IDE, amiberry won't even boot the emulated with that HDF attached.

**Comment by midwan** [comment]
This seems to be fixed, or at least I cannot recreate it using the steps above.
I tried them with a kickstart 3.2, installed the AmigaOS 3.2 release on it, then tried changing the controller.
I also did a second test by adding another HDF after this step, going through HDToolBox to partition, format and copy some files over to the new drive. Then changed the controller type and rebooted.

In all scenarios it worked without crashes, and I could see my drives normally.
