### ISSUE TITLE
"Unable to create window" on Raspberry Pi OS Lite

### ISSUE THREAD

**Issue by DavidCWGA** [midwan/amiberry#689]
Attempting to run the pre-built release binary gives this error:
Unable to create window Could not initialize OpenGL / GLES library

Running one built from source gives a similar error:
Unable to create window Could not initialize EGL

I'm not sure of the difference between OpenGL and EGL but both fail. Is it because I'm running RPiOS "Lite"? And if so, what's the minimal packages I need to install to get this to work? I chose the Lite OS because I assumed it didn't use X. Is that wrong?

**Comment by DavidCWGA** [comment]
I'm getting the same error on the "full" Raspberry Pi OS, so I guess it's not because X is not installed.

**Comment by solskogen** [comment]
You must have X running in order for amiberry to work out of the box.

**Comment by midwan** [comment]
@DavidCWGA 
As @solskogen mentioned, it will work out-of-the-box only if the SDL2 framework installed was built with support for the available drivers in the system. On RPI OS (both Desktop and Minimal), the pre-built SDL2 is supplied with support for the X11 environment, so it won't work from the console.

If you want it to work from the console also, you would need to do some manual work, as documented here: https://github.com/midwan/amiberry/wiki/Compile-SDL2-for-KMSDRM

Other distros might be a different story, such as Manjaro Linux (64-bit only) which comes with SDL2 compiled to include support for KMSDRM (so it can also run from the console there).

**Comment by DavidCWGA** [comment]
Thank you for explaining, and I'm sorry that I'm an idiot. (!)

I installed xorg, and now I can do "startx amibian" and it works great. Thank you.

**Comment by joolswills** [comment]
Just to note that you can use RetroPie-Setup to install just amiberry if you wish on top of Raspberry Pi OS. And it will install our SDL2 with Kms support.

Eg.

`sudo ./retropie_packages.sh amiberry _autoupdate_`

Would install or update just amiberry using a prebuilt binary if available and all dependencies. Or leave out the `_autoupdate_` parameter to build latest source.

Or if you just wanted retropie SDL2

`sudo ./retropie_packages.sh sdl2 _autoupdate_`

Etc

/Spam :-)

**Comment by midwan** [comment]
@joolswills 
Thanks, that's useful to know :)

**Comment by DavidCWGA** [comment]
> sudo ./retropie_packages.sh amiberry _autoupdate_

> Would install or update just amiberry using a prebuilt binary if available and all dependencies. Or leave out the _autoupdate_ parameter to build latest source.

For what it's worth, this doesn't seem to work. It installs, but running the resulting version of amiberry throws this error:

    Internal error; file src/osdep/gui/main_window.cpp, line 990
    Aborted

**Comment by joolswills** [comment]
You need to launch it via the amiberry.sh script or change folder to the amiberry folder before launching directly.

**Comment by DavidCWGA** [comment]
Yup, that works. Thanks. :)
