### ISSUE TITLE
PowerLED + HD LED Bug

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#69]
Sry that i found a small Bug again :-)
There is a little Bug with the PowerLED Filter and the HD LED.
At the start the Amiga Filter is standart set on. U can see it while the LED Color "red" lights up for the Power LED. This is standart in all Amiga Computer.
Same with the HD LED. The behavior is accurate as the Power LED.
HD reading or writing does not change the HD LED Color.
I've test it. I make the LED for reading green and for writing red.
But it doesn't work.
The filter settings in the audio menu have no influence on the behavior of the LEDs.
Only after a program / demo set the internal audio filter to off, then the HD LED is off.
After the Filter is off the HD LED doesn't work.

So that's all from me.....
Best regards 
Markus

**Comment by midwan** [comment]
@CypherXG 
Thanks for the feedback. Also, never be sorry for finding a bug, it helps making things better and we should be grateful for finding it (it means we can fix it). :-)

I'll test this and see what I find.

**Comment by CypherXG** [comment]
In the actually Version it was fixed.
But i read that the Keyboard LED's only working when u start the emulator without root rights.
It is not easy to geht all dirs, functions with the pi if you are not root.

About the onscreen LED's. Can you add a CD and a Audio Buffer LED?
I tried to make that but i can not see it on the Screen. It made some mistakes.. :-)

**Comment by midwan** [comment]
OK, let's close this issue then to avoid confusion (since the LEDs do work).
Regarding the Audio Buffer LED, we can open that up separately and discuss it there, OK?

**Comment by CypherXG** [comment]
Ok :-)
