### ISSUE TITLE
Add CUE/BIN Guidance to Docs

### ISSUE THREAD

**Issue by idemiq** [midwan/amiberry#691]
**Is your feature request related to a problem? Please describe.**
I'm having difficulty configuring/launching CUE/BIN CD32 images in Amiberry (RPi). The [Docs](https://github.com/midwan/amiberry/wiki/Using-Amiberry-WHDBooter-with-RetroPie-(Step-3)) generally are quite concise, but lack advice/guidance on the subject.

**Describe the solution you'd like**
For owners of Amiga CD32 games, it'd be very useful to a have guide on how to install and run our Disc images - so that Audio tracks and FMV are kept in-tact. Ideally with WHDLoad Autoboot.

**Describe alternatives you've considered**
I've run through all the guides I can find on the subject, and can't get images to load from EmulationStation without Quickstarting them via the +Amiberry (or F12) UI.

**Additional context**
I've a [thread](https://retropie.org.uk/forum/topic/27807/amiberry-cd32-bin-cue-configuration-troubles) on the RPi Forums which as some additional information on my experience. In general - help for setting-up Amiberry/RPi/CUE is very hard to find.

**Comment by midwan** [comment]
@idemiq 
Have you upgraded your RetroPie-script to the latest version?

With the v3.2.1 release of Amiberry, one of the changes included was the syntax of the command line parameters.
Launching games through RetroPie uses those command line parameters, so they had to be updated to match, as well. The RetroPie script handles that.

**Comment by idemiq** [comment]
Hi @midwan - Yeah I've updated the Retropie-Setup script.
```
Version: 4.6.7 - Last Commit: 2 Days Ago (91e69972)
System: rpi4 (armv71) - running on Raspian GNU/Linux 10 (buster)
```
My paths (with example files) are:
```
/home/pi/RetroPie/roms/amiga/Alien Breed - Tower Assault_CD32.cue
/home/pi/RetroPie/BIOS/amiga/Kickstart v3.1 rev 40.60 (1993)(Commodore)(CD32).rom
```
And here's a Pastebin of my [amiberry.conf](https://pastebin.com/4N1i54w3)

It's possible that I've done something wrong - but I've followed the available Docs as best I can and appreciate any advice.

**Comment by midwan** [comment]
@idemiq 
Coming back to this after a while... :)

Launching CD32 games does not require any default config, and you shouldn't use the A1200 config with it either (it won't enable the CD32 specific bits). If you have .cue/bin files, then the best way to launch them would be:

- From the command line: use the `-autoload <path-to-cue-file>` parameter. E.g. `./amiberry -autoload /home/pi/RetroPie/roms/amiga/Alien Breed - Tower Assault_CD32.cue` (use escape characters where necessary, to handle spaces)
- From the GUI: Select CD32 from Quickstart, select the .CUE file in the CD slot, click on Start.

CD32 images don't need or use WHDLoad. If you have WHDLoad installed CD32 games however, you can also launch them using the `-autoload` option, in the same way as shown above. Only the file passed would probably be an `.lha` one, not a CD image. Keep in mind that WHDLoad games usually don't contain CD audio tracks, so you'll be missing those...

**Comment by midwan** [comment]
Documentation also added in the FAQ section of the wiki: https://github.com/midwan/amiberry/wiki/FAQ
