### ISSUE TITLE
Physical Devices - USB Floppy Drives

### ISSUE THREAD

**Issue by KojiKenshiro** [midwan/amiberry#694]
**Is your feature request related to a problem? Please describe.**

Not really, but would be nice to use my physical disks with Amiberry.

**Describe the solution you'd like**

Be able to use my physical disks with Amiberry.

**Describe alternatives you've considered**

Use ADF files for loading software with.

**Additional context**

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

I’m considering it. :)

**Comment by midwan** [comment]
@KojiKenshiro 
Although that would be nice, there is a problem:
The Amiga floppy disk drives are not the same as the PC ones.

If you want to connect a USB floppy drive and use PC-formatted floppies, that already works. And it's useful for exchanging files with say, a real Amiga. 

But if you want to be able to read Amiga-formatted floppies natively, I don't think that's possible from a hardware perspective. 

Perhaps a middle-ground solution, would be to have the ADF in the (PC-formatted) floppy and open it from there with Amiberry. Again, this works already, though I don't see how useful it would be. :)
