### ISSUE TITLE
Full Power with JIT in Applications and 68020/14 Mhz in Games.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#695]
Raspberry Pi 4 with Manjaro Linux + Amiberry 3.3.1 and AmigaOS 3.1.4.1.

Hello Dimitris,
Thank you that "Correct Aspect Ratio" can now also be deactivated under SDL2. :-)

As you know, I use the AmiHybrid system that I set up according to Steve Jones' instructions. Thanks to the "host-run" command. It is now possible to start Linux applications from the AmigaOS. A very good job from you.

I have now activated JIT and am happy about the very good performance on the AmigaOS surface and the possibility to watch videos via VLC or to surf the Internet with Firefox.

But where there is light there is also shadow. As much as the performance in the applications is helpful, it is sometimes annoying when games are started via WHDLoad from Workbench. The amiberry settings then have to be readjusted regularly to correct graphic errors.

Under RetroPie there is the possibility to start WHDLoad games directly from the RetroPie interface. But I don't want to change my setup. So continue to start WHDLoad games via the Workbench.

I therefore have a feasibility question:
Would it be possible to integrate a second speed controller into the Amiberry setup, with which you can control how fast Amiberry should be if you switch to PAL or NTSC mode through a WHDLoad game? For this Amiberry would of course have to be able to recognize a change to the PAL / NTSC mode in order to be able to adjust the speed.

It would also be conceivable if one had only one additional option in the Amiberry menu that could be activated / deactivated and a 68020 with 14 Mhz was used as standard in PAL / NTSC mode. This should run all games properly.

That would of course be awesome. One could use the full performance in the applications and would not have to worry about the speed-configuration of the games anymore.

Cheers
Retro1968

**Comment by midwan** [comment]
This is already possible to do, using the command line tool `uae-configuration`.

See this example guide: http://guide.abime.net/wb3.1/miscwhd.htm
