### ISSUE TITLE
[Stretch] warning: ‘nodiscard’ attribute directive ignored [-Wattributes]

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#697]
On Raspbian/Debian Stretch during compilation I get a large number of these warnings:
```
In file included from ./include/guisan/defaultfont.hpp:60:0,
                 from src/defaultfont.cpp:61:
./include/guisan/font.hpp:89:71: warning: ‘nodiscard’ attribute directive ignored [-Wattributes]
   [[nodiscard]] virtual int getWidth(const std::string& text) const = 0;
                                                                       ^
./include/guisan/font.hpp:96:49: warning: ‘nodiscard’ attribute directive ignored [-Wattributes]
   [[nodiscard]] virtual int getHeight() const = 0;
                                                 ^
In file included from src/defaultfont.cpp:61:0:
./include/guisan/defaultfont.hpp:100:61: warning: ‘nodiscard’ attribute directive ignored [-Wattributes]
   [[nodiscard]] int getWidth(const std::string& text) const override;
                                                             ^~~~~~~~
./include/guisan/defaultfont.hpp:102:39: warning: ‘nodiscard’ attribute directive ignored [-Wattributes]
   [[nodiscard]] int getHeight() const override;
                                       ^~~~~~~~
...
```
This was introduced here: https://github.com/midwan/amiberry/commit/a6c7862a26db41e57cdd6ba0ab476ea66cf048a8

Am I right that this is something new, not yet supported by Stretch build tools, but can be ignored?

Or is it better to stick with an older Amiberry version on Stretch to avoid any incompatibilities?

**Comment by midwan** [comment]
@MichaIng 
It's an attribute that is valid for newer versions of the compiler, so you're correct. They are not recognized by older versions, but they are just warnings and you can ignore them (the attribute is ignored because it's not recognized, as mentioned in the warning message).

**Comment by MichaIng** [comment]
Many thanks for the quick response.

OOT FYI:
- Last of DietPi Amiberry build based on v3.3 is currently compiling. Since the archive name has not changed, all installs will get the new version automatically, additionally we'll apply an upgrade with DietPi v6.33.
- I updated and added the pre-configured Amiberry RPi images to our download page: https://dietpi.com/#download
I'll create such images for Odroid XU4 and ASUS Tinker Board as well.
- Odroid N2 support will be added soon, as we have good GPU acceleration there. For other models, especially RK3399, reliable/generic way to enable GPU support (without breaking X.org or creating package conflicts) turned out to be difficult, and likely we'll wait for Debian Bullseye where new Mesa drivers provide great support OOTB, comparable or better than the ARM library blob.
- With next Amiberry update (our side) I'll switch to a DEB package approach, so that updates are done via regular `apt upgrade` from then on 🙂.
