### ISSUE TITLE
RPI3B /3B+ -> "auto_height on" = black screen 

### ISSUE THREAD

**Issue by zolive59** [midwan/amiberry#698]
Hello and thank you very much for your work !

---------------------------------------------------------------------------------
Version Amiberry:  v3.3
---------------------------------------------------------------------------------
Describe the bug
   --> When I activate the "auto_height" option, the game screen goes black.
---------------------------
Reproduce**
1. Go to 'Menu'
2. Click on 'auto_height'
---------------------------
**Expected behavior**
Adjust image height
---------------------------
**Screenshots**
Black screen...
---------------------------
**Desktop information:**
- Test on two RPI 3
---------------------------
1 - Device: RPi 3 Model B (armv7l)
   - OS:       DietPi (Buster)
   - Version 6.32.2
   - Only Amiberry install 
   - Whdload install Workbench version
   - Output vidéo: HDMI on TV LCD 50hz Samsung
---------------------------
2 - Device: RPI 3 Model B+ (armv7l)
   - OS:       Retropie (Buster)
   - Version 4.6.6
   - Whdload LHA format.
   - Output vidéo:  TV CRT15khz on vga666 --> SCART (péritel) on "Retropie-CRT-Edition"
 --------------------------
 **Additional context**
Important information:
1 - On DietPi, launching ADF directly without going through the workbench gives the black screen with the option activated.
If I run the Workbench without adding RTG memory, it does not appear (see below)

2 - The Workbench with RTG is displayed, but the whdload games give a black screen when launching, unless I go back to the Amiberry menu and come back without modifying anything, but the game becomes black again when it changes image, except the game "No second prize" ...

On the RPI3 B+ via retropie, the Amiberry menu no longer even appears: only solution: Restart ...

Thanks for taking the time to read my problem.

**Comment by midwan** [comment]
I can't seem to recreate this, so far.
I've tested in RetroPie and RPI OS, using the latest versions of the system/drivers in both cases.
Amiberry 3.3, using Dispmanx and SDL2.

Tested a few different games from WHDLoad (Leander, Ghosts 'n' Goblins, etc), and I switched Auto-Height to ON after launching the game. I didn't see any issues...

**Comment by zolive59** [comment]
Thank you for the answer.
It's strange, because at home, this problem is on two different models (3B and 3B +), LCD and CRT, Retropie and DietPi (Buster) ...
The only possibility must be a file of the old version remained on these two OS which creates this bug...

**Comment by midwan** [comment]
It might be...
Could you try compiling the latest from source, to test again?

**Comment by zolive59** [comment]
Yes, i will do it today and get back to you.

**Comment by midwan** [comment]
@zolive59 
If possible, I'd recommend you also try the `dev` branch version, just in case there's a difference for you.

**Comment by zolive59** [comment]
Ok, I test before the standard version and if the bug returns, I will test the dev version.

**Comment by zolive59** [comment]
It works !!!

Installed with the standard source, I no longer have issues with auto_height enabled.
It is really an important option for me, thank you for having implemented it in Amiberry !!!
The problem came from the binary installation ...
Thank you very much for your work !!!

**Comment by midwan** [comment]
Great, happy to see that it's resolved for you! :)
