### ISSUE TITLE
Bluetooth Joystick support?

### ISSUE THREAD

**Issue by BrianGilbert** [midwan/amiberry#699]
**Is your feature request related to a problem? Please describe.**
I have an 8bitdo SN30 pro+ that I have connected to my pi4 using the terminal based instructions at https://pimylifeup.com/raspberry-pi-bluetooth/ 

The joypad is connected, but is not visible within the Amiberry settings gui. Can you give any direction as to how I can make it visible to the GUI so that I can set it as my joystick?

**Describe the solution you'd like**
I'd like to be able to set this controller as my joystick

**Comment by midwan** [comment]
@BrianGilbert 
Any controller that SDL2 sees, should be visible in the GUI automatically when Amiberry starts up.
If you're comfortable with compiling Amiberry from source, I'd recommend you test the current `dev` branch version, because I rewrote the controller handling logic there - hopefully it should improve the situation.

**Comment by BrianGilbert** [comment]
Any ideas how to configure for SDL2, I'm not having any luck finding info via websearch :(

**Comment by midwan** [comment]
You normally don't have to do anything about that, if it shows up in the system.

I still recommend testing the newer version I mentioned above, as it provides default mappings for many more controllers. Hopefully it will work right away for you.

**Comment by midwan** [comment]
@BrianGilbert 
Did you have a chance to test this any further?

**Comment by BrianGilbert** [comment]
@midwan no, I haven't had time to look at compiling it yet, playing around today

**Comment by midwan** [comment]
@BrianGilbert 
Did you get a chance to test this with `dev` ?
If it doesn't show up there, you can add a mapping for your controller using this tool: https://generalarcade.com/gamepadtool/

Then copy the gamecontrollerdb.txt file (or even better, just append the line it generates to the existing one in amiberry's conf/gamecontrollerdb.txt file) and restart the emulator.

If all goes well, it should show up in the list normally.

**Comment by midwan** [comment]
The 8bitdo SN30 pro+ is supported out of the box in the `dev` branch version, since it's using standard XInput mappings (with a community maintained external file - `gamecontrollerdb.txt` under conf).
This should hopefully resolve this case.
