### ISSUE TITLE
Quake/Doom Installation

### ISSUE THREAD

**Issue by symbios24** [midwan/amiberry#70]
Hello, great project

Does anyone knows how can i install Quake/Doom to Amiga OS? is there a guide somewhere?

Thank you

**Comment by midwan** [comment]
@symbios24 
Thanks for the kind words. Let's try to keep the "Issues" list for bug reports and suggestions however, guides can be found in other places (forums, Facebook groups, etc.).

Closing this one since it's not really an "issue" :)
