### ISSUE TITLE
Kick Pascal 2.0 - Crash

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#704]
Hi,
i've just loaded Kick Pascal for general testing (I've it on my personal distribution) and freeze the system, with GURU 8000 0003 or 8000 0004 (or crash amiberry and returning on linux).
I have attached the ADF, for your test.

Hope to help you :)

[Kick Pascal v2.00 (19xx)(1900)(Disk 2 of 2)[Maxon Computer Gmbh Libraries].zip](https://github.com/midwan/amiberry/files/5415684/Kick.Pascal.v2.00.19xx.1900.Disk.2.of.2.Maxon.Computer.Gmbh.Libraries.zip)
[Kick Pascal v2.00 (19xx)(1900)(Disk 1 of 2)[Maxon Computer Gmbh Editor].zip](https://github.com/midwan/amiberry/files/5415685/Kick.Pascal.v2.00.19xx.1900.Disk.1.of.2.Maxon.Computer.Gmbh.Editor.zip)

**Comment by midwan** [comment]
What configuration did you use for this?
It seems to work on an A1200 config that I tried.

**Comment by FabrizioRadica** [comment]
> 
> 
> What configuration did you use for this?
> It seems to work on an A1200 config that I tried.

Hi
I state that, I'm creating my own distribution (FAMIGA) with instead of HDF, folders in the linux filesystem.
Here my deafult.uae
This problem it's the same of IBrowse crash.

The problem could be the KS 3.1.4, I think.

Kickstart 3.1.4 and Workbench 3.1.4.1 with BestWB
[default.txt](https://github.com/midwan/amiberry/files/5469545/default.txt)

**Comment by midwan** [comment]
Kick Pascal also crashes on WinUAE, so this is probably a compatibility issue. I think it was designed for Kickstart 1.3?

**Comment by FabrizioRadica** [comment]
> 
> 
> Kick Pascal also crashes on WinUAE, so this is probably a compatibility issue. I think it was designed for Kickstart 1.3?

Nope, because works with FSUAE/WINUAE with KS3.1... maybe KS3.1.4?

**Comment by midwan** [comment]
Indeed, it works on 3.1 but crashes on 3.9 on WinUAE.

**Comment by midwan** [comment]
And yet, it seems to work on a vanilla (non-RTG) OS 3.1.4 installation on WinUAE.

**Comment by midwan** [comment]
And it also works on 3.1.4 on Amiberry as well, at least with the installation I had here: 
![image](https://user-images.githubusercontent.com/3877365/97846946-1204d480-1cef-11eb-849b-45a51dfb8891.png)

**Comment by FabrizioRadica** [comment]
> 
> 
> And it also works on 3.1.4 on Amiberry as well, at least with the installation I had here:
> ![image](https://user-images.githubusercontent.com/3877365/97846946-1204d480-1cef-11eb-849b-45a51dfb8891.png)

Ok mate, the problem is precisely RTG.
Seems to works only on non RTG screens (maybe not an Amiberry problem?)

**Comment by midwan** [comment]
I don't think so: the latest test I made above, using 3.1.4, also had RTG enabled. It's running at 800x600 using the uaegfx driver. :)

**Comment by FabrizioRadica** [comment]
> 
> 
> I don't think so: the latest test I made above, using 3.1.4, also had RTG enabled. It's running at 800x600 using the uaegfx driver. :)

For me, this task is closed :)
Really thanks for your job. 
I would like to help solve problems with Amiberry. I believe in your project.

:)
