### ISSUE TITLE
[ dev ] Missing RESUME button on panel and Uae-configuration problems (on dev and master)

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#707]
Hi :)
on the dev branch, did you forget the RESUME button?

Another problem.
Seems not works the CLI command uae-configuration floppy0 "/mnt/dietpi_userdata/AmigaADF/mydisk.adf" but on winuae, the same (with different path), it works.

Regards,
Fabrizio.

**Comment by midwan** [comment]
Not sure what you're talking about here. Could you please give specific steps to see?

**Comment by FabrizioRadica** [comment]
> 
> 
> Not sure what you're talking about here. Could you please give specific steps to see?

Problems:
1 - on Amiberry panel in (dev branch), can't see the Resume button but only Reset. 
2 - I whould like to use Uae-Configuration and the parameter floppy0, for use/insert an ADF Image, seems doesn't works.
other parameters like cachesize 8192 for JIT, for example, are working.

**Comment by midwan** [comment]
@FabrizioRadica 
* The Resume button is at the same location as the Start button. It's only visible when the emulation has started and it's possible to resume (i.e. you haven't made any configuration changes that require a Reset to apply). No changes regarding that have been made on the `dev` branch.
* please provide the exact command you used, so I can try to recreate this?

**Comment by FabrizioRadica** [comment]
> 
> 
> @FabrizioRadica
> 
>     * The Resume button is at the same location as the Start button. It's only visible when the emulation has started and it's possible to resume (i.e. you haven't made any configuration changes that require a Reset to apply). No changes regarding that have been made on the `dev` branch.
> 
>     * please provide the exact command you used, so I can try to recreate this?

Yes, sorry,
Use Show no GUI and create a default.uae. at the next restart, RESUME disappears.
![no resume](https://user-images.githubusercontent.com/1652242/97683341-ac1f0f80-1a98-11eb-9e6f-684695ec888f.jpg)
