### ISSUE TITLE
Fullscreen screen mode doesn't change monitor resolution

### ISSUE THREAD

**Issue by pakraider** [midwan/amiberry#708]
I'm using Amiberry 3.3 on an RPi4 (running Amibian). The system resolution is 1024x768 @ 60Hz, and my Amiga install is set to a 1024x768 RTG screenmode for Workbench. In the Amiberry display settings, I've set the Amiga screen to 640x480, with the fullscreen screen mode.

However, opening an Amiga screen (like running a game via WHDLoad) won't change the monitor resolution as expected. The monitor stays at 1024x768, and the native Amiga output is just scaled up.

**Comment by midwan** [comment]
@pakraider 
Are you running the Dispmanx version? If so, it's not possible to use that feature there.
This only works when using the SDL2 back-end, which can support it (along with windowed/full-window modes). Dispmanx is full-window always, I'm afraid.

**Comment by pakraider** [comment]
Ahh.. yeah I'm using Amibian so it's the Dispmanx version. I used to have some filesystem watchers and kludgy scripts that would allow the Amiga side to change the Pi's resolution. I guess I could clean that up a bit now with host-run. I'll give it a shot.

**Comment by midwan** [comment]
Thanks for confirming 👍
