### ISSUE TITLE
Warp/Wazp3D compatibility

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#709]
Hi, any possibility to play games like Quake3 on Amiberry or better, use or programming 3D with acceleration?
I had installed Wazp3D with StormMesa e various library but return me a ramlib guru $8000 00008.

Ciao!

**Comment by FabrizioRadica** [comment]
It seems to go to GURU with soft3d.library (on winuae it works).
![bug](https://user-images.githubusercontent.com/1652242/98169305-4d202700-1eec-11eb-861b-b7c69c7266bf.jpg)

**Comment by FabrizioRadica** [comment]
> 
> 
> It seems to go to GURU with soft3d.library (on winuae it works).
> ![bug](https://user-images.githubusercontent.com/1652242/98169305-4d202700-1eec-11eb-861b-b7c69c7266bf.jpg)

Hi, 
![124183013_10221685838329574_6458772836256451677_o](https://user-images.githubusercontent.com/1652242/98471912-bb683080-21ef-11eb-8a3d-66971c43adcc.jpg)

after various tests, now works very slow only with wazp3d.library-full (for real Amiga).
The problem is wazp3d.library and soft3d.library which should access soft3d.dll (WinUae).

screenshot from my FAmigaOS

**Comment by midwan** [comment]
There is no `soft3d.dll` on Linux however...

**Comment by FabrizioRadica** [comment]
> 
> 
> There is no `soft3d.dll` on Linux however...

Yes, i know (obviously) :) 
Is there any possibility to recompile it (or wrap it)?

**Comment by midwan** [comment]
I don't think so, that uses DirectX/Direct3D behind the scenes, which is Windows-specific.
We'd need to make a separate implementation to use SDL2's 3D back-end, if we wanted a truly portable multi-platform solution. But I don't have enough knowledge to implement that myself, at least not yet. :)

**Comment by FabrizioRadica** [comment]
> 
> 
> I don't think so, that uses DirectX/Direct3D behind the scenes, which is Windows-specific.
> We'd need to make a separate implementation to use SDL2's 3D back-end, if we wanted a truly portable multi-platform solution. But I don't have enough knowledge to implement that myself, at least not yet. :)

yes me too, i don't know SDL (and i know little about the linux world).
I tried to look at the source of Soft3D.dll and everything should be rewritten in SDL2 .... mmh ...
