### ISSUE TITLE
[dev] Keyboard as Joystick right arrow brings up GUI

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#711]
Hi,
I set on Amiberry panel "INPUT / Port 1: Keyboard as Joystick [Default]" and when I back on Amiga, if I press RIGHT ARROW on keyboard, it back on Amiberry panel (like F12 button)

Amiberry dev 2020/11/02
Ciao!

**Comment by midwan** [comment]
Indeed, this seems like a bug. Thanks for finding it!
