### ISSUE TITLE
[dev] Fblit/Ftext causes problem in reboot

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#713]
Hi :) 
After your last dev update (2020-11-04), Amiberry seems to boot but, when i reset (with CTRL+A+A), the sound of floppy drive play faster and than it freeze, as you can see on video.
(Sorry for my bad english).

http://www.radicadesign.com/amiga/bug20201105.mp4

**Comment by midwan** [comment]
Thanks for the video.
So far, I cannot recreate the same problem here. I've tested it with my 3.1.4 installation, and resetting through the Keyboard seems to work as expected.
I'll keep trying a few more combinations to see if something specific triggers it.

Meanwhile, could you confirm if this is not happening with earlier versions? Ideally, could you find the specific commit that changes this behavior for you?

**Comment by FabrizioRadica** [comment]
> 
> 
> Thanks for the video.
> So far, I cannot recreate the same problem here. I've tested it with my 3.1.4 installation, and resetting through the Keyboard seems to work as expected.
> I'll keep trying a few more combinations to see if something specific triggers it.
> 
> Meanwhile, could you confirm if this is not happening with earlier versions? Ideally, could you find the specific commit that changes this behavior for you?

Hi :)
The problem seems to be related to the PICASSO library. I'm investigating.
If I reset BEFORE RTG starts, it manages to boot.
very strange .. and it does it in all versions of Amiberry (even 3.3)

**Comment by FabrizioRadica** [comment]
> 
> 
> > Thanks for the video.
> > So far, I cannot recreate the same problem here. I've tested it with my 3.1.4 installation, and resetting through the Keyboard seems to work as expected.
> > I'll keep trying a few more combinations to see if something specific triggers it.
> > Meanwhile, could you confirm if this is not happening with earlier versions? Ideally, could you find the specific commit that changes this behavior for you?
> 
> Hi :)
> The problem seems to be related to the PICASSO library. I'm investigating.
> If I reset BEFORE RTG starts, it manages to boot.
> very strange .. and it does it in all versions of Amiberry (even 3.3)

I confirm... uninstalling P96.. it reboot again...
VERY strange...

**Comment by FabrizioRadica** [comment]
> 
> 
> > > Thanks for the video.
> > > So far, I cannot recreate the same problem here. I've tested it with my 3.1.4 installation, and resetting through the Keyboard seems to work as expected.
> > > I'll keep trying a few more combinations to see if something specific triggers it.
> > > Meanwhile, could you confirm if this is not happening with earlier versions? Ideally, could you find the specific commit that changes this behavior for you?
> > 
> > 
> > Hi :)
> > The problem seems to be related to the PICASSO library. I'm investigating.
> > If I reset BEFORE RTG starts, it manages to boot.
> > very strange .. and it does it in all versions of Amiberry (even 3.3)
> 
> I confirm... uninstalling P96.. it reboot again...
> VERY strange...

Strange Bug Mate...
I did a clean install of P96 3.0 (bought it to test) and now it works.
Before, I had 2.0Aminet (and it worked) and after the last update, it gave me today's problems.
I don't know why but I'm keeping an eye on it.

**Comment by midwan** [comment]
Hm, in the `dev` version there was an update to support P96 v3.0. I tested it with v3.0 and earlier versions and didn't notice any problems, but perhaps I missed something. The earlier versions I tested were not the Aminet one, but the earlier iComp versions (2.4.6). 

Perhaps this only occurs with the Aminet version. I'll test it a bit more to find out.

**Comment by FabrizioRadica** [comment]
> 
> 
> > > > Thanks for the video.
> > > > So far, I cannot recreate the same problem here. I've tested it with my 3.1.4 installation, and resetting through the Keyboard seems to work as expected.
> > > > I'll keep trying a few more combinations to see if something specific triggers it.
> > > > Meanwhile, could you confirm if this is not happening with earlier versions? Ideally, could you find the specific commit that changes this behavior for you?
> > > 
> > > 
> > > Hi :)
> > > The problem seems to be related to the PICASSO library. I'm investigating.
> > > If I reset BEFORE RTG starts, it manages to boot.
> > > very strange .. and it does it in all versions of Amiberry (even 3.3)
> > 
> > 
> > I confirm... uninstalling P96.. it reboot again...
> > VERY strange...
> 
> Strange Bug Mate...
> I did a clean install of P96 3.0 (bought it to test) and now it works.
> Before, I had 2.0Aminet (and it worked) and after the last update, it gave me today's problems.
> I don't know why but I'm keeping an eye on it.

Another test.
- P96 3.0 clean installation and reboot.
Resetting working but.. every program with screen custom, like Protracker, PPaint, Sysinfo et similia... crashes...

**Comment by FabrizioRadica** [comment]
> 
> 
> Hm, in the `dev` version there was an update to support P96 v3.0. I tested it with v3.0 and earlier versions and didn't notice any problems, but perhaps I missed something. The earlier versions I tested were not the Aminet one, but the earlier iComp versions (2.4.6).
> 
> Perhaps this only occurs with the Aminet version. I'll test it a bit more to find out.

After only "few" hours... I found the problem...
**VISUALPREFS!!!!** 

**Symptoms:**
- Problem on reboot (like my video) - P96 <3.0
- Problems when open custom screens like Protracker, Sysinfo, PPaint etc. - P96 3.0

Problem found in Amiberry 3.3 and 3.4b and P96 2.0Aminet / IComp 2.4+ and 3.0

Visualprefs probably writes badly in memory, creating conflicts with P96.
On Winuae, however, this does not happen (same configuration as Workbench and kickstart on Amiberry).

Hope to help you :)
Ciao!

**Comment by FabrizioRadica** [comment]
> 
> 
> > Hm, in the `dev` version there was an update to support P96 v3.0. I tested it with v3.0 and earlier versions and didn't notice any problems, but perhaps I missed something. The earlier versions I tested were not the Aminet one, but the earlier iComp versions (2.4.6).
> > Perhaps this only occurs with the Aminet version. I'll test it a bit more to find out.
> 
> After only "few" hours... I found the problem...
> **VISUALPREFS!!!!**
> 
> **Symptoms:**
> 
>     * Problem on reboot (like my video) - P96 <3.0
> 
>     * Problems when open custom screens like Protracker, Sysinfo, PPaint etc. - P96 3.0
> 
> 
> Problem found in Amiberry 3.3 and 3.4b and P96 2.0Aminet / IComp 2.4+ and 3.0
> 
> Visualprefs probably writes badly in memory, creating conflicts with P96.
> On Winuae, however, this does not happen (same configuration as Workbench and kickstart on Amiberry).
> 
> Hope to help you :)
> Ciao!

Also FBLIT/FTEXT...

**Comment by FabrizioRadica** [comment]
> 
> 
> > > Hm, in the `dev` version there was an update to support P96 v3.0. I tested it with v3.0 and earlier versions and didn't notice any problems, but perhaps I missed something. The earlier versions I tested were not the Aminet one, but the earlier iComp versions (2.4.6).
> > > Perhaps this only occurs with the Aminet version. I'll test it a bit more to find out.
> > 
> > 
> > After only "few" hours... I found the problem...
> > **VISUALPREFS!!!!**
> > **Symptoms:**
> > ```
> > * Problem on reboot (like my video) - P96 <3.0
> > 
> > * Problems when open custom screens like Protracker, Sysinfo, PPaint etc. - P96 3.0
> > ```
> > 
> > 
> > Problem found in Amiberry 3.3 and 3.4b and P96 2.0Aminet / IComp 2.4+ and 3.0
> > Visualprefs probably writes badly in memory, creating conflicts with P96.
> > On Winuae, however, this does not happen (same configuration as Workbench and kickstart on Amiberry).
> > Hope to help you :)
> > Ciao!
> 
> Also FBLIT/FTEXT...

Hi and good morning (ZZZzzzz...) :)
Final Verdict... is not VisualPrefs... but FBLIT/FTEXT conflict.
So, it could be Amiberry or P96? 
On WInUae it works for example.

Ciao!

**Comment by midwan** [comment]
I would be surprised if it was VisualPrefs, since that runs in AmiKit as well and I didn't notice such problems there.

I haven't tried fblit/ftext, but I guess they do some nasty stuff in the background, which cause Amiberry to fail this way.
I'll see if I can recreate it first, then we go from there.

Thanks for the help!

**Comment by FabrizioRadica** [comment]
> 
> 
> I would be surprised if it was VisualPrefs, since that runs in AmiKit as well and I didn't notice such problems there.
> 
> I haven't tried fblit/ftext, but I guess they do some nasty stuff in the background, which cause Amiberry to fail this way.
> I'll see if I can recreate it first, then we go from there.

With FBLIT/FTEXT these symptoms remain:

* Problem on reboot (like my video) - P96 <3.0
* Problems when open custom screens like Protracker, Sysinfo, PPaint etc. - P96 3.0
Problem found in Amiberry 3.3 and 3.4b and P96 2.0Aminet / IComp 2.4+ and 3.0

> 
> Thanks for the help!

Nop, i'm very happy to help you :)

**Comment by midwan** [comment]
@FabrizioRadica 
Is this still an issue for you, with the current `dev` ?

**Comment by FabrizioRadica** [comment]
> 
> 
> @FabrizioRadica
> Is this still an issue for you, with the current `dev` ?
I have to take a test. :)

**Comment by FabrizioRadica** [comment]
> 
> 
> @FabrizioRadica
> Is this still an issue for you, with the current `dev` ?

Ok Mate, seems to works fine now :)

**Comment by midwan** [comment]
Thanks for confirming!
