### ISSUE TITLE
RPi scaling kernel 

### ISSUE THREAD

**Issue by tednilsen** [midwan/amiberry#716]
Hey man, just wanne inform you that I've made a launch script for my amiberry to set the RPi scaling kernel and restore it when amiberry quits.
You can do whatever you wanne and include it also - do what you like :)
Thank you for Amiberry, awesome work! 

https://github.com/tednilsen/scripts/blob/main/scale-rpi.sh

**Comment by midwan** [comment]
@tednilsen 
Thanks for this! :)
