### ISSUE TITLE
Uae-configuration can't load ADF from CLI

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#717]
Hi,
uae-configuration floppy0="game.adf" or uae-coniguration floppy0 game.adf seems doesn't works.
On WinUae it works.

Test:
- put an ADF on any folder then call it from cli with: uae-configuration floppy0 "yourpath/your adf".
other params like cachesize or cpu, works fine.

Ciao!

**Comment by midwan** [comment]
This seems to work as expected, with the latest `dev` at least.
Just make sure you're using the full path to your adf file...

![Amiberry - Amiberry_2020-12-28_18-21-48](https://user-images.githubusercontent.com/3877365/103232008-a3807380-4939-11eb-853d-8ae4145a9a63.png)
