### ISSUE TITLE
[ dev ] Can't Compile PLATFORM=pi64

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#719]
Hi,
i had try to comple pi64 (and pi64-dispmanx) but give me some errors.
![1604931971712](https://user-images.githubusercontent.com/1652242/98553751-3c7f0080-22a0-11eb-8024-36be75e46ddd.jpg)

**Comment by solskogen** [comment]
What OS are you on?

**Comment by FabrizioRadica** [comment]
> 
> 
> What OS are you on?

DietPI

**Comment by midwan** [comment]
You need a 64-bit distro to compile the 64-bit binaries. I don't think DietPi has a 64-bit version yet.

You can use Ubuntu or Manjaro, for the RPI4. ;)

**Comment by solskogen** [comment]
But not 64bit, right? Could you post the output of "uname -a" please (no
screenshot)

**Comment by solskogen** [comment]
That's not entirely correct.
https://dietpi.com/downloads/images/testing/DietPi_RPi-ARMv8-Buster.7z

**Comment by FabrizioRadica** [comment]
![1604934158416](https://user-images.githubusercontent.com/1652242/98557969-2d4e8180-22a5-11eb-9e75-b62d6b78ac0d.jpg)

**Comment by solskogen** [comment]
You're running 32bit, so it won't work.
