### ISSUE TITLE
Document full list of dependencies

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#72]
Hello Midwan,

First of all this is gonna be quite long and maybe totally stupid and I'm sorry for it if this is the case (I'm not very good in linux)

So I'm currently currently developping some custom solution to add Amiga emulator to Recalbox which is a retrogaming distribution, kinda Retropie but instead of being based on Rasbian it's buit from scratch using buildroot. So on this distribution there's no package manager and no way without rebuilding entirely the whole thing to add the dependencies needed by amiberry other than manuallly.

For my solution I was using Chips UAE4ARM and I needed the following libraries to launch it : https://github.com/Voljega/amiga4recalbox/tree/master/libs

Seeing all the good things going on on amiberry (we spoke a little on Raspbery forum if you remember) I decided to switch to  amiberry.

So if I just use your executable file without adding any other dependency amiberry launches but the GUI doesn't display anymore, something is missing

As as I have no access to a package manager on my Recalbox, I installed your required dependencies (sudo apt-get install libsdl1.2debian libsdl-image1.2 libsdl-gfx1.2-5 libsdl-ttf2.0-0 libmpg123-0 libguichan-sdl-0.8.1-1 libxml2) on a Raspbian and then using sudo dpkg -L packagename I retrieve all the libs installed by those dependencies which gives us only the following additional libs to use (I didn't overwrite the one I had already installed for uae4arm) 
[amiberry explicit dependencies](http://imgur.com/a/L5LyP)

But then amiberry crashes and doesn't launch anymore, saying explicitely a lot of dependencies are missing (well you have to add them one by one to see the next one missing !)

So after a while I managed to add all the required missing dependencies and there are a lot.
[missing dependencies](http://imgur.com/a/L5LyP)
and then everything works fine !

Those dependencies seem to be part of Raspbian standard installation so I figured maybe they were hidden to your build process, well at least they are hidden for someone trying to do something manually outside a standard distribution like me or without a package manager.

Anyway, I understand my way of doing is pretty dirty to say the least, and again I don't know much about Linux but I figured maybe it would be interesting to file some issue page, even If i'm totally out of it ?

and by the way the emulator is great, the big GUI is a nice addition, so are the custom keys/buttons and I can't wait to see the next steps !

**Comment by midwan** [comment]
@Voljega 
Wow, thanks for your effort in documenting these. It's certainly useful to have, especially if you want to use it on systems like the one you described.

I'll make sure to add them in the readme, just in case others need it as well. 

Thanks!

**Comment by midwan** [comment]
For the record, Amiberry SDL1.x doesn't use any extra libraries than UAE4Arm-rpi. They are identical in their requirements.

This changes with Amiberry SDL2 however, since I have switched to SDL2 libraries there. Besides the SDL framework, the rest of the dependencies are also the same there.

In your list of "explicit dependencies", those mentioned are part of SDL1.2, libmpg123 and libxml2. All of which are required by Amiberry and UAE4Arm-rpi, at least in their current versions.

The list with the "missing dependencies" are provided in Raspbian out-of-the-box as you said, so they were not really "extra" dependencies in the build process and thus were not documented. I will add them in a list of course.

**Comment by midwan** [comment]
@Voljega 
Coming back to this after a long time... :)

Do you have a text-based list of dependencies that I could use? The two links above point to the same image, which is a jpg file.
Since we now have a Wiki page, we could add them in a special section there.

**Comment by Voljega** [comment]
Sadly I have none but I'm willing to type it if you need it on your wiki if
younpoint me toward the page tonuse or I can send you that as a text file

Le 20 janv. 2018 10:15, "Dimitris Panokostas" <notifications@github.com> a
écrit :

**Comment by midwan** [comment]
@Voljega 
Sure, the wiki is at https://github.com/midwan/amiberry/wiki or you can attach a file in this issue page if you prefer that.

**Comment by Voljega** [comment]
Here they are :

[dependencies.txt](https://github.com/midwan/amiberry/files/1649595/dependencies.txt)

**Comment by midwan** [comment]
@Voljega 
Thank you! I've added this page https://github.com/midwan/amiberry/wiki/Full-list-of-dependencies-(SDL1-version)

Closing this issue for now then...
