### ISSUE TITLE
Booting from a .hdf with JIT activated : works from SSH, not from EmulationStation

### ISSUE THREAD

**Issue by Yserra** [midwan/amiberry#721]
Hi, 
This question has already been posted on the Retropie Forum a few days ago, but nobody found the answer so far. You're my last hope. (https://retropie.org.uk/forum/topic/28400/amiberry-is-jit-whdload-broken-on-rpi4)

Under Retropie 4.7.1 system, with Amiberry 3.3 (installed from binaries), I want to run an emulated Amiga4000/040 with JIT=ON and an "Amiga4000.hdf" hardfile image. I have this hardfile and my custom configuration installed as follow:
 
~/RetroPie/roms/amiga/Amiga4000.hdf
~/RetroPie/roms/amiga/Amiga4000.uae

Everything works as expected when I run Amiberry from the command line, like this:
`cd /opt/retropie/emulators/amiberry`
`./amiberry -f ~/RetroPie/roms/amiga/Amiga4000.uae -G`

But if I try to run the item "Amiga4000" from the EmulationStation panel, Amiberry launches (I see the virtual LEDs of the disks at the bottom of the screen) and quits immediately. 

When I deactivate the JIT parameter from my Amiga4000.uae configuration, then, the "Amiga4000" item from EmulationStation works: it boots this configuration, but obviously the emulated system is faaaar sloooower than with JIT. 

When I activate the JIT parameter and boot from an ADF: it works too, from EmulationStation, but obviously I would prefer booting from my complete Workbench 3.1 hardfile. 

What could be the problem that prevent EmulationStation to launch a JIT-configured Amiga with an .HDF ? 

Many thanks for your answer.

**Comment by midwan** [comment]
Could you please share your config file here, so I can try to recreate this?
I can use my own hdf to boot it, but I'm more interested in the rest of the options.

**Comment by Yserra** [comment]
Yes, sure! Here is my Amiga4000.uae file:

config_description=Amiga 4000
config_hardware=true
config_host=true
config_version=4.4.0
config_hardware_path=
config_host_path=
config_all_path=
amiberry.rom_path=./
amiberry.floppy_path=./
amiberry.hardfile_path=./
amiberry.cd_path=./
; 
; *** Controller/Input Configuration
; 
joyport0=mouse
joyport0_autofire=none
joyport0_friendlyname=Mouse
joyport0_name=MOUSE0
; 
joyport1=joy1
joyport1_autofire=none
joyport1_friendlyname=MY-POWER CO.,LTD. USB Joystick
joyport1_name=JOY1
; 
; 
; 
input.joymouse_speed_analog=2
input.joymouse_speed_digital=10
input.joymouse_deadzone=33
input.joystick_deadzone=33
input.analog_joystick_multiplier=18
input.analog_joystick_offset=-5
input.mouse_speed=100
input.autofire_speed=600
input.autoswitch=1
kbd_lang=us
; 
; *** Host-Specific
; 
amiberry.gfx_auto_height=true
amiberry.gfx_correct_aspect=0
amiberry.kbd_led_num=-1
amiberry.kbd_led_scr=-1
amiberry.scaling_method=-1
amiberry.allow_host_run=false
amiberry.use_analogue_remap=false
amiberry.use_retroarch_quit=true
amiberry.use_retroarch_menu=true
amiberry.use_retroarch_reset=false
amiberry.active_priority=1
amiberry.inactive_priority=0
amiberry.minimized_priority=0
amiberry.minimized_input=0
; 
; *** Common / Paths
; 
use_gui=no
show_leds=true
show_leds_rtg=true
kickstart_rom_file=/home/pi/RetroPie/BIOS/kick310-A4000.rom
kickstart_ext_rom_file=
ide_mb_rom_file=:ENABLED
flash_file=
cart_file=
rtc_file=
kickshifter=true
; 
; *** Floppy Drives
; 
floppy_volume=33
floppy0=
floppy1=
floppy2=
floppy3=
nr_floppies=2
floppy_speed=100
; 
; *** Hard Drives
; 
hardfile2=rw,DH0:/home/pi/RetroPie/roms/amiga/Amiga4000.hdf,32,1,2,512,0,,uae0
uaehf0=hdf,rw,DH0:/home/pi/RetroPie/roms/amiga/Amiga4000.hdf,32,1,2,512,0,,uae0
scsi=true
; 
; *** CD / CD32
; 
cd_speed=100
; 
; *** Display / Screen Setup
; 
gfx_framerate=1
gfx_width=720
gfx_height=512
gfx_top_windowed=0
gfx_left_windowed=0
gfx_width_windowed=720
gfx_height_windowed=512
gfx_width_fullscreen=1280
gfx_height_fullscreen=1024
gfx_refreshrate=50
gfx_refreshrate_rtg=50
gfx_backbuffers=2
gfx_backbuffers_rtg=1
gfx_vsync=false
gfx_vsyncmode=normal
gfx_vsync_picasso=false
gfx_vsyncmode_picasso=normal
gfx_lores=false
gfx_resolution=hires
gfx_lores_mode=normal
gfx_flickerfixer=false
gfx_linemode=none
gfx_fullscreen_amiga=fullwindow
gfx_fullscreen_picasso=fullwindow
gfx_center_horizontal=smart
gfx_center_vertical=smart
gfx_colour_mode=16bit
gfx_blacker_than_black=false
gfx_api=directdraw
gfx_api_options=hardware
; 
; *** CPU options
; 
cpu_speed=max
cpu_throttle=0.0
cpu_type=68040
cpu_model=68040
fpu_model=68040
cpu_compatible=false
cpu_24bit_addressing=false
cpu_data_cache=false
cpu_cycle_exact=false
cpu_memory_cycle_exact=false
blitter_cycle_exact=false
cycle_exact=false
fpu_strict=false
comp_trustbyte=direct
comp_trustword=direct
comp_trustlong=direct
comp_trustnaddr=direct
comp_nf=true
comp_constjump=true
comp_flushmode=soft
compfpu=true
comp_catchfault=true
cachesize=16384
; 
; *** Memory
; 
z3mapping=real
fastmem_size=0
a3000mem_size=0
mbresmem_size=128
z3mem_size=128
z3mem_start=0x40000000
bogomem_size=0
gfxcard_hardware_vblank=false
gfxcard_hardware_sprite=false
gfxcard_multithread=false
gfxcard_size=16
gfxcard_type=ZorroIII
chipmem_size=16
rtg_modes=0x112
; 
; *** Chipset
; 
immediate_blits=true
fast_copper=true
ntsc=false
chipset=aga
chipset_refreshrate=59.280407
collision_level=sprites
chipset_compatible=A4000
ksmirror_e0=false
fatgary=0
ramsey=15
z3_autoconfig=true
unmapped_address_space=zero
ide=a4000
; 
; *** Sound Options
; 
sound_output=normal
sound_channels=stereo
sound_stereo_separation=7
sound_stereo_mixing_delay=0
sound_max_buff=16384
sound_frequency=44100
sound_interpol=anti
sound_filter=emulated
sound_filter_type=standard
sound_volume=0
sound_volume_paula=0
sound_volume_cd=20
sound_volume_ahi=0
sound_volume_midi=0
sound_volume_genlock=0
sound_auto=true
sound_cdaudio=false
sound_stereo_swap_paula=false
sound_stereo_swap_ahi=false
; 
; *** Misc. Options
; 
parallel_on_demand=false
serial_on_demand=false
serial_hardware_ctsrts=true
serial_direct=false
uaeserial=false
sana2=false
bsdsocket_emu=true
synchronize_clock=false
maprom=0x0
uaeboard=min
parallel_postscript_emulation=false
parallel_postscript_detection=false
ghostscript_parameters=
parallel_autoflush=5
; 
; *** WHDLoad Booter. Options
; 
whdload_slave=
whdload_showsplash=false
whdload_buttonwait=false
whdload_custom1=0
whdload_custom2=0
whdload_custom3=0
whdload_custom4=0
whdload_custom5=0
whdload_custom=

**Comment by midwan** [comment]
Could you try using only Z3 RAM, and no Motherboard RAM?
We've had some issues when using Motherboard RAM with JIT in the past, in some scenarios - perhaps it's something similar in this case also.

**Comment by Yserra** [comment]
I tried several scenarios with Z3 only Fast RAM (no motherboard/CPU RAM, but with more or less Chip/Slow/RTG RAM). At the end, the result is the same: Amiberry with JIT=ON quits when launched from EmulationStation. 
But I noticed several differences, when I have Z3 RAM only:

- a longer disk activity, as shown by the HD LED on the bottom of the screen (but Amiberry quits before showing Workbench)
- (when run from the command line) Amiberry brutally quits when I want to show its GUI with F12 (it shows its GUI when I have other Fast RAM)
- and there is much more text in the terminal when I run from the command line (I do it from ssh). Here is what Amiberry writes: 

failed to export dumb buffer: Permission denied
Failed to create scanout resource
INFO: --- New exception ---
INFO: Error in compiled code.
INFO: JIT: Address bank: NONE, address c0000168
INFO: JIT: ARM opcode = 0xe795200a
INFO: long load to register r2
INFO: New value in r2: 0x00000000 (old: 0x5a0100c0)
INFO: JIT: Deleted trigger (0xaa6ef4bc < 0xaa6ef42c < 0xaa6ef4d4) 0x60024cb8
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = e0000168
INFO: r0  = 0x00000500
INFO: r1  = 0x00000006
INFO: r2  = 0x00000000
INFO: r3  = 0x00000000
INFO: r4  = 0x03a98678
INFO: r5  = 0xc0000168
INFO: r6  = 0xc000015a
INFO: r7  = 0x40000484
INFO: r8  = 0x40024520
INFO: r9  = 0x40024530
INFO: r10 = 0x20000000
INFO: FP  = 0x03a98678
INFO: IP  = 0x40024522
INFO: SP  = 0xbea7e30c
INFO: LR  = 0x001d3174
INFO: PC  = 0xaa6ef430
INFO: CPSR = 0x20000010
INFO: Fault Address = 0xe0000168
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x0000020f
INFO: Old Mask = 0x00000000
INFO: LR - 0x001D3174: <(null)> (/opt/retropie/emulators/amiberry/amiberry)
INFO: Stack trace:
INFO: 0x00188134 <(null) + 0x00188134> (/opt/retropie/emulators/amiberry/amiberry)
INFO: 0xb6771130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: IP out of range
INFO: Stack trace (non-dedicated):
INFO: /opt/retropie/emulators/amiberry/amiberry() [0x18824c]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6771130]
INFO: End of stack trace.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: Error in compiled code.
INFO: JIT: Address bank: NONE, address c0000144
INFO: JIT: ARM opcode = 0xe795200a
INFO: long load to register r2
INFO: New value in r2: 0x00000000 (old: 0x360100c0)
INFO: JIT: Deleted trigger (0xaa6ef824 < 0xaa6ef794 < 0xaa6ef83c) 0x60024cb8
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = e0000144
INFO: r0  = 0x5060cbe8
INFO: r1  = 0x00000069
INFO: r2  = 0x00000000
INFO: r3  = 0x60024cb8
INFO: r4  = 0x03a98678
INFO: r5  = 0xc0000144
INFO: r6  = 0xc0000136
INFO: r7  = 0x400004c8
INFO: r8  = 0x40024520
INFO: r9  = 0x40024530
INFO: r10 = 0x20000000
INFO: FP  = 0x03a98678
INFO: IP  = 0x00000000
INFO: SP  = 0xbea7e30c
INFO: LR  = 0x001d3174
INFO: PC  = 0xaa6ef798
INFO: CPSR = 0x60000010
INFO: Fault Address = 0xe0000144
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x0000020f
INFO: Old Mask = 0x00000000
INFO: LR - 0x001D3174: <(null)> (/opt/retropie/emulators/amiberry/amiberry)
INFO: Stack trace:
INFO: 0x00188134 <(null) + 0x00188134> (/opt/retropie/emulators/amiberry/amiberry)
INFO: 0xb6771130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: IP out of range
INFO: Stack trace (non-dedicated):
INFO: /opt/retropie/emulators/amiberry/amiberry() [0x18824c]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6771130]
INFO: End of stack trace.
INFO: --- end exception ---
Internal error; file src/osdep/gui/main_window.cpp, line 990
Abandon

(the last two lines appear when I press F12). 

To compare, here is what Amiberry usually writes in the terminal when it is launched with JIT + motherboard ou CPU RAM, from the command line: 

failed to export dumb buffer: Permission denied
Failed to create scanout resource
INFO: --- New exception ---
INFO: Error in compiled code.
INFO:   Stupid kickstart detection for size of ramsey_high at 0x10000004.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: Error in compiled code.
INFO:   Stupid kickstart detection for size of ramsey_high at 0x10000000.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: Error in compiled code.
INFO:   Stupid kickstart detection for size of ramsey_high at 0x10000000.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: Error in compiled code.
INFO:   Stupid kickstart detection for size of ramsey_high at 0x10000000.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: Error in compiled code.
INFO:   Stupid kickstart detection for size of ramsey_high at 0x10000004.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: Error in compiled code.
INFO:   Stupid kickstart detection for size of ramsey_high at 0x10000000.
INFO: --- end exception ---

**Comment by midwan** [comment]
The crash above is an exception, while trying to open the GUI font. Normally, that is located in `data/AmigaTopaz.ttf` from where the binary was started. If it failed to open it, it is supposed to throw such a message and quit (although it also fails to output the proper error message, I guess what's what the `failed to export dumb buffer: Permission denied
Failed to create scanout resource` messages refer to)

**Comment by midwan** [comment]
Or actually, the messages should be output to the logfile - did you have logging enabled?
If you did, that would explain the permission denied errors: it probably doesn't have permissions to create the logfile or write to it.

**Comment by Yserra** [comment]
I just checked in the Paths panel: Logging is (and was) disable.

**Comment by Yserra** [comment]
By the way, since you mentioned it, I just tried to activate logging. Whether I run Amiberry from EmulationStation, or from the command line, I see no amiberry.log file in the /opt/retropie/emulators/amiberry/ folder.

**Comment by midwan** [comment]
That's because the location is not writable, unless you change the permissions. ;)

**Comment by Yserra** [comment]
Actually, if I understand correctly, there is a log: the Runcommand script, that EmulationStation uses to launch Amiberrry, creates a /dev/shm/runcommand.log file. 
Here is what this log says when I try to run my Amiga4000.uae JIT+hardfile configuration from EmulationStation:

/dev/shm/runcommand.log
Parameters: 
Executing: /opt/retropie/emulators/amiberry/amiberry.sh auto "/home/pi/RetroPie/roms/amiga/Amiga4000.uae"
INFO: --- New exception ---
INFO: Error not in JIT code.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = -6
INFO: info.si_addr = 00000efd
INFO: r0  = 0x00000000
INFO: r1  = 0xbefe546c
INFO: r2  = 0x00000000
INFO: r3  = 0x00000008
INFO: r4  = 0xb6f3a968
INFO: r5  = 0x0000000b
INFO: r6  = 0xbefe546c
INFO: r7  = 0x000000af
INFO: r8  = 0x06f00000
INFO: r9  = 0x00100000
INFO: r10 = 0x20000000
INFO: FP  = 0x03a98678
INFO: IP  = 0x00000000
INFO: SP  = 0xbefe5468
INFO: LR  = 0x00000000
INFO: PC  = 0xb6d278ec
INFO: CPSR = 0x00000010
INFO: Fault Address = 0x26f00004
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x00000206
INFO: Old Mask = 0x00000000
INFO: LR - 0x00000000: symbol not found
INFO: Stack trace:
INFO: 0x00188134 <(null) + 0x00188134> (./amiberry)
INFO: 0xb66f4130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: IP out of range
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x18824c]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb66f4130]
INFO: End of stack trace.
INFO: --- end exception ---
~

does it sound familiar to you?

**Comment by midwan** [comment]
That the generic exception handler we have in place.
But I don't know what caused the exception yet, especially if I cannot recreate it here to try and figure it out...

We'll see if I can find anything more about this.

**Comment by Yserra** [comment]
Thank you for your perseverance.
I would especially like to identify if this is the normal behavior or if this behavior only exists on my configuration, because I would have changed a setting, or a Linux permission, or anything without remembering it. 
- I'm using the regular Retropie Distribution for Raspberry Pi 4B, here: https://github.com/RetroPie/RetroPie-Setup/releases/download/4.7.1/retropie-buster-4.7.1-rpi4_400.img.gz
- I'm using this common Amiga hardfile: http://classicwb.abime.net/classicweb/downloadp96.htm
- I put this hardfile in Retropie with this recommended path: ~/Retropie/roms/amiga/Amiga4000.hdf
- I installed the pre-compiled Amiberry binaries from the regular Retropie menu. 
- I created a custom configuration with JIT + 68040 + 128MB onboard RAM + 16GB RTG RAM + the downloaded hardfile as DH0: and saved this configuration with this recommended path: ~/Retropie/roms/amiga/Amiga4000.uae

Amiberry launches and quits when I just select the "Amiga4000" item from EmulationStation -> it shouldn't!!

And what is really a headache is that Amiberry launches as it should when I "cd" to its binary folder and run any of these command lines:
./amiberry -f ~/Retropie/roms/amiga/Amiga4000.uae -G
./amiberry --config ~/Retropie/roms/amiga/Amiga4000.uae -G
./amiberry.sh auto ~/Retropie/roms/amiga/Amiga4000.uae

All this looks like a simple path issue.
You mentioned some permissions that could be changed. I'm not sure to understand what you meant. But this could be the solution, couldn't it be?

Many thanks.

**Comment by midwan** [comment]
I have a RetroPie installation here, so I'll try to recreate the same thing and see if I can get the same results.
I'll get back to you with more details once I have completed some more tests.

Meanwhile, have you tried getting the latest Amiberry version from source? Just in case...

**Comment by Yserra** [comment]
I just tried to compile/update Amiberry from source - from the dedicated menu in RetroPie - but the result is the same. By the way, I'm not sure Retropie gets your latest source. When I go to the About panel, I still have the 3.3 version from 2020-09-17.

**Comment by midwan** [comment]
@Yserra 
That's the current stable version, so it's correct. v3.4b is not released yet, and can only be compiled from the `dev` branch until that happens. It's work-in-progress. ;)

**Comment by nudgerselby** [comment]
I can also recreate this issue with Amiberry v3.3 and Retropie 4.7.1. I happens both from within ES and the command line.  

My WHD games will no longer load (boot loop) if JIT=ON and Z2 fast memory is used. Changing the Amiberry config to disable Z2 memory OR disabling JIT resolves the issue but I have over 700 games in my collection (on USB) so I would like to see if this gets resolved before make any mass config changes.  

I went back and tried some of my earlier Retropie  images with Amiberry versions prior to v3.2 and these seem to work fine with both Z2 memory and JIT enabled for WHD games.  The issue seems to have occurred with post v3.2 Amiberry versions ? 

Interestingly I have never had any success with Amiberry running AmigaOS hard disk images with JIT=ON from the command line or ES.  I use a very similar setup described above for the Amiga400.uae config.  To get it working I disable JIT - slower but to works.

**Comment by Yserra** [comment]
Hi @midwan, 
Just to tell you I finally succeed creating a logfile from Amiberry. What sounds weird is I had to _chmod ugo+rwx /opt/retropie/emulators/amiberry_  to get an _amiberry.log_. This folder belongs to root user. The amiberry.log is created by the pi user. 

So, I first created a logfile when I run Amiberry with HDF + JIT from the command line, as the pi user (the way it works).
Then I created a logfile when I run Amiberry with HDF + JIT from EmulationStation (the way it quits quickly) (I don't know which Linux user launches Amiberry that way). 

The two log files are exactly the same, but the second one is shorter, it stops after: 
`Memory map after autoconfig:`

The first one goes on:
`Memory map after autoconfig:
filesystem: diagentry 08000098 configdev 000015d0
SNDRATE 313.0*227.0*49.920410=3546895.062012
PAL mode V=49.9204Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
SNDRATE 313.0*227.0*49.920410=3546895.062012
PAL mode V=49.9204Hz H=15625.0879Hz (227x312+1) IDX=10 (PAL) D=0 RTG=0/0
RTGFREQ: 312*49.9204 = 15575.1680 / 60.0 = 259
Mounting uaehf.device:0 0 (0):
FS: mounted HDF unit DH0 (0000-1f400000, /home/pi/RetroPie/roms/amiga/Amiga4000.hdf)
RDB: fakefilesys, trying to load '/opt/retropie/emulators/amiberry/kickstarts/FastFileSystem', dostype 0x444F5301 (DOS\1)
RDB: filesys not found, mounted without forced filesys
uaegfx.card 3.4 init @0800E3FC
P96 RESINFO: 0800E48A-08010CCA (214,10304)
Creating UAE bsdsocket.library 4.1
`
and so on... 
I hope it could help...

**Comment by Yserra** [comment]
Hi @midwan,
Just to add a new information I just realized: actually, it doesn't work neither from the terminal console on the Pi itself. All my success were when i run the command line from SSH (from my Mac). That's becoming really weird.

So: 
/opt/retropie/emulators/amiberry/amiberry.sh auto "/home/pi/RetroPie/roms/amiga/Amiga4000.uae 
...runs (on the Pi, obviously) the expected AmigaOS 3.1 environment with JIT and a .HDF hardfile when typed from SSH
...Or quits when typed from the Raspberry Pi terminal. And what appears then on screen is almost the same as the runcommand.sh error log I previously notified, the "generic exception handler" you mentioned (the address mentioned are not exactly the same).

**Comment by midwan** [comment]
@Yserra 
I've just tested this scenario with the current `dev` version, but I can't recreate it so far.
Here's what I did, exactly:

- Latest RetroPie on an RPI3
- Fully updated system (using `sudo apt update && sudo apt upgrade`) as of 2020-12-05.
- Rebooted after upgrade.
- Copied the ClassicWB P96 HDF as per your link above.
- Started up Amiberry to create a new configuration, using the following details

- Quickstart: A1200, single floppy drive
- CPU: 020, Enable JIT
- FPU: 882, JIT FPU should also be enabled
- Speed: Fastest
- CPU Idle: set it to 2 clicks (just to keep the temperature down a bit)

Chipset: Set Blitter to Immediate. Ignore the "Cycle-Exact" options which looked enabled, that's a known issue in `dev`. They should be disabled automatically when selecting JIT (and they will be in the config file in the end).

ROM: I used 3.1 A1200.

RAM: 2MB Chip, 128MB Z3 RAM, 16MB RTG. The amount of RAM on RTG is probably overkill, but I wanted to test with the same you used. 4MB would also be enough.

Floppy: Set floppy drive speed to Turbo. Don't have to wait too long for those disks to be read that way.

HDD: I attached the HDF as DH0: with the default settings (bootable).

Display: Screenmode doesn't matter if using Dispmanx (which RetroPie does), but I changed the Width/Height to 640x512. Enabled Horizontal/Vertical Centering, and Double Line mode.

Sound: defaults

Input: I set Port 1 to None, as I didn't have a joystick connected and I didn't want to use a keyboard as Joystick setting (it uses up keyboard keys, which I want to use).

Misc: Enabled `bsdsocket.library` to have internet access. Also enabled RCtrl=RAmiga due to the keyboard I'm using.

Saved the config as `ClassicWB.uae` and tested it out by starting it up. The installation completed normally and I could boot into the environment once. I had to select the Screenmode to get a P96 mode working (I went for 800x600 32-bit), and after rebooting it all worked fine.

I eventually copied the .uae config file in `~/RetroPie/roms/amiga/` as well, to have it showing up in the list of EmulationStation. I can still launch it from there with no issues...

Hope this helps, perhaps some of the settings I used were slightly different than yours, and it could make a difference? I followed the official instructions for them, on Bloodwych's site: http://classicwb.abime.net/classicweb/instructionsp96.htm (though perhaps they are a bit outdated).

**Comment by Yserra** [comment]
@midwan many, MANY thanks for your tests and your time!
IT WORKS!

Well, at the beginning, it didn't. I followed all your steps in the configuration (expect I'm still using the 3.3 version of Amiberry, I have no idea how to install the latest dev one) and, boom, it failed, exactly as before. It sounded impossible, since I followed your exact steps.

So, I tried something new: recreating a new hdf from scratch, installing everything from Amiberry. Because the hdf I was using before had been installed months ago on my Mac, with the FS-UAE emulator. This old hdf was installed from the same WBClassic source, and perfectly run on FS-UAE with JIT. But - obviously - I should have had changed something, I don't know what, maybe a .library that the JIT engine in Amiberry doesn't like. I honestly don't remember. I "installed some Amiga stuff" on it... 

And, then, YES! This new hdf created from Amiberry runs perfectly with JIT from EmulationStation! At last!

I think I would have never tried this option before knowing you had a working configuration. Especially considering this old hdf worked, with JIT on Amiberry, when it is run from SSH (this is still a mystery).

So, again, many, many thanks for your time and your tests! And, obviously, for your great work on Amiberry, the best Amiga emulator on the Raspberry Pi!
Well done!

**Comment by midwan** [comment]
@Yserra 
Great stuff! I'm happy it finally works for you.
There are still some remaining known bugs in JIT, which I'm hoping that TomB will fix soon. And there are always unknown bugs to be found, and squashed of course. Perhaps you run into one of those... :)
