### ISSUE TITLE
[ Dev ] No boot when JIT Active

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#722]
Hi
With your latest DEV, Amiberry (and my FAmigaOS) won't works... 
Amiberry it starts, but seems not boot Amiga side.. (no drive sound and black screen)

**Comment by FabrizioRadica** [comment]
> 
> 
> Hi
> With your latest DEV, Amiberry (and my FAmigaOS) won't works...
> Amiberry it starts, but seems not boot Amiga side.. (no drive sound and black screen)

ok, problem found.
seems a simple conflict with "old" config.
WIth a fresh config it works

**Comment by midwan** [comment]
@FabrizioRadica 
I'm working on some parts in `dev` and it seems to break a few things. I'll either get it fixed or roll back the recent changes, sorry about that.
You should roll back to a previous commit in the meantime. ;)

**Comment by midwan** [comment]
@FabrizioRadica 

I've reverted the last commits that broke it, it should be fine again now.
I need more time to fix what's wrong with that...

**Comment by FabrizioRadica** [comment]
> 
> 
> @FabrizioRadica
> I'm working on some parts in `dev` and it seems to break a few things. I'll either get it fixed or roll back the recent changes, sorry about that.
> You should roll back to a previous commit in the meantime. ;)

No problem mate, you are number one.
I'm only help you to test it your great work :)

(My FAmigaOS is almost done)
