### ISSUE TITLE
savestate freeze the gui

### ISSUE THREAD

**Issue by amyren1966** [midwan/amiberry#725]
When trying to save a game state, the GUI freezes. The mouse cursor can be moved around, but the GUI seemes frozen.
I am running Amiberry on RPi4, Rasperry pi OS. 
The issue happens if I had a different config with HDD's loaded first, then load a floppy only config.

I had the default config set to boot up my A4000 WB39 setup, having two HDF's and one folder as harddrives, so this autostarts when Amiberry is launched.
Then I press F12, and select my config for Flimbo's Quest, a one floppydisk setup with kick 1.3 and 512kb ram and no HDD's.
I press reset to start the emulator and when the game starts I press F12 and try create a savestate.
This results in a non responsive GUI, and eventually I press Ctrl-Alt-Backspace to restart the desktop.

If I remove the default config file and start Amiberry, and then start the floppy game before any other configs, then the savestate works as it should.  If I load a harddrive setup first, and then load the game after this, then it sometimes freeze and other times work.

**Comment by jonpatterson** [comment]
I've experienced this as well, but I hadn't done enough investigation to raise an issue for it.  From my (limited!) testing I'd narrowed it down to happening when I was using a config with RTG and Picasso96.  With a similar config in WinUAE I think you get a warning to say the configuration isn't supported, although it still seems to work.

One thing I'd noticed is that the save state file **does** get saved to the _savedstates_ directory, even when it crashes.  However, the screenshot does not get saved to the _screenshots_ directory.  I was wondering if it was falling over at the point it tries to capture the screenshot, and whether some combination of RTG or P96 was causing this.

**Comment by amyren1966** [comment]
I think that savestates will not work with setups using  Harddrives. Unless you are using P96 frim a floppy setup, that might be the problem in your case.

**Comment by midwan** [comment]
I cannot recreate this problem with the latest `dev` version, following similar steps as described above.
I will assume therefore that this is fixed there, at least until we discover anything else. 👍 

![Amiberry - Amiberry_2020-12-28_18-32-48](https://user-images.githubusercontent.com/3877365/103232575-1b9b6900-493b-11eb-9cc6-c9a935c1b301.png)

**Comment by amyren1966** [comment]
How to get the dev version for testing this?
I tried "git clone -b dev https://github.com/midwan/amiberry" but got some error messages when running the make command, so no executable was created.

**Comment by midwan** [comment]
@amyren1966 
What you describe is correct, but make sure you are cloning it on a separate directory, not the same one you already had. You can have git create the directory for you as well in the same command, with something like `git clone -b dev https://github.com/midwan/amiberry amiberry-dev` (this would create and clone it in `amiberry-dev` for example).

Other than that, the compile steps are the same. What kind of error messages did you get?

**Comment by amyren1966** [comment]
I did rename the old amiberry folder before the command, so it was not in the same folder. I did not write down the errors, but I can try again later.

Happy new year to you.

**Comment by amyren1966** [comment]
This is the error message I get:

src/osdep/amiberry_gfx.cpp: In function ‘int graphics_setup()’:
src/osdep/amiberry_gfx.cpp:377:5: error: ‘host_hz’ was not declared in this scope
     host_hz = static_cast<int>(frame_rate);
     ^~~~~~~
src/osdep/amiberry_gfx.cpp: In function ‘bool vsync_switchmode(int)’:
src/osdep/amiberry_gfx.cpp:1894:13: error: ‘host_hz’ was not declared in this scope
   if (hz == host_hz)
             ^~~~~~~
make: *** [<builtin>: src/osdep/amiberry_gfx.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by midwan** [comment]
Looks like you're using the Dispmanx target, and I missed replacing `host_hz` for that one. My bad..
Fixed with c10f314025e25429c1ccafa95c32d68145c76089

**Comment by amyren1966** [comment]
Compiled successfully now.
I noticed some warnings though. Dpnt knopw if they are anything to worry about:

AMIBERRY  -c -o src/expansion.o src/expansion.cpp
src/expansion.cpp: In function ‘void free_expansion_bank(addrbank*)’:
src/expansion.cpp:2759:16: warning: converting to non-pointer type ‘uae_u32’ {aka ‘unsigned int’} from NULL [-Wconversion-null]
  bank->start = NULL;
                ^~~~
src/expansion.cpp: In function ‘void fastlane_memory_callback(romconfig*, uae_u8*, int)’:
src/expansion.cpp:4856:55: warning: passing NULL to non-pointer argument 2 of ‘zfile* read_device_from_romconfig(romconfig*, uae_u32)’ [-Wconversion-null]
  struct zfile *z = read_device_from_romconfig(rc, NULL);
                                                       ^
src/expansion.cpp: At global scope:
src/expansion.cpp:6735:1: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
 };

**Comment by midwan** [comment]
Those you can ignore, they come from WinUAE ;)

**Comment by amyren1966** [comment]
Just testet. Now I can load my HDD config, enter the GUI and load a floppy based setup and use the savestate without freezing.
Good job :)

**Comment by jonpatterson** [comment]
So does Amiberry support savestate when using RTG?  I pulled the latest dev branch and have an A1200 configured with 32MB Z3 Fast and 64MB RTG Board.  When I try to savestate the Amiberry gui hangs, then eventually crashes.  The console logs:

```
malloc(): invalid size (unsorted)
Aborted (core dumped)
```

However, after crashing an _.uss_ savestate file is in the _savestate_ directory, but there is no screenshot in the _screenshots_ directory.

If it's a case that savestate isn't supported with RTG then perhaps that feature could be disabled when a RTG config is selected?

**Comment by midwan** [comment]
@jonpatterson 
I haven't tested it with RTG modes, but it sounds like it crashed while trying to create the screenshot. I'll take a look.

**Comment by midwan** [comment]
@jonpatterson 
It's not the screenshot that's the problem, it's creating the savestate itself. It begins to create the file, but fails to write a compressed chunk in it. I believe that generally (even in WinUAE) savestates are not supported when using HDD and JIT mode?

**Comment by midwan** [comment]
I've added a relevant message in the GUI, so when an HDD is mounted it will not allow you to attempt to create a savestate.
