### ISSUE TITLE
Pressing x gives me an automatic enter key press

### ISSUE THREAD

**Issue by Raddinox** [midwan/amiberry#726]
**Describe the bug**
When I press the x key the Amiga acts as if I pressed x and enter.

It is easier to see in the Amiga Shell, but it is always happening whenever I use the x key.

and some more, if I press 2 i get 2p and if I press z i get an extra space after.

I have tried different USB keyboards, and there is no issues with the keyboard in Linux.

**To Reproduce**
This is what I have done
1) Install of latest Raspbian OS, apt update & upgrade and stuff.
2) Installed the required dependencies
3) Compiled Amiberry for my rpi3 (I have tried both master and dev branch)
4) Created a standard A1200 without hard drive
5) Boot workbench from floppy (although it's the same when booting from hard drive)
6) Open Amiga Shell and start typing, whenever I hit x key it will also hit enter.

**Expected behavior**
When I hit an x I expect to get an x without any extra key press

**Screenshots**
![alt text](https://i.imgur.com/OnyZbQR.png "Amiga Workbench")
I am only typing 1234567890abcdefghijklmnopqrstuvwxyz but I am getting an extra p (after 2) and an enter key press (after x) and an extra space (after z)

**Desktop (please complete the following information):**
Raspberry pi 3b+ with latest Raspberry pi OS

**Comment by midwan** [comment]
Check if you have "Keyboard as Joystick" assigned in Port 1.
That's expected behavior, if you do (with the current stable version at least).

**Comment by Raddinox** [comment]
O Yes, finally! I have looked all over for something like that could interfere with the keyboard, I probably need glasses..

Anyway thanks for fast answer.
