### ISSUE TITLE
Latest Binary 3.3 Cant load CD of some AMIGA CD32 games (ex Litil Divil)

### ISSUE THREAD

**Issue by 2play** [midwan/amiberry#727]
**Describe the bug**
Latest binary can boot CD32 "Litil Divil (Europe).cue" rom pack but once you kill the green devil on the bridge and enter the tunnel to start game, black screen stays forever.
**CD isnt loading** (tested also by enabling the led cd option to see activity of vritual cd) and emulator stays at this status.
Even if you try to exit/close the amiberry binary stays open and only by killing the running process can go back to cli or ES.

On the other hand the **beta binary amiberry-rpi4-3.2b05.08.20**  WORKS ok and none of the above behavior appears

**To Reproduce**
Just use latest binary and a cd32 cue based litil divil rom.

**Comment by midwan** [comment]
Tested the CD image I had with the latest `dev` version, and it seems to work as expected. At least, I can get past the point you mentioned :)

![Amiberry - Amiberry_2020-12-28_18-42-19](https://user-images.githubusercontent.com/3877365/103233103-77b2bd00-493c-11eb-8d09-41d5c1106e7e.png)

**Comment by 2play** [comment]
Thank you for checking. I will compile from latest code and check

**Comment by 2play** [comment]
ALL OK! tx @midwan  compiled 3.4beta from dev!
