### ISSUE TITLE
mousehack - Relative vs. Absolute mouse moves

### ISSUE THREAD

**Issue by Gerbinist** [midwan/amiberry#728]
Still wondering if this needs to be considered a bug, but I'll explain in detail what the Title suggests, which might lead to an issue with 'mousehack'.

My normal setup:
- A host with a Synergy server that is configured with 'relativeMouseMoves = false'
- A Pi 400 running Raspbian Buster with a Synergy client
- Everything besides Amiberry works as can be expected

Symptom with this normal setup in Amiberry:
"No matter what direction I move the mouse, the pointer moves in a diagonal line towards the bottom right corner of the window. I'm unable to move the mouse afterwards."

Now if I want to use the mouse properly, two things need to come together:
1. The server needs to be configured with relativeMouseMoves = true
2. The client needs the keyboard and mouse locked to the screen (with ScrollLock)

All is ok with this setup.

Now for the link with mousehack. FS-UAE knows a configuration parameter called 'mouse_integration'. When I'm using FS-UAE with my normal setup *and* I have this parameter set to 1, the mouse behaves correctly. But, I want to use Amiberry and I was feeling lucky because I noticed the setting 'mousehack' in Input. Going back to the documentation of mouse_integration in FS-UAE, I'm reading:
mouse_integration AKA magic mouse / *mousehack* / virtual mouse driver

With or without activating this setting on the normal setup however, the exact same symptom as described above is seen.

Two questions:
1. Is mousehack considered to be working properly or is this a bug?
2. Could Amiberry also start using mouse_integration as it does in FS-UAE?

My ultimate goal is to:
- Use Amiberry
- Use the normal setup (relativeMouseMoves = false)

(Using amiberry-v3.3-rpi4-sdl2-32bit.zip)

**Comment by midwan** [comment]
@Gerbinist 
This is currently broken in the `master` branch, but fixed and working in the `kbdlayout` one, soon to be merged into `dev` (and from there to `master` eventually, making a new stable release).

I've also implemented Magic Mouse cursor modes there, as found in WinUAE.

If you want to test it right away, you'll need to clone the `kbdlayout` branch and compile it from there. Keep in mind that branch will likely be deleted when things are merged into `dev`.

**Comment by Gerbinist** [comment]
Thanks for confirming. Unfortunately cloning a branch and compiling it from there is out of my league ;)

**Comment by midwan** [comment]
No worries, then you'll just have to wait a little longer, until I fix all the remaining (known) bugs and push this to a new release.

**Comment by Gerbinist** [comment]
Ok, compiling dev wasn't actually that hard. Still some strange behavior seen on the DispmanX version (rpi4).

With relative mouse moves and without locking the mouse to the screen, I see a couple of symptoms:
- Both mouse cursors are far apart when showing Both (I would assume they would be on top of each other?)
- I cannot reach the right edge on WB
- When starting from the right both mouse cursors are closest to each other, moving to the left causes the Amiga cursor to move quicker (space between cursors grow)
- Native mouse pointer vanishes when nearly on the left side and reappears a bit to the right when moving further to the left

Hope the above makes sense a bit, behavior is weird...

**Comment by midwan** [comment]
I need to test this under Dispmanx, as it was mostly designed for desktop usage...
