### ISSUE TITLE
WHDLoad stuck in AmigaDOS screen

### ISSUE THREAD

**Issue by wn2000** [midwan/amiberry#729]
Hello,
I built amiberry on a 64bit RK3328 platform using the "generic aarch64" configuration.
Tested some ADF games and works great!
Now I want to use the whdload feature so I can use amiberry inside a frontend, to go directly into a game from command line. But every time I use 
`amiberry --autoload /path/to/game.lha`
it ends up with a white AmigaDOS screen, with a `1>` prompt and no error messages.
I made sure that I have all mentioned kickstart roms in the wiki, and I can see symlinks made in whdload directory to point to them.
What can I do to debug this issue?

**Comment by midwan** [comment]
Could you please give some examples of the .lha filenames you're trying to run?
Do they contain the full game, or only the slave?

**Comment by wn2000** [comment]
One example is `A10TankKiller_v2.0_2Disk_1396.lha`, the content is like this:
.
├── A10TankKiller2Disk
│   ├── A10TankKiller2Disk.info
│   ├── A10TankKiller2Disk.Slave
│   ├── data
│   │   ├── a10
│   │   ├── a10.cfg
│   │   ├── A10Theme.snx
│   │   ├── alert16.bmp
│   │   ├── avenger2.instr
│   │   ├── avenger.instr
│   │   ├── avenger.ss
│   │   ├── BassDrum.instr
│   │   ├── BassDrum.ss
. . . many more entries

│   ├── Manual
│   ├── Manual.info
│   ├── ReadMe
│   └── ReadMe.info
└── A10TankKiller2Disk.info

So I assume it has the full game inside.

**Comment by wn2000** [comment]
Think I found the bug...will create a PR shortly.
