### ISSUE TITLE
SDL1 | Button shortcut for GUI and exit emulator don't work in GUI

### ISSUE THREAD

**Issue by Voljega** [midwan/amiberry#73]
Well simply said, when inside the GUI those two buttons won't work, you have to click Resume to return to the game and then they work again.

I thought it would be cool if the GUI button shortcut acted as a toggle (in/out) and the exit button everywhere.

Also I'm just writting that here as I maybe remember to have already read it on the issues there, but it would be good to be able to use 'higher' buttons for those two shortcuts, like button 8 to 10 (select, start,  ps home / xbox button) on a xbox or ps3 controller would be better for those two functionalities and avoid mistake when mashing buttons.

**Comment by midwan** [comment]
Those are good points, I'll make sure they are implemented.

Full button range mapping is coming in future versions. :)

**Comment by midwan** [comment]
FYI, this (the GUI toggle button) is already in the SDL2 version which will eventually replace the older SDL1.x one.

**Comment by Voljega** [comment]
cool ! I'll test it when it'll be out

**Comment by midwan** [comment]
This has been fixed in the current sdl1-dev and sdl2-dev branches
