### ISSUE TITLE
'Untrap = middle button' not saved

### ISSUE THREAD

**Issue by Gerbinist** [midwan/amiberry#732]
I usually like to configure the middle mouse button to switch screens inside the emulation. The untrap setting works when deactivating 'live' through F12, but the setting is not saved in the configuration file it seems, so I have to manually change it every time.

**Comment by Gerbinist** [comment]
Confirmed fixed in dev branch.

(What is the usual approach, close at this stage or keep it open until the release is out?)

**Comment by midwan** [comment]
We can leave it open for now, it will be closed automatically when the `dev` branch gets merged.
