### ISSUE TITLE
Trackball + Joystick config for games with Mouse primary control

### ISSUE THREAD

**Issue by wn2000** [midwan/amiberry#733]
This is mainly a question. Apology if it has already been asked.
I'm using Amiberry on an AtGames Legends Ultimate cabinet, which runs aarch64 Linux on a RK3328 board.
It has a trackball, and two joysticks each with 6 buttons, also a MENU and a REWIND button on player 1 side, a START button on either side.
I have configured the MENU button as the hotkey modifier, and MENU + REWIND to exit, and MENU + START to show the GUI.
This all worked perfectly for games with `PRIMARY_CONTROL=JOYSTICK`.
For games with `PRIMARY_CONTROL=MOUSE`, I'm having two problems:

1. The trackball moves mouse pointer fine, but I don't know how to map a joystick button to mouse button. I found #421 which mentions custom mapping a button to `Joy1 Fire/Mouse1 Left Button` but it did not work for me.

2. My preset MENU+REWIND and MENU+START hotkeys have no response. So I'm stuck in the game.

Since I'm using whdload, I found the file `whdload_db.xml` has this for joystick games:
```
PRIMARY_CONTROL=JOYSTICK
PORT0=CD32
PORT1=CD32
```
Hotkeys work fine with this.

And for mouse games:
```
PRIMARY_CONTROL=MOUSE
PORT0=MOUSE
PORT1=CD32
```
Hotkeys have no response under this setting.

How can this be properly set up with my joystick + trackball combo?

**Comment by wn2000** [comment]
To answer my own question, the issue is that by default `amiberry.conf` has
```
default_mouse2=joy0
```
Once I change it to
```
default_mouse2=joy1
```
it works well.

**Comment by midwan** [comment]
@wn2000 
Thanks for solving this :)
