### ISSUE TITLE
Make WHD path and start_path_data configurable and overridable by ENV variables

### ISSUE THREAD

**Issue by wn2000** [midwan/amiberry#734]
In my setup, the amiberry directory is located on an external USB drive, thus its exact absolute path can change from time to time. I see the Android code path already supports using an env variable to specify the main directory, so it'll be nice to extend that to all platforms.

Also the USB drive is most likely formatted in exFAT or NTFS, where a symlink is not supported. So I'd like to be able to specify the location of `whdboot` directory separate to the main amiberry directory (also overridable by env variable).

**Comment by midwan** [comment]
@wn2000 
How do you imagine this to work?

Currently, the starting location is used to determine the location of several key directories Amiberry uses, such as `conf`, `kickstarts`, `controllers` etc. These paths are determined and saved in the config when needed.

If we used an ENV variable for the path, that would also get resolved and saved to the actual full path, when saving the config file.

So the way I see it, if you path changes from time to time as you say, the paths saved in the config file(s) will be invalid in both cases?

**Comment by wn2000** [comment]
I guess the key is to only save relative paths to the config file.
Then when the program starts, it interprets those paths based on whether certain ENV variables are set. If yes, resolve paths starting from the ENV; otherwise assume the starting path is CWD, or some other sensible defaults like XDG_CONFIG_HOME etc.
That would make it truly portable.

**Comment by midwan** [comment]
The start path has now been added as a variable, as mentioned in the FAQ section (near the bottom): https://github.com/midwan/amiberry/wiki/FAQ
