### ISSUE TITLE
Mouse Pointer disappears. Raspberry Pi 3+ under Debian Buster

### ISSUE THREAD

**Issue by Zondel** [midwan/amiberry#740]
Hallo ,

My Problem is following:
I started amiberry automaticly under Raspberry Pi 3 B+ and Debian Buster with graphical Surface ( named XFACE ???) 
So far so good.  Unfortunetly my Mouse Pointer is unvisible. I can klick the LMB if I move the mouse over the Main menu surface but I don't see my Pointer. 
When I Start amiberry without the Graphical Surface  ( in multi-user.target mode ) --> only in Terminal,  the mouse works perfectly.

Why? What can I do to fix the Problem?

Thanks a lot for you answer.

Chris

**Comment by midwan** [comment]
I can't really recreate this here. It seems to work normally in all environments I start it under.
Which distro are you using?
I've tested it on RPI OS, RetroPie, Manjaro, Pimiga, AmiKit beta...

**Comment by dcutugno** [comment]
I have this issue too, on raspi os with latest updates and an rpi 3b+

**Comment by midwan** [comment]
Have you tried fully upgrading your system?
What gfx driver are you using on Raspbian - `fkms` should be the default. Check `/boot/config.txt` if you're not sure.

**Comment by midwan** [comment]
Still can't recreate this anywhere I've tested it:
- X11 with XFCE
- console with KMSDRM
- console with Dispmanx

Unless someone can provide a way to recreate it, I don't think there's anything I can do...
