### ISSUE TITLE
Cache configuration list

### ISSUE THREAD

**Issue by muchahagrande** [midwan/amiberry#741]
**Is your feature request related to a problem? Please describe.**
When handling a huge configuration list, e.g. 2000 configs or more, each time that you go to the configuration menu, it takes a long time to read the list.

**Describe the solution you'd like**
It would be usefull to have a kind of configs cache to accelerate the process of showing the config menu.

**Describe alternatives you've considered**
Other approach could be, loading the list in background so it no longer freezes the program when entering the menu.

**Additional context**
I'm using Amiberry 3.3 on a RPi 3B+ under DietPi
I have a list of 2290 .uae configs. Each time I access the configuration it takes several second until the menu shows up.
My configuration directory is located locally on the SD card, but my games are actually on a SMB share.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
This is covered in the FAQ section: https://github.com/midwan/amiberry/wiki/FAQ
