### ISSUE TITLE
PulseAudio (distortion) vs. ALSA

### ISSUE THREAD

**Issue by Gerbinist** [midwan/amiberry#742]
With the latest update of Raspberry Pi OS, a switch of sound server is seen.

(more background information on https://www.raspberrypi.org/blog/new-raspberry-pi-os-release-december-2020/)

I'm now noticing this has a negative impact on the sound in Amiberry... games really need Sound Buffer Size 2 to be of any use, but with this setting, there is a lot of distortion in the sound. Even when playing a .mod file this issue is heard. Raising the Buffer value helps a bit, but it isn't gone entirely.

Has anyone else experienced this same behavior? Does this mean anything for development of Amiberry?

I compared this to an install of DietPi where it still runs correctly, but I think they haven't touched the sound server yet.

**Comment by midwan** [comment]
@Gerbinist 
Which distro and environment did you test this with?
Also, which specific scenarios (specific games?) please?

**Comment by Gerbinist** [comment]
> Which distro and environment did you test this with?
> Also, which specific scenarios (specific games?) please?

Tried this with amiberry-v3.3-rpi4-dmx-32bit and the dev version of December 4th on a Pi 400 currently running the official Raspberry Pi OS (Buster):

`Linux PI400 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux`

I used the 32-bit Buster image of DIetPi the other day.

Sound is Ok with both versions of Amiberry within DietPi and also ok in the previous official release of Raspberry Pi OS. Issue started when I did an upgrade of the official OS. When looking into the details of the OS upgrade, a change of sound server is seen. So perhaps not entirely correct, but a relation with PulseAudio makes the most sense.

It actually doesn't matter which game I start, issue is heard with every game and even with .mod playback...

**Comment by midwan** [comment]
OK, thanks for the feedback. I'll set up an environment to test with here.

**Comment by Gerbinist** [comment]
@midwan
I compiled the dev branch today to have another testrun and the distortion is gone...!

**Comment by midwan** [comment]
@Gerbinist 
Thanks for confirming.
