### ISSUE TITLE
68060 selection in base config

### ISSUE THREAD

**Issue by andiweli** [midwan/amiberry#745]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Currently 68000, 68020, 68030 and 68040 CPUs are available.
The 68060 is missing so far.

**Describe alternatives you've considered**
Currently using 68040.

**Additional context**
Nope.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

I am loving it :) Just donated.

**Comment by midwan** [comment]
@andiweli 
the CPU emulation in Amiberry is based on previous work done on the Aranym project (https://aranym.github.io/), who created the first ARM port. Unfortunately, there is no 68060 implementation in Aranym, so it's doubtful we'll have that in Amiberry anytime soon.

On the other hand, 040 works quite well already and all software that uses an 060 usually runs just fine there as well. Unless you have any specific cases where that doesn't work?

**Comment by andiweli** [comment]
No, everything's fine. I was just asking.
