### ISSUE TITLE
Floppy disk sounds

### ISSUE THREAD

**Issue by andiweli** [midwan/amiberry#746]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
The typical floppy noise (klick) sound a real Amiga does...

**Describe alternatives you've considered**
None so far. FS-UAE on Windows has it, but I wan't to use my Raspi3.

**Additional context**
Nope.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
This is already implemented, in the Sound panel of v3.3.

**Comment by andiweli** [comment]
Uh my fault!
I am on Amibian and upgrading Amiberry always seems to result in an error terminating the build.
So I am still on 2.18 Amiberry :)

Thanks!
