### ISSUE TITLE
SDL2 | Custom keys mapping

### ISSUE THREAD

**Issue by loz34** [midwan/amiberry#75]
Hi, I am using an X-Arcade tankstick as my controller.
Retropie recognises the x-arcade as a keyboard not a controller
Setting custom keys within Amiberry doesn't work.
I need to be able to change PgDown to another key.
Does Amiberry use ascii?
Thanks

**Comment by midwan** [comment]
The custom mapping functionality is planned to be improved (a lot), so hopefully this would help your situation as well.

I have an X-Arcade to test with, so this will not be a problem. :)

**Comment by midwan** [comment]
@loz34 
Custom Controls now get saved and loaded properly from the config file.

The next step is to allow any keyboard key or controller button to those functions. Hopefully this will help address this issue as well.

**Comment by HoraceAndTheSpider** [comment]
We should enhance the keyboard-as-joystick mode to cover a full set of cd32 buttons, and then allow those to be remapped also. 

I will look into this following the next release version.

**Comment by midwan** [comment]
@HoraceAndTheSpider can we close this also with the latest merge?

**Comment by HoraceAndTheSpider** [comment]
I think so - the user can now use a `retroarch.cfg` file for setting their keyboard controller as a joystick, and customise the retroarch file to suit.

I will eventually also allow even the keyboard-remap to take advantage of game-specific customisations also.
