### ISSUE TITLE
latest dev (Dispmanx) version crashes when using RTG graphics

### ISSUE THREAD

**Issue by mrdave1968** [midwan/amiberry#757]
After checking out the latest dev version, the program exits with an error when configured to use RTG graphics

I used a Raspberr PI400 and configured to run Amiberry without X.

Select a 68020 and JIT, then in RAM pane add some RTG memory
Run

Got thie error:
INFO: --- New exception ---
INFO: Error not in JIT code.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = 00000008
INFO: r0  = 0xabb00a50
INFO: r1  = 0x03a9f3d8
INFO: r2  = 0x00001410
INFO: r3  = 0x03aeb1d4
INFO: r4  = 0x05a73430
INFO: r5  = 0x05a73430
INFO: r6  = 0x03a5ab98
INFO: r7  = 0x05a73430
INFO: r8  = 0xbef29262
INFO: r9  = 0xa8efc450
INFO: r10 = 0x00000000
INFO: FP  = 0xa8efbf8c
INFO: IP  = 0x00000003
INFO: SP  = 0xa8efbdc8
INFO: LR  = 0xabb03f70
INFO: PC  = 0x002230ec
INFO: CPSR = 0x00000010
INFO: Fault Address = 0x00000008
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x00000207
INFO: Old Mask = 0x0e017007
INFO: LR - 0xABB03F70: symbol not found
INFO: Stack trace:
INFO: 0x00250028 <(null) + 0x00250028> (./amiberry)
INFO: 0xb68b4130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: 0x002230ec <(null) + 0x002230ec> (./amiberry)
INFO: 0x0011765c <(null) + 0x0011765c> (./amiberry)
INFO: 0x001d80f8 <(null) + 0x001d80f8> (./amiberry)
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x250140]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb68b4130]
INFO: ./amiberry() [0x2230ec]
INFO: ./amiberry() [0x11765c]
INFO: ./amiberry() [0x1d80f8]
INFO: End of stack trace.
INFO: --- end exception ---

master version runs fine with same configuration.

**Comment by midwan** [comment]
Which distro are you running this on please?
Also, which version of SDL is Amiberry using? You can find that in the About panel in the GUI (right under the version info).

**Comment by mrdave1968** [comment]
Raspbian 10 (with latest updates), SDL2-2.0.10, SDL2_ttf-2.0.15, SDL2_image-2.0.5.

Trying with SDL2-2.0.14 gives a frozen mouse pointer (the GUI can be navigated with keyboard or mouse even if the pointer is stuck in the top left corner) and when launched with RTG gives this error:

INFO: --- New exception ---
INFO: PC is NULL.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = 00000000
INFO: r0  = 0xab3feda0
INFO: r1  = 0x00000081
INFO: r2  = 0x9c0b5d00
INFO: r3  = 0x00000000
INFO: r4  = 0xb6f242f4
INFO: r5  = 0xab3feda0
INFO: r6  = 0x00000000
INFO: r7  = 0x00000000
INFO: r8  = 0xbef11242
INFO: r9  = 0xab3ff450
INFO: r10 = 0x00000000
INFO: FP  = 0xab3fef8c
INFO: IP  = 0x00002efa
INFO: SP  = 0xab3feda0
INFO: LR  = 0xb6ecc44c
INFO: PC  = 0x00000000
INFO: CPSR = 0x60000010
INFO: Fault Address = 0x00000000
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x80000207
INFO: Old Mask = 0x0e017007
INFO: LR - 0xB6ECC44C: <(null)> (/usr/local/lib/libSDL2-2.0.so.0)
INFO: Stack trace:
INFO: 0x00250020 <(null) + 0x00250020> (./amiberry)
INFO: 0xb68a0130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x250138]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb68a0130]
INFO: End of stack trace.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: PC is NULL.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = 00000000
INFO: r0  = 0xa9ffdda0
INFO: r1  = 0x00000081
INFO: r2  = 0x9c0b5d00
INFO: r3  = 0x00000000
INFO: r4  = 0xb6f242f4
INFO: r5  = 0xa9ffdda0
INFO: r6  = 0x00000000
INFO: r7  = 0x00000000
INFO: r8  = 0xbef11242
INFO: r9  = 0xa9ffe450
INFO: r10 = 0x00000000
INFO: FP  = 0xa9ffdf8c
INFO: IP  = 0x00002efc
INFO: SP  = 0xa9ffdda0
INFO: LR  = 0xb6ecc44c
INFO: PC  = 0x00000000
INFO: CPSR = 0x60000010
INFO: Fault Address = 0x00000000
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x80000207
INFO: Old Mask = 0x0e017007
INFO: LR - 0xB6ECC44C: <(null)> (/usr/local/lib/libSDL2-2.0.so.0)
INFO: Stack trace:
INFO: 0x00250020 <(null) + 0x00250020> (./amiberry)
INFO: 0xb68a0130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x250138]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb68a0130]
INFO: End of stack trace.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: PC is NULL.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = 00000000
INFO: r0  = 0xaa7feda0
INFO: r1  = 0x00000081
INFO: r2  = 0x9c0b5d00
INFO: r3  = 0x00000000
INFO: r4  = 0xb6f242f4
INFO: r5  = 0xaa7feda0
INFO: r6  = 0x00000000
INFO: r7  = 0x00000000
INFO: r8  = 0xbef11242
INFO: r9  = 0xaa7ff450
INFO: r10 = 0x00000000
INFO: FP  = 0xaa7fef8c
INFO: IP  = 0x00002efb
INFO: SP  = 0xaa7feda0
INFO: LR  = 0xb6ecc44c
INFO: PC  = 0x00000000
INFO: CPSR = 0x60000010
INFO: Fault Address = 0x00000000
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x80000207
INFO: Old Mask = 0x0e017007
INFO: LR - 0xB6ECC44C: <(null)> (/usr/local/lib/libSDL2-2.0.so.0)
INFO: Stack trace:
INFO: 0x00250020 <(null) + 0x00250020> (./amiberry)
INFO: 0xb68a0130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x250138]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb68a0130]
INFO: End of stack trace.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: PC is NULL.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = 00000000
INFO: r0  = 0xacf35da0
INFO: r1  = 0x00000081
INFO: r2  = 0x9c0b5d00
INFO: r3  = 0x00000000
INFO: r4  = 0xb6f242f4
INFO: r5  = 0xacf35da0
INFO: r6  = 0x00000000
INFO: r7  = 0x00000000
INFO: r8  = 0xbef11242
INFO: r9  = 0xacf36450
INFO: r10 = 0x00000000
INFO: FP  = 0xacf35f8c
INFO: IP  = 0x00002ef7
INFO: SP  = 0xacf35da0
INFO: LR  = 0xb6ecc44c
INFO: PC  = 0x00000000
INFO: CPSR = 0x60000010
INFO: Fault Address = 0x00000000
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x80000207
INFO: Old Mask = 0x0e017007
INFO: LR - 0xB6ECC44C: <(null)> (/usr/local/lib/libSDL2-2.0.so.0)
INFO: Stack trace:
INFO: 0x00250020 <(null) + 0x00250020> (./amiberry)
INFO: 0xb68a0130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x250138]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb68a0130]
INFO: End of stack trace.
INFO: --- end exception ---
INFO: --- New exception ---
INFO: PC is NULL.
INFO: Segmentation Fault
INFO: info.si_signo = 11
INFO: info.si_errno = 0
INFO: info.si_code = 1
INFO: info.si_addr = 00000000
INFO: r0  = 0xabdfeda0
INFO: r1  = 0x00000081
INFO: r2  = 0x9c0b5d00
INFO: r3  = 0x00000000
INFO: r4  = 0xb6f242f4
INFO: r5  = 0xabdfeda0
INFO: r6  = 0x00000000
INFO: r7  = 0x00000000
INFO: r8  = 0xbef11242
INFO: r9  = 0xabdff450
INFO: r10 = 0x00000000
INFO: FP  = 0xabdfef8c
INFO: IP  = 0x00002ef9
INFO: SP  = 0xabdfeda0
INFO: LR  = 0xb6ecc44c
INFO: PC  = 0x00000000
INFO: CPSR = 0x60000010
INFO: Fault Address = 0x00000000
INFO: Trap no = 0x0000000e
INFO: Err Code = 0x80000207
INFO: Old Mask = 0x0e017007
INFO: LR - 0xB6ECC44C: <(null)> (/usr/local/lib/libSDL2-2.0.so.0)
INFO: Stack trace:
INFO: 0x00250020 <(null) + 0x00250020> (./amiberry)
INFO: 0xb68a0130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
INFO: Stack trace (non-dedicated):
INFO: ./amiberry() [0x250138]
INFO: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb68a0130]
INFO: End of stack trace.
INFO: --- end exception ---
double free or corruption (fasttop)
Aborted

**Comment by midwan** [comment]
OK, are you using the Dispmanx or SDL2 (with KMSDRM) target?
Do you have the fkms or KMS driver enabled in your `/boot/config.txt` file?

**Comment by mrdave1968** [comment]
I'm using KMSDRM/DIspmanx with fkms enabled

I just tried rolling back commits and found that until commit 741c1dce3c90720d38c8b712dc23beee1bb18f55 it works normally, the problem appears with commit f16ad73318c60cd44d3dc899b5e07353ea1aae3e (P96 improvements).....

**Comment by mrdave1968** [comment]
EDIT: ISorry, commit f16ad73318c60cd44d3dc899b5e07353ea1aae3e works, I gave an erroneous git command that compiled HEAD instead, still checking which commit triggers the error

**Comment by midwan** [comment]
@mrdave1968 
You're either using Dispmanx OR KMSDRM, it can't be both :)
Which PLATFORM option did you use when compiling Amiberry?

That commit changed the way the available screen resolutions are populated, instead of hardcoding a list it is supposed to get the available screenmodes from your hardware now. It works normally in the scenarios I've tested here, but perhaps I missed something...

**Comment by mrdave1968** [comment]
make -j4 PLATFORM=rpi4

I  did not specify a HDMI mode in boot/config.txt and left autoconfiguration, my monitor does 1680x1050

**Comment by midwan** [comment]
Thanks - that's the Dispmanx version for RPI4.
It might be an issue with that backend then, because I'm using SDL2's functions to get the available screenmodes. Perhaps when using Dispmanx it doesn't get anything back, so I'll have to test it a bit here.

**Comment by midwan** [comment]
@mrdave1968 
Please test with the latest commit, this should be fixed now.

**Comment by mrdave1968** [comment]
Yes, it works again with SDL2.0.10. Trying with 2.0.12 or 2.0.14 crashes and has the 'mouse pointer stuck in GUI' problem.

**Comment by midwan** [comment]
I don't see a problem with SDL2 v2.0.12 here, when using the same Dispmanx target.
Is that under the same system?
