### ISSUE TITLE
Workbench Cli  keyboard type x issue

### ISSUE THREAD

**Issue by Strommel** [midwan/amiberry#758]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by Strommel** [comment]
When Amiberry is runing with a worbench and i start cli, cli starts normely but if i have to use the letter "x" it will do rare things like
implement a return after the letter x.
This will happend on nearby any prog that i start on workbench.
can you help me whith this?

**Comment by midwan** [comment]
This seems to be a common question, so I just added it to the Wiki FAQ section also: https://github.com/midwan/amiberry/wiki/FAQ

Don't use Keyboard as Joystick in the Input panel, if you want to use the keyboard on Workbench. The mapping uses some extra keys for CD32 mapping that will interfere with normal typing scenarios. :)

**Comment by Strommel** [comment]
Thank you for your fast andere. It works now perfect

Dimitris Panokostas <notifications@github.com> schrieb am So., 17. Jan.
2021, 14:54:
