### ISSUE TITLE
Bug found now in the Image Size....

### ISSUE THREAD

**Issue by CypherXG** [midwan/amiberry#76]
Hi i found one Bug again. 
You can found it if you change the Resolution Width. 
There are some Errors if you switch the Resolution to 320, 352, 384 and 704 Pixel.
640 and 768 Pixel works fine.
I compiled a fresh Version of your Code and use your Built-in Amiga 500 Config.
I post here some example with Witdth 320 and 352 Pixel.

320 Pixel: https://picload.org/image/rlpcacli/320.jpg
352 Pixel: https://picload.org/image/rlpcaccr/352.jpg

P.S. Can u tell me where the Code is written for the black Backround behind the Statusline LED?

Best regards...
Markus

**Comment by CypherXG** [comment]
Ok i've found the Error.
In src/osdep/rasp_gfx.cpp Line 189
Dummy_prSDLScreen = SDL_SetVideoMode(width, height, 16, SDL_**HW**SURFACE | SDL_FULLSCREEN);
Change it to:
Dummy_prSDLScreen = SDL_SetVideoMode(width, height, 16, SDL_**SW**SURFACE | SDL_FULLSCREEN);

Then all Resolutions are working fine in all Modes.
This change has no effect on the "missing resolutions" errors :-)

Best regards....Markus

**Comment by midwan** [comment]
Great find, thanks!
It might be what caused the "missing" resolutions also actually.

I'll roll this change back to SWSURFACE and prepare a new binary with the fix.

**Comment by midwan** [comment]
Fixed with 33fe45f39263dedb231f1958dfd7d3824bdc1db6
