### ISSUE TITLE
After one of latest commits  mouse does not work correctly in GUI

### ISSUE THREAD

**Issue by mrdave1968** [midwan/amiberry#760]
**Describe the bug**
Probabkly after this commit: debd67c28b2b7dc78c36f78dd4490ca16524c3bb
    - Now using separate windows for emulation and GUI
Launching amiberry without parameters does not open the GUI and leaves you stuck in the console until you press CTRL-C
Launching with a configuration file starts emulator normally, it works but when you use F12 to bring the GUI mouse pointer does not reflect real click location.

Using DISPMANX version without X and SDL2-2.0.10, using newer versions of SDL2 give worse results like not showing the mouse pointer at all in GUI or crash.

**Comment by midwan** [comment]
@mrdave1968 
This should be fixed now, please test from your side also?

**Comment by mrdave1968** [comment]
Yes, fixed.
WIth latest commit you changed RGB to BGR, this gives wrong colors in Amiga (non-RTG) screens

**Comment by midwan** [comment]
@mrdave1968 
I can't recreate that, are you testing with the latest commit?
In any case, this is still pretty much work in progress still, so I'm fixing it as I test it :)

**Comment by FabrizioRadica** [comment]
> 
> 
> Yes, fixed.
> WIth latest commit you changed RGB to BGR, this gives wrong colors in Amiga (non-RTG) screens

same problem.
FIX: if you use UAEGfx, just set it 16 bit on screen mode.

**Comment by midwan** [comment]
> > Yes, fixed.
> > WIth latest commit you changed RGB to BGR, this gives wrong colors in Amiga (non-RTG) screens
> 
> same problem.
> FIX: if you use UAEGfx, just set it 16 bit on screen mode.

This only affects RTG modes that are 32-bit. The change was made to sync Amiberry with WinUAE in that area, so future changes can be done with less hassle.

The solution is to open the GUI, go to the new RTG Panel, and change the 32-bit mode pixel format there to the (new) default. You can easily find the default as it has an asterisk next to it. Save the configuration, boot into your Workbench and open ScreenMode, then select the new 32-bit mode you want.

To avoid booting into a PAL:HighRes mode, you could change to a 16-bit color depth mode before that, in ScreenMode. Those haven't changed and will still work with the right colors.
