### ISSUE TITLE
RTG modes using 50Hz cause audio playback issues

### ISSUE THREAD

**Issue by macphreak4evr** [midwan/amiberry#761]
sudo raspi-config , set a display mode to from the default (in this case) CEA mode 16 1920x1080 60hz,  this work great, and all is well, but if i change to pal, cea mode 31 1920x1080 50hz, save and reboot, the sound skips to a point its useless to enjoy.   returning to cea mode 16 (60hz ) or 60 hz any mode, returns sound to normal speed.  this happens regardless if the ntsc check box is ticked  in amiberry or not. 

tested versions amiberry-v3.3-rpi4-sdl2-32bit.zip skips regardless,  and amiberry-v3.3-rpi4-dmx-32bit.zip <-- that works fine in 60hz, not 50

**Comment by midwan** [comment]
This is a known bug, but only under P96 mode as far as I know.
Can you please confirm? Running PAL games/demos for instance, should have correct sound playback.

**Comment by macphreak4evr** [comment]
indeed, pal games, whdload or f12 booting a adf seem to work fine.  mainly mods/mp3's or workbench sounds. things that get out of workbench modes tend to work fine.

**Comment by midwan** [comment]
@macphreak4evr 
Thanks for confirming. :)
