### ISSUE TITLE
Mouse does not move in GUI, console mode in DEV

### ISSUE THREAD

**Issue by cdurbin1970** [midwan/amiberry#762]
I am running a PI4 4GB, External 1TB SSD via USB (boot), Fresh Raspberry PI OS install, fully updated.

Following the directions here and in the Wiki, I downloaded and compiled the SDL2 libraries for use in
console mode. Then did a make install to install them properly. Everything compiled correctly.
I cloned DEV from here and compiled Amiberry with the PLATFORM=rpi4 attribute.
Everything compiled fine.

When I run Amiberry, the mouse cursor does not move. I can use the keyboard to navigate and load a
profile and launch Amiberry. Once in AmigaOS, the mouse works fine.
At the command line, if I do a startx, go into the desktop, open up a command line and launch Amiberry,
the mouse works fine.

**Comment by Lex15** [comment]
Build SDL2 2.0.12. Version 2.0.14 does not seem to be compatible yet.

**Comment by midwan** [comment]
Manjaro just got an update today, which included SDL2 2.0.14.
From what I can see, KMSDRM with that version of SDL2 still works for me (including the mouse pointer in the GUI).
And X11 also works, of course.

Perhaps this is an issue with RPI OS and the latest SDL2 only? If it works with previous SDL2 versions, then that sounds like the case.

**Comment by midwan** [comment]
So far, I've seen this happen in one scenario only:
- Using the Dispmanx version (not KMSDRM), and launching it from the console (works under X11).

**Comment by cdurbin1970** [comment]
Building 2.0.12 seems to have fixed the issue.

**Comment by midwan** [comment]
I noticed in the changelog of SDL2, that many changes related to KMSDRM were applied in 2.0.14. Including several regarding the mouse cursor, so maybe these work with the newer kernels only? Anyway, it's not an Amiberry issue as such. :)
