### ISSUE TITLE
Mouse movement glitch (RTG and Chipset)

### ISSUE THREAD

**Issue by FabrizioRadica** [midwan/amiberry#766]
Hi :)
I've some problem with mouse with your last DEV commit.
As you can see in the video, the mouse pointer seems to go crazy :D 

https://drive.google.com/file/d/1Bhfsc64osbpJ-lPSuwdMJggu2Z3RkpOl/view?usp=sharing

Ciao!

**Comment by midwan** [comment]
@FabrizioRadica 
Can you test if the latest commit fixes this, please?
I still can't confirm here, since I can't recreate it.

**Comment by FabrizioRadica** [comment]
I confirm, it works again (what happened?).

**Comment by midwan** [comment]
I implemented one extra thing from WinUAE, that did this. I guess we don't need it. :)
