### ISSUE TITLE
Amiberry 3.3 slow and choppy on RPi 4

### ISSUE THREAD

**Issue by gordonfreemanhr** [midwan/amiberry#767]
First of all, thanks for this. This is the best working RPi Amiga emulator so far. All my games just work out of the box.

But, the emulation is a bit slow - not super slow, just bit slow - and the sound is choppy accordingly. I have not messed with the settings and I don’t want to break anything.

I’m on Retropie 4.71, yesterday’s fresh install, 64 GB SD card, 4 GB RPi 4, official power supply, games stored on an external USB.

**Comment by midwan** [comment]
@gordonfreemanhr 
Under what conditions do you find it slow and with choppy sound?

**Comment by gordonfreemanhr** [comment]
Every game started from the EmulatioStation is like this. I can hear sound chopping and the animations seem to be playing at about 0.7-0.8 default speed. (This just a feeling, I have no way to accurately calculate this). The Pi is not overclocked.

**Comment by midwan** [comment]
@gordonfreemanhr 
That sounds weird, I've never seen a game that doesn't run full speed on the Pi4.
You can enable the Status bar from the Amiberry GUI (check the Misc panel), to see how many FPS it's doing. PAL games should run at 50, NTSC ones at 60.

Did you install Amiberry using RetroPie-Setup?
Are you using the pre-compiled binary that RetroPie provides, or did you install it from source?

**Comment by gordonfreemanhr** [comment]
Thanks for the tip. I checked with the Status bar: every Amiga game I tried runs at 30 FPS.

Yes, I used RetroPie-Setup and the pre-compiled binary.

**Comment by midwan** [comment]
OK, sounds like something is limiting your FPS. What resolution is the RPI running at, on your monitor?
Amiberry uses VSync, so if the resolution is at 30Hz, that would explain it.

**Comment by gordonfreemanhr** [comment]
It's plugged to my Smart TV and at the default settings. Apparently the
default 4K settings are limiting the framerate to 30 FPS.
The problem is, when I change my resolution to anything else than the
"monitor preferred resolution", the Retropie... dies. Seriously, I tested
it. It happened to me twice yesterday. The ES just won't boot afterwards
and I have to wipe the SD card to start over again.
Therefore, I need to find a way to change framerate to 60 FPS WITHOUT
changing the resolution...

**Comment by midwan** [comment]
It could be that the 30Hz is limited by the RPI4 itself, in order to output 4K.
Have you tried changing the /boot/config.txt options, to force 1080p? There’s documentation on that on the official Rasperry Pi foundation page.

Either way, this doesn't seem to be an Amiberry problem exactly... :)

**Comment by instan7Karma** [comment]
try adding this line to config.txt:
**hdmi_enable_4kp60**
(Pi 4B only)
By default, when connected to a 4K monitor, the Raspberry Pi 4B will select a 30hz refresh rate. Use this option to allow selection of 60Hz refresh rates. Note, this will increase power consumption and increase the temperature of the Raspberry Pi. It is not possible to output 4Kp60 on both micro HDMI ports simultaneously.
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

**Comment by gordonfreemanhr** [comment]
I managed to switch to 1080p eventually, but no effect, sadly. Amiberry’s running at 30 FPS, as previously.

**Comment by midwan** [comment]
@gordonfreemanhr 
If your monitor is doing 1080p at 30Hz, then you'll always get 30FPS in Amiberry as well.
Did you check that?

**Comment by gordonfreemanhr** [comment]
According to raspi-config, it’s 1080p at 60Hz now. I don’t know how accurate the tool is, but that’s what it says.

**Comment by gordonfreemanhr** [comment]
Also, another person just popped up in the respective topic on the RetroPie forum. Apparently, I’m not the only one having problems with Amiberry on the latest RetroPie image.

**Comment by midwan** [comment]
@gordonfreemanhr 
Do you have a way to see what the monitor/TV reports as current resolution? It should have some information panel regarding the current settings, which will include refresh rate.

I can't think of any other reason you would be limited to 30FPS while on 1080p, the Pi4 is more than capable of handling it (even the Pi3 could handle most games at 50/60 FPS), and Amiberry v3.3 has not changed since it was released several months ago (with hundreds of testers on various platforms).

**Comment by gordonfreemanhr** [comment]
You might want to look into the ongoing topic on the RetroPie forum:
https://retropie.org.uk/forum/topic/29453/amiberry-3-3-rpi-4-slow/40

Apparently, despite RetroPie claiming I’m on 1080p, I wasn’t. I was still on 4K, hence the 30 FPS.

The struggle to change the resolution is ongoing. After a recent advice regarding config.txt, eventually my Smart TV ‘admitted’ to be running in 640x480 60p, but - guess what - the EmulationStation is not booting now.

It seems they’ve given up...


>

**Comment by midwan** [comment]
@gordonfreemanhr 
Thanks for the link. It certainly seems like a bit of a mess...
Amiberry can handle any resolution you throw at it, but it's up to the device's hardware to handle the extra throughput if you go for a higher one (e.g. 4K). The higher the resolution, the more pixels it needs to push per frame.

I hope you'll find a solution to this, but as it's not really related to Amiberry and there's nothing I can do from here, I'll close this case for now. Feel free to post any updates if you find a solution in the future, so that other people might find them as well.

**Comment by gordonfreemanhr** [comment]
WE GOT IT.

After countless combinations, we found the right one.

The problem is that Samsung Smart TV overrides RPi's resolution settings -
despite your raspi-config choices and what you put in config.txt - and
upscales them up to 4K - it's preferred resolution. This works bad for RPi,
forcing it to 30 FPS, which really, really shows in Amiberry.

The solution is adding the following lines to config.txt:

[hdmi:0]
hdmi_max_pixel_freq=200000000
[hdmi:1]
hdmi_max_pixel_freq=200000000
hdmi_ignore_edid=0xa5000080

**Comment by midwan** [comment]
@gordonfreemanhr 
Thanks for sharing the solution!

**Comment by solskogen** [comment]
Perhaps put that in the FAQ?

**Comment by midwan** [comment]
Done: https://github.com/midwan/amiberry/wiki/FAQ

**Comment by mpisau** [comment]
Same here with a LG Nano TV. Thanks for sharing the solution.
