### ISSUE TITLE
DOS-Error #205 (object not found) on reading "Intro"

### ISSUE THREAD

**Issue by penx** [midwan/amiberry#768]
**Describe the bug**

When loading a whdload lha, I always get a black screen. On checking `/opt/retropie/emulators/amiberry/whdboot/save-data/Debugs` the result is nearly always:

```
DOS-Error #205
(object not found)
on reading "Intro"
```

(with the disk name changing depending on the game, e.g. `on reading "flashback"`).

**To Reproduce**

- Fresh install Retropie 4.7.1 with Raspberry Pi Imager
- Update RetroPie-Setup (I am on https://github.com/RetroPie/RetroPie-Setup/commit/c5e56d864f8c5b5c0fb78d794d568833b6666fc7)
- Install amiberry from binary
- Reboot
- Insert USB drive containing BIOS and ROMs such as [this one](http://www.whdload.de/games/Lemmings.lha)
- Wait for copy to complete and restart retropie
- Open lha, see Amiberry logo,
- (If first time loading lha, see Amiberry WHDload AutoBooter, including "Setpatch... not found")
- see black screen
- Check`/opt/retropie/emulators/amiberry/whdboot/save-data/Debugs` 

**Desktop (please complete the following information):**

- OS: RetroPie 4.7.1
- Hardware: Raspberry Pi 400

**Comment by penx** [comment]
I saw https://github.com/midwan/amiberry/issues/679#issuecomment-672336624 but can confirm I am using the lha as it exists on http://www.whdload.de/

**Comment by penx** [comment]
on a side not it took me a long time to figure out the correct log file to be looking at - is there any way to surface errors like this on the screen, or else add a section to the wiki called "log files/debug" that lists these file locations along with the amiberry.log file and runcommand.log (it wasn't clear to me there were 3 places the errors could have been logged to)

**Comment by midwan** [comment]
This is actually the same thing. The .lha files from WHDLoad.de do not contain any games, they are just the installers.
You'll need to look elsewhere for pre-installed LHA "packs" if you want those. ;-)

Regarding the documentation about logfiles, I'll add something in the wiki about that. Keep in mind the `runcommand.log` is not related to Amiberry however, that's RetroPie's own log.

**Comment by penx** [comment]
oh ok that makes sense 😄

thanks
