### ISSUE TITLE
Logitech F710 Wireless gamepad - How to install?

### ISSUE THREAD

**Issue by BartP223** [midwan/amiberry#772]
I have installed the DietPI with Amiberry. Everything works fine but I have a problem with the Logitech F710 controllers. They are not shown on the amiberry input menu. Only a mouse and a "keyboard as joystick are available. I tried to install the drivers:

sudo apt-get install xboxdrv

The drivers installed but it had no effect.
How to install these pads?

**Comment by midwan** [comment]
That's difficult to answer... :)

I don't have one of these to test with, but generally we rely on SDL2 and the system drivers for recognizing controllers and joysticks. Newer SDL2 versions add support for more controllers and fix glitches as well, and system drivers (where needed) might help with that.

Maybe there's another driver that does a better job with this controller? E.g. `xpad` might be another choice?

**Comment by BartP223** [comment]
Problem solved.  You need to switch the amiberry fast boot option to normal boot.  Then the pads are available.  Maybe someone will need this information
