### ISSUE TITLE
ArkOS - Button/Mouse Mapping - Amiberry not recognizing all Buttons/Analog Sticks 

### ISSUE THREAD

**Issue by Humungus303** [midwan/amiberry#774]
Hello Midwan!

Under ArkOS (on Anbernic RG351m) the Button Mapping Function does not work properly as it should.
Mapping the **OpenSimHardware OSH PB Controller** works with the Main four Buttons (ABXY) and the DPad
but not the Shoulder nor the AnalogSTickButtons

Also the Joystick Function doesn't apply for the left Analog Stick as general.
The Select and Start Buttons works nice for the Quickmenu/Reset but can not be mapped as well.
To use the OpenSimHardware OSH PB Controller as a Mouse works with the DPAD but not with the Analog Sticks.
In addition the North/South/east/west is totally messed up (North is right,)

Is this an Amiberry issue or an ArkOS?
christianhaitian from ArkOS had no clue on it and refered me to the faqs.
Under emulec on the same system everything works great as always with amiberry newest version
Also the OpenSimHardware OSH PB Controller.cfg is the same.

input_driver = "udev"
input_device = "OpenSimHardware OSH PB Controller"
input_vendor_id = "4617"
input_product_id = "12544"
input_b_btn = "0"
input_y_btn = "3"
input_select_btn = "22"
input_start_btn = "21"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "2"
input_l_btn = "19"
input_r_btn = "20"
input_l2_btn = "25"
input_r2_btn = "26"
input_l3_btn = "23"
input_r3_btn = "24"
input_menu_toggle_btn = "2"
input_enable_hotkey_btn = "7"
input_exit_emulator_btn = "6"

this is the one from the ArkOS system. everything seems good to me. Don't know what to do!
Do you have any idea? Thank you in advance midwan! have a good weekend

PS: I have to say that i use Amiberry since it was released years ago and you are my Hero Midwan as Horace is and all the others who made this possible. Thank you so much ! Also keeping up that support is quit impressive. Guru Meditation for all of us :)

**Comment by midwan** [comment]
@Humungus303 
Thanks for the kind words :)
Which version of Amiberry are you using please?
You mention "latest one" but is that the latest stable or beta? You can find out in the GUI -> About panel.

Since you posted a retroarch mapping above, I'm assuming that's what you're using in your system?

**Comment by Humungus303** [comment]
Hey Midwan!  Thanks for your quick Reply.

I have the last stable version 3.3 running (please correct me if i am wrong). Had the 3.3 on both System (Emulec/ArkOS)
and as i mentioned in EMulec with the same version everything is functioning correctly. Don't get me wrong.
Everything else in AMiberry is working on ArkOS great. The OS and Amiberry Itself were fresh installed & updated.
I am a little bit familiar with emulating doing this now for 30 years..sadly :) The OpenSim....cfg is the same on both systems.

Right now i have no clue. I think that it is not a Amiberry Problem because of it's stand alone ability and working on EMulec.
The messed up ABXY where North is right gives me something to think of. Also that the Select/Start are working for the Reset/Menu but not for mapping confuses me. Also you can Map the Main 4 buttons for the Hotkey using it But nothing else.

Kind words are not enough Midwan/Horace for what you have achieved with this. I haven't used any AMIGA emualtor in my life that it is near your digital child. everything is working like a charm and that since you released it. Had never ever Problems getting Games/Progs/Demos started. Even the most Unknown stuff is working Great. People having Problems(Stuttering/soundissue) getting started mostly don't know much about it and are confused with the Kickstarts and WHDLOAD packages..

(OK there are 2 things i haven't get started for the last years. but they are a little bit special. It'S the fanmade EOB1&2 AGA WHDLOAD package with Automapping .running nice on FAUAE but Amiberry still gives me the Info that the package is write protected :)   ah.. also the last BattleIsel1.9 package is not runnning as it should but i hadn't time since to dig into it.
Greetings midwan. Wish you all the best. And thanks for your reply!

**Comment by Humungus303** [comment]
i forgot:

tonight i will flash the 351Emulec  for testing.
Such a great device these Anbernic pieces. If someone had said to me 40 years ago that i can play Amiga Games on a GameBoy Like Device with color monitor i would have laughed at him saying that the Amiga is to fast for that.
For me the Mouse2Analog option is essential. Maybe i should switch over to another OSystem. This Problem is making me itch :) (Christian from ArkOS told me to switch over to PUAE. But i will not.)

**Comment by Humungus303** [comment]
351Emulec update:

Amiberry Control Functions are working  under the new 351Emulec release.
Only thing is that the Left Analog Stick is reversed on all axis with the Mouse mapped and the right Analog Stick is "normal".
Also it is reversed in the Amiberry Menu.

Button mapping is working correct. North is North :) And all Buttons can be mapped.
Analog Sticks are working as they should as Joysticks also the left one is reversed.

**Comment by Humungus303** [comment]
First of all sorry for the many posts and writing off-topic also but i am so excited speaking to you personally midwan:) . For me as a silent user of the net it is a great honor sharing my thoughts with you!

Emulec update:

i forgot to mention that under Emulec everything is good with Amiberry. Right out of the box. All Axis work correct/Mapping etc.

Only different thing is that the Hotkeys are set to X and A (North/East) by default.

**Comment by midwan** [comment]
@Humungus303 
This still feels like a controller mapping issue, in the retroarch file? Amiberry tries to use that for the controller buttons and axes, including options to reverse axes. Have you checked the related wiki articles? https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers

**Comment by Humungus303** [comment]
i think if the retroarch.cfg would be corrupted/modified the controlls wouldn't function at all even on the retroarch based emulators. This really gives me a headache midwan.
(i recognized watching a Tutorial Video about ArkOS using Amiberry - from Retrogamecorps - the Guy shows how it works, playing Apydia (WHDLOAD package). And he tries, for a split second, the Analog Buttons but it is not working so he switches back to DPAD. Also he mentioned that it is very laggy. But the lag is coming from his old WHDLOAD Package.)

After flashing every OS twice I am done for now with this. If you have no idea, no one will.
Every System was updated, fresh installed, no tweaks or configs changed. Emulec is running, 351lec is reversed and ArkOS will not use half of the Buttons. I hate my hobby

**Comment by Humungus303** [comment]
me again.
sorry for the lag of information midwan.
Yes i have checked the retroarch files/cfg. as the amiberry configs. - and i have printed out the wiki article twice and have stored one under my pillow for the last 2 days of sleep and the other one is kept close to my Amiga Shrine right next to a Picture of you and Horace decorated with flowers built out of 3.5 Floppy Disks - Formated with x-copy  :)

**Comment by midwan** [comment]
It's hard to be sure, since I don't have such a device to test here with... But in most cases this is a mapping problem, as I mentioned above. Unless we've run into some bug regarding the parsing of the retroarch mapping file in Amiberry, but that would be the first time I'm seeing this kind of problem.

It might be worth testing with the latest beta version, since I've reworked a lot of the controller handling code there. Maybe this was a bug in v3.3 that got fixed in the latest version?

To test with the latest beta, you'd need to compile that from source (instructions are in the Readme as usual). Otherwise just wait until that is finalized and released, and the distro maintainer adds the newer version?

**Comment by Humungus303** [comment]
Thanks Midwan for your effort as always. 

351elec -  SOLVED:

As you mentioned it was the Retroarch Mapping. But it's quite strange. In fact i haven't changed anything.
Just for testing i was using the Controller-Mapping Setup through Emulationstation. That didn't change anything so i compared the retroarch.cfg with the old one and every setup was the same as expected.
But then i overwrite the retroarch.cfg with the one i had on my Desktop PC for testing. Exactly the same.
but now it's ok. No more Reverse. Strange isn't it? 

I will try something tonight on ArkOS and will post the Solution if i find one. And as you mentioned. I think on long terms this will be fixed through upcoming updates...as the OS:s are very young for these devices,

**Comment by Humungus303** [comment]
ArkOS - SOLVED:

This *controller*.cfg will do. Anyway. Axis are now correct for gaming. Every Button map-able. Amiberry Menü with LefrAnalogStick still reversed. Thanks Midwan. You were right. as always! 


input_device = "OpenSimHardware OSH PB Controller"
input_driver = "udev"
input_vendor_id = "4617"
input_product_id = "12544"
input_r_y_plus_axis = "+3"
input_r_x_minus_axis = "-2"
input_l_btn = "4"
input_load_state_btn = "4"
input_start_btn = "6"
input_exit_emulator_btn = "6"
input_r_y_minus_axis = "-3"
input_down_btn = "h0down"
input_volume_down_btn = "h0down"
input_l_x_plus_axis = "-0"
input_r_btn = "5"
input_save_state_btn = "5"
input_right_btn = "h0right"
input_state_slot_increase_btn = "h0right"
input_select_btn = "7"
input_left_btn = "h0left"
input_state_slot_decrease_btn = "h0left"
input_l2_btn = "10"
input_rewind_btn = "10"
input_l3_btn = "8"
input_l_y_minus_axis = "+1"
input_up_btn = "h0up"
input_volume_up_btn = "h0up"
input_a_btn = "0"
input_b_btn = "1"
input_reset_btn = "1"
input_enable_hotkey_btn = "7"
input_l_y_plus_axis = "-1"
input_r2_btn = "11"
input_hold_fast_forward_btn = "11"
input_r3_btn = "9"
input_fps_toggle_btn = "9"
input_x_btn = "2"
input_menu_toggle_btn = "2"
input_l_x_minus_axis = "+0"
input_y_btn = "3"
input_r_x_plus_axis = "+2"

**Comment by midwan** [comment]
Thanks for confirming! :)
