### ISSUE TITLE
Elfmania -  image flickers while loading

### ISSUE THREAD

**Issue by BartP223** [midwan/amiberry#778]
Amiberry 3.3 with RetroPie Buster 4.7.1.

The game is in whdload version. I tried also on different configurations.
Anyone know how to fix this?

**Comment by AnalogHero** [comment]
I think this is os swapping causesd by the whdload slave. Dont know how to fix though.

**Comment by nemo93** [comment]
@BartP223 thanks for reporting back and apologize for the delay. This package starts with `NOWRITECACHE` which is causing the flashing you see. Removing that option from the startup-sequence will fix it. 

With Amiberry 5.0 it's possible to set `default_whd_writecache=yes` from [amiberry.conf](https://github.com/midwan/amiberry/blob/v5.0/conf/amiberry.conf) this will fix your issue. It's not something that can be fixed from xml.

As not related to Amiberry I'd recommend to close this ticket off.
