### ISSUE TITLE
Cycle exact doesn't work

### ISSUE THREAD

**Issue by kowidoza** [midwan/amiberry#780]
**Describe the bug**
The Cycle exact  (full) option in all recent betas doesn't work. Even if it is selected, starting emulation and switching back to GUI makes it turn off by itself.

And it's not just the GUI, because demos like **9 Fingers** are completely desynchronized now, unwatchable (whereas they work fine in the last release version).

Tested on Raspberry Pi 400 on multiple operating systems: Manjaro Minimal 64-bit, Ubuntu Server 64-bit, Raspi OS 32-bit and various SDL2 versions (.12 and .14).  64-bit builds were built with PLATFORM=pi64-dispmanx option and the 32-bit RaspiOS build was built with PLATFORM=rpi4 option.

An additional problem under Manjaro and Ubuntu (both in console, fkms) is that the mouse cursor doesn't work in GUI. The mouse actually does work but its actual cursor is invisible (so it is a hit and miss) whereas the visible cursor remains inactive in the upper left corner. 

**To reproduce**
- the Cycle exact issue:  launch the 9 Fingers demo and see how distorted it plays. Also switch back to GUI and note that the Cycle exact option gets automatically switched off
- the mouse issue: launch beta in above mentioned OS'es and note that the mouse cursor doesn't work.

**Desktop (please complete the following information):**
Device:  RPI 400
OS Manjaro Minimal 64-bit, Ubuntu Server 64-bit, fkms
-RaspiOS 32-bit X11
- Amiberry version: all recent betas (Feb & March 2021)
- SDL 2.0.12 & 2.0.14

**Comment by midwan** [comment]
That's because that feature is not implemented yet :)
It's planned for a future release, but since the option from the config files are already in place and interpreted normally, I added the checkboxes in the GUI. Perhaps it should be disabled, since it doesn't do anything if you enable it anyway.

The secondary "Cycle Exact" option regarding Memory does have some minimal implementation, but again it's not feature-complete yet.

I haven't tested 9 Fingers recently, but is this a problem only happening in the latest versions (vs earlier ones)?

**Comment by kowidoza** [comment]
Oh, I see :)  Sorry for false alarm then ;)

But if so then something else must have changed considering the very bad behavior of 9 Fingers demo.  Please, try it yourself to see what I am talking about.  Even if CPU speed and all other options are set to match A500 speed, the demo runs much faster and gets totally out of sync.   It works perfectly fine on version 3.3 but goes nuts on all recent betas...

**Comment by solskogen** [comment]
Do you have JIT enabled?

**Comment by kowidoza** [comment]
Of course not.  As I wrote, the settings are to match A500 speed, i.e. 68000 CPU (which doesn't even allow JIT, right?), 7 MHz, More compatible, no FPU, OCS chipset, and so on.     As I wrote,that same config gives perfectly smooth demo execution on 3.3 (and earlier) versions but completely distorts it on all recent betas.

Please simply launch that demo and see it yourself....

**Comment by ninjaweb62** [comment]
I made some test. I suffer the same lags & resync problem s kowidoza. It disappears when using Line mode/Single in Display menu instead of Double or Scanlines. A similar behavoiur appears when using a CD32 emulation config: the boot screen animation is jerky as soon as is starts if no using Single Line mode.

**Comment by kowidoza** [comment]
In my case, Line Mode / Single was the mode that I was using by default and it is affected. Switching to any other line mode doesn't help, either. All other options are the standard Quickstart "most common" A500 config, not modified.

EDIT:  I've just discovered that the demo works perfectly smooth on the default A1200 quickstart configuration (68020, 14 MHz, 24-bit, More compatible, AGA).  So maybe it is something 68000 CPU emulation related?

**Comment by midwan** [comment]
The latest beta in the `dev` branch just got correct Cycle-Exact 68000 emulation (among other things), so perhaps this is resolved with it. I will run some tests with 9 fingers later, but maybe you'd like to test from your side also?

**Comment by kowidoza** [comment]
Fantastic job!  It works PERFECTLY FINE now! Not only 9 Fingers but also a couple of other demos which used to have strange timing issues.  Now they're as smooth as on the A500 itself :-)

THANK YOU!
