### ISSUE TITLE
AHI(UAE) driver is working or not?

### ISSUE THREAD

**Issue by Nasedo73** [midwan/amiberry#781]
**Describe the bug**
I read your reply about AHI driver from May 2020, when you replied:
"AHI support is not yet implemented in Amiberry, sorry."

I would accept this, as an answer, however AHI/UAE is working for some, but not for me. Let me explain it.

I had a chance to test PiMiga (versions 1.4 and 1.5) based on Amiberry 3.3 and two versions of 3.4 BETA. I was able to test it, and noticed AmiAmp is playing MP3. AHI device was set to AHI/UAE, and MP3 played as it meant to be.

I was testing Amiberry 3.3 and 4.0RC on Raspberry OS (full and lite), Manjaro, DietPi, and never was able to use AHI/UAE output for AmiAmp and play MP3 files. No sound, behaviour of progress bar was too quick, sometimes system became not responsive.
Base for my test was ClassicWB - and I made sure AHI/UAE was working on WinUAE - obviously it's not a proof - but I'm trying to point, I know how to play MP3 files in different environment.
I checked and compared all necessary files from ClassicWB to PiMiga, I tried to reinstall AHI from Aminet - nothing helps.

Kickstart 3.1, ClassicWB based on WB 3.1 - platform RPi400.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
The implementation is there for the v4.x version, but something is wrong and it doesn't work yet. It didn't exist at all in v3.3 or previous versions.

**Comment by Nasedo73** [comment]
Thanks for your reply. 
I'm not sure if you ever had a chance to test PiMiga, but it uses your emulator and somehow Chris Edwards has managed to make it work. Maybe it was some sort of workaround, or maybe it's not a pure AHI/UAE or maybe it's some sort od "Linux trick" - but I spent several hours so far and was not able to find anything unusual and nothing to bring me to closure of this problem.
AHI is working - for example when I'm using AHI Unit 1 and set it to: Paula:HiFi 14bit stereo++ calibrated (Freq. 22050Hz, two channels). Only concern is related to UAE.audio

**Comment by midwan** [comment]
That's what I mean also, it will work if you use Paula modes, but then you're not using "native" AHI drivers - that's the part that doesn't work. :)
