### ISSUE TITLE
Amiberry 4.0 on RetroPie does not start with JIT

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#784]
Raspberry Pi 4 with RetroPie and AmigaOS 3.1.4.1

Hello Dimitris,
thanks for releasing Amiberry 4.0.

While the 64-bit version has been running problem-free under Manjaro so far, I have the problem with the 32-bit version under RetroPie that amiberry does not want to start as soon as JIT has been activated. You then always come back to the RetroPie interface without being able to access the amiberry menu with the F12 key. If JIT is deactivated there are no problems. 

Cheers
Retro1968

**Comment by midwan** [comment]
@Retro1968 
did you compile it from source or use the binary please?

**Comment by Retro1968** [comment]
I uninstalled version 3 first and deleted the config folder. Then I compiled the source code of amiberry 4.0.

**Comment by midwan** [comment]
I can't recreate the problem here, so far.
If I select A4000 from Quickstart (which enables JIT), it gets me to the Kickstart screen normally.

I compiled the binary manually on the same device, then copied the file over to the expected location. I'll try with RetroPie's script also, in case it makes a difference...

**Comment by midwan** [comment]
Confirmed, if compiled using RetroPie-Setup's script then it crashes when JIT is enabled.
But it works normally if compiled manually. Something must be going on with the compile script I guess?

**Comment by midwan** [comment]
I'm reporting this to the RetroPie team: https://github.com/RetroPie/RetroPie-Setup/issues/3313

**Comment by Retro1968** [comment]
If you install the precompiled binaries via the RetroPieSetup, you get amiberry version 3.3. If you choose the source code you get the faulty version amiberry 4.0.

**Comment by midwan** [comment]
> If you install the precompiled binaries via the RetroPieSetup, you get amiberry version 3.3. If you choose the source code you get a faulty version of amiberry 4.0.

That's expected, the RetroPie team hasn't updated their binaries yet. But compiling from source should have worked.

**Comment by Retro1968** [comment]
With version amiberry 4.1 the error no longer occurs.
