### ISSUE TITLE
Wrong compiler option: -Ofast

### ISSUE THREAD

**Issue by PandTomB** [midwan/amiberry#786]
With the option -Ofast, gcc enables -ffast-math, which doesn't handle invalid floating point results as IEEE or ISO rules/specifications says.
This results in wrong emulation of Amiga floating point opcodes in some special cases. 
Use -O3 as best optimizer option.

Regards,
TomB

**Comment by midwan** [comment]
@PandTomB 
Thanks for the tip, I'll update the Makefile accordingly.
