### ISSUE TITLE
Blacker than black option wierd

### ISSUE THREAD

**Issue by AnalogHero** [midwan/amiberry#788]
The option blacker than black messes up the color pallette. If my guess is right, it looks like if the green is missing.

**To Reproduce**

1. Go to menu/Display

2. Click on blacker than black

**Expected behavior**
Im not sure what this option does anyway. I only noticed this bug because it was for some reason turned on in on of my configs.

Thanks for looking into this minor issue.
Happy Easter to all!

**Comment by midwan** [comment]
Are you sure the color problem you're seeing is related to this option?
It's only supposed to change the gamma values of all RGB colors, to make the border blank "black" appear darker. It doesn't change the palette...

But what _can_ affect the palette is the change of the 32-bit RTG pixel format, that was done as part of 4.x. If you're only seeing incorrect colors in 32-bit modes and not in 16-bit ones, then it could be that.

Open the RTG Panel in the GUI, and make sure both 16/32-bit pixel format options are set to the values with the asterisk. Then reconfigure your workbench Screenmode (if you change pixel format here, your previous screenmode prefs will no longer be valid).

**Comment by AnalogHero** [comment]
Checked this. Both options are the ones with an asterisk. Here are some screenshots:
![PXL_20210403_191752775 MP](https://user-images.githubusercontent.com/21363055/113489104-6db3d380-94c2-11eb-92a7-4726794e4280.jpg)

![PXL_20210403_191732050 MP](https://user-images.githubusercontent.com/21363055/113489100-6987b600-94c2-11eb-916b-2edea34b4b23.jpg)

![PXL_20210403_191710432 MP](https://user-images.githubusercontent.com/21363055/113489091-5ffe4e00-94c2-11eb-97e0-5473c1edbc8a.jpg)

Just selected blacker than black. No other changes made. Maybe its my tv? Or any other setting on the Raspberry?

**Comment by midwan** [comment]
Ok, the RTG settings are not related to games, since those don't use such modes. I'll do some testing to see and get back on this one.

**Comment by midwan** [comment]
This was indeed a bug, due to a typo. It should be fixed now, with v4.1.1
