### ISSUE TITLE
SDL 2 | Autostart configuration w/o GUI: "Unable to set video mode" / black screen

### ISSUE THREAD

**Issue by rabejens** [midwan/amiberry#79]
When I deactivate "Show GUI on startup" in my autostart configuration, the emulator locks up when it wants to set the needed resolution.

When I start such a configuration from the console like doing `./amiberry-sdl2 -f nogui.uae`, I get `Unable to set video mode`

When I boot DietPi to directly launch such a configuration, I get a black screen.

In both cases, the Pi doesn't respond any more locally, but it still responds to SSH.

**Comment by Fourdee** [comment]
@rabejens 
Thanks for the report 👍 
We'll be implementing AmiBerry SDL 2 soon into DietPi, i'll take a look at the reported issues at the same time.
https://github.com/Fourdee/DietPi/issues/850

**Comment by CypherXG** [comment]
I start my Emulator with ./amiberry -config=myconfig.uae -s -use_gui=no
and it works perfectly with all my configs like Amikit etc.
In my Config i deactivate Show Gui  on startup.
That's all.

**Comment by midwan** [comment]
@rabejens 
Thanks for the report, I'll test and see if I can recreate this...

**Comment by midwan** [comment]
@CypherXG 
Did you test this with the SDL2 version also?

**Comment by CypherXG** [comment]
I compile your Version that you write on your Site:
https://github.com/midwan/amiberry for my Pi3. 
That is with SDL2 or not? Or is there a separate SDL2 Version?

**Comment by midwan** [comment]
@CypherXG 
The master branch is still using SDL1, the SDL2 version is in a separate branch "sdl2". Unless you checked out the SDL2 branch you're still using the older version. :)

The plan is to move the SDL1 version to a separate archive branch and replace the master with the SDL2 one, as soon as that version is stable enough for a release.

Regardless, I just pushed a fix for this bug, thanks for reporting it @rabejens !

**Comment by CypherXG** [comment]
Mhhhh
How should I say that. The old version runs somehow better.
When I have just launched the new version, I first thought "Huch what is the happening there"
I do not like the surface.
And when I started my Amikit configuration, I've immediately determined again that the resolution does not fit.
In the old configuration, the image is adjusted to full screen, but not in the new one. There I have black edges left and right.
OK. The Keyboard LED's working here. This is the only one i missed in the old version. I know there is a bug with root and no root. Maybe you can correct that still.

So, as I said, for the time being I stay with the old version :-) But if I still find bugs, I write of course. P.S. Is there a way to send the FloppyLED signal directly to the GPIO Conntector? So it would be an ideal solution to use the Pi in a real Amiga case together with the emulator.

**Comment by midwan** [comment]
@CypherXG 
The resolution is automatically adapted to keep the correct aspect ratio, so it depends on what resolution you're currently running on the Pi vs what resolution you requested the emulated Amiga to open.

For example, a 320x256 screen will not stretch to 1080p, it will be scaled as much as possible vertically but it will leave borders left and right. That way, the image looks correct and not distorted. On the other hand, if you open a Picasso96 mode you can display anything supported, even a 1080p Workbench in all its glory. :)

I'm not sure what you mean by "you don't like the surface", but if you have suggestions for improvements, they are always welcome (as well as bug reports of course). Please let's do those on new issues though, to avoid losing them under closed ones. ;)
