### ISSUE TITLE
Using gamepad as mouse input?

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#792]
This is more of a question if I’m missing something obvious.

tried both having keyboard+mouse+gamepad connected as well as only gamepad connected but I can’t get the gamepad (SN30Pro) to move the cursor. Maybe intended or is there a way to use the gamepad as mouse input with nothing else connected?

tried both adventures of Willy beamish and beneath a steel sky with same result.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
You need to set the gamepad in Port 0, where a mouse is expected by the emulated system.
If you have analog sticks, you can set those to move the mouse by using the "Mouse Stick 0:" option as well.
