### ISSUE TITLE
Unable to open gui from joypad hotkey

### ISSUE THREAD

**Issue by AnalogHero** [midwan/amiberry#794]
When you launch a game from emulationstation which has no attached .uae file, you cant enter the gui from your retroarch joypad. If you however enter the gui from keyboard then exit the gui, your hotkey works.

Running latest 4.1.1.

**Comment by midwan** [comment]
Have you tested this with the latest 4.1.2?
Perhaps this was the same bug about reading joystick input that got fixed there as well...

**Comment by AnalogHero** [comment]
Tested now with latest dev. 4.x beta (2021-04-09).
Works perfect. Bug fixed!

**Comment by midwan** [comment]
Thanks for confirming!
