### ISSUE TITLE
GUI crashes when clicking LOAD (configuration)

### ISSUE THREAD

**Issue by andiweli** [midwan/amiberry#797]
**Describe the bug**
My Raspberry Pi 3B+ completely freezes, when I hit the LOAD button when selected a configuration.

**To Reproduce**
I only have a "default" configuration (so just one config). Usually simply clicking "START" starts the emulator. But as soon as I click "LOAD" button - just to load the configuration and edit - the GUI freezes. It doesn't bother me, since the default configuration is loaded by default, so it can be edited anytime.

**Expected behavior**
Load the configuration to be able to edit it.

**Desktop (please complete the following information):**

Fresh set up 32GB microSD with Amiberry 4.1.2 and a fresh configuration (just as the config I sent you).
- OS: Raspbian Lite
- Version 2021-03-04

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
@andiweli 
I can't recreate this so far. I tried removing all other configs except one, renamed it to `default.uae` and tested.
I can use Load as many times as I want, it never crashes on me.
Can you try with a new (test) config, instead? Just to see if it's related to something in the file or not?

**Comment by andiweli** [comment]
Just tried a bit... it seems to crash when I set my default resolution in Raspbian to 1366x768 via Raspi-Config.

LOAD works on all resolutions with Amiberry 3.3.
With 4.1.2 it crashes as soon as I set 1366x768, but works with "default" setting in Raspi-Config.

**Comment by midwan** [comment]
I don't have such an option in raspi-config:

![image](https://user-images.githubusercontent.com/3877365/114058056-6a8a6000-9893-11eb-991b-ced2d49350be.png)

Perhaps I need to test this on another monitor...
