### ISSUE TITLE
Adding Key-Shortcut for QUIT snaps GUI to bottom-left

### ISSUE THREAD

**Issue by andiweli** [midwan/amiberry#798]
**Describe the bug**
As soon as I want to define a Key-Shortcut for QUIT the GUI window gets fixed to the bottom left corner of the monitor. You can't press any button anymore because the mouse is still aligned to the centered layout of the GUI. So clicking "Configuration" gets you to "RTG board". 

**To Reproduce**
Try to configure a shortcut key for QUIT. Other shortcuts are no problem. 

**Expected behavior**
Set a shortcut Key. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11447150/113938638-2a779e80-97fb-11eb-8b19-751c741d63b8.jpeg)

**Desktop (please complete the following information):**

- OS: Raspbian Lite

Love Amiberry? (I do!) Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
Which target are you using?
Dispmanx or SDL2?

**Comment by andiweli** [comment]
Sorry, it´s SDL2 on Raspberry 3B.

**Comment by midwan** [comment]
Then I guess you're using KMSDRM? 
- Did you compile SDL2 yourself, since the one from the repo doesn't come pre-compiled with KMSDRM support?
- If so, which version of SDL2 are you using? You can also see that in the About panel of the GUI.

**Comment by andiweli** [comment]
I did compile it on my old installation. At the fresh install I just downloaded it with "apt install".

**Comment by midwan** [comment]
@andiweli 
You cannot use the version from the repositories (with `apt install`) if you want KMSDRM, which you need from RPI OS Lite. At least, you need it if you run it from the console, not sure if you've installed a desktop environment on top?

So perhaps you still have a manually compiled version in your system, and it's using that? In that case, it's worth testing with a more recent one.

I still cannot recreate this, even when testing under the console with KMSDRM on Manjaro (which uses SDL2 v2.0.14). What key did you try to assign to the Quit function? Perhaps that was a combination that triggered a change of the window to "Windowed" mode, and that's why you're seeing this (and I'm not).

**Comment by andiweli** [comment]
Hmm that is quite weird...

I have installed everything via apt-get. Nothing compiled. I am using console and no UI installed. 

I tried compiling SDL 2.0.14 today. But no true colors so far...  

I think the problem is a metre in front of the screen Haha 😂

**Comment by midwan** [comment]
Removing the libraries using `apt-get` will not remove any manually compiled and installed ones, just those that were installed the same way (from the repo). If you had previously compiled it yourself, it might still be there - check under `/usr/local/lib` for example?

**Comment by andiweli** [comment]
There have been some libSDL files which I removed now. 

Now Amiberry starts but I only see a black screen. Just can hear the floppy sounds...

I will try compiling it myself now again...

**Comment by andiweli** [comment]
Ok so I compiled SDL2 from fresh after deleting all the old files in /usr/local/lib.
I did it step-by-step with this guide: https://choccyhobnob.com/sdl2-2-0-8-on-raspberry-pi/
Everything without any errors...

sdl2-config --version gives me a "2.0.15". I also compiled all the utility libraries.
But now when starting Amiberry (3.3 or 4.1.2) it shows:
./amiberry: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

**But the file is there:**

pi@Amiberry:~/amiberry33 $ ls /usr/local/lib
cmake                       libSDL2main.a               libSDL2_net.la             libwiringPiDev.so
libSDL2-2.0.so.0            libSDL2main.la              libSDL2_net.so             libwiringPiDev.so.2.60
libSDL2-2.0.so.0.14.1       libSDL2_mixer-2.0.so.0      libSDL2.so                 libwiringPi.so
libSDL2.a                   libSDL2_mixer-2.0.so.0.2.0  libSDL2_test.a             libwiringPi.so.2.60
libSDL2_image-2.0.so.0      libSDL2_mixer.a             libSDL2_test.la            pkgconfig
libSDL2_image-2.0.so.0.2.0  libSDL2_mixer.la            libSDL2_ttf-2.0.so.0       python2.7
libSDL2_image.a             libSDL2_mixer.so            libSDL2_ttf-2.0.so.0.14.0  python3.7
libSDL2_image.la            libSDL2_net-2.0.so.0        libSDL2_ttf.a
libSDL2_image.so            libSDL2_net-2.0.so.0.0.1    libSDL2_ttf.la
libSDL2.la                  libSDL2_net.a               libSDL2_ttf.so

**Comment by midwan** [comment]
@andiweli 
There have been a lot of bug fixes in SDL2's latest sources regarding KMSDRM, so if you'd like you could test with the latest version from SDL2's repository as well.

@solskogen you're usually testing things with KMSDRM - did you even manage to recreate this?

**Comment by solskogen** [comment]
Sorry, I haven't.

**Comment by andiweli** [comment]
> @andiweli 
> 
> There have been a lot of bug fixes in SDL2's latest sources regarding KMSDRM, so if you'd like you could test with the latest version from SDL2's repository as well.
> 
> 
> 
> @solskogen you're usually testing things with KMSDRM - did you even manage to recreate this?

Sad to say, but I changed to MiST FPGA emulation meanwhile...
