### ISSUE TITLE
Corrupted Graphics in Several Games under 4.x

### ISSUE THREAD

**Issue by GeorgeSpiggott** [midwan/amiberry#799]
Hi I've been going through my collection and I have found the following graphical glitches in games using Amiberry 4.x (currently 4.1.2) that were not present in 3.3.

I'm not using pre-existing config files for any of these games. Running on Retropie 4.7.11 on a 4GB Pi 4.

Alien Breed and Project X: Both games have partially invisible lettering on the menu fonts. 

Nebulus: Sprites leave behind strange blue ghosting/shadows. Also the 'sky' has bocks of miscoloured areas.

Wings of Fury: The info bar at the bottom of the screen has areas of mis-colouring/flashing blocks

Revenge of the Mutant Camels: This is fixed in 4.1.2 but was present previously. I'm including it just in case it is of use. parts of destroyed enemy sprites would remain on screen.

I think these may be caused by the same thing causing the similar Batman/Pinball Dreams errors. I was planning to run through my whole collection  to check before I posted. I will attempt to do so at the weekend. These are the games I have found so far.

Thanks

**Comment by midwan** [comment]
Can you test with `dev` also?
There have been several custom chipset updates merged in from WinUAE, and this is still WIP even there. I expect that we'll fix these when that work is finished and I merge in all the upcoming updates as well.

**Comment by GeorgeSpiggott** [comment]
I don't know how. If there is a guide to setting it up I would be happy to.

**Comment by midwan** [comment]
Here's a quick guide (you'll need to drop to a shell to type these in - use F4 from EmulationStation to do that):

- Clone the repo to a new local directory named `amiberry-dev`, but choose the `dev` branch: `git clone https://github.com/midwan/amiberry -b dev amiberry-dev`
- Go in that new directory: `cd amiberry-dev`
- Compile your version as usual: `make -j4 PLATFORM=rpi4`
Once this finishes, you'll have a binary named `amiberry` in the current directory.

Now to copy it over to the location RetroPie expects it to be:
- Take a backup of your existing binary first: `sudo mv /opt/retropie/emulators/amiberry/amiberry /opt/retropie/emulators/amiberry/amiberry.bak`
- Copy your new binary over there: `sudo cp amiberry /opt/retropie/emulators/amiberry`
Finished. Now you can type `exit` and EmulationStation will start again. When you launch Amiberry, it will be the newer version that runs.

If you ever need to roll back to the previous binary, just rename the file again:
`sudo mv /opt/retropie/emulators/amiberry/amiberry.bak /opt/retropie/emulators/amiberry/amiberry`

**Comment by midwan** [comment]
Keep in mind the `dev` branch version is still under development, and things there are not ready for release yet.
Currently Fast Copper is disabled in it, for example.

**Comment by GeorgeSpiggott** [comment]
I have followed the instructions but I get no picture and slow distorted sound on all games. I should have mentioned that I am using KMS (my very bad) but I don't know the correct make command line arguments.

**Comment by midwan** [comment]
Thanks for the feedback.
Since these changes are still WIP in WinUAE, we'll have to wait until they are finalized to see if all glitches are fixed at that point.
Then I have to see if I can bring back Fast Copper :)

**Comment by nemo93** [comment]
Just in case: I've tested all the aforementioned games on the 5.0 tag with great success. I couldn't see a single issue with those games. One exception though: Mutant Camels as I don't own it I couldn't test that one.

For the record the games are: Alien Breed, Batman the Movie, Nebulus, Pinball Dreams, Project X (both original and Special edition), Wings of Fury.
Test platform: pi4 on current Retropie (4.8). Which means 32-bit Buster and fake KMS (dispmanx backend).
