### ISSUE TITLE
SDL 2 | Font & No Capital letters can be entered in GUI boxes

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#80]
In the chipset section, 'Wait for blitter' and 'Sprites and Sprites vs. Playfield' are slightly cut off.

Is the new font the same as in Workbench/DOS etc. ? It doesn't look quite right, maybe it's a bit too bold as 8's look like 0's in the CPU section.

Also, can't enter capital letters in the Configurations Name and Descriptions boxes.

**Comment by windale** [comment]
The font looks a bit better with the adjusted colour scheme but still doesn't look right compared to workbench/DOS. It might just be me :)

I'm not sure if you could use capital letters when entering config names in SDL2. I can't remember, so don't know if its because of the new font.

**Comment by midwan** [comment]
@windale 
I've fixed the cutting-off of the fields in all the areas, just noticed that you can't type capitals in the Config field.

I'll try to sort that out.

**Comment by rabejens** [comment]
Another thing I noticed: The keyboard layout is fixed at US in the GUI, no matter what layout was loaded by the underlying system.

**Comment by midwan** [comment]
The capital letters input seems to be a bug in Guisan, since it occurs even with its own examples.
Opened separate issues for that there:
https://github.com/mythsman/guisan/issues/1
https://github.com/kallisti5/guisan/issues/4

**Comment by blinkydoos** [comment]
I think the old font looks better as it looks clearer/cleaner. The topaz one looks a bit dark. (Only my opinion :) I can manually change it to the old font).
