### ISSUE TITLE
Sound Time Delay with WHDLoad Games

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#802]
Raspberry Pi 4, amiberry 4.1.2 (32 Bit on RetroPie + 64 Bit on Manjaro), with AmigaOS 3.1.4.1.

Hello friends,
I have added these lines to the s: whdload.prefs file

ExecuteStartup = uae-configuration cycle_exact true cpu_speed real cpu_multiplier 8 cachesize 0
ExecuteCleanup = uae-configuration cycle_exact false cpu_speed max cachesize 8192

This means that WHDLoad games run on 28 Mhz.
https://fs-uae.net/docs/options/uae-cpu-multiplier

I have the following problem even if the option "cpu_multiplier 8" is removed.

The sound comes with a time delay.
Example: I'm driving in Lotus 2 ... then I hit a street sign ... the ping sound doesn't come immediately, but only 1-2 or more seconds later.

I have the problem under 32 and 64 bit.

Cheers
Retro1968

**Comment by midwan** [comment]
Have you tried changing the sound buffer size?
Try setting it to a lower value from the default of 8, let's say 5?

**Comment by Retro1968** [comment]
Thank you mate. Sound Buffer Size 3 was the solution.

**Comment by boras-pl** [comment]
I have just tested v4.1.2 64 bit on RaspiOS 64 bit Lite and suprisingly discovered that there is no any sound delay on WHDLoad games (and sw like PT) when I set Sound Buffer Size to "min". I have set default settings of A4000 - 68030, jit, fastest + RTG. WB 3.1, ClassicWB. Works excellent, no delays, no glitches. An accident?

**Comment by midwan** [comment]
That's why we have a configurable value there :)
