### ISSUE TITLE
Audio & Performance issues with Reshoot-R and other games

### ISSUE THREAD

**Issue by 10MARC** [midwan/amiberry#804]
I have Amiberry set up to emulate a PAL A1200, 68040 JIT, RTG, 64MB ZORRO III. It performs OK overall. I am using the latest version of Amiberry.
It is is running on a pi400, overclocked to 2.1 Ghz (Overclocking did not help). Using a Sandisk 64GB SD Card

Tried it with Reshoot-R (Which runs OK on an unexpanded A1200 if you are careful) and it is a hot mess. Horrible glitchy audio, tremendous slowdowns and generally unenjoyable to play. 
1. Turned off JIT, tested with 68020, 68030 and 68040 - minimal change
2. Adjusted RAM, tried 24 bit and ZORROIII - seems to slow down more if 24bit RAM is even enabled.
3. Adjusted blitter and copper settings. Seems to work best with all turned off. Turning Copper setting on made the graphics a corrupt mess.
4. Adjusted audio settings - no substantial change. still glitchy and slow

Some games work OK, but others like Saint Dragon are also very stuttery and slow, and audio is not accurate. 
All of these games work fine in WinUAE and on real hardware - I even play Saint Dragon on my real A1000 and it runs flawless! ;)

Is this a normal occurrence with some games or should I be looking at some type of solution?

**Comment by midwan** [comment]
It's certainly not normal behavior.
Which version of Amiberry?
Running on what distro?
How did you run the game (WHDLoad, ADF or other method)?

**Comment by 10MARC** [comment]
Latest version of Amiberry from this site. Just downloaded it two days ago. The SDL2 version, as the other version had issues with mouse control on the Amiberry setup screen (as in it really did not work - had to use KB to set it up)
I have it running on the 3/4/2021 Distribution of Raspberry Pi OS - Full Version (with nothing that I know of really running in the background)
This is the full version of the game, installed on a 1 Gig HDF with Workbench 3.1.4, BestWB and Picasso96 installed. That's a pretty normal setup for me.
SaintDragon ran from WHDLOAD and it had really odd slowdowns and audio issues, too. Deluxe Pacman seemed to run OK.
I am using a Logitech 710 controller if that matters.

**Comment by midwan** [comment]
OK, then I suspect I know what's causing this...
Under RPI OS, the recommended version to use for best performance is the Dispmanx one. The pure SDL2 will also work, but it's slower under that distro - which is what's causing the slowdown in various games as you describe.

An alternative, if you want to use the SDL2 version under a desktop, would be to use a 64-bit distro instead: Manjaro has much better performance on the Pi4/Pi400 than the RPI OS, and since it includes the latest versions of kernel/drivers/libraries, Amiberry works better and faster on it as well.

You mentioned the mouse didn't work in the GUI, when using the dispmanx version? What mouse model are you using? If it works in RPI OS, it should also work in Amiberry...

**Comment by 10MARC** [comment]
Oh I see. The Dispmanx was the first version I installed, but when I launch it, the Amiberry screen flows a bit into the overscan area, and the mouse moves, but the hitbox for the mouse is off by about an inch. It hardly works at all on the right sides of the screen where I have to tic little boxes. Once I set it up with the KB and launched it AmigaOS worked and responded ok, it was just the initial AmiBerry screen that the mouse acted weird. Using the cute little pi400 mouse.
I will try the Dispmanx distro again, and maybe the 64 bit too. Thanks!!!!

**Comment by midwan** [comment]
If you have Overscan enabled, you can disable it in `raspi-config` - that should fix the mouse problem you're describing, when using Dispmanx.

**Comment by midwan** [comment]
For the record, I just bought Reshoot-R to test it and it worked perfectly on the following minimal setup I created:
- A1200 with 4MB Fast
- Added Directory as HDD, pointing to the archive that comes with the Download version of the game
- Saved all that as a config so I can easily launch it whenever I want.

If you experience any sound lag, you can also try reducing the Sound Buffer down to 3, from the default of 8.

**Comment by 10MARC** [comment]
I am going to be trying it now. It is an awesome game, and well worth the price you paid for it! The guy who did the graphics did my logo - Kevin Saunders. Talented crew working on that game.
Thanks for all your help! I will let you know when my review of Amiberry goes up!
