### ISSUE TITLE
Some gamepad button mappings are weird.

### ISSUE THREAD

**Issue by boras-pl** [midwan/amiberry#805]
**Describe the bug**
Amiberry has a great feature that allows to assign gamepad buttons to some functions, however some default behaviours are mysterious. I have Logitech Gamepad F710 where all buttons I personally tested with the 'jstest' tool from the 'joystick' apt package. For the needs of this issue I created an example Retroarch configuration. The most important excerpt is:
````
input_a_btn = "1"
input_b_btn = "0"
input_x_btn = "3"
input_y_btn = "2"
input_start_btn = "8"
input_select_btn = "4"
input_l3_btn = "9"
input_r3_btn = "10"
input_enable_hotkey_btn = "6"
input_menu_toggle_btn = "5"
````
It does not matter where the buttons are physically placed on my pad. This is an example only. The important is that all buttons work in the same way and what happens later when I press them. I am not considering axes, dpads, etc. On/off buttons only.

Amiberry recognizes all configuration entries correctly and allows me to define what action should be taken when I press a particular button. I decided to simulate presses of some keyboard letters: a, b, c, etc. and observe what happens in Amiga Shell or any other text editor.
````
joyport1_amiberry_custom_none_south=A
joyport1_amiberry_custom_hotkey_south=1
joyport1_amiberry_custom_none_east=B
joyport1_amiberry_custom_none_west=C
joyport1_amiberry_custom_none_north=D
joyport1_amiberry_custom_none_select=E
joyport1_amiberry_custom_none_menu=F
joyport1_amiberry_custom_none_start=G
joyport1_amiberry_custom_none_left_stick=H
joyport1_amiberry_custom_none_right_stick=I
joyport1_amiberry_custom_none_left_shoulder=J
joyport1_amiberry_custom_none_right_shoulder=K
joyport1_amiberry_custom_none_dpad_up=L
joyport1_amiberry_custom_none_dpad_down=M
joyport1_amiberry_custom_none_dpad_left=N
joyport1_amiberry_custom_none_dpad_right=O
joyport1_amiberry_custom_none_misc1=P
joyport1_amiberry_custom_none_paddle1=Q
joyport1_amiberry_custom_none_paddle2=R
joyport1_amiberry_custom_none_paddle3=S
joyport1_amiberry_custom_none_paddle4=T
joyport1_amiberry_custom_none_touchpad=U
````
![amiberry_custom_controls](https://user-images.githubusercontent.com/59491904/117510798-fa075980-af8c-11eb-8c62-640bd522fe91.jpg)

![amiberry_custom_controls_withhotkey](https://user-images.githubusercontent.com/59491904/117510824-08557580-af8d-11eb-8652-a21c955c8344.jpg)

Until this moment **everything looks good**. Let's go forward and elaborate what happens in following cases:

- Logitech Gamepad F710 has the special 'select' button in the middle with Logitech logo drawn. It is physically assigned to the **'8'** number. According to my configuration expected result is to invoke **input_start_btn** and it should execute what I chose in the **Start:** option. In this case I expect writing of **G**. Instead of this I observe:
  - Amiberry handles the button on it's own and goes to the main menu. I understand that some predefined and default actions are welcome for non-experts. It is ok for me, however I try to override this behaviour and I can not.
  - There is a race condition somewhere and Amiberry sometimes presses the **G** letter in the emulator and when I go back (Resume) I can see a lot of G letters written in some kind of **autorepeating** mode. I does not stop pressing the letter until I press any other key or button. **It is a bug** definitely.
![emulator_unwanted_autorepeating](https://user-images.githubusercontent.com/59491904/117514974-6ab27400-af95-11eb-9dd6-3e514364cc18.jpg)
  - The default behaviour is one way only. It invokes Amiberry menu, but it can not back to the emulator, so it must be done by another method. Not so convenient. 
- Every button I assign to the **input_select_btn** behaves mysteriously. It does not write **E** as I defined but when pressed together with any other button it enables very fast autorepeating mode of the second button. It does not stop until I press any other key or button. Is this intentional? Some kind of autofire? If yes, why Amiberry allows me to define an action under the **Select:** and **HotKey Select:** options if it is ignored anyway?
- Every button I assign to the **input_menu_toggle_btn** instead of writting **F** it does nothing in the emulator. I discovered later that it works like 'Resume' when I am in the main menu. When I want to go to the main menu I need to use the button with HotKey. It is **weird**, but acceptable, however
  - why it allows to define actions in the Custom controls menu if it is ignored anyway? I would like to override this and I can not.
  - Entering to the menu doubles the functionality described in the first case (the Logitech button). Something is redundant here.

Amiberry 4.1.2 64bit compiled manually on 64bit RaspiOS buster. 
All emulator settings except of above are default:
- A4000 68030
- RTG
All configs were purely generated in v4.1.2

If I messed something, do not hesitate to ask me. I will check again anything if needed. At the end of my boring elaboration I need to mention that the project is really outstanding, so I wish you a lot of success. Best Regards. 

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
@boras-pl 
Thanks for the thorough testing. It seems that this area needs some work, but I'll need some time to go into the details and figure out what happened.

**Comment by boras-pl** [comment]
Sure, especially that most of this can be easily worked around by using another button names.

**Comment by midwan** [comment]
If you're using a retroarch mapping on top of custom controls, then it may have hotkey functions configured. Those will override any custom controls normally, e.g. Select might be your configured hotkey, which is used in combination with other keys to perform special functions (like enter the GUI, Reset or Quit the emulator).

Normally those combinations should be greyed out in Custom Controls, so you cannot use them if they are already mapped.

If you do not use a retroarch config at all, then all options are available to map anyway you want.

There were a few bugs in this area that I fixed with the commits above. Perhaps there are more, we'll need to do some more testing to see... :)
