### ISSUE TITLE
Build amiberry on a Dietpi/PI-4 (unexpected size, RGB vs BGR)

### ISSUE THREAD

**Issue by gylead** [midwan/amiberry#806]
Hello,

I just built amiberry (from master) on my Raspberry Pi 4 (dietpi V7.1.2) against the device SDL (which seems to be a little older than the ones installed by dietpi, 2.0.9 vs 2.0.12). I used "`make -j2 PLATFORM=rpi4`".

The amiberry binary from dietpi has 6617476 bytes while my built executable has 9352732 bytes. Surprisingly big difference (`strip -s` doesn't help). I assume some libraries are statically linked instead of dynamically, but ldd does not show that many differences.

The bigger issue I have is that my built amiberry swaps color channel red with blue on Picasso screens (using 1280x720 32bit RGBA).

So my question is if I need to use some more configuration flags to get amiberry of a similar size and to fix the color channel issue?

Regards, gylead

**Comment by gylead** [comment]
I can correct the issue with the swapped color channels by setting rtg_modes to 0x212 (instead of 0x112) in the configuration file. ScreenMode preferences tool now shows screen mode 1280x720 32bit BGRA.

**Comment by midwan** [comment]
The pixel format was changed to match that of WinUAE, in order to make merges from there easier. You can change it from the config file as you did, but there's also a new GUI panel for that (RTG) which allows you to do the same thing (the dropdown entries with the Asterisk are the new defaults).

Note: using another pixel format than the one with the Asterisk (default) is not yet supported, and will give you incorrect colors.

**Comment by midwan** [comment]
@gylead 
Indeed - the config file was a big source of headaches with every new update, due to those differences. It's now 100% synced with WinUAE, and even though it looks worse to look/read, it's much easier to maintain.

**Comment by MichaIng** [comment]
Probably compiler optimisation flags play a role. I use:
```
make -j$(nproc) PLATFORM=$PLATFORM CFLAGS='-g0 -O3' CXXFLAGS='-g0 -O3 -Wno-narrowing'
```

Also I use a minimal SDL2 build with only the features enabled that are used by Amiberry. Not sure if that has an effect on Amiberry binary size as well or only on SDL2 library size.
