### ISSUE TITLE
rp9 format not loading on recalbox 7.2 (Amiberry 3.3)

### ISSUE THREAD

**Issue by thesnable** [midwan/amiberry#808]
Hi!

I am using the latest amiga Forever 9.. and i see that rp9 files wont load on amiberry 3.3.

It just crashed the whole recalbox.

ADF etc. works fine.

**Comment by midwan** [comment]
RP9 support was removed a while back, since nobody seemed to be using it... 
But that was after v3.3 was released.

Still, it wasn't tested much so there could have been some bug that was there for a long time, if it crashed for you.
