### ISSUE TITLE
whdload.prefs problem in amiberry 4.1.2 64Bit

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#809]
Raspberry Pi 4 with amiberry 4.1.2 (and 4.2 beta 2021-04-29) on Manjaro Linux 64 Bit running AmigaOS 3.1.4.1.
WHDLoad Version 18.7.6266

I use this setting in whdload.prefs to optimize WHDLoad Games
https://fs-uae.net/docs/options/uae-cpu-multiplier

**ExecuteStartup=uae-configuration cycle_exact true cpu_speed real cpu_multiplier 14 cachesize 0
ExecuteCleanup=uae-configuration cycle_exact false cpu_speed max cachesize 8192**

While this setting works very well under amiberry 4.1.2 under RetroPie, i.e. at almost 50 Mhz, the WHDLoad games run very slowly under 64 bit. In terms of speed, it looks as if all settings after "cpu_speed real" are ignored under 64 bits. 

If both lines are removed, amiberry runs at maximum speed .

**Comment by Retro1968** [comment]
Has anyone been able to reproduce the problem in the meantime?

**Comment by Retro1968** [comment]
The best way to test this is with Frontier-Elite II. Run this under RetroPie and then under Manjaro Linux with the above WHDLoad.prefs settings (50 MHz). The intro video jerks heavily under 64 bit and the sound is so slow and crackling.

**Comment by midwan** [comment]
@Retro1968 
You can't use Cycle Exact unless you switch CPU to 68000 also, and in most cases that's not needed - it is probably enough to turn off JIT and limit the CPU speed from Fastest Possible to something less, in most titles.
Frontier specifically works fine with JIT and Fastest possible also, from what I've tested.

Have you tried taking away the `cycle_exact` option from your prefs, to see if that helps?

**Comment by Retro1968** [comment]
> 
> 
> @Retro1968
> You can't use Cycle Exact unless you switch CPU to 68000 also, and in most cases that's not needed - it is probably enough to turn off JIT and limit the CPU speed from Fastest Possible to something less, in most titles.
> Frontier specifically works fine with JIT and Fastest possible also, from what I've tested.
> 
> Have you tried taking away the `cycle_exact` option from your prefs, to see if that helps?


I found another solution. If JIT is activated and the speed is set to "Fastest", this entry in whdload.prefs deactivates JIT when starting WHDLoad and reactivates it when exiting.

ExecuteStartup = uae-configuration cpu_throttle -0.0 cachesize 0
ExecuteCleanup = uae-configuration cpu_speed max cachesize 8192

If you want, you can reduce the speed even further. But it is enough for me that JIT is deactivated. 



Read here:
https://fs-uae.net/docs/options/uae-cpu-throttle

cpu_throttle
Description: FIXME
Default:
Range: -900.0 - 5000.0
Type: float

FIXME: describe what it does

In cycle-exact-mode, this option cannot be used and is locked to 0.0.

In approximate mode, this option can be used with the range -900.0 - 5000.0
to speed up or slown down the emulated CPU. In fastest-possible mode,
you can only use this option to slow down the emulation (-900.0 - 0).

**Comment by midwan** [comment]
You can deactivate JIT by just using `cachesize 0` to disable it, and then `cachesize 8192` to enable it. 
But good that you found a solution that works for you. :)
