### ISSUE TITLE
SDL 2 | File requester list position

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#81]
When picking a disk image in the file requester and then opening it again to pick another game/disk the list position has shifted a few pages.

Also, the mouse is a bit sluggish/stutters when the requester is open.

**Comment by windale** [comment]
I think the list position shifts away from the previously selected file a different amount depending on how many files are in the directory. Doesn't happen on SDL1. (More files mean more sluggish mouse also, which I didn't notice happening on SDL1).

**Comment by blinkydoos** [comment]
Now the builds have been merged this also happens on SDL1. When going back to the file requester, the previously selected file is off screen (sometimes several pages).
