### ISSUE TITLE
Swap ports and mouse emulation

### ISSUE THREAD

**Issue by redm123** [midwan/amiberry#811]
I'm not really sure if this is a bug, or I just still haven't understood something how the controls mapping works. So bear with me, it's a bit confusing ;)

**Describe the bug**
I have a mouse as Mouse in port 0 and a joystick as Joystick in port 1. When I swap ports (by mapping hotkey+A/East to "Swap joystick ports") this works fine for buttons/keys (B/A trigger LMB/RMB actions), but not for cursor movement, i.e. joystick up/down/left/right does nothing. 
If I configure the same joystick as Mouse in port 0, which is as I understand is the same the swap does, everything works as expected, I can move and click (except that the joystick is in port 0, of course..).

**Expected behavior**
A/B act like mouse buttons, up/down/left/right move the mouse cursor.

- OS: Recalbox 7.2.1
- Amiberry: v3.3

**Additional context**
I'm trying to find a way to have some basic mouse support (port 0) while using a joystick (port 1). Mainly to go through some cracktro for otherwise joystick games. I could probably do some "Custom controls" mapping or some other way. But as I'm using a Competition Pro I'm somewhat limited with available buttons. And sometimes I'm using other controllers, so it would be nice to have something consistent across all devices.
So I figured the easiest thing might be swapping the ports by hotkey+A/East. Go through the cracktro and swap back.

**Comment by midwan** [comment]
There was a bug which got fixed with a recent update, which affected this behavior in 4.1.4.
This is now fixed in the latest version from the `master` branch, and will soon be released as part of 4.1.5.
Please test with the latest version and report back if you still have an error about this.
