### ISSUE TITLE
Fire-button not working on Parallel ports

### ISSUE THREAD

**Issue by zeppari** [midwan/amiberry#812]
Looks like there's something wrong with the Parallel port joysticks. I've tried with few different games and with few different setups, but can get fire buttons to work for players 3 and 4. I've tried with 8bitdo SN30 Pro and iCode Retro Gaming Adapter, X and Y axis works fine, but no fire power.....

Amiberry v4.1.2 (4.0 / 4.1 / 4.1.1 too )
RetroPie v4.7.12

**Comment by midwan** [comment]
This is now fixed in both `dev` and `master`.
The next release will include it, but you can already grab the latest sources and compile it, if you want it right away. :)
