### ISSUE TITLE
WHDLoader ending in blank screen

### ISSUE THREAD

**Issue by fentimanj** [midwan/amiberry#813]
I've installed Amiberry on my Pi400.  Games are all showing up on main screen, and appears to have picked up the ROMS correctly and set up the links.  But when I go to launch a game it brings up the AmiBerry logo, then shows a Amiberry WHDload Autobooter screen (where is says patch not found) and then just goes to a blank screen.  If I press F12 it'll take me back to the config screen, so I know the Pi hasn't crashed.  Just nothing more is happening.  Any thoughts or tips as to what I might be doing wrong?

**Comment by nemo93** [comment]
Let's continue that discussion on Retropie's [forum](https://retropie.org.uk/forum/topic/30568/amiberry-frozen-launch-screen) would you? This in order to not duplicate issues.

**Comment by midwan** [comment]
As I posted on the Facebook page also, this sounds related to the .lha filename not being recognized. @nemo93 is on the right track with the information he's asking about on the Forum, so it's best to follow that for now.
Closing this here to avoid duplicates...
