### ISSUE TITLE
narrowing conversion errors when compiling cpustbl.cpp

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#815]
**Describe the bug**
I'm currently compiling new Amiberry binaries on Debian/Raspbian Buster and Bullseye and it fails with a large number of these errors:
```
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘252’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘254’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘252’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘254’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘252’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘254’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
src/cpustbl.cpp:12112:9: error: narrowing conversion of ‘252’ from ‘int’ to ‘uae_s8’ {aka ‘signed char’} [-Wnarrowing]
```
It seems to be related to the new compiler version, but I'm not experienced enough to know details: https://stackoverflow.com/questions/51861932
I then added `-Wno-narrowing` to `CXXFLAGS` which makes the build succeed, but it's probably better to solve the underlying reason for the warnings/errors instead of disabling/ignoring them.

**To Reproduce**

1. Start with a fully upgraded Debian or Raspbian Buster or Bullseye

2. Compile SDL2, capsimg and install with other required libraries

3. Compile Amiberry

4. See first `-Wnarrowing`-related warnings, then errors which make the build fail.

**Expected behavior**
No warnings, at least no errors.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
This seems like a compiler configuration thing.
I don't get it at all on Manjaro and RPI OS, but I did see it on other Ubuntu-based distros.
The underlying problem is of course the conversions themselves, but those are not done by me, so I'll have to flag this on the maintainer of the CPU/JIT code and see if he has any plans to fix it. :)

**Comment by MichaIng** [comment]
I definitely saw it on Raspberry Pi OS Buster, but probably there was a fix in the meantime 🤔.

> I'll have to flag this on the maintainer of the CPU/JIT code and see if he has any plans to fix it. :)

Many thanks for sending it upstream 👍.

**Comment by midwan** [comment]
@MichaIng 
Is this related to #966 as well? Do you still get errors after that?
Warnings are one thing (which is still something that could be fixed upstream), but you should definitely not get errors about it.

**Comment by MichaIng** [comment]
Since you set this in the [Makefile](https://github.com/midwan/amiberry/blob/653a212/Makefile#L21) now, I don't get the errors anymore. But probably we should remove the flag and see whether it has been solved upstream. Will do that now 🙂.

**Comment by midwan** [comment]
@MichaIng 
Should we close this case for now then?

**Comment by MichaIng** [comment]
I tested the build after removing the flag from `Makefile` on Raspbian Bullseye and x86_64 Debian Bullseye and it still fails, i.e. `-Wno-narrowing` is still required. I'll leave it up to you whether you want to keep this open for tracking the upstream report (no reaction yet 😢) or not. I cannot evaluate whether this has any negative effect for Amiberry or not.

**Comment by midwan** [comment]
@MichaIng 
OK, thanks! I will close this for now, and monitor the upstream one I have opened for any updates. If this gets fixed there eventually, I'll merge it in anyway.
