### ISSUE TITLE
amiberry-v4.1.2-rpi4-64bit throws `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by boras-pl** [midwan/amiberry#817]
**Describe the bug**
amiberry-v4.1.2-rpi4-64bit.zip taken from Releases
OS: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/2021-05-07-raspios-buster-arm64-lite.zip
Installation in accordance to https://github.com/midwan/amiberry/wiki/Compile-SDL2-for-KMSDRM (Minimal requirements)

Results:
````
pi@raspberrypi:~ $ cd amiberry-rpi4-64bit/
pi@raspberrypi:~/amiberry-rpi4-64bit $ ./amiberry 
./amiberry: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./amiberry)
pi@raspberrypi:~/amiberry-rpi4-64bit $ dpkg -l libc-bin
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libc-bin       2.28-10      arm64        GNU C Library: Binaries
pi@raspberrypi:~/amiberry-rpi4-64bit $ apt-cache madison libc6
     libc6 |    2.28-10 | http://deb.debian.org/debian buster/main arm64 Packages
````
Has the release been prepared on another OS? Manjaro?

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
The 64-bit binaries are compiled on Manjaro Linux, so they will probably fail on other distros.
