### ISSUE TITLE
Problems upgrading my Rpi3 3.3 DMX Amibian

### ISSUE THREAD

**Issue by andiweli** [midwan/amiberry#818]
**Describe the bug**
Amibian 3.3 DMX Rpi3 working perfect.
Upgrading to anything above DMX 4.0 results in a black screen. GUI is initially shown, I start the emulation, I can hear the floppy noise and have black screen. Pressing F12 only shows the pointer on a black screen. Pressing the area where the QUIT-key should be results in quitting Amibian GUI. Overlay tabs for DF0/FPS/etc aren't visible in default and RTG-mode after I start the emulation.

**To Reproduce**
Use the same config settings (I created a new config with same settings) as for 3.3 on a DMX 4.x build.

**Desktop (please complete the following information):**

- OS: latest Raspbian OS (downloaded yesterday)

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
How did you upgrade?
Did you use a pre-compiled binary of v4.1.2?

If so, then please try compiling it from source instead, and see if that version works better for you. There was a bug related to this, that I only fixed recently, but I didn't compile new binaries after that...

**Comment by andiweli** [comment]
> How did you upgrade?
> Did you use a pre-compiled binary of v4.1.2?
> 
> If so, then please try compiling it from source instead, and see if that version works better for you. There was a bug related to this, that I only fixed recently, but I didn't compile new binaries after that...

Thanks, tried it and it works. I've got a picture :)

Unfortunately it is damn slow.
FPS counter is down at 20-26.
Was at stable 50 with 3.3 DMX.

**Comment by midwan** [comment]
That doesn't seem normal, it shouldn't be that slow. Have you tried recreating your config(s) from scratch? A lot of options changed since v3.x to match WinUAE, perhaps something there is messing it up?

**Comment by andiweli** [comment]
Yes, I recreated my config from scratch.

Even the Quickstart profiles without disk inserted won't give me more than 20 FPS.

While testing the Quickstart profiles I experienced some strange issue... as soon as I set "Borderless" in "Display" the FPS went up to a stable 50.

I tried that with my config too, I got my stable 59 FPS as soon as I activate and deactivate "Borderless". But when I reload that profile its 20 FPS again... hmm.

**Comment by andiweli** [comment]
> That doesn't seem normal, it shouldn't be that slow. Have you tried recreating your config(s) from scratch? A lot of options changed since v3.x to match WinUAE, perhaps something there is messing it up?

I downloaded the precompiled 4.1.3 today and it has the same issue as my self-compiled one.

It runs on a low 20 FPS until I set to Windowed Mode and "Borderless", reset, switch off "Borderless" again and I have 50 FPS.

**Comment by midwan** [comment]
Hm, I just saw that as well. It's certainly some kind of a bug, I'll get it fixed.

**Comment by midwan** [comment]
@andiweli does it only happen for you as well, if you open the GUI first?
Meaning that if you run the emulator without the GUI, you get 50 FPS as expected.

Try this: `./amiberry --model A1200 -G`

**Comment by midwan** [comment]
v4.1.4 is compiling as a new release - that should fix the bug.
Please let me know if you still have any problems after that!

**Comment by andiweli** [comment]
> v4.1.4 is compiling as a new release - that should fix the bug.
> 
> Please let me know if you still have any problems after that!

Thanks. It is working now 😉
