### ISSUE TITLE
Error compiling dev version from source on RaspiOS Buster Lite

### ISSUE THREAD

**Issue by ninjaweb62** [midwan/amiberry#819]
**Describe the bug**
Get the following errors compiling from source on RaspiOS Buster Lite - SDL2 v2.0.15 Mercurial:
(sorry, I'm not so skilled to be able to correct it)

src/osdep/amiberry_gfx.cpp:267:28: error: conflicting declaration ‘volatile uae_atomic vsync_counter’
 static volatile uae_atomic vsync_counter = 0;
                            ^~~~~~~~~~~~~
In file included from src/osdep/amiberry_gfx.cpp:11:
src/include/custom.h:55:41: note: previous declaration as ‘long unsigned int vsync_counter’
 extern unsigned long int hsync_counter, vsync_counter;
                                         ^~~~~~~~~~~~~
src/osdep/amiberry_gfx.cpp: In function ‘void vsync_callback(unsigned int, void*)’:
src/osdep/amiberry_gfx.cpp:270:13: error: invalid conversion from ‘long unsigned int*’ to ‘volatile uae_atomic*’ {aka ‘volatile int*’} [-fpermissive]
  atomic_inc(&vsync_counter);
             ^~~~~~~~~~~~~~
In file included from src/include/sysdeps.h:341,
                 from src/osdep/amiberry_gfx.cpp:7:
src/osdep/target.h:220:58: note:   initializing argument 1 of ‘uae_atomic atomic_inc(volatile uae_atomic*)’
 STATIC_INLINE uae_atomic atomic_inc(volatile uae_atomic* p)
                                     ~~~~~~~~~~~~~~~~~~~~~^
src/osdep/amiberry_gfx.cpp: In function ‘void show_screen(int, int)’:
src/osdep/amiberry_gfx.cpp:1584:16: error: invalid conversion from ‘long unsigned int*’ to ‘volatile uae_atomic*’ {aka ‘volatile int*’} [-fpermissive]
     atomic_set(&vsync_counter, current_vsync_frame);
                ^~~~~~~~~~~~~~
In file included from src/include/sysdeps.h:341,
                 from src/osdep/amiberry_gfx.cpp:7:
src/osdep/target.h:237:52: note:   initializing argument 1 of ‘void atomic_set(volatile uae_atomic*, uae_u32)’
 STATIC_INLINE void atomic_set(volatile uae_atomic* p, uae_u32 v)
                               ~~~~~~~~~~~~~~~~~~~~~^
make: *** [<builtin>: src/osdep/amiberry_gfx.o] Error 1


**To Reproduce**
just compile:
make -j2 PLATFORM=rpi4

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by solskogen** [comment]
Are you on 64bit or 32bit? Could you give us the output of `uname -m`?

**Comment by ninjaweb62** [comment]
> Are you on 64bit or 32bit? Could you give us the output of `uname -m`?

32bit, armv71

Thanks

**Comment by midwan** [comment]
@ninjaweb62 
Have you tried doing a `make clean` first, then re-compiling with `make -j4 PLATFORM=rpi4` ?

**Comment by ninjaweb62** [comment]
> @ninjaweb62
> Have you tried doing a `make clean` first, then re-compiling with `make -j4 PLATFORM=rpi4` ?
Sorry, I forgot to specify I'm compiling the dev version.

Tried what you asked for, unfortunately I get the same errors...

It compiled fine till the 11th of june dev release

**Comment by ninjaweb62** [comment]
Ok, it compile correctly now. Issue can be closed.

Thanks!
