### ISSUE TITLE
bluetooth gamepad not reconnecting

### ISSUE THREAD

**Issue by tednilsen** [midwan/amiberry#82]
bluetooth gamepad isn't reconnecting when turned on again, so the user is forced to quit amiberry with keyboard / mouse and restarting amiberry again to use the gamepad.

**Comment by midwan** [comment]
This will be a bit hard to troubleshoot as I don't have a bluetooth controller, but we'll see what we can do.

What type of controller are you testing it with? PS3/PS4?

**Comment by tednilsen** [comment]
I have a G910, but fails with other gamepads too, I haven't tried xbox controller.
Works with no issues in RetroArch and more.

**Comment by HoraceAndTheSpider** [comment]
This is duplicate of issue #52 I think and should be merged.

**Comment by midwan** [comment]
@HoraceAndTheSpider indeed it is, thanks

@tednilsen this will be merged with #52
