### ISSUE TITLE
Amiberry Whdload not working

### ISSUE THREAD

**Issue by venkman383** [midwan/amiberry#820]
Hi.. I have an RP4 with retropie installed. I can get everything to work except amiberry. I have loaded all the kickstart roms and various lha files. They all Show in the amiga meni but when i run them i always get the blue amiga dos screen (release 1.3) which comes up with:
Unknown command IF
1>

any ideas what im doing wrong? Randomly i have an old. RP3 with the same amiga settings and they all seem to work fine on there. I want to get them working on my rp4 as this is the basis for my arcade unit.

Any help would be much appreciated.

**Comment by midwan** [comment]
@venkman383 
Have you checked with the RetroPie forums/support first?
It's recommended you do so, since that distro has a custom front-end which launches Amiberry with a script.

**Comment by HoraceAndTheSpider** [comment]
Your `amiberry.sh` on RetroPie is probably using the incorrect syntax for the auto-booter. it no longer requires `-autoload=game.lha` but `--autoload game.lha` I had this problem also

**Comment by midwan** [comment]
in my tests, updating the RetroPie script through RetroPie-Setup also used the proper syntax, so I had no problem launching lha titles... But in any case, the Retropie team has requested that such issues are reported there first, and elevated here only if necessary.
