### ISSUE TITLE
Retroarch Quit doesn't work when Mouse Mode is used for Controller

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#823]
**Scenario**
- Amiberry v4.1.4
- Tested on self-compiled copy for Raspberry Pi 3
- Loading games via WHDBooter (through RetroPie)

**Issue** 
Setting a retroarch controller to Port 0 and 'Mouse' Mode retroarch combination buttons and custom controls no longer work.

This is within the `mode == JSEM_MODE_MOUSE` in the Amiberry code.

This means that any user who has a non-mouse setup (e.g. one of many popular portable Pi devices) can no longer quit Amiberry or enter the menu when launching a mouse game.

Example setup:
https://discord.com/channels/392441013471543308/392453763094282270/861721965173276725

**Comment by midwan** [comment]
This only seems to affect the Retroarch Quit combo.
I can still use the Hotkey + Menu combo to enter the GUI in my tests.
And it only happens in Mouse or Wheel mouse modes, all the others work as expected.
