### ISSUE TITLE
[DMX] Flickering Black Screen when changing UAE configs from GUI

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#824]
**Scenario**
- Amiberry v4.1.4
- Tested on self-compiled copy for Raspberry Pi 3
- Loading games via WHDBooter (through RetroPie)

**Issue** 

After loading a game from the WHDBooter, if another config file is loaded from the GUI (followed by a uae 'reset'), after a few times, the screen becomes locked as a 'black screen' with the mouse showing.  This fault is intermittent and requires multiple UAE files to reproduced. 

I have produced the fault with this file: 
http://djcresswell.ultimateamiga.co.uk/Bloodwych_v2.51_0439.uae

If the GUI button (f12) is triggered, then a 'flash' of the emulated screen may appear. Returning to the game may return to the black screen.

**Comment by midwan** [comment]
This only seems to be a problem in the Dispmanx versions of Amiberry.
I suspect that it has to do with the "blackscreen" dispmanx element used there, which is supposed to sit behind the emulation screen and hide the desktop/console. It might be losing the depth position sometimes when going through this process.

I tested the same steps using the SDL2 version of Amiberry and this problem did not occur there, which leads me to my suspicion above.

**Comment by midwan** [comment]
Update: this seems to be triggered only when the window size (width/height) changes between configs. If the two configs have the same, it seems to work.
