### ISSUE TITLE
Save States under HDD modes Not Working

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#825]
**Scenario**
- Amiberry v4.1.4
- Tested on self-compiled copy for Raspberry Pi 3
- Loading games via WHDBooter (through RetroPie)

**Issue 1**

Saving  of save states is no longer possible in HDD mode.  Load any WHDload game (.lha file) and attempt to save a state. This behaviour should be reverted.

This appears to have been an inherited behaviour from WinUAE. In that case there is no WHDbooter, and it is disabled to 'protect' the user from loading save-states where the HD has been written to between saves.

This has an impact on how casual users will use the WHDBooter, and the use of Save-States with the Booter has previously been very reliable, as all saves/edits are done to a separate 'drive' (DH3 i think)

However, FS-UAE features a WHD loading feature (similar to Amiberry) and  allows save-states to be used with HDD setups with an 'unsafe savestate enabled' option. If needed, this should be considered as an option within `amiberry.conf` to allow users to save states with the WHDload Booter 'at risk'.

**Issue 2**
Loading older save states with HDD setups now crashes the emulation environment. This may be due to changes within the core.

**Comment by Drag0nFly** [comment]
Just to quickly comment on issue 2– loading of _any_ "older" save-state file now appears to crash the emulated cpu – HDD setup or not (ref issue #831), at least on my Retroarch setup running on rpi4 (tested with a variety of savestate files & clean reboots to verify). This is quite unfortunate, as I doubt the average Amiberry user expects this functionality to be impaired after an upgrade (minor or not).

As for  save states under HDD mode no longer working, I agree that this should be possible if saving to a separate drive the way FS-UAE handles it, it is a very useful feature indeed for Amiberry to retain.

**Comment by midwan** [comment]
This behavior was changed to fix another bug: https://github.com/midwan/amiberry/issues/725

Perhaps it would be enough to check for enabled RTG/JIT only, and then block the savestate generation? I'll need to test these scenarios and make sure it doesn't cause the same problem.

**Comment by midwan** [comment]
This is fixed in the `master` branch also.
I'll release v4.1.5 when I fix a few other things in my list, but you can test it already if you just get the latest from source and re-compile. The version will still show 4.1.4 for now.

**Comment by midwan** [comment]
Amiberry will now prompt the user in case an unsafe scenario is present (P96 or JIT enabled).
You can still proceed and create the savestate, at own risk.
