### ISSUE TITLE
Indiana Jones and Fate of Atlantis (Adventure / WHDLoad)

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [midwan/amiberry#826]
**Scenario**
- Amiberry v4.1.4
- Tested on self-compiled copy for Raspberry Pi 3
- Loading games via WHDBooter (through RetroPie)

**Issue**

Doesnt seem to run after getting though to th intro and into the main game. Amiberry quits out without reason.

**Comment by midwan** [comment]
Seems to work normally in 4.1.5 RC3 where I just tested it, with version 2.3_0851.
If you can still recreate it with this version, perhaps it's something external to the game itself?
