### ISSUE TITLE
Black screen after starting the emulator

### ISSUE THREAD

**Issue by Hobysp** [midwan/amiberry#829]
Hi,
I installed Amiberry 4.1.4 on Raspios buster lite from source (compile SDL2 without DispmanX).
Gui is displayed, I can configure emulator options.
After starting emulation is a black screen, but emulator works because I hear floppy drive sound (characteristic ticking)

Kickstart files are good for sure.

My installation way (step by step):

sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev libdrm-dev libgbm-dev libudev-dev libasound2-dev liblzma-dev libjpeg-dev libtiff-dev libwebp-dev git build-essential
sudo apt-get install gir1.2-ibus-1.0 libdbus-1-dev libegl1-mesa-dev libibus-1.0-5 libibus-1.0-dev libice-dev libsm-dev libsndio-dev libwayland-bin libwayland-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev x11proto-randr-dev x11proto-scrnsaver-dev x11proto-video-dev x11proto-xinerama-dev

wget https://www.libsdl.org/release/SDL2-2.0.14.tar.gz
wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz
wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz

tar xf SDL2-2.0.14.tar.gz
tar xf SDL2_image-2.0.5.tar.gz
tar xf SDL2_ttf-2.0.15.tar.gz

cd SDL2-2.0.14
./configure --enable-video-kmsdrm --disable-video-rpi && make -j$(nproc) && sudo make install
cd
cd SDL2_image-2.0.5
./configure && make -j $(nproc) && sudo make install
sudo ldconfig -v
cd
cd SDL2_ttf-2.0.15
./configure && make -j $(nproc) && sudo make install
sudo ldconfig -v
cd
sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev
git clone https://github.com/midwan/amiberry
cd amiberry
make -j2 PLATFORM=rpi4-sdl2
./Amiberry

**Comment by boras-pl** [comment]
Try the latest SDL directly from GIT

**Comment by midwan** [comment]
@Hobysp 
Have you tried with the latest SDL2 version from git?
They fixed quite a few bugs related to KMSDRM (which is what you're using I guess, since you are not using dispmanx or X11), so perhaps this is resolved already.
Otherwise, please let me know and we'll see if we can figure out what's wrong.
