### ISSUE TITLE
SDL 2 | Latest commit build error

### ISSUE THREAD

**Issue by windale** [midwan/amiberry#83]
Just tried to build after your latest commit https://github.com/midwan/amiberry/commit/0fb37784de3c25dc90f085dde2dd96fa4c3d47be and got this error -

> src/osdep/gui/PanelSavestate.cpp:3:23: fatal error: SDL_image.h: No such file or directory
>  #include <SDL_image.h>
>                        ^
> compilation terminated.
> <builtin>: recipe for target 'src/osdep/gui/PanelSavestate.o' failed
> make: *** [src/osdep/gui/PanelSavestate.o] Error 1

**Comment by midwan** [comment]
@windale 
There hasn't been any dependency change recently, certainly not with that commit.
To be sure, I just tested a build from scratch on the Pi3 here and it worked normally.

Please make sure you have the **SDL_image** dependency installed in your system as per the instructions in the readme. If it's in another path for example, it may not get picked up. 

The Makefile will use `sdl2-config --cflags --libs` to detect the proper paths and compiler flags. You can try running that manually to see where it expects everything to be in...

**Comment by windale** [comment]
I'm still getting the error when I try to build. It started when I tried to get rid off the old method of SDL2 that used to be installed in your build instructions. I didn't know where it was installed so I built it again using the old instructions -

cd ~ 
wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
tar zxvf SDL2_image-2.0.1.tar.gz 
cd SDL2_image-2.0.1 && mkdir build && cd build 
../configure 
make -j 4 
sudo make install

then I used

sudo make uninstall

Now when I use the new build instructions I get that error I mentioned during the last step

make all

**Comment by midwan** [comment]
@windale 
Did you remember to do this part when you installed SDL2 with the updated instructions?

> Next, we need SDL2_image and SDL2_ttf:
>   `sudo apt-get install libsdl2-image-dev libsdl2-ttf-dev `

**Comment by windale** [comment]
Yes, I followed all the steps, I have no idea what's happening. It used to work before I tried to get rid of the other SDL2 version.

**Comment by windale** [comment]
I installed the old SDL2_image and now it builds Amiberry correctly again. I'll have to stick with that until I decide to re-install my whole RetroPie setup. I have no idea what happened. (Love the new icons).

**Comment by midwan** [comment]
@windale 
Ok, good to see that it works for you - strange that you got this problem, but it certainly seems to be an issue related to the environment, not the emulator itself.
