### ISSUE TITLE
[v4.1.4] Emulator crash (JIT exception) when running “Nature - Zeon”

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#832]
When running the above demo (Zeon by Nature, https://www.pouet.net/prod.php?which=2803), a JIT exception is thrown and the core crashes (hard) near the end. This happens consistently with my 68040 config (4Mb chip, 64Mb Fast, 16Mb RTG, CPU+FPU JIT)

amiberry.log excerpt:

```
AUD0LCH HACK: 000D 40179456 (1) (1 1 000d78b0)
AUD0LCL HACK: 78B0 40179456 (1) (1 1 000d78b0)
AUD1LCH HACK: 000D 40179456 (1) (1 1 000d80b0)
AUD1LCL HACK: 80B0 40179456 (1) (1 1 000d80b0)
AUD2LCH HACK: 000D 40179456 (1) (1 1 000d88b0)
AUD2LCL HACK: 88B0 40179456 (1) (1 1 000d88b0)
AUD3LCH HACK: 000D 40179456 (1) (1 1 000d90b0)
AUD3LCL HACK: 90B0 40179456 (1) (1 1 000d90b0)
--- New exception ---
Error not in JIT code.
Illegal Instruction
info.si_signo = 4
info.si_errno = 0
info.si_code = -6
info.si_addr = 00005047
--- New exception ---
Error not in JIT code.
Segmentation Fault
info.si_signo = 11
info.si_errno = 0
info.si_code = -6
info.si_addr = 00005047
r0  = 0x00000000
r1  = 0xbec769c4
r2  = 0x00000000
r3  = 0x00000008
r4  = 0xb6f43968
r5  = 0x0000000b
r6  = 0xbec769c4
r7  = 0x000000af
r8  = 0x00000004
r9  = 0x00005047
r10 = 0x00000000
FP  = 0x03e0afc0
IP  = 0x00000000
SP  = 0xbec769c0
LR  = 0x00000000
PC  = 0xb6d5b8ec
CPSR = 0x00000010
Fault Address = 0x00005047
Trap no = 0x0000000e
Err Code = 0x00000207
Old Mask = 0x00000008
LR - 0x00000000: symbol not found
Stack trace:
0x00250db4 <(null) + 0x00250db4> (./amiberry)
0xb6868130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
Stack trace (non-dedicated):
./amiberry() [0x250ecc]
/lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6868130]
End of stack trace.
--- end exception ---AUD0LCH HACK: 000D 40179456 (1) (1 1 000d78b0)
AUD0LCL HACK: 78B0 40179456 (1) (1 1 000d78b0)
AUD1LCH HACK: 000D 40179456 (1) (1 1 000d80b0)
AUD1LCL HACK: 80B0 40179456 (1) (1 1 000d80b0)
AUD2LCH HACK: 000D 40179456 (1) (1 1 000d88b0)
AUD2LCL HACK: 88B0 40179456 (1) (1 1 000d88b0)
AUD3LCH HACK: 000D 40179456 (1) (1 1 000d90b0)
AUD3LCL HACK: 90B0 40179456 (1) (1 1 000d90b0)
--- New exception ---
Error not in JIT code.
Illegal Instruction
info.si_signo = 4
info.si_errno = 0
info.si_code = -6
info.si_addr = 00005047
--- New exception ---
Error not in JIT code.
Segmentation Fault
info.si_signo = 11
info.si_errno = 0
info.si_code = -6
info.si_addr = 00005047
r0  = 0x00000000
r1  = 0xbec769c4
r2  = 0x00000000
r3  = 0x00000008
r4  = 0xb6f43968
r5  = 0x0000000b
r6  = 0xbec769c4
r7  = 0x000000af
r8  = 0x00000004
r9  = 0x00005047
r10 = 0x00000000
FP  = 0x03e0afc0
IP  = 0x00000000
SP  = 0xbec769c0
LR  = 0x00000000
PC  = 0xb6d5b8ec
CPSR = 0x00000010
Fault Address = 0x00005047
Trap no = 0x0000000e
Err Code = 0x00000207
Old Mask = 0x00000008
LR - 0x00000000: symbol not found
Stack trace:
0x00250db4 <(null) + 0x00250db4> (./amiberry)
0xb6868130 <__default_rt_sa_restorer + 0x00000000> (/lib/arm-linux-gnueabihf/libc.so.6)
Stack trace (non-dedicated):
./amiberry() [0x250ecc]
/lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6868130]
End of stack trace.
--- end exception ---
```

**Comment by midwan** [comment]
Tested the demo under a similar config here:
- WB 3.9 with BB4 ROM, RTG, 040/Fastest possible, JIT
- Using v4.1.5 RC3 (current one from `master`)
- The demo run all the way to the end without problems

**Comment by Drag0nFly** [comment]
Did you run it with FPU-JIT enabled? I did test this a number of times on my WhdLoad HDD image, which is running WB3.1. not 3.9 (and no additional ROMs)

Currently I am on a lower Amiberry v3 version due to the non-loading of "older" savestates, but I can retest when possible.

**Comment by midwan** [comment]
Yes, JIT and JIT FPU were both enabled in my test. 
But as I mentioned in the other issues, Demos and Games are usually not meant to run with JIT - they may work, or they may not.

**Comment by Drag0nFly** [comment]
I will retest, thanks for confirming. As I mentioned in the other ticket, I realize that JIT is not a preferred config for games and demos (it was simply on due to being run from my main .hdf WorkBench image.)

The reason I reported these issues (and sorry, there were a few which probably were related to the same issue) however was due to AmiBerry itself crashing with a segmentation fault, instead of halting emulation. (i.e, there should be a cleaner way of handling these JIT exceptions)

Since you are reporting that it indeed does not crash on your config there could be something in recent versions which have improved this, or it is related to how Amiberry is launched from EmulationStation on my system (a little strange, but still), or (perhaps even stanger) it is Rpi4/kernel related.

**Comment by midwan** [comment]
Yeap, I understand your intention :)

I tested things under a Manjaro Linux (64-bit) installation with the latest updates, so it could be differences in kernel and libraries as well.

**Comment by Drag0nFly** [comment]
Believe me, I'd love to move over to an Arch-based system, but unfortunately I am bound by Raspbian (and its library versions, which tend to be older than Arch/Manjaro/Artix/Parabola and the rest of its family.)

So you are on Rpi4 also, correct?

**Comment by Drag0nFly** [comment]
Ok. 

btw., I meant to write “bound by RetroArch” above :). _(Not sure what the support is for non-dpkg/apt (i.e, Pacman) packages would be, but I suspect a lot more manual intervention.)_
