### ISSUE TITLE
[v4.1.4] Option to change button mapping for PS3 and related controllers

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#833]
I've looked through amiberry.conf in order to figure out how to accomplish swapping "X" and "Y" ("X" and "Circle") on Sony-compatible controllers, but coming up short.

There is a setting for this within Retroarch, but it only affects the GUI. Basically, it would be nice to have consistent behaviour so that the X ("Cross") button in Amiberry was mapped to fire. The way it is now is that "Circle" (commonly used as "back") is the fire button.

Thanks for considering _and for the great work that is being done on Amiberry (surprised to see how well many 060-style demos run fluidly). Only issue so far are some crashes relating to JIT and a ~1sec audio delay._

**Comment by midwan** [comment]
We've used CD32-style mapping for controllers in Amiberry, to make it more Amiga-like.
You can however create your own custom mapping for your controller, in a few different ways:
- Retroarch mapping. There's plenty of documentation for that in the wiki pages, and usually it's done already for you when you use Retropie.
- If you don't have a retroarch config file (i.e. for all distros other than Retropie, usually), you can create a config entry in the `<amiberry>/controllers/gamecontrollerdb_user.txt` file. Check the relevant wiki page for more info on that: https://github.com/midwan/amiberry/wiki/Creating-a-new-Controller-mapping-(SDL2-gamecontroller)

**Comment by Drag0nFly** [comment]
AFAIK, the RetroArch mapping only works for the libretro (lr_) prefixed emulators/engines. I am aware that a completely new mapping can be created, but since this only affects the X and O buttons (cross and circle on PS3), which need to be reversed; as the default behaviour (along with other emulators, sadly), is that of the Xbox controllers, where circle (which is assigned to 'back' on the Playstation) is fire/action and vice-versa.

That was my basis for suggesting a config entry simply for this (swap the two buttons, and thereby restore the behaviour so that it is inline with how a Playstation controller behaves)

One might ask why the Xbox-style controller mapping became the default in the first place in RetroArch, but that is a question for another time I guess. ;)

**Comment by midwan** [comment]
Amiberry has had retroarch support for quite a while now... ;)
So as I mentioned above, there are 2 ways to change this mapping globally:
- Retroarch config (which takes priority) or
- controller mapping file

If you only want a per-game change, then you can also use the Custom Controls section in the GUI, which saves that with a config file (usually per game).

And again, the decision on that was to be inline with the CD32 controller that we're emulating (which has the Red button acting as Fire0). 

![image](https://user-images.githubusercontent.com/3877365/129457569-5f31b474-9a4d-45fc-8ec4-085bdea1bf1d.png)

**Comment by Drag0nFly** [comment]
Thing is, I've already changed this on the RetroArch side. However, it only affects the EmulationStation GUI. Perhaps I am missing something?

From my one controller (in /opt/retropie/configs/all/retroarch/autoconfig/, which the Amiberry config is symlinked against)

input_b_btn = "1"
input_a_btn = "2

These correspond to circle and cross, respectively. When running jstest cross is "2" ("A" button) and circle is "1" ("B" button). Perhaps these should be reversed? (color me confused)

Obviously, this is not completely within the purview of Amiberry and has more to do with the seemingly monstrously confusing way RetroPie handles configs _(and is the reason for me still not having added a second controller; as I am afraid of what deviant creatures such a move would unleash...;)_

**Comment by midwan** [comment]
Besides the retroarch config which is automatically loaded (if found), you can additionally use Custom Controls to assign any functionality you want on the controller buttons. The changes you make there are saved with a config file, so they can be made per-game if you want to.
