### ISSUE TITLE
[v4.1.4] Option to change mouse-speed in the GUI

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#838]
I've been fiddling around with the mouse-settings in Amiberry as the mouse is painfully slow in the user interface, but can only seem to be able to change the speed after having booted into an actual AmigaOS environment.

Is there something I am missing? The only setting I've found is “input_default_mouse_speed” (which I've currently set to '200').

This setting, however, has no effect on the mouse in the GUI, where it is most useful. (The mouse is so slow in the interface that it takes several complete 'rolls' to move it from one side of the screen to another.)

**Comment by solskogen** [comment]
This might not even have anything to do with amiberry, but you mouse. I have several mice with the same problem (and one that does show the same symptoms) - but the solution I found was at https://peppe8o.com/fixing-slow-mouse-with-raspberry-pi-os. By setting usbhid.mousepoll=0 as the kernel parameter.

**Comment by Drag0nFly** [comment]
Hei Christer,

I'll try the usbhid.mousepoll=0 kernel option - thanks for the tip. It would probably be a non-issue for mice with the DPI setting available (as an extra button), but I've seen this problem mentioned a few places already. I agree it is more of an OS config issue not immediately related to Amiberry, but quite relevant from a user point-of-view. If it was X it would be a simple 'xset m <int>' Not sure how it is controlled from SDL2/ES, apart from the aforementioned kernel option.

I should mention though, that in other apps such as ScummVM and AGS, the mouse behaves as normal.

**Comment by Drag0nFly** [comment]
Can confirm that the change proposed by Christer does work. Took a bit longer to verify, as I had the pleasure of encountering a potential system-breaking bug after upgrading to 5.10.52-v7l+ (raspberrypi-kernel 1.20210303-1) (https://github.com/raspberrypi/firmware/issues/1603), which caused all kinds of unpredictable behaviour and almost bricked the installation.

In any case–closing ticket as this is no longer an issue. Sorry for any extra noise. (Takk igjen til Christer)
