### ISSUE TITLE
Hstwb installer support

### ISSUE THREAD

**Issue by symbios24** [midwan/amiberry#844]
Hi there
Is it possible to add support for the hstwb installer in Amiberry??
To make easier the installation of amigaos,workench's etc

There s already support for Raspberry Pi for hstwb in amibian but the amiban project is almost 2 years outdated with no support for newest Raspbian and probably abandoned.

https://hstwb.firstrealize.com/

Thanks

**Comment by midwan** [comment]
What exactly doesn't work with it?

**Comment by symbios24** [comment]
Doesn't work with what?

**Comment by midwan** [comment]
You mentioned the hstwb installed above, and adding "support" for it in Amiberry.
What doesn't work with it currently, that you'd like to add support for? It seems to me that it already works with it, since it generates a hardfile to boot from?

**Comment by symbios24** [comment]
Sorry i wanted to say for amiberry to boot with hstwb pre-installed on it or an option to add it as an extra

**Comment by midwan** [comment]
That sounds like something for a distro maintainer though, not an emulator thing. I think you're looking for an image bundled with the stuff...

Amiberry already supports using RDB hardfiles that the tool you mentioned creates, so it seems this is not an issue for Amiberry itself.

**Comment by symbios24** [comment]
Ok thanks for your time
