### ISSUE TITLE
Dual-joystick setup (port 0, port 1) not working properly in some games

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#847]
_Apologies if this has been reported earlier (nothing showed up with a search - on Github or elsewhere), but as I've just spent the better part of a day trying to get this working without any success I am submitting this as a potential bug report._

I have two wireless joysticks (“joypads”, rather). One is a Gioteck VX2, and the other is a DualShock 3, connected via bluetooth. They both work great individually, but not at the same time (which was the intention for using two in the first place). The Gioteck is the one I use as the primary in EmulationsStation.

Let me clarify–they both show up in Amiberry (providing the DS3 is turned on). Whichever stick is then set for Port 1 will be the one being used. The other controller does nothing (tried setting it to 'mouse' or 'gamepad', etc. to not effect) Also tried the custom controls menu to change 'joystick port' to 0, as well as set one of the controllers as an “emulated parallel port joystick adapter”.

I've tested with a few games (currently testing with SWIV_v1.7_0038.lha), and the problem appears consistent. Since these are launched via WhdLoad, I've also verified its settings in whdload_db.xml (config included at the bottom).

I can safely say that there are no driver issues causing this, as I can switch on-the-fly between the DualShock 3 and the Gioteck after the game has launched, it works without issues.

I've also tested running “jstest /dev/input/js1” (js1 being the joystick which isn't responding while in Amiberry) but all buttons register.

However, the second joystick never sends any actual input to the game, whereas the keyboard does. (R_Shift acting as the firebutton, at least in SWIV)

My unqualified guess would be that it appears that one of the ports may be hardcoded to the dreaded “Retroarch Keyboard as joystick [#1]” (wish there was an option to simply disable this, as it also messes up standard keyboard in Workbench when it is erroneously set – with "W" acting as fire, causing it to send a carriage return)

The abovementioned setting is not set when the game is launched btw. (only if the joystick in port#0 is switched off due to a timeout). Tested a few times with both joysticks on, and they are showing up correctly in Amiberry's Input settings as they should, so all seems well at least.

Really don't know what I could be missing, config-wise, here. It may be something trivial. So I appreciate any comments.

Relevant part of Amiberry configuration–

```
;
; *** Controller/Input Configuration
;
joyport0=joy1
joyport0_autofire=none
joyport0_mode=djoy
joyport0_friendlyname=Goodbetterbest Ltd Gioteck VX2 2.4G Wireless Controller
joyport0_name=JOY1
;
joyport1=joy2
joyport1_autofire=none
joyport1_mode=djoy
joyport1_friendlyname=Sony PLAYSTATION(R)3 Controller
joyport1_name=JOY2
```

``` 
       <game filename="SWIV_v1.7_0038"  sha1="79dc560938e33bfaef1e3e23e36306491158cea8">
                <name>SWIV</name>
                <subpath>SWIV</subpath>
                <variant_uuid>28f044ea-3089-5326-8137-90f95403b77a</variant_uuid>
                <slave_count>1</slave_count>
                <slave_default>SWIV.Slave</slave_default>
                <slave_libraries>False</slave_libraries>
                <slave number="1">
                        <filename>SWIV.Slave</filename>
                        <datapath></datapath>
                        <custom>
                        C1:B:Disable jump control (if 2nd button pressed)
                        C2:B:Unlimited lives
                        </custom>
                </slave>
                <hardware>
                PRIMARY_CONTROL=JOYSTICK
                PORT0=JOY
                PORT1=JOY
                FAST_COPPER=FALSE
                JIT=FALSE
                SCREEN_AUTOHEIGHT=FALSE
                SCREEN_HEIGHT=512
                SCREEN_CENTERH=SMART
                SCREEN_CENTERV=SMART
                </hardware>
        </game>
```

**Comment by midwan** [comment]
I just noticed that you're not running the latest Amiberry version, from your screenshots.
Retropie is still providing 3.3 only, but hopefully that will be updated (we have an open issue with them about it).
If you can compile Amiberry from source yourself, then you can test this on the latest version, where I'm also doing the tests. Otherwise, perhaps wait until Retropie have updated their system accordingly, and can deliver the latest Amiberry version (4.1.6 currently).

**Comment by Drag0nFly** [comment]
So the issue is unrelated to v3.3.

**Comment by Drag0nFly** [comment]
Actually, the behaviour is not completely identical. Despite both joysticks registering on the Linux-side with jstest and showing up in Amiberry's drop-down menu, the PS3 controller cannot be selected once this has had a sleep timeout (turned back on, verified that it talks to the system with jstest)

I did not experience this issue with v3.3 but will re-test.

Selecting "PS3 Controller" causes the existing entry "System mouse" to be selected. See attached screenshot.

![amiberry-git-screenshot-input2](https://user-images.githubusercontent.com/3673489/136599146-4012b637-a207-40d0-835c-ea17c555ca76.png)

**Comment by Drag0nFly** [comment]
I did struggle for a time to find an actual game to test with two joysticks. Looks like I picked the “wrong” one. (Naturally, this is based on games I'd actually want to play in two-player mode)

I don't have "Pang" available atm. but I assume it will work then. Thanks for the tip.

**Comment by midwan** [comment]
I also just tested Chaos Engine (AGA) - WHDLoad version. Also works fine.

I think this may be some sort of problem with SWIV and maybe only the WHDLoad version? Not sure, more tests would be needed - but it seems to work in general otherwise. :)

**Comment by Drag0nFly** [comment]
Tested Lotus Turbo Challenge 2 (WHDLoad version) and it works with both joystick under v3.3

**Comment by Drag0nFly** [comment]
_(Really weird that the one game I chose to test had such issues with the 2-player mode)_
