### ISSUE TITLE
[v.4.1.6] sound_max_buff setting ignored after upgrade

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#848]
Despite setting “sound_max_buff=4096” in default.uae, as well as any other .uae files in /opt/retropie/configs/amiga/amiberry/conf/ (all of which are unchanged after an upgrade), this setting is ignored, and requires one to save all config files again.

However, the sound_max_buff setting remains unchanged. Presumably there is a header in the file, or other content, which causes the default value of 8 (introduces a significant audio delay) to be used.

```
diff /opt/retropie/configs/amiga/amiberry/conf/default.uae /opt/retropie/configs/amiga/amiberry/conf/default.uae.diffme |grep sound_max
< sound_max_buff=4096
> sound_max_buff=4096
```

It would be good if settings which are identical between versions are retained.

**Comment by Drag0nFly** [comment]
Yes–it appears all are affected. I thought it might be related to the version header on the top. When I re-saved the file from within the Amiberry GUI (although its value is exactly the same for sound_max_buff) it then works properly again.

Since I've been testing a couple of different versions I've noticed this happening to other settings as well, and thought it was related. I can confirm that the actual config file were not touched, so the override is not working (at least for default.uae)

**Comment by midwan** [comment]
I can't recreate that problem.
If I save the audio buffer as "4" in 3.3, then load the same config with 4.1.6, it's still set to 4.

**Comment by Drag0nFly** [comment]
Then it could be the interaction between EmulationStation and Amiberry, as I can confirm that I verified the buffer change before I upgraded (it was a long-running issue). (But it is strange that the buffer value was then honored when manually saved from within the Amiberry GUI.)

**Comment by midwan** [comment]
I'm not sure how EmulationStation could affect this specifically, but here are a few ideas to test:
- Load Amiberry without any parameters first, then load the config from inside the GUI. Does it work as expected then? There's no EmulationStation process to affect it in this way.
- If the above works fine, but loading the config directly from ES does not, perhaps there's something wrong with either how that is called, or the process of loading a config file from startup (as opposed to loading it from the GUI). It would be weird, but it does make some more sense at least. :)

Another test would be to drop to the console (Alt-F4), then cd to where the amiberry binary is located (normally under `/opt/retropie/emulators/amiberry/` and run Amiberry manually from there: `./amiberry` (not with the shell script!). Then try loading the config file from the GUI again - does that work?

And finally, you can try the same steps above, but also pass the parameter to load the config file directly on the command line: `-f conf/<configfilename.uae>` - does that work as expected?

**Comment by midwan** [comment]
Thanks for the extra details. You should be able to start Amiberry itself from within ES, by choosing the `+Start Amiberry+` option in the menu (it's there by default once you install Amiberry from RetroPie-Setup). That one does not require a config, and just launches the emulator using a shell script.

I'll check through what you described and see if I can find anything further.

**Comment by Drag0nFly** [comment]
```
pi@playbox4 ~> cat RetroPie/roms/amiga/+Start\ Amiberry.sh
#!/bin/bash
"/opt/retropie/emulators/amiberry/amiberry.sh"
```

When running this entry in the meny, the last game launched starts. Could be it is falling back to whatever it finds in /tmp, which has the startup-sequence et al. copied to it.

**Comment by Drag0nFly** [comment]
Compiled v4.1.6 again, and at least now the max_sound_buff is 4 when starting '+Start Amiberry.sh' – which currently boots up to "object not found" "CD failed returncode 20"

It is still set to 8 when running actual games though. I'll remove the default.uae file again (which Amiberry is using, as it is highlighted as active, although being in the middle of the other configs)

**Comment by Drag0nFly** [comment]
This is how I checked.

```
git clone https://github.com/midwan/amiberry -b dev amiberry-dev
Cloning into 'amiberry-dev'...
remote: Enumerating objects: 24268, done.
remote: Counting objects: 100% (2532/2532), done.
remote: Compressing objects: 100% (1146/1146), done.
remote: Total 24268 (delta 1859), reused 2033 (delta 1383), pack-reused 21736
Receiving objects: 100% (24268/24268), 52.51 MiB | 14.00 MiB/s, done.
Resolving deltas: 100% (18558/18558), done.

pi@playbox4 ~/compile> cd amiberry-dev/

 grep sound_max ./conf/amiberry.conf
```

Has the setting been changed from “sound_max_buff” to “default_sound_buffer”?

**Comment by Drag0nFly** [comment]
I verified the config parameters by using an existing git repo tree, as doing this from within Retropie would put it in a temporary place.

I am testing on v4.1.6 compiled from the RetroPie setup script, see screenshot. I was doing this specifically to see whether any of those scripts caused this behaviour to occur.
![amiberry-screenshot-about](https://user-images.githubusercontent.com/3673489/137378374-32c8e970-b11e-44b8-9f47-59e9de32c281.png)

If anything, the difference in the naming of the config options certainly cause some confusion, although I am glad to have shed some more light on what exactly is going on.

I still think it is beneficial to use a default.uae config (and again, not created by me), as most users will change settings from within the GUI. The issue is what apparently takes precedence – seeing that the config loading directly from the GUI is correct under both v3.3 and 4.1.6 something is amiss, possibly related to how the .uae configs are parsed when launching from ES and the WHDLoad loader.

**Comment by midwan** [comment]
The process is roughly like this:
- The default (internal) prefs are set
- The default prefs are updated based on values coming from `amiberry.conf` where applicable
- If a config file was loaded, it overrides all prefs contained in it with its values
- If the WHDLoad booter is triggered, it will look for a game-specific config file (`.uae`) and load it if found, so options contained in that one will override the current prefs.
- If the WHDLoad booter was triggered, and a match is found in the XML file, the settings from the XML file will override the current prefs.

After that, emulation starts with the current prefs and proceeds accordingly.

The existence of the `default.uae` file meant that the initial prefs were altered, and from there the booter made the minimal changes required for the game.

You can of course use a `default.uae` file if you want to, but it doesn't seem to be very useful in an environment like Retropie, where each game you launch will probably have/require different settings anyway. Unless you want to have a "default" environment to start in, when you launch Amiberry without any other parameters. It's up to you what you do with it and how you use it. But if you have a config file, then it's recommended you update it with newer versions of the emulator as there may be changes made that affect it (older versions had differently named options, newer versions are closer to WinUAE). 

I'm not sure we can do much more in this case, as this doesn't seem to be a generic problem related to the emulator itself, based on our discussion.

**Comment by midwan** [comment]
We now have an additional function: you can use command line parameters to specify default options normally held in `amiberry.conf` - this will override them.

I think that with the addition of this, you should be covered for what you're trying to do in multiple ways now (use amiberry.conf for sensible defaults, use command line options for customized defaults, using config files for case-per-case customizations).

**Comment by Drag0nFly** [comment]
Ok–so the config files/.uae files will override settings in `amiberry.conf`, and any command-line parameters takes precedence over both?

Sounds sensible to me if I understood correctly.
