### ISSUE TITLE
German Keyboard PI400 Hashtag Key

### ISSUE THREAD

**Issue by stefs12** [midwan/amiberry#852]
I am Using amiberry stable (4.1.6) on Arch on a Pi 400 as a standalone emulator. I have a German layout on the Pi. I am using Amiga OS 3.2, English installation, German Keyboard layout. 

It does not let me enter the '#' Key. It Produces the \ instead.

When I comment out the check for german keyboard (src/osdep/amiberry_input.cpp:194, in keyhack())   it works as expected. I found the check for German keyboard in init_kb(), but in my case that does not seem to work. 

Is there something obvious that i missed in my setup?

**Comment by midwan** [comment]
@stefs12 
Sorry this took a while to look into.
That piece of code is a bit of a hack, which seemed to work for most (?) people so far. It comes from WinUAE originally, adapted for SDL2 by me.

So if I understood you correctly, you commented out the check there, which means the variable `keyboard_german` remained with a value of `0`, and then it worked as expected?

**Comment by midwan** [comment]
@stefs12 
There's also a command line option to set Amiberry's keyboard language:
`-I <value>` where `<value>` is one of `de, dk, us, se, fr, it, es`

Not sure if that helps in your case, but worth a try.
