### ISSUE TITLE
Feature req: adf.xz (and possibly adf.lzma/adf.lz4 et al.) support

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#853]
ADF images compress quite decently with newer compression algorithms, and it would be quite useful for Amiberry to support this – at least for single .adf files.

It would be even nicer if *tar.xz* (or similar) was supported for multi-disk games, but this would be a bigger issue I imagine, so just floating the idea.

As an example another user did a test with just over 26.000 ADFs (in a similar feature req. to FS-UAE)–

Uncompressed total size: 22,659 MiB
Zip-compressed total size: 13,038 MiB
Xz-compressed total size: 11,596 MiB
So I was able to save 1,442 MiB of space (-11%). That's not a lot but still a significant amount in my opinion.

**Comment by midwan** [comment]
I haven't tested this, but since we have 7-zip as one of the archivers, these formats might already be working (in which case, it's just a matter of allowing those file extensions in the filter).

**Comment by midwan** [comment]
Just tested with .xz and it worked fine.
It's probably the same with the other formats - but a test would be good.

I didn't even have to change anything in the emulator, the file selector doesn't limit those filenames :)

**Comment by Drag0nFly** [comment]
I did test this with several adf.xz files before creating a ticket, they were all selectable in the file selector, but the emulator behaved as if an empty floppy had been inserted upon rebooting. After unxz-ing the same ADFs, they loaded just fine.

I do not have the debug log for it available as this is some time ago. Then either something is different on the system-side, or some change impacted this in recent versions perhaps. (I can retest when I have my Pi available.)

**Comment by midwan** [comment]
If you have a failing file, please send it my way so I can test it also.
I just did a quick test by compressing a WB1.3.adf with 7-Zip, using .xz as the format - and it worked for me.

**Comment by Drag0nFly** [comment]
This might also be some kind of temporary-files permissions issue. I cannot verify it from where I am now, but one of the files was SotB disk 1, u/l here–

https://www.dropbox.com/s/9sk2nctbltl9j29/Shadow%20of%20the%20Beast_Disk1.adf.xz?raw=1

(I first thought the system lacked the `7z` executable, but it is available.)

**Comment by midwan** [comment]
ok, that's weird.
If I try with the file you sent me, it doesn't work.
If I decompress it, and recompress it with .xz again (using the latest 7-zip), then it works.

Apparently something is different in the format, but they both indicate the same LZMA2...

**Comment by Drag0nFly** [comment]
It makes sense, as these were from my archived-adfs folder, which were compressed, with xz, a few years back. So it means that 7z only tackles the newer lzma format/header which makes it fail.

(btw., I guess these are all unextracted to stdout, so no temporary files are in the loop.)

**Comment by Drag0nFly** [comment]
Since recompressing the file works, the cynic in me whispers that this is the typical W*n <-> *nix induced incompatibility BS simply for incompatibility's sake... 

btw., when you mention the latest 7-zip, do you mean 7z or p7zip? (assume the former)

At least when I try to uncompress the file with p7zip it barfs out–

`p7zip -d '/data/amiga/adfs-archived/Shadow of the Beast_Disk1.adf.xz' 
/usr/bin/p7zip: /data/amiga/adfs-archived/Shadow of the Beast_Disk1.adf.xz: unknown suffix`

**Comment by midwan** [comment]
I tried it with the latest 7-zip (21.06) on WIndows.

The 7-zip archiver files in Amiberry are also quite old, coming from 7-zip v9.22 beta. It might be worth updating those to the latest as well. Not sure if it would help with this case or not.

**Comment by Drag0nFly** [comment]
The included code in the amiberry source-tree for xz appears quite old, or at least the header file has an older timestamp compared to the most recent 7z verson.

./src/archivers/7z/Xz.h–

```
/* Xz.h - Xz interface
2011-01-09 : Igor Pavlov : Public domain */

#ifndef __XZ_H
#define __XZ_H

#include "Sha256.h"

EXTERN_C_BEGIN

#define XZ_ID_Subblock 1
#define XZ_ID_Delta 3
#define XZ_ID_X86 4
#define XZ_ID_PPC 5
#define XZ_ID_IA64 6
#define XZ_ID_ARM 7
#define XZ_ID_ARMT 8
#define XZ_ID_SPARC 9
#define XZ_ID_LZMA2 0x21
[...]
```

```
7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_DK.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)
```

**Comment by Drag0nFly** [comment]
Seems we made the observation about the older code at about the same time. ;) But again, since 7-zip is primarily used on W*n (the tool, not the compression algorithm), I am not surprised that it introduces headaches wrt. incompatibility–even for older archives which _should_ be backwards-compatibile.

**Comment by midwan** [comment]
I'll try a little test with the latest 7z sources, just to see if they help - and how complicated it is to upgrade to them.

**Comment by Drag0nFly** [comment]
Hopefully that should do the trick, yes.

**Comment by Drag0nFly** [comment]
_(and if not, replacing the 7-zip dependency with a short suffix-based if block which uses the underlying OS-archivers directly would work just as well, as these should be present on most–if not all–Linux machines running Amiberry already.)_

Or perhaps that these take precendence, before falling back on 7zip as a “one-size-fits-all” solution.

**Comment by midwan** [comment]
Looks like it's not that simple to upgrade the 7z files, too many breaking changes.
I'm leaving this for now, as it would poses a high risk of things breaking, perhaps we can do the upgrade at some point in the future.

**Comment by Drag0nFly** [comment]
That is unfortunate. I would suggest ultimately getting rid of 7-zip, as the software is also copyrighted by the owner (despite being stated as open-source from places such as RedHat). Better to rely on simple external commands for this which would not add complexity to the source-tree for Amiberry, nor pose risks of breakage after major (or minor) version changes.

**Comment by midwan** [comment]
@Drag0nFly Update:
After the latest commit from today, your `.xz` compressed file works normally. :)

**Comment by midwan** [comment]
For the record:
- 7-zip libraries have been updated to v16.04 (from 9.22 beta)
- CHD support has been implemented
- 7-zip compressed archives and hardfiles can now be selected from the GUI

**Comment by Drag0nFly** [comment]
That is good to hear – thanks @midwan. I'll give the updated version a try. Wonder if zstd & lz4 are also supported via the 16.04 version (which actually sounds like April 2016, in *buntu terms. (but at least it isn't properly ancient as the prior incarnation was.) ;)
