### ISSUE TITLE
[feature req.] Option to disable 'Shutdown' menu item

### ISSUE THREAD

**Issue by Drag0nFly** [midwan/amiberry#855]
The Shutdown menu item (bottom left) has little use in a multi-user system, and it would be nice if it could be disabled via an option in amiberry.conf

As it stands now, one always has to make doubly sure not to hit it by mistake (which happened recently while doing some compiling in the background, pairing of bluetooth DS3 with the sony-hid patch for the current kernel, etc), and was a little inconvenient to have it shut-down the entire system because of an erroneous mousepress. ;-)
(actually, the mouse was sleeping, and I woke it in the 'wrong' place and it sent an extra keypress)

_(Apologies in advance if there already is an option for this, but I couldn't locate it.)_

**Comment by Drag0nFly** [comment]
Tested and works fine–great. btw., `disable_shutdown_button=no` should probably be added to the amiberry.conf template so others can find (I looked at the git commit to locate the syntax) :)

**Comment by midwan** [comment]
Amiberry will generate it automatically if it's not there, but I've also added it to the file on the repo now. :)
