### ISSUE TITLE
Unable to set triggers as buttons or use in game on Amiberry

### ISSUE THREAD

**Issue by fenster89411** [midwan/amiberry#859]
Cannot assign trigger buttons on xbox wired controller.

Example game will be Walker – however I cannot assign triggers for any game.
Triggers work with other emulators etc – it is only Amiberry
Amiberry is running pretty much OOB.

Using right analogue for moving left/right
Using left analogue for gun movement/aim

Currently using N/S/E/W for lock and fire.

I need to assign right trigger for fire
Left trigger for lock to be able to play.

Current custom controls from .aue

joyport1_name=JOY1
joyport1_amiberry_custom_none_dpad_up=Mouse1 Up
joyport1_amiberry_custom_none_dpad_down=Mouse1 Down
joyport1_amiberry_custom_none_dpad_left=Mouse1 Left
joyport1_amiberry_custom_none_dpad_right=Mouse1 Right
joyport1_amiberry_custom_none_left_shoulder=M
joyport1_amiberry_custom_none_south=None
joyport1_amiberry_custom_none_east=Joy1 Fire/Mouse1 Left Button
joyport1_amiberry_custom_none_west=F1
joyport1_amiberry_custom_none_start=None
joyport1_amiberry_custom_none_right_shoulder=Joy1 2nd Button/Mouse1 Right Button
joyport1_amiberry_custom_none_right_stick=None
joyport1_amiberry_custom_none_left_stick=None

**Expected behavior**
Able to assign triggers to custom mapping for in play

Pi v4
Retropie 4.7.19
Amiberry V3.3

**Additional context**
Is there a simple way that Im missing to use triggers in Amiga games – also the GUI could hold these options?
[amiberry.conf.txt](https://github.com/midwan/amiberry/files/7442507/amiberry.conf.txt)
[Walker.uae.txt](https://github.com/midwan/amiberry/files/7442510/Walker.uae.txt)

**Comment by midwan** [comment]
This is a known limitation so far, the triggers are not mapped to any function (yet).
I will look into improving this in future updates.

**Comment by midwan** [comment]
This is implemented in `dev`, after bbf94c1d7872aca0e493d65a7132c365176972f1 which concludes a rewrite of the input handling code. There may be a few glitches left there, needs more testing - but so far it seems to work for me. I've tested it using normal game controller and RetroArch mappings, on a PS4 gamepad and a Competition Pro USB joystick, so far.

Please test and provide feedback! :)
