### ISSUE TITLE
How well does Amiberry run on a Pi Zero?

### ISSUE THREAD

**Issue by rabejens** [midwan/amiberry#86]
This is not really an issue. I found a PS/2 keyboard in my "box-o-junk" which could accomodate a Pi Zero W to create an old-school "keyboard-style computer". The first thing I thought about was to emulate a somewhat beefed-up A500 or A1200 with it.

Did anyone already run Amiberry or another Port of UAE4ARM on a Pi Zero and how did the performance turn out? I want to play classic games on it, as well as run some of the old software for nostalgic reasons (DPAINT IV, CanDo, BlitzBasic, Scala (not the programming language)).

**Comment by midwan** [comment]
@rabejens 
The short answer is, "it runs, but slowly".

You can get much better performance with any faster Pi model, and in some cases even the Pi 3 struggles to keep up. The code can be further optimized to improve the situation of course, but the Zero will probably be a little slow for some things.

I'd recommend you give it a try and see, some things will be faster than a real A1200 (raw CPU speed for example), other parts might be slower.
