### ISSUE TITLE
AmigaDos "Unknown command IF" error on WHDLoad

### ISSUE THREAD

**Issue by ravallo** [midwan/amiberry#862]
Attempts to start WHDLoad game end up with AmigaDos screen and error "Unknown command IF". Similar to  #[820]

**Steps to reproduce the behavior:**

Either `pi@retropie:~/amiberry $ ./amiberry --autoload ~/RetroPie/roms/amiga/RainbowIslands_v1.4.1_0012.lha -G` or starting to Amiberry GUI and selecting ROM manually on WHDLoad Autoconfig on Quickstart, then "Start". 

Have rescanned paths and updated WHDLoad XML's. Checked that ROM's (basically whole Amiga Forever set) populate on Rom -> Main ROM file -dropdown.

Originally encountered this on retropie with version 3.3. installed through Retropie, reproduces identically from EmulationStation and from command line. Tried removing binary install and install from source, no change. Then compiled 4.1.6. from source and run that from command line, same result, so I assume I've missed something or something fishy going on on my setup...

On hard drive / CD -tab it populates DH0 with /tmp/, DH3 with whdload/boot-data, DH2 with ROM location (have tried couple different options) and DH1 with whdload save-data when ROM is selected on WHDLoad autoconfig.

**Workaround**

It seems that for some reason if I open Amiberry GUI, rescan the paths, and after that select the ROM manually, the game loads ok. For some reason Amiberry seems to lose the kickstarts on every restart. Rescan needs to be done on every restart, otherwise load fails. Also if I just restart on GUI, it loses the hard drives, need to reselect the WHDLoad autoconfig file to repopulate them.

Symlinks on whdboot/save-data/Kickstarts would seem fine:

```
pi@retropie:~/amiberry/whdboot/save-data/Kickstarts $ symlinks .
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/rom.key -> /home/pi/RetroPie/BIOS//rom.key
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick40063.A600 -> /home/pi/RetroPie/BIOS/amiga-os-310-a600.rom
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick37175.A500 -> /home/pi/RetroPie/BIOS/amiga-os-204.rom
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick40068.A1200 -> /home/pi/RetroPie/BIOS/amiga-os-310-a1200.rom
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick39106.A1200 -> /home/pi/RetroPie/BIOS/amiga-os-300-a1200.rom
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick40068.A4000 -> /home/pi/RetroPie/BIOS/amiga-os-310-a4000.rom
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick34005.A500 -> /home/pi/RetroPie/BIOS/Kick13.rom
absolute: /home/pi/amiberry/whdboot/save-data/Kickstarts/kick33180.A500 -> /home/pi/RetroPie/BIOS/amiga-os-120.rom
```

Running on RPI4, 32bit installs.

**Comment by midwan** [comment]
I can't recreate this, but I suspect it has something to do with permissions. What you mentioned about not being able to keep the ROM info between restarts points to something like that, at least.

The ROM list is cached in the `conf/amiberry.conf` file, which also holds other global settings for Amiberry. Check if that gets updated after you rescan, and make sure it's writeable by your username. Maybe it's something as simple as that.
