### ISSUE TITLE
Fix compilation warnings 

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#869]
With LTO, gcc/g++ gives these warnings:

src/osdep/gui/PanelCustom.cpp:40:7: warning: virtual table of type ‘struct string_list_model’ violates one definition rule [-Wodr]
   40 | class string_list_model : public gcn::ListModel
      |       ^
src/osdep/gui/PanelCustom.cpp:40:7: note: the conflicting type defined in another translation unit
src/osdep/gui/PanelCustom.cpp:62:7: note: virtual method ‘clear_elements’
   62 |  void clear_elements() override
      |       ^
external/libguisan/include/guisan/listmodel.hpp:100:16: note: ought to match virtual method ‘clear_elements’ but does not
  100 |   virtual void clear_elements()
      |                ^
src/cfgfile.cpp: In function ‘cfgfile_option_find_it.constprop’:
lto1: warning: function may return address of local variable [-Wreturn-local-addr]
src/cfgfile.cpp:479:8: note: declared here
  479 |  TCHAR buf[MAX_DPATH];
      |        ^
src/cfgfile.cpp: In function ‘cfgfile_option_find_it.constprop’:
lto1: warning: function may return address of local variable [-Wreturn-local-addr]
src/cfgfile.cpp:479:8: note: declared here
In function ‘au_fs_copy’,
    inlined from ‘_ZL10fixcharsetPc.part.0’ at src/filesys.cpp:756:13:
src/osdep/charset.cpp:76:9: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   76 |  strncpy(dst, src, maxlen - 1);
      |         ^
src/filesys.cpp: In function ‘_ZL10fixcharsetPc.part.0’:
src/filesys.cpp:756:24: note: length computed here
  756 |  au_fs_copy (s, strlen (tmp) + 1, tmp);
      |                        ^
src/drawing.cpp: In function ‘_Z23hsync_record_line_statei7nln_howi.part.0’:
src/drawing.cpp:4928:14: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 4928 |    state[-1] = LINE_BLACK;
      |              ^
src/drawing.cpp:258:15: note: at offset -1 to object ‘linestate’ with size 1205 declared here
  258 | static uae_u8 linestate[LINESTATE_SIZE];
      |               ^
src/drawing.cpp:4935:14: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 4935 |    state[-1] = LINE_DONE;
      |              ^
src/drawing.cpp:258:15: note: at offset -1 to object ‘linestate’ with size 1205 declared here
  258 | static uae_u8 linestate[LINESTATE_SIZE];
      |               ^
src/drawing.cpp:4905:14: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 4905 |    state[-1] = LINE_DECIDED; //LINE_BLACK;
      |              ^
src/drawing.cpp:258:15: note: at offset -1 to object ‘linestate’ with size 1205 declared here
  258 | static uae_u8 linestate[LINESTATE_SIZE];
      |               ^
In function ‘zfile_fgets’,
    inlined from ‘getconfigstoreline’ at src/cfgfile.cpp:6674:20,
    inlined from ‘calcformula’ at src/cfgfile.cpp:6409:28:
src/zfile.cpp:2324:14: warning: ‘fgets’ writing 5120 bytes into a region of size 4096 overflows the destination [-Wstringop-overflow=]
 2324 |   s1 = fgets (s2, size, z->f);
      |              ^
src/zfile.cpp: In function ‘calcformula’:
/usr/include/stdio.h:568:14: note: in a call to function ‘fgets’ declared with attribute ‘write_only (1, 2)’
  568 | extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)

`

**Comment by midwan** [comment]
Most of these are upstream issues, so they should normally be addressed there (WinUAE in this case).
I can certainly look into those that are Amiberry specific, though.
