### ISSUE TITLE
Audio settings cause emulation slowdown

### ISSUE THREAD

**Issue by amyren1966** [midwan/amiberry#870]
When setting the audio buffer to minimum and changing from push to pull, the game runs as reduced speed.

To Reproduce:
Create a new plain config as a standard A500 or A1200 setup, and add some game floppies, or use any existing floppy game config you might have already
I have tested with "The Lost Vikings (A500 setup), and Sensible Soccer v1.2 (A1200), but I think it will apply for other games as well.
Go to the audio tab and set audio buffer to minimum, and audio to "Pull". 
Save the config.
Start the game.
Observe the game speed.

Note that you must not start any emulation before testing this. This config must be loaded and started just after starting Amiberry.

As a special "feature" you can use the audio frequency settings to adjust the slowdown. The higher frequency, the slower the game runs. 
Try now to set the buffer size above minimum, and the game will run normal speed. 
Setting it back to minimum will not have any effect at this point.

Device raspberry pi 4,  Raspberry OS 32bit.
Tested on Amiberry v.4.1.6 and 4.2 beta.

**Comment by midwan** [comment]
I think this is "normal" in the sense that it's how SDL2 works, from what I understand.
Using the Pull method creates a callback which runs separately, and needs an audio buffer size to fill to send it to the audio chip. If that buffer size is not large enough, then the video updates are slowed down as we wait for it to catch up.

In my tests on a Pi400, the lowest buffer size I can use reliably using Pull Audio is 6 (which translates to 8192 bytes). Below that there is some stuttering sometimes (with buffer size 5) which gets worse the lower you go.

When using Push mode instead, the method of delivery is different: We push audio chunks to the output in regular intervals manually, so you can get away with smaller buffer sizes without slowing down the rest (assuming you have a fast enough device of course, this will still slow down on a Pi3 if you use very small buffer sizes).

Behind all this is SDL2's framework, and behind that there's also the Linux system's audio library used, which has it's own settings and behavior (depending on distribution this might change also!). And that's tied to the Linux kernel as well, with some having options to reduce audio latency further (realtime audio, usually for sound professionals).

**Comment by amyren1966** [comment]
Ok. But why will it only happen in first run after starting emulation? You can not get the issue by adjusting the settings after the game is loaded with normal settings.

**Comment by midwan** [comment]
Well, that I cannot explain really, as it does change behavior when I change the options on the fly here. Tested with TinyBobble (ADF) using the latest Amiberry from `master`, on Manjaro 64-bit on a Pi400. :)

**Comment by amyren1966** [comment]
I just tested the game running from whdload on the A4000 setup I have.
This is configured with 68040 and fastest CPU setting. Audio delay here was almost gone, but cpu fastest caused a terrible sound distortion on this game. Setting the cpu speed to 25 mhz made the distortion almost wanish and the delay was not to bad.
So I set up a floppy setup with the same cpu config and this is better than running the game on a standard A1200 setting.

For me this was unexpected, since I though it would be better to emulate a weaker cpu, so that the emulation would have more resources to handle the audio. 

BTW, that audio distortion mentioned above is only for the Sensible Soccer International Edition v1.2. I did not notice that when running SWOS from whdload.

**Comment by midwan** [comment]
It depends on what's being emulated - A500 has the most compatible modes, including "More Compatible" and Cycle Accurate. If these are enabled, more resources are used to increase emulation accuracy, so it can end up being quite demanding.

Fastest Possible will use as many CPU cycles as possible for the maximum emulated CPU speed, so it can take quite a toll on something that also requires Custom Chipset time (as most games do). Reducing the speed there would leave some more room for those things, so your observation above is correct.

I've changed the defaults with the latest updates, so that Pull mode is enabled and the Buffer size is set to 6 (8192), which from my tests seem to behave quite good. You can still customize them using `amiberry.conf` and individual .uae configs, of course.
