### ISSUE TITLE
Joystick/Mouse configuration documentation

### ISSUE THREAD

**Issue by redm123** [midwan/amiberry#871]
I'm trying to find a configuration of joystick and mouse that is working for me, but I have a hard time understanding how the available options are supposed to work. After finally upgrading to Amiberry 4.1.5, together with Recalbox 8.0, I was hoping to make use of some fixes that happened since the previous 3.3. However, somehow it still doesn't do what I would expect it to do. 

I think my problem is twofold:

1. In any case I think it would be good and very helpful to add some documentation to the wiki, and/or even within the GUI, that explains the options a little, how they are supposed to work, what to expect, what use case they are for, how they affect or are affected by other options. 
2. As "nothing" works, there is probably also something wrong. Maybe there is still something misconfigured, or something is fishy with the Recalbox auto config or the Retroarch config, or maybe even a bug. But I can't tell, as I don't how things _should_ work.

*Input / Swap Ports*: ok, it swaps device + device type between port 0 and 1. But why is this useful, beyond literally swapping ports? A use case I could imagine: I want to use my joystick in port 1 to get through some cracktro, which require mouse control in port 0. So after swapping ports the stick is in port 0, fine. However, as the type is also swapped, it is still of type Joystick. So it does not work as a mouse... so, wrong use case? misconfiguration? bug?

*Input / Mouse/Joystick autoswitching*: What is autoswitched? The device? Or the device type? Which port or ports does this affect? Which physical devices does this affect? What would trigger the switch?

*Input / Mouse Stick 0/1*: What does this mean? What stick does "stick" refer to? What should it do? If this somehow simulates a mouse, what would be the mouse buttons? Why would I emulate a mouse in port 1, if that's what it should do? What if that device type is set to "Joystick"? In any case, it does not seem to do anything for me...

*Input / Port x / Joystick vs. Gamepad* (as device type): What is the difference? What does it mean?

*Input / Port x / autofire: I understand "Autofire (toggle)" and "Autofire (always)", but what is "Autofire" in contrast to those two?

*Input / Virtual mouse driver*, *Input / Magic Mouse untrap*: I don't think they apply to me, but some doc would be good, too.

*Input / Both, Native only, Host only*: Mysterious... 

*Custom controls / Remap DPad to left axis*: What is left axis? What does it do? What is the use case, why would I want to do that?

*Custom controls*: in the mapping drop downs many entries are cut off, due to limited screenspace. Having the complete list in the wiki would be good (at least the more elaborate functions). Also for me it's not always clear what the meaning of some entries is. E.g. "Mouse Toggle P0 (First ": It's cut off and unclear what it would toggle.

What I'm trying to achieve: 
Some way to emulate a mouse, depending on the options I have. So that I don't have to go and get the mouse, just to click through some cracktro. Or with 2 players, when there is no port left for the mouse.

System:
Recalbox 8.0
Amiberry 4.1.5
Controller configuration through auto config and Retroarch ([R]).
Controller: I tried this with is some PS style controller, with dpad, two sticks, various buttons.

**Comment by midwan** [comment]
I've updated the Help contents in the GUI in the areas you mentioned, hopefully that will make it a bit more clear.

Regarding what you're trying to achieve, I think the Mouse/Joy auto-switch option is what you're looking for. It's meant to allow you to switch the device in port 0 from Mouse to Joystick and back, depending on which one's fire (or LMB) was pressed.

**Comment by midwan** [comment]
Thanks for the comments!
Based on them, I've made some minor adjustments to the text:

- I've added that Autoswitch only works when type is left to Default
- You are right about the Mouse Stick 0/1, those are the Port the controller is connected to, of course. I've corrected the text.
- Autofire being normal, means that you press fire and it fires at the selected rate, as long as you have it pressed. Toggle would mean that you press it and it starts firing, until you press it again to stop firing. And Always-On is self explanatory I think...
- Virtual Mouse: Yes, it used to be named Mousehack but it changed name to match the same in WinUAE. It's not only for touch input, though it's used there. It can be used with a normal mouse as well.
- Magic Mouse: I've added some more text to make it clear, that this is only useful in a windowed environment.

There may be a bug in the Mouse Stick function, as it doesn't seem to be doing what I expected. I'll look into that.

**Comment by midwan** [comment]
Looks like the mouse map function hasn't been working properly for a while now, thanks for bringing this up.
For now, only the Left analog stick is used, so I changed the GUI options accordingly.
You can use LShoulder/RShoulder for the LMouse/RMouse buttons when you enable this.
It doesn't matter which port the controller is connected to, it will always emulate the mouse on port 0.

**Comment by redm123** [comment]
> Thanks for the comments! Based on them, I've made some minor adjustments to the text:

Thanks a lot! The fog starts to lift. I think this should make things a lot clearer for users. There are still a ton of other things that can go wrong, so it's good to have some variables fixed ;)

> You can use LShoulder/RShoulder for the LMouse/RMouse buttons when you enable this.

Should this already work in 4.1.5, or did you just add this with the last commit? (looks like)

> Looks like the mouse map function hasn't been working properly for a while now, thanks for bringing this up.
> For now, only the Left analog stick is used, so I changed the GUI options accordingly.
> It doesn't matter which port the controller is connected to, it will always emulate the mouse on port 0.

Ok, this confirms my suspicion. Well, partly. I understand that Left should work. As this is also not the case for me, I may have some controller issue... (it's not a real, but just a no-name DualShock model, which may behave slightly different; or maybe a configuration or driver thing...). For normal directions I can use the dpad or the left stick interchangeably, not sure if it should be that way, although it's nice... I will investigate. At least now I know how it _should_ work :)

Can you say what Retroarch (?) key or event codes you expect for the left stick to emulate mouse directions?

That's what I see in the log for the controller:

```
Controller #0: PS3 Controller
      GUID: 030000008f0e00000300000010010000
Controller 0 is mapped as "030000008f0e00000300000010010000,PS3 Controller,a:b2,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpu
p:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,right
y:a3,start:b9,x:b3,y:b0,".
Retroarch controller cfg file found, using that for mapping
Controller Detection: input_enable_hotkey_btn : 8
Controller Detection: input_exit_emulator_btn : 9
Controller Detection: input_reset_btn : 0
Controller Detection: input_menu_toggle_btn : 2
Controller Detection: input_b_btn : 2
Controller Detection: input_a_btn : 1
Controller Detection: input_y_btn : 3
Controller Detection: input_x_btn : 0
Controller Detection: input_select_btn : 8
Controller Detection: input_menu_toggle_btn : 2
Controller Detection: input_start_btn : 9
Controller Detection: input_l3_btn : 999
Controller Detection: input_r3_btn : 999
Controller Detection: input_l_btn : 4
Controller Detection: input_r_btn : 5
Controller Detection: input_up_btn : -1
Controller Detection: input_down_btn : -1
Controller Detection: input_left_btn : -1
Controller Detection: input_right_btn : -1
Controller Detection: input_l_x_plus_axis : 0
Controller Detection: input_l_y_plus_axis : 1
Controller Detection: input_r_x_plus_axis : 2
Controller Detection: input_r_y_plus_axis : 3
Controller Detection: input_l2_axis : -1
Controller Detection: input_r2_axis : -1
Controller Detection: count_hats : 1
Controller Detection: invert left  y axis: 0
Controller Detection: invert left  x axis: 0
Controller Detection: invert right y axis: 0
Controller Detection: invert right x axis: 0
```
