### ISSUE TITLE
Feature: m3u playlist for multidisc games

### ISSUE THREAD

**Issue by legluondunet** [midwan/amiberry#873]
Hello,
do you plan to add m3u playlist support, like UAE already supports:
https://docs.libretro.com/library/puae/#m3u-and-disk-control
It is very usefull for multidisc games.

**Comment by midwan** [comment]
@legluondunet 
You mean `PUAE` has that, not all UAE implementations ;)

Not sure about m3u support yet, but I just implemented the "Diskswapper" feature from WinUAE which does a similar job.
No GUI for it (yet), but you can add your disks in a config file (same as in WinUAE), and swap them using END + 1-10, or END + SHIFT + 1-10 for slots 11-20. The diskswapper holds a total of 20 available slots.

WinUAE documentation regarding the GUI is here: https://www.vware.at/winuaehelp/DiskSwapper.html
And generic documentation which also mentions the in-game swapping feature using keyboard shortcuts, is here: http://guide.abime.net/gguides/winuaeb.htm

I'll look into implementing a GUI for this also, but it works already with a config file. You just have to add the related rows manually for now.

**Comment by midwan** [comment]
The GUI part has also been implemented with 43a0cbe2cdfbea8d0193d9c9ac9d548c44cbf0aa
Closing this for now, as the feature is implemented, even though not in the same way as suggested. If there's enough interest in m3u specifically, we can take a look in the future. But for now, I think this is good enough for most people and syncs with the upstream WinUAE.
