### ISSUE TITLE
Unable to navigate to all fields within settings with keyboard or joypad

### ISSUE THREAD

**Issue by vretro** [midwan/amiberry#874]
Unable to navigate to all fields/options within settings using Keyboard tab/arrow keys or Joypad/stick input.

Example: Unable to move the focus to “Sound > Floppy Drive Sound Emulation > Enable floppy drive sound”

Other examples:
Sound Buffer Size
Floppy drives > DF1:

Pi v4 
Retropie 4.7.19
 Amiberry V3.3

**Comment by midwan** [comment]
These have been fixed in newer versions, but unfortunately RetroPie is still only offering v3.3.
I'm not sure when they will offer the latest version, we have a separate case with them about that (https://github.com/midwan/amiberry/issues/807).
