### ISSUE TITLE
Ghosts'n Goblins unplayable slow when using it with a uae config file

### ISSUE THREAD

**Issue by Neo-Stone** [midwan/amiberry#875]
Ghosts'n Goblins becomes unplayable slow after creating a uae config file and restarting the game.

System: 
Pi 400
RetroPie v4.7.19
Amiberry V3.3

Game: 
GhostsNGoblins_v1.4.lha

Reproduce:
Start GhostsNGoblins_v1.4.lha from Retropie/Emulationstation until CFOU intro runs
Enter Amiberry menu (F12)
Save configuration (uae)
Quit game
Restart GhostsNGoblins_v1.4.lha from Retropie/Emulationstation until CFOU intro runs

Now already the intro runs far slower than before even if the config file is still unchanged!
Try to enter the game. The game is extremely slow and unplayable.

My intention is to use the configuration file to change controller / change custom1 / etc.

**Comment by midwan** [comment]
There's something weird with that intro from what i can tell so far, it stops completely in newer versions of Amiberry as well.
The emulator is still responding, but the image freezes and the intro doesn't show anything else.

Can you skip the intro completely, does that help?

**Comment by Neo-Stone** [comment]
Skipping is possible with setting whdload_custom1=240 (for example).
But this is only possible in the corresponding uae config file.

So that is not helping, sorry. Because one needs the config file to do so. 
And with the config file the described problem occurs. 

I was not able (till now) to skip the intro using the command line option
  -s whdload_custom1=240

It would be great just to skip the intro and the trainer, because I just do not want that.
Any other possibilities? 
Or is my command line option wrong?

**Comment by midwan** [comment]
Using `-s whdload_custom1=240` works as expected in the current version of Amiberry, I think there was a bug in earlier versions that didn't parse those options.

e.g. the test I just did was using this full command:
`./amiberry --autoload lha/Games/G/GhostsNGoblins_v1.4.lha -s whdload_custom1=240`

and it started without the intro (and it seems to be running at normal speed).

**Comment by Neo-Stone** [comment]
Ok, thanks. So it is a bug in the old (v3.3) amiberry version. I've assumed that.

So what to do in retropie now? 
Wait for a newer version of amiberry?
Is there a possibility of disabling it in the whdload_db.xml file? 
Or is there another possibility of getting rid of that intro and trainer?

**Comment by midwan** [comment]
It behaves the same way with or without a config here, and the option to skip the intro can be saved in the config so it sticks.
However, this particular game seems to have issues - at least for me:
- The intro gets stuck if you don't disable it
- Starting the game after the title screen seems to get stuck also, or at least I get no response from the game.

Considering that the vast majority of games work fine, I suspect it's something to do with this specific one. I didn't test the ADF version to see if it's any better.

**Comment by Neo-Stone** [comment]
> Considering that the vast majority of games work fine, I suspect it's something to do with this specific one.

Agreed.

I did a lot of testing the last days and I have found a small workaround for retropie/amiberry v3.3 at least.

A very small change in the `whdload_db.xml` helps getting the game playable without a config file or the possibility to skip the intro in amiberry v3.3 (should be obsolete in newer amiberry version where skipping the intro/trainer is possible). 

Changing `PRIMARY_CONTROL=MOUSE` to `PRIMARY_CONTROL=JOYSTICK` in `whdload_db.xml` inside `GhostsNGoblins_v1.4` helps. At least control for intro and trainer is now done using the Keyboard (and not the Mouse). In addition the normal Joystick/Gamepad is enabled, which makes the game playable. I've encountered no slowdowns as no config file is used.

My changed `whdload_db.xml` for `GhostsNGoblins_v1.4` looks like this now:
....
	`<game filename="GhostsNGoblins_v1.4"  sha1="3478f4f694b7445900bc983a5d9693e1e685178e">`
		`<name>Ghosts 'n Goblins</name>`
		`<subpath>GhostsNGoblins</subpath>`
		`<variant_uuid>2a494335-5535-535c-bacc-9a8031d0e112</variant_uuid>`
		`<slave_count>1</slave_count>`
		`<slave_default>GhostsNGoblins.slave</slave_default>`
		`<slave_libraries>False</slave_libraries>`
		`<slave number="1">`
			`<filename>GhostsNGoblins.slave</filename>`
			`<datapath></datapath>`
			`<custom>`
			`C1:X:Original Hi-Score Cheat Mode:0`
			`C1:X:Unlimited Lives:1`
			`C1:X:Unvulnerability:2`
			`C1:X:Unlimited Time:3`
			`C2:L:as starting Level for PL1:Level 1,Level 2,Level 3,Level 4,Level 5,Level 6,Level 7`
			`C3:L:as starting Weapon for PL1:Flames,Spear (Default),Axe,Crucifix,Knives`
			`C4:L:as starting Level for PL2:Level 1,Level 2,Level 3,Level 4,Level 5,Level 6,Level 7`
			`C5:L:as starting Weapon for PL2:Flames,Spear (Default),Axe,Crucifix,Knives`
			`BW`
			`C1:X:Second Button to jump (&amp; CD32 PAD):4`
			`C1:X:Turn in jump possibility:5`
			`C1:X:Force JoyUp support with Second Button enabled:8`
			`C1:X:Skip CFou's intro (no leave it!!!):6`
			`C1:X:Skip CFou's trainer (no leave it too!!!):7`
			`</custom>`
		`</slave>`
		`<hardware>`
		`PRIMARY_CONTROL=JOYSTICK`
		`PORT0=MOUSE`
		`PORT1=JOY`
		`FAST_COPPER=FALSE`
		`JIT=FALSE`
		`SCREEN_AUTOHEIGHT=FALSE`
		`SCREEN_HEIGHT=480`
		`SCREEN_CENTERH=SMART`
		`SCREEN_CENTERV=SMART`
		`</hardware>`
	`</game>`
....

**Comment by midwan** [comment]
@Neo-Stone It would be best to report the XML changes to the relevant repository, so they can be included in the next update: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder

**Comment by Neo-Stone** [comment]
Thanks for the link and your response.

Wouldn't it be a good idea to place a bug for the game here: [http://mantis.whdload.de/search.php?project_id=1092&hide_status_id=-2](http://mantis.whdload.de/search.php?project_id=1092&hide_status_id=-2)?

Ideally we get a new version and/or slave for GhostsNGoblins.
In addition a change to the `whdload_db.xml` might be a good idea too, I would agree.

What do you think?

One more question:
Can you provide me a working binary new (4.1.x/4.2.x) amiberry version for raspi/retropie?
I would like to use it for my further testing purposes. I would really appreciate your help, thanks.
