### ISSUE TITLE
File name kickstart 3.2?

### ISSUE THREAD

**Issue by stuffu** [midwan/amiberry#876]
Think I read that you added support for kickstart 3.2 a while ago but can’t seem to find anything in the wiki on what the file name should be. Also, as 3.2.1 just recently was released should you be able to replace the file and keep file name? Just planning ahead…

thanks for the great work and looking forward to the “final” 4.x.

**Comment by solskogen** [comment]
The filenames doesn't matter. 3.2.1 must be chosen manually, but 3.2 should
show up in the selector.

søn. 26. des. 2021, 23:39 skrev stuffu ***@***.***>:

**Comment by midwan** [comment]
@stuffu As @solskogen said above, the filenames don't matter, kickstarts are discovered based on their checksums.
3.2 Kickstarts are already included in the latest Amiberry versions, 3.2.1 hasn't ben added yet but I'll add that as part of the next released version.
