### ISSUE TITLE
Problem with installing 64bit version

### ISSUE THREAD

**Issue by zxcQS** [midwan/amiberry#879]
Hello to all users and I wish you all the best in the new year!

My English is poor but maybe I can write what I mean. 
I have a question about installing Amiberry in the 64bit version. I install from source code but the process hangs at some point in the compilation.
I'm using raspios bullseye arm64 lite on the raspberry pi 4 2GB.

My installation way looks like this:

sudo apt-get update && sudo apt-get upgrade
sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
sudo apt-get install libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev libdrm-dev libgbm-dev libudev-dev libasound2-dev liblzma-dev libjpeg-dev libtiff-dev libwebp-dev git build-essential

sudo apt-get install gir1.2-ibus-1.0 libdbus-1-dev libegl1-mesa-dev libibus-1.0-5 libibus-1.0-dev libice-dev libsm-dev libsndio-dev libwayland-bin libwayland-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev x11proto-randr-dev x11proto-scrnsaver-dev x11proto-video-dev x11proto-xinerama-dev
git clone https://github.com/libsdl-org/SDL.git
cd SDL
./configure --enable-video-kmsdrm --enable-video-opengl --enable-video-opengles --disable-video-wayland --disable-video-rpi --disable-video-x11 --disable-video -vivante --disable-video-cocoa --disable-video-directfb --disable-video-vulkan --disable-directx
make -j4
sudo make install
cont
wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz
wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz
tar xf SDL2_image-2.0.5.tar.gz
tar xf SDL2_ttf-2.0.15.tar.gz
cd SDL2_image-2.0.5
./configure
make -j4
sudo make install
cont
cd SDL2_ttf-2.0.15
./configure
make -j4
sudo make install
cont
sudo apt-get install libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev
git clone https://github.com/midwan/amiberry
cd amiberry
make -j4 PLATFORM = rpi4-64-dmx

I am not sure this way is correct. Everything worked fine on the raspios 32bit system. Can anyone help me?

**Comment by solskogen** [comment]
Does it really hang? It takes quite some time to compile amiberry.

søn. 2. jan. 2022, 10:40 skrev zxcQS ***@***.***>:

**Comment by zxcQS** [comment]
I think so.  I waited 1.5 hours

**Comment by midwan** [comment]
@zxcQS
How much RAM does your Pi4 have?
Try using fewer CPU cores to compile, like -j3 or -j2 to see if that helps.
If it runs out of memory, it will start using the pagefile and then things will get _really_ slow or even hang. If you've got a 1GB model, that's quite possibly what's happening here.

**Comment by zxcQS** [comment]
Yes, that was it.  
I deleted the amiberry folder, download  and recompiled the program with -j2.  Compilation was successful, but after entering the command ./amiberry the program does not start.  There is only the mouse pointer in the background of the console.  The pointer reacts to the movements of the mouse.  No message appears on the console.  
Maybe there is some problem with SDL2 on 64bit system?

**Comment by midwan** [comment]
If you're going to use the Dispmanx version, you'll need to make sure that:
- you have the `fkms` driver enabled, not `kms`, in `/boot/config.txt`
- you have the dispmanx files installed in your system (I expect that you do, otherwise you'd probably see compilation errors)

**Comment by zxcQS** [comment]
This was exactly what was causing the problem. I changed the command in config.txt from
dtoverlay = vc4-kms-v3d
on:
dtoverlay = vc4-fkms-v3d
and it worked!
Thank you very much for help :-)
