### ISSUE TITLE
cursor-x2.bmp has no alpha channel

### ISSUE THREAD

**Issue by fogobogo** [midwan/amiberry#88]
This looks rather odd. Also, not sure if it's such a good idea to begin with since checking for high-resolutions tells you nothing about the physical screen size.

**Comment by midwan** [comment]
@fogobogo 
Thanks, this is my bad: I edited the files to clean up the sizes and colors recently, but mistakenly saved the x2 version in 24-bit format instead of 32-bit.

Though ideally we should convert them to PNG to save some space...
