### ISSUE TITLE
Raspberry Pi OS Lite Bullseye sound lock up

### ISSUE THREAD

**Issue by henrikstengaard** [midwan/amiberry#882]
**Describe the bug**

Amiberry emulation locks up when any sound is being played, but I can still press F12 to show gui and quit Amiberry. If no sounds are played like game sounds, trackers then Amiga emulation runs fine.

I can hear about 0.5-1.0 second of sound before it locks up and if I increase sound buffer I can hear maybe 1.5 seconds of sound. I have tried both pull and push mode for sound and Amiberry still locks up.

I'm not sure if this is a Raspberry Pi OS Lite configuration issue or compiling SDL2 and Amiberry.

**To Reproduce**

1. Clone master branch with latest commit 5413eeb4baa023b84763a8ceb7cdf5549eee53f3.
2. Compile SDL2 and described in wiki FAQ page.
3. Compile Amiberry with platform rpi4-sdl2.
4. Start Amiberry with default configuration and run A1200 with 030 CPU, FPU, Z3 32MB, JIT.
5. Start a game og play mod to produce sound.
6. Amiga emulation locks up as soon as first "sound chunk" is played.

**Expected behavior**

No lock up of Amiga emulation when sounds are played.

**OS and Hardware**

- OS: Raspberry Pi OS Lite, Release date: October 30th 2021 (Raspbian GNU/Linux 11 bullseye) 

- Device: Raspberry Pi 4B rev 1.1

**Additional context**

I have added following lines to /boot/config.txt to force 1080p hdmi resolution:
```
hdmi_ignore_edid=0xa5000080
hdmi_group=1
hdmi_mode=16
```

**Comment by solskogen** [comment]
If you change 
`dtoverlay=vc4-kms-v3d` to `dtoverlay=vc4-fkms-v3d` in `/boot/config.txt` (and reboot) does that change anything?

**Comment by henrikstengaard** [comment]
I managed to get it sound working 👍.

Here's what I did:
1. Started from scratch again with a clean MicroSD and Raspberry Pi OS Lite, Release date: October 30th 2021.
2. Compiled and installed SDL2 v2.0.18 with commands:
```
sudo apt-get --assume-yes update && sudo apt-get --assume-yes upgrade

sudo apt install gcc g++ debhelper libasound2-dev libdbus-1-dev libegl1-mesa-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles-dev libpulse-dev libudev-dev libibus-1.0-dev libsndio-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxxf86vm-dev libxt-dev libxv-dev libsamplerate0-dev wayland-protocols

./configure --enable-video-kmsdrm --enable-video-opengles --enable-arm-neon --disable-video-rpi --disable-pulseaudio --disable-esd --disable-video-wayland --disable-video-opengl --disable-video-x11

make -j$(nproc)

sudo make install
```
3. Compiled Amiberry master commit 5413eeb4baa023b84763a8ceb7cdf5549eee53f3 with commands:
```
sudo apt-get --assume-yes install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev

make clean

make -j2 PLATFORM=rpi4-sdl2
```
4. Create file `/etc/asound.conf` with commands:
```
sudo nano /etc/asound.conf
```
5. Enter following contents:
```
defaults.pcm.card 1
defaults.ctl.card 1
```
6. Save file with `CTRL + X` and press `y` and enter.
7. Reboot with command:
```
sudo reboot
```

Amiberry v4.2.0 sound is now working smoothly with default settings sound buffer 6 and pull audio.

So it was a Raspberry Pi OS Lite configuration issue and not Amiberry related, but quite tricky to figure out with changes to Raspberry Pi OS. The missing link was /etc/asound.conf which fixed the sound issue.

This could also help others with same distro and issue.

I can only imagine keeping Amiberry working on various distro is a challende as well.

**Comment by solskogen** [comment]
I wouldn't suggest you that, because now you've got two installations of SDL2. In the FAQ you'll find a small guide on how to do it instead.

**Comment by henrikstengaard** [comment]
Ok, so don't run apt-get install sdl2 dev command `sudo apt-get --assume-yes install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libflac-dev libmpg123-dev libpng-dev libmpeg2-4-dev` because it will install older SDL2 version?

**Comment by solskogen** [comment]
Correct. Follow the FAQ and you'd be ready to go :)

**Comment by solskogen** [comment]
You might want to join us on Discord as well :)
