### ISSUE TITLE
Banshee (AGA) - Shifting screen

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#887]
Raspberry Pi4B 4GB running amiberry 4.1.6 with AmigaOS 3.2.1. I start the WHD-Load games from the workbench. The problem exists in both the 32-bit version under RetroPie and the 64-bit version under Manjaro.

Hello Midwan,
at this point I would like to wish you a happy new year 2022 and say thank you for all your good work for the Amiga community.

Please take a look at these two screenshots.
![1](https://user-images.githubusercontent.com/58906142/150683599-fde4fea1-1cb9-41fd-a46d-60639fd33496.jpg)

![2](https://user-images.githubusercontent.com/58906142/150683601-93cbc0af-ee94-47a8-b5dd-ed3543550211.jpg)

You can clearly see the left-shifted ingame screen of Banshee (AGA). Of course that's not nice.
The problem has existed for a long time, I don't remember exactly since which amiberry version. 

The strange thing is that the intro screen is displayed completely normally.
![3](https://user-images.githubusercontent.com/58906142/150683628-8f11b41b-6e25-4b98-b38d-ae97cecf6990.jpg)

Here you can see my display settings. 
![4](https://user-images.githubusercontent.com/58906142/150683634-e25c4c1f-cb97-41ad-915d-de5cd5e3fb1e.jpg)

I have this problem only with Banshee (AGA). Do you have an idea how to fix that?

Cheers
Retro1968

P.S.: On my original Amiga 1200 and my FPGA, Banshee (AGA) runs perfectly under AmigaOS 3.2.1.

**Comment by midwan** [comment]
Try increasing width to 720?

**Comment by Retro1968** [comment]
Changing to Width=720 only changes the very first loading screen, which shows multiple planes. Instead of full screen, the screen now has black borders on the left and right. Otherwise it remains the same as in all the photos above.

**Comment by midwan** [comment]
Remove Horizontal Auto centering

**Comment by Retro1968** [comment]
Now all screens are shifted to the left. In addition, the very first loading screen, which shows several planes, now has color errors. I've come to the conclusion that the horizontal auto centering of amiberry doesn't work on the Banshee ingame screen. What do you think?

**Comment by midwan** [comment]
It works normally here with 4.2.0, with width set to 720 and no Horizontal Auto-centering...

**Comment by Retro1968** [comment]
Can you reproduce the error with my settings? You mean the 4.2.0 developer version?

**Comment by midwan** [comment]
4.2.0 is on master currently, not yet released as a binary but will be soon.
The `dev` branch has an even newer version, currently versioned as 4.3.0.

If I enable auto centering, then I can see the same result as you, but it works normally if I disable it.

**Comment by midwan** [comment]
![image](https://user-images.githubusercontent.com/3877365/150690396-bc1cbb10-4cb2-4e4e-9041-378142c0da35.png)

![image](https://user-images.githubusercontent.com/3877365/150690412-2672c722-1bb0-4ade-87ad-90ae5a79c970.png)

**Comment by Retro1968** [comment]
I was able to reproduce your solution, but I'm not happy with it. You can see from the photos above that I had real full screen on my 4:3 monitor. Except for Banshee, EVERY game ran in full screen, i.e. over the entire screen. With your solution, I now have black borders on the left and right... and that's just to avoid having a left-shifted screen in one game (Banshee). I do not like it. Is there really no better solution?

**Comment by midwan** [comment]
Not for this game, I'm afraid. It has to do with how it shows the graphics on screen. You can use a script to change emulator settings on the fly when you launch it, and then change them again when you quit, I guess.

Even the newer `dev` version which uses the latest custom chipset updates from WinUAE, works the same way with this game.

**Comment by Retro1968** [comment]
Why does the horizontal auto center of amiberry do not work on the ingame screen of banshee?

**Comment by Retro1968** [comment]
What kind of screen is that?

**Comment by midwan** [comment]
It does technically work, but with the main screen which is the background - the left hand side panel seems to be on a separate plane, with it's own width, so it does not count as part of the main one - that's my best guess scenario, since I don't know what exactly they've done of course. The result is that the "sea" in the first level is centered perfectly if you enable auto centering, but the left panel is then cut-off.

**Comment by Retro1968** [comment]
Ist es zu aufwendig für Dich da mal rumzuprobieren, wie man den amiberrycode optimieren könnte?

**Comment by midwan** [comment]
There's nothing to "optimize" here, this is a game-specific behavior and does not apply elsewhere. Not sure it's worth the trouble of trying to do something differently, just for a single case...

**Comment by Retro1968** [comment]
Yes, you never know beforehand whether something like this is worthwhile. But do you remember how we managed to get full screen under Manjarolinux by trial and error? It was worth it. You were fooling around back then too.
