### ISSUE TITLE
Updated release builds?

### ISSUE THREAD

**Issue by n0rt0nthec4t** [midwan/amiberry#888]
Are there going to me more updated release builds (prebuilt), since the last was 4.1.6?

**Comment by midwan** [comment]
Yes, v4.2.0 is almost ready - troubleshooting some issues with the FloppyBridge controller which I'm hoping to improve, then it will be released as a binary also.

**Comment by n0rt0nthec4t** [comment]
Ah ok. thats the part I'm interested in, FloppyBridge ;-)
