### ISSUE TITLE
Custom controlls disappearing in v4.x.x, in Retropie

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#889]
I've tried Amiberry 4.1.6. in Retropie,  When I run the UAE configuration directly from the Retropie UI, it loads the game correctly,
but when I open the Amiberry GUI durring game, the saved custom control disappear and is reset to the default settings.
Other settings - CPU, Display, etc is there.

The exception is if I start Amiberry separately and select a configuration from the list in the emulator,
then everything is visible and everything works correctly.

This behavior is from v 4.0 to 4.1.6.
I have tested all of them.

- OS: retropie-buster-4.7.1-rpi4_400
- Raspberry Pi 4, 4GB

**Comment by midwan** [comment]
@Tomato1981 
Please try with the latest from `master` - I cannot recreate the issue there, so either it's fixed already, or I'm going to need exact steps to recreate it, if it still fails for you.

This is what I tried:
- Launched a WHDLoad game
- Opened the GUI, configured Custom Control for a button on my controller (e.g. Open GUI)
- Saved the configuration for that game with the suggested title
- Closed down the emulator
- Launched the same game again
- Opened the GUI, checked Custom Controls -> My configuration was still there, as expected

**Comment by Tomato1981** [comment]
Thanks for the effort;)
I know that running programs directly through UAE configuration is outdated, but still the best.
