### ISSUE TITLE
Red and Blue button swapped. maybe.

### ISSUE THREAD

**Issue by fogobogo** [midwan/amiberry#89]
config.h states:

/*
 * Virtual Key for CD32 Blue button
 * default: END (279)
 */
#define VK_Blue SDL_SCANCODE_PAGEDOWN

/*
 * Virtual Key for CD32 Red button
 * default: PAGEDOWN (281)
 */
#define VK_Red SDL_SCANCODE_END

Not sure if that's intentional.

**Comment by midwan** [comment]
@fogobogo 
It's intentional, to better match the layout of the original CD32 controller:

![image](https://cloud.githubusercontent.com/assets/3877365/25195617/7884d32e-253e-11e7-8bb8-f34b02163d91.png)
