### ISSUE TITLE
Smart centering causes glitches

### ISSUE THREAD

**Issue by Tomato1981** [midwan/amiberry#890]
Hi, I've tested a lot of games and found that smart centering, especially vertical centering, causes a lot of glitches.
When the image slides, from the bottom, the emulator keeps trying to center and it causes the image jumping.
I would be grateful if you would bring back the option of manual offset, like in version 2.25.
I know you don't want to go back to the past, but please at least put this setting as a command in the UAE file,
if you don't want to put it in the gui menu.

Thanks a lot and I appreciate your work.)

- OS: retropie-buster-4.7.1-rpi4_400, PiOs (bug in every os)

- RPi4 (4GB)

**Comment by midwan** [comment]
I've brought back the option of V. Offset, this will be included in the v4.2.0 release coming soon.

**Comment by midwan** [comment]
On top of that, I've also implemented a Horizontal offset setting, which might also help with custom screen sizes (width)

**Comment by Tomato1981** [comment]
Thanx a lot:)
Interestingly, everything through WHDLoad is shifted, but when you run the same game through ADF, it's OK.
For example Lemmings - the intro animation is significantly shifted down and the main game is up.
It's something deep in WHDLoad.
