### ISSUE TITLE
macOS port fails to build

### ISSUE THREAD

**Issue by Kreeblah** [midwan/amiberry#891]
**Describe the bug**
https://github.com/midwan/amiberry/commit/3e382c5793bea305416cefac56e7562bdf315170 ported AmiBerry to ARM Macs, which is awesome, but I think a couple of things got missed in the checkin, because I'm seeing some odd results when building that commit.

**To Reproduce**

1. Check out https://github.com/midwan/amiberry/commit/3e382c5793bea305416cefac56e7562bdf315170
2. Run `make PLATFORM=osx`
3. Observe the output

**Expected behavior**
I'd expect it to build.

**Actual behavior**
libguisan fails to build because the directory `external/libguisan/dylib` is missing.

After manually creating that directory, the libguisan makefile doesn't seem to recognize that not all of the targets were successfully built without first doing a `make clean`.

Then, after successfully building libguisan.dylib, the build ends with the following:

```
sh make-bundle.sh
cat: Info.plist.template: No such file or directory
Removing old App directory
Creating App directory
Entitlements.plist: cannot read entitlement data
cat: conf/amiberry-osx.conf: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```

Taking a look at `make-bundle.sh`, it doesn't look like `Info.plist.template` was included in the checkin, and without that, the entitlements step fails.  I also don't see a `conf/amiberry-osx.conf` in the tree, either.  Lastly, line 40 (the long `mkdir` line) has some typos in it, and should be:

`mkdir -p ~/Documents/Amiberry/Hard\ Drives ~/Documents/Amiberry/Configurations ~/Documents/Amiberry/Controllers ~/Documents/Amiberry/Logfiles ~/Documents/Amiberry/Kickstarts ~/Documents/Amiberry/RP9 ~/Documents/Amiberry/Data/Floppy_Sounds ~/Documents/Amiberry/Savestates ~/Documents/Amiberry/Screenshots ~/Documents/Amiberry/Docs`

**Desktop (please complete the following information):**

- OS: macOS 12.2

**Additional context**
I'm also unable to build later commits due to some Linux-specific stuff that's been checked into the serial IO code, but I haven't taken the time to track that down yet.

Love Amiberry? Please consider supporting our collective:
👉  https://opencollective.com/amiberry/donate

**Comment by midwan** [comment]
Should be fixed now, with https://github.com/midwan/amiberry/pull/892

**Comment by solskogen** [comment]
Reopen please. 
While amiberry compiles, it doesn't start:

```
/Users/solskogen/amiberry/amiberry ; exit;
solskogen@tenderheart ~ % /Users/solskogen/amiberry/amiberry ; exit;
dyld[63742]: Library not loaded: libguisan.dylib
  Referenced from: /Users/solskogen/amiberry/amiberry
  Reason: tried: 'libguisan.dylib' (no such file), '/usr/local/lib/libguisan.dylib' (no such file), '/usr/lib/libguisan.dylib' (no such file), '/Users/solskogen/libguisan.dylib' (no such file), '/usr/local/lib/libguisan.dylib' (no such file), '/usr/lib/libguisan.dylib' (no such file)
zsh: abort      /Users/solskogen/amiberry/amiberry

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by Kreeblah** [comment]
Do you have `dylibbundler` installed?  If so, the build process should be bundling it into the .app and updating the binary to look there.

If not, then you need to copy external/libguisan/dylib/libguisan.dylib into /usr/local/lib for the app to find it.

**Comment by Kreeblah** [comment]
Oh, I just noticed you're running the binary directly.  I'm not sure it'll work outside of the app bundle.

**Comment by solskogen** [comment]
I'm running the Amiberry.app
