### ISSUE TITLE
Having trouble running Giana Sisters SE

### ISSUE THREAD

**Issue by redm123** [midwan/amiberry#895]
I'm trying to run the wdhload version of Giana Sisters Special Edition, but all I get is a black screen. I tried various hardware, kickstart, etc settings, but it's always the same. The floppy version of the game runs fine (only the intro is a bit fast).

I'm using the HDD version 1.2 from here: https://pixelglass.org/#gianase 

Could this be wdhload related? But it seems at least the slave is correctly found. The wdhload XML has a Giana Sisters SE 1.2 entry, but this seems to be different...

I'm using Amiberry 4.1.5 on Recalbox 8.0.2.

**Comment by midwan** [comment]
@redm123 
This seems to be related to the .lha pack indeed - it's also not recognized by Amiberry (missing from the XML), so it tries to launch it using the fallback method - @HoraceAndTheSpider have you seen this release? Perhaps it can be added to the XML?

The CD32 version works well also, so perhaps that's a good alternative to use for now.

**Comment by redm123** [comment]
Ah right, trying the CD32 is a good point, didn't think of it... That works fine. Thanks!

Btw. there also seems to be a 1.0 version, that I tried first, which also does not run as lha: https://www.vintageisthenewold.com/giana-sisters-s-e-special-edition-giana-sisters-revamped-by-reimagine-games
