### ISSUE TITLE
Amiberry can't read files from mounted drive

### ISSUE THREAD

**Issue by Barr-find** [midwan/amiberry#901]
**Describe the bug**
I have mounted MicroSD exFAT formated drive into /mnt folder and amibery can't see those files. OS can see them and can do all operations on them. I even try to symlink file location to My /home/user/AmigaFiles folder but Amibery can't see this symlink ether.

**To Reproduce**
Mount exFAT partition to any location using OS and try to access those files using Amiberry.

**Comment by midwan** [comment]
Which Amiberry version? Which OS/distro?
There were plenty of updates in this area rather recently, so if you are running an older version it might be worth testing with the current one from `master` (v4.2.0).

**Comment by Barr-find** [comment]
Ohhh Sorry forgot about details. Amiberry v2.18 inside Amibian 1.4.1001 Distro for Raspberry Pi 3b+. I still have WIFI problems on that distro so I will not be able to update it right now.

**Comment by midwan** [comment]
v2.18 is very old, and no longer being updated.
This has been fixed since in the later versions, which work correctly with both symlinks, VFAT filesystems and unicode filenames.
If you discover an issue with the latest version regarding this, feel free to re-open this ticket.
