### ISSUE TITLE
Amiberry 4.2.0 - JIT and mouse problems 

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#905]
Raspberry Pi 4, Manjaro Linux, AmigaOS 3.2.1 running WHDLoad Games.

Hello Dimitris,
i have these Problems after compiling amiberry v4.2.0 (2022-02-022)

1. If I compile the source code with the option:

make -j2 PLATFORM=rpi4-64-dmx

I don't have any mouse problems, but I can't activate JIT in the amiberry menu. Only if i use a configfile in which
JIT is activated, JIT runs. I can see that in sysinfo. But in the amiberry menu, JIT is also displayed as deactivated and cannot be selected. When I press the "QUIT" button in the menu, amiberry doesn't exit. 

2. If I compile the source code with the option:

make -j2 PLATFORM=rpi4-64-sdl2

I can activate JIT, but have mouse problems. I can use the mouse on the workbench and in the amiberry menu without any errors. Only when I load a WHDLoad game, for example "Abandoned Places" does the mouse not work in the game. I don't see a mouse pointer either.

What can be the reason? 

Cheers
Retro1968

**Comment by solskogen** [comment]
Are you running it remote?

lør. 26. feb. 2022, 13:27 skrev Retro1968 ***@***.***>:

**Comment by Retro1968** [comment]
Remote? Do not understand.
I run it like described in my first post.

**Comment by midwan** [comment]
The JIT option in the GUI is a bug I introduced recently, due to a typo. It will be fixed soon.
Regarding the mouse, check if you have the right settings in the Input Panel. The WHDLoad default options can change your input ports according to what you have in amiberry.conf.

**Comment by midwan** [comment]
Fixed with https://github.com/midwan/amiberry/commit/673948f54853d34d4f46c90a4853f65e2d0b1579
