### ISSUE TITLE
amiberry 4.2.0 - Exit Bug

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#906]
Raspberry Pi 4, Manjaro Linux, AmigaOS 3.2.1 running WHDLoad Games.

Hello Dimitris,
i have these Problems after compiling amiberry v4.2.0 (2022-02-22) version from 27.02.2022.

Amiberry version 4.2.0 can be started without any problems and ended normally with F11.

But if I go to the menu after the start, select "Restart" there, it is restarted and I find myself in the menu. If I now choose "Quit", it restarts again and loads the default.ini. With me I get back to AmigaOS3.2.1 workbench. If I now go to the menu with F12 and choose "Quit" again, the menu just closes and I'm back on AmigaOS3.2.1 workbench (without a restart). The same happens when I click on "shutdown" or "restart" in the menu again. I keep getting back to the AmigaOS3.2.1 workbench. Amiberry can no longer be terminated. 

P.S: I was able to fix the previous mouse problem by disabling the virtual mouse driver.

**Comment by cwsoft** [comment]
Realized the same issue also on a PiOS Desktop 32-bit version.
