### ISSUE TITLE
Include uae_pragmas.h in the amiberry releases

### ISSUE THREAD

**Issue by stefs12** [midwan/amiberry#914]
I was watching Chris Edwards' pimiga video and stumbled upon the too UAEcontrol that hes using to shut down and enable JIT at runtime. I have looked into the amiberry source and poked around GitHub. 

It's a quite fascinating read to use illegal opcodes of the 68k CPU to communicate to the emulation. Looking at the host-run and the uae-control repo I stumbled upon the uae_pragmas.h which seem to define how to call the available opcodes. uae-control and host-run seem to include different versions, as host-run defines a few more opcodes to use. 

I think it would be a treat to include this header with the amiberry release to exactly define what the possible a specific amiberry release understands and is willing to answer to if "native_code" is set to yes. So any tool that is trying to communicate to the emulation can be compiled to the abilities of the running amiberry release.

I like to extend the host-run utility to include runtime configuration changes to the emulation in an effort to automate the emulator settings based on the applications needs. This might be more suited to the uae-control repo, but only in host-run I see the EmuConfig and EmuconfigModify traps defined. 

That's why I'm asking to include that header in the amiberry release.

**Comment by midwan** [comment]
@stefs12 
There already is such a tool, including with WinUAE releases: It's called uae-config if I remember correctly, and allows you to see and modify emulation options on the fly (all from the command line, so it can easily be used in scripts).
Regardless, I can still add the header file of course. :)

**Comment by midwan** [comment]
Yes, the older parts will remain the same - I'm only expanding the functionality if I can help it.
