### ISSUE TITLE
amiberry version 5.0 (2022-03-19) crashes

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#916]
Raspberry Pi 4 with Manjaro Linux. Running amiberry 5.0 with AmigaOS 3.2.1 and WHDLoad Programs.

As described above, amiberry 5.0 has been running successfully on my RPi 4 under Manjaro.... till today.

After I compiled and started the version amiberry 5.0 (2022-03-19) today, amiberry crashed immediately after starting. I deleted my defrault.uae and got into the amiberry menu. There I created a new default.uae. However, it then crashed again. Why?!? It ran before but just the same under amiberry 5.0.  I use the same hdd file as before, so i don´t understand that error.

Cheers
Retro1968

PS.: I just found out that amiberry 5.0 (2022-03-19) crashes even if I don't insert an HDD at all and the normal kickstart screen should come up. I compiled with "make -j4 PLATFORM=rpi4-64-sdl2".

**Comment by midwan** [comment]
Did you have Auto-Height enabled? I think there's a bug there that I'll be fixing shortly.

**Comment by Retro1968** [comment]
yes i do have auto-height enabled.
