### ISSUE TITLE
Controller D-Pad is not active unless GUI is opened once

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#917]
Raspberry Pi 4 with Manjaro Linux. Running AmigaOS 3.2.1

I changed the joystick settings in the amiberry version 5.0 (2022-03-20) menu under "custom controls" and saved them in my default.uae.

After a restart, however, the old values are restored. I've tried that three times now. Obviously the joystick settings are not saved.

Cheers
Retro1968

**Comment by midwan** [comment]
Can't say I can recreate this. I added a setting in Custom Controls on an unmapped button, saved the config as `default` and then closed down Amiberry.
When I start it up again, the config is loaded and I can see my setting in Custom Controls, as expected.

You'll have to be more specific in what you did.

**Comment by Retro1968** [comment]
On the first picture you can see that my joystick is recognized as "PS3 Controller".
![01](https://user-images.githubusercontent.com/58906142/159242694-24f42969-a69d-412b-8989-603e3779319e.jpg)


On the second picture you can see the standard settings under "Custom controls".
![02](https://user-images.githubusercontent.com/58906142/159242718-94203f9a-a29a-45e9-8f7d-efb61c96899f.jpg)


I now change the standard settings as follows and then save them in the file default.uae
![03](https://user-images.githubusercontent.com/58906142/159242733-53cc7b30-15e7-4056-9b3b-40a03cb51259.jpg)


Now that I've closed and restarted amiberry 5.0 (2022-03-20), you can see the result here. The standard settings under "Custom controls" are displayed again. 
![04](https://user-images.githubusercontent.com/58906142/159242767-212e22e8-33bd-474b-8e19-7985c94f2b48.jpg)

**Comment by midwan** [comment]
But your modified settings did get saved, as you can see in the South/East/West/North dropdowns.
You set the rest to None, which basically means "no custom mapping", but as the default controller mapping is always loaded first, you see those default assignments show up again. 

Custom Controls is meant for customizing the default mapping. If no customization is applied, then the default mapping is still used. The logic is like this:
- Load default map for controller
- Check if any custom controls are set, and modify mapping accordingly. Otherwise leave it alone.

**Comment by Retro1968** [comment]
So now I've tested it again. I was surprised that the first four settings on the first third screenshot were indeed saved corecctly. That was a config in which I had not set much, almost you the joystick settings. I then configured everything and while playing Zool AGA I was surprised that ingame the controls no longer responded and the above standard values (second screenshot) were also set for the first four values (up, down, left, right.) After that I had changed these first four settings again several times into the values as above... saved... and then exited amiberry and started again. Everything (including the first four values) was set to standard again under Custom controls  (second screenshot). Saving no longer works. I'll send you my default.uae 

[default.zip](https://github.com/midwan/amiberry/files/8323475/default.zip)

I wonder that in the defaut.uae this entries are correct:

joyport1_amiberry_custom_none_a=Joy2 Down
joyport1_amiberry_custom_none_b=Joy2 Right
joyport1_amiberry_custom_none_x=Joy2 Left
joyport1_amiberry_custom_none_y=Joy2 Up


but i still see the settings from screenshot 2 under custom controls and the controls still don't work in games.

**Comment by midwan** [comment]
I'm a bit confused as to what you're trying to do here...
The mapping you're trying to set seems incorrect, as you're configuring the A/B/Y/X buttons to directional ones (Up/Down/Left/Right), and trying to set everything else to None. Even so, changing the mapping of the A/B/Y/X buttons still works, at least in my tests here. It's only setting the default ones to None, that doesn't work (reverts back to the default value if you try that).

Could you please explain what the reasoning behind this is? Perhaps I'm missing something, but it seems to me that you'd always want the default mapping OR you could re-assign buttons of course, but I don't see a reason you'd want to remove a mapping from the defaults and set it to None?

**Comment by Retro1968** [comment]
This is my "Lioncast Arcade Fighting Stick" where I swapped out the cheap microswitches in the joystick with Cherry D44X microswitches, swapped out the cheap buttons with SANWA OBSF-30 Snap In Acrade Buttons and rewired.

![Joystick](https://user-images.githubusercontent.com/58906142/159694313-0c88cf94-bbe4-44a5-82d0-ac496af51931.jpg)

The part is really good now!

To answer your question, it is recognized as a PS3 joystick, but of course it isn't one.
So far, my joystick has always worked fine when configured as described above.

I give you my default.uae here, which also ran well in amiberry 5.0... at least up to the version (2022-03-20). 
[default.zip](https://github.com/midwan/amiberry/files/8332768/default.zip)

**Comment by Retro1968** [comment]
I think I've found the solution for me.... but there is still an error!

First I created a new default.uae in which I configured everything I needed. Finally, I made the joystick settings.

This time under Port 0: System Mouse I changed the "Default" option to "Wheel Mouse" and Port 1: PS3 Controller the "Default" option to "Joystick".
![1](https://user-images.githubusercontent.com/58906142/159702691-66bd46c2-db8c-47bf-8a33-5f9628957003.jpg)

After that, the Custom Controls were set up automatically.
![2](https://user-images.githubusercontent.com/58906142/159702728-73abc612-b236-4aba-af3f-a2ddf006304e.jpg)

I didn't change anything and was able to use my joystick in the game without any problems.

But that is not always the case. Sometimes I can't control the game with my joystick. Then I have to go to the menu with F12 and immediately return to the game with "Resume". Then the control works again. Isn't that strange?!?... because I'm only in the menu and immediately out again without changing anything in the settings.

**Comment by midwan** [comment]
Do you need a `default.uae` for other things as well? What happens if you rename it?
The default joystick mapping always applies, and by default if you have a controller connected it will be assigned to Port 1, so it's designed to work right away, without loading a special config.

Unless of course you want to modify the mapping, but let's take it one step at a time...

Step 1: How's the behavior for you without a `default.uae`
Step 2: How about saving your config under a different name, and loading that on-demand (or even from the command prompt). Does that make a difference?

**Comment by Retro1968** [comment]
I don't know if you understood the current problem. I now used the default settings, which work.

Now there is the problem that I have to go into the menu every time in order to leave it again immediately (without changing the settings),
for the controls to work in the game. It's a bug, isn't it?

**Comment by midwan** [comment]
I don't think so, considering I cannot recreate that behavior here :)
The default settings should work "out-of-the-box" for a controller like the PS3 (or similar), without the need for a `default.uae` to set them.

How are you launching the emulator exactly, when this problem happens?
Are you using a config file which has the GUI disabled, or running it from the command line with `-G`, or something else?

**Comment by midwan** [comment]
Hold on, I just found something - the analog stick works, but the D-Pad doesn't, until you enter the GUI once, as you described.

That is certainly a bug.

**Comment by Retro1968** [comment]
> Hold on, I just found something - the analog stick works, but the D-Pad doesn't, until you enter the GUI once, as you described.
> 
> That is certainly a bug.

Well done mate! ;-)
