### ISSUE TITLE
Apidya (Kaiko) crashes amiberry 5.0 (2022-03-23) if Auto-Crop is enabled

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#919]
Raspberry Pi 4 running Manjaro Linux and amiberry (2022-03-23) with Amiga OS 3.2.1.

If I start Apidya (Kaiko) via WHDLoad via the AmigaOS 3.2.1 Workbench with amiberry 4.1.6 or 4.2.0, everything runs without errors.

But if I start Apidya (Kaiko) with amiberry 5.0 (2022-03-23) i get a black screen. Then I can neither exit amiberry with F11 nor call up the menu with F12. I can no longer reach the Raspberry Pi 4 with putty. How can that be?

So far I haven't found the error in any other game.

Cheers
Retro1968

**Comment by midwan** [comment]
It works normally on two different configurations I tested it:
- Pimiga2 from Workbench / iGame
- Standalone using the WHDBooter and .lha file

So I don't think this is an issue with the game specifically. Sounds more like something to do with your configuration perhaps?

**Comment by midwan** [comment]
Please specify which Amiberry platform you are using (32/64 bit, DMX or SDL2), and also your config file used to recreate the issue.

**Comment by midwan** [comment]
Also check if you had Auto-Crop enabled, and try disabling it.

**Comment by Retro1968** [comment]
Yes, "Auto Crop" causes the crash. However, I need "Auto Crop" to achieve the full screen you know on my 4:3 monitor. 
 
[default.zip](https://github.com/midwan/amiberry/files/8338722/default.zip)

**Comment by stefs12** [comment]
I can add one. Demo: Voyage from Razor 1911 crashes with Auto-Crop too. Even the version from today.

**Comment by midwan** [comment]
Fixed with 33250cb2d6f717c496b841598de7a00e9b017940

**Comment by midwan** [comment]
Note: Dispmanx still uses the old approach for now, the changes are for SDL2 only versions.
