### ISSUE TITLE
Autocrop wrong pitch?

### ISSUE THREAD

**Issue by stefs12** [midwan/amiberry#920]
I am using the latest Amiberry release on PI400 Arch aarch64 build with dmx backend and linux-rpi kernel.

Wen I activate the Autocrop feature. The demos and games I start ( I havent tested much) seem to run into the problem that the autocrop is using a wrong pitch for the blit? 

![viber_image_2022-03-23_20-54-11-054](https://user-images.githubusercontent.com/92685636/159784922-7ca7d134-aa42-422c-b61a-e32b4b060198.jpg)

Notable also is, that some screens in those games / demos seem to work fine, and are also perfectly cropped. 

The only thing that is maybe a hint, is, that I use a 21:9 Monitor with a framebuffer reported as 2560x1080 in (/sys/class/graphics/fb0/modes). That maybe throws the calculation off? I haven't yet looked into the code. 

Using a fixed mode (does not matter which one from 720x400 to 720x568)  does not have a problem at all.

But honestly: autocrop is too cool not to have :)

**Comment by midwan** [comment]
Can you give me some more specific cases this happened in?
And the config you used to recreate this, if possible?

**Comment by stefs12** [comment]
Demo case Im using is FridayAtEightAGA for Whdload. I have taken the liberty to add some messages to _void auto_crop_image()_

I will attach the outputs, as well as the uae config. 

[viewport_changes.txt](https://github.com/midwan/amiberry/files/8339597/viewport_changes.txt)

[default.uae.txt](https://github.com/midwan/amiberry/files/8339610/default.uae.txt)

**Comment by midwan** [comment]
Thanks, I'll test it out and see.
I noticed AutoCrop triggers a crash in SDL2's FreeSurface when running Apidya also, which is weird considering it doesn't do that elsewhere (so far?). So it seems that something is a bit wrong there.

Meanwhile, you could try using it as a mapped event to a controller if you want (in Custom Controls), where it will only perform the cropping on-demand (whenever you press the assigned button). Perhaps that will work better for now.

**Comment by midwan** [comment]
Can you check with the latest version from today, please? It seems to work better now. :)

**Comment by stefs12** [comment]
Yes that did it for me. Visually its working fine now :)

Sometimes it seems the calculation is done repeatedly a couple of times before it settles though.
