### ISSUE TITLE
Auto Crop problem with Amiberry version (2022-03-26)

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#922]
Raspberry Pi 4 running Manjaro Linux and amiberry (2022-03-26) with Amiga OS 3.2.1.
I compile with: make -j4 PLATFORM=rpi4-64-sdl2

Hello Dimitris,
thanks for the new amiberry version (2022-03-26) in which you fixed the system crash problem with "Auto Crop".
There is now another problem with "Auto Crop".

Here you can see my workbench with activated "Auto Crop".
![AutoCrop ON](https://user-images.githubusercontent.com/58906142/160246427-89fa7c11-743f-4d9f-a7f1-cf384597cf23.jpg)

Here with deactivated "Auto Crop".
![AutoCrop OFF](https://user-images.githubusercontent.com/58906142/160246434-725a76e0-225b-4e6f-a943-b29e86e9d7ea.jpg)

The "Auto-Crop" function is not really usable in the present version. ;-)

I am sending you my default.uae.
[default.zip](https://github.com/midwan/amiberry/files/8355765/default.zip)

Cheers
Retro1968

**Comment by midwan** [comment]
That's a P96 screen, isn't it? I think I missed one line, to revert the crop Rect when P96 screens open...

**Comment by Retro1968** [comment]
> That's a P96 screen, isn't it? I think I missed one line, to revert the crop Rect when P96 screens open...

Yes, i use the Picasso Driver Version 3.2.4.
