### ISSUE TITLE
Apidya Auto Crop problem with Amiberry version (2022-03-26)

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#923]
Raspberry Pi 4 running Manjaro Linux and amiberry (2022-03-26) with Amiga OS 3.2.1.
I compile with: make -j4 PLATFORM=rpi4-64-sdl2

Hello Dimitrios,
the version amiberry (2022-03-26) no longer causes amiberry or manjaro linux to crash, but there is still an error.
If I start Apidya from Workbench 3.2.1 as WHDLoad with activated Auto Crop, I get this image output.
![Apidya1](https://user-images.githubusercontent.com/58906142/160253438-43d615e9-1a32-404e-b2ec-ea5cb0d5c0f6.jpg)
![Apidya2](https://user-images.githubusercontent.com/58906142/160253446-b6d1e6bb-ab53-4041-8c49-5bc9eeb5d921.jpg)

If I now go into the GUI and deactivate Auto Crop and exit the GUI, then go straight back into the GUI and activate Auto Crop, Auto Crop works normally with Apidya.
![Apidya3](https://user-images.githubusercontent.com/58906142/160253454-96ce7288-733e-45b7-8b2c-59f2b46011d4.jpg)
![Apidya4](https://user-images.githubusercontent.com/58906142/160253456-7ec0f722-7c16-4442-8a9d-bb9f9afaf3d7.jpg)

I can now exit  with F10 and restart Apidya and everything runs normally. Only when I exit amiberry and start again does it all start over again.

Cheers
Retro1968

**Comment by midwan** [comment]
Looks like I missed one more scenario then: native -> P96 -> native, probably needs to force trigger auto-crop once (which is what you did manually by going to the GUI).

**Comment by midwan** [comment]
Hm, no - I can't recreate this. Did you get the latest sources from today? I included some fixes for aspect ratio as well.

**Comment by Retro1968** [comment]
On the fourth screenshot you can see that Auto Crop shifts the screen up a little bit so that there is a black bar at the bottom and a piece of the image is missing at the top. Maybe you can fix that too.  ;-)

**Comment by Retro1968** [comment]
> Hm, no - I can't recreate this. Did you get the latest sources from today? I included some fixes for aspect ratio as well.

Yes the latest source.

**Comment by midwan** [comment]
I can't recreate any of the above here, if I launch it from an RTG 1080p workbench:

![Amiberry - Amiberry_2022-03-26_20-18-28](https://user-images.githubusercontent.com/3877365/160254020-f62fe96c-d2db-4392-b602-14844f041f4d.png)
h

**Comment by Retro1968** [comment]
I use 800x600 on my 4:3 monitor.

**Comment by midwan** [comment]
The resolution shouldn't (and doesn't, I tested it) matter. It might be something else in your config or environment, but I still can't recreate it here... Are you running this under an X11 desktop, or using KMSDRM from the console? If I remember correctly, you said you're using the SDL2 version (no Dispmanx).

**Comment by Retro1968** [comment]
I use the manjaro XFCE version.

**Comment by midwan** [comment]
That's the same I used for testing this, so it's not that either. I think that leaves us with the specific .uae config you used, and perhaps the specific AmigaOS environment you used also. Must be something in there that behaves differently than my case.

**Comment by Retro1968** [comment]
Meine default.uae datei hast du bereits.

**Comment by midwan** [comment]
Your `default.uae` had some values that you could test changing:
- Width/Height: you had that at 320x400, try setting it to 720x568 instead
- Try disabling Auto Centering, both H and V. They are not needed with the new Auto Crop option.
- Try experimenting with different Screen mode options: Windowed, Full-window, Fullscreen. See if those make any difference.

Generally I'd say try some different display-related options, until you see a difference. I would guess it's something there.

**Comment by midwan** [comment]
Might be worth checking the options in `amiberry.conf` also, just in case the above doesn't help.

**Comment by Retro1968** [comment]
Hello Dimitris,
I've tested around a bit now.

After recompiling amiberry and creating a new default.uae, I was able to start Apidya without errors. Well it's still up a little bit but otherwise playable.
![01](https://user-images.githubusercontent.com/58906142/160281747-f64f1843-5b82-48d1-9c42-0b94520b35ab.jpg)
![02a](https://user-images.githubusercontent.com/58906142/160281756-94e0c226-f3a7-4f4c-b88b-cafb5739abb7.jpg)


However, in other games I tested, there were stronger image shifts with "Auto Crop" enabled, which I didn't have in the previous amiberry 5.0 version. Since the amiberry version (2022-03-26) there are these new problems.
![02](https://user-images.githubusercontent.com/58906142/160281767-c3eb982c-ba25-4f3e-bf49-78def0950dfb.jpg)
![03](https://user-images.githubusercontent.com/58906142/160281773-4c7496d0-753e-4983-9ff0-67ed8075da38.jpg)
![04](https://user-images.githubusercontent.com/58906142/160281852-fd788b68-7ffc-4949-a65d-38a58d1f41ae.jpg)


I'm not exactly sure what the advantage of "Auto Crop" over "Auto Height" from version 4.1.6 is anyway. is? Do you want to explain?

Under amiberry 4.1.6 everything went perfectly for me!
![09](https://user-images.githubusercontent.com/58906142/160281872-25457b23-3faf-4ada-b564-55e896bbe869.jpg)
![10](https://user-images.githubusercontent.com/58906142/160281875-ad86ce02-512a-42b7-b8c4-3868a7f81459.jpg)
![11](https://user-images.githubusercontent.com/58906142/160281878-dda72dda-cdd1-4e9a-b78e-d60c0f1594ab.jpg)


Would it be possible to offer "Auto Height" as an option again? Either in addition to "Auto Crop" so that you can decide which option you want, or instead of "Auto Crop"? 

I send you my complete conf folder of amiberry 5.0 (2022-03-26): 
[conf.zip](https://github.com/midwan/amiberry/files/8357611/conf.zip)

Cheers Retro1968

**Comment by midwan** [comment]
Can you try the following please:
- Disable Centering
- Change Width/Height to the max values (actually when you enable Auto-crop those sliders should be disabled
- Change mode to Full-window instead of Full screen

**Comment by Retro1968** [comment]
> Can you try the following please:
> 
>     * Disable Centering
> 
>     * Change Width/Height to the max values (actually when you enable Auto-crop those sliders should be disabled
> 
>     * Change mode to Full-window instead of Full screen

Damit läuft es perfekt! :-)
![01](https://user-images.githubusercontent.com/58906142/160287569-01ed5e83-cfa7-4d5f-91fc-188dbf109755.jpg)

![02](https://user-images.githubusercontent.com/58906142/160287580-e924feb7-92d1-402b-9f17-496e23bb206a.jpg)

![03](https://user-images.githubusercontent.com/58906142/160287584-4baad791-c667-4c64-a248-282235e1364e.jpg)

![04](https://user-images.githubusercontent.com/58906142/160287592-862afebd-c3dd-49cf-a03e-2484af1b39a1.jpg)

Do amiberry have a fullscreen problem?

**Comment by midwan** [comment]
I think it's the width/height in combination with Centering that causes the issue, not the full-screen option. You can try changing only that to make sure.

If this is proven indeed to be the cause, I'll adapt the code to automatically update those values if Auto-Crop is found to be enabled, and disable the options in the GUI accordingly, to hopefully make this work smoothly even when loading configs with those options... :)

**Comment by midwan** [comment]
The commit above _should_ fix the issue for existing configs loaded, and also block you from changing values that would cause problems in the GUI. Hopefully this caught all scenarios, but if you find something else I missed, feel free to comment here and we'll re-open the issue. :) 

Thanks for testing!
