### ISSUE TITLE
"Auto Crop" problem running amiberry 5.0 (2022-03-31) on RetroPi.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#929]
Raspberry Pi4B running RetroPie 4.7.11 with amiberry 5.0 (2022-03-31) with AmigaOS 3.2.1 and WHDLoad Games.

After downloading the latest amiberry source code, copying it to my "/home/pi/RetroPie" folder, unzipping it there with "unzip amiberry-master.zip", then "cd amiberry-master" and compiled the source code with "make -j4 PLATFORM=rpi4" and then changed the file rights with "chmod 755 amiberry" and then installed amiberry according to these instructions, amiberry 5.0 ran successfully for me.
https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version.

Although I'm using the same settings here as on RaspiOS 64 bit , I get this choppy image output instead of a full image like in this post: https://github.com/midwan/amiberry/issues/923. 

![AC1](https://user-images.githubusercontent.com/58906142/161428975-43e9c499-ecb2-4dd7-a096-e9d299b06a94.jpg)
![AC2](https://user-images.githubusercontent.com/58906142/161428978-c0e978e1-477e-4a22-89c0-b12b8b4da38a.jpg)
![AC3](https://user-images.githubusercontent.com/58906142/161428980-0201e59a-5838-4e5d-86ea-bc0ad855a78b.jpg)

If I change the settings like here, I get a usable image output. 
![AC6](https://user-images.githubusercontent.com/58906142/161429471-8f2a8b72-93d8-4eb7-a1a2-ed208f3efa31.jpg)
![AC7](https://user-images.githubusercontent.com/58906142/161429472-676ac1ab-1445-41ee-a0c9-ff8a5bee2b82.jpg)

But how do I get the same full screen output on RetroPie as in this image on RaspiOS 64 bit? Look here: https://github.com/midwan/amiberry/issues/923
![AC8](https://user-images.githubusercontent.com/58906142/161429622-05239096-0fd2-40aa-bad4-cb89a902b969.jpg)

Cheers
Retro1968

**Comment by midwan** [comment]
That's because auto crop is not implemented for Dispmanx, so it still uses the previous approach. It may come in a future update, but so far I couldn't make it work reliably under Dispmanx.

**Comment by Retro1968** [comment]
But the previous approach had "Auto-Height". So would it be better to use RetroPie with amiberry version 4.1.6 until you solve the problem?

**Comment by midwan** [comment]
There are many more improvements besides auto crop, so I'd still recommend v5 anyway.

**Comment by Retro1968** [comment]
I didn't mean that in a bad way. With version 5.0, the "Nexus 7 AGA" demo finally runs without errors and without jerks. Very well! But without my beloved full screen, it's really stupid for me... I like it so much. ;-) 

Will Auto Crop ever run on RetroPie?

**Comment by midwan** [comment]
Possibly in a future update, if I can get it to work the same way it does under sdl2.

**Comment by Retro1968** [comment]
Today (2022-04-10) I installed the new version (DMX: Auto-Height fixes) manually in RetroPie.

It's nice that you've reintroduced "Auto-Heigt". However, it still doesn't run without errors.

I used my version 4.1.6 settings in version 5.0 for auto-height:

Centering on for horizontal and vertical
Width: 640, Height: 400 and "Auto Height" on.
Line Mode: Double

Otherwise I have not activated anything else under Display.

Test with Lotus Esprit Turbo Challenge:
The height is set correctly and then incorrectly again.
So sometimes I have a full image (see above) and sometimes the image below is cut off.
Since this was not the case under 4.1.6 I think this is a bug.

Cheers
Retro1968

**Comment by midwan** [comment]
@Retro1968 please test with the latest commits, and see if these changes make things better for you?

**Comment by Retro1968** [comment]
Yes, the problem is fixed in three tested games! Thanks buddy.

There was still a problem in Leading LAP AGA. Is this the same as in Banshee?

**Comment by midwan** [comment]
Should be fixed "for good" now. :)

**Comment by Retro1968** [comment]
Addendum: 

After I updated RetroPie's operating system with these commands:

sudo apt update && sudo apt upgrade -y && sudo apt full-upgrade -y && sudo apt autoremove && sudo apt autoclean

sudo reboot

and after i then updated my existing RetroPie 4.7.11 version to version 4.8, now apparently sdl2 is available.

I was able to compile amiberry with this command,

make -j4 PLATFORM=rpi4-sdl2

and upgrade manually according to these instructions:
https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version

So now I also have "Auto-Crop" available under RetroPie, which also works very well and gives me a full screen.

Cheers
Retro1968

**Comment by midwan** [comment]
Oh, that's great news - I wasn't aware they updated SDL2 as well, which they must have, in order to use it from the console.
