### ISSUE TITLE
SDL2 - Menu button - Map to open GUI

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#93]
Hello. In latest build from binnary with new corrects i found bug:

- when pressed button from XBOX 360 PAD to assign map to Open the GUI  then each key causing exit from Amiberry.

**Comment by midwan** [comment]
@pawelomega 
The code for mapping controller buttons is not 100% working yet, it will be fixed over the next few days hopefully.

**Comment by midwan** [comment]
I believe this is now resolved with the addition of the Retroarch-style mapping
