### ISSUE TITLE
[WHDLoad] Zool_v2.0_CD32 - Needs more Fast RAM

### ISSUE THREAD

**Issue by APGRoboCop** [midwan/amiberry#931]
This .lha for whdload_db.xml appears to require more Fast RAM as my Amiberry for my Pi 4B automatically uses 4MB of Fast RAM, but works better if this XML had 8MB Fast RAM. I take it needs to add like "FAST_RAM=8" inside <hardware> for whdload_db.xml?

Those are the settings and error pics I got from loading Zool_v2.0_CD32.lha from Amiberry using the default.uae settings:-
![IMG_20220404_192059](https://user-images.githubusercontent.com/3459575/161607933-26d29752-a5b5-4b96-8e28-38cd3ef72a99.png)
![IMG_20220404_192129](https://user-images.githubusercontent.com/3459575/161607940-93558e96-4cea-4fec-a818-837c339016be.png)

**Comment by midwan** [comment]
This is already updated in Amiberry v5.0, which uses 8MB Fast for all titles by default.
It looks like you're running an older version there.

**Comment by APGRoboCop** [comment]
Hmm I just updated AmiBerry, 3-5 days ago... Maybe RetroPie Update script missed that update.

**Comment by celeritydesign** [comment]
> Hmm I just updated AmiBerry and the other packages, 3-5 days ago... Maybe RetroPie Update script missed that update.
> 
> P.S. My AmiBerry for my Pi 4B is using v3.3 (2020-09-17)

Retropie’s update script won’t give you Amiberry 5 yet unfortunately, it has been stuck at 3.3 for about a year. Have you read the Amiberry update instructions here? : https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version

**Comment by nemo93** [comment]
Update to 5.x is coming to Retropie. Check that [PR](https://github.com/RetroPie/RetroPie-Setup/pull/3508). It should take a bit more time to smoothen the edge but it's there for good ;-)

**Comment by celeritydesign** [comment]
> Update to 5.x is coming to Retropie. Check that [PR](https://github.com/RetroPie/RetroPie-Setup/pull/3508). It should take a bit more time to smoothen the edge but it's there for good ;-)

Such good news, thanks!
