### ISSUE TITLE
autocrop with whdload aladdin 

### ISSUE THREAD

**Issue by Mozzerfan** [midwan/amiberry#933]
Hi,
When using autocrop, centering in whdload aladdin doesn't work right. The screen is not centered.
I'm using the dev version of amiberry. When I turn off autocrop, and select horizontal and vertical centering, all is ok.

**Comment by midwan** [comment]
Which SDL2 version, which distro, which back-end? Dispmanx or SDL2?

**Comment by Mozzerfan** [comment]
Sorry. I'm using manjaro 64-bit sdl2 version.

**Comment by midwan** [comment]
Yes, I can recreate this.
Some games or demos are unfortunately special cases, and don't output the expected result. For now, you can just skip Auto-Crop for those titles and use the "normal" approach of setting width/height and centering, as needed.

**Comment by Mozzerfan** [comment]
OK. Thank you.
