### ISSUE TITLE
To have a `disable_restart_button` as global option

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#938]
I wonder if it would be possible to have a (boolean) option `disable_restart_button` in global `amiberry.conf` the same way there's a `disable_shutdown_button`. This should prevent any unexpected reboot of the device Amiberry is running on if you haven't paid enough attention :-)

To be as clear as possible let's follow your wiki example:

### `disable_restart_button`

This setting controls if the Restart button in the GUI should be disabled or not.

**Possible values**: `yes/no`
**Default value**: `no`
**Example**: `disable_restart_button=yes`

**Comment by midwan** [comment]
Hm, I'm not sure how useful this would be - Restart is a button that people want to use a lot of the time, whereas the Shutdown is understandably kind of a unique case (hence the config option to disable it if needed).

It _could_ be added as a config option of course, it's just that I don't see much use in it from my point of view... :)

**Comment by nemo93** [comment]
If people use that a lot then I withdraw this ask :-) Closing this off.
