### ISSUE TITLE
Binary of Amiberry 5.0 for Mac M1 seems broken

### ISSUE THREAD

**Issue by Yserra** [midwan/amiberry#939]
**Describe the bug**
The Amiberry app found in this archive https://github.com/midwan/amiberry/releases/download/v5.0/amiberry-v5.0-macOS-m1.zip doesn't run on a MacBook pro M1 Max with macOS 12.3.1. When I try to run it, MacOS says this app is broken and should go to the trashcan. 
I also tried the macOS x86 version and, this one, works as expected (in x86 emulated mode, I presume)

**To Reproduce**

1. From a Mac M1 computer, download https://github.com/midwan/amiberry/releases/download/v5.0/amiberry-v5.0-macOS-m1.zip

2. unzip it (with macOS's Archive tool)

3. double-click on the new Amiberry icon

**Expected behavior**
The Amiberry app should run without macOS saying its binary is broken.

**Screenshots**
How do I upload a screenshot? 

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : macOS 12.3.1

- machine : MacBook Pro M1 Max, 14 inch.

**Comment by solskogen** [comment]
The binary is not broken, but Apple OS does for some strange reason not allow non-signed apps to be run if you download it with a browser. There are two workarounds: Download the zip file with wget or run "xattr -rd com.apple.quarantine Amiberry.app"

**Comment by midwan** [comment]
As @solskogen mentioned above, this is probably related to the bundle not being signed by an Apple Developer account.
There are a few more small glitches with the macOS binaries, all seem to be related to Apple restrictions (like access to the Documents folder, for example). I'm hoping we'll sort those out in the future as well, to make the experience better.

**Comment by Yserra** [comment]
Many thanks. the wget command actually solved the launch problem. But, yes, bugs remain. Mainly, I can't browse the home folder and my Greaseweazle board is not recognized.
