### ISSUE TITLE
SDL2- JIT

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#94]
When JIT is enabled then cause laggy in sound playback in ex. protracker. When dissable JIT then sound playback is without laggs.

**Comment by Fourdee** [comment]
I found sound is choppy initially in some games, then clears itself.

@pawelomega 

> When JIT is enabled then cause laggy in sound playback in ex. protracker

Is this also the case with audio emulation + most accurate option?

**Comment by pawelomega** [comment]
it doesn't matter. That persist in both option. Only JIT when is dissabled solve problem

**Comment by starcube75** [comment]
Same problem here and without JIT emulation is really slow by my side.
When i change the resolution with PAL: Super-High Res there are any problem with laggy sound playback.

**Comment by midwan** [comment]
Don't use JIT for games for now, as it doesn't seem to offer any advantages for those.
It's useful for Workbench applications mostly.

This area is being worked upon, but it's rather complex and big, so it takes time. :)
