### ISSUE TITLE
Strange mouse behavior in amiberry GUI.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#940]
Raspberry Pi 4B running RetroPie 4.8 with amiberry 5.0 (2022-04-12) (sdl2) with AmigaOS 3.2.1 and WHDLoad-Games.

Hello Dimitris,
as i reported in this thread at my last post (https://github.com/midwan/amiberry/issues/929) i installed today the SDL2 version of amiberry on RetroPie 4.8 by compiling with: make -j4 PLATFORM=rpi4-sdl2

But i had the following problem on RetroPie 4.8; with the DMX version too, which i had installed before.

While the mouse and joystick work flawlessly on the workbench and in games, it's completely different with the mouse in the amiberry GUI. You can move the mouse and click on the things you want. But it's almost like ice skating when you move in one direction and then slide on without moving. The mouse also keeps gliding. It's difficult to select the things you want with it.

Cheers
Retro1968

**Comment by Drag0nFly** [comment]
FWIW; I had similar issues with the mouse behaviour in the Amiberry GUI until I added the `usbhid.mousepoll=0` kernel option to /boot/cmdline.txt

Obviously, your issue might be different, but perhaps worth a try. ;)

**Comment by Retro1968** [comment]
Thanks for the hint. As a result, the mouse pointer is now moved muuuuch more slowly. This helps to click objects better, but is probably not the final solution. ;-)

**Comment by Drag0nFly** [comment]
That is curious, as it had the direct opposite effect for me. (Then again, the problem was originally that the mouse moved extremely slowly in the GUI but worked fine elsewhere before the option was added.)

The mouse I use also has a DPI setting which would probably impact the behaviour somewhat.

**Comment by Retro1968** [comment]
My mouse does not have such a DPI switch. Nevertheless, thanks for your help. :-)

**Comment by ninjaweb62** [comment]
Hi, I experienced the "ice skating" effect just yesterday, when I updated the RPi4 firmware (rpi-update) to the latest version. I restored the old firmware and all went ok.

**Comment by Retro1968** [comment]
Yes i updated the firmware too. Please let me know the commanline with which you restored the old firmware.

**Comment by Retro1968** [comment]
After I downgraded the firmware from version 5.15.33+ to version 5.15.18+ using this command, the issue was resolved. :-)

sudo rpi-update 9c6362635308cb3034d22f42daf9bfda1e3d36de

**Comment by solskogen** [comment]
The ice skating mouse only happens with fkms. If you switch to kms (which is default in Raspberry Pi OS) you should be good to go.

**Comment by Retro1968** [comment]
As far as i know the Raspberry Pi 4 only supports fmks.

**Comment by solskogen** [comment]
No, it also support KMS.

ons. 13. apr. 2022, 23:25 skrev Retro1968 ***@***.***>:
