### ISSUE TITLE
[D-PAD] not working in-game

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#942]
**Describe the bug**
I'm using a Xbox One bluetooth controller with a retroarch config. The gamepad is working absolutely fine yet I can't use D-PAD while in-game. Only left stick is working there. What's weird though is that D-PAD is properly working in GUI and if I click on the `remap` button.

Opening and closing GUI once as described in #917 doesn't fix it.

**To Reproduce**

1. Get a Xbox One bluetooth controller!
2. Follow [this guide](https://github.com/midwan/amiberry/wiki/Setting-up-Input-Controllers#creating-a-controller-map).
3. Launch any game
4. Open the GUI. You should be able to navigate it with either D-PAD or left stick.
5. Close the GUI, back to the game. You can't use D-PAD. Only left analog stick does work.

**Expected behavior**
To be able to use D-PAD (and left stick) while in-game. Alternatively to be able to let users to chose between D-PAD and analog stick to be used as cursors.

**Additional context**
Test platform: pi4 on current Retropie (4.8). Which means 32-bit Buster and fake KMS (dispmanx backend).

RetroArch controller mapping has been recognised >> `[R]` on the Custom Control panel. Here's the content of my `Xbox Wireless Controller.cfg`. 
**Note**: I've tried removing the `input_player1_*_axis` section as well as using `-/+6` instead of `h0left` still no success (`jstest` shows D-PAD directions not as buttons # but as axis).

```
input_r_y_plus_axis = "+4"
input_r_y_minus_axis = "-4"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"

input_l_x_minus_axis = "-0"
input_l_x_plus_axis = "+0"
input_l_y_minus_axis = "-1"
input_l_y_plus_axis = "+1"

input_player1_left_axis = "-6"
input_player1_right_axis = "+6"
input_player1_up_axis = "-7"
input_player1_down_axis = "+7"

input_up_btn = h0up
input_down_btn = h0down
input_left_btn = h0left
input_right_btn = h0right

input_start_btn = "7"
input_select_btn = "6"

input_a_btn = "1"
input_b_btn = "0"
input_x_btn = "2"
input_y_btn = "3"
input_l_btn = "4"
input_r_btn = "5"

input_l2_axis = "+2"
input_r2_axis = "+5"
input_l3_btn = "9"
input_r3_btn = "10"

input_enable_hotkey_btn = "6"
input_exit_emulator_btn = "7"
input_menu_toggle_btn = "2"
input_reset_btn = "1"

input_state_slot_decrease_axis = "+2"
input_state_slot_increase_axis = "+5"
input_save_state_btn = "5"
input_load_state_btn = "4"
```

**Comment by Retro1968** [comment]
Maybe this thread could help you, where a problem with my Joystick was solved: https://github.com/midwan/amiberry/issues/928

**Comment by midwan** [comment]
I can recreate this with a PS4 controller here also - only when using RetroArch configs.
