### ISSUE TITLE
Sound disturbances with the DeliTracker V2.32

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#943]
Raspberry Pi 4B running RetroPie 4.8 with amiberry 5.0 (2022-04-13) (sdl2) with AmigaOS 3.2.1 (RTG).

Hello Dimitris,
as i reported in this thread at my last post (https://github.com/midwan/amiberry/issues/929) i installed the SDL2 version of amiberry on RetroPie 4.8 by compiling with: make -j4 PLATFORM=rpi4-sdl2.

While I don't have any sound problems in WHDLoad demos and WHDLoad games, MODS with the DeliTracker V2.32 are played either too slowly or with strong sound disturbances. If I play MODS with the Soundtracker Pro II, there are no errors.

I use these sound settings: [default.zip](https://github.com/midwan/amiberry/files/8489262/default.zip)

Sound Emulation: Enabled, most accurate.
Frequency: 48000 (also tried 44100 here to troubleshoot.)
Interpolation: Disabled (tried all other troubleshooting settings here too)
Filter: Always off (also tried all other troubleshooting settings here)
Sound Buffer Size: 6 (tried all other troubleshooting settings here too)
Pull Audio: Enabled (tried Push Audio)

Cheers
Retro1968

P.S: The Hippoplayer has the same problem.

**Comment by midwan** [comment]
Is that when running under a WB with RTG?
Can you check how many FPS you're getting, by enabling the Status bar (RTG or Native, depending on which one you're using)?

If you have less than the expected 50 (for PAL), it would explain problems with the audio.

**Comment by Retro1968** [comment]
I am using a Raspberry Pi 4B running RetroPie 4.8 with amiberry 5.0 (2022-04-13) (sdl2) with AmigaOS 3.2.1 (RTG).

This ist the RTG-Statusbar: 
![Status](https://user-images.githubusercontent.com/58906142/163549094-0a8f5453-c7f9-4759-b7db-c5ebb18e59bc.jpg)

**Comment by Retro1968** [comment]
I use a resolution of 1280x1024 on my 4:3 monitor.

If I choose smaller resolutions of 1024x768 or as usual 800x600, I no longer have any problems in the Delitracker. But what bothers me about that smaler resolutions is that I then have black bars at the top and bottom of the screen edge. It's been like this since Auto-Crop.

**Comment by Retro1968** [comment]
I have now switched to 640x512 and thus got rid of the black bars and solved the sound problem. However, I am surprised that some users even run amiberry in 1920x1080 and apparently have no sound problem.

**Comment by midwan** [comment]
If you were only doing 20 FPS, that explains the audio issues.

I guess that RetroPie using KMSDRM with SDL2 is not fast enough yet - this works well under Manjaro from what we've seen, and very well under X11 (even on RPIOS) where you can enable multi-threaded screen updates. Otherwise you can try Dispmanx which is usually faster on RetroPie.

**Comment by Retro1968** [comment]
> If you were only doing 20 FPS, that explains the audio issues.
> 
> I guess that RetroPie using KMSDRM with SDL2 is not fast enough yet - this works well under Manjaro from what we've seen, and very well under X11 (even on RPIOS) where you can enable multi-threaded screen updates. Otherwise you can try Dispmanx which is usually faster on RetroPie.

In the resolution 1280x1024 under RaspiOS 64 Bit I also only have 30 fps and soundproblems... so only 10 FPS more than under RetroPie. How can i enable the multi-threaded screen updates?

**Comment by Retro1968** [comment]
I have now switched to 640x512 under RaspiOS 64 bit too. As always, thanks for your excellent support Dimitris! :-)
