### ISSUE TITLE
Mac OS M1 version is damaged

### ISSUE THREAD

**Issue by vaccinemedia** [midwan/amiberry#945]
**Describe the bug**
When trying to launch you see an error saying "Amiberry is damaged and can't be opened"

**To Reproduce**
Download the package and try opening it from the applications folder

**Expected behavior**
Amiberry expected to launch

<img width="372" alt="Screenshot 2022-04-15 at 15 25 47" src="https://user-images.githubusercontent.com/10465885/163583148-c7632d28-0a3f-4610-8623-acf097131d26.png">

- OS: Mac OS 12.3

**Comment by solskogen** [comment]
This is covered in the FAQ :)
https://github.com/midwan/amiberry/wiki/FAQ

**Comment by vaccinemedia** [comment]
That did the trick! In case anyone is reading this, you need to open a terminal and cd into the /Applications folder and then run "xattr -rd com.apple.quarantine Amiberry.app"
