### ISSUE TITLE
Lotus Esprit Turbo Challenge 3 - Left shifted

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#946]
Raspberry Pi 4 running RetroPie 4.8 with amiberry (2022-04-15)(sdl2) with AmigaOS 3.2.1 (RTG) and WHDLoad Games. 
Auto-Crop is active. So far I have only noticed the problem with "Lotus Esprit Turbo Challenge 3" (WHDLoad).

After I loaded the game, the image is slightly shifted to the left. Please pay attention to the "170 KMH" at the top left. 
![leftshifted](https://user-images.githubusercontent.com/58906142/163671361-814986a0-520b-42be-b3d6-81f2bfd5f7dd.jpg)

After I entered the GUI with the F12 key and immediately exited it without having done anything there, the image is displayed normally again.
![normal](https://user-images.githubusercontent.com/58906142/163671371-7c139d39-4a6a-4a87-a195-91d32bfb62a4.jpg)

[default.zip](https://github.com/midwan/amiberry/files/8499667/default.zip)

Cheers
Retro1968

P.S: The Lotus Trilogy for AMIGACD32 has the problem too.

**Comment by midwan** [comment]
Seems like you had auto crop enabled?
There will be cases where the output is not perfect, unfortunately.
One workaround you can try is this: map a controller button to auto crop in custom controls, and use that to trigger it on demand. Perhaps that will fix it for you.

**Comment by Retro1968** [comment]
I put "Toggle Auto-Crop" on the Select button. In the game it only has an effect after I have called up the GUI with F12 and left it again immediately... That bites the mouse in the tail... ;-)

**Comment by Retro1968** [comment]
Thank you for releasing amiberry 5.1 (2022-04-17) which solved the problem. :-)
