### ISSUE TITLE
Let the mouse select the trailer options when WHDLoad games are starting

### ISSUE THREAD

**Issue by Yserra** [midwan/amiberry#947]
**Is your feature request related to a problem? Please describe.**
Hi Dimitris, 

TWO YEARS LATER. This is a followup of #730. 
Most of WHDLoad games start with a trailer screen where you select options with mouse.
I have a real USB mouse attached.
The mouse pointer doesn't move. 
It doesn't move because in almost all entries of the file whdload_db.xml, someone thought it was a good idea to put by default: 
		PRIMARY_CONTROL=JOYSTICK
		PORT0=JOY
That's not how a real Amiga worked. On real Amiga, the port 0 was in most case used by the mouse
To manually correct that issue, I have to press F12, go to the Input menu, and change Port 0: to "System Mouse"
This absolutely doesn't affect in any way the regular use of a joystick during the following game. Because the game uses joystick in PORT1. So the PORT0=JOY item was - in most case - just an annoyance. 

Yes, some games use two joysticks, so one in PORT0, but they are a minority. So, I don't understand the choice to generalize the minority at the expense of the majority. 

**Describe the solution you'd like**
The best solution would be to mention PORT0=JOY **only** when we are absolutely sure that the game really needs two joysticks.
In my opinion, if it is too complicated to list which games really need a joystick in port 0, the whdload_db.xml file should better never mention PORT0=JOY at all.
We would change Port 0 to Joystick when we really run a two joystick game ; it will be less often than having to change it for almost every game. 

**Describe alternatives you've considered**
I know what you would tell me: "just save the config of your game with your Port 0: System Mouse. Its .uae will have a higher priority than the .xml file. You won't be bothered next time"
Yes. 
BUT.
I would have to do this. On. Every. WHDLoad. Game. 
They are several thousands. And they are updated monthly. If I understand well, the goal of whdload_db.xml was to avoid the user to manually edit the configuration for every single game. But, that's what happens because of this PORT0=JOY item that is put everywhere by default in the whdload_db.xml.

**Additional context**
We already discussed this two years ago in #730 but I could never really check what you changed in the following release of Amiberry, since I kept stuck with Amiberry 3.3 in Retropie during all this time. I finally decided to upgrade to version 5.0, and I realize only now that the issue is still there. 

By the way, except this annoyance, many, many thanks for the great work you do on Amiberry. This software is absolutely fantastic. Accept my warm congratulations!

**Comment by HoraceAndTheSpider** [comment]
There are multiple solutions to this we can explore

- force users to use autoswitch mouse/joystick (easiest answer) 
- enable 'joymouse' program on whd boot to control DOS mouse with the joystick
- have the functions available via the AMOS WHD booter (can be navigated by joystick, mouse and keyboard - this might already work? try holding fire on boot up)
- have the default joystick option act as a 'hybrid' (use analogue stick 2 as a mouse, and L/R triggers as mouse buttons)

**Comment by HoraceAndTheSpider** [comment]
> It doesn't move because in almost all entries of the file whdload_db.xml, someone thought it was a good idea to put by default:
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
That's not how a real Amiga worked. On real Amiga, the port 0 was in most case used by the mouse

It's important to understand that the idea of a single-file booting game on an Amiga also isn't how a 'real' Amiga worked back in the day. This WHD booting is designed to bring a console-like experience to playing amiga games. I believe there is a misunderstanding here about what "PRIMARY_CONTROL=JOYSTICK" does - this is telling the setup to favour a single input device (say a controller) as a joystick - this is the case for the majority of games. 

I agree that we could consider PORT0=MOUSE as a change to defaults, but this would mean identifying all 2 player joystick games to override this setting, which still means a lot of work for the team.

**Comment by midwan** [comment]
@Yserra 
Besides what @HoraceAndTheSpider mentioned above, I'd like to add the following:
- The Autoswitch Mouse/Joystick option is enabled by default from v5.1 (coming soon), so this might be a non-issue in fact. With that option, it's enough to click the mouse button and it will automatically be assigned to Port 0, or press Fire1 on a joystick to assign that one back. So you can have 2 joysticks and a mouse connected, and Port 0 can switch from mouse to joystick and back, using Mouse button 1 or Fire1.
