### ISSUE TITLE
Question: How to start the Amiga CD32 Bootmenue

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#948]
Raspberry Pi with amiberry (2022-04-15)(sdl2) running RetroPie 4.8:

Under the RetroPie heading "Amiga CD32" I can successfully start and play the CD "Defender of the Crown II".
The English version is always started by default. How can I call up the CD boot menu to start the German version?

Cheers
Retro1968

**Comment by midwan** [comment]
I'm not sure - I never owned a CD32, so I don't know how that would work in real life.
Amiberry just emulates the same thing, so it depends on what the real-life equivalent method was...

**Comment by Retro1968** [comment]
49 / 5.000
Übersetzungsergebnisse
I've never owned an Amiga CD32 either... ;-)

**Comment by Retro1968** [comment]
Maybe we can get an answer here:
http://eab.abime.net/showthread.php?p=1541736#post1541736

**Comment by midwan** [comment]
OK, since this doesn't seem like an emulator issue, I'll close this case - unless something comes up that changes this, of course.

**Comment by Retro1968** [comment]
Can you check if it's an amiberry problem?

http://eab.abime.net/showthread.php?p=1541797#post1541797

There someone writes that you should press the right mouse button when the spinning disk symbol appears to set the language and then insert the CD.

**Comment by nemo93** [comment]
To select CD32 system language you have to press the **BLUE** button (aka EAST, or B on Xbox pads, Circle on PS) at boot screen. 

This means that if you run the iso/chd from EmulationStation or other frontend you'll have to **EJECT** the CD image **first** (open Amiberry GUI > Hard drive/CD > Eject > close GUI). Pick any language from the list and hit a button. Then load up your CD image again from the GUI and resume.

This may not work on the current Retropie as the CD32 nvram (`cd32.nvr`) is being stored into the `data/` dir which is owned by **_root_**. To fix that:
```
$ sudo chown -R pi:pi /opt/retropie/emulators/amiberry/data/
```

I'll add that to the list of requirements for 5.1. Thanks for pointing that out.

**Comment by Retro1968** [comment]
Thanks for the guide. I still have a problem.

When starting from the RetroPie menu, I start "Defender of the Crown II" as usual. Then I go to the menu with F12 and eject the CD." Now I can select the language as you described. I go back to the GUI and select the .cue file under "Hard Drives/CD". I go with Resume There, however, only the animation with the spinning CD is repeated again and again without it continuing.

**Comment by Retro1968** [comment]
So once I had set the language to German and then left amiberry, the language setting was apparently set as the default for all CDs that support German. So now I can start games and have the German language without having to go back to the language menu every time. :-))
