### ISSUE TITLE
amiberry 5.1 - Key binding "Quit Emulator" does not work correctly.

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#949]
Raspberry Pi 4 running RetroPie 4.8 with amiberry 5.1 (2022-04-17)(sdl2) and AmigaOS 3.2.1.

In my default.uae I assigned the "Quit Emulator" function to the "Select" button. When operating amiberry, pressing the "Select" button only exits the emulator if I previously went to the GUI with the F12 key and exited it immediately without doing anything there.

So I suspect a bug.

Cheers
Retro1968

[default.zip](https://github.com/midwan/amiberry/files/8502038/default.zip)

**Comment by midwan** [comment]
Have you tried setting the relevant option in `amiberry.conf` instead?

**Comment by Retro1968** [comment]
I haven't changed anything manually in amiberry.conf.

[amiberry.zip](https://github.com/midwan/amiberry/files/8504769/amiberry.zip)

**Comment by Retro1968** [comment]
I just saw that I used the F11 key to exit at the same time under "Miscellaneous". After I deleted the entry there, exiting amiberry works with the select button.

**Comment by Retro1968** [comment]
Crap... rejoiced too soon... the problem persists even then. It only ends with the select button after I was in the GUI.

**Comment by Retro1968** [comment]
However, exiting with F11, i.e. with the keyboard, works without any problems. The only problem is with the controller. There the GUI must first be entered and exited via F12.

I have two RPi 4. I use one with the "Action Acrace Stick" you know, the other with a PS3 controller clone. With both RPi 4, leaving does not work with the controller but with the keyboard via F11.

**Comment by midwan** [comment]
Please test with the latest from `master` and let me know if that works better?

**Comment by Retro1968** [comment]
No, unfortunately not. Only after I pressed F12 (GUI) twice did the select button work to exit amiberry. Tested on both RPi 4.

**Comment by midwan** [comment]
I can't recreate this anymore, after the above fixes.
In fact, I can even use `amiberry.conf` now and set a controller button for Quit there (instead of a keyboard key), and it will work by default on all configs that don't override it.

I tested it with a PS4 controller, used `back` as the button of choice in `amiberry.conf`, then launched Amiberry with `-G` to hide the GUI. Pressing the button Quit the emulator as expected.

**Comment by Retro1968** [comment]
Have now tried again with a newly created default.uae ... without success.

**Comment by midwan** [comment]
Where did you add the setting? Amiberry.conf or your `.uae` file?
How did you add it? From the GUI or manually?
What value did you add to the line?

**Comment by Retro1968** [comment]
Wait... I can now click the button to leave amiberry. But although I have stored the select button, he now uses the fire button for it.... I guess I'll have to see how I can solve that. he does that on both rpi 4.

**Comment by midwan** [comment]
Also make sure you get the latest version after the 2nd commit above ;)

**Comment by Retro1968** [comment]
After I installed the latest amiberry version, re-installed the amiberry.conf from the amiberry-master folder, created a new defaul.uae, removed the keybinding for "Quit Emulator" under "Custom Controls" and set under "Miscellaneous" the "Select Button" (shown there as "back-button") as "Quit Key", everything works perfectly now! Thank you Dimitris!!!

This is particularly useful when I'm lying around on the couch and playing amiga games on my big screen TV and now I no longer have to fetch the keyboard to exit amiberry every time. Now i only have to press the Select button... Perfect!

**Comment by Retro1968** [comment]
Addendum: I read in today's update description: Added new CD32 config with 8MB Fast, use that with --autoload option.
How do I enable the --autoload option?

**Comment by midwan** [comment]
It's one of Amiberry's command line options
