### ISSUE TITLE
Question: Amiberry 3.3 (on THEA500mini) - how to disable the autobooter and load config settings from the game .uae file

### ISSUE THREAD

**Issue by solarmon** [midwan/amiberry#950]
Hi,

Apologies if this is the wrong place to ask this question about THEA500mini which is running Amiberry 3.3+redquark

I'm trying to use .uae file to be able to load ADF game files. However, the only way to get THEA500mini to launch something is to create a dummy .LHA and trick it to load the custom .uae config file.

However, I've noticed that the floppy and filesystem configs don't get loaded and when I look in the Amiberry GUI configuration settings I see that it still has the filesystem settings for the WHDLoad autobooter solution.

The question is, if possible, how do I get Amiberry to disable/ignore the WHDLoad autobooter config settings and to load the game .uae configs fully? Is this an Amiberry thing, or is it an Amiberry 3.3+redquark thing?

**Comment by midwan** [comment]
This is definitely a limitation that Retro Games have imposed on Amiberry with their modifications.
The normal behavior would have been to open the GUI and do whatever you need with it, if you so wished. I'm guessing the carousel launcher is using the `--autoload` option to pass an .LHA file, which triggers the WHDBooter in turn.

I'm sorry, but I cannot help you in this case, as that modified version is not under my control. If we eventually manage to make a version of the latest Amiberry available for that platform, then you'd have the capability to use the full range of features of the emulator.

**Comment by solarmon** [comment]
@midwan 

Thanks for the response. I totally understand that the version used on THEA500mini is not under your control.

I just wanted to understand whether it was functionality that was removed from that version (whether intentionally or not).
