### ISSUE TITLE
A500 Mini - loading a .lha file prompts "volume DH0 is write protected" error message

### ISSUE THREAD

**Issue by ocean-voyager** [midwan/amiberry#951]
My apologies, I have seen similar issues to this raised before but because they do not provide a solution I have raised again in the hope someone can assist.

All of my .lha files work apart from one, which gives me an error message when I load it; “volume DH0 is write protected”.

All I can do is retry or cancel - the game cannot be played. Do you have any idea on what I need to do here please?

The game in question is this one; [https://aminet.net//game/2play/AmigaTanx-1.0](https://aminet.net/game/2play/AmigaTanx-1.0) it’s the only .lha I can find online for this game so I can't try any others. I am using a Windows 10 PC and do not know how to get into the individual files within the .lha to make permission changes and then re-save as a .lha again. I'm afraid I'm new to all this, sorry! Any advice you have is really appreciated

![volume dh0 error](https://user-images.githubusercontent.com/104194644/164674060-1fb5b8b0-8880-4f55-b0b2-d3f0a234393e.png)
!

**Comment by solskogen** [comment]
Please route problems regarding the A500 Mini to Retro Games.

**Comment by ocean-voyager** [comment]
Thanks. Have already done that, they said they were unable to comment! I've tried here because it references the Amiberry within the error message.

**Comment by wepl** [comment]
Are you using release 1.0.1 of the whdload package?
This possible fixes the issue.

**Comment by ocean-voyager** [comment]
Yes I am, as per this link; https://retrogames.biz/support/thea500-mini/whdload/

**Comment by DanBuchan** [comment]
I can't speak to this write protection problem but that aminet lha file doesn't have a whdload slave in it so I suspect whatever is in this package it isn't a whdload package so wouldn't run anyway.
