### ISSUE TITLE
P96 v3.3.0 causes problems

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#954]
Raspberry Pi 4 running RetroPie 4.8 with amiberry 5.1 (2022-04-18)(sdl2) and AmigaOS 3.2.1. RTG using picasso96 driver version 3.3.0.

Hello Dimitris,
since version 3.3.0 of the picasso96 i have had problems which i have reported to the developer of the driver in this thread.

https://forum.icomp.de/index.php?thread/2572-p96-v3-3-0-released/&postID=23889#post23890

There the developer reports that he is also aware of the problems with version 3.3.0 of WinUAE and that this would be due to an error in the uae core, so he was already in contact with Toni. But he doesn't know who to contact about the RPi/Linux version.

Can you help?

**Comment by midwan** [comment]
This is an upstream issue on WinUAE, so as soon as Toni publishes a fix for it, I can merge it back into Amiberry as well.

**Comment by Retro1968** [comment]
That sounds great. Thanks!
Are you staying in touch with Toni on this?

**Comment by midwan** [comment]
I always monitor WinUAE's repository for new changes, and merge in those that are applicable to Amiberry as soon as possible. Besides that, we're in touch with Toni in general as well, yes.

**Comment by midwan** [comment]
@Retro1968 
Can you please test with the latest commits (both `master` and `dev` have them)?
I don't see any issues with P96 3.3 when using that version

**Comment by Retro1968** [comment]
I compiled amiberry 5.2 (2022-05-14) on RaspiOS 64 bit and RetroPie 4.8 with this command: make -j4 PLATFORM=rpi4-sdl2 and can confirm that amiberry is now running correctly with the P96 v3.3.0 driver.

Thank you very much! :-)

**Comment by Retro1968** [comment]
Do you know if there is now an updated WinUAE version that accepts the P96 v3.3.0 driver? So far I haven't been able to find anything on winuae.net.

**Comment by Retro1968** [comment]
OK... just saw that you can download the source code here:

https://github.com/tonioni/WinUAE

Is there an easier way to get an updated WinUAE version... ;-)
