### ISSUE TITLE
[custom controls] either not set or not working

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#956]
**Describe the bug**
Some games do have `custom controls` defined in XML. Those are useful to bind specific keys to a pad button (eg. bind `Space` to the `X` button of your Xbox controller). Yet it happens sometimes those `custom controls` are either not being picked by Amiberry or not working.

1. **Alien Breed Tower Assault AGA** (`AlienBreedTowerAssault_v1.3_AGA_2331`) will illustrate the scenario where `custom controls` are not picked.
2. **Indy Heat** (`IndyHeat_v1.21_2436`) for the case where those controls are not properly working.

**To Reproduce**
1. Simply run any of the games above and open GUI > Custom Controls
2. In case of Alien Breed TA I can see `None` as value for all buttons.
3. Indy Heat: I can see the proper mapping this time yet the right direction is not working when I press my D-Pad right. Only that mapping is not working all other keys/buttons do work. My pad is working no problem with any other games and within the GUI.

**Expected behavior**
`custom controls` to be populated from XML and working as intended.

**Additional context**
For the record current mapping for the aforementioned games:
* [Alien Breed Tower Assault AGA](https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/blob/master/customcontrols/AlienBreedTAAGA)
* [Indy Heat](https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder/blob/master/customcontrols/IndyHeat)

Quote from @midwan: "Because instead of a hardcoded array of strings, I'm getting the actual name SDL2 reports back as a string, for the given button. So, instead of East, West, North, South, we get back A, B, X, Y for example. The order is from Button 0 and ascending, same with the axes. And regarding the layout, SDL2 uses the XBox one: North = Y, South = A, East = B, West = X"

SDL2 naming convention
```
Buttons:
a
b
x
y
back
guide
start
leftstick
rightstick
leftshoulder
rightshoulder
dpup
dpdown
dpleft
dpright
misc1
paddle1
paddle2
paddle3
paddle4
touchpad

Axes:
leftx
lefty
rightx
righty
lefttrigger
righttrigger

```
I'm running latest master e23ca569b4e3bcbe0112fc4d32302334eaa3fdd7 on Retropie 4.8 on Pi4. Buster / 32-bit / DMX. Everything (`.uae`, `.chd`, `.lha`) is therefore launched with the `--autoload` parameter.

My controller is a Xbox One bluetooth with the associated mapping defined:
[Xbox Wireless Controller.cfg](https://github.com/midwan/amiberry/files/8562669/Xbox.Wireless.Controller.txt)

**Comment by midwan** [comment]
@nemo93 
This seems to work as expected in the latest version, now that the XML is updated:

![image](https://user-images.githubusercontent.com/3877365/168420318-789c3094-275b-4d9f-9c20-09c64c7e89e9.png)

I'll test it on RetroPie separately also, just in case there's a difference when using Retroarch mapping + Custom Controls

**Comment by midwan** [comment]
Screenshot from a scenario using Retroarch (like Retropie would):

![image](https://user-images.githubusercontent.com/3877365/168420428-3d003604-09e7-4d1f-9367-20261082a0eb.png)

As you can see, the custom controls are loaded and applied from the XML. The difference with the rest of the dropdowns showing "None" is expected when using Retroarch, since in that scenario we _only_ show applied Custom Controls, not the default mapping.

**Comment by midwan** [comment]
@nemo93 
I'll close this for now, as it seems it's resolved. But feel free to test and let me know if you notice an issue I may have missed.

**Comment by nemo93** [comment]
For the record, issue with Indy Heat where some direction wasn't working was due to a bug to Xbox driver I was using. With latest [xpadneo](https://github.com/atar-axis/xpadneo) driver issue is gone!
