### ISSUE TITLE
[CD32] `centering` settings not applied

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#957]
**Describe the bug**
When running CD32 images (**CHD** format) the `auto-centering` settings (horizontal/vertical) are not being applied even when explicitly set within `amiberry.conf`, they're unchecked/disabled automatically instead of being enabled. **Note**: `autoheight/crop` setting is applied alright.

**To Reproduce**
Hereafter my current `amiberry.conf` settings:
```
default_horizontal_centering=yes
default_vertical_centering=yes
default_auto_crop=yes
default_width=720
default_height=568
allow_display_settings_from_xml=yes
```

1. do run some `.lha` with above settings > it goes smooth no problem (XML values take precedence).
2. same settings but now run CD32 images (chd) eg. Akira or Flink > `auto-centering` settings are not applied and unchecked in GUI. Just in case, I don't have any `.uae` associated for the CHDs.

**Note**: I realise I've named my CHDs after the associated `filename` found in XML. For instance: `Akira_v1.2_CD32.chd` and `Flink_v2.4_CD32.chd`. Not sure why I've done that but anyhow in XML the `auto-centering` settings are `ON` for those entries.

**Expected behavior**
Default/fallback settings to be applied as set in `amiberry.conf`.

**Additional context**
I'm running latest master e23ca569b4e3bcbe0112fc4d32302334eaa3fdd7 on Retropie 4.8 on Pi4. Buster / 32-bit / DMX. Everything (`.uae`, `.chd`, `.lha`) is therefore launched with the `--autoload` parameter.

My complete `amiberry.conf`:
[amiberry.conf](https://github.com/midwan/amiberry/files/8562930/amiberry.conf.txt)

**Comment by nemo93** [comment]
Filename of `.chd` is the culprit > renaming the file to anything different from XML fixes it. I just hit a corner case it seems. 

I'd like to keep that one open though as even in such scenario I'd expect settings to be properly applied anyway. In the case above Amiberry should have followed `allow_display_settings_from_xml=yes` and applied the settings matching the filename defined. If no match then `amiberry.conf` (default) should take precedence.

**Comment by midwan** [comment]
Is there a difference if you don't use `default_auto_crop` ?

**Comment by nemo93** [comment]
I got different outcomes today which contradict my post from yesterday... Hereafter a more rigorous analysis using filename equals to what's found in XML and another one different.

* **Akira_v1.2_CD32**.chd (does match filename from XML):
```
default_horizontal_centering=yes
default_vertical_centering=yes
default_auto_crop=yes
default_width=720
default_height=568
allow_display_settings_from_xml=yes
```
=> **result**: autocentering disabled / autoheight enabled

* **AlienBreed3D**.chd (doesn't match any filename from XML):
```
default_horizontal_centering=yes
default_vertical_centering=yes
default_auto_crop=yes
default_width=720
default_height=568
allow_display_settings_from_xml=yes
```
=> **result**: autocentering disabled / autoheight enabled

* **Akira_v1.2_CD32**.chd:
```
default_horizontal_centering=yes
default_vertical_centering=yes
default_auto_crop=no
default_width=720
default_height=568
allow_display_settings_from_xml=yes
```
=> **result**: autocentering enabled / autoheight disabled / width=720 / height=568

* **AlienBreed3D**.chd:
```
default_horizontal_centering=yes
default_vertical_centering=yes
default_auto_crop=no
default_width=720
default_height=568
allow_display_settings_from_xml=yes
```
=> **result**: autocentering enabled / autoheight disabled / width=720 / height=568

For the record the following are values from the `Akira_v1.2_CD32` entry in XML:
```
SCREEN_AUTOHEIGHT=FALSE
SCREEN_HEIGHT=400
SCREEN_WIDTH=720
SCREEN_CENTERH=SMART
SCREEN_CENTERV=SMART
```

**Comment by midwan** [comment]
The issue here is that `.chd` images trigger the CD32 auto-prefs function, not the WHDLoad one. And that does not use the WHDBooter code at all, just uses a CD32 config, any defaults from `amiberry.conf` of course, and boots your image.
