### ISSUE TITLE
SDL 2 | Path is not correctly applied when selecting a directory as a harddisk

### ISSUE THREAD

**Issue by rabejens** [midwan/amiberry#96]
When selecting a directory as a harddisk, the path is only partly applied. The Volume label however is correctly applied.

Example: I am currently using the SDL2 version as a drop-in replacement for the emulator in Amibian. My virtual hard disks are at `/root/amiga/hdd/dirs/System` and `/root/amiga/hdd/dirs/Work`. When selecting one, the volume label is correctly set to `System` or `Work`, but only `/root/amiga/hdd/` gets written to the configuration file.

**Comment by fogobogo** [comment]
without too much looking I think its currentDir which doesn't get updated to the new value at the proper place. 
A somewhat similar issue is with creating hardfiles. I (mostly) ended up with "Unable to create new file." After some state of the art debugging with `printf()'s` I figured out that somewhere in `txtPath.getText()` the path string get mangled.
However that rabbit hole was just too deep. I couldn't figure out the problem there.

**Comment by rabejens** [comment]
This not only applies to hard disk folders; it is also impossible to mount ADFs now, as the path is not correctly applied there either.

**Comment by midwan** [comment]
Looks like I broke something in the recent updates then, let me see if I can fix it...

**Comment by midwan** [comment]
Please let me know if you experience the same with the latest commit...

If so, kindly provide a sample path you're using so I can recreate it here, since it seems to work for me at this point.
