### ISSUE TITLE
[Feature] Ability to set default soundcard

### ISSUE THREAD

**Issue by danko79** [midwan/amiberry#963]
Hi, i have a RP3+ with Retropie 4.8 and amiberry 5.1 connected with HDMI but the audio with usb speaker 3.5 jack on the RPi, have a problem that i can't set the to audio output on amiberry mandatory headphones can you tell me how to do it? see the pic.

https://i.postimg.cc/htQvgh0G/amiberry-5.jpg

**Comment by solskogen** [comment]
usb speaker? As in an external sound card?

**Comment by danko79** [comment]
> usb speaker? As in an external sound card?

yes, but the problem is only with amiberry.

**Comment by solskogen** [comment]
Looks to me like SDL doesn't find your soundcard, only the internal ones on the Pi itself. Why that is, I'm not sure.

**Comment by danko79** [comment]
> Looks to me like SDL doesn't find your soundcard, only the internal ones on the Pi itself. Why that is, I'm not sure.

how can it be solved?  simply set headphones but do not know how to do

**Comment by midwan** [comment]
I have tested it with an external USB sound card, and it seemed to work fine here. Obviously, I cannot test each and every item out there, but in principal if SDL2 can open the device, it should work in Amiberry as well. Perhaps there's something going on with that device specifically (in combination with SDL2)?

**Comment by danko79** [comment]
> I have tested it with an external USB sound card, and it seemed to work fine here. Obviously, I cannot test each and every item out there, but in principal if SDL2 can open the device, it should work in Amiberry as well. Perhaps there's something going on with that device specifically (in combination with SDL2)?

It works for me too, but every time I turn on I have to select headphones in amiberry preference otherwise I don't hear anything I connected Trust Leto 2.0 USB speakers.

**Comment by midwan** [comment]
OK, now I'm confused - you say it works, but you have to change to it.
Does that option not get saved with a config?

Or do you mean you'd like to have it set to another option by default, without loading a config?

**Comment by danko79** [comment]
> OK, now I'm confused - you say it works, but you have to change to it.
> Does that option not get saved with a config?
> 
> Or do you mean you'd like to have it set to another option by default, without loading a config?

It works but have to change it every time, I don't know how to set this option by default so for solved my problem, I don't know which file to edit.

**Comment by midwan** [comment]
There is no "default soundcard" setting yet, that will come with the next release however.
For now, you can only save a `.uae` config with your preferred setting, and when loading it is should use it.

**Comment by midwan** [comment]
Wiki updated with the new option in `amiberry.conf`: https://github.com/midwan/amiberry/wiki/Amiberry.conf-options

As I mentioned above, this will be part of the 5.2 release.
