### ISSUE TITLE
Compile errors on Debian Bullseye and Buster

### ISSUE THREAD

**Issue by MichaIng** [midwan/amiberry#966]
Hey,

I'm currently building Amiberry v5.1 (`master` branch) DEB packages for DietPi and run into one fixable and one non-fixable error on Debian Bullseye and Buster, while Bookworm went through well).

One thing is:
```
error: 'string_view' is not a member of 'std'
```
and alike, which are part of C++ 17, so this can be fixed with `-std=c++17` or `-std=c++20`. Probably it makes sense to assure the requited minimum version right in the Makefile?

RPi 32-bit builds on Raspbian Bullseye go through with this, but compiling the `n2` target on Debian Bullseye and Buster fail at a later point, and I wasn't able to solve it:
```
In file included from src/jit/compemu_support.cpp:1263:
src/jit/compemu_midfunc_armA64.cpp.in: In function ‘void flush_cpu_icache(void*, void*)’:
src/jit/compemu_midfunc_armA64.cpp.in:602:3: error: ‘__clear_cache’ was not declared in this scope
  602 |   __clear_cache(start, stop);
      |   ^~~~~~~~~~~~~
```
This seems to affect 64-bit builds only, since `xu4` worked well. 

Any ideas how to solve this? Obviously, since you provide a compiled RK3399 and RPi 64-bit as release assets, which should be a very similar build.

Probably it's as of the libSDL2 v2.0.22 is built as well?

**Comment by solskogen** [comment]
`-std=gnu++17` is the default in the Makefile. Have you changed it?

**Comment by MichaIng** [comment]
I see it: https://github.com/midwan/amiberry/blob/653a212/Makefile#L307
I set additional flags by passing `CXXFLAGS='...'` as `make` argument, probably this overrides the value set in the Makefile? If so, how to better add flags?

**Comment by solskogen** [comment]
For a build system I would rather create a patch with your needed changes. What kind of additional flags do you need?

**Comment by solskogen** [comment]
As I've got no problems compiling Amiberry on Bullseye I'm wondering what you've done to your system.

**Comment by MichaIng** [comment]
As said, most likely it is related to own libSDL2(+images+ttf) builds, where I use latest v2.0.22 sources while Debian Bullseye ships v2.0.14. I guess you compile Amiberry against `libsdl2-dev`, isn't it? Probably the latest version causes issues with older/non-Bookworm libs.

> what you've done to your system

Not one system, but a set of build containers for all architectures and Debian versions. A pretty minimal Debian, of course, but as said, all 32-bit Amiberry builds and on Bookworm it compiles fine, so no obvious missing dependency or such.

**Comment by MichaIng** [comment]
So it's not the libSDL2 version itself. I build a minimal version with only DRM/KMS, GLES2 and ALSA support, no wayland or X11 or PulseAudio. I'll go through the flags. Probably Amiberry 5.1 requires some additional feature it didn't before, for 64-bit builds on Debian below Bookworm. Probably the failing code line/context gives some hint 🤔.

**Comment by solskogen** [comment]
You shouldn't get the error you get if you haven't touched the CFLAGS or CXXFLAGS. Sure you haven't set anything in the environment?

**Comment by MichaIng** [comment]
The build starts in a fresh shell, so no other environment than the passed flags. Good point, probably something else is overridden aside of the `-std=gnu++17``.
