### ISSUE TITLE
whdload_db.xml comtains duplicates

### ISSUE THREAD

**Issue by kec2** [midwan/amiberry#973]
**Describe the bug**
whdload_db.xml comtains duplicates

**To Reproduce**

These filename and sha1 has a duplicate:
BlazingGunsDemo-WHDL | 812cd51a0aa8e50aa635415367cb390b65f2fa32
AnnalsRomePL-WHDL | 7ecaf707fb785e960728c8e2161d19e804c67756
CivilizationPL-WHDL | 568c56f670fb125c2c62afca068eb48f28fa56c5
Elite2FrontierPL-WHDL | f514949714728c4df115ca31dc6c4a2afe6b30d8
Elvira2PL-WHDL | f867a54ccb6ab5d24a052369584087c092867ba6
Elvira3WaxworksPL-WHDL | f4a54503ea4866a53ea54b28bc6a6f8c187b4969
GenghisKhanPL-WHDL | 0d03499632f172da76f98ad7becfa01f251c466f
Kingdoms2EnglandPL-WHDL | fc9e40c84de72dd52340e6a8ec7eb39c0aa70be5
ManagerPL-WHDL | 4552732a3f31808cce7531031c55ba6924a319a7
NobunagaAmbitionPL-WHDL | c51f1943b51083f23bd7f3bbb1a9e33e6e93a345
PatricianPL-WHDL | 1309b4e20b7f4a809037569490129ccfe74ba3cd
RailroadTycoonPL-WHDL | aa279773c0402fafba66184ba1edcba63cffaea3
SettlersPL-WHDL | eb1fcadc1b3e58b5c1f2c3ba923460c87b2dede7
StockMarketPL-WHDL | 115752316f4969956f4b7b1ade8d3d024fdf1a4f

**Expected behavior**
I did'nt expect duplicates

**Comment by midwan** [comment]
@kec2 
Thanks - but this should really be reported to the source repository, so it can be addressed: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder

@HoraceAndTheSpider

**Comment by kec2** [comment]
I have create a bug her: https://github.com/HoraceAndTheSpider/Amiberry-XML-Builder
Feel free to close this.
