### ISSUE TITLE
`default_whd_quit_on_exit=yes` returns to AmigaDOS prompt

### ISSUE THREAD

**Issue by twojstaryzdomu** [midwan/amiberry#976]
**Describe the bug**
`default_whd_quit_on_exit=yes` returns to AmigaDOS prompt

**To Reproduce**
Steps to reproduce the behaviour:

1. Set `default_whd_quit_on_exit=yes` in amiberry.conf. Ensure no other option by that name exists.
2. Run a WHDLoad demo. Note the WHDLoad quit key.
3. Press the quit key.
4. Amiberry does not quit emulation, returning to AmigaDOS. 

**Expected behavior**
Amiberry quits as expected.

**Screenshots**
AmigaDOS error reads:
amiberry "DH0:C/AmiQuit: Unknown command"

**Desktop (please complete the following information):**

- OS: Raspbian Buster
- Amiberry v5.2, commit 9c76e03b8ad4fae001e4ff23ba3b6444faf30950
**Additional info**
Only WHDLoad binary found in DH0:C. No AmiQuit binary can be found at the AmigaDOS prompt.

**Comment by midwan** [comment]
The required file (`AmiQuit`) is part of the WHDBooter now, but I didn't include it inside the `boot-data.zip` file as well, which is the fall-back booter (triggered when a title was not recognized from the XML). I'll add that to the file, but in the meantime you can do the same thing also (just add `AmiQuit` inside the zip file's "C" directory).

**Comment by midwan** [comment]
Should be fixed now, with the commit above. I'll check with @HoraceAndTheSpider to make sure this is also fixed upstream.
For now, you can replace the `zip` file with the one from the repo, if you didn't already copy the `AmiQuit` binary inside it earlier.
