### ISSUE TITLE
Set default screen reslution

### ISSUE THREAD

**Issue by kec2** [midwan/amiberry#978]
**Is your feature request related to a problem? Please describe.**
When I play WHDLoad games I have to set the screen resolution from 800*600 to 1920*1080 in GUI to get a crisp image every time.

**Describe the solution you'd like**
I would like a setting in amiberry.conf where I can set the default screen resolution.
In the GUI Display -> Amiga Screen -> "Fullscreen" should maybe be "Resolution".
I have just checked the Wiki and can't find anything.

**Describe alternatives you've considered**
Going into AmiBerry GUI a setting the screen resolution and save the configuration.

**Comment by nemo93** [comment]
Hi. Can you please provide details about your environment please? 

Meanwhile I can only recommend you to have a look at [the doc](https://github.com/midwan/amiberry/wiki/Amiberry.conf-options) provided there are quite a lot of options to ensure games are running as they should on any screen.

Feature like _[autocrop](https://github.com/midwan/amiberry/wiki/Amiberry.conf-options#default_auto_crop)_ will attempt to resize the screen to best possible values automatically. 

You have the ability to set exact width/height values with the [corresponding settings](https://github.com/midwan/amiberry/wiki/Amiberry.conf-options#default_width). 

If you're on Retropie with default setup then an external XML file will do the work for you and resize screen size properly (amid other stuff). 

With other environments you also get the _[fullscreen](https://github.com/midwan/amiberry/wiki/Amiberry.conf-options#default_fullscreen_mode)_ option.

**Comment by kec2** [comment]
My environment is RetroPie v4.8.1
Raspberry Pi 3.
AmiBerry version is: 5.2, compiled and linked against SDL2 v2.0.10.

I appreciate you links.

I'm not sure which external XML you refer to.

I know that I can go into the GUI and change the resolution and save the configuration for each WHDLoad game. 
But I can't set a default value in the amiberry,conf file for all games.

Autocrop is that was is called Auto Height in the GUI?

**Comment by midwan** [comment]
The solution to this could be quite simple:
- Don't use Full-screen mode, but Full-Window mode instead
- Set the desired resolution on the Linux system underneath

That will cause Amiberry to use the configured resolution and resize the output screen to it (keeping the aspect ratio or not, depending on your options), for all games.
