### ISSUE TITLE
Latest git Amiberry-SDL2 directory bug

### ISSUE THREAD

**Issue by pawelomega** [midwan/amiberry#98]
Just compiled and tested latest git and new bug:

When "add directory" and I want select path to my harddisk folder then amiberry still remember path saved in adfdir.conf and can't select file from my folder. always remeber and showing this path:
  
"path=/opt/retropie/emulators/amiberry-sdl2/" (for example).

That same problem persist when select game from folder "/home/pi/retropie/roms/amiga/adf/" and select "game.adf" and click ok then i still see in floppy directory path  "/opt/retropie/emulators/amiberry-sdl2/".

I think it's global problem with saving proper path location and reading data from stored configs with proper location of files.  Now it completely doesn't work

**Comment by midwan** [comment]
Sorry about this, I completely missed it in my last test as it only occurs when creating a new config.
It should be fixed now.
