### ISSUE TITLE
SDL2 | Guisan Makefile improvement

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#99]
diff --git a/Makefile b/Makefile
index ad83a91..9730899 100644
--- a/Makefile
+++ b/Makefile
@@ -23,7 +23,7 @@ PROG   = $(NAME)
 all: guisan $(PROG)

 guisan:
-       cd src/guisan && make all && cd ../..
+       $(MAKE) -C src/guisan

 #DEBUG=1

**Comment by solskogen** [comment]
`diff --git a/Makefile b/Makefile
index ad83a91..9730899 100644
--- a/Makefile
+++ b/Makefile
@@ -23,7 +23,7 @@ PROG   = $(NAME)
 all: guisan $(PROG)

 guisan:
-       cd src/guisan && make all && cd ../..
+       $(MAKE) -C src/guisan

 #DEBUG=1`

This looks perhaps better...

**Comment by midwan** [comment]
@solskogen 
Indeed it does, thanks! :)

**Comment by solskogen** [comment]
Dammit, it does not. 
But I think you've got the idea.
